### ISSUE TITLE
https://igov.org.ua/about - імена/прізвища мають бути українською мовою

### ISSUE THREAD

**Issue by Maximaximum** [e-government-ua/iForum#1]
На сторінці імен волонтерів, що беруть участь в проекті https://igov.org.ua/about, більшість імені написані російською. Всі імена мають бути українською.

**Comment by poremchuk** [comment]
Чому так котигорично "мають бути написані українською"? Хоче людина аби його ім'я було на російській - це його право. То ж не офіційний документ.

**Comment by Maximaximum** [comment]
А хто вам сказав, що людина "котигорично" хоче, аби її ім'я було російською?

Мене, наприклад, не питали - і без мого дозволу якийсь розумник власноручно
переклав мої ім'я-прізвище російською. Хто дав таке право - незрозуміло.
Звідки цей розумник взяв, що його переклад - правильний, теж не зрозуміло.

 І я не один такий, даю гарантію.

23 вересня 2015 р. 10:45 Evgeniy Poremchuk <notifications@github.com>
написав:

> Чому так котигорично "мають бути написані українською"? Хоче людина аби
> його ім'я було на російській - це його право. То ж не офіційний документ.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/1#issuecomment-142521251>
> .
>



-- 
*Не Україна для нас, а ми для України!*

*Дмитро Мирон*

**Comment by bvv4ik** [comment]
@Maximaximum я категорически против, чтоб мне указывали - на каком языке писать мне свою ФИО!

@poremchuk 100% прав - это не государственній документ, респект! 

П.С.: не надо ссорить людей(и так хватает проблем в стране)...
Ваши убеждения прошу проявлять в более толлерантном режиме...

**Comment by tsymbaliuk** [comment]
Як же задовбали розумники, які перекладають прізвища з української на будь-які інші мови. Моє прізвище російською пишеться як Цымбалюк, англійською Tsymbaliuk, натомість понаписують Цимбалюк (рос.) або Cymbaluk, Tsymbalyuk, Cymbalyk, ... Потім не можуть за прізвищем нічого знайти. Із вимогою писати всі прізвища українською погоджуюся і всіляко підтримую, як і назви міст мають українською бути.

**Comment by poremchuk** [comment]
Що за hollywar, хлопці ? То всього навсього сторінка подяки від core-team учасників волонтерам. Не згодні з розміщенням свого прізвища там чи з тим як прізвище написане - з'яжіться, наприклад, з Володьою (@bvv4ik) він виправить. Справ то менше ніж розмов по сабжу.

**Comment by AlexYurov** [comment]
1. Погоджуюсь з твердженням, що всі імена повинні бути написаними однією мовою.
2. З попереднього випливає, що необхідно обрати єдину мову для написання. Варіант "державною мовою" має раціональні переваги: можна використати паспортні дані (попереджуючи потенційні коментарі - не усі громадяни України мають двомовні паспорти)
3. Опційно пропоную дублювати всі імена латиницею відповідно до правил транслітерації, розробрених ще в 90-х і використовуваних в закордонних паспортах.
4. Пропоную застосувати вищевказані правила до усієї документації або працювати виключно з англомовною документацією, що значно спростить потенційні можливості співпраці із закордонними учасниками проекту

**Comment by poremchuk** [comment]
@AlexYurov , якщо будете цим займатись - чому би і ні.

**Comment by AlexYurov** [comment]
@poremchuk Чим саме ви пропонуєте мені займатись, введенням паспортних даних?

**Comment by VadymVolos** [comment]
Це правила хорошого тону, коли на сайті написано все однієї мовою.
Це репутація компанії. Тому я так само кажу що все на сайті повинно бути однією мовою.
Якщо автор іноземець, то в дужках можна написати ім'я його рідною мовою.

**Comment by katebutenko** [comment]
>>Погоджуюсь з твердженням, що всі імена повинні бути написаними однією мовою.
не погоджуюсь. У ситуації, яка склалась в Україні, напис власного імені тою чи іншою мовою може бути принциповим моментом. 
Мені от пофігу, але є такі люди, яким не все одно. Тому вважаю, що це повинно бути за бажанням.

До речі, на сайтах деяких стартапів навіть нікнейми замість імен. І нічого, дуже затишно виглядає :)

Можу перекласти ваші імена-фамілії так, як ви хочете і закоммітити на вебсайт. Пишіть у Slack katebutenko.

**Comment by Maximaximum** [comment]
Підтримую @AlexYurov і @VadymVolos: проект робиться для громадян України, в першу чергу. Не розумію, чому не можна написати всі імена українською мовою. Всі громадяни мають український паспорт, в якому ім'я вказано українською.

В крайньому разі, пропоную такий варіант: всі імена українською, а для тих хто явно попросить, щоб його ім'я було іншою мовою - додатково іншою мовою.

Але не так, як зараз, що всіх написали російською - і тільки для тих, хто явно просить, роблять винятки.

**Comment by poremchuk** [comment]
Прошу адміністрацію IGOV прийняти рішення по цьому питанню і закрити таск.

2015-09-25 13:29 GMT+03:00 Maksym Kobieliev <notifications@github.com>:

> Підтримую @AlexYurov <https://github.com/AlexYurov> і @VadymVolos
> <https://github.com/VadymVolos>: проект робиться для громадян України, в
> першу чергу. Не розумію, чому не можна написати всі імена українською
> мовою. Всі громадяни мають український паспорт, в якому ім'я вказано
> українською.
>
> В крайньому разі, пропоную такий варіант: всі імена українською, а для тих
> хто явно попросить, щоб його ім'я було іншою мовою - додатково іншою мовою.
>
> Але не так, як зараз, що всіх написали російською - і тільки для тих, хто
> явно просить, роблять винятки.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/1#issuecomment-143183162>
> .
>



-- 
З повагою, Поремчук Євгеній Володимирович
Електропошта: e.poremchuk@gmail.com
Skype: aisogroup

**Comment by bvv4ik** [comment]
принимаю решение:
- все кто на этой странице хотят свои ФИО на любом языке (включая английский) - пишут мне в скайп (belyavtsevw) - обязательно напишем/заменим на том языке на котором попросят!

П.С.: неверно утверждение, что "зараз, що всіх написали російською - і тільки для тих, хто явно просить, роблять винятки.". Пишут только на том языке, на котором предоставляют свои ФИО, и даже ни кто не пытался переводить на другой.

П.С.С.: учитывая толерантную позицию коллектива разработки портала(и мою лично) - мы ни в коем случае не будем поддаваться "радикальным и ультра-националистичным идеям"! (в конце концов мы стремимся в Европу, где вообще немыслимы такие категории требований) Портал хоть и обеспечивает предоставление государственных услуг, но сам не является государственным и государство на него не дает ни копейки. А данная "страница благодарности" вообще является "государством в государстве", т.к. там участники далеко не только граждане Украины, а Сингапура, Израиля, США, Канады, Бельгии и т.д. и потому там все будет так, как пожелают этого сами те люди, кто там представлен (в отношении их ФИО)

тема закрыта!

**Comment by Maximaximum** [comment]
Твердження "Пишут только на том языке, на котором предоставляют свои ФИО, и даже ни кто не пытался переводить на другой." неправдиве, оскільки я нікому не давав своїх імені та прізвища російською мовою.

**Comment by VadymVolos** [comment]
Шановні Друзі, на майбутнє давайте введемо правило, перед тим як когось додавати, той хто додає повинен запитати у автора. Якщо у автора не запитували за замовченням пишемо українською. 

Максим, напишіть будь ласка Володимиру в скайп щоб він виправив.

**Comment by VadymVolos** [comment]
Шановні Друзі! @bvv4ik залишилось відкритим запитання по місту. 
Якось не гарно коли і Київ и Киев, Чернігів і Чернигов... 
З боку при перегляді сторінки виглядає якось безграмотно.
