### ISSUE TITLE
971911778

### ISSUE THREAD

**Issue by 971911778** [e-government-ua/iForum#100]
Добрый день!
Моя заявка на оформление субсидии зарегистрирована 21.10.2015 г. под № 10089041.поданная в Саксаганский район.
17.11.2015 пришел ответ на почту, что моя заявка обработана и "Розмір субсидії вказаний у файлі, який прикріплено до цього листа". Но письмо пришло без вложения. Как быть?
Спасибо! 
Мой электронный адрес 971911778_v@mail.ru

**Comment by dmitrijzabrudskij** [comment]
добрый день
выслал на почту решения а назначении субсидии
объяснил району как нужно правильно крепить файлы - так что на Вашем примере они уже научились:)
спасибо за сигнал!

**Comment by 971911778** [comment]
Добрый день! Спасибо за содействие, но ,увы, оба файла не читаемые, скан копии со струйного принтера сделаные в плохом качестве, кроме подписи и печати ни чего.  Помогите!

**Comment by dmitrijzabrudskij** [comment]
эх...
запросил новые сканы. вышлю когда получу

**Comment by 971911778** [comment]
Спасибо огромное!

**Comment by 971911778** [comment]
Доброе утро! Сканкопии справок на субсидию так и не получила??? Можно ли надееться на то, что я их получу???

**Comment by dmitrijzabrudskij** [comment]
доброе утро.
я запросил у них новые сканы когда последний раз тут отвечал. пока не прислали - отправлю как только будут

**Comment by 971911778** [comment]
Спасибо, получила.


>Среда, 25 ноября 2015, 0:24 -08:00 от dmitrijzabrudskij <notifications@github.com>:
>
>доброе утро.
>я запросил у них новые сканы когда последний раз тут отвечал. пока не прислали - отправлю как только будут
>—
>Reply to this email directly or  view it on GitHub .


С уважением,

971911778_v@mail.ru
