### ISSUE TITLE
Пришло письмо о выполнении, но без вложения

### ISSUE THREAD

**Issue by Dimchi** [e-government-ua/iForum#101]
Добрый день,

Пришло письмо:
"Ваш запит успішно оброблено.
Електронна копія довідки підписана ЕЦП знаходиться в додатку до цього листа."

Но письмо без вложений, к сожалению. Номер заявки 10706093.

А также, кнопка в письме "Відправити" не корректно работает: при нажатии открывается браузер с формой идентификации
"«https://igov.org.ua» запрашивает имя пользователя и пароль. Сайт сообщает: «Activiti REST API»". Ни один логин\пароль не подходит.

Спасибо Вам за развитие этой системы. Надеюсь, мой отзыв будет Вам полезен.
С уважением, Дмитрий

**Comment by kurbpa** [comment]
@Dimchi 
Добрый день.
К огромному сожалению пока идет реформа по перводу МВД в полицию у коллег из МВД нетактуального ЭЦП для заверения этой справки. Поэтому временно не отправляют.

С кнопкой "Відправити" разберемся - спасибо за сигнал !
