### ISSUE TITLE
Субсидии Кривой Рог

### ISSUE THREAD

**Issue by kocuperdyk** [e-government-ua/iForum#102]
Добрый день. Портал не обслуживает жителей г. Кривой Рог. Заполнены все поля заявки на оформление субсидии. "Подать заявку" - реакции нет, к сожалению. Спасибо.

**Comment by dmitrijzabrudskij** [comment]
добрый день.
Кривой Рог тут ни при чем - проверьте все поля заявки (поле либо будет подсвечено красным либо будет ошибка в самом верху)
