### ISSUE TITLE
Оформлення та видача паспорта громадянина по досягненні 16-річного віку

### ISSUE THREAD

**Issue by dralex0575** [e-government-ua/iForum#103]
При попытке внести данные по 
Область: Дніпропетровська
Місто: Дніпропетровськ
В поле *Район м. Дніпропетровськ, у якому зареєстрована особа, яка буде отримувати паспорт: фигурирует только Бабушкиснкий. Почему?

**Comment by Koffeek** [comment]
@dralex0575
На данный момент услуга проходит обкатку на Бабушкинском районе. С 25.11 подключаются Кировский, Жовтневый, АНД. Остальные вероятнее всего с 1 декабря. Спасибо, за отзыв.
