### ISSUE TITLE
Отказ в выдаче справки о доходах физ. лица (налоговая)

### ISSUE THREAD

**Issue by Ksellos** [e-government-ua/iForum#104]
Заявка: 15814745.
Сегодня, при обращении в Левобережную ОГНС г. Днепропетровска, которую я выбирал при заказе справки, в выдаче справки отказали, ссылаясь на ее отсутствие: "нам ничего не приходило".
Корме того, сотрудница ГНС настойчиво предлагала заполнить бланк заявления установленного образца для получения данной справки, хотя определенной формы такого заявления не установлено и оно подается в произвольной форме.

**Comment by dmitrijzabrudskij** [comment]
Вы точно заказывали справку о доходах? я не вижу по этому номеру заказа от вас
и заявление они таки требуют - оно приходит вам на почту при заказе услуги. так что можете его заранее заполнить и принести уже заполненное в налоговую

**Comment by Ksellos** [comment]
Отримання довідки про доходи фізичних осіб (https://igov.org.ua/service/655/general).

Заявление у меня уже было с собой готовое:
Лівобережна об'єднана державна податкова інспекція м. Дніпропетровська
Головного управління ДФС
у Дніпропетровській області
пр. Газети «Правда», 95-А, м. Дніпропетровськ
[ПІБ]
[РНОКПП]
[Адреса]
ЗАЯВА	
Прошу надати мені відомості з Державного реєстру фізичних осіб – платників податків про суми виплачених доходів та утриманих податків/джерела виплачених доходів та утриманих податків за період з 1 січня 2014 р. по 31 грудня 2014 р. для оформлення субсидії на житлово-комунальні послуги.
ЗАЯВА	
Прошу надати мені відомості з Державного реєстру фізичних осіб – платників податків про суми виплачених доходів та утриманих податків/джерела виплачених доходів та утриманих податків за період з 1 січня 2014 р. по 31 грудня 2014 р. для оформлення субсидії на житлово-комунальні послуги.
[Дата] [Підпис]

Но им наверное от руки и кровью подписанное надо...

**Comment by dmitrijzabrudskij** [comment]
так справку выдали в итоге или еще актуально ее получение? если актуально, подайте пожалуйста новую заявку и скиньте сюда ее номер - я лично проконтролирую чтобы до левобережной налоговой все дошло

**Comment by Ksellos** [comment]
Заявку мою они таки получили.
Сегодня забрал справку.
Спасибо.
