### ISSUE TITLE
Вопрос по заявке на субсиди

### ISSUE THREAD

**Issue by WalterRWJ** [e-government-ua/iForum#105]
Здравствуйте!
Возникло несколько вопросов во время заполнения заявки:
1. Поле "Тип субсидії" отмечено как необязательное к заполнению, но на что оно влияет?
Если субсидии нужны на оплату и жилищно-коммунальных услуг, и газа, то нужно подать две заявки с разными указанными типами субсидии?
2. "Період, за який Ви заповнюєте декларацію" - по умолчанию указан период за 2014-й год. Его не менять?
3. Суммы доходов нигде указывать не надо?
4. "Інформація про витрати на придбання майна, товарів або оплату послуг на суму, що перевищує 50 тис" - если их не было, то что написать?

И, собственно, основной вопрос, который почти сразу возник и который не касается непосредственно айГов:
Я живу в частном доме с еще одним человеком, наш общий оф. доход на данный момент - 1300 грн. Никто не поверит, что мы живем на эти деньги.
За прошлый год у меня сложная структура доходов: з/п то была, то ее не было, она была и черной, и серой, и белой. Были доходы от продажи личного имущества, от разных подработок, от аренды жилья, от получения призов и т.д.
Возникнут ли у меня после или во время оформления заявки на субсидию проблемы с фискальной службой? Потребуют ли уплаты подоходного налога и т.п.?

Спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день
1. выбирайте "на оплату коммунальных услуг"
2. если будет за прошлый год, то Вам не нужно будет никуда ходить - соцзащита сама в налоговой возьмет данные о доходах. период сделан выбираемым для тех людей, у которых за последнее время сильно снизились доходы - тогда они выбирают период "последние 3 месяца" и приносят справки о доходах с работы
3. не нужно. сами вытянут
4. "не было"

вопросов не возникнет - субсидия назначается на основании официально уплаченных налогов - проверять Вас на честность в уплате налогов не будут:)

**Comment by WalterRWJ** [comment]
Просто у нас неофициальных доходов раза 3 больше, нежели официальных.
Не будут ли требовать уплаты подоходного налога?
Есть у меня такое опасение, учитывая, в какой стране живем.

**Comment by ChernyakovaYuliya** [comment]
Здравствуйте! При оформлении субсидии, выходит что услуга не распространяется на нашу область. Мы Донецкая обл.м.Вугледар, терри-я Украины, как Волноваха - военный городок. Сами понимаете живем в экстремальных условиях и все стоит дороже чем в остальных обл. Украины. Когда мы сможем оформлять субсидии??? Заранее спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день
хотим в ближайшее время запуститься по всей стране - следите за новостями:)
