### ISSUE TITLE
Статус "необхідно уточнити дані"- что делать? Третий раз задаю вам вопрос, ответьте, наконец!

### ISSUE THREAD

**Issue by nadiarum** [e-government-ua/iForum#106]
Что делать, если после подтверждения, что я подала заявку на субсидию от admin@igov пришло письмо с текстом "необхідно уточнити дані" и при запросе статуса появляется тоже этот текст???

**Comment by dmitrijzabrudskij** [comment]
уточнение данных еще не работает - район отправляет эти запросы ошибочно. подскажите номер заявки и район, куда подавали заявку - попробуем выяснить на каком она этапе

**Comment by nadiarum** [comment]
Ура. Заявка 16408869, Соломенский район.

**Comment by dmitrijzabrudskij** [comment]
@OlgaKhomenko подключитесь пожалуйста

**Comment by OlgaKhomenko** [comment]
Ваша заявка была оформлена корректно, для оформления субсидии необходимо прийти в Управление соцзащиты и поставить подпись. 
Если есть вопросы, просьба обращаться в Управление соцзащиты (они работают с заявками граждан), я не обрабатываю заявки и ответить на все Ваши вопросы не смогу.

**Comment by nadiarum** [comment]
Ольга, спасибо за объяснение.
Насколько я понимаю, приходить в отделение и ставить подпись нужно будет тогда, когда мне придёт подтверждение на электронную почту о том, что субсидия назначена, верно? 
А сейчас мне ничего делать не нужно, никакие данные уточнять не требуется.
Если я неправа, пожалуйста, исправьте меня.
С уважением,
Надежда

Отправлено с iPad

**Comment by OlgaKhomenko** [comment]
В Киеве каждый район принимает решение самостоятельно как они будут обрабатывать заявки, которые поступают с портала. На Соломенке было принято решение, что подпись необходимо ставить до начисления субсидий. Ссылаются они на то, что Министерство соцполитики сделало услугу по субсидиям в электронном виде, где все равно предусматривается живая подпись гражданина, поэтому явится в Управление необходимо, но не нужно стоять в очереди.

**Comment by nadiarum** [comment]
Спасибо. Было бы неплохо информировать об этом заявителя в письме.

Отправлено с iPhone

**Comment by dmitrijzabrudskij** [comment]
@nadiarum 
скоро не нужно будет такое уточнение в письме - все районы по всей стране будут работать одинаково с 0 визитов. у Вас, к сожалению, другая ситуация - Вы попали в первую волну клиентов, когда еще присутствует самодеятельность районов

**Comment by nadiarum** [comment]
Дмитрий, но пока ведь нужно. Я оставалась в неведении, а моё заявление- без рассмотрения с 13/11. Нужен результат, а не процесс, верно? Кстати, сегодня заезжала в Собез, или как он там, чтобы поставить подпись и дико обрадовалась, что смогла это сделать в отдельном кабинете без очереди, потому что то, что творится внутри ( толпы измученных людей в тесном помещении, без кресел и лифтов)- ужасно. 
Спасибо большое за то, что облегчаете людям жизнь.
