### ISSUE TITLE
добавлення міст

### ISSUE THREAD

**Issue by dimaferneha** [e-government-ua/iForum#108]
Коли буде добавлено м.Вінниця (Вінницька обл.) ?

**Comment by Koffeek** [comment]
@dimaferneha 
Місто буде добавлено тоді, коли його влада буде готова до впровадження послуг за допомогою iGov

**Comment by dimaferneha** [comment]
я можу їх якось поквапити ??  тому що вони самі нічого не будуть робити!

**Comment by Koffeek** [comment]
Долучайтесь до волонтерів, заповнивши форму на  https://docs.google.com/forms/d/1w-BR01CSicvhWSXb36CiRjHCwvp-vyPuTHBaWw1iW4U/viewform Там будуть більш детальні інструкції. Дякую.

**Comment by dimaferneha** [comment]
долучився
