### ISSUE TITLE
Оформление субсидий

### ISSUE THREAD

**Issue by DenisDnepr91** [e-government-ua/iForum#109]
Добрый день, при оформлении субсидий, после заполнения всех полей не срабатывает кнопка "Заказать услугу".
Браузер Chrome
Ранее на данном сайте сложностей с заказом услуг не было, только вот с этим сервисом.
Почему так?

**Comment by solokha-o** [comment]
Добрый день!
Воспользовался услугой iGov, подал заявку на субсидию
уже 20 день, ответ так и не пришел
можно узнать в чем может быть причина?
Статус заявки 
03.11.2015 09:23	Ви подали заявку на послугу Київ - Отримання субсидії на оплату житлово-комунальних послуг!. Cтатус: Заявка подана
Статус не менялся с самого начала когда подал 
Ваша заявка 12881897 прийнята!
Киевская область, г. Буча

**Comment by dmitrijzabrudskij** [comment]
добрый день!

@solokha-o попробуйте позвонить в район уточнить состояние заявки: 045-97 4-99-05
@DenisDnepr91 проверьте заполнение всех полей заявки - скорее всего где-то вместо цифр ввели буквы

**Comment by solokha-o** [comment]
Набрал по следующему номеру 045-97 4-99-05 и сотрудники даже не в курсе работает ли вообще у них эта услуга. Можно как то разобраться с этим вопросом?
