### ISSUE TITLE
соцпомощь при рождении ребенка

### ISSUE THREAD

**Issue by Marikoshka** [e-government-ua/iForum#11]
Здравствуйте! В разделе о назначении соцпомощи при рождении ребенка не загружаются запрашиваемые копии ИНН и св-во о рождении  ребенка - кнопка "выбрать файл" не активна...Пробовала с разных компьютеров - все равно без результатов.. Это можно как-то исправить? ведь молодым мамам реально просто некогда ходить за справками и стоять в очередях -  сайт igov.org.ua реальная находка - вот бы только заработала возможность загрузки документов, чтоб можно было завершить операцию. Надеюсь на вашу отзывчивость!

**Comment by dmitrijzabrudskij** [comment]
файлы нормально загружаются. подскажите свою версию браузера и ОС, чтобы проверили тестировщики

пс: у делал в фф на 7й винде

**Comment by Marikoshka** [comment]
О, спасибо за подсказку - дело было в браузере! я заходила ОС винда7 через Оперу, а попробовала Гугл Хром - проблема загрузки документа пропала!!!!! Но у меня появился еще один вопрос - в заявке просят ввести номер карты банка для перечисления средств, но в банке мне сказали, что под социальные выплаты открывается новая карточка - выходит, пока я не открою карту и не буду знать ее номер - не могу полноценно заполнить заявку? или все-таки указывать номер любой существующей банковской карты? СПАСИБО большое за ответ!

**Comment by dmitrijzabrudskij** [comment]
да, карта нужна реальная. но некоторые банки (Приват например) в случае, если вы дадите неправильный номер карты, зачислит эти деньги на ваш текущий счет и потом переведт их н социальную карту, когда вы за ней подойдете в отделение

**Comment by Marikoshka** [comment]
я как раз клиент Приватбанка, значит в заявке указываю номер существующей универсальной карты, а потом просто пойду оформлять социальную. Спасибо!
