### ISSUE TITLE
Оформление субсидии

### ISSUE THREAD

**Issue by ValentinMix** [e-government-ua/iForum#110]
Здравствуйте! После проверки заявки приходит письмо следующего содержания:
Причина: Ваша заява оформлена неналежним чином, а саме: не заповнені поля : -гаряча вода,; - газ. - вивіз побутового сміття; -№ серія свідоцтво про народження дитини 
В этих графах отметил "не користуюсь", а № серія свідоцтво про народження дитини вообще в формах нигде не указано. отправлял заявку два раза - ответ один и тот же.

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой это район и какие были номера заявок?

**Comment by ValentinMix** [comment]
Заявка 19579098, 19263440, район Соломенский города Киева.

**Comment by annastolbova** [comment]
Заявки закриті, 
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
