### ISSUE TITLE
заявка №0-18829236 статус уточнение данных

### ISSUE THREAD

**Issue by akatsia** [e-government-ua/iForum#111]
подскажите пожалуйста каких данных? чего не хватает? какие дальнейшие шаги?спасибо

**Comment by dmitrijzabrudskij** [comment]
добрый день
уточнение данных пока не работает. подскажите пожалуйста что это была за услуга и какой район выбирали при подаче?

**Comment by akatsia** [comment]
оформление пособия по беременности и родам бабушкинский район днепропетровск

**Comment by GrekD** [comment]
погоджено
