### ISSUE TITLE
Карта на якій буде показано, які послуги доступні в даній області 

### ISSUE THREAD

**Issue by vladik1996** [e-government-ua/iForum#112]
Потрібно зробити карту України з доступними послугами. Наприклад, мені цікаво які послуги доступні в моїй області.

**Comment by dmitrijzabrudskij** [comment]
1. зайдите на портал https://igov.org.ua/
2. нажмите на стрелочку в поле для ввода поискового слова
3. выберите ваш регион
4. цель достигнута - вы видите услуги по вашей области:)

**Comment by vladik1996** [comment]
Дякую) Не зовсім інтуїтивно зрозуміла стрілочка, можливо краще під полем вводу зробить "Розширений пошук"
