### ISSUE TITLE
Заявка на субсидию. Нет ответа!!! 

### ISSUE THREAD

**Issue by ValerijL** [e-government-ua/iForum#114]
Здравствуйте! Открыл заявку здесь 15 дней назад. Её содержание:"Здравствуйте! Подскажите, пожалуйста, заявку на оформление субсидии подал 11.10.15. На почту пришло письмо о том, что ответ будет дан в течении 20 дней. При проверке статуса пишет: взять в работу (в работе). Прошло уже 20 дней, а ответа нет. Номер заявки: 7786697. Город Днепропетровск, район Индустриальный."
С момента оформления заявки на субсидию уже прошло 33 рабочих дня. Реакции ноль как со стороны соц. служб так и со стороны сайта Igov. Хоть напишите куда звонить, что делать. Статус заявки до сих пор тот же: "Взяти в роботу (у роботi)".
Почта: loevskij@gmail.com.
Ответьте, пожалуйста!
И как предложение: при оформлении заявки укажите, что по истечении 20 дней звоните по тел. соответствующего отдела (контактного лица) соответствующей службы района, города и т.п.

**Comment by dmitrijzabrudskij** [comment]
добрый день
Ваша заявка еще в работе у района. Нам дозвониться до них не удалось при Вашем прошлом обращении - попробуйте, пожалуйста, по телефону 056 725-47-41
Насчет отправки телефонов после подачи заявки - уже готово в следующей версии, скоро выставим
