### ISSUE TITLE
Пропажа заявки на субсидию

### ISSUE THREAD

**Issue by Pensioner-P1** [e-government-ua/iForum#115]
При посещении Самарского исполкома, выясняется что номера заявки на субсидию они не видят. Как может такое быть? Днепропетровск.
[субсидия-статус.pdf](https://github.com/e-government-ua/iForum/files/44735/-.pdf)

**Comment by dmitrijzabrudskij** [comment]
Ваша заявка у них в работе еще - решение по назначению еще не пришло. Как только будет - они отправят его копию в ответе на заявку. Вы можете также сами проверять статус по их телефону 056 728-77-06

**Comment by Pensioner-P1** [comment]
Спасибо!!
