### ISSUE TITLE
Заявка на субсидию

### ISSUE THREAD

**Issue by oleglantuh** [e-government-ua/iForum#116]
Здравствуйте, 

заявка на субсидию № 20662309 (днепровский район г. Днепродзержинск), статус "Запит на уточнення даних".

Подскажите пожалуйста, какие дальнейшие действия от меня необходимы?

**Comment by dmitrijzabrudskij** [comment]
добрый день!

Ваша заявка принята в работу. Район пришлет ответ на почту по результату ее рассмотрения

**Comment by oleglantuh** [comment]
Спасибо за ответ

**Comment by annastolbova** [comment]
Заявка закрита 01.02.2016.
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
