### ISSUE TITLE
Нет прикрепленного документа

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/iForum#117]
Получил ответ о выполнении моей заявки. В письме указано "Електронна копія довідки підписана ЕЦП знаходиться в додатку до цього листа." но никакой копии нету. Номер заявки 12325951. Могу ли я получить копию справки моего запроса?

**Comment by GrekD** [comment]
@NikitaLyah 
укажите, пожалуйста, название услуги по кооторой подавали обращение и город/район

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
