### ISSUE TITLE
Субсидия, нет файла

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/iForum#119]
"23.11.2015 на свою електронну скриньку, я отримав лист-відповідь, про те що мій запит (14319640 ) успішно оброблено. 
Електронна копія довідки підписана ЕЦП знаходиться в додатку до електронного листа. 
АЛЕ ДОДАТОК ДО ЛИСТА ВІДСУТНІЙ!!!"

**Comment by kurbpa** [comment]
@NikitaLyah 
Добрый день.
К огромному сожалению пока идет реформа по перводу МВД в полицию у коллег из МВД нетактуального ЭЦП для заверения этой справки. Поэтому временно не отправляют.

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
