### ISSUE TITLE
Дизайн сторінки about

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#12]
@katebutenko пропонує зробити так (і при наводі на фото з'являються іконки соц мереж):

![1](http://i.piccy.info/i9/277c15522a8c7499897d8f6ac7d313ab/1443945373/148722/887339/1.png)

**Comment by VadymVolos** [comment]
Ще один варіант можна залишити список як є, а при наводі на ім'я, з'являється спливаюче віконце з фоткою, ім'ям, текстом, і іконками соц мереж

**Comment by brunneng** [comment]
+1 так будет веселее смотреться чем просто список имен..

**Comment by GrekD** [comment]
@bvv4ik 
что думаете?

**Comment by kurbpa** [comment]
Выглядит здорово, но  думаю приоритет этой доработки по сравнению с остальными стремится к нулю...

**Comment by VadymVolos** [comment]
А у нас есть дизайнеры и верстальщики? Они разве загружены работой?

**Comment by kurbpa** [comment]
В том то и дело, что фронт-эндеров  так не хватает.. а по ним есть  много задач по тому же дашборду

**Comment by VadymVolos** [comment]
Так чтож вы молчите, я ж спрашивал кто нужен, сейчас будем искать. Дайте пожалуйста перечень задач для фронт-эндеров чтоб люди приблизительно понимали что нужно делать, и сразу напишите куратора чтоб я знал за кем закреплять новичков.

**Comment by bvv4ik** [comment]
Прошу глянуть Milestones  front-end в репозитории i
Все те задачи, где не стоит лейбл тест и которые ни на кого не ассайнуты

По поводу фоток, мне кажется это стоит сделать в виде ссылки на профиль  любой из подсетей или нескольких, откуда и сможет автоматом подтягиваться фотка... а то ведь либо мы замучаемся каждого фотку деплоить либо люди сами не захотят в реализованном нами интерфейсе ето каждый раз делать (а ведь интерфейс добавления тоже не так просто сделать)

**Comment by VadymVolos** [comment]
Тут практически все задачи ассайнуты
https://github.com/e-government-ua/i/issues?page=1&q=is%3Aopen+is%3Aissue+milestone%3AFrontEnd_NodeJS

**Comment by VadymVolos** [comment]
По поводу фоток, да все правильно, нужно их из соцсетей подгружать, вручную это куча ненужной работы.

**Comment by GrekD** [comment]
скоро будет новый дизайн с фотками
