### ISSUE TITLE
Субсидия, нет файла

### ISSUE THREAD

**Issue by NikitaLyah** [e-government-ua/iForum#120]
"02.11.2015 была заказана справка.
23.11.2015 мне на е-мейл пришло поисьмо о том, что подписанная ЭЦП справка находится во вложении, но вложения в письме не было.
Номер заявки: №0-12190777"

**Comment by dmitrijzabrudskij** [comment]
@NikitaLyah смотрите ответ в этой заявке: https://github.com/e-government-ua/iForum/issues/119

пс: это справка о несудимости. в справках по субсидиям эцп нет

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
