### ISSUE TITLE
Фідбек: розробити механізм офлайн черг для операторів в держ органах.

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#121]
Надійшов фідбек від вдячного кліента:
-============
https://www.facebook.com/igov.org.ua/posts/149347178756495
‎Іван Воробйов‎
Доброго дня! Сьогодні подавав документи на закордонний паспорт до міграційної служби м. Кривий Ріг зареєструвавшись на порталі igov.org.ua. Це супер. Мене прийняли згідно часу. Всі документи прийняли. Я вражений!!! Ніколи не бачив такої роботи міграційної служби! Дякую розробникам!!! Ви молодці!!! Дякую хто підтримує цю ідею та впроваджує її у життя!!! Смайлик «smile»
Але, як завжди буває маленьке але... Перед кабінетом у міграційній службі стояла черга з людей, які реєструвалися у цій службі на місці. Та виникла суперечка, хто повинен заходити наступний. Працівниця міграційної служби (жіночка років під 60 у червоній кофтині), відповідальна за реєстрацію повідомила, що прийом клієнтів, що реєструвалися за допомогою сайта igov.org.ua здійснюється одними й тими ж працівниками. Почала розповідати, що цю чергу їм нав*язали згори, вона не портібна й вони не хочуть так працювати, тому це не їх вина. Потім вона додала, що взагалі не знає людей з тієї черги та хто повинен прийти. Після цього люди почали обурюватись ще більше і косо дивитись на тих, хто прийшов з реєстрацією igov.org.ua .
Міграційна служба не пояснює людям про нові можливості і всіляко намагається саботувати нововведення. Коли я почав людям розповідати про igov.org.ua та його можливості, дехто зацікавився а дехто й сказав, що чув та не знав що він працює. Висновок ,люди зрозуміли, що міграційна трохи не допрацьовує в цьому напрямку.
Але, я також хочу дізнатися у розробників чи дійсно працівники міграційної служби не знають ПІБ хто до них записався на прийом за допомогою сайту igov.org.ua???
Дякую за увагу Смайлик «smile»
-============

Згідно цього фідбеку, люди які в віконцях надають послуги, не знають як дати раду з чергою. Треба розробити чітку інструкцію для них, з стимулом до 100% виконання.

**Comment by Koffeek** [comment]
Механізм потенційно реалізувати можна, тільки питання в тому, що існуюча черга розрахована на сталий проміжок часу (15 хв.), а іноді працівники ДМС можуть витратити і 25 на одну людину. Зараз якраз вірішується як краще сінхронізувати "живу" чергу та користувачів iGov. Стосовно знання ПІБ людей, хто записаний на прийом - це саботаж чистий. При вході на портал чиновник має змогу по конкретній даті переглянути усі записи та інформацію по них (ПІБ, телефон та інше). В деяких ДМС співробітники розруковують собі цю чергу, якщо не має змоги дивитись у режимі онлайн.

**Comment by VadymVolos** [comment]
>як краще сінхронізувати "живу" чергу та користувачів iGov
так це ж і треба.

Якщо для iGov посадити окремого оператора, я думаю це вирішить проблему.

**Comment by Koffeek** [comment]
"Якщо для iGov посадити окремого оператора, я думаю це вирішить проблему." це звичайно було б круто, але є багато перешкод.
1. При оформленні закордонного паспорту працівники ДМС вносять дані до спеціальної системи, яка шифрованим каналом поєднується з серверами у Києві. Тобто далеко не кожен працівник має змогу доступу до неї
2. Окремий оператор це штатна одиниця із зарплатою, забезпеченням технікою та таке інше, що на фоні скорочення держслужбовців не пройде.
3. Для синхронізації потрібна працююча електронна черга, до якої ми мали б змогу інтегруватись, а її нажаль немає.

**Comment by VadymVolos** [comment]
Тоді, зробити графік, наприклад прийомний день для юзерів iGov вівторок і четвер після обіду. І планувати графік так щоб офлайн користувачам назначати на один день, а онлайн на інший.

**Comment by Koffeek** [comment]
І ДМС отримає закономірні претензії у дискримінації, бо приймати громадян вони зобов'язані суворо регламентований проміжок часу на тиждень (десь 40 годин, але можу помилитись). Вони і так працюють з порушенням. Також треба додати, що наші люди ще й запізнюються на заздалегідь замовлений час (нагадаю шаг черги 15 хвилин) і потім ображаються, коли їм про це говорять.
