### ISSUE TITLE
Субсидия. Статус "Взяти в роботу (у роботi)"

### ISSUE THREAD

**Issue by Nuttty17** [e-government-ua/iForum#122]
Подскажите как проверить принята ли заявка на субсидию? Заявка номер  9598604  со статусом "Взяти в роботу (у роботi)" висит еще с 19.10.2015. Хотелось бы узнать результат. Заранее спасибо)

**Comment by dmitrijzabrudskij** [comment]
в какой район отправляли заявку?

**Comment by Nuttty17** [comment]
Жовтневый район

**Comment by dmitrijzabrudskij** [comment]
она в работе у района. по срокам уже должна быть на подходе. перезвоните в район, пожалуйста, по телефону 056 377-08-37 уточните в каком она состоянии.

**Comment by Nuttty17** [comment]
с Вашей стороны будут еще какие-либо оповещения или всю дальнейшую информацию узнавать непосредственно в инстанции?

**Comment by dmitrijzabrudskij** [comment]
когда субсидия будет назначена, Вам пришлют имейл с отсканированным решением

**Comment by Nuttty17** [comment]
увы, невозможно дозвониться(

**Comment by Nuttty17** [comment]
то есть все-таки окончательных вестей можно ждать от Вас?

**Comment by dmitrijzabrudskij** [comment]
не конкретно от меня) будет письмо от имени портала по типу такого, которое Вы получили при подаче. только там будет написано назначена ли субсидия и будет прикреплен ее скан.

а насчет дозвониться - у них рабочий день по пятницам до 15. госорганы такие госорганы(

**Comment by Nuttty17** [comment]
как узнать результаты по субсидии?

**Comment by dmitrijzabrudskij** [comment]
ваша заявка находится на назначении. постараются ускорить

**Comment by Nuttty17** [comment]
Получила письмо следующего содержания:
"На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг відхилене через недостатню або неправильну інформацію.
Причина: Вам назначена субсидия с октября 2015года."
Как и где получить перерасчет за этот период?

**Comment by Nuttty17** [comment]
а статус все еще "Взяти в роботу (у роботi)"

**Comment by dmitrijzabrudskij** [comment]
это косяк жовтневого района - субсидия уже назначена, но за бумажкой с подробностями они приглашают подойти лично(
боремся сейчас с ними чтобы отправляли как положено - в имейле

**Comment by Nuttty17** [comment]
спасибо за Вашу работу!!!

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
