### ISSUE TITLE
Субсидії, місто Вугледар, як підключити?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#123]
Люди у місті Вугледар, хочуть отримувати субсидії онлайн, але на порталі немає можливості вибрати їх місто, що їм треба зробити щоб вони могли онлайн отримати?
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1638455686443308&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by GrekD** [comment]
Угледар пытались раскачать раз 5. Пока безрезультатно
