### ISSUE TITLE
Заявка 17031855.

### ISSUE THREAD

**Issue by EugeneGavrilyuk** [e-government-ua/iForum#125]
Допомога при народженні дитини.
Заявка 17031855. Подана 16.11.2015 року.
Район Жовтневий, місто Дніпропетровськ. 
До цього часу відсутня жодна інформація про обробку чи виконання даної заявки.

**Comment by GrekD** [comment]
@EugeneGavrilyuk 
ваша заявка находится в работе у соц.защиты в статусе:
Заповнені дані вірні, інформація направлена на розгляд, очікується рішення
