### ISSUE TITLE
Помилка в "Мій журнал"

### ISSUE THREAD

**Issue by lemaryn** [e-government-ua/iForum#127]
http://screencast.com/t/dUp2JiX93

**Comment by bvv4ik** [comment]
![image](https://cloud.githubusercontent.com/assets/4208821/11495644/921bbd78-9815-11e5-92cd-c869c9f7c0aa.png)

подозрения, что это старые записи, где еще даты не ставились... но перепроверим!

**Comment by lemaryn** [comment]
Нет не старые , я зарегистрировался на прошлой неделе и заявку тоже подавал тогда же.
