### ISSUE TITLE
iGov-субсидії-Франківськ

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iForum#129]
@dmitrijzabrudskij 
ответь, пожалуйста

Доброго вечора! На жаль у цьому документі відсутні контактні дані Дмитра Забрудського, який є менеджером послуги "Отримання субсидії..."
https://docs.google.com/spreadsheets/d/1ZLJgro3bn0P3oi9uhm3cSmRvQTTLlKo9bhn7zww-bmQ/edit?usp=sharing

Справа ось у чому: в Івано-Франківську місцеві чиновники оголосили про початок прийому заявок як через міністерський сайт, так і через сайт igov. Хоча насправді через iGov послуга в Івано-Франківську недоступна. Хотілось би отримати інформацію стосовно поточної ситуації по запуску цієї послуги у нас — чи чиновник поспішив, чи, можливо, забули повідомити про свою готовність

-- 
З повагою, 
Андрій Озорович,
експерт з комунікацій та PR
Молодіжний громадський центр «Еталон»
м. Івано-Франківськ, вул. Павлика, 10
тел. (097) 246-05-92,
(050) 599-29-38
e-mail: press@mgcetalon.org.ua

**Comment by dmitrijzabrudskij** [comment]
в Ивано-Франковске не запускались субсидии. похоже, чиновник опережает события. можно ссылку на его объявление?

мои контакты: dmitrij.zabrudskij@gmail.com, 0979362996

**Comment by aozor** [comment]
Ось тут: http://www.blitz.if.ua/news/prykarpatci-skarzhatsya-scho-systema-elektronnoi-podachi-zayav-na-subsydiyu-ne-pracyue.html
Хоча, цілком можливо, що це журналісти перемудрили. Бо коли я одному з місцевих каналів давав коментар і пояснив, що на iGov послуга ще не працює і потрібно трохи почекати, вони чомусь цей момент вирізали: http://www.vezha.org/oformyty-subsydiyu-mozhna-v-on-lajn-rezhymi-video/

**Comment by dmitrijzabrudskij** [comment]
точно предвосхищают события...
кстати, если у Вас есть контакт с департаментом соцзащиты Ивано-Франковская, прошу помочь связаться с ними (или дайте мне их контакты, или мои - они выше написаны). Если у них и вправду такой настрой, то запустить мы там все можем в течение пары дней
