### ISSUE TITLE
Оформление субсидии на портале https://igov.org.ua

### ISSUE THREAD

**Issue by Mellvin1987** [e-government-ua/iForum#130]
После заполнения формы, пр нажатии кнопки "Замовити послугу" вылетает ошибка "ПОМИЛКАSYSTEM_ERR"

**Comment by dmitrijzabrudskij** [comment]
можете сделать скриншоты всего экрана и сбросить сюда?

**Comment by Mellvin1987** [comment]
![15](https://cloud.githubusercontent.com/assets/16135154/11561743/12ac95f8-99d2-11e5-8926-8ecef2ebd268.jpg)

**Comment by dmitrijzabrudskij** [comment]
https://www.dropbox.com/s/j3k0llv04htjug4/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-12-03%2015.27.57.png?dl=0

попробуйте заново авторизоваться - у Вас сверху должен появиться выбор района. из-за не пускает заявку

**Comment by Mellvin1987** [comment]
![3](https://cloud.githubusercontent.com/assets/16135154/11561872/dc2a5a78-99d2-11e5-9a81-b1dec56e1d51.png)
Район выбирается, пробовал уже раз 5. Заполняю как референт от имени другого человека (отца)

**Comment by dmitrijzabrudskij** [comment]
заполнение от имени другого человека еще в процессе. придумаем пока какое-то предупреждение или скроем. извините за неудобства
