### ISSUE TITLE
подача заявки на получение пособия по рождению ребенка

### ISSUE THREAD

**Issue by Galina64** [e-government-ua/iForum#131]
17.11.15 г. подала заявку на пособие по рождению ребенка.  17.11.2015 22:53 Ви подали заявку на послугу Дніпропетровськ - Призначення соціальної допомоги при народженні дитини!. Cтатус: Заявка подана. 18.11.2015 09:32	Ваша заявка №0-17571483 змiнила свiй статус на обработка этап 1 (у роботi). 18.11.2015 09:56 Ваша заявка №0-17571483 змiнила свiй статус на Запит на уточнення даних. Какие данные уточнить и каким образом? Подавала через BankID (Приватбанк), но счет был открыт на девичью фамилию (приложила свидетельство о браке, новый паспорт, свидетельство о рождении, перевод, апостиль. Статус до сих пор не изменился. Звонила в Управление труда и соц защиты Бабушкинского (теперь Шевченковского) района, приходите 18 декабря, двое малышей… Что делать? (Почта glavbuh3579@gmail.com, Бабушкинский район, г. Днепропетровск)

**Comment by Suzern** [comment]
Я не являюсь основателем и разработчиком данного сайта, но дам подсказку. Если в статусе стоит: "Запит на уточнення даних." Вам стоит обратиться в соц.службу и узнать у них, какие именно Ваши данные стоит уточнить.
Возможно много вариантов:
счет не является социальным(банковский), нужен оригинал апостиля, для заверения его в соц. защите, и др.

**Comment by dmitrijzabrudskij** [comment]
@Galina64 разбираемся с районом. я напишу по результату

**Comment by Galina64** [comment]
огромное спасибо

2015-12-04 13:26 GMT+02:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by Galina64** [comment]
и если бы еще номер телефона, куда звонить...

4 декабря 2015 г., 13:26 пользователь Галина Носач <glavbuh3579@gmail.com>
написал:

**Comment by dmitrijzabrudskij** [comment]
056 763 05 79

**Comment by Galina64** [comment]
спасибо


2015-12-04 15:09 GMT+02:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by GrekD** [comment]
@Galina64 добрый день!
удалось ли выяснить в районе: какие данные они отели уточнить?

**Comment by Galina64** [comment]
Добрый день, мы подавали через Приват24, а там была девичья фамилия и они
запутались... Пришлось все-таки прийти и все, электронная заявка была
принята. Пришло с сайта уведомление, что пособие назначено, но еще не зашли
деньги, ждем. Спасибо за вашу работу.

воскресенье, 24 января 2016 г. пользователь Darja Grek написал:
