### ISSUE TITLE
подала заявку на субсидию 30.10.15

### ISSUE THREAD

**Issue by Galina64** [e-government-ua/iForum#132]
30 октября 2015 г. подала заявку на субсидию, Ваша заявка 12243224 прийнята! До сих пор статус - 2 ноября 2015 г.  Взята в роботу и все? Журнал: 30.10.2015 23:28 Ви подали заявку на послугу Отримання субсидії на оплату житлово-комунальних послуг!. Cтатус: Заявка подана. 02.11.2015 09:33	Ваша заявка №0-12243224 змiнила свiй статус на Взяти в роботу (у роботi). 02.12.2015 11:44	Приватбанк завантажує Громадянський паспорт Паспорт у Ваш розділ Мої документи. Подавала через BankID (пенсионная карта, Приватбанк), Статус до сих пор не изменился. Что делать? (Почта glavbuh3579@gmail.com, Солонянский район, Днепропетровская область). Что делать? теперь бежать подавать вручную? Еще подавать он-лайн? или ждать? скоро год закончится. Заранее благодарна

**Comment by dmitrijzabrudskij** [comment]
ваша заявка в работе у района. попробуйте им позвонить (05669 21396) и узнать подробности, пожалуйста

**Comment by Galina64** [comment]
спасибо

4 декабря 2015 г., 13:16 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by Galina64** [comment]
Добрый день. Мы подавали через Приват24 31 октября 2015 г... Субсидию
назначили 16 декабря.  Но это уже наши знакомые ходили в район и получили
ее на руки. Так бы мы получили позднее... 14 января по электронке , но в
отчет о назначении субсидии нам вложили скан-копию не нашей субсидии и меня
чуть кондратий не хватил, пока не дочиталась, что это не наша субсидия...
Там стоял другой получатель и субсидия в меньшем размере... Спасибо за вашу
работу.

2016-01-24 21:47 GMT+02:00 Darja Grek <notifications@github.com>:

**Comment by Galina64** [comment]
Очень нужный ресурс подачи электронных запросов, правда они, конечно, не
выдерживают сроки, но это уже мелочи, по сравнению с тем, что не пришлось
стоять в очереди и толпой бегать из кабинета в кабинет... К сожалению
наблюдала такую картину, когда приходила объяснять, почему человек
отсутствует, а субсидию сильно хочет и не может подтвердить... Спасибо за
вашу работу.

25 января 2016 г., 9:54 пользователь Галина Носач <glavbuh3579@gmail.com>
написал:
