### ISSUE TITLE
Подача на субсидию

### ISSUE THREAD

**Issue by Galina64** [e-government-ua/iForum#133]
Пытаюсь подать заявку на субсидию через BankID (пенсионная карта, Приватбанк), заполнила (подаю не первый раз, было удачно, если не считать, что нет ответа), нажимаю Заказать услугу, не реагирует, и не выдает никакой ошибки. Что делать? (Почта glavbuh3579@gmail.com, Бабушкинский район, Днепропетровская область). Что делать? Проблема с сайтом? Заранее благодарна

**Comment by dmitrijzabrudskij** [comment]
все работает. проверьте все поля, которые заполняли - наверняка ошибка в каком-то из них (должно подсвечиваться красным)

**Comment by Galina64** [comment]
В том то и дело, что все заполнило, ничего не подсвечивало, и не выдавало
никакой ошибки, подаю сейчас заново. Может был какой-то глюк вчера.

4 декабря 2015 г., 13:20 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by Galina64** [comment]
а наименования коммунальных служб должны без кавычек? может быть..

4 декабря 2015 г., 13:22 пользователь Галина Носач <glavbuh3579@gmail.com>
написал:

**Comment by dmitrijzabrudskij** [comment]
вообще не должно влиять. но попробуйте без

**Comment by Galina64** [comment]
дуже дякую, отправила, при указании площади надо было использовать
разделитель точечку...

2015-12-04 13:37 GMT+02:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by dmitrijzabrudskij** [comment]
это да, скоро добавим подсказку на этот счет

**Comment by Galina64** [comment]
Добрый день. Мы подали через Приват24 04 декабря 2015 г,  а уже 8 декабря
позвонили... Там был вопрос, что надо прийти и подписать лично заявление,
хотя запрос электронный... это Бабушкинское управление... Но там еще и
прописано 3 человека, а по факту проживает только один человек... и то
отсутствует с марта 2015 г. (перенес 3 операции, находится у детей за
границей... Пришлось мне выступить доверенным лицом, подтвердить лично,
подписать, ну а то, что дети только прописаны, а не получают доходы в
Украине легко было проверить по ИНН...Субсидию назначили 12 января,
сообщение пришло 22 января... В личном кабинете по газу уже появились даже
деньги....   Спасибо за вашу работу.Очень нужный ресурс подачи электронных
запросов, правда они, конечно, не выдерживают сроки, но это уже мелочи, по
сравнению с тем, что не пришлось стоять в очереди и толпой бегать из
кабинета в кабинет... К сожалению наблюдала такую картину, когда приходила
объяснять, почему человек отсутствует, а субсидию сильно хочет и не может
подтвердить...

2016-01-24 21:47 GMT+02:00 Darja Grek <notifications@github.com>:
