### ISSUE TITLE
Послуга реєстрація авто з пробігом в МРЕВ, неможливо вибрати дату візиту.

### ISSUE THREAD

**Issue by KievAndrey** [e-government-ua/iForum#134]
При заповненні заявки на реєстрацію ТЗ в м. Київ неможливо вибрати або внести бажану дату візиту.
![bug](https://cloud.githubusercontent.com/assets/16150289/11587771/8eb2afe0-9a84-11e5-87e1-0f115a330cb1.png)

**Comment by GrekD** [comment]
@kurbpa рассмотри, пожалуйста

**Comment by kurbpa** [comment]
В курсе проблемы. 
К сожалению сейчас нет обученных сотрудников, которые могли бы обрабатывать заявки. Общаемся с ГАИ для решения проблемы. Поэтому возможности подать заявку временно нет.
