### ISSUE TITLE
оформление субсидии - как предоставить оригиналы справок о доходах к электронному обращению

### ISSUE THREAD

**Issue by Udaha** [e-government-ua/iForum#135]
01.12.2015 года направила обращение №22938908 на оформление субсидии. Оно было рассмотрено и возвращено на доработку с указанием следующих причин. 

Причина: 1. доходи вказуються за період 01.01.2014-31.12.2014, або за останні три місяці до місяця звернення, з поданням оригіналу довіки про доходи; 
2. необхідно вказати в якому районі Пенсійного фонду пенсіонери отримують пенсію

У меня возник вопрос, как я смогу предоставить  оригінали довідки про доходи к электронному обращению? Как дают разьяснения средства массовой информации - на сайте необходимо заполнить только форму и отправить. о принятом решении дадут ответ на электронный адрес. дают разьяснения, что не надо ходить по организациям и собирать разные справки.

**Comment by dmitrijzabrudskij** [comment]
в случае, если указывается период декларации последние 3 месяца, нужно приносить оригиналы справок о доходах в отделение собеса. если декларация за минувший год, то собес сам запросит  инфо из налоговой

**Comment by Udaha** [comment]
спасибо за разьяснения

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
