### ISSUE TITLE
Пособие на рождение ребенка 

### ISSUE THREAD

**Issue by EvaSergeevna92** [e-government-ua/iForum#136]
28.11.2015 былв подана заявка 21759363 и до сих пор статус "заявка подана",хочу узнать,движение дальше будет или так и будет висеть в воздухе эта заявка?сколько нужно ждать для получения ответа и самого пособия?

**Comment by dmitrijzabrudskij** [comment]
в какой район отправляли заявку?

**Comment by EvaSergeevna92** [comment]
Или в жовтневый или в индустриальный,не помню,а можно это как-то посмотреть?
--
Отправлено из Mail.Ru для Android понедельник, 07 декабря 2015г., 11:48 +02:00 от dmitrijzabrudskij < notifications@github.com> :

**Comment by GrekD** [comment]
@EvaSergeevna92 Вам должно было прийти сообщение о предоставлении оригинала больничного. приходило такое?
После этого помощь будет начислена
