### ISSUE TITLE
Пособие по беременности

### ISSUE THREAD

**Issue by EvaSergeevna92** [e-government-ua/iForum#137]
28.11.2015 была подана заявка 21755724 и до сих пор статус "заявка подана",через сколько будет результат этой подачи и начисление пособия,действие справки истекает 7 декабря 2015 года,не сильно хочется остаться без пособия из-за работы вашего портала,а ездить в совбез к черту на рога с грудным ребенком возможности нет никакой,надеюсь на вразумительный ответ.

**Comment by GrekD** [comment]
@EvaSergeevna92 
сейчас Ваша заявка еще находится в работе у соц.защиты в статусе:
Заповнені дані вірні, інформація направлена на розгляд, очікується рішення

**Comment by EvaSergeevna92** [comment]
Спасибо большое за помощь!уже начислили
--
Отправлено из Mail.Ru для Android вторник, 19 января 2016г., 17:10 +02:00 от Darja Grek < notifications@github.com> :
