### ISSUE TITLE
Статус заявки на получение субсидии

### ISSUE THREAD

**Issue by Ssvsdim** [e-government-ua/iForum#138]
Отправил заявку на получение субсидии. Статус выконано. Что это значит. Получил я субсидию или мне в ней отказано.

**Comment by GrekD** [comment]
@Ssvsdim укажите, пожалуйста, номер заявки (приходила в письме на почту) и район в который подавали

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
