### ISSUE TITLE
Получение выписки из кадастра на землю.

### ISSUE THREAD

**Issue by olafenator** [e-government-ua/iForum#139]
При заказе выписки с помощью igov в ЦНАП возникла такая проблема:
Заказал справку на своё ФИО, дача на маме. При заказе ничего не предвещало неожиданностей, проплатил 53 грн, приехал в назначенное время, а там ответ кадастровой службы - отказ. 53 грн уходят за заявку, и все по-новой(( Заказал уже на маму, она приехала и получила. 
Понимаю что виноват сам, думал что её сделают но мне не отдадут например, тогда бы забрала мама, но не ожидал что будет как при игре в лотерею, вы проиграли - деньги уходят в банк. Это же гос.услуги все-таки. 
Ездил на встречу с главой кадастровой службы, Олегу Николаевичу Цвях, кажется, но он принимает раз в месяц два часа, и то в тот день он не появился на своем же приеме. 
Спасибо.

**Comment by NizhnikAlex** [comment]
Добрый день. Несколько вопросов:
1. Какой документ конкретно вы заказывали? Выписку из кадастра у нас заказать невозможно - нет такого выбора.
2. Будем исходить из того, что вы заказали "Витяг про земельну ділянку". Если это не так - возвращаемся к п.1
3. "Витяг про земельну ділянку" на данный момент реализован через кадастровую карту Регистрационной службы (их официальный портал). С сайта iGov стоит редирект.
4. Насколько я знаю, по закону вы можете получить справку на чужое имущество, просто хозяин имущества будет знать кто запрашивает информацию. Кроме того, на сайте кадастровой карты в информации не указано обязательное требование быть владельцем или пользователем земли http://wikimap.dzk.gov.ua/wiki/%D0%A5%D1%82%D0%BE_%D0%BC%D0%B0%D1%94_%D0%BF%D1%80%D0%B0%D0%B2%D0%BE_%D0%BD%D0%B0_%D0%BE%D1%82%D1%80%D0%B8%D0%BC%D0%B0%D0%BD%D0%BD%D1%8F_%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BE%D1%81%D1%82%D0%B5%D0%B9_%D0%B7_%D0%94%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%BE%D0%B3%D0%BE_%D0%B7%D0%B5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BA%D0%B0%D0%B4%D0%B0%D1%81%D1%82%D1%80%D1%83%3F. Т.е. можете попробовать найти этот пункт в законах и поругаться с Регистрационной службой.

**Comment by olafenator** [comment]
Здравствуйте) Ответы:
1,2. Да, естественно, я заказывал Надання відомостей з Державного
земельного кадастру у формі витягу з Державного земельного кадастру про
земельну ділянку <https://igov.org.ua/service/101/general>.
 Мне кажется вытяг и выписка одно и то же, разве нет?
3. Понятно, не вы реализовывали.
4. Спасибо) В реальности выдают отказ из-за того что заказ не от хозяина
земли. Хотя даже фамилии у нас с мамой одинаковые. А денежки тю-тю.
Ругаться уже надоело, писал Вам уже что ездил на прием к руководителю, но
он не приехал в этот день. И от гос.учереждений тошнит.
Спасибо за быстрый ответ. Олег

8 декабря 2015 г., 16:06 пользователь NizhnikAlex <notifications@github.com>
написал:
