### ISSUE TITLE
Заявка № 19562534

### ISSUE THREAD

**Issue by Nikolay2016** [e-government-ua/iForum#140]
Прошу предоставить уведомление о назначении субсидии с ноября 2015г. Статус заявки на данный момент - "Взяти в роботу (у роботi)", а фактически сумма субсидии уже перечислена поставщикам услуг. Спасибо.

**Comment by GrekD** [comment]
@Nikolay2016 
вопрос еще актуален? Если да - напишите город/район по которому подавали заявку

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
