### ISSUE TITLE
Довідка про взяття на облік особи, переміщеної з тимчасово окупованої территорії

### ISSUE THREAD

**Issue by tshalf** [e-government-ua/iForum#141]
Доброго дня. 
Цікавить чи є в планах реалізація можливості замовити оформлення або подовження сабжової довідки(її треба продовжувати кожні півроку) через iGov. 
Зараз це доволі незручна операція(дуже багато людей, принаймні в Київі). ЇЇ покращіли, розбивши на два етапи: спочатку треба зробити замовлення, а потім приїхати отримати. Але щоб замовити процедуру, треба приїхати туди(відділ праці та соціального захисту населення). А потім треба їхати за результатом. Замовити послугу за телефоном неможливо. Тому дуже бажано було би мати можливість замовити процедуру через iGov.

**Comment by Koffeek** [comment]
@tshalf 
Доброго дня. На даний момент робота над такою послугою не ведеться. Але ми додамо її до планів на майбутнє. Дякуємо за пропозицію.
