### ISSUE TITLE
Чи можна перенести отримання закородн пасп на інший день?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#143]
Наталья Бондарчук: Добрый день! а можно как-то отменить заявку на отримання паспорту для виїзду за кордон??не получается в этот день никак(((
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1643439512611592&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by dmitrijzabrudskij** [comment]
да, оформить новую заявку

**Comment by VadymVolos** [comment]
Так якось не логічно?
Людина ж принесла документи, сфоткалася...
При оформлені нової заявки куда дінеться стара? 
А якщо скажуть знову приходити фоткатися і оплачувати?

**Comment by dmitrijzabrudskij** [comment]
1. та не приходила она еще. оплата действует постоянно - она может оплатить 01.12, а подойти фотографироваться 01.01.2016 и все сработает.

2. насчет месяца - ровно такая же опасность будет ее поджидать и при переносе - все равно будет браться свободное время из слотов
