### ISSUE TITLE
Уведомление о принятии заявки на субсидию

### ISSUE THREAD

**Issue by WalterRWJ** [e-government-ua/iForum#144]
Здравствуйте!
Оформил заявку на субсидию, прошло чуть больше 3 дней - никаких уведомлений не получил.
Создать заявку заново?
Спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день
должен быть номер (в письме на имейл) - поищите в спаме, пожалуйста
или могу попробовать по-другому найти - для этого мне нужен район, куда отправляли, фио подателя и точная дата

**Comment by WalterRWJ** [comment]
В почте ничего нет.
Через Журнал посмотрел, что заявка была выполнена 21.12.2015.
№25289773 
Можно узнать по ней ответ?
Спасибо!

**Comment by dmitrijzabrudskij** [comment]
"Шановна Лілія Іванівна! В заяві про призначення житлової субсидії невірно вказаний номер особового рахунка газопостачання.Виправте недолік та надішліть повторно заяву та декларацію. Заява від 16.12.2015 прийнята в роботу."

такой ответ Вам отправляли

**Comment by WalterRWJ** [comment]
Спасибо!
Повторную заявку я отослал еще 16.12.2015, с тех пор по ней никакого движения не видно.
№35607427

**Comment by dmitrijzabrudskij** [comment]
она в работе, теперь нужно дождаться решения по ней
