### ISSUE TITLE
Приложение «Договор 24». Для эл. документооборота (СПД и граждан).

### ISSUE THREAD

**Issue by alexlowyer** [e-government-ua/iForum#147]
Добрый день !

Я имею одно предложение возможно оно вас заинтересует. По моему мнению это будущее. Или к нему необходимо стремиться.

Приложение «Договор 24» по сути.

Позволяет заключать Договора (купли-продажи, поставки, аренды, услуг и т.д.), Приложения, Протоколы, Акты и т.п. в электронном виде. 
Идентификация: ID bank.
При заключении Договора (сделки) Приложение: 
1.	использует данные гос. реестров;
2.	использует шаблоны договоров (с возможность вносить правки («голос в текст»)), а также «заливать» уже согласованные;
3.	система автозаполняет данные контрагентов;
4.	предоставляет возможность он-лайн оплаты;
5.	напоминает об оплате;
6.	подсказывает о необходимости оценки им-ва, нотариального удостоверения и т.п.;
7.	предоставляет возможность добавить видео, фото факты;
8.	для подтверждения заключения сделки использует на выбор: селфи, голос и пр.

Приложение «предоставляет услуги»:
1.	верификации участника (агента);
2.	гаранта персональных данных участников при заключении сделки;
3.	хранения персональных данных участника;
4.	подтверждения данных (он-лайн) для гос. органов (судов и пр.) о сделках;
5.	размещение частные и публичные (рекламные) оферты (оценщика, нотариусы, адвокаты, переводчики и страховики и пр.);
6.	платежной системы;
7.	формирования (и автоподачи) отчетности, на основе совершенных сделок;
8.	добавление и хранении фото и видео связанные со сделками; 
9.	архивирования данных (в pdf и в спец. архиве) на носителе участника.

Пользователь имеет право:
1.	размещать оферты (частные и публичные (рекламные));
2.	принимать оферты (частные и публичные (рекламные));
3.	предоставлять доступ (с согласия 2-й стороны) к подписанным Договорам;
4.	предоставлять доступ адвокату(без согласия 2-й стороны) к подписанным Договорам (с случае спора);
5.	выставлять счета на оплату товар, услугу, имущество и т.д.;
6.	получать оплату за товар, услугу, имущество и т.д.

Для каждого договора разрабатывается обязательные (реквизиты, дата, место, условия оплаты, порядок передачи, гос. регистрация и т.д.) и дополнительные условия.

С каждым подключенным гос. реестром возможности системы увеличиваются.

В идеале это функция государства, но на коммерческих «рельсах» эта система уедет дальше…

Полагаю, что проект которым вы занимаетесь https://igov.org.ua/ отличная площадка для этого.

Вместе мы сделаем нашу Украину лучше!!! 

С уважением, Александр.

**Comment by GrekD** [comment]
@alexlowyer добрый день!
Направьте, пожалуйста, Ваше предложение Дмитрию Дубилету - d@igov.org.ua
