### ISSUE TITLE
Оформление субсидии

### ISSUE THREAD

**Issue by NataljaP** [e-government-ua/iForum#148]
заявка № 11670845, подана 2015-10-29 08:39:33, г. Днепропетровск, Индустриальный район.
при подаче указывалась почта natalja_pronzhenko@ukr.net
статус "Взяти в роботу (у роботi)" и не меняется
ответа нет

**Comment by dmitrijzabrudskij** [comment]
субсидия по ней назначена. должны прислать решение. если до пятницы не будет имейла - маякните в эту ветку

**Comment by NataljaP** [comment]
маякую. нет имейла по субсидии 11670845

**Comment by dmitrijzabrudskij** [comment]
вижу, что отправляли 23.12 - проверьте на всякий случай все папки в почте - вдруг в спам попало..

пс: ну, и на всякий случай еще раз отправил решения:)
