### ISSUE TITLE
Как оформить субсидию онлайн

### ISSUE THREAD

**Issue by Nightlyn** [e-government-ua/iForum#149]
Как оформить документы на субсидию онлайн? 
запрашивает какие то БанкИД или подтверждение электронной подписи! Дохожу до второго шага и на этом упираюсь!

**Comment by dr1v3** [comment]
Про BankID можно почитать [тут](http://bankid.org.ua), если Вы до данного момента не сталкивались с необходимостью оформления электронной подписи, то ради субсидии нет смысла её оформлять. Про подпись можно почитать [тут](https://taxer.ua/ru/kb/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B9_%D0%AD%D0%A6%D0%9F)
