### ISSUE TITLE
соц помощь при рождении ребенка

### ISSUE THREAD

**Issue by drover1988** [e-government-ua/iForum#15]
не могу оформить соц помощь при рождении ребенка т.к. выдаёт ошибку SYSTEM_ERR Exception while invoking TaskListener: Exception while invoking TaskListener: null

**Comment by drover1988** [comment]
как исправить, что это такое?

**Comment by dmitrijzabrudskij** [comment]
проверьте чтобы в полях для ввода реквизитов не было ничего кроме цифр. и еще уточнение - вы же на боевом пробуете?

**Comment by drover1988** [comment]
Громадянам: Взаємодія з державними органами  потом Призначення соціальної допомоги при народженні дитини , тут, всё верно??

**Comment by drover1988** [comment]
на боевом??

**Comment by drover1988** [comment]
полях для ввода реквизитов  на зачисление на карту хочу на приват банк, всё заполняю верно МФО ЕГРПОУ привата ввожу, прописку и место проживания, сканы ипн и свидетельство о рождении всё загружаеться как всё ввели ошибка SYSTEM_ERR Exception while invoking TaskListener: Exception while invoking TaskListener: null

**Comment by dmitrijzabrudskij** [comment]
сделайте пожалуйста скрины всей страницы, на которой вы видите ошибку

**Comment by drover1988** [comment]
![default](https://cloud.githubusercontent.com/assets/15017962/10360443/58751bd2-6da9-11e5-8d38-f03258b0490d.jpg)
![1](https://cloud.githubusercontent.com/assets/15017962/10360447/5dd2c5f2-6da9-11e5-8861-e4d826880690.jpg)
![2](https://cloud.githubusercontent.com/assets/15017962/10360449/6156db82-6da9-11e5-81b8-9dece58a6fad.jpg)

**Comment by drover1988** [comment]
вот так

**Comment by bvv4ik** [comment]
а какого числа и во сколько была последняя такая неудачная попытка?

**Comment by drover1988** [comment]
8.10.2015 в 11 утра, каждый раз именно такая ошибка

**Comment by LucyVR** [comment]
Проблема осталась
