### ISSUE TITLE
Помилка при заповненні форми реєстрації авто з пробігом в МРЕВ

### ISSUE THREAD

**Issue by 140480** [e-government-ua/iForum#152]
Доброго дня! При заповненні форми реєстрації авто з пробігом в МРЕВ не вдається вказати значення у полі "Бажана дата візиту до МРЕВ". Помилка виникає у всіх доступних браузерах - Firefox, Chromе та IE. 
![date_bug](https://cloud.githubusercontent.com/assets/16309576/11820129/8807dd06-a36b-11e5-91bc-5ede735f2f59.png)

**Comment by GrekD** [comment]
@kurbpa посмотри, пожалуйста
