### ISSUE TITLE
Заявка на получение субсидии

### ISSUE THREAD

**Issue by Ulia0807** [e-government-ua/iForum#154]
29.10.2015 подала заявку "На отримання субсидії на оплату житлово-комунальних послуг". Получила номер заявки №12011725. Было указано, что ответ будет получен на протяжении 20 дней. В статусе заявки с 30.10.2015 стоит "Заявка виконана".На электронную почту не пришло ни подтверждение, ни опровержение субсидии. Как узнать судьбу заявки?

**Comment by dmitrijzabrudskij** [comment]
какой район выбирали при подаче?

**Comment by Ulia0807** [comment]
Бабушкинский

**Comment by dmitrijzabrudskij** [comment]
не нахожу эту заявку в работе. проверьте спам в почте или напишите ее сюда - проверю какое письмо отправлялось

**Comment by Ulia0807** [comment]
Ошибочный номер заявки указала, прошу прощения. После исправления ошибки мне дали номер 12136872.
На электронку пришло письмо -   "Ваша заявка 12136872 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення"

С тех пор не могу выяснить приняли её или нет..

**Comment by dmitrijzabrudskij** [comment]
заявка еще в работе. Вы можете перезвонить в район уточнить на каком она этапе: 056 763 08 55

**Comment by Ulia0807** [comment]
а на вашем сайте можно узнавать статус заявки или нет?

**Comment by dmitrijzabrudskij** [comment]
можно. но он отражает статус заявки в нашем портале. в нем нет внутренней информации от соцзащиты. поэтому я и советую звонить им
