### ISSUE TITLE
регистрация авто с пробегом

### ISSUE THREAD

**Issue by Djohnypalace** [e-government-ua/iForum#155]
система видно умерла едва родившись. Третий день бьюсь подать заявку в МРЭО (СЦ) с трех разных компьютеров, двух разных банк-айди и трех разных браузеров. Не активируется выбор даты визита и соответственно форма стопорится и дальше не идет.
ну и в качестве предложения - добавить всего один чекбокс и вместе с регистрацией авто можно получить и заявку на прямую перерегистрацию через договор купли продажи. Логично?

**Comment by GrekD** [comment]
@kurbpa посмотри, пожалуйста

**Comment by kurbpa** [comment]
@Djohnypalace 
Уточните пожалуйста город и  для какого СЦ ?

**Comment by Djohnypalace** [comment]
Киев. СЦ пробовал Петропавлівська Борщагівка, вул.Кільцева 4 
вул. Туполєва, 19 
вул. Велика кільцева дорога. 22-А 
вул. Столичне шосе, 104 
вул. Новокостянтинівська, 8 
пров. Балтійський, 20 
сейчас могу попробовать Братиславскую.

**Comment by Djohnypalace** [comment]
тоже не работает. ГуглХром, Файрфокс ИЕ и Эдж

**Comment by kurbpa** [comment]
@Djohnypalace 
ясно проблема по Киеву.  Сейчас разберемся.

**Comment by Djohnypalace** [comment]
Спасибо. Буду ждать. 
Заодно в качестве предложения:
 может добавите возможность через эту же форму подавать заявку на прямую перерегистрацию? (по идее или один чекбокс или стринглист)   По суммам платежей в СЦ они насколько на автоуа проследили одинаковы. ++ при платежах дать возможность выбирать "экспертный осмотр" или "экспертное заключение" (второе не обязательно но дороже на почти 200 грн) (тоже один чекбокс)

**Comment by kurbpa** [comment]
@Djohnypalace 
возможно в будущем. Это все надо "проталкивать" в  МВД, что не всегда быстро и просто.

**Comment by Djohnypalace** [comment]
на сегодня при отмене справки-счета и регистрации договора прямо в СЦ разница только в одном телодвижении с их стороны которое они таки обязаны выполнять и которое по их-же заявлению бесплатное. 
Опять-же по их нормативке экспертное исследование не обязательно, достаточно экспертного осмотра. http://forum.autoua.net/showflat.php?Cat=0&Number=7830601&page=0&fpart=0&vc=1 судя по опыту разница в первом случае 150-200 грн а во втором 10-30

**Comment by kurbpa** [comment]
@Djohnypalace 

Киев. СЦ пробовал Петропавлівська Борщагівка, вул.Кільцева 4  -  можно подавать

**Comment by Djohnypalace** [comment]
ПОМИЛКАSYSTEM_ERR Could not send e-mail in execution 3995877

**Comment by Djohnypalace** [comment]
но кстати время выбранное уже занято (видно как раз мной :)

**Comment by kurbpa** [comment]
@Djohnypalace  
к сожалению нет.. это  временное резервирование пофакту выбора слота из списка (на 15 минут с целью избежания возможных коллизий, если несколько человек захотят выбрать одно и тоже время в один же момент) 

... чтобы временное резервирование в постоянное перешло необходимо чтобы заявка подалась

**Comment by Djohnypalace** [comment]
теперь только кольцевая 4 висит.. при выборе СЦ вход не появляется. Ни банк айди ни ЕЦП

**Comment by kurbpa** [comment]
Разбираемся...

**Comment by Djohnypalace** [comment]
Приветствую. Надежда что заработает есть? Или не надеяться а брать пару отгулов, бутерброді и ехать в мрео на удачу?

**Comment by Djohnypalace** [comment]
банк-айди на кольцевой появился, время вібрать дает но при нажатии замовити ПОМИЛКАSYSTEM_ERR Could not send e-mail in execution 4517958

**Comment by kurbpa** [comment]
Проблема с почтовиком.... Вчера вроде починили вечером и снова не работает.. Боремся.

**Comment by Djohnypalace** [comment]
вроде как ушло, на почту в отличии от проверки по базе ничего не пришло, и ответа на заявку с 7 утра нет :(   хотя таки 11.00 26/12 уже занято.

**Comment by Djohnypalace** [comment]
ЙЕС! Сдвинулось.
 Ваша заявка 50786551 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення. 
правда пришлось повторно подавать заявкуи уже не на 11 а на 11.30

**Comment by Djohnypalace** [comment]
а воз и ныне там :(  На 26 декабря заявка так и осталась в статусе "принято" , подал на 16 января. Надежда что ее рассмотрят есть? или таки заявки уходят в треш или их просто игнорят...

**Comment by kurbpa** [comment]
Услуга полностью реструктурирована.
С коллегами в  сервисных центрах проведено обучение.

**Comment by Djohnypalace** [comment]
Спасибо но уж не дождался и переоформил оффлайн :)
