### ISSUE TITLE
Субсидии

### ISSUE THREAD

**Issue by Sanar53** [e-government-ua/iForum#156]
Добрый день!
Есть такая ситуация: субсидия оформлена в прошлом году( оформлялась  без использования iGov), каждый раз после изменения стоимости комунальных услуг происходит перерасчет субсидии и каждый раз чтобы получить уведомление о назначенной субсидии нужно идти в управление соцзащиты и стоять в очереди для того чтобы узнать есть или нет ( если повезет, то получить) само уведомление о назначенной субсидии.
Сам вопрос: планируется или может уже есть услуга на iGov для получения этого уведомления на е-mail?

**Comment by dmitrijzabrudskij** [comment]
добрый день
конечно его можно получать. правда, сейчас для этого нужно заполнить заявку полностью - но в ответ Вам придет как раз уведомление о перерасчете субсидии

**Comment by Sanar53** [comment]
спасибо
