### ISSUE TITLE
Проблема регистрации на сайте igov.org.uа

### ISSUE THREAD

**Issue by Sogochi** [e-government-ua/iForum#16]
"Створення електронного піпипису", открывается страница где нужно "обрати файл сховища". Что это за файл и где его искать? Какой пароль к этому файлу?

Как зарегистрироваться?

**Comment by nika65** [comment]
Как зарегистрироваться?

Регистрация через выбор банка . Отсутствуют другие банки, в которых у моих родственников счёта. Например добавьте Банк Кредит Днепр

Зарание спасибо за ответ.

**Comment by LamronNu** [comment]
@Sogochi 
ЭЦП (электронно-цифровая подпись) -- это специальные файлы-ключи, которые хранятся на компьютере или флешке (это и есть то место, которое подразумевается под "файлом сховища").
получить ЭЦП можно в налоговой, самостоятельно "создать" такой файл Вы не можете, т.к. нужна организация, которая "подтвердит" Вашу личность.

@nika65 
Сейчас в списке только те банки, которые предоставляют такую функцию, т.е. дают возможность "заходить через БанкИД". К сожалению, не все банки "идут на контакт", поэтому не все есть в списке.

Поясню еще, что БанкИД или ЭЦП -- это как подтверждение Вашей личности третьей стороной. 
ЭЦП -- Вы "подтверждаетесь" налоговой (или тем органом, который выдал Вам эту подпись)
БанкИд -- соответствующим банком (поскольку при заведении счета банк сверял Ваши паспортные и другие данные, поэтому он может "гарантировать", что под этим логином зайдете именно Вы). 
Вполне возможно, что в дальнейшем список способов авторизации расширится (MobileID, например), но пока он только такой.

**Comment by alex-xander-dp-ua** [comment]
Авторизация в IGOV через банк Михайловский не работает.
Просто происходит авторизация с заходом на интернет-банкинг Михайловского.

**Comment by alex-xander-dp-ua** [comment]
Авторизация через Фидобанк не работает - сразу происходит переход на главную страницу сайта банка.
