### ISSUE TITLE
Время напомнить

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#160]
>Марина Кельменчук
Добрый вечер. На 25.12 регистрировалась в электронной очереди - Щурова И.В. Не могли бы время напомнить.

https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1645786652376878&comment_tracking=%7B%22tn%22%3A%22R%22%7D

Время у нас посмотреть где можно в личном кабинете? В письме?

**Comment by dmitrijzabrudskij** [comment]
добрый день
Марина, какая это услуга? время всегда шлется в письме после регистрации с адреса noreply@igov.org.ua - попробуйте найти в почте

**Comment by VadymVolos** [comment]
Я тоже думал в письме должно быть, на всякий случай уточнил тут.
