### ISSUE TITLE
Кривий Ріг - довідка про доходи - перший раз чують

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#161]
>Алексей Журавко
Здравствуйте. Я заказал справку о доходах неделю назад. Сегодня сам съездил в налоговую. Они про сайт вообще не знают и очень удивляются. На сайте написано, что услуга в Кривом Роге доступна. Может это ошибка?

https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1646477008974509&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by dmitrijzabrudskij** [comment]
могут и не знать - для сотрудников района это все выглядит как стандартная процедура выдачи справки о доходах

**Comment by VadymVolos** [comment]
Дмитрий Забрудский какая именно инспекция и когда подавали?
18 декабря в 17:39
Алексей Журавко Дзержинского района и подавали 10 числа вечером.
18 декабря в 17:42
Алексей Журавко Номер заявки - 27161035

Таску можна закривати чи ще ні?
