### ISSUE TITLE
Заява про державну реєстрацію шлюбу

### ISSUE THREAD

**Issue by raiair** [e-government-ua/iForum#162]
Добрый день. 
Мы создали обращение:

Номер звернення: № 145337
Вид звернення: звернення для заяви
Дата формування звернення: 22.07.2015
Дата подання звернення: 18.12.2015
Вид заяви: про державну реєстрацію шлюбу
Статус звернення:Подано

В связи с отсутствием цифровых подписей,  18.12.2015 утром мы записались на прием  на 10 часов 19.12.2015 в Відділ державної реєстрації актів цивільного стану реєстраційної служби Броварського міськрайонного управління юстиції у Київській області.

19.12.2015  работник РАЦС нам сообщила, что нашего обращения не видит и  что сайт igov на реконструкции.  

Поменяли РАЦС  на центральный. Заявку обработали в течении часа. 

Вопрос: Броварской  РАЦС  еще подключен к данной системе или работник РАЦС не знает как работать с ней?
Если не все РАЦС работают с этой системой, то имеет смысл скрыть данные отделы.

Также большая просьба сделать инструкцию или подсказки по заполнению обращения так как столкнулись со следующими проблемами:
1. Копии каких страниц паспорта необходимо подавать (все страницы с  пропиской или только последнюю и т.п.)
2. Подготовили файл  с копиями паспорта и кода в формате  doc, чтоб было одним файлом, и только при выборе файла для загрузки узнали что необходим формат jpeg.
3. Есть ограничение на размер прикрепляемого файла не более 1 МБ. Это было обнаружено  когда часть файлов загрузилась а часть нет. 
4. Возможность загрузки сразу нескольких файлов  не очевидна.

**Comment by GrekD** [comment]
@raiair 
Добрый день
дайте, пожалуйста, ссылку на услугу - думаю, что Вы подавали ее на стороннем сайте.

**Comment by raiair** [comment]
Добрый день. 

Выкладываю ссылку на услугу: http://dracs.minjust.gov.ua/Appeal/ByType/Q 

Попадаю на данную страницу следующим образом: 

https://igov.org.ua/subcategory/1/20 - "Громадянам: Родина" 

Выбираем "Подати заяву про державну реєстрацію шлюбу" и попадаем на 

https://igov.org.ua/service/703/general - "Подати заяву про державну реєстрацію шлюбу 
Реєстраційна служба управління юстиції" 

На этой странице  сообщение 
"Для одержання послуги потрібно зареєструватися на порталі та скористатися електронно-цифровим підписом" 

При нажатии на кнопку перейти попадаем на сайт http://dracs.minjust.gov.ua/ 

Здесь заходим под своим логином и видим заявку. 



22 декабря 2015, 10:55:24, от "Darja Grek" < notifications@github.com >: 

@raiair 
Добрый день 
дайте, пожалуйста, ссылку на услугу - думаю, что Вы подавали ее на стороннем сайте. —

**Comment by GrekD** [comment]
@raiair 
на портале iGov на эту услугу стоит переадресация на сайт минюста. Т.е. получается все Ваши вопросы необходимо адресовать им.

**Comment by raiair** [comment]
Добрый день. 
Большое  спасибо, что уделили время. 
К сожалению у меня сложилось неправильное представление, что по данным вопросам необходимо обращаться к Вам. 
Возможно имеет смысл информировать пользователей услуг, на которые стоит переадресация на другие сайты, куда необходимо обращаться при  проблемах с использованием соответствующей услуги. 
Я думаю, что это позволит экономить Ваше время. 
Мы благодарны Вам за Вашу работу.
