### ISSUE TITLE
Нет ответа по субсидии

### ISSUE THREAD

**Issue by tanusa** [e-government-ua/iForum#163]
Здравствуйте. Моя заявка № 18333339   на субсидию взята в работу с 23.11.2015 г.Уже прошел месяц и никаких изменений статуса.Как я могу узнать,начислят мне субсидию или нет? Мой адрес tanusa.82@mail.ru  Лененский район,спасибо.

**Comment by GrekD** [comment]
@tanusa вопрос еще актуален?

**Comment by tanusa** [comment]
нет спасибо.
