### ISSUE TITLE
Субсидия

### ISSUE THREAD

**Issue by OlegKaspari** [e-government-ua/iForum#164]
Заявка на оформление субсидии № 26164194. Я снимаю квартиру. Позвонили с соц службы, сказали принести договор аренды, жена принесла, но от нее потребовали какие-то дополнительные справки с электросети, водоканала, горгаза, теплокоммунэнерго, жека. Правомочны ли их требования и какие справки им надо? Заранее спасибо за ответ.

**Comment by dmitrijzabrudskij** [comment]
справки не нужны. с 01.10.2015 требование об оформлении лицевых счетов на заявителя стало необязательным. подскажите в какой район подавали заявку?

**Comment by OlegKaspari** [comment]
Здравствуйте. Подавали через сайт igov.org.ua. Находимся в г. Марганец. Вызывали в Марганецкий  УТСЗН.

**Comment by dmitrijzabrudskij** [comment]
спасибо за информацию. с районом дополнительно переговорим. справки от коммунальщиков не нужны

**Comment by OlegKaspari** [comment]
Скажите, а справка с ЖЭКА нужна?

**Comment by dmitrijzabrudskij** [comment]
тоже сами должны запрашивать. вот договор аренды могли попросить - этого у них нет

**Comment by OlegKaspari** [comment]
Можно ли  как-то повлиять на работников УПСЗН, ответственных за субсидии? Куда жаловаться?

**Comment by dmitrijzabrudskij** [comment]
вы внимательно читаете? я же написал выше, что переговорим с районом
