### ISSUE TITLE
Не понятно где брать документы, которые нужно загружать в igov и как они должны выглядеть

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iForum#165]
Давайте посмотрим на типичную форму заявки на какую-то услугу .
![1](https://cloud.githubusercontent.com/assets/1929332/11936783/aea0a978-a818-11e5-9beb-48a29859b713.png)

Как видим, для получения услуги требуется загрузить 4 документа, которые совершенно непонятно, где взять. В результате человек, пожелавший воспользоваться услугой, всё-равно вынужден идти лично к чиновнику, просить бланки, помощи в заполнении, подсказок куда идти и в каком порядке. И вот мы снова получаем бюрократию и коррупцию. 

Предложения:
1. Если какой-то из документов, требуемых для услуги, может быть получен как результат другой услуги - справа от кнопки "Обрати файл" должна быть ссылка на эту услугу
2. Если какой-то из документов, требуемых для услуги, это просто заявление по определённому бланку - справа от кнопки "Обрати файл" должна быть ссылка на бланк
3. Если предыдущие два пункта невозможны - справа от кнопки "Обрати файл" должна быть ссылка на объяснение (возможно, на стороннем сайте) где и как получить данный документ

Имеет смысл?

**Comment by GrekD** [comment]
@ezhikus 
дайте ссылку на услугу, пожалуйста

**Comment by ezhikus** [comment]
Это проблема не конкретной услуги, а глобально, на счёт всех услуг. Кнопка "Обрати файл" для загрузки документа есть, а как этот документ должен выглядеть и где его брать - непонятно. Скриншот выше из "дозволу на розміщення зовнішньої реклами". Я думаю нужно поручить отвественным за каждую услугу сформировать ссылки, о которых я говорил выше.

**Comment by Koffeek** [comment]
@ezhikus По пунктам предложений
1. Это есть и так, просто пересекающиеся услуги почти отсутствуют
2. Любые бланки переведены в принтформы, которые печатаются госслужащим при обработке заявки (исключения описаны)
3. Объяснение справа невозможно по архитектуре портала. Как получать некоторые документы зачастую органы их запрашивающие до нас не доводят, т.к. услуги реализуются в основном через ЦНАПы

**Comment by ezhikus** [comment]
@Koffeek неужели мы никак не можем помочь человеку, который не знает, где взять данный документ? Он же просто уйдёт с портала, навсегда. Ну может хотя бы телефон\сайт ЦНАПа предлагать для получения информации?
