### ISSUE TITLE
Полностью не работает услуга подтверждения данных юр.лица

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#166]
вот эта услуга
https://igov.org.ua/service/770/general
полностью не работает!!!

**Comment by GrekD** [comment]
@NizhnikAlex 
посмотри, пожалуйста

**Comment by NizhnikAlex** [comment]
Добрый день. Ночью ошибка была исправлена

**Comment by AndreyPopovNew** [comment]
наконец-то заработало. заявку приняло.


поправьте описание услуги:

тут https://igov.org.ua/service/770/instruction сказано:

 Завантажте актуальний бланк Форми-6 за посиланням, заповніть його, збережіть у форматі PDF та завірте своїм цифровим підписом.

но ведь в форме этого делать НЕ НАДО!

и опять же в форме есть поле "Форма 6:" - там раньше была ссылка на файл формы. а сйчас она зачем?
![image](https://cloud.githubusercontent.com/assets/8410116/11954556/3545f4c6-a8b2-11e5-9744-eeade96361ac.png)

**Comment by AndreyPopovNew** [comment]
вопрос следующий:
 - если вошел в систему по ЭЦП
- вошел в услугу по ЭЦП
то почему автоматом не стоит галка на "Накласти ЕЦП"?????

**Comment by NizhnikAlex** [comment]
Пока только пробуем такой вариант подачи. Для удобства тестирования можно подать и без ЭЦП, просто реальную заявку в таком случае отклонят.

Описание поправим. Спасибо за замечание.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex а Форма 4 - кто за нее отвечает?

**Comment by NizhnikAlex** [comment]
Моя изначально. Сейчас изучаем новые законы, после этого будем решать что с нею делать.

**Comment by AndreyPopovNew** [comment]
так расскажите как PDF подписать ЭЦП ДФС?

**Comment by NizhnikAlex** [comment]
Для Приватовской подписи использую signtools.
Для налоговой, по идее, подойдет http://acskidd.gov.ua/korustyvach_csk
АЦСК Украина - не знаю точно, надо в Медке глянуть. Хотя, не исключаю, что нет софта для подписи.

**Comment by AndreyPopovNew** [comment]
указанный софт подписывает как-то "по своему", а не так как это принято в том же Adobe Acrobat

![image](https://cloud.githubusercontent.com/assets/8410116/11956854/09a32eba-a8c6-11e5-9070-57a3a59fbf18.png)

**Comment by NizhnikAlex** [comment]
Да. Кроме того, акробатом не проверишь такую подпись. Думаю, эти вещи больше связаны с законодательством и самой структурой ЭЦП

**Comment by AndreyPopovNew** [comment]
почему не проверишь?????

![image](https://cloud.githubusercontent.com/assets/8410116/11957299/9d905ed8-a8c9-11e5-9ee7-73895911aa81.png)

**Comment by AndreyPopovNew** [comment]
тем более там есть кнопка проверить подписи

![image](https://cloud.githubusercontent.com/assets/8410116/11957330/d7ca9c9e-a8c9-11e5-98fb-017ffe007940.png)


![image](https://cloud.githubusercontent.com/assets/8410116/11957336/e5ff05fc-a8c9-11e5-8b25-d105e23a3cb4.png)

**Comment by NizhnikAlex** [comment]
Это от налоговой? Приватовскую у меня не хочет открывать

**Comment by NizhnikAlex** [comment]
![default](https://cloud.githubusercontent.com/assets/13959354/11957379/2566e3f4-a8ca-11e5-9a8e-6bf7ff6158b2.PNG)

**Comment by AndreyPopovNew** [comment]
это ДТЭК - www.doe.com.ua - сдача отчетности по электричесву

ключи от https://cesaris.itsway.kiev.ua/public/default.aspx

**Comment by AndreyPopovNew** [comment]
по английски звучит - has problem - имеет проблему, а не недействительна

[Форма 4_КС_data_1_signed_both.pdf](https://github.com/e-government-ua/iForum/files/69803/4_._data_1_signed_both.pdf)

**Comment by NizhnikAlex** [comment]
Я и не писал про недействительность. Писал, что невозможно проверить. В принципе, не так важно - у нас проверка все равно не через акробат происходит.

**Comment by AndreyPopovNew** [comment]
ну просто подписывание ключами ДФС отличается от "стандартного понимания" подписывания документов. потому думаю надо инструкцию сделать - чем и как подписывать.

а то фраза "Заповніть форму, збережіть її в PDF форматі та завірте ЕЦП" уж больно расплывчата и непонятна

**Comment by AndreyPopovNew** [comment]
прошло три  полных рабочих с момента подачи заявки.

нет никаких ответов. телефон для справок указанный в ответе на мыло никто не берет!

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex 
еще раз пишу НИКАКИХ ответов НЕ ПРИШЛО!!!!

указанный телефон в сообщении НЕ отвечает, никто не берет трубку!

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex  подскажите, я как бы рад, что мне пришли подтверждения:

28.12.2015 17:34	Ваша заявка №0-43462009 змiнила свiй статус на Заявка виконана
28.12.2015 17:33	Ваша заявка №0-49008886 змiнила свiй статус на Заявка виконана
28.12.2015 17:32	Ваша заявка №0-48922541 змiнила свiй статус на Заявка виконана
28.12.2015 17:31	Ваша заявка №0-43239791 змiнила свiй статус на Заявка виконана
28.12.2015 17:28	Ваша заявка №0-54646640 змiнила свiй статус на Заявка виконана
28.12.2015 15:15	Ваша заявка №0-47848149 змiнила свiй статус на Заявка виконана

но что ЗНАЧИТ статус "выполнена"?

на мыло пришло:
Ваше подання опрацьовано адміністратором ЦНАП та надано державному реєстратору

и дальше что? изменения внесены? зарегисрированы?

**Comment by GrekD** [comment]
@AndreyPopovNew 
Ваше подання опрацьовано адміністратором ЦНАП та надано державному реєстратору
и дальше что? изменения внесены? зарегисрированы?

Ваше обращение передано государственному регистратору, по результатам рассмотрения прийдет еще одно писмо.

**Comment by AndreyPopovNew** [comment]
@GrekD ну так статус "выполнена" должен стоять уже ПОСЛЕ завершения рассмотрения.

может быть статус должен быть "принята для виконаня"

просто по логике вещей - если  заявка выполнена, то изменения уже должны быть внесены!

**Comment by AndreyPopovNew** [comment]
@GrekD 
@NizhnikAlex 

так что дальше с регистрационными данными?

**Comment by NizhnikAlex** [comment]
Ничего. В изменениях законодательства, вступивших в силу с 1.01.2016 форма 6 отменена

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex  а Форму 4 тоже отменили?

 Зміна додаткової інформації про зв`язок з юридичною особою (Форма-4)

и 

 Зміна кінцевих бенефіціарних власників (контролерів) або зміна відомостей про кінцевих бенефіціарних власників (контролерів) юридичної особи (Форма-4)

**Comment by NizhnikAlex** [comment]
Сильно поменяли. Добавилась (или изменилась) платность услуги, регламент поменялся. Местный МинЮст пока не знает как и что будет работать, пока убираем и эту форму с сайта

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex так услуги регистрации работают?

**Comment by NizhnikAlex** [comment]
нет. Услуги не предоставляются (идут отказы), в следующую версию отключаются.

**Comment by AndreyPopovNew** [comment]
но я подавал еще ДО Нового года - значит они должны были быть приняты и обработаны.

вот меня и интересует их судьба!

**Comment by NizhnikAlex** [comment]
Какие вы конкретно услуги заказывали, какой датой и под какими номерами?
Если поданы 31-го, то тоже вряд ли обрабатывались.

**Comment by AndreyPopovNew** [comment]
я подавал:
- Підтвердження відомостей про юридичну особу (форма 6)
- Зміна додаткової інформації про зв`язок з юридичною особою
- Зміна кінцевих бенефіціарних власників (контролерів) або зміна відомостей про кінцевих бенефіціарних власників (контролерів)

чуть выше есть список номеров заявок, которые числятся выполнены.
какие номера конкретно соответствуют заявкам - не знаю.

все подавались в период с 18 по 22 декабря 2015 года.

**Comment by NizhnikAlex** [comment]
Попробую найти, но уже с понедельника.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex сегодня вторник - есть новости по заявкам?

**Comment by NizhnikAlex** [comment]
№0-54646640 данные подтверждены

**Comment by NizhnikAlex** [comment]
форму 4 не нашел. Практически нереально искать. Можете посмотреть здесь https://usr.minjust.gov.ua/ua/freesearch актуальны ли данные (бесплатный запрос).
Там же, кстати, есть информация и подтверждены или нет данные

**Comment by AndreyPopovNew** [comment]
я практически каждый день смотрю бесплатный запрос с 25-го декабря.

данные НЕактуальные.

т.е. непонятно - то ли запрос отклонили, но по каким причинам непонятно, то ли не обработали.

**Comment by NizhnikAlex** [comment]
Значит отклонили (заявка закрыта).

**Comment by AndreyPopovNew** [comment]
т.е. узнать что произошло таки - не представляется возможным. почему отклонили - тоже "тайна за семью печатями"
