### ISSUE TITLE
субсидия

### ISSUE THREAD

**Issue by booratyna** [e-government-ua/iForum#168]
Здравствуйте! Днепропетровск, Бабушкинский район. Заявка на субсидию 14357738 принята в работу 6.11. На 22.12 никакого ответа не получено. Положенные на рассмотрение двадцать рабочих дней давно вышли. Что делать дальше? Спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день!

Ваша заявка еще в работе. Вам ответят когда будет решение

пс: 20 дней - это, так сказать, при "попутном ветре" - не редки случаи, когда дольше...

**Comment by annastolbova** [comment]
Заявка закрита 29.12.2015, 
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
