### ISSUE TITLE
Помогите пожалуйста  узнать ответ по субсидии

### ISSUE THREAD

**Issue by tanusa** [e-government-ua/iForum#169]
Здравствуйте. Моя заявка № 18333339 на субсидию взята в работу с 23.11.2015 г. Уже прошел месяц и никаких изменений статуса.Как я могу узнать,начислят мне субсидию или нет? г. Днепропетровск, Ленинский район,спасибо.

**Comment by dmitrijzabrudskij** [comment]
добрый день
Ваша заявка в работе у района. По результатам ее рассмотрения Вы получите письмо с решением по субсидии. Вы так же можете сами перезвонить в район и уточнить текущий этап (056 372 19 67)

**Comment by tanusa** [comment]
А как мне спрашивать,назвать им номер заявки или по фамилии?

**Comment by dmitrijzabrudskij** [comment]
и так и так можно. они найдут

**Comment by tanusa** [comment]
спасибо большое
