### ISSUE TITLE
соц помощь при рождении ребенка

### ISSUE THREAD

**Issue by aldn001** [e-government-ua/iForum#17]
Добрый День! Заявка 4699547 была подана 24.09, но по сей день никаких сдвигов по ней нет. Хотя обещали что заявка будет обработана в течении 10 дней. Можно ли ускорить этот процесс. Спасибо

**Comment by dmitrijzabrudskij** [comment]
обработали. но вообще со следующей недели все должно ускориться - районные отделения соцзащиты ждут согласования еще некоторых юрилических вопросов. потому сеййчас 10 дней не выдерживаются

**Comment by marinaneg** [comment]
Я не записала номер заявки и не помню когда ее оформила. В журнале стоит статус что заявка принята. Как узнать ее статус? По-моему уже прошло 10 дней. спасибо!

**Comment by dmitrijzabrudskij** [comment]
скажите район. дату подачи (если помните) и фио от кого подавалась

**Comment by marinaneg** [comment]
Днепропетровск, где-то 26-28 от Дилевская Марина Леонидовна

**Comment by marinaneg** [comment]
26-28 сентября

**Comment by marinaneg** [comment]
Уже ответила на форуме, но продублирую еще здесь: подавала где-то 26-28
сентября в Днепропетровске Дилевская Марина Леонидовна. спасибо!

2015-10-09 12:14 GMT+03:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by dmitrijzabrudskij** [comment]
какой район Днепропетровска выбирали при подаче?

**Comment by dmitrijzabrudskij** [comment]
нашел. забраковали сегодня с такой формулировкой:
Неможливо відкрити паспортні дані

подайте еще одну заявку, пожалуйста

**Comment by marinaneg** [comment]
оформила еще одну заявку, но там паспортные данные загружаются
автоматически через bankid. Какая гарантия что в этот раз они их смогут
открыть?

2015-10-12 18:38 GMT+03:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by dmitrijzabrudskij** [comment]
номер заявки и в какой район подали?

**Comment by marinaneg** [comment]
номер 8455757 в анд

**Comment by dmitrijzabrudskij** [comment]
с паспортом в этот раз проблемы нет. но реквизиты банка не заполнены

**Comment by marinaneg** [comment]
Какой статус у заявки номер 9961251 оформлена в Днепропетровске АНД район
на Дилевская Марина Леонидовна 20 окт 2015? Спасибо!

2015-10-15 15:56 GMT+03:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by dmitrijzabrudskij** [comment]
ожидает обработки
работаем над тем, чтобы районы все вовремя обрабатывали. к сожалению, не со всеми получается сразу

**Comment by marinaneg** [comment]
Спасибо, сегодня уже позвонили из органов.

2015-11-04 11:32 GMT+02:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by dmitrijzabrudskij** [comment]
а чего звонили?

**Comment by marinaneg** [comment]
нужно приехать и еще привезти документы.

On Wed, Nov 4, 2015 at 11:20 PM, dmitrijzabrudskij <notifications@github.com

**Comment by dmitrijzabrudskij** [comment]
опишите пожалуйста какие еще документы попросили?

**Comment by aldn001** [comment]
У меня просили копии паспорта жены

**Comment by aldn001** [comment]
но уже две недели тишина. Можно уточнить статус заявки 7382278 ?

**Comment by dmitrijzabrudskij** [comment]
aldn001: какой район выбирали?

по поводу документов вопрос был Марине

**Comment by aldn001** [comment]
Район Индустриальный

**Comment by aldn001** [comment]
Можно ли в Собес обращаться по этому номеру заявки и проверять результаты? И есть ли у вас прямы контакты людей которые этот вопрос курируют на местах?

**Comment by dmitrijzabrudskij** [comment]
тел 760-24-98. попробуйте

**Comment by marinaneg** [comment]
Просили привезти все стандартные документы, паспорт, код, свид о рождении
(оригиналы и копию)
