### ISSUE TITLE
Когда снова будет возможность заказать электронную версию справки об отсутствии судимости?

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#171]
https://igov.org.ua/service/1/general

в конце ноября была анонсирована возможность заказать электронную версию.

что мною и было сделано:
30.10.2015 16:49	Ви подали заявку на послугу Днепропетровск - Надання довідки про відсутність або наявніcть судимості!. Cтатус: Заявка подана

ответа так и нет и на сегодня доступна только возможность в бумажном виде.

**Comment by Koffeek** [comment]
@AndreyPopovNew 
Получение данной справки с ЭЦП будет возможно после окончания реорганизации в МВД в связи с вступлением в силу ЗУ "О национальной полиции". Это прояснит принадлежность департаментов их новые названия и позволит получать корректные ЭЦП для заверения справок.

**Comment by AndreyPopovNew** [comment]
@Koffeek @GrekD  @bvv4ik 
сделал заявку 0-121514826
указал в электронном виде
пришел ответ:
Ваш запит успішно оброблено.
Оригінал довідки Ви зможете отримати за адресою
м. Дніпропетровськ, вул Ворошилова, 21 Графік прийому:
Графік прийому:
з 15:00 до 17: 00 (крім вихідних)


статус в журнале отображается "криво":
![image](https://cloud.githubusercontent.com/assets/8410116/13773973/fcf00406-eaa4-11e5-84ca-8874bd4a965b.png)
