### ISSUE TITLE
В письме об отказе в предоставлении услуги - предлагать пересоздать заявку

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iForum#172]
Иногда (есть подозрение, что часто) люди будут получать отказ по заявке с аргументацией о неверно заполненной заявке, ошибках, не тех прикрепленных документах. В этом случае людям придётся заново заходить на igov, искать услугу, перенабирать все поля - ну и исправлять ошибку - колоссальная трата времени. Было бы отлично в письме об отказе сделать кнопку "Пересоздать заявку на основе отклонённой", которая бы перекинула пользователя на страничку создания аналогичной заявки с уже заполненными всеми полями (из прошлой, отклонённой заявки). Человек сможет лишь исправить ошибку и подать заявку снова. Огромная экономия времени на подаче повторной заявки - может быть до десятков минут!

**Comment by Koffeek** [comment]
@ezhikus Сейчас ведётся работа по сохранению определённых полей при создании заявки для бека портала. При включенном автозаполнении форм в браузере значения полей и так будут подбрасываться (исключения телефон, календарь и поля для ввода большого количества текста).
