### ISSUE TITLE
Отримання субсидії на оплату житлово-комунальних послуг

### ISSUE THREAD

**Issue by pogrenat** [e-government-ua/iForum#173]
Здравствуйте! Заявка 22580883 от 1 декабря 2015, г. Кривой Рог, Терновской р-он.Получила на адрес pogrenat1@gmail.com ответ: Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг опрацьовано.

Розмір субсидії вказаний у файлі, який прикріплено до цього листа.

Файл, прикрепленный к письму, имеет формат rp026276.d99 и, соответственно, не читаемый. Помогите узнать содержимое вложения. Спасибо.

**Comment by spectr327** [comment]
Тот же вопрос,как открыть этот файл? Вчера такое же письмо пришло

**Comment by AndreyPopovNew** [comment]
судя по принципу по которому работают программы наложения цифровой подписи от нашей налоговой и минюста, то они меняют расширение файла.

попробуйте переименовать файл в расширение .doc

**Comment by pogrenat** [comment]
Здраствуйте! А что значит - попробуйте? Т.е., Вы сами не уверены, что так файл раскроется? А инструкцию, как это сделать? не все ж заявители - опытные айтишники. Судя по форуму, такие вложения приходят не всем, значит, можно и нормальный файл отправить?

**Comment by AndreyPopovNew** [comment]
я такой же пользователь как и вы. и сказать точно что за файл вам пришел не могу.

ответ вам присылает орган соц.защиты

там операторы сидят далеко не ИТ специалисты.

им сказали к примеру наложить ЭЦП на файл ответа - они наложили и отослали файл.

просто видя как "идиотски" работают инструменты подписи ДФС и МинЮста - я вам дал совет.

сохраните пришедший файл и переименуйте расширение в .doc или .rtf или .txt

**Comment by dmitrijzabrudskij** [comment]
всем добрый день

@AndreyPopovNew этот файл они из своей внутренней программы получают и должны распечатать, и уже скан распечатанного отправить в ответе на заявку. как видите не все придерживаются этой процедуры

@pogrenat запросил Ваш скан у района. как сделают - пришлю

@spectr327 дайте номер заявки и район - постараюсь разобраться

**Comment by dmitrijzabrudskij** [comment]
@pogrenat выслал на почту решение по субсидии. район тоже наконец разобрался как нужно делать:)

**Comment by pogrenat** [comment]
спасибо огромное!!!! только все-равно теперь другой вопрос, но , наверное, уже не непосредственно к Вам. В тексте написано *назначена субсидия с декабря 2015 по ноябрь 2016 включительно ежемесячно*. В самом конце *Дата назначения 1 января 2016*. Меня смущает декабрь - на него будет субсидия? И как будут рассчитываться суммы, при расходах свыше установленных норм? У меня непреодолимое желание пообщаться с теми, кто назначает субсидии. У Вас нет их номера случайно? Еще раз благодарю за помощь и оперативность

**Comment by AndreyPopovNew** [comment]
- субсидия назначена с декабря 2015
- счета за декабрь 2015 будут выставляться в январе 2016 - вот там и будет уже фигурировать субсидия

порядок по субсидиям такой:
1. у вас по каждой услуге указан минимально необходимый платех платеж (последняя колонка)
2. также указана социальная норма - на сумму свыше социальной нормы субсидия уже НЕ распространяется.

порядок такой(по каждой услуге отдельно):
- если сумма за месяц меньше минимального платежа, то вы платите только эту сумму
- если сумма за месяц больше минимального платежа, но меньше или равна социальной норме, то вы платите минимальный платеж
- если сумма за месяц больше социальной нормы, то вы платите минимальный платеж и разницу между суммой и социальной нормой

это по каждой услуге ОТДЕЛЬНО! субсидией от одной услуги НЕВОЗМОЖНО компенсировать затраты по другой услуге!

Примеры:
- электричество
социальная норма 96грн., минимальный платеж 18,50
вы за месяц намотали 120кВтч - это 62грн.

вы платите 18,50 грн., а 43,50 субсидия

- газ
социальная норма 130грн., минимальный платеж 27,00
вы за месяц сожгли 3 куб.м - это 22грн.

вы платите 22 грн.


- отопление
социальная норма 960грн., минимальный платеж 210,00 грн.
вы за месяц ЖЭК вам выставил 1950 грн.

вы платите 210 грн. и доплачиваете 1950-960=990 грн. - итого 1200грн.

**Comment by spectr327** [comment]
мой номер заявки 13921502
Днепропетровск 
Амур Нижнеднепровский район

**Comment by spectr327** [comment]
мой номер заявки 13921502
Днепропетровск
Амур Нижнеднепровский район

24 декабря 2015 г., 11:20 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by pogrenat** [comment]
AndreyPopovNew вопросы к Вам (от блондинки )))) ). Если рассматривать социальные нормы не в гривнах, а в потребляемых объемах,то:
1. на газ (отопление) соц.объем мне выделен 335м3. Если я потреблю 200м3 - сколько платить минимум - то, что мне указали или я должна высчитать другую сумму? что происходит с остатком - он переносится на след. м-ц или обнуляется?
2. на газ (отопление) если я потреблю больше 335 - по какому тарифу это будет считаться , как до 200 по 3.6 или по 7.18?
ПыСы. Сейчас общалась с теми, кто назначает субсидии, сказали, что при потреблении, меньшем чем соц.норма - оплачивается объем по действующему тарифу. Другими словами, если я потребила, например, не 335, а 320, то платится 200х3.6+120х7.18=..  Что это за бред? В чем прелесть этих субсидий?

**Comment by AndreyPopovNew** [comment]
с отоплением(газ) вопрос отдельный, потому что 200м3 в месяц по цене 3,6 - это УЖЕ субсидия!!!!

потому на объем до 200м3 вы будите платить оплачивать все по цене 3,60

а вот что больше 200м3 по цене 7,18.

но у вас то субсидия в гривнах указана, а не в объемах, и минимальный платеж в гривнах.

никакие остатки на следующий месяц не переходят. кроме разве если вы потребите меньше 200м3 - то типа можно перенести на другой месяц.

в уведомлении о назначении субсидии сказано, что если потреблено меньше минимального платежа, а не меньше социальной нормы!!!!! - то платится фактическая стоимость потребленного по текущему тарифу.
социальная норма - это предел, за которым уже никакие субсидии НЕ распространяются.

**Comment by pogrenat** [comment]
а можно я Вам вышлю мое повидомлення, а Вы мне разжуете, плиз? Субсидия, действительно в гривнах, но, ведь, на конкретные соц. нормы.....ужас какой-то...без бутылки не разберешься))))

**Comment by pogrenat** [comment]
кроме того, смотрела субсидию соседки, там по газу идет накопление неиспользованных гривен..во всяком случае, в личном кабинете по газу числится уже больше 3 тыс.грн. якобы переплаты...

**Comment by AndreyPopovNew** [comment]
по газу с отоплением "хитрая" схема
https://104.ua/ua/gas-and-money/how-costs/id/tarifi-dlja-riznih-kategorij-spozhivachiv-7315
раньше было 200м3 в месяц по цене 3,60, а потом сделали возможность 1200 м3 на полгода разбросать по месяцам как вам удобней.

но, при назначении субсидии все равно учитывается 200м3 в месяц.

можете высылать, а можете тут прикрепить.

**Comment by pogrenat** [comment]
![img_0001](https://cloud.githubusercontent.com/assets/16390295/12003420/9504830c-ab26-11e5-8447-8d95bd4ae902.jpg)

**Comment by pogrenat** [comment]
кажется, я поняла смысл этой заумной фразы....если я потреблю газа (отопление), например 15м3 ,т.е. меньше чем 77.93/3.6=21.65м3, то к оплате будет 15х3.6=54грн...правильно?

**Comment by AndreyPopovNew** [comment]
да правильно. если потребляете меньше обязательного платежа, то платите реальную сумму потребления.

теперь пример.

вы потребили на отопление 320 м3

вам считают: 200*3,6 + 120 * 7,18 = 1581,60. вы платите 77,93 - остальное должна быть субсидия.

если вы потребите на отопление 420 м3

вам считают: 200*3,6 + 220*7,18 = 2299,60. вы платите 77,93 и (2299,60 - 1761,67)=537,93


если вы потребите на отопление 120 м3

вам считают: 120*3,6 = 432. вы платите 77,93 - остальное должна быть субсидия.
перейдут ли 80м3 "в зачет"????? скорее всего нет, хотя бог его знает.

**Comment by pogrenat** [comment]
кстати, Вы не пробовали высчитать цену газа по субсидии? там странные цифры получаются
335.93м3 стоят 1761.67, из них 200х3.60= 720грн, 1761.67-720=1041.67грн на остальные 135.93м3,  1041.67/135.93= 7.663грн вместо 7.188? там при любой математике на 135.93м3 не получается тариф 7.188

а как быть со счетчиками в таком случае? передаешь фактическое, а платишь тот минимум? 
это потом такая путаница будет с показаниями....когда дают что-то надурняк - жди потом удара в спину с разборками показаний, долгов и переплат...

**Comment by AndreyPopovNew** [comment]
по правилам с 25-го предыдущего до 5-го следующего вы передаете показания.
на основании этих показаний вам выставляют счет (с 7-го числа по 10-ое осуществляется рассылка счетов). до 20-го числа месяца вы должны этот счет оплатить.

передавайте показания, дождитесь счетов - и не будет никакой путаницы.

хотя у нас все привыкли по "совковому" бежать в начале месяца платить и еще с переплатой "на всякий случай"

**Comment by pogrenat** [comment]
никуда не бегаю - передаю показания 1-го и сразу же оплачиваю, все через инет...в декабре попробую, как Вы говорите...сколько живу в своем доме - квитанций в глаза не видела. Спасибо за потраченное на меня время и объяснения. С наступающими!
