### ISSUE TITLE
Заявка на субсидію

### ISSUE THREAD

**Issue by Yammystar123** [e-government-ua/iForum#175]
Добрий день. Подала заявку 18303140 на субсидію, але не було в списку м. Черкаси. Тому обрала Смілу. Відповіді немаєбільше місяця. Я так розумію, Черкаси поки що не приймають участі в роботі порталу. Ви можте скасувати мою заяву або видалити, я збираюсь йти самостійно подавати документи. Дякую.

**Comment by AndreyPopovNew** [comment]
ее и так отклонят. не переживайте.

**Comment by Yammystar123** [comment]
Из за того что город неправильно выбран?

**Comment by AndreyPopovNew** [comment]
центр соц.защиты может рассматривать заявки тех, кто зарегистрирован на их территории.

вот каким образом центр соцюзащиты г.Смелы может рассмотреть заявку на субсидию жителя Черкасс?

**Comment by Yammystar123** [comment]
Ну ее даже в работу не приняли. Она просто в статусе створена больше месяца. Можно ее удалить, чтобы людям лишнюю работу не делать? А то она так висеть может еще вечность.

**Comment by AndreyPopovNew** [comment]
нашил за что волноваться.

**Comment by dmitrijzabrudskij** [comment]
@Yammystar123 забраковал. в списке не просто так только Смела есть - пока что только этот город участвует в проекте

**Comment by Yammystar123** [comment]
Спасибо за помощь. Странно конечно что Смела есть, а областной центр нет)
