### ISSUE TITLE
Заявка на получение загран. паспорта ребенку

### ISSUE THREAD

**Issue by TatyanaSorochik** [e-government-ua/iForum#176]
Добрый день. Зарегистрировала заявку на получение паспорта ребенку, но не получила на электронку письмо с перечнем док-тов и расчетными номерами.

**Comment by Koffeek** [comment]
@TatyanaSorochik Добрый день. Вопрос ещё актуален? Если да, то уточните, пожалуйста, в какое подразделение ДМС подавалась заявка и её номер.

**Comment by TatyanaSorochik** [comment]
Добрый день. Вопрос актуален. Мы записаны на 5 января на 15.00.,  на ул. Красная 2а. Номер заявки не записала, рассчитывая на письмо. В "Мой журнал" номер не показан.

**Comment by Koffeek** [comment]
@TatyanaSorochik Если Вы записаны на 5 января, то должны были как минимум получить письмо с моей почты, о том, что в связи с установкой оборудования для ID-карт работы программы по оформлению загранпаспортов 4-6 числа будет прекращена. Проверьте, пожалуйста, на всякий случай папку "Спам". Если ни одного письма нет. Напишите сюда или на zhigan.roman@gmail.com
