### ISSUE TITLE
заявка на субсидию от 13/11/15 Киев, Соломенский - нет ответа

### ISSUE THREAD

**Issue by nadiarum** [e-government-ua/iForum#177]
Здравствуйте. Как получить ответ по заявке 16408869?
подана 13/11/15, тел 2093912, 2093911 не отвечают. Киев, Соломенский.

**Comment by nadiarum** [comment]
Киев, Соломенский р-н

**Comment by dmitrijzabrudskij** [comment]
@olgakhomenko помогите пожалуйста

**Comment by nadiarum** [comment]
@olgakhomenko , помогите,  пожалуйста

**Comment by OlgaKhomenko** [comment]
Добрый день,
на данный момент есть проблемы со всеми соцуслугами города Киева, управления отказываются работать, т.к. Департамент соцзащиты против электронных услуг. Решаем с помощью руководства КМДА. Извините за неудобства.

**Comment by nadiarum** [comment]
Вот с...! От всей души желаю вашей команде сил и удачи! С наступающим!

Отправлено с iPhone

**Comment by bvv4ik** [comment]
"управления отказываются работать, т.к. Департамент соцзащиты против электронных услуг."

а у кого-то хватит мужества заставить их написать письменный отказ?

чтоб потом этот письменный отказ в всех СМИ, да с фамилиями.... чтоб потом поганой метлой таких у..... не только с соцзащиты, а и вообще "на задворки страны"!!!

ребята, если тут не занять принципиальную позицию - такую моду могут взять и другие "совковые микробы"!

**Comment by OlgaKhomenko** [comment]
Департамент соцзащиты в Киеве согласен работать с электронными услугами в том случае, если Министр им скажет работать с электронными заявками.

**Comment by nadiarum** [comment]
т.е. субсидия с субсидией и за ноябрь, и за декабрь я пролетела? Может, жалобу какую-то подать?

**Comment by bvv4ik** [comment]
"OlgaKhomenko commented a day ago
Департамент соцзащиты в Киеве согласен работать с электронными услугами в том случае, если Министр им скажет работать с электронными заявками."

А может департамент письменно это-же озвучить? Чтоб потом можно было-бы передать эту "письменную форму" министру... а министр так-же "письменно-бы и ответил")

**Comment by bvv4ik** [comment]
т.к. у меня есть информация, что министр Розенко полностью поддерживает проект iGov, за что граждане страны ему очень благодарны!) И создается ощущение, что "в разрез с его поддержкой" - идет "саботаж на местах")
