### ISSUE TITLE
Призначення соціальної допомоги при народженні дитини

### ISSUE THREAD

**Issue by ElenaMoroz** [e-government-ua/iForum#178]
Подали заявку 24712136 еще 12.12.2015. Прошло свыше 20 дней, а статус заявки не поменялся Заявка подана, хотя мы из Днепропетровской области. Начинаем разочаровываться в данном сервисе, а жаль(((((

**Comment by dmitrijzabrudskij** [comment]
какой район?

**Comment by ElenaMoroz** [comment]
Днепропетровский район

**Comment by dmitrijzabrudskij** [comment]
Ваша заявка в работе. когда будет решение - Вам его вышлют на почту

пс: 20 рабочих дней

**Comment by ElenaMoroz** [comment]
Так уже прошло 24 дня

**Comment by dmitrijzabrudskij** [comment]
еще раз - рабочие дни
можете перезвонить в район уточнить у них на какой стадии ваша заявка сейчас: (0562) 27 70 46

**Comment by ElenaMoroz** [comment]
Спасибо!

**Comment by ElenaMoroz** [comment]
Сегодня уже 11 января, заявка подавалась 5 декабря, а статус как был, так и остался "Заявка подана"((((((( Наверное, не готова Украина к таким новшествам. Жалеем о потраченном зря времени. Все, кто подавал заявку обычным способом, уже получили деньги(((

**Comment by ElenaMoroz** [comment]
Сегодня уже 11 января, а заявка подавалась 5 декабря, статус не изменился "Заявка подана". Наверное, не готова Украина к таким новшествам (((( Жалеем о потраченном времени. Все, кто подавал заявку обычным способом, уже получили деньги((((

**Comment by dmitrijzabrudskij** [comment]
заявка еще на рассмотрении. скорость ответа не зависит от способа подачи заявки. Вы можете уточнять у района состояние заявки в любое время (телефон я выше писал)
