### ISSUE TITLE
Письма от admin@mail.igov.org.ua Gmail считает спамерскими и складывает в "Спам" мимо папки входящих

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iForum#179]
![1](https://cloud.githubusercontent.com/assets/1929332/12002111/8f6fedea-aaff-11e5-8914-2b35736b3ee3.png)

Я пробовал на нескольких таких письмах нажимать "не спам", но это не помогло. Следующее письмо снова ложится в спам. Есть ли у нас (или у юнисендера?) какие-то способы сделать письмо менее "спамоподобным" ? Возможно, в письме должна быть ссылка на отписку от рассылки или наш сервер должен поддерживать какой-то общеизвестный протокол отписки от рассылок (Gmail вроде бы умеет отписываться от некоторых рассылок, если отсылающий даёт такую возможность).

Письма в "Спаме" - плохо, мы постоянно будем получать жалобы об отсутствии уведомлений.

**Comment by AndreyPopovNew** [comment]
на мое мыло admin@csa.dp.ua часто тоже не доходят некоторые рассsлки и письма.
их режет провайдер

по причине того, что он проверяет реальный ли ящик, с которого отослали сообщение. т.е. можно ли на этот ящик отослать письмо!
если на адрес, с которого отослано письмо нельзя отослать ответ, то провайдер тупо отбрасывает это сообщение.

**Comment by GrekD** [comment]
@bvv4ik можете, пожалуйста, передать проблему по адресу?

**Comment by ezhikus** [comment]
Письма теперь содержат строку "Якщо Ви не бажаєте отримувати цю розсилку, натисніть тут, щоб відписатись." и ссылку на отписку (через юнисендер). Gmail больше не считает их спамом. 
Предлагаю задачу закрыть.
