### ISSUE TITLE
Некорректная вёрстка страницы  при просмотре в нестандартных условиях

### ISSUE THREAD

**Issue by Pakirava-Datsuma** [e-government-ua/iForum#18]
1. При просмотре на телефоне подвал страницы перекрывает основное содержимое ![screenshot_2015-10-11-01-34-55](https://cloud.githubusercontent.com/assets/1230991/10413623/f31e0ab0-6fb9-11e5-885c-ba91eb87e2f3.jpg)
2. При увеличенном масштабе страницы фон пункта меню перекрывает заголовок ![2015-10-11 14 31 08](https://cloud.githubusercontent.com/assets/1230991/10416604/7f88f1a2-7025-11e5-8104-03829f8a96f6.png)

**Comment by GrekD** [comment]
@Pakirava-Datsuma добрый день!
должны были поправить, согласно ишью
https://github.com/e-government-ua/i/issues/932#issuecomment-174433171
можете проверить Ваш кейс, пожалуйста?

**Comment by Pakirava-Datsuma** [comment]
Мобильная верстка подвала не исправлена, меню в десктопной проверю позже

**Comment by Irynka** [comment]
Prosmotrite https://poligon.igov.org.ua/. Footer peredelali polnost'u. Kak i header.

**Comment by Pakirava-Datsuma** [comment]
Все ок

чт, 28 янв. 2016, 23:09 Iryna K <notifications@github.com>:
