### ISSUE TITLE
Сбои в работе igov.org.ua

### ISSUE THREAD

**Issue by stans** [e-government-ua/iForum#180]
23,24 и 25 декабря в журнале вместо № и даты заявок выполненных-невыполненных
вот такое :-1: 
![2015-12-25 12-02-05](https://cloud.githubusercontent.com/assets/16435836/12002259/cb4283a2-ab02-11e5-889f-8fe9509ba039.png)

При подаче последних двух заявок , на почту ничего так и не пришло
о статусе своих поданных заявок остается только догадываться !!!

Сайт и админы видимо уже "празднуют" ??!!

**Comment by AndreyPopovNew** [comment]
похожая проблема https://github.com/e-government-ua/iForum/issues/174
