### ISSUE TITLE
Не читаемый ответ по субсидии

### ISSUE THREAD

**Issue by spectr327** [e-government-ua/iForum#181]
Здравствуйте! Заявка №0-13921502  г. Днепропетровск, Амур-Нижнеднепровский район.
Получил на адрес spectr327@gmail.com ответ:
 Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг опрацьовано.

Розмір субсидії вказаний у файлі, який прикріплено до цього листа.

Файл, прикрепленный к письму, имеет формат .d25 и, соответственно, не читаемый. Помогите узнать содержимое вложения. Спасибо.

**Comment by AndreyPopovNew** [comment]
такая же тема
https://github.com/e-government-ua/iForum/issues/173

**Comment by dmitrijzabrudskij** [comment]
добрый день
@spectr327 запросил у района отсканированную копию уведомления, вышлю как только получу

**Comment by dmitrijzabrudskij** [comment]
@spectr327 выслал на почту отсканированные решения

**Comment by spectr327** [comment]
@dmitrijzabrudskij спасибо большое!
А теперь хотелось бы узнать,как вообще пользоваться субсидией? Нужно вовремя платить всё и сколько? Где бы прочитать инструкцию что бы мне субсидию выплачивали нормально,что бы со стороны плательщика не было косяков) Ибо в этих отсканированных решениях,не очень понятно на какие услуги какая сумма распространяется.

**Comment by dmitrijzabrudskij** [comment]
@spectr327 откройте и перечитайте вот эту тему: https://github.com/e-government-ua/iForum/issues/173

Андрей Попов уже подробно ответил на бОльшую часть вопросов
