### ISSUE TITLE
Призначення соціальної допомоги при народженні дитини Днепр, Бабушкинский р-н

### ISSUE THREAD

**Issue by nadlena** [e-government-ua/iForum#182]
В Журнале виду статусы без дат http://screencast.com/t/ons4R1qt9SDS
Заявка была мной подана 16.12. 17.12 был прислано письмо с информацией про статус "Запит на уточнення даних" (попал в Спам и был найден только сегодня 26.12 - столько время потеряла!).
Что означает этот статус?, Надо все таки идти записываться в очередь собеза и нести все документы?! Жаль, надежды на Ваш сервис не оправдались (хотя в загсе предупреждали, что лучше не пользоваться - только время потеряем)

**Comment by AndreyPopovNew** [comment]
такая же тема https://github.com/e-government-ua/iForum/issues/173

**Comment by AndreyPopovNew** [comment]
Запит на уточнення даних - это значит или не все документы подали или некорректно поля заполнили.

или может у вас кто-то числится частным предпринимателем с неоплаченными налогами и несданными отчетами.

**Comment by dmitrijzabrudskij** [comment]
@nadlena заявка номер 37029261 (для себя пишу). в какой район подавали?

@AndreyPopovNew сейчас не нужна эта справка (хотя заказать ее можно тоже с портала) - районы самостоятельно между собой уточняют эту инфу

**Comment by nadlena** [comment]
Да, я предприниматель. Со сданными отчетами и оплаченными налогами. И регистрация и проживание совпадают, район подачи тот же - Бабушкинский.
По возможности, напишите, пожалуйста,  мне ехать в соц.защиту лично и вести документы или возможно зарегистрироваться для получения помощи при рождении ребёнка через igov.org.ua?

**Comment by AndreyPopovNew** [comment]
@nadlena скорее всего вам придется подъехать. но поскольку ваша заявка уже есть (есть дело-папочка) то скорее всего попросят еще какую-то справку типа об отсутствии задолженности перед бюджетом (это я просто предполагаю).

понимаю, что вам не до того сейчас, чтобы ездить, но к сожалению без реального тестирования услуг данный проект не сможет заработать на "полную мощность".

@dmitrijzabrudskij "не нужна" - это нам с вами хочется, вы же реально сами знаете, что клеркам на местах "лишние движения" тоже делать не хочется.

**Comment by dmitrijzabrudskij** [comment]
@nadlena завтра разберусь с районом и дам ответ что нужно/не нужно по этой заявке. и вопрос для интереса - в каком загсе Вам такое сказали?

@AndreyPopovNew Андрей, это РАБОТАЕТ. запросы между собой они шлют без участия заявителя. и такие ветки, как эта, позволяют отлавливать как раз случаи "ленивых клерков" и направлять их на правильный путь.

**Comment by nadlena** [comment]
@dmitrijzabrudskij сказали, естественно, в Бабушкинском загсе при получении свидетельства о рождении - я рассказала о своих планах не ехать в соц.защиту, а оформить все через Ваш сервис.

Вопрос: меня (в школу) просят предоставить паспорт многодетной семьи (т.к. у нас уже 3 детей), сказали заказывать также в соц.защите. В перечне услуг не нашла. Я ее просто не вижу или она действительно еще не автоматизирована?
Спасибо

**Comment by dmitrijzabrudskij** [comment]
@nadlena Ваша заявка по детским деньгам в работе, ждут ответа, по его получению отправят Вам уведомление на почту

относительно загса - типичное поведение людей на местах, которые не верят ни во что, кроме старых схем и бумажных процедур..

по паспорту многодетной семьи - вот эта услуга: https://igov.org.ua/service/1430/general/
называется просто по-другому

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij ссылка ведет просто на главную страницу

**Comment by dmitrijzabrudskij** [comment]
@AndreyPopovNew ссылка ведет на саму услугу (по крайней мере у меня). может, у вас браузер режет хвост

**Comment by nadlena** [comment]
@dmitrijzabrudskij в какие сроки ожидать ответ? Вроде бы должны были ответить в течение 10 дней, т.е. 26 декабря

**Comment by dmitrijzabrudskij** [comment]
10 дней - это оптимистичный срок от соцзащиты, обычно они в него не укладываются - 2-3 недели срок, как показала практика

**Comment by nadlena** [comment]
добрый день. С праздниками!
Когда ожидать ответ по заявке №37029261? Скоро будет месяц с момента подачи заявки :(

**Comment by dmitrijzabrudskij** [comment]
добрый день
спасибо, и Вас!
выплата уже назначена, осталось дело за малым - выслать Вам на почту этот ответ. сегодня должны сделать. если не будет - маякните в эту ветку, плиз
