### ISSUE TITLE
Витяг з державного земельного кадастру про земельну ділянку

### ISSUE THREAD

**Issue by skirey** [e-government-ua/iForum#183]
Здравствуйте. 21.12.15 подал и оплатил заявку на получение витяга з державного земельного кадастру про земельну ділянку. До сих пор ответ так и не пришел. Подскажите пожалуйста, когда примерно ожидать результат. Г. Житомир Заявка # ЗВ-9900347762015

**Comment by Koffeek** [comment]
@skirey Добрый день. Похоже Вы оформляли заявку на сайте Кадастровой карты. Портал iGov по данной услуге предоставляет только перенаправление на Кадастровую карту и, к сожалению, не может отслеживать выполнение заявок. Спасибо.
