### ISSUE TITLE
Заявка на получение субсидии от незарегистрированного лица

### ISSUE THREAD

**Issue by Rublevskiy** [e-government-ua/iForum#184]
Здравствуйте,
Могу ли я подать заявку на получение субсидии на оплату ЖК услуг через iGOV,  войдя через свой BANKID, если я фактически оплачиваю эти услуги, но я не прописан и не проживаю по адресу, на который оформляется субсидия, а проживает и прописана моя сестра? Если да, то какие особенности заполнения заявки (например, "Место регистрации - адрес моей прописки или тот, на который оформляется субсидия")?

**Comment by AndreyPopovNew** [comment]
через iGov  вам субсидию не дадут, как и не дадут при личном обращении в собез!

у меня такая же ситуация, только квартира зарегистрирована на маму, а мам зарегистрирована по другому адресу (и живет там).

и хотя я зарегистрирован по адресу квартиры - но субсидия назначается только тому, на кого ОТКРЫТЫ лицевые счета.

выход есть - вы можете обойти все коммунальные службы и открыть на себя "временные" лицевые счета - вот тогда на вас и назначат субсидию.

хотя пусть подает ваша сестра, какая разница кто оплачивает.

**Comment by Rublevskiy** [comment]
спасибо за ответ. А если счета открыты: некоторые на меня, некоторые на сестру, а некот на отца?

**Comment by AndreyPopovNew** [comment]
надо, чтобы счета были открыты на ОДНО лицо, и еще лучше зарегистрированное по адресу.

по постановлению субсидия назначается лицу, которое зарегистрировано по адресу и на которое открыты лицевые счета.

**Comment by Rublevskiy** [comment]
Ясно, Спасибо
