### ISSUE TITLE
заявка на регистрацию авто с пробегом Киев 

### ISSUE THREAD

**Issue by Djohnypalace** [e-government-ua/iForum#185]
Одно из двух, или заявка идет вникуда, или тупо игнорится со стороны СЦ. 
54273833  2015-12-25 11:40:49.820	Заявка подана (на 16.01)
50786551 2015-12-23 13:49:57.816	Заявка подана ( на 26.12!!!! ) 
Я уже не говорю про то что слоты времени кроме как на Кольцевой так нигде и не появились. Глюк или тупой саботаж со стороны СЦ? :rage: 
Ну нет у меня сейчас ни денег ни желания кормить прилипал :fire: , а времени потратить пару дней прорываясь через искуственно создаваемые :cop:  очереди тоже нет... Я понимаю что такую кормушку (перерегистрация на столичке у прилипал - 3 тыс, Туполева 2.6 тыс,  Новоконстантиновская - 3 тыс...) они не хотят перекрывать, но надежда хоть есть?  :crying_cat_face:

**Comment by GrekD** [comment]
@kurbpa посмотри, пожалуйста

**Comment by Djohnypalace** [comment]
Вам відмовлено в реєстраціі авто.
Підстава: На жаль, з технічних підстав обробка Вашого звернення в належний термін була неможлива. Щиро вибачаємось за незручності.

**Comment by Djohnypalace** [comment]
@kurbpa
===8<==============Original message text===============
iGov
портал державних послуг
Шановний(-а) ОЛЕКСІЙ ВОЛОДИМИРОВИЧ.
Вам відмовлено в реєстраціі авто.
Підстава: На жаль через технічні ускладнення Ваше звернення неможливо було обробити в зазначений термін. 
Щиро вибачаємось за тимчасові незручності. 

З повагою,
Міністерство Внутрішніх Справ України,
Команда Порталу державних послуг iGov.org.ua. 




===8<===========End of original message text===========
это уже третий раз, третья заявка была подана за месяц :(

**Comment by kurbpa** [comment]
@Djohnypalace 

К сожалению в курсе... 
Приношу свои извинения за подобное... 
Обученные в свое время сотрудники МРЭО, были или уволены или ротированы в связи с глобальными реформами в МВД.  Сейчас воюем  за обучение новых сотрудников в Киеве и в Днепропетровске, которые смогли бы корректно работать с электронными заявками.

**Comment by Djohnypalace** [comment]
надежда есть? Когда приблизительно ожидать? (я уже не надеюсь на то что всего одним чекбоксом или стринглистом добавить возможность заявки на снятие с учета или перерегистрацию с продажей или замену техпаспорта к примеру для установки газа... т.к в реале.... перерегистрация за 500 грн миф - очередь 50 человек к открытию, из них 90% те самые барыги которые предлагают сделать все быстро но за 3000, а иначе до вечера ты будешь 45м в очереди :(

**Comment by kurbpa** [comment]
@Djohnypalace 

Надежда конечно есть, но не раньше февраля. 
Я обещаю, что поборем  эти неприятности.  Проект не похоронят. Дожмем. Запустим в нормальном режиме.
У меня также зависло ещё внедрение по 2 услугам из-за  подобной неопределенности.
* Восстановление/замена прав 
* Перерегистрация авто без смены владельца
