### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by anatooly** [e-government-ua/iForum#186]
Создайте Gitter комнату для разработчиков проекта, новичков, что бы новым кадрам (если в них есть необходимость) было проще вливаться в процесс, и в рамках обсуждения обмениваться техническим опытом по проекту.

**Comment by uncle-T0ny** [comment]
для этих целей есть слак чат

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
