### ISSUE TITLE
Встановлення статусу батьків та дитини з багатодітної сім’ї - Дніпропетровськ

### ISSUE THREAD

**Issue by nadlena** [e-government-ua/iForum#187]
При попытке заказать услугу в списке населенных пунктов только Царичанка
![2015-12-29_1211](https://cloud.githubusercontent.com/assets/16442488/12032900/08920248-ae26-11e5-8f57-2502823fbed9.png)

**Comment by AndreyPopovNew** [comment]
прикольно.

только вам все равно это не поможет. потому что есть более "сакральная" графа:

Довідка про склад сім’ї:

при этом при заказе субсидии собез сам ее может заказать, а тут видителе дайте!

а чтобы получить спарвку о сотаве семьи надо для начала ребенка зарегистрировать по адресу.

**Comment by dmitrijzabrudskij** [comment]
@nadlena таки да - только Царичанка сейчас. до недавнего времени услуга предоставлялась не через соцзащиту, а через центры предоставления админ. услуг (поэтому только один населенный пункт в области доступен).

с нового года выдача этого удостоверения будет полностью делаться в соцзащите с последующим назначением льгот и полагающихся выплат. и так как услуги соцзащиты у нас на портале работают для всей области, то и эта сразу будет доступна по всем отделениям соцзащиты. запустим, думаю, до конца января максимум -  так что есть смысл не спешить сейчас с походами по инстанциям и дождаться появления услуги на портале. называться будет так же
