### ISSUE TITLE
Не працює завантаження документів - Призначення соцдопомоги при народженнi дитини

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#19]
Oxana Sergeevna (https://www.facebook.com/igov.org.ua/posts/1628399240782286)

Добрый день! На сайте в рубрике "Призначення соцдопомоги при народженнi дитини" не работает "загрузить файл". То есть загрузить документы нет возможности! Исправьте пожалуйста ошибку!

**Comment by VadymVolos** [comment]
Таке запитання вже є https://github.com/e-government-ua/iForum/issues/11

**Comment by VadymVolos** [comment]
Написав відповідь на фейсбук сторінці:

Добрий день, Оксано! Ось тут схожа проблема https://github.com/e-government-ua/iForum/issues/11 Спробуйте інший свіжий браузер.

===

Але, якщо це проблема масова, або слід виправити, щоб з усіх браузерів працювало, або як мінімум коли користувач завантажує, написати: 
"Якщо не виходить завантажити - причина в браузері, будь ласка спробуйте інший свіжий"

**Comment by drover1988** [comment]
до 600 кб. загружает документ, проверено лично
