### ISSUE TITLE
Как чиновник может быть уверен, что гражданин получил email-уведомление ?

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iForum#191]
На днях администратор ЦНАП задал мне вопрос: "Как я могу быть уверена, что когда я нажимаю кнопку "Отправить человеку уведомление о результате обработки его заявки" - он его действительно получит?". Сам факт того, что заявка переходит из состояния "В работе" в "Отработанные" её не убеждает. Она хочет иметь что-то, что можно будет предъявить разгневанному клиенту, который, возможно, пропустил это письмо, не проверил папку "Спам" или неверно ввел почту. 

Поступило предложение в каждое письмо, отправленное гражданам, в поле "копия" или "скрытая копия" дописывать email-адрес ЦНАП. По этому поводу у меня два вопроса:

1. Это вообще допустимое решение? Ведь данные письма содержат личные данные граждан плюс иногда причины отказов и другую информацию, а emailы администраторов, бывает, на каком-нибудь ukr.net - мы можем туда это слать?

2. Если с п.1 всё ок - требуется ли модифицировать каждую отсылку письма в каждом бизнес-процессе или есть какая-то возможность добавить этот "ящик для подтверждения отсылки" один раз для всех процессов, обрабатываемой некоторой группой или пользователем?

**Comment by AndreyPopovNew** [comment]
ну есть же журнал отправленных сообщений, чтобы предъявить. хотя конечно если используется протокол php sendmail, то с этим труднее, н овсе равно в логах где-то должно остаться.

не знаю каким образом у вас это реализовано, но может пользоваться почтовым клиентом?

опять же у мыла тоже есть возможность поставить флаг "уведомить о прочтении" и при открытии такого письма обычно спрашивает "уведомлть?"

**Comment by GrekD** [comment]
--который, возможно, пропустил это письмо, не проверил папку "Спам" или неверно ввел почту.--
почему хоть что-то из этого вдруг должно стать проблемой цнапа, а не гражданина?
Если такое случится - я думаю найдется не один способ доказать гражданину что ему было отправлено письмо (в крайнем случае - найдем и покажем). Сколько таких случаев прогнозируется за год? Надо опираться на реальные данные, чтоб они служили основанием для допиливания БП. 

-- поле "копия" или "скрытая копия" дописывать email-адрес ЦНАП--
как правило, БП один на всю страну, если мы его дорабатываем таким образом - захотят ли сотрудники ЦНАПов других городов так же получать себе на почту эту кучу писем? - знаю нескольких, которые точно не захотят

**Comment by AndreyPopovNew** [comment]
@GrekD думаю вам надо отладить для начала саму систему уведомлений о принятии и выполнении заявок.

к примеру я вот НЕ МОГУ понять какие именно заявки выполнились!!

вот вижу в своем журнале:
30.12.2015 16:13	Ваша заявка №0-1234479 змiнила свiй статус на Заявка виконана

а что это????????????

в журнале событий такой заявки не вижу!
в списке пришедших сообщений тоже

что это за заявка????

**Comment by AndreyPopovNew** [comment]
вот еще пример:

в журнале вижу:
28.12.2015 17:34	Ваша заявка №0-43462009 змiнила свiй статус на Заявка виконана
28.12.2015 17:33	Ваша заявка №0-49008886 змiнила свiй статус на Заявка виконана
28.12.2015 17:32	Ваша заявка №0-48922541 змiнила свiй статус на Заявка виконана
28.12.2015 17:31	Ваша заявка №0-43239791 змiнила свiй статус на Заявка виконана
28.12.2015 17:28	Ваша заявка №0-54646640 змiнила свiй статус на Заявка виконана
28.12.2015 15:15	Ваша заявка №0-47848149 змiнила свiй статус на Заявка виконана

а на мыле:
![image](https://cloud.githubusercontent.com/assets/8410116/12074595/3dd4917c-b165-11e5-9932-1859e9a12bb9.png)


всего ЧЕТЫРЕ уведомления и то НЕПОНЯТНО по какой заявке!?!?!?!?! внутри мыла НЕТ номера заявки!

**Comment by ezhikus** [comment]
@GrekD "почему хоть что-то из этого вдруг должно стать проблемой цнапа, а не гражданина?"
Потому что на ЦНАП регулярно (несколько раз в год) подают в суд по поводам в духе "вы мне не перезвонили", "я просил ответ по почте и не получил его". ЦНАП уже насобачился в этих делах использовать логи операторов связи и квитанции почты в качестве доказательств того, что он звонил\писал. Мы предлагаем ЦНАПу новый способ взаимодействия с клиентами, значит, должны и предложить ему способ получения доказательств для судов. 

Отсылать копии писем, может и не надо, но тогда нужна написанная инструкция в духе "если Вам понадобилось документальное подтверждение отсылки письма порталом igov.org.ua - позвоните вот по этому номеру телефона или напишите вот этому человеку..." и т.д.

Мы можем сделать такую инструкцию?

**Comment by GrekD** [comment]
добрый день
@AndreyPopovNew 
я так понимаю, конкретно сейчас Вы пишите о заявках минюста, за уведомления в этих процессах отвечает @NizhnikAlex 
1234479 - такую заявку я тоже не вижу - цифр явно малова-то как для ид заявки

@ezhikus 
1. где эта инструкция должна размещаться?
2.что будет являться "документальным подтверждением рассылки"?

**Comment by ezhikus** [comment]
@GrekD 
1. Ну, по-хорошему на портале чиновника у нас должен быть раздел "Справка" - там и этой инструкции место. Раздел "Справка" вообще нужен - меня вот спрашивали что делать, если пароль забудешь. Ответ на этот вопрос тоже должен быть в "Справке".

2. "документальное подтверждение" от почты - это такой кусочек бумажки, где написано "письмо было отправлено туда-то тогда-то". От оператора связи - это распечатка звонков с некоторого номера. Мы могли бы предложить какой-нибудь кусочек лога сервера с датой\временем отправки письма, адресами получателей, темой письма. Понятно, что это не железобетонный аргумент, но намного лучше, чем ничего.

**Comment by AndreyPopovNew** [comment]
@GrekD 
1. я пишу в общем на конкретном примере. о том что в сообщении о приеме заявки НЕ стоит номер самой заявки. это относится не только к заявкам минюста. это относится вообще ко всем заявкам!

Надання витягу з Єдиного державного реєстру МВС України
Ваше звернення успішно зареєстровано. 
Результат обробки звернення будуть спрямовані на цей е-мейл. 


Довідка про доходи (пенсійний фонд)
Ваше звернення щодо отримання довідки про доходи фізичних осіб відхилено, так як Ви не сплатили послуги протягом 3-х днів. Ви можете подати ще одну заяву на порталі igov.org.ua

Довідка про доходи
Ваша заява на отримання довідки про доходи прийнята в роботу. 
Забрати довідку Ви зможете через 5 робочих днів в тому відділленні податкової служби, яке Ви вказували при замовленні послуги. 

НЕ номеров заявок!!!

если конечно исходить из того, что гражданин подает всего ОДНО обращение......

2. 1234479 - я вам скопировал строку из Моего журнала - я вообще не могу понять о чем это. но оно ЕСТЬ!

@ezhikus 
портал iGov  нужен в первую очередь для граждан Украины, и в данном случае ОБЯЗАННОСТЬ чиновника УБЕДИТЬСЯ, что гражданин ПОЛУЧИЛ ответ. иначе iGov НИЧЕМ не будет отличаться от существующей системы.
это мое ИМХО

**Comment by GrekD** [comment]
@AndreyPopovNew 
это не касается абсолютно всех заявок. В тех, которые Вы привели - скорее всего так и есть, но это не все.
Вот тут есть список ответственных за услуги бизнес-аналитиков:
https://docs.google.com/spreadsheets/d/1ZLJgro3bn0P3oi9uhm3cSmRvQTTLlKo9bhn7zww-bmQ/edit#gid=0
и нужно по каждой конкретной услуге адресовать вопрос человеку который ее разрабатывал (контакты на соседнем листе)

@ezhikus обсудите Ваши предложения с Белявцевым Владимиром
