### ISSUE TITLE
Проблема регистрация субсидии.

### ISSUE THREAD

**Issue by DrVipes** [e-government-ua/iForum#192]
На регистрации ,во 2 шаге, когда добавится весь список банков в Днепропетровской области? Так невозможно пройти дальнейшую регистрацию!!!

**Comment by AndreyPopovNew** [comment]
вы хотите сказать, что в списке нет всех банков?

ну так это от банков зависит.

если вашего банка нет в списке, то вы можете:
- стать клиентом другого банка. тот же Приватбанк выдает кредитную карту бесплатно.
- получить цифровую подпись в Центре Сертификации ДФС бесплатно
http://acskidd.gov.ua/contacts
![Uploading image.png…]()
