### ISSUE TITLE
Субсидія, прийшов лист з файлом .d52

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#193]
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1651651615123715&comment_tracking=%7B%22tn%22%3A%22R2%22%7D

Таня Пальчик:
>Здравствуйте! Я подала на субсидию через ваш портал и даже ее получила, но в виде приложения к письму, которое я не могу открыть никакой программой. Подскажите как прочитать информацию в приложении (видны только цифры, а буквы - иероглифы).

>Мой файл называется rp106033.d52, а заявка была № 15338350. Word у меня 2010 и если бы даже он не открыл, то через интернет точно открылось бы.

**Comment by dmitrijzabrudskij** [comment]
добрый день. какой район соцзащиты прислал этот файл?

**Comment by tatianapalchik** [comment]
Я зарегистрирована в АНД-районе, думаю, что он и занимался субсидией, а в письме в конце было написано: З повагою, Управління соціального захисту у Дніпропетровській області,
Команда Порталу державних послуг iGov. Больше никаких реквизитов, указывающих откуда пришло письмо, не было.

**Comment by dmitrijzabrudskij** [comment]
да от них же и пришло. сейчас точечно по таким жалобам вылавливаю эти случаи и требую от них скан уведомления
по Вам запросил его. как только будет - отправлю на почту

**Comment by VadymVolos** [comment]
Нужно в письме дать возможность вопрос задать, Ибо не все ж знают что такое фейсбук и как там вопрос задать, не говоря уже за вопрос на гитхабе.

**Comment by dmitrijzabrudskij** [comment]
куда адресовывать этот вопрос?

**Comment by VadymVolos** [comment]
Мой?) Ну не знаю, в отдел по улучшению качества, кто у нас за качество и инновации отвечает

**Comment by dmitrijzabrudskij** [comment]
нет
"Нужно в письме дать возможность вопрос задать, Ибо не все ж знают что такое фейсбук и как там вопрос задать, не говоря уже за вопрос на гитхабе. И получаются люди месяц ждут, и не знают к кому обратится за помощью."

вот эти вопрос куда должны маршрутизироваться?

**Comment by VadymVolos** [comment]
Есть три варианта куда направлять вопрос:

1. Дать линк на обучающие видео о том "как зарегится и задать вопрос на гитхабе" чтоб юзер сам тут написал.
2. Направлять тому кто предоставлял услугу, чтоб он мог мониторить клиент доволен (получил ли услугу).
3. Направлять нам, чтоб мы видели в админ панели по каким услугам в каких городах есть вопросы у клиентов.

**Comment by dmitrijzabrudskij** [comment]
2. контакты района есть сейчас в письме после подачи заявки. добавлю еще и в конечное письмо - теряют, видимо
3. скоро так и будет. все негативные оценки с отзывами будут попадать в обрабботку волонтерам

**Comment by VadymVolos** [comment]
Было б хорошо чтоб негативные оценки попадали и тем кто предоставлял услугу. Иначе они не будут видеть своих косяков. Получится что одни делают косяки и не знают о них, а другие расхлебывают, и злятся на тех кто делает косяки.

**Comment by ValerijL** [comment]
Мне тоже пришел такой файл. Попробовал изменить расширение файла на  *.pdf, читать не захотел. Потом перебил на *.doc - открылось. При открытии спросило какой код, ничего не менял, нажал ок и всё заработало. Правда без электронных подписей, но ничего и так сойдет.
А теперь вопрос  к dmitrijzabrudskij: в конце отопительного сезона или начале следующего отопительного сезона должен быть перерасчет, который выполняется автоматически службами субсидии. А ответ тоже будет через Вас приходить на почту, указанную при первоначальном оформлении субсидии?

**Comment by dmitrijzabrudskij** [comment]
@tatianapalchik файл можно открыть блокнотом и поменять в нем шрифт на Terminal (Формат - Шрифт - Terminal, скрин: https://www.dropbox.com/s/63p2sfb4s6a3k4q/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-01-12%2011.43.03.png?dl=0)
район, к сожалению, упорно не хочет печатать и сканировать уведомления. боремся

@ValerijL нужно будет подать новую заявку - в ней вышлют уведомление по пересчитанной субсидии

**Comment by VadymVolos** [comment]
>район, к сожалению, упорно не хочет печатать и сканировать уведомления. боремся
ну так давайте найдем решение. Не хотят ибо это много роботы, и когда и так загружен делать еще что-то нет времени.Плюс сканеров же у людей нет, плюс нужно ПО для сканеров, плюс уметь этим ПО пользоваться. Вообщем головно боли много, и заставлять их делать эту работу нелогично, тем более нашару.

**Comment by dmitrijzabrudskij** [comment]
@VadymVolos предлагайте решение. только не в общих чертах

**Comment by VadymVolos** [comment]
@dmitrijzabrudskij вы у них спрашивали, какое они решение предлагают? на что жалуются, что просят?

**Comment by dmitrijzabrudskij** [comment]
@VadymVolos не отвечайте вопросом на вопрос. жду предложений по конкретному случаю, который здесь описан. если предложения нет, прошу не тратить время впустую

**Comment by VadymVolos** [comment]
Дмитрий вы сами попросили помощь, когда я задал уточняющие вопросы чтоб найти решение, вы начали себя вести как маленькая девочка сразу в кусты. Что это за бред? Если не нужна помощь не просите помогать. Цените мое время.

**Comment by tatianapalchik** [comment]
Спасибо! Все получилось! Теперь смогу сориентироваться в пересчетах.

С уважением, Татьяна

12 января 2016 г., 11:45 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by dmitrijzabrudskij** [comment]
@VadymVolos я не просил у вас помощи - вы сами начали предлагать найти решение. 
давайте на будущее договоримся так: вы делаете ветку с жалобой от клиента и потом не вмешиваетесь в разговор - дальше диалог ведут ответственные от портала за конкретную услугу
