### ISSUE TITLE
Нет ответа по заявке на субсидию 

### ISSUE THREAD

**Issue by stans** [e-government-ua/iForum#195]
Подавал заявку на субсидию 19 октября 2015 года ,заявка 9570430 , до сих пор никакого ответа !
Прозвон ничего не дал - "нам не пришло ваше дело из 37 кабинета" ???!!!
Как будто меня интересуют номера их кабинетов !
г.Днепропетровск, Бабушкинский район

**Comment by stans** [comment]
Подавал заявку на субсидию 19 октября 2015 года ,заявка 9570430 , до сих пор никакого ответа !
Прозвон ничего не дал - "нам не пришло ваше дело из 37 кабинета" ???!!!
Как будто меня интересуют номера их кабинетов !
г.Днепропетровск, Бабушкинский район

**Comment by dmitrijzabrudskij** [comment]
не могу найти Вашу заявку в бабушкинском районе. подскажите, письмо с решением не приходило за последние дни?

**Comment by GrekD** [comment]
@stans эта заявка была выполнена административным органом со статусом "субсидія погоджена"
