### ISSUE TITLE
Субсидия. Электроенергия

### ISSUE THREAD

**Issue by Ulia0807** [e-government-ua/iForum#196]
Здравствуйте! Получила субсидию на оплату жилищно-коммунальных услуг. Пришли на почту файлы PDF с датой назначения 12 декабря, указана обязательная плата, социальная норма, вроде всё понятно. Но теперь на  сайте Днепроблэнерго в декабре показано: начисления - субсидия 350, 36 грн, на лицевом счету образовалась переплата. Не понимаю, что за единоразовая сумма, если я использовала меньше киловатт, чем социальная норма, деньги же не накапливаются для следующего месяца?

**Comment by AndreyPopovNew** [comment]
это распространненая заморочка, в которую почему-то все верят как в мантру и повторяют на каждом углу.


социальная норма - это предел, после которой вам субсидию уже не дают!!!!!

а вот между обязательным платежем и социальной нормой (в гривнах!!!!!!! только, а не в киловат/часах) - это то что будет компенсироваться.

а приписка в назначении о субсидии, котоаря гласит, что при потреблении меньше ОБЯЗАТЕЛЬНОГО платежа, вы платите только сумму реально потребленного означает:

что если вы потребили 100кват за месяц - а это 41,70грн., то вам надо платить не ОБЯЗАТЕЛЬНЫЙ платеж 89,90, а всего 41,70!

**Comment by Ulia0807** [comment]
А если субсидия назначена с октября, почему мне её ввели за 7 месяцев?!  Висит сайт облэнерго, не получает сделать картинку, но в графе субсидия - у меня указана сумма 350,36 (7). Почему  7 месяцев?

**Comment by AndreyPopovNew** [comment]
лично я вам сказать не могу. про (3) три - это мое предположение. потому что к примеру по газу более четко видно:
![image](https://cloud.githubusercontent.com/assets/8410116/12143933/03ad1ca0-b48d-11e5-8efb-3ce00b864ce7.png)

что 1.12.2015 три раза (за октябрь, ноябрь и декабрь) субсидию начислили.

водоканал тоже одной суммой все провел
![image](https://cloud.githubusercontent.com/assets/8410116/12143990/5ed3fe96-b48d-11e5-99fa-30ecc4396e13.png)

**Comment by Ulia0807** [comment]
Спасибо за ответы. Если можно, ещё вопрос.  В сентябре 2016 года мне нужно заново подавать заявку на получение субсидии, или она пролонгируется автоматически?

**Comment by AndreyPopovNew** [comment]
говорили, что субсидия будет пересчитываться автоматически. вам должны будут прислать новое уведомление о размере субсидии на следующий сезон.

и ее еще должны весной пересчитать, после отопительного сезона.

**Comment by Ulia0807** [comment]
Спасибо за разъяснения!

**Comment by AndreyPopovNew** [comment]
@Ulia0807 
расшифровку по суммам субсидий можно увидеть в деталировке 

![image](https://cloud.githubusercontent.com/assets/8410116/12240154/c7f018d2-b894-11e5-94a3-b9362c538a1a.png)

**Comment by Ulia0807** [comment]
Ещё раз спасибо! Теперь стало ясно!
