### ISSUE TITLE
Не пришел ответ на выполненную заявку

### ISSUE THREAD

**Issue by romex22** [e-government-ua/iForum#197]
В статусе на igov.ua заявка выполнена, но ответа на e-mail не пришло. номер 18085998

**Comment by dmitrijzabrudskij** [comment]
что за заявка и на какую почту должен был поступить ответ?

**Comment by romex22** [comment]
на субсидию ЖКХ. не пришел ответ предоставлена или нет. заявка с статусе "виконана".

**Comment by dmitrijzabrudskij** [comment]
в какой район отправляли заявку?

**Comment by romex22** [comment]
бабушкинский

**Comment by GrekD** [comment]
@romex22  эта заявка была выполнена административным органом со статусом "субсидія погоджена"
