### ISSUE TITLE
Системные требования для компьютеров, где будет использоваться iGov

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iForum#198]
Ходил я, значит, сегодня демонстрировать igov в одно из местных управлений горсовета. Перед этим поинтересовался, есть ли у них компьютеры и интернет, получил ответ "да, конечно, приходи". Пришел и своими глазами увидел два компьютера уровня Celeron-800, 512 Мб ОЗУ на Win98 и WinXp (без обновлений). Из браузеров мне было предложено IE6 и Оперу (года эдак 2002-го выпуска). Как вы, может быть, догадались, на всём этом счастье igov просто даже не открылся - на сайте менюшки не выпадают, кнопки не нажимаются, комбики не выбираются и т.д.   Горсовет в принципе готов обновлять и ПО и, при необходимости, железо. Но просят написать чего нам надо, поскольку стало очевидно, что "да мы работаем на чём угодно" - не правильный ответ. Предлагаю написать минимальные требования по железу и ПО. Для старта можно взять, например, системные требования Хрома, как предпочитаемого браузера и сделать небольшой "запас" под себя. Плюс нужно описать требуемое ПО (а нам, между прочим, не только браузер нужен).

Я начну, а кто лучше разбирается, дополняйте

**Hardware**
* Intel Pentium 4 processor (or later)
* 1 GB of free disk space (or more)
* 2 GB of RAM (or more)
* Internet connection - 1 Mb/s (or faster)
* Display 19" (or more)

**Software**
* Windows XP Service Pack 2+, Windows Vista, Windows 7, Windows 8, or Windows 10
* Google Chrome or Mozilla Firefox or Internet Explorer 10/11
* Image viewer (for example, IrfanView - http://www.irfanview.com/)
* Archiver (for example, 7-zip - http://www.7-zip.org/)
* PDF reader (for example, Foxit Reader - https://www.foxitsoftware.com/products/pdf-reader/)
* Open Office or Microsoft Office

**Comment by GrekD** [comment]
@msvidran 
Максим, подскажи, пожалуйста - что вы для гор.совета рекомендовали?

**Comment by msvidran** [comment]
Список, перечисленный выше для работы с iGov вполне устроит, единственное оперативки можно и 2GB.
Еще добавлю - это монитор: широкоформатный не ниже 19 дюймов, если монитор меньше - не очень удобно пользоваться фильтрами и поиском в дашборде чиновника.

**Comment by ezhikus** [comment]
Ок, текст в первом сообщении поправил. Заявку закрываю, кому нужно - можно теперь на неё ссылаться.
