### ISSUE TITLE
Не работает услуга Виготовлення викопіювання в масштабі 1:500, 1:2000

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#199]
уже два раза подавал заявку

первый раз когда еще для Днепропетровска отдельно стояла 
Виготовлення викопіювання в масштабі 1:500

второй раз, когда уже объединили в одну
Виготовлення викопіювання в масштабі 1:500, 1:2000

так НИ разу ответ и не пришел!

номеров не знаю. потому как в журнале их нет:
21.12.2015 20:11	Ви подали заявку на послугу Дніпропетровськ ГоловАПУ - Викопіювання з топографічного плану міста 1:500!. Cтатус: Заявка подана

02.12.2015 16:29	Ви подали заявку на послугу Дніпропетровськ ГоловАПУ - Викопіювання з топографічного плану міста 1:500!. Cтатус: Заявка подана

а приходила ли на мыло - бог его знает - там где стоит номер, не указана о чем она. там где указано о чем она - нет номера.

**Comment by GrekD** [comment]
@NizhnikAlex

**Comment by AndreyPopovNew** [comment]
а в ответ ТИШИНА!!!!

@GrekD 

@NizhnikAlex 

так услуга работает? а то Борис Филатов вон хвастатется, что Днепр "впереди планетыф всей", а реально только пару услуг и работает!!!!!

**Comment by NizhnikAlex** [comment]
Работает. В следующий раз пробуйте заявки по одной подавать - тогда реально будет отследить выполнение. По вашим данным не получится отследить.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex так я по одной и подвал!!!

первая
02.12.2015 16:29 Ви подали заявку на послугу Дніпропетровськ ГоловАПУ - Викопіювання з топографічного плану міста 1:500!. Cтатус: Заявка подана


вторая
21.12.2015 20:11 Ви подали заявку на послугу Дніпропетровськ ГоловАПУ - Викопіювання з топографічного плану міста 1:500!. Cтатус: Заявка подана

сейчас еще раз подам

**Comment by AndreyPopovNew** [comment]
78751924

13.01.2016 17:00	Ви подали заявку на послугу Дніпропетровськ ГоловАПУ - Викопіювання з топографічного плану міста 1:500!. Cтатус: Заявка подана

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex в логе на портале вижу
14.01.2016 11:00	Ваша заявка №0-78751924 змiнила свiй статус на Заявка виконана

на мыло НИКАКИХ уведомлений и тем более 1:500

**Comment by NizhnikAlex** [comment]
какой почтовый ящик?

**Comment by AndreyPopovNew** [comment]
соответствует тому, что указан в профиле здесь.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex так где работоспособность услуги?

**Comment by NizhnikAlex** [comment]
Были проблемы с почтовой рассылкой по порталу вообще, уже устранены. Услуга работала и работает.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex ну так а как получить услугу? еще раз заказывать?

**Comment by NizhnikAlex** [comment]
попробую сделать повторную отправку. Если сегодня не придет - тогда еще раз заказать.

**Comment by AndreyPopovNew** [comment]
жду

**Comment by AndreyPopovNew** [comment]
пришло:
![image](https://cloud.githubusercontent.com/assets/8410116/12451815/04f889c0-bf94-11e5-89bf-fd60ef1a8ab5.png)


остался вопрос о том, а зачем оно надо, если там есть надпись:
Зверніть увагу! Викопіювання не актуальне .

**Comment by NizhnikAlex** [comment]
Здесь проще. С 2010 г. данные не актуализировались. В большинстве случаев вам не нужна такая актуализация - разработать проект архитектор может и на неактуальной карте.
Если же подавать в органы, требующие актуализацию - необходимо обращаться в геодезическую организацию (частную), они за плату проводят измерения и отдают вам материалы. Такие же материалы они передают в ГлавАПУ и следующий кто закажет выкопирование по этому участку в течении года, получит уже с отметкой "актуально".

Т.е. здесь надо понимать что конкретно вам надо.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex у меня закончился срок аренды земли. его надо продлевать.

как думаете горсовет захочет актуальную 500-ку или им пойдет такая?

днепрводоканал хочет перезаключить договор и там в списке документов тоже числится 500-ка

как думаете они примут такую?

**Comment by NizhnikAlex** [comment]
если вы ничего в инженерных сетях не меняете - скорее всего подойдет. Точнее скажут только те, кто требует.
Актуальная точно нужна при разработке проекта застройки (где надо подключаться к инженерным сетям, выяснять выходите вы или нет на красную линию и т.д.). В большинстве других случаев пойдет и неактуальная.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex вот я лично в тупике от такой услуги. тем более что при ее заказе есть выбор:
![image](https://cloud.githubusercontent.com/assets/8410116/12476832/a3e64a7c-c034-11e5-9a07-36e5ec3dcfd8.png)

- подключение к инженерным коммуникациям
- застройка

как вы сами говорите, тут нужна актуальная копия!
так как быть тогда?

а как быть мне, при заключении договоров, если мой офис выглядит сейчас вот так:

**Comment by NizhnikAlex** [comment]
если в ГлавАПУ копия неактуальна, обращаться в геодезическую организацию. Кто вам проектирует - должні знать.

**Comment by AndreyPopovNew** [comment]
она неактуальная еще как минимум с 2010 года. я честно говоря не обращал внимания на сколько она актуальна, когда получал в 2010. но мошу сказать, что по состоянию на 2010 она УЖЕ была неактуальна! как видно по моей копии Придатно - данные даны по состоянию на 2007!!!!!! год.

вот так это выглядело в апреле 2012
![040420121025](https://cloud.githubusercontent.com/assets/8410116/12477268/342a1c06-c037-11e5-9c6f-6282188719c9.jpg)

уже почти ДЕСЯТЬ лет никто не актуализирует данные!!!

**Comment by NizhnikAlex** [comment]
Если никто не актуализирует - значит никому это не надо. Пробуйте с таким вариантом, если нет - придется актуализировать.

**Comment by AndreyPopovNew** [comment]
@NizhnikAlex 
сделал еще одну заяку 87189727 и выбрал подключение к инженерным коммуникациям

в журнале стоит:
21.01.2016 19:34	Ви подали заявку на послугу Дніпропетровськ ГоловАПУ - Викопіювання з топографічного плану міста 1:500!. Cтатус: Заявка подана

22.01.2016 10:35	Ваша заявка №0-87189727 змiнила свiй статус на Заявка виконана

2016-01-22 10:35:04.775	Заявка закрита з відгуком -

ответа на мыло снова НЕ пришло.
и как понимать статус: закрыта с отзывом?

**Comment by NizhnikAlex** [comment]
Если бы вы получили ответ на почту, там есть поле отзыва. При заполнении отобразилось бы.
Что-то с почтой непонятное происходит. Не проходит минимум писем (доли процента), но ваш адрес не принимает...

**Comment by GrekD** [comment]
Заявка закрита з відгуком - это некорректно отображается статус. 
87189727 - Эта заявка была закрыта с положительным решением "Викопіювання виготовлене"
