### ISSUE TITLE
Пособие на ребенка

### ISSUE THREAD

**Issue by drover1988** [e-government-ua/iForum#20]
2015-10-12 15:12:40.938	Заявка виконана   и что дальше, не понятно...

**Comment by dmitrijzabrudskij** [comment]
разве имейла не было? и дайте данные, которые есть по заявке - фио, дата подачи, район, номер - поищу-посмотрю что в ней написали

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
