### ISSUE TITLE
Не выполняется оформление.

### ISSUE THREAD

**Issue by Vet4444** [e-government-ua/iForum#200]
Нет ответа по заявке 27903247 от 11.12.15 г.Днепропетровск АНД район ,тел.3759064 не отвечают.

**Comment by dmitrijzabrudskij** [comment]
эта заявка еще в работе. можете попробовать набрать их по номеру 056 375 90 64. но по опыту других заявок еще рановато для ответа

**Comment by GrekD** [comment]
заявка была закрыта административным органом со статусом "відмова в обробці"
