### ISSUE TITLE
Нет ответа на заявку 

### ISSUE THREAD

**Issue by relanium** [e-government-ua/iForum#202]
Не пришел ответ на заявку на загран.паспорт. 
05.01.2016 11:16	Ви подали заявку на послугу Отримання паспорта для віїзда громадянина за кордон!. Cтатус: Заявка подана
К сожалению не записал номер заявки ((  
Регистрировался на 25.01.16 на 10.00

**Comment by dmitrijzabrudskij** [comment]
какую почту указывали при подаче заявки?

**Comment by relanium** [comment]
kalina-67@ukr.net

**Comment by dmitrijzabrudskij** [comment]
не вижу чтобы на эту почту уходило хотя бы одно письмо по любой услуге. 
в какой район была запись и на какую фамиллию?

**Comment by relanium** [comment]
На городской (Красная)
Калінніков

**Comment by dmitrijzabrudskij** [comment]
заявка и правда есть. все в силе. сбросил еще раз имейл с реквизитами

**Comment by relanium** [comment]
дякую! :)
