### ISSUE TITLE
Не пришёл ответ по заявке на оформление загран паспорта.

### ISSUE THREAD

**Issue by alex79dpua** [e-government-ua/iForum#203]
Добрый день! Вчера заполнил заявку, ответ до сих пор нет. Номер 70923161
Прошу помочь побыстрее, т.к. я записался на послезавтра.

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой отделение миграционной выбирали?

**Comment by alex79dpua** [comment]
Днепропетровск, ул Ильича, Бабушкинский район

**Comment by alex79dpua** [comment]
Днепропетровск, ул Ильича, Бабушкинский район 

12 января 2016, 12:52:35, от "dmitrijzabrudskij" < notifications@github.com >: 

добрый день 
какой отделение миграционной выбирали? — 
Reply to this email directly or view it on GitHub . 

-- 
Alex Dudich 
ATZT Eurometall LTD 
Ukraine, Dnepropetrovsk 
Starokozatska str, 32

**Comment by dmitrijzabrudskij** [comment]
все в силе на 2016-01-14 10:00
имейл переотправил

**Comment by alex79dpua** [comment]
Спасибо большое, пришло.
