### ISSUE TITLE
Что означает статус заявки "заявка виконана" и что делать дальше. № заявки 3516383

### ISSUE THREAD

**Issue by ocra1977** [e-government-ua/iForum#204]

**Comment by dmitrijzabrudskij** [comment]
что за заявка и в какой город/район подавалась?

**Comment by ocra1977** [comment]
г. Днепропетровск, р-н Бабушкинский, заявка на получение субсидии, № 3516383

2016-01-12 15:00 GMT+02:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by dmitrijzabrudskij** [comment]
не нахожу такую. можете дать почту, которую указывали при подаче?

**Comment by ocra1977** [comment]
vasilieva_a@i.ua

12 января 2016 г., 17:08 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by dmitrijzabrudskij** [comment]
заявка была забракована. ответ отправил повторно Вам на почту

**Comment by ocra1977** [comment]
Спасибо

13 января 2016 г., 11:28 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by TaranMariya** [comment]
Добрый день! Подала заявку на субсидию. На данный момент статус заявки "Заявка виконана". Никаких писем на почту не приходило. Заявка № 70639440 Что дальше?

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой район?

**Comment by TaranMariya** [comment]
город Павлоград

**Comment by TaranMariya** [comment]
название района "40 лет октября", но при заполнении заявки данная информация не требовалась, достаточно было города

**Comment by dmitrijzabrudskij** [comment]
отказано в заявке. комментарий района следующий:
Невірно вказаний період за який заповнюється декларація (01.01.2015 по 30.09.2015, або за останні 3 місяці перед зверненням при наявності довідок про доходи)

имейл об этом отправлялся 11.01.2016 - попробуйте проверить папку "спам" в почте - мог туда попасть

**Comment by TaranMariya** [comment]
Спасибо огромное за информацию,  буду пробыватавать еще
