### ISSUE TITLE
Видача довідки про доходи (розмір пенсії) не пришло уведомление на мыло о принятии заявки. полностью НЕРАБОЧАЯ услуга!

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#207]
Видача довідки про доходи (розмір пенсії)
https://igov.org.ua/service/661/general

в журнале вижу:
13.01.2016 17:27	Ви подали заявку на послугу Отримання довідки про доходи (пенсійний фонд)!. Cтатус: Заявка подана

а на мыло подтверждения не пришло.

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij вроде вы ответственный за данную услугу?

**Comment by dmitrijzabrudskij** [comment]
@AndreyPopovNew тут проблема не в самом процессе, а в работе портала - потому что имейл с номером заявки отправляется автоматически абсолютно по всем процессам. конкретно в вашем случае случилась ошибка при отправке имейла (хотя сама заявка живая и подалась успешно), после которой повторной попытки отправить уже не было. сейчас в работе доработка, которая позволит минимизировать такие случаи: будем неуспешные запросы на отправку имейла добавлять в очередь, из которой они будут с определенной периодичностью повторяться

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij я подаю заявку уже четвертый или пятый раз (с сентября месяца).
там вроде должен еще приходить счет на оплату. так вот ни разу еще ничего не пришло.

**Comment by dmitrijzabrudskij** [comment]
это уже из процесса имейл идет. когда сотрудница укрпочты обрабатывает заявку. и у вас проблема на стороне приема была - ваша почта резала наши письма. я сейчас из вшей заявки отправил письмо для оплаты - проверьте дошло/не дошло (у нас поменялся доставщик почты - это может повлиять)

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij что доставщик поменялся видел на примере 1:500

но пока ничего похожего не пришло.

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij так больше нет никакой инфы? что дальше то?

**Comment by dmitrijzabrudskij** [comment]
письмо об оплате так и не появилось?

**Comment by AndreyPopovNew** [comment]
нет. не появилось.

**Comment by dmitrijzabrudskij** [comment]
отправил еще одно из другой вашей заявки. есть/нет?

**Comment by AndreyPopovNew** [comment]
нету

**Comment by dmitrijzabrudskij** [comment]
@bvv4ik Володя, посмотри пожалуйста по логам что случилось с отправкой письма из процесса post_spravka_o_doxodax_pens в промежутке 15:50-16:05. боевой

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij  @bvv4ik и каковы перспективы?

**Comment by AndreyPopovNew** [comment]
мне пришли уведомления за три раза, но.....

1. Для отримання послуги Вам необхідно сплатити її протягом 1 дня з моменту подачі заяви.

т.е. надо все равно подавать заново

2. самое главное - сколько не жми на кнопку Оплатить - это просто картинка!!

![image](https://cloud.githubusercontent.com/assets/8410116/12645122/821bcdda-c5d0-11e5-9869-3a0472690629.png)

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij  @bvv4ik создал еще одну заявку 0-95368048

в Журнале ее не видно.
на мыло тоже ничего не пришло пока.

проверка статуса выдает ощибку
![image](https://cloud.githubusercontent.com/assets/8410116/12681549/c1294808-c6b7-11e5-8555-cb5dbbf6f0a9.png)

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij и @bvv4ik скажите, а что-то вообще можно сделать с этой услугой?!?!?!?

подтверждение на мыло НЕ приходит
счет на оплату НЕ приходит
в журнале этой услуги НЕТ

зато отказ приходит исправно:
![image](https://cloud.githubusercontent.com/assets/8410116/12789846/29aaed2a-caa8-11e5-995c-fec9ba09f9a8.png)

и в журнале появляется, только под непонятно каким номером!!!!

![image](https://cloud.githubusercontent.com/assets/8410116/12789869/44a6f506-caa8-11e5-8a7b-379e7a380765.png)

**Comment by AndreyPopovNew** [comment]
@GrekD 
@dmitrijzabrudskij сделал еще одну заявку
0-104470145

в журнале НЕТ
на мыло не приходит
при проверке статуса выдает ошибку

полностью НЕ РАБОЧАЯ услуга!!!!

**Comment by GrekD** [comment]
@AndreyPopovNew 
ваша заявка находится в работе у соответствующего адм. органа - я проверила - она есть
мейл Вам был отправлен
вот скрин
![2016-02-11_133813](https://cloud.githubusercontent.com/assets/10836093/12975501/ec7c3c42-d0c4-11e5-896b-82210b2a4f10.jpg)

по статусам  - это к Белявцеву Владимиру

**Comment by AndreyPopovNew** [comment]
@GrekD 

то что начало приходить на почту - это прогресс, но.....

как я писал выше, должна приходить ССЫЛКА на оплату, а приходит мыло просто с КАРТИНКОЙ

**Comment by dmitrijzabrudskij** [comment]
приходит КНОПКА
я не знаю почему у вас ссылка. попробуйте другую почту

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij 
вот тут видно
![image](https://cloud.githubusercontent.com/assets/8410116/12978653/f1f902d4-d0da-11e5-836c-d5badb29d769.png)
что пришли ссылки

может сделать все же в виде ссылки, а не кнопки(рисунка)?

**Comment by AndreyPopovNew** [comment]
далее - заявка подана 08.02 в районе 15:00

10.02 в 18:18 приходит мыло с текстом:
Для отримання послуги Вам необхідно сплатити її протягом 1 дня з моменту подачі заяви.

на протяжении ОДНОГО дня с момента подачи заявки!

так заявка подана 08.02 - день уже прошел!!!!

или имеется в виду день получения этого письма?

**Comment by dmitrijzabrudskij** [comment]
вы все перепутали
скрины по справке о доходах (которую налоговая выдает)
где вы там искали оплату?

по пенсионному - спасибо, поменяю на "с момента получения письма"

**Comment by AndreyPopovNew** [comment]
я из налоговой привел для примера. там ссылки отображаются нормально. видно что ссылки.

а по пенсионному приходит как картинка. если открыть в броузере, то ссылка появляется.

**Comment by AndreyPopovNew** [comment]
а с отображением в журнале и поиск в статусе - кто будет "допиливать"?

**Comment by dmitrijzabrudskij** [comment]
с пенсионным и должна быть картинка - она ведет на заведенный под эту заявку ликпеевский магазин

по журналу - Володя

**Comment by AndreyPopovNew** [comment]
ну а сделать ссылкой, а не картинкой? или добавить под картинкой дополнительно ссылку?

**Comment by dmitrijzabrudskij** [comment]
быстро не получится. нужно допиливать

**Comment by AndreyPopovNew** [comment]
а быстро не надо. главное сделать.

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij по-прежнему НЕТ записи в журнале о заявке и выдает ошибку при проверке статуса услуги:
![image](https://cloud.githubusercontent.com/assets/8410116/13287462/e5f803e2-db0f-11e5-861b-0c8c60f8b4af.png)

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij @GrekD @bvv4ik 
когда почините услугу?!?!?!??!?!

или уберите ее совсем!

еще раз подал
 0-123151229

в Журнале НЕТ
проверка статуса выдает ошибку
на мыло подтверждение не приходит

**Comment by AndreyPopovNew** [comment]
пришло ДВА уведомления об оплате
![image](https://cloud.githubusercontent.com/assets/8410116/13358591/c231ef86-dcb8-11e5-8df6-92e801e5901f.png)

по какому платить?

не хочется отправлять деньги в "никуда" - хоть и 17 грн.

**Comment by dmitrijzabrudskij** [comment]
ну все правильно - заявки ведь 2:
121554346
123151229

платите по любой - вторая забракуется

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij не совсем понятен смысл сообщения, который пришло на мыло:


Ваша довідка про доходи (пенсійний фонд) готова та направлена Вам на пошту за адресою:
м.Дніпропетровськ, вул.Мініна, буд.19, кв.123
Ви отримаєте листа протягом 7 днів. 
Ви можете відстежити наджодження листа до Пенсійного фонду за цим кодом перейшовши за цим посиланням

1. так куда отправили справку? на мой адрес или в Пенисонный фонд?
2. по какому коду отслеживать? если в письме ссылка только на поисковую форму?

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij @GrekD @bvv4ik 
все вопросы так и останутся без ответа?????

**Comment by dmitrijzabrudskij** [comment]
1. на домашний адрес
2. протупили. должны будут сегодня выслать вам штрих-код письма, по которому уже сможете проверять состояние

**Comment by AndreyPopovNew** [comment]
так что дальше??????????

**Comment by AndreyPopovNew** [comment]
пришло письмо
![image](https://cloud.githubusercontent.com/assets/8410116/13881030/e49c6090-ed27-11e5-90fe-271fb076f91f.png)


только код 4900040849101 явно неправильній!!

49101 - код почтового отделения
49000 
остаетсятся только 408

**Comment by AndreyPopovNew** [comment]
прошло ДВЕ недели!!!!

письма на почте нет! штрих-кода нет!

@dmitrijzabrudskij  @GrekD @bvv4ik 

может все же разберетесь с услугой и просто выбросите ее из списка?

он НЕ РАБОЧАЯ!!!!!!!!!!!!
