### ISSUE TITLE
Не пришло подтверждение

### ISSUE THREAD

**Issue by veronika4** [e-government-ua/iForum#208]
Оформила заявку на выдачу загран паспорта, на почту не пришла информация о дате, времени и необходимых документах. Повторите пожалуйста письмо. Номер заявки 62829557. Спасибо

**Comment by dmitrijzabrudskij** [comment]
какой район выбирали и когда подавали заявку?

**Comment by veronika4** [comment]
Заявку подавала 30.12.2015 г. в 19.39 в отделение на площади Красной, 2

**Comment by veronika4** [comment]
В г. Днепропетровск

**Comment by veronika4** [comment]
Заявку подавала 30.12.2015 в г. Днепропетровск, ул. Красная Площадь, 2

Отправлено с iPhone

**Comment by dmitrijzabrudskij** [comment]
заявка актуальна. с визитом в миграционную 18.01.2016 в 10:45
письмо с реквизитами и указаниями я переслал Вам на почту еще раз

**Comment by veronika4** [comment]
Все дошло, спасибо!


>Пятница, 15 января 2016, 0:03 -08:00 от dmitrijzabrudskij <notifications@github.com>:
>
>заявка актуальна. с визитом в миграционную 18.01.2016 в 10:45
>письмо с реквизитами и указаниями я переслал Вам на почту еще раз
>—
>Reply to this email directly or  view it on GitHub .


-- 
Вероника Млинарич
