### ISSUE TITLE
База Данных

### ISSUE THREAD

**Issue by DonHose** [e-government-ua/iForum#209]
Добрый день, в каком Дата Центе находятся Ваша информация, интересует надежность сохранения данных.

**Comment by ezhikus** [comment]
Ответ на данный вопросы Вы можете найти здесь: https://github.com/e-government-ua/i/wiki/%D0%91%D0%B5%D0%B7%D0%BF%D0%B5%D1%87%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8
