### ISSUE TITLE
"Отримання допомоги при народженні дитини"

### ISSUE THREAD

**Issue by OksanaF777** [e-government-ua/iForum#21]
Здравствуйте! Уточните, пожалуйста, почему заявка отклонена (номер заявки 6456004)

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой район выбирали при подаче заявки?

**Comment by OksanaF777** [comment]
Выбрала Кировский

**Comment by OksanaF777** [comment]
но закреплена за Новомосковским районом, а там такого нет.

**Comment by dmitrijzabrudskij** [comment]
район прописки еще не участвует в эксперименте. к концу этой недели подключится вся область - тогда сможете переподать

**Comment by OksanaF777** [comment]
но если ребёнку 16.10 исполняется годик, я смогу подать заявку?

**Comment by dmitrijzabrudskij** [comment]
пару дней у вас будет. заявку можно подать до исполнения ребенку 1 года

**Comment by OksanaF777** [comment]
и ещё один вопрос: если мы на данный момент живём за границей?

**Comment by dmitrijzabrudskij** [comment]
место жительства должно быть украинским. но попробуйте.
