### ISSUE TITLE
Когда ожидать выплаты??

### ISSUE THREAD

**Issue by EvaSergeevna92** [e-government-ua/iForum#210]
Заявка 21755724 и 21759363. Они были поданы еще в конце ноября 2015,были отвезены все документы в совбез и теперь глухо как в танке.ответ предыдущий ничего не объяснил "в том месяце когда назначена субсидия",какая к черту субсидия,я не на субсидию подавала,а на соц выплаты на рождение ребенка и по беременности и родам,хотелось бы получить нормальный,вразумительный ответ.спасибо заранее.

**Comment by dmitrijzabrudskij** [comment]
какой район? или поднимите старую ветку, если мы уже переписывались по этим заявкам

**Comment by EvaSergeevna92** [comment]
Жовтневый район
--
Отправлено из Mail.Ru для Android пятница, 15 января 2016г., 11:58 +02:00 от dmitrijzabrudskij < notifications@github.com> :
