### ISSUE TITLE
Предложение  

### ISSUE THREAD

**Issue by PavelKyllik** [e-government-ua/iForum#213]
Добрый день,  хотел предложить делать маленькие презентации на те услуги которые внедряются и на те которые уже работают. 
Возможно, это будут презентации или в виде видеороликов.

**Comment by GrekD** [comment]
Павел, уточнение:
Вы будете делать презентации?

**Comment by PavelKyllik** [comment]
Добрый день Дарья, я предложил идею, может кто то умеет делать видео
ролики, которые за минуту могут показать и объяснить на много больше чем
текст на презентациях.
Я лишь могу делать вот такие презентации ...

2016-01-18 10:02 GMT+02:00 Darja Grek <notifications@github.com>:
