### ISSUE TITLE
Предложение  по АР Крым 

### ISSUE THREAD

**Issue by PavelKyllik** [e-government-ua/iForum#214]
Скажите, может, подумаем, как можно будет людям проходить КПВВ на границе в АР Крым? Запись на дату/время/количество подачу документов для предварительной проверки. 

Что скажите как думаете реально и актуально ли это ? 
Спасибо Вам за уделенное вами время…

**Comment by GrekD** [comment]
Дмитрий Дубилет уже ответил по почте
