### ISSUE TITLE
на мое мыло насыпались уведомления о заявках, которые я не делал

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#215]
![image](https://cloud.githubusercontent.com/assets/8410116/12377089/0ea0f426-bd19-11e5-83a6-1fb52933741c.png)

**Comment by dimahadgi** [comment]
Также после регистрации моя заявка зарегестрировалась 3 раза. Сегодня получил регистрацию на 5 заявок(все зарегистрированы)
Также получил ответы другим пользователям с их персональными данными!

![1](https://cloud.githubusercontent.com/assets/12786192/12377243/4a36e8c8-bd1f-11e5-8a37-f18b1a74cbfe.JPG)
![2](https://cloud.githubusercontent.com/assets/12786192/12377244/4a3768f2-bd1f-11e5-82d6-e30d266aa070.JPG)
![3](https://cloud.githubusercontent.com/assets/12786192/12377245/4a379a8e-bd1f-11e5-8a45-5f9014d1bc67.JPG)
![4](https://cloud.githubusercontent.com/assets/12786192/12377246/4a378774-bd1f-11e5-86ac-999982b445c8.JPG)

**Comment by GrekD** [comment]
был сбой на почтовом сервере, уже испрваили

**Comment by Djohnypalace** [comment]
:) только хотел создать тему - аналогично. 
ЗЫ по теме незаявляющихся заявок на регистрацию авто реакция будет?
