### ISSUE TITLE
Заявка "Об отсутствии судимости"

### ISSUE THREAD

**Issue by proha909** [e-government-ua/iForum#216]
Заявка, которую подавала я 13. 01, № 78738926,уже на следующий день
14. 01 в "статусах"  обозначена как "выполнена", но сообщение о
выполнении не приходило.

Аналогичную заявку "Об отсутствии судимости" № 78762302 через полчаса
после меня в тот же день13. 01.сделал муж. Прошло 6 дней - а воз и
ныне там. Статус "ПРИНЯТА".
Почему  такая разница в сроках? Как быть уверенным, что заявка будет выполнена?
Как отменить заявку, если она не нужна или сделал ошибку?
Спасибо.

**Comment by GrekD** [comment]
@kurbpa помотри, пожалуйста

**Comment by kurbpa** [comment]
@proha909 

После подачи заявки на Ваш емейл должно прийти письмо следующего содержания:
```
Дякуємо, що скористалися Інтернет-сервісом замовлення довідки про наявність або відсутніть судимості! Ваш запит успішно зареєстровано.

Ви зможете забрати Вашу довідку приблизно за 20 робочих днів за адресою вул.Ворошилова 21. 
```
* 78762302  (13.01.2016) - Прохоров И.Г. Заявка взята в работу. Срок обработки заявки в течение 20 рабочих дней.
* 78738926  (13.01.2016) - пытаемся разобраться почему так быстро заявка стала обработана. Возможно это был технический сбой.

**Comment by proha909** [comment]
@kurbpa Спасибо!
