### ISSUE TITLE
Где получить документ?

### ISSUE THREAD

**Issue by AndrewOM** [e-government-ua/iForum#217]
Получил сообщение о готовности документа:"Заява ЗВ-9800002562016 від 13.01.2016 про надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки (кадастровий номер: 1210100000:03:255:0030) оброблена. 
Підготовлено Витяг з тех. док-ії про нормативну грошову оцінку зем. ділянки від 16.01.2016 з реєстраційним номером 17/86-16. 
Отримати документ можна у "Філія центру надання адміністративних послуг Дніпропетровської міської ради "Правобережний"" за адресою 49000, Дніпропетровська обл., м. Дніпропетровськ, просп. Карла Маркса, 75. "
Созвонился с центром надання админпослуг - они ответили, что мне нужно обращаться в  Держгеокадастр, что им они никогда ничего не передают. Вопрос - так где же находится мой  Витяг?

**Comment by GrekD** [comment]
@AndrewOM добрый день
На эту услугу с сайта iGov стоит ссылка на кадастровую карту.
http://map.land.gov.ua/kadastrova-karta
в правом верхнему гулу там есть кнопка "зворотній зв'язок".
Напишите, пожалуйста, Ваше сообщение туда.

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
