### ISSUE TITLE
Социальная помощь при рождении ребёнка

### ISSUE THREAD

**Issue by OksanaF777** [e-government-ua/iForum#22]
Здравствуйте! Посмотрите, пожалуйста, результат по заявке №8554405.

**Comment by OksanaF777** [comment]
Я вроде бы всё правильно заполнила, но моей малышке завтра годик.

**Comment by OksanaF777** [comment]
Наш район появился только сегодня, по-этому заявку получилось только сегодня подать. Очень переживаю, успеем ли мы?

**Comment by dmitrijzabrudskij** [comment]
Оксана, какой район выбирали?

**Comment by OksanaF777** [comment]
Новомосковский район.

**Comment by dmitrijzabrudskij** [comment]
заявка успешно подалась

**Comment by OksanaF777** [comment]
То есть, я успела? Заявка одобрена и всё по закону?

**Comment by dmitrijzabrudskij** [comment]
заявка оформлено правильно и со всеми данными. ждем ответа от района. должны одобрить

**Comment by OksanaF777** [comment]
Спасибо!
