### ISSUE TITLE
заявка 18767414 

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iForum#221]
добрый день
уточните, пожалуйста, район, в который подавалась заявка

**Comment by RayaIlyasova** [comment]
добрый, синельниковский район

**Comment by RayaIlyasova** [comment]
когда я проверяю статус заявки показывает только это - Взяти в роботу (у роботi) 2015-12-09 15:52:58.303.

**Comment by dmitrijzabrudskij** [comment]
она уже в работе у района. когда они ответят нам - маякну сюда по результату. если хотите, можете сами их набрать: (05663)4-22-23. может у Вас быстрее получится

**Comment by RayaIlyasova** [comment]
Сомневаюсь, что получится)) я знаю, какие там "коммуникабельные" люди.

**Comment by dmitrijzabrudskij** [comment]
в понедельник дам ответ. на больничном сотрудник района, поэтому сейчас не могут сказать что с субсидией

**Comment by RayaIlyasova** [comment]
Спасибо.

**Comment by RayaIlyasova** [comment]
Дмитрий,здравствуйте!
Прошу прощения, что отрываю Вас, но тут такое дело
Продолжается эпопея, на прошлой неделе позвонили и сказала принести справку о составе семьи -  ок, отнесли! Сказали позвонить в начале недели и можно будет узнать на счет решения. Сегодня сестра звонила и там теперь просят продиктовать паспортные данные и ин.код мол в заявке есть ошибка...Меня это настораживает, подскажите как быть?

**Comment by dmitrijzabrudskij** [comment]
добрый день
не вижу у них в работе заявок, похожих на Вашу. можете номер напомнить, пожалуйста?

**Comment by RayaIlyasova** [comment]
18767414

**Comment by dmitrijzabrudskij** [comment]
спасибо, нашел. отпишусь по результату

**Comment by annastolbova** [comment]
Заявка закрита 24.02.2016.

Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
