### ISSUE TITLE
пока услуги работают не везде, главная страница неюзабельна

### ISSUE THREAD

**Issue by pal666** [e-government-ua/iForum#222]
надо сделать фильтр услуг по области, чтобы не тыкать во все подряд и не убеждаться, что твоей области нет

**Comment by GrekD** [comment]
@pal666  добрый день
поиск по области есть
Фильтр на скрине
![default](https://cloud.githubusercontent.com/assets/10836093/12459257/7c77cf70-bfb6-11e5-96c4-055fa67605ba.png)

**Comment by pal666** [comment]
супер, еще бы его было легче обнаружить

**Comment by GrekD** [comment]
скоро переделаем - будет заметен. Спасибо!
