### ISSUE TITLE
 заявка на послугу Призначення державної допомоги у зв'язку з вагітністю та пологами

### ISSUE THREAD

**Issue by AnitaLuz** [e-government-ua/iForum#223]
Добрый день!
Какой срок обработки заявки?
 04.01.2016 17:50	Ви подали заявку на послугу Призначення державної допомоги у зв'язку з вагітністю та пологами!. Cтатус: Заявка подана
Сколько мне ждать ответа и ждать ли вообще?
Спасибо!

**Comment by AnitaLuz** [comment]
Район АНД Днепропетровск

**Comment by dmitrijzabrudskij** [comment]
добрый день. какой номер заявки?

**Comment by AnitaLuz** [comment]
номера нет - где его искать?

**Comment by AnitaLuz** [comment]
на почту ничего не пришло
я так понимаю, мою заявку не приняли?

**Comment by AnitaLuz** [comment]
65827847 - в спам попало

**Comment by dmitrijzabrudskij** [comment]
не нахожу эту заявку в анд-районе. точно район правильный?

**Comment by AnitaLuz** [comment]
Амур нижнеднепровский

**Comment by AnitaLuz** [comment]
Что делать с этим? Я стоять не могу в очередях , даже сидеть, никто за меня пойти не может. Может еще раз подать?

**Comment by dmitrijzabrudskij** [comment]
подавайте конечно. вреда не будет
