### ISSUE TITLE
Заявка №23277694

### ISSUE THREAD

**Issue by TapacD** [e-government-ua/iForum#224]
Пришло письмо с ответом Звернення на тему "Отримання субсидії на оплату житлово-комунальних послуг"
В письме файл "=_UTF-8_B_0LTRltC00LXQvdC60L4ucmFy_=" с расширением "файл"
Я менял и на doc. и tex и др. и кодировку ставил UTF-8
все равно абракадабра 
помогите пожалуйста

**Comment by AndreyPopovNew** [comment]
это файл jpg - это картинка

**Comment by TapacD** [comment]
поменял разрешение на jpg - не paint не просмотрщик windows не открывает.
может еще есть способ посмотреть, что там такой уж больно интересно.
Подскажите пожалуйста, что можно еще сделать

**Comment by dmitrijzabrudskij** [comment]
@TapacD подскажите номер заявки и район - я из базы вытащу файл и перешлю Вам. тут отправщик почты стратил - из-за этого такой формат получился

**Comment by TapacD** [comment]
№ заявки 23277694 г. Днепропетровск Красногвардейский район (Чечеловский район по новому)
Спасибо!

**Comment by dmitrijzabrudskij** [comment]
выслал на ту почту, что была в заявке

**Comment by TapacD** [comment]
спасибо

2016-01-26 14:18 GMT+02:00 dmitrijzabrudskij <notifications@github.com>:
