### ISSUE TITLE
Заявка №67064064

### ISSUE THREAD

**Issue by Slav67** [e-government-ua/iForum#225]
Ваше звернення №67064064 успішно зареєстровано,
Результати будуть спрямовані на Ваш e-mail vva-box@ukr.net.
05.01.2016
Перевіряю статус "Невідома помилка сервісу! Час: "2016-01-25T11:32:40.092Z" Функція: searchOrder". Що трапилось?

**Comment by dmitrijzabrudskij** [comment]
добавьте 0- перед тем номером, что пишел Вам на почту - заявка найдется
https://www.dropbox.com/s/g7pdoqxth5lk0n1/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-01-25%2016.02.19.png?dl=0

**Comment by Slav67** [comment]
Спасибо получилось. А, что с самой заявкой? Когда, хотя-бы  примерно, можно ждать результата?

**Comment by dmitrijzabrudskij** [comment]
сейчас срок у них 30 рабочих дней. некоторые районы справляются раньше, некоторые позже...

**Comment by Slav67** [comment]
Спасибо. Будем ждать с нетерпением, потому что платить уже не чем.

**Comment by annastolbova** [comment]
Заявка закрита 12.02.2016.

Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
