### ISSUE TITLE
Заявки 68505047, 68501668

### ISSUE THREAD

**Issue by MaksymKM** [e-government-ua/iForum#226]
Добрый день.
7 января подавались заявки 68505047, 68501668.
Подскажите, пожалуйста, по следующим вопросам:
1. Если заявка принята, то значит ли что она будет точно положительно обработана? Волнует момент, что придется ждать 20 дней, а потом получить отказ.
2. Статистка на данный момент: 18 днів, 12 годин, 19 хвилин. Эти дни - рабочие или календарные? Т.е. вопрос плана - ожидать ли мне справку в ближашие несколько дней или через две недели (4-5 февраля)?

Спасибо за ответы

**Comment by GrekD** [comment]
@MaksymKM 
1. значит ли что она будет точно положительно обработана - нет, не значит
2. календарные

**Comment by MaksymKM** [comment]
Спасибо за ответ. Как я понимаю на данный момент статуса "Заявка в процессе обработки" или подобной для справки о несудимости не предусмотрено?

**Comment by GrekD** [comment]
@kurbpa посмотри, пожалуйста

**Comment by GrekD** [comment]
по заявкам было принято положительное решение
