### ISSUE TITLE
Помилка при оформлені запиту на допомогу при народжені дитини

### ISSUE THREAD

**Issue by JuliaMudrak** [e-government-ua/iForum#227]
12 січня через портал державних послуг оформлювала зверненя на отримання допомоги, при відправці виникла помилка, але на мою пошту надійшов лист :
Шановний(-а) ЮЛІЯ ЮРІЇВНА.
Ваше звернення щодо отримання отримання допомоги при народженні дитини зареєстроване. Ви отримаєте відповідь протягом 20 робочих днів.
Контакти підрозділу соцзахисту, яке буде займатися обробкою Вашого звернення:
УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ
49000, Дніпропетровськ, вулиця Радистів, 8
Режим роботи з 8.00 до 17.00
Телефон для довідок: (056) 375-90-64, (056) 376-52-03

Телефоную за цими номерами щоб дізнатися , не відповідають
Що мені робити???

**Comment by dmitrijzabrudskij** [comment]
вам пришло письмо с номером заявки?

**Comment by JuliaMudrak** [comment]
Дякую за увагу, самостійно відвідала Центр соціального захисту населення, вистояла чергу, як виявилось нікаких звернень до них не надходило.... :-(  (Ідея порталу гарна але поки що потрібно допрацювати) 

26 января 2016, 13:02:25, от "dmitrijzabrudskij" < notifications@github.com >: 

вам пришло письмо с номером заявки? —

**Comment by dmitrijzabrudskij** [comment]
я не просто так спросил про номер заявки - если он высветился на экране после нажатия на "замовити", то все в порядке - заявка ушла в район.
если его не было - то произошла какая-то ошибка и заявку нужно переподать

и все-таки: был номер или нет?

пс: услуги соцзащиты почти все работают в полностью удаленном режиме -  ходить никуда не нужно

**Comment by JuliaMudrak** [comment]
ні, номер не приходив, тільки лист : 

iGov 
портал державних послуг Шановний(-а) ЮЛІЯ ЮРІЇВНА. 

Ваше звернення щодо отримання отримання допомоги при народженні дитини зареєстроване. Ви отримаєте відповідь протягом 20 робочих днів. Контакти підрозділу соцзахисту, яке буде займатися обробкою Вашого звернення: УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ 
49000, Дніпропетровськ, вулиця Радистів, 8 
Режим роботи з 8.00 до 17.00 
Телефон для довідок: (056) 375-90-64, (056) 376-52-03 З повагою, 
УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ 
Команда Порталу державних послуг iGov 

26 января 2016, 15:09:54, от "dmitrijzabrudskij" < notifications@github.com >: 

я не просто так спросил про номер заявки - если он высветился на экране после нажатия на "замовити", то все в порядке - заявка ушла в район. 
если его не было - то произошла какая-то ошибка и заявку нужно переподать и все-таки: был номер или нет? пс: услуги соцзащиты почти все работают в полностью удаленном режиме - ходить никуда не нужно —

**Comment by dmitrijzabrudskij** [comment]
такое письмо отправляется еще до того, как заявке присваивается номер. такие особенности работы, к сожалению. из-за этого и бывают такие ситуации, как у Вас. приношу извинения

в будущем в таких случаях просто подавайте новую заявку - все равно все дубли районы отбракуют и оставят в работе самую правильную
