### ISSUE TITLE
ошибка при оформлении заявки на субсидию

### ISSUE THREAD

**Issue by kotgav** [e-government-ua/iForum#228]
---------------------------
Помилка по операції: 'Сабміт форми послуги'

Помилка при запиті!

Час: "2016-01-27T09:37:55.516Z"

Функція: submitForm
Відповідь сервера:Код: SYSTEM_ERRІнші дані (обь'єкт): {"code":null,"message":null}
Значення параметрів:nID_Service: 654,nID_ServiceData: 549,processDefinitionId: subsidiesUkraine:1:1,saField: [{"sID":"sID_Public_SubjectOrganJoin","sType":"select","sValue":"0"},

ЛИЧНЫЕ ДАННЫЕ УДАЛЕНЫ

Дані відсілаються на сервер...

---------------------------
Помилка по операції: 'Сабміт форми послуги'

Повернен пустий об'ект!

Час: "2016-01-27T09:37:55.519Z"

Функція: submitForm(UI)
Значення параметрів:nID_Service: 654,nID_ServiceData: 549,processDefinitionId: subsidiesUkraine:1:1,

Дані відсілаються на сервер...
------------------------------

**Comment by dmitrijzabrudskij** [comment]
не могу воспроизвести. какая область-район выбиралась при подаче?

**Comment by kotgav** [comment]
Одесская область, 
к сожалению г. Одессы в списке районов нет, поэтому район был оставлен пустым.

**Comment by dmitrijzabrudskij** [comment]
вот из-за этого и ошибка:(
Одесса пока не участвует в проекте, поэтому ее и нет в выборе районов - пытаемся договориться с ними, чтобы запустить. пока только все районы Одесской области доступны, кроме городских

**Comment by kotgav** [comment]
но ошибку из-за этого не показывало, наверное надо сделать проверку на пустое поле :)
а мы пока ждем, когда же заработает и для одессы.
заранее огромное вам спасибо!

**Comment by dmitrijzabrudskij** [comment]
да, нормальную ошибку сделаем. спасибо за пример

**Comment by kotgav** [comment]
ждем одессу :)
