### ISSUE TITLE
Заявка на региональном портале не может быть обработана, если гражданин ввёл некорректный email

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iForum#229]
На альфе заявка 100502680, гражданин ввёл некоректный адрес электронной почты (chvsl@ukr.net - не существует). При попытке обработать данную заявку на региональном портале при нажатии кнопки "Опрацювати" пишется "Зачекайте..." и на этом всё. При этом сервер возвращает код 500 и текст ошибки:

"{"code":"SYSTEM_ERR","message":"couldn't execute activity <serviceTask id=\"servicetask6\" ...>: Error happened when sending email (chvsl@ukr.net)(oID_Message=41067746)"}"

Понятно, что письмо не может быть отослано на невалидный адрес. А что дальше? Как эту заявку закрыть\удалить?

Требуется: 

1. Корректное сообщение об ошибке - что-то типа "Заявника не може бути повідомлено про результат обробки заяви електронною поштою, оскільки введений ним email не є валідним. Будь ласка, повідомте заявника іншим способом (по телефону, поштою)."

2. Способ закрыть заявку.

**Comment by Koffeek** [comment]
@ezhikus Проблема встала после перехода на новый способ доставки писем, раньше её не было. Знаем, работаем над этим.

**Comment by Koffeek** [comment]
@ezhikus Проблема решена. Если дело только в почте, то заявка должна закрываться.

**Comment by ezhikus** [comment]
Проверил на альфе, заявка закрывается.
