### ISSUE TITLE
Фильтрация доступных услуг по месту

### ISSUE THREAD

**Issue by loginwashere** [e-government-ua/iForum#23]
Как я понял в Харькове сейчас доступно не очень много услуг и при фильтрации нет возможности  выбрать место (область, город), чтобы получить список всех доступных там услуг. Из-за этого приходится преходить в каждую услугу чтобы проверить доступна ли она втом или ином месте.

Возможно было бы удобнее иметь возможность выбрать место  при просмотре общего списка услуг.

**Comment by annastolbova** [comment]
На цей момент фільтр по області та місту вже є.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
