### ISSUE TITLE
Смена стиля курсора для disabled-полей на региональном портале

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iForum#231]
В данный момент при наведении курсора мышки на нередактируемое поле в заявке мы видим вот такой курсор (в CSS "cursor: not-allowed"):

![1](https://cloud.githubusercontent.com/assets/1929332/12696191/61b1531a-c76c-11e5-8017-ef884e95e05e.png)

Это делает очень трудной задачи вроде "выделить из поля пасспортных данных отдельно номер паспорта и отдельно - кем выдан". Курсор большой, закрывает буквы, позиционироваться трудно. Кроме того, стиль "not-allowed" - это вообще про другое и к текстовым полям не применяется (http://www.w3schools.com/cssref/pr_class_cursor.asp)

Предлагаю поставить стиль "cursor: text"

**Comment by manwhowins** [comment]
Поддерживаю идею, cursor: text больше подходит.

**Comment by manwhowins** [comment]
Реализовано.

**Comment by ezhikus** [comment]
Проверено на альфе - работает.
@manwhowins , спасибо
