### ISSUE TITLE
Ошибка доступности услуги в Кривом Рогу

### ISSUE THREAD

**Issue by Garvan1** [e-government-ua/iForum#232]
При поиске услуги "Вклеювання до паспорта громадянина фотокартки при досягненні 25- і 45-річного віку" по городу Кривой Рог - она доступна
![1](https://cloud.githubusercontent.com/assets/16986530/12702470/995d304c-c832-11e5-8e33-c7d6df52858b.PNG)

При попытке зарегистрироваться - уже не доступна

![2](https://cloud.githubusercontent.com/assets/16986530/12702471/9d431794-c832-11e5-9481-955f530d6980.PNG)

**Comment by Koffeek** [comment]
@Garvan1 к сожалению - это ошибка фильтра. При фильтрации подобным образом доступными показываются услуги, которые есть хотя бы в одном городе области. В этом вопросе сейчас разбираются. Спасибо.

**Comment by annastolbova** [comment]
помилка вже виправлена.
дякуємо за коментар.
якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
