### ISSUE TITLE
Заявка закрита з відгуком. Как это ??? (у відгуку нічого не написано)

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#234]
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1662319254056951&comment_tracking=%7B%22tn%22%3A%22R%22%7D

Слава Кузькин:
Заявка закрита з відгуком. Как это ???Подскажите,а то как додумать не получается.

**Comment by VadymVolos** [comment]
Я вже запитав
"Що у відгуку написано? Якщо написано про відгук, в ньому напевно є деталі чому закрита."

**Comment by 777leon** [comment]
Добрый день.У видгуку ни чего не написано.Заявка закрита з відгуком.Больше ни чего нет.

**Comment by VadymVolos** [comment]
Пока никто не откликнулся. @777leon напишите пока тут ваш город, район, и номер той заявки. Когда возьмутся за вашу проблему так быстрей смогут найти ее.

**Comment by 777leon** [comment]
г. Днепропетровск Ленинский район   заявка №0-63750066

**Comment by 777leon** [comment]
Уже разобрался.Есть следующий вопрос.Хочу оформить субсидию ,но я работаю не официально как заполнять строку об организации где получаю доход.Что я должен там указать.Инше не подходит.

**Comment by VadymVolos** [comment]
1. Напишите пожалуйста как решили вопрос, чтоб другие с подобной проблемой знали как решить.
2. Для второго вопроса создайте новую тему тут, это поможет людям с подобным вопросом ее найти "Хочу оформить субсидию, но я работаю не официально как заполнять строку"

**Comment by 777leon** [comment]
Вопрос решился сам собой.На мыло пришло письмо с опаздыванием на месяц.Подал другую заявку ,ответ пришел в течении 20 минут.

**Comment by VadymVolos** [comment]
Понятно, спасибо за ответ, я эту тему закрываю так как вопрос из шапки решен.

**Comment by 777leon** [comment]
Как создать новую тему ,не могу найти 

05 февраля 2016, 09:05:18, от "VADYM VOLOS" < notifications@github.com >: 

Понятно, спасибо за ответ, я эту тему закрываю так как вопрос из шапки решен. —

**Comment by VadymVolos** [comment]
Нажмите сверху зеленую кнопку "New issue" эти и есть создание новой темы.
