### ISSUE TITLE
Проблема с письмами

### ISSUE THREAD

**Issue by Alexander2017** [e-government-ua/iForum#235]
Оформил загранку,пришло 2 письма с номером и инфо.,по ошибки удалил их,возможно ли мне опять переслать их???

**Comment by VadymVolos** [comment]
ВЫ удалили в корзину? С корзины их достать можете?

**Comment by Koffeek** [comment]
@Alexander2017 в принципе можем попробовать. Укажите дату визита и подразделение ДМС, в которое подавали заявку.

**Comment by Alexander2017** [comment]
Да с корзины удалил

-- реклама -----------------------------------------------------------
Управление сайтом на популярных CMS это так просто!
Хостинг http://FREEhost.UA делает всю черновую работу за Вас.

**Comment by Alexander2017** [comment]
Ви подали заявку на послугу Отримання паспорта громадянина України для виїзда за кордон. Cтатус: обробка дмс
дня 3-5 назад

**Comment by Alexander2017** [comment]
3 февраля если не ошибаюсь я делал запрос на загранку

**Comment by Alexander2017** [comment]
Так мне помогут с моей проблемой или нет?

**Comment by Koffeek** [comment]
@Alexander2017 повторю вопрос. в какое отделение делали запрос и хотя бы какой-то параметр для поиска, если номера заявки нет (дата для прихода, ФИО, почта)

**Comment by Alexander2017** [comment]
Кузьменко Александр Николаевич....Dickens@i.ua
Сделал запрос чтобы получить загран паспорт

-- реклама -----------------------------------------------------------
Управление сайтом на популярных CMS это так просто!
Хостинг http://FREEhost.UA делает всю черновую работу за Вас.

**Comment by Alexander2017** [comment]
28 или 29 марта дата прихода

**Comment by Koffeek** [comment]
@Alexander2017 заявку нашел. Сейчас повторно отправлю письма на указанный адрес.

**Comment by Alexander2017** [comment]
спасибо

-- реклама -----------------------------------------------------------
Управление сайтом на популярных CMS это так просто!
Хостинг http://FREEhost.UA делает всю черновую работу за Вас.

**Comment by Alexander2017** [comment]
А второе письмо с номером заявки не нашли?

**Comment by Koffeek** [comment]
Письмо с номером заявки отправил. Можно закрывать.
