### ISSUE TITLE
Хочу оформить субсидию ,но я работаю не официально как заполнять строку об организации где получаю доход

### ISSUE THREAD

**Issue by 777leon** [e-government-ua/iForum#236]

**Comment by dmitrijzabrudskij** [comment]
пишите, что не работаете. соцзащита будет ориентироваться на данные налоговой о Ваших доходах - в Вашем случае информации у налоговой не будет

**Comment by 777leon** [comment]
т.е Я УКАЗЫВАЮ В ГРАФЕ БЕЗ РАБОТНЫЙ,Я ПРАВИЛЬНО ПОНЯЛ. 

05 февраля 2016, 10:19:17, от "dmitrijzabrudskij" < notifications@github.com >: 

пишите, что не работаете. соцзащита будет ориентироваться на данные налоговой о Ваших доходах - в Вашем случае информации у налоговой не будет —

**Comment by dmitrijzabrudskij** [comment]
да.

пс: безработный пишется слитно

**Comment by 777leon** [comment]
Спасибо. 
05 февраля 2016, 15:10:47, от "dmitrijzabrudskij" < notifications@github.com >: 

да. пс: безработный пишется слитно —
