### ISSUE TITLE
не могу подать заявку на перерегистрацию авто

### ISSUE THREAD

**Issue by KonstantinManoilo** [e-government-ua/iForum#237]
Добрый день, при подаче заявки предлагается выбрать дату визита в МРЭО, но в выпадающем списке нет возможности выбрать дату, а вручную ввести не получается. Вот скрин http://screencast.com/t/HPwm76Xqvs17. Из-за этого не получается подать заявку. Проблема длится уже неделю, примите меры

**Comment by Koffeek** [comment]
@KonstantinManoilo В каком городе подаете заявку?

**Comment by KonstantinManoilo** [comment]
@Koffeek В Киеве

**Comment by Koffeek** [comment]
@KonstantinManoilo В Киеве на данный момент идет переаттестация сотрудников и услуга временно не предоставляется.

**Comment by KonstantinManoilo** [comment]
@Koffeek как долго это будет продолжаться и как в таком случае произвести перерегистрацию?

**Comment by Koffeek** [comment]
@KonstantinManoilo Точные сроки на данный момент не известны. Для перерегистрации необходимо лично ехать в сервисный центр.

**Comment by KonstantinManoilo** [comment]
@Koffeek сколько эта процедура будет стоить и как быстро по срокам?

**Comment by Koffeek** [comment]
@KonstantinManoilo стоимость может разниться в зависимости от автомобиля, необходимости экспертизы и некоторых других параметров (в Днепропетровске 350-500 грн. без учета экспертизы), по времени также всё зависит от загруженности Сервисного центра и экперта.

**Comment by KonstantinManoilo** [comment]
@Koffeek а где можно подробно почитать об этой услуге, чтобы работники МРЭО не вешали лапшу на уши? Нужно просто поменять номера в связи со сменой прописки

**Comment by Koffeek** [comment]
@KonstantinManoilo наша услуга из другой области, она заказывается при купле-продаже авто. По Вашей ситуации, к сожалению, подсказать не могу.

**Comment by annastolbova** [comment]
Зараз старі послуги по авто трансформовані в наступні 9 послуг:

1. Перереєстрація транспортного засобу на нового власника за договором купівлі-продажу 
2. Зміна анкетних данних власника транспортного засобу 
3. Зняття транспортного засобу з обліку для реалізації 
4. Перереєстрація транспортного засобу на нового власника по успадкуванню 
5. Перереєстрація транспортного засобу при видачі дубліката свідоцтва 
6. Перереєстрація транспортного засобу при заміні номерного знаку 
7. Перереєстрація транспортного засобу при переобладнанні без зміни ном.агрегатів 
8. Реєстрація транспортного засобу привезеного з-за кордону 
9. Реєстрація транспортного засобу придбаного в торгівельній організації (нові транспортні засоби)

Ви можете обрати необхідну послугу і замовити ії.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
