### ISSUE TITLE
Нет ответа по заявке на субсидию 0-55836186

### ISSUE THREAD

**Issue by Volchkov** [e-government-ua/iForum#238]
Доброго дня, подскажите пожалуйста, заявка подана 2015-12-26 14:05:08.740, как долго ждать результат по заявке ? Контактные номера АНД отделения не отвечают (3759061, 232320)

**Comment by Volchkov** [comment]
Вопрос закрыт. 17.02.2016 пришел ответ.

**Comment by annastolbova** [comment]
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
