### ISSUE TITLE
 заявка 0-79202237 и что с ней произошло?

### ISSUE THREAD

**Issue by Tamara555** [e-government-ua/iForum#239]
Добрый день. По моей заявке 0-79202237 в статусах написано "2016-01-14 17:45:01.781 Заявка закрита з відгуком - " Никакого видгука нет. Что это значит? как можно понять, что с ней произошло и каков ее статус?

**Comment by GrekD** [comment]
@Tamara555 
Добрый день. Извините за поздний ответ
Ваша заявка была закрыта со статусом "відмова в обробці" и комментарием административного органа: Якщо    субсидія   для   відшкодування   витрат   на   оплату \nжитлово-комунальних   послуг  призначається  у  I  кварталі  року, \nсередньомісячний сукупний дохід визначається за перші три квартали \nпопереднього  року,  в  інших випадках - за попередній календарний \nрік.
