### ISSUE TITLE
Невірний показ доступності послуги

### ISSUE THREAD

**Issue by DBuldakov** [e-government-ua/iForum#24]
послуга "Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України." id=1

![screen shot 2015-10-15 at 2 15 33 pm](https://cloud.githubusercontent.com/assets/15142828/10515653/1b0f1d42-735d-11e5-9e41-1d7daf2fc5eb.png)

**Comment by dmitrijzabrudskij** [comment]
ну так ее нет в Харькове. в чем неправильность?

**Comment by DBuldakov** [comment]
Неисправность в том, что на первом экране она показывается как доступная для региона.

**Comment by dmitrijzabrudskij** [comment]
я не увидел ее доступной для харьковской области. у Вас точно повторяется эта ситуация?

**Comment by DBuldakov** [comment]
Нет не точно, с отличиями - время дня разное, браузеры разные, настроение, так что ситуация повторяется приблизительно.

1. откройте анонимную сессию браузера
2. перейдите в адресную строку (Cmd/Ctrl + L)
3. наберите igov.org.ua
4. нажмите Enter
5. подождите пока страница полностью загрузится
6. кликните мышкой на экранную кнопку расширенного поиска -  уголок вниз в конце вайджета поиска
7. кликните мышкой в поле "регион"
8. наберите на клавиатуре букву "х"
9. сосчитайте до 10
10. дождитесь появления списка из трех обастей
11. кликните мышкой на "Харьковская"
12. сосчитайте 23
13. дождитесь пока закончится поиск
14. проверьте результаты поиска под формой поиска

Ожидаемый результат
показывается текст - 0 послуг доступно онлайн

Актуальный результат
показывается текст с гиперссылками

1 — послуги доступно онлайн
Громадянам
Міліція та ДАІ
 Надання довідки про відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України.


PS: словно с работы и не уходил...

**Comment by bvv4ik** [comment]
там по фактически есть активная услуга, хоть и для Днепра... видать как-то напутаны связки областей/регионов... разберемся

**Comment by annastolbova** [comment]
отображение услуги на данный момент уже корректное
