### ISSUE TITLE
Не заполняется заявка на регистацию авто с пробегом г. Днепропетровск

### ISSUE THREAD

**Issue by KIV0906** [e-government-ua/iForum#240]
Прошу помочь срегистацией завки на переофрмление авто. В поле желаемая дата визита не выбирается дата, прошу станить ошибку. Мои кординаты моб. 0673017632 почта  3017632@gmail.com. Заранее благодарен.

**Comment by Koffeek** [comment]
@KIV0906 ответил в почту

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
