### ISSUE TITLE
Ошибка при отправке, после заполнения формы

### ISSUE THREAD

**Issue by GuNGG** [e-government-ua/iForum#241]
Возникает ошибка при отправке формы, после заполнения ее полей http://joxi.ru/4DmBqzKfWkg8rP. А так же в списке форме меню отсутствует главный город Одесской области - Одесса (Одеса) http://joxi.ru/E5md5vKh0QeV21

**Comment by AndreyPopovNew** [comment]
@GuNGG укажите конкретную услугу.

на скриншотах непонятно о чем речь

Одесса есть в списках.

![image](https://cloud.githubusercontent.com/assets/8410116/12916142/ce54480a-cf38-11e5-8118-258e4d860742.png)

**Comment by GuNGG** [comment]
Услуга предоставления жилищной субсидии 
В данный  момент  вообще нет возможности войти в этот раздел http://joxi.ru/vn2YvZpTy1VgA6

**Comment by GuNGG** [comment]
http://joxi.ru/LVm6l9jHbW79AZ нет возможности выбора города (ТОЛЬКО в Одесской области!!!)  при “Отримання субсидії на оплату житлово-комунальних послуг”

**Comment by AndreyPopovNew** [comment]
уже тут была такая тема вроде. в Одессе недоступна эта услуга.

**Comment by GuNGG** [comment]
Как вы ответите на это http://usi.online/2016/01/21/zhiteli-odesskoj-oblasti-teper-mogut-poluchit-subsidii-ne-vyhodya-iz-doma/ ???
(Электронный сервис в сфере получения субсидий на оплату жилищно-коммунальных услуг доступен для жителей Одесской области. Более продвинутым обслуживанием могут похвастаться только Днепропетровская (115 услуг), Винницкая (49) и Киевская (35) области. Как рассказала заместитель одесского губернатора Мария Гайдар, на данный момент одним из главных тормозящих факторов в развитии сферы электронных государственных услуг в Одесской области является традиционная бюрократия и человеческий фактор.? 
И почему тогда,   нет информации, что эта услуга недоступна, как в других недоступных услугах?!

**Comment by dmitrijzabrudskij** [comment]
добрый день
депратамент соцзащиты области подчиняется губернатору, районы соцзащиты области подчиняются департаменту соцзащиты области
НО
районы соцзащиты города подчиняются мэру города

и вот с самим городом пока договоренности о работе через igov нет
поэтому услуга для самой Одессы недоступна

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
