### ISSUE TITLE
Заявка 7842924 и 19827942

### ISSUE THREAD

**Issue by elenakyshnirenko** [e-government-ua/iForum#242]
Заявка 7842924 зарегестрирована еще 12.10.2015.Ответа никакого нет,заявку не возможно отследить, пишут, что старый формат и ошибку.Хотелось бы узнать хоть какой-то ответ по заявке.
Заявка 19827942 за.регестрирована 24.11.2015.Ответа нет, и тоже не отслеживается.Что с этой заявкой?

**Comment by AndreyPopovNew** [comment]
попробуйте в таком формате 0-7842924 и 0-19827942

**Comment by elenakyshnirenko** [comment]
Статус теперь вижу, "2015-10-12 11:30:02.987	Заявка закрита з відгуком -" и всё.Какой именно "відгук" не понятно...Читала в ветке такой же вопрос и конкретно не ответили,мне ,что по новой заявку отправлять,я ответ на эту 4 месяца жду?

**Comment by GrekD** [comment]
@elenakyshnirenko 
Вы были авторизованы в системе в то время как просматривали статус?

**Comment by elenakyshnirenko** [comment]
Да,я была авторизирована,заходила через Банкинг.

**Comment by elenakyshnirenko** [comment]
Ничего не понятно с этой системой.7842924 Заявка закрыта с отзывом 12.10.2015...хотя в статусе документов еще 24.11.2015 была написано ,что принята и все....Вторая заявка 19827942 все еще в работе,хотя прошло далеко за 20 дней.(подана и принята 24.11.2015) На электронную почту ни одного ответа не приходило. г.Днепропетровск Ленинский район.

**Comment by elenakyshnirenko** [comment]
Ответ по заявке 19827942 пришел.По ней субсидию начислили. А вот с заявкой 7842924 так ничего и не ясно.Устала ждать-подала новую заявку.На этот раз хоть адрес и номер телефона прислали(спасибо большое, а то н найдешь их нигде)И срок обработки заявки уже не 20 дней,а 30.

**Comment by GrekD** [comment]
@elenakyshnirenko 
7842924 - эта заявка закрыта со статусом "відмова в обробці" с комментарием административного органа: Вкажіть назву організаціїї де отримуєте соціальну допомогу, наприклад УПСЗН ЛЕнінського району, уточніть опалювальну площу з загальною, так як опалювальна повинна бути меншою від загальної - балкон, ванна кімната не отоплюються.

Правильно сделали, что подали новую, ждите по ней ответа
