### ISSUE TITLE
Нормативна грошова оцінка земельної ділянки для бізнесу

### ISSUE THREAD

**Issue by WalterRWJ** [e-government-ua/iForum#243]
Здравствуйте!
Подали заявку на "витяг з Державного земельного кадастру про нормативно грошову оцінку".
С igov перенаправило на http://e-gov.dzk.gov.ua.
Номер заявки: 9800023662016
Дата подачи: 28/01/16
Статус "Передано на опрацювання" отображается со второго с 29/01/16. 
Можно каким-то образом узнать, на какой стадии выполнения заявка?
Нам нужно в определенные сроки вложиться, поэтому хотелось бы знать, ждать выполнения заявки или сделать уже все по старинке. 
Спасибо!

**Comment by WalterRWJ** [comment]
На странице мониторинга http://e-gov.dzk.gov.ua/dashboard/excerpts
что по номеру заявки, что по кадастровому номеру ничего нет: "Нема записів для відображення".

**Comment by Koffeek** [comment]
@WalterRWJ Добрый день. Услугу "Нормативна грошова оцінка земельної ділянки для бізнесу" предоставляет Кадастровая карта. На портале iGov стоит только редирект. Поэтому, к сожалению, не можем помочь Вам.

**Comment by WalterRWJ** [comment]
Сегодня получили.
Спасибо!

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
