### ISSUE TITLE
Отримання довідки про доходи фізичних осіб (предложение)

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#244]
по услуге [Отримання довідки про доходи фізичних осіб ](https://igov.org.ua/service/655/general)

после заказа приходит письмо где написано в частности:

- заяву на отримання довідки про доходи (Ви можете її заповнити вдома або зробити це на місці, шаблон заяви)

![image](https://cloud.githubusercontent.com/assets/8410116/12981235/7282b30c-d0e8-11e5-9c7c-1ca4f834d18d.png)

в заявлении все теже!!!! поля, что заполняются при подаче заявки.

почему нельзя одновременно с заявкой формировать заявление? в pdf или jpg(tiff) и присылать заполненное заявление, которое можно просто взять и распечатать.
или у себя или в налоговой по номеру заявки.

а не заполнять его снова.....

**Comment by dmitrijzabrudskij** [comment]
да, спасибо за предложение - это сделаем
