### ISSUE TITLE
Не пришли письма после подачи заявки.

### ISSUE THREAD

**Issue by alena-dp** [e-government-ua/iForum#245]
Добрый день.
Я подала заявки и не получила ни одного письма.
Олена Олегівна Топоровська
10.02.2016 13:34	Ви подали заявку на послугу Отримання паспорта громадянина України для виїзда за кордон для дитини. Cтатус: обробка дмс
10.02.2016 13:29	Ви подали заявку на послугу Отримання паспорта громадянина України для виїзда за кордон. Cтатус: обробка дмс

Как можно узнать причину?

**Comment by AndreyPopovNew** [comment]
а до этого приходили письма? e-mail адрес вы указали верно?

**Comment by alena-dp** [comment]
Письма на этот адрес приходят постоянно, адрес указан верно, т.к. когда повторно захожу для заказа услуги, вижу адрес правильный. Уведомление о вашем ответе с этого сайта тоже пришло. На igov впервые заказываю услугу.

**Comment by alena-dp** [comment]
Спасибо. Вопрос закрыт. Они угодили в спам, нашла через почтоый сервер на сайте.
