### ISSUE TITLE
Попробовал оформить услугу на "получение пособия по рождению ребенка" в Одесской обл - получил SERERROR. Заполнил тикет по ссылке "Повідомити про помилку на порталі" - не ответа не привета (довольно долго).

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iForum#248]
Игорь, будем тут решать эту проблему

подскажите плиз повторяется ли и есть ли полный текст ошибки?

**Comment by ikatrechko** [comment]
#### Как воспроизвести проблему:

1. Отрыть портал iGov и кликнуть по ссылке "Призначення соціальної допомоги при народженні дитини"
2. На вкладке "Послуга" выбрать для "Крок 1. Оберіть свій регіон. Область" - **Одеська**
3. Кликнуть для "Крок 2. Увійдіть в систему через" - **BankID** и проити авторизацию (в даном случае через ПриватБанк)
4. Заполнить оставшиеся поля формы (в даном случае значениями из файла _values.txt_ как на _screen1.jpg, screen2.jpg, screen3.jpg_)
5. Кликнуть "Замовити послугу" и сазабмитить заявку
===============>

6. Popup диалог со следующим текстом появляеться:

> Помилка по операції: 'Сабміт форми послуги'
> Помилка при запиті!
> 
> Час: "2016-02-15T20:15:43.209Z" , Функція: submitForm
> Відповідь сервера:
> Код: SYSTEM_ERRІнші дані (обь'єкт): {"code":null,"message":null}
> Значення параметрів:
> nID_Service: 752,nID_ServiceData: 678,processDefinitionId: socialhelp_kidsUkraine:1:1,saField: [{"sID":"sID_Public_SubjectOrganJoin","sType":"select","sValue":"0"},{"sID":"bankIdlastName","sType":"string","sValue":"КАТРЕЧКО"},{"sID":"bankIdfirstName","sType":"string","sValue":"ГАЛИНА"},{"sID":"bankIdmiddleName","sType":"string","sValue":"ВОЛОДИМИРІВНА"},{"sID":"bankIdbirthDay","sType":"string","sValue":"20.01.1984"},{"sID":"bankIdPassport","sType":"string","sValue":"КМ478173 АНАНЬЕВСКИМ РО ГУМВД УКРАИНЫ В ОДЕССКОЙ ОБЛ 27.08.2007"},{"sID":"bankIdinn","sType":"string","sValue":"3070016165"},{"sID":"adress1","sType":"string","sValue":"Одеська обл. Овідіопольський район с. Нова долина вул. Крупскої 2/8б кв. 21"},{"sID":"adress2","sType":"string","sValue":"Одеська обл. м. Одеса вул. ген.Бочарова буд. 71/1 кв. 63"},{"sID":"email","sType":"string","sValue":"cechina.galina@gmail.com"},{"sID":"bankId_scan_passport","sType":"file","sValue":"79f26954-3190-4ab3-8d79-1afe01df32b7"},{"sID":"inn_scan","sType":"file","sValue":{"id":"7b374e39-868d-4478-99d0-a8754a6c5a96","signInfo":null,"fromDocuments":false}},{"sID":"birthdocument_scan","sType":"file","sValue":{"id":"93185358-c64a-4aa3-b764-6ad3e0839b04","signInfo":null,"fromDocuments":false}},{"sID":"transfer_type","sType":"enum","sValue":"attr2_bank"},{"sID":"post_office","sType":"string","sValue":"-"},{"sID":"bank_name","sType":"string","sValue":"ПриватБанк"},{"sID":"bank_mfo","sType":"long","sValue":"328704"},{"sID":"bank_okpo","sType":"long","sValue":"14360570"},{"sID":"bank_account","sType":"long","sValue":"25606054400253"},{"sID":"bankticket","sType":"file","sValue":{"id":"19663640-74d0-47b7-92b8-1fda6ddb385d","signInfo":null,"fromDocuments":false}}],
> 
> 

7..  После закрытия предыдущего диалога появляеться новое со следующим текстом:

> Помилка по операції: 'Сабміт форми послуги'
> Повернен пустий об'ект!
> 
> Час: "2016-02-15T20:15:43.213Z" , Функція: submitForm(UI)
> Значення параметрів:
> nID_Service: 752,nID_ServiceData: 678,processDefinitionId: socialhelp_kidsUkraine:1:1,

**Comment by dmitrijzabrudskij** [comment]
так выберите район, в который отправляете заявку. из-за него и ошибка - он пустой сейчас

**Comment by ikatrechko** [comment]
Так и предпологал когда детали запроса вчера расмотрел (раньше было просто уведомление sererror). 

Почему я не выбрал район:
1) Поле не обязательно для заполнения
2) В списке нет г. Одесса (подходящее значение)

Если отсутствие г. Одесса связано с тем, что услуга там еще не доступна, может имело бы слысл задизайнить такое же поведение как и для поля на "Крок 1. Оберіть свій регіон. Область" (тоесть в списке все значения, невалидные подкрашены в серый цвет), а само поле "Оберiть свiй район або мiсто" зделать обязательным (пометить красным астериксом)

Но это up to you. В любом случае спасибо.

P.S. Попробую вечером подать заявку еще раз, в случае успеха отпишусь и подтеру свои даные (скрины и  респонс)

**Comment by dmitrijzabrudskij** [comment]
участвуют сейчас все районы области, кроме самого города, к сожалению((
пытаемся с ними договориться

**Comment by dmitrijzabrudskij** [comment]
сделать выбор района обязательным попробую. спасибо

**Comment by ikatrechko** [comment]
При указании района заявка успешно засабмитилась. Вопрос с моей стороны закрыт. 

**Еще раз спасибо команде iGov за вашу большую и важную работу**
