### ISSUE TITLE
Субсидия. Киев

### ISSUE THREAD

**Issue by NadinSA** [e-government-ua/iForum#249]
Скажите,в Киеве кроме Деснянского и Соломенского района есть и другие районы. 
Им оформление субсидии через портал не предусмотрено? (при попытке заполнить форму на субсидию необходимо выбрать свой район проживания, но Киев несколько больше, чем эти два района). 
Как оформить заявку? Помогите пожалуйста.

**Comment by dmitrijzabrudskij** [comment]
в Киеве только эти два района участвуют в обработке заявок с igov. по остальным пока обычным способом можно подать заявление. к сожалению
