### ISSUE TITLE
помилкаSYSTEM_ERR For input string: "один"

### ISSUE THREAD

**Issue by Kostyatsenko** [e-government-ua/iForum#25]
Заполнил форму на субсидию, при отправке выскакивает "помилкаSYSTEM_ERR For input string: "один". Как с этим бороться? Заказывал субсидию в Днепропетровске.

**Comment by dmitrijzabrudskij** [comment]
а куда вы вводите слово "один"?

**Comment by Kostyatsenko** [comment]
Я его никуда не ввожу.

**Comment by dmitrijzabrudskij** [comment]
ситуация стабильно повторяется?

**Comment by Kostyatsenko** [comment]
Сейчас попробую ещё раз отправить.

**Comment by Kostyatsenko** [comment]
Ошибочка, действительно вводил слово "один" в поле "кількість поверхів". Попробую цифрой.

**Comment by Kostyatsenko** [comment]
Сработало, спасибо.
