### ISSUE TITLE
Оформление субсидии на другого человека возможно?

### ISSUE THREAD

**Issue by sigomarina** [e-government-ua/iForum#250]
Здравствуйте, живу в Киеве, хотела бы оформить субсидию на свою старенькую маму, которая живет в Киевской области. Ей тяжело ходить, до СОБЕСа она не дойдет. Банковских карточек нет. Возможно ли как то залогиниться под её именем и оформить субсидию? Или залогиниться под своим именем и оформить на неё? Какой самый простой вариант? Подумываю вытащить ее в отделение банка и открыть на её имя карту, но ради регистрации в системе это слишком сложный путь.
Спасибо за ответы.

PS. Спасибо за сервис, работает прекрасно и очень мне помог! Вы большие молодцы!

**Comment by dmitrijzabrudskij** [comment]
добрый день
к сожалению, нет - пока такой возможности нет
планируем через какое-то время дать эту возможность сотрудникам соцзащиты - смогут от другого человека подать заявку

**Comment by sigomarina** [comment]
Спасибо за ответ. А какой в моем случае самый быстрый путь? Просто я заходила в систему с помощью Приватовской карты. Что такое ЕЦП и мобильная аутентификация не знаю, они мне не помогут? Проще и быстрее посетить отделение Приватбанка?
Еще раз спасибо!

**Comment by dmitrijzabrudskij** [comment]
эцп - это электронно-цифровая подпись (получить можно в налоговой или в том же ПриватБанке - но для этого нужно быть его клиентом)

мобильная аутентификация - это когда Вы будете авторизовываться через свой номер мобильного (для этого персональные данные должны быть у оператора - подходит для контрактных абонентов)

в Вашем случае самый простой способ - это стать клиентом банка

**Comment by sigomarina** [comment]
Спасибо большое, вы очень любезны!
