### ISSUE TITLE
Можно ли продублировать сообщение?

### ISSUE THREAD

**Issue by KARTSEN** [e-government-ua/iForum#251]
Подала заявление на загранпаспорт, но   были временные проблемы с электронной почтой, можно ли продублировать сообщение?  № 0-85990018, заявления было отправлено 21.01.16 на 18.02.16 на 14: 00.

**Comment by dmitrijzabrudskij** [comment]
в какое подразделение миграционной отправляли заявку?

**Comment by KARTSEN** [comment]
Никополь микитенська 5

**Comment by dmitrijzabrudskij** [comment]
отправил

**Comment by KARTSEN** [comment]
большое спасибо.

**Comment by VadymVolos** [comment]
Якщо питання вирішили, тоді я закриваю цю задачу.
