### ISSUE TITLE
Субсидия и депозиты 

### ISSUE THREAD

**Issue by Ulia0807** [e-government-ua/iForum#253]
Здравствуйте! Попробую сформулировать вопрос, может получу ответ. С осени получила подтверждение субсидии, пользуюсь ею. При оформлении заявки узнавала, что депозиты указывать не обязательно, так как согласно Порядку предоставления субсидий (Постановление КМ №848), субсидия назначается на основании среднемесячного совокупного дохода (причем, доходы от размещения депозитов в состав совокупного дохода не включаются). Теперь, оказывается, президент   подписал закон, который позволяет раскрывать банковскую тайну. То есть, теперь минфин будет проверять счета, с целью узнать скрываю я от него депозиты или нет. 
и  вот теперь собственно вопрос, получу ли я штраф за неуказание депозита ранее, или этот сезон  пройдет нормально, а в следующем нужно будет теперь указывать депозиты?

**Comment by dmitrijzabrudskij** [comment]
добрый день
пока никаких изменений в части раскрытия информации по доходам, полученным от размещения денег на депозитных счета, нет. поэтому о штрафе можете не беспокоиться. а вот какие источники доходов указывать на следующий сезон будет ясно позже - после соответствующего разъяснения от минсоцполитики
