### ISSUE TITLE
Судьба заявки на субсидию.

### ISSUE THREAD

**Issue by Roman12121212** [e-government-ua/iForum#254]
Добрый день. Подскажите пожалуйста - 17.01.16 подана заявка на получение субсидии. г. Новомосковск днепропетровской обл.
17.01 Ответ на почту. Заявка 0-81305144 подана.
Больше ни какой информации.
Подскажите судьбу данной заявки или где можно выяснить, что с ней происходит?
Спасибо.
Роман

**Comment by dmitrijzabrudskij** [comment]
добрый день
поищите в почте, пожалуйста, письмо, которое приходило после подачи заявки - какой район там указан?

я не нахожу Вашу заявку ни в г.Новомосковск, ни в новомосковском районе днепропетровской области

**Comment by Roman12121212** [comment]
Ваша заявка 81305144 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення.

**Comment by Roman12121212** [comment]
Шановний(-а) РОМАН БОРИСОВИЧ.

Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг зареєстроване. Ви отримаєте відповідь протягом 30 робочих днів.

Контакти підрозділу соцзахисту, яке буде займатися обробкою Вашого звернення:

УПСЗН м. Новомосковська
м.Новомосковськ, вул. Горького, 2а
Режим роботи з 8.00 до 17.00
Телефон для довідок: (0569) 31-49-72

З повагою,
УПСЗН м. Новомосковська
Команда Порталу державних послуг iGov

**Comment by Roman12121212** [comment]
В этот день пришло 4-е подтверждения 
81307852
81305144
81306942
81304245 
и несколько "Надання витягу з Єдиного державного реєстру МВС України"
причем я их не запрашивал...

**Comment by dmitrijzabrudskij** [comment]
этих тоже не нахожу
подайте еще раз, пожалуйста, и скиньте номер сюда - я проверю попала ли она в район

**Comment by Roman12121212** [comment]
Дозвонился в Новомосковск 
"УПСЗН м. Новомосковська
м.Новомосковськ, вул. Горького, 2а
Режим роботи з 8.00 до 17.00
Телефон для довідок: (0569) 31-49-72"
Такие заявки не поступали. Не по адресу не по ФИО заявок нет.
Говорят , что могли уйти на район.
А как это узнать ???

**Comment by dmitrijzabrudskij** [comment]
на районе тоже нет. подавайте новую

**Comment by Roman12121212** [comment]
Понял. Спасибо. Наверно отнесу в живую документы. месяц потерял....

**Comment by dmitrijzabrudskij** [comment]
не нужно вживую относить. подайте новую заявку сейчас. а район я попрошу обработать ее как поданную 17.01

**Comment by Roman12121212** [comment]
Спасибо. Вечером по новой оформлю.

**Comment by Roman12121212** [comment]
Добрый день . Дмитрий подал новую заявку.
"Шановний(-а) РОМАН БОРИСОВИЧ!
Ваше звернення №0-115998146 успішно зареєстровано,"
Попросите пожалуйста, на сколько это возможно, чтобы заявка пошла от 17.01.2016

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
