### ISSUE TITLE
Сергей

### ISSUE THREAD

**Issue by QAwsed77** [e-government-ua/iForum#255]
Добрый день. Подскажите пожалуйста - 18.01.16 подана заявка на получение субсидии. г. Днепропетровск, Шевченковский (Бубушкинский) район.
18.01 пришел ответ на почту:
"Ваша заявка 82401508 прийнята"
Больше ни какой информации.
Подскажите судьбу данной заявки. В статусе она так и висит: "Прийнята"
Спасибо.
Сергей.

**Comment by dmitrijzabrudskij** [comment]
добрый день
заявка в работе у района, ожидает ответа о назначени субсидии

статусы на портале и правда сейчас не очень информативны - мы работаем над этим, скоро будет намного понятнее:)

**Comment by QAwsed77** [comment]
Спасибо за быстрый ответ.
Как узнать срок ее выполнения? Месяц отведенный прошел....

**Comment by dmitrijzabrudskij** [comment]
можете позвонить в район и уточнить на каком этапе заявка и что ее задерживает (контакты высылались в имейле после подачи заявки)

зачастую срок больше месяца (уже указываем 30 рабочих дней в имейлах)

**Comment by GrekD** [comment]
субсидія погоджена
