### ISSUE TITLE
Ошибка при подаче заявки на субсидию ЖКХ

### ISSUE THREAD

**Issue by ValerijL** [e-government-ua/iForum#256]
Пытаюсь подать заявку на оформление субсидии в Ленинский район г. Днепропетровска, Вроде все поля заполнены, но в конце выдает ошибку: 
![1](https://cloud.githubusercontent.com/assets/15772103/13187760/f05795f4-d755-11e5-9daf-92b87370de9c.jpg)
![2](https://cloud.githubusercontent.com/assets/15772103/13187640/0471f8d2-d755-11e5-978c-cb6be2878bd4.jpg)
![3](https://cloud.githubusercontent.com/assets/15772103/13187642/047672fe-d755-11e5-9098-26ba799a1423.jpg)
![4](https://cloud.githubusercontent.com/assets/15772103/13187639/0471e50e-d755-11e5-94ad-7d9df5084ae9.jpg)

В этих иероглифах ничего непонятно, ни где ошибка, ни какая ошибка. Может что-то подскажите?

**Comment by AndreyPopovNew** [comment]
@ValerijL а вы не пробовали поле про покупки больше 50тыс. оставить просто пустым?

там же вроде хотят  ФИО лица делавшего покупки, а не слово "не має"

**Comment by dmitrijzabrudskij** [comment]
@ValerijL  проверьте выбран ли район в самом верху формы

@AndreyPopovNew сегодня уже обновленная версия достуна - там все поля нужно будет заполнить по покупкам свыше 50 000
