### ISSUE TITLE
Ошибка при регистрации через BankID

### ISSUE THREAD

**Issue by NVDeshka** [e-government-ua/iForum#257]
Возникает ошибка при попытке передачи данных с приват банка для регистрации в электронной очереди на получение загран. паспорта. Что подскажите делать?
помилка null
Так же при ввода кода подтверждения и нажатии кнопки подтведить ничего не происходит

**Comment by Koffeek** [comment]
@NVDeshka эта ошибка связана с окончанием свободных слотов. Добавим.

**Comment by NVDeshka** [comment]
@Koffeek спасибо. А когда?

**Comment by Koffeek** [comment]
@NVDeshka постараемся вечером. Я отпишусь здесь или могу Вам на почту

**Comment by NVDeshka** [comment]
@Koffeek хорошо, спасибо. Буду ждать
