### ISSUE TITLE
Приложение под андроид

### ISSUE THREAD

**Issue by ArtemBilous** [e-government-ua/iForum#258]
Было бы неплохо иметь/разработать приложение под андроид. 21 век на дворе))
Сейчас все движется в сторону мобильности. 

В приложение вставить какие-то очень не надоедающие рекламы для дополнительного финансирования проекта igov. Приятно, очень приятно, что у нас в стране наконец начались изменения в ИТ сфере, в сфере державних онлайн услуг. Молодцы, лёд тронулся)

**Comment by Koffeek** [comment]
@ArtemBilous Проект волонтерский и разработчиков мобильных приложений в команде на данный момент нет. Если хотите присоединиться - милости просим.
