### ISSUE TITLE
Фідбек, покращити авторизацію, додати короткий опис для тих хто перший раз

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#259]
Згідно цього звернення:
https://www.facebook.com/igov.org.ua/posts/1669333360022207

1. Люди які перший раз на порталі шукають там кнопку Реєстрація а її нема
2. Там в "Між журнал" треба пояснити:
.- чому ми авторизуємо через BankID
.- там є кнопка емейл, пояснити що буде якщо зареєструватися тільки через емейл (які послуги будуть доступны а які ні)

3. Коли я ще неавторизований обираю послугу наприклад "Видача/заміна паспорта громадянина для виїзду за кордон" наступній крок пропонується обрати область. Обираю область, а далі мені пропонують аторизуватися через BankID, а якщо мого міста немає серед активних, тоді нащо мені реєструватися і авторизуватися? Дати людині вибрати місто, і якщо в цьому місті доступна послуга, вже після цього просити авторизуватися.

4. Коли я ще неавторизований обираю послугу наприклад "Видача/заміна паспорта громадянина для виїзду за кордон" я обираю область, і далі для авторизацію пропонують тільки ЕЦП і BankID, а де емейл? Чому на вкладці "Між журнал" можна авторизуватися через емейл, а тут немає кнопки "емел"?

5. І стосовно цього звернення: 
https://www.facebook.com/igov.org.ua/posts/1669333360022207
Людина хоче замовити біометричний закордон паспорт в Дніпропетровській обл, але немає потрібного банку в списку. Якщо людина зареєструється через емейл вона зможе замовити? Чи для замовлення потрібно реєструватися тільки через BankID? І як людині побачити без авторизації в яких містах доступна послуга замовлення паспорту, щоб не реєструватися а потім виявиться що послуга не доступна.

**Comment by Koffeek** [comment]
@VadymVolos 
1. Людина може прочитати вкладку "Як працює" і тоді буде зрозуміло, що кнопки реєстрації не існує.
2. При виборі послуги після обирання міста (області) відображається перелік можливих способів авторизації. Якщо банку немає у переліку доступних та немає ЕЦП, то використання порталу наразі неможливе.
3. Стосовно закордонного паспорту то перелік міст, у яких можливе оформлення фіксований і залежить від наявності спецобладнання. Якщо населеного пункту нема, то обираємо найзручніший, бо в іншому місці не зроблять. При додаванні обладнання ми розширюємо перелік доступних міст.
4. Мій журнал це доступ до статусів заявки. Його дані не є критично важливими, тому верифікація може бути простішою. Верифікація на послугах значно більш сувора
5. Дивись попередні відповіді.

**Comment by VadymVolos** [comment]
@Koffeek дякую за відповіді.

2. По цьому пункту, я пропоную коли людина вибрала область, потім дати вибрати місто, а вже потім дати кнопки для авторизації. Тому що, людині слід побачити чи є його місто в списку, і якщо є тоді реєструватися.

**Comment by Koffeek** [comment]
@VadymVolos Ситуація в тому, що якщо послуга доступна для області, то відкриті зазвичай усі доступні міста (є невеличкі вийнятки).

**Comment by VadymVolos** [comment]
Ок, дякую за допомогу!

**Comment by VadymVolos** [comment]
@Koffeek підкажіть будь ласка ще одне запитання, людині потрібен біометричний закордон паспорт, він для всіх за замовченням вже йде біометричний чи ні? В нас на порталі можна замовити саме біометричний, чи в нас не має можливості це вибрати?

**Comment by Koffeek** [comment]
@VadymVolos Тип паспорту обирається при замовленні послуги.Від цього залежить сума для сплати.

**Comment by VadymVolos** [comment]
Ок, дякую ще раз!
