### ISSUE TITLE
Проблема при регістрації б.у. авто

### ISSUE THREAD

**Issue by vovolka** [e-government-ua/iForum#26]
Привіт, зайшов на портал за допомогою BANKID, далі вибираю реєстрація авто -> Київ -> Київ і Крок2 перейти. Після чого мене перенапрявляю сюда https://region.igov.org.ua/wf/ де знову просить логін і пароль. Підскажіть де отримати логін? Пробував повторно ввести дані із BANKID,- не пускає

**Comment by bvv4ik** [comment]
Добрый день, а дайте плиз ссылку на исходный профиль услуги, где начинаете авторизовываться по БанкИД?

**Comment by vovolka** [comment]
Де авторизуватись не знайшов взагалі, тому перейшов по ссилці https://igov.org.ua/journal/bankid і зайшов і тут залогінився. Далі вибираю реєстрація авто і т.д. ... і мене перекидує знову на форму ввода логіна/пароля.

**Comment by for-denis** [comment]
Та же самая ситуация, при этом если выбираю регион Днепропетровская область и город Днепропетровск - система пропускает меня дальше к заполнению полей связанных с перерегистрацией авто. Когда почините?

**Comment by VadymVolos** [comment]
@bvv4ik видео бага https://www.youtube.com/watch?v=EH2PlcojE9o

**Comment by for-denis** [comment]
Да, все так и происходит. А вот если выберете Днепропетровскую область и город Днепропетровск - то все получится.

**Comment by annastolbova** [comment]
Доброго дня, послуга була трансформована у 9 окремих послуг:

•	Перереєстрація транспортного засобу на нового власника за договором купівлі-продажу 
•	Зміна анкетних данних власника транспортного засобу 
•	Зняття транспортного засобу з обліку для реалізації 
•	Перереєстрація транспортного засобу на нового власника по успадкуванню 
•	Перереєстрація транспортного засобу при видачі дубліката свідоцтва 
•	Перереєстрація транспортного засобу при заміні номерного знаку 
•	Перереєстрація транспортного засобу при переобладнанні без зміни ном.агрегатів 
•	Реєстрація транспортного засобу привезеного з-за кордону 
•	Реєстрація транспортного засобу придбаного в торгівельній організації (нові транспортні засоби)

Всі вони доступні для замовлення.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
