### ISSUE TITLE
Не понятен статус заявки на субсидию ЖКХ

### ISSUE THREAD

**Issue by rav37** [e-government-ua/iForum#261]
На igov.org.ua оформил заявку на субсидию №79220091. Время 2016-01-14 13:01:31.998 
Статус Заявка закрита з відгуком -
На эл. почту никакой информации не приходило.
Хочу понять результат рассмотрения?

**Comment by dmitrijzabrudskij** [comment]
в какой район отправляли заявку?

**Comment by rav37** [comment]
В Ленинский

**Comment by dmitrijzabrudskij** [comment]
не нахожу такую заявку. а в имейле, который пришле после подачи, указан Ленинский район?

**Comment by rav37** [comment]
На эл. почту никакой информации не приходило.  После регистрации в разделе статус был ответ - Заявка виконана, а затем в статусе появилась информация - Заявка закрита з відгуком -

**Comment by elenakyshnirenko** [comment]
У меня было так же тоже Ленинский(((,скорее всего в субсидии отказано.Я подаю повторно

**Comment by rav37** [comment]
dmitrijzabrudskij. Я понимаю, что проект волонтерский, и особого желания разбираться нет, но хотелось бы понять дальнейшие действия при статусе заявки - Заявка закрита з відгуком.

**Comment by dmitrijzabrudskij** [comment]
заявки в принципе нет. подавайте повторно. и сбросьте номер - проверю чтобы точно попала в работу району

**Comment by rav37** [comment]
0-120410248

**Comment by dmitrijzabrudskij** [comment]
все в порядке. заявка попала в работу району

**Comment by mitrich2209** [comment]
"У черзі на обробку зареєстровано нове звернення
Опрацюйте це звернення на порталі" пришло по почте,не пойму что с этим делать и что с моей заявкой на субсидию, Лиходей Дмитрий Александрович,Днепропетровск ул.Набережная Победы д.50 кв.84?

**Comment by GrekD** [comment]
субсидія погоджена
