### ISSUE TITLE
Некорректный ответ на запрос в Полицию

### ISSUE THREAD

**Issue by kharshakh** [e-government-ua/iForum#262]
Вопрос по услуге Надання витягу з Єдиного державного реєстру МВС України
по одному ИНН показанна реальная ситуация, по другому - ТС не найденны, ХОТЯ на человеке висит ТС и снять его  срегистрации НЕВОЗМОЖНО по определённым причинам. Что делать?

**Comment by Koffeek** [comment]
@kharshakh Это связано с несовершенством в реестре МВС. Мы достаем оттуда данные и если они не внесены, то возвращаем ответ об отсутствии.

**Comment by kharshakh** [comment]
Т. Е. Все эти ответы это не есть достоверный источник. Может данных нет а в базе есть.

**Comment by Koffeek** [comment]
@kharshakh Наоборот. Те данные, которые есть в Єдиному державному реєстрі МВС України ми можем выгрузить и показать. Основное наполнение реестра ведется с 2012 года и то там бывают пробелы. У МВС есть разные способы хранения информации и хоть они и обещают перевести все данные в Единый реестр, скорость наполнения полностью зависит от них.

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 50 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
