### ISSUE TITLE
Лінгвістична підтримка -752 - Призначення соціальної допомоги при народженні дитини

### ISSUE THREAD

**Issue by igovok** [e-government-ua/iForum#266]
Прошу переглянути коментарі [за посиланням](https://docs.google.com/document/d/1ttqK85QKSr8eDcLXYQoMFbsZiO0ZaBoDgeoYgheBlRQ/edit)

**Comment by zolotovatatyana** [comment]
Коментарі враховані, дякую за допомогу.
