### ISSUE TITLE
Кадастровый номер

### ISSUE THREAD

**Issue by Yanko1960** [e-government-ua/iForum#268]
Можно ли на портале  iGov.оформить получение кадастрового номера на земельный участок.Если можно объясните для чайника пошагово .С Ув.

**Comment by AndreyPopovNew** [comment]
очень скудная информация от вас, что вам именно надо и для чего.

сделайте фильтр по кадастр

и увидите много услуг

 Внесення до Державного земельного кадастру відомостей (змін до них) про земельну ділянку


 Державна реєстрація земельної ділянки з видачею витягу з Державного земельного кадастру

 Надання відомостей з Державного земельного кадастру у формі викопіювань з кадастрової карти (плану) та іншої картографічної документації Державного земельного кадастру

 Надання відомостей з Державного земельного кадастру у формі витягу з Державного земельного кадастру про

**Comment by Yanko1960** [comment]
Добрый день.Мне это нужно как бы узаконить свое право на землю у меня есть старый акт 90годов но он сейчас не дает право совершать какие ни быть действия .А с чего начать не знаю.С Ув.

**Comment by AndreyPopovNew** [comment]
@Yanko1960 наверное вот с этого
 Внесення до Державного земельного кадастру відомостей (змін до них) про земельну ділянку
