### ISSUE TITLE
Электронная очередь

### ISSUE THREAD

**Issue by AlenaVolkova** [e-government-ua/iForum#269]
Здравствуйте! Зарегестрировалась в очередь на получение загранпасорта для ребенка. Регестрировалась в феврале, ближайшая дата была на конец апреля. То есть на ближайшие два месяца хочет получить паспорта такое огромное количество людей??? Хорошо, допустим. Тем не менее, в коридоре сидит живая очередь порядка 100 человек, которую принимают в случае, если по электронной никто не приходит. Но проблема  в том, чтт по электронной очереди практически никто и не приходит, является несколько человек за два рабочих часа (работает служба, к слову, по 2 часа). В итоге "живая" очередь сидит мертвым грузом, электронная не идет! Кто контролирует этот вопрос? Где проверяющие органы? Есть чувство, что очередь создается искуственно!!! Какой выход из этой ситуации? И как обычному человеку без взятки и знакомств подать документы? Ваши системы созданы для того, чтобы упростить процедуру оформления документов, но на деле они только упрощают работу тех, кто не хочет работать!

**Comment by Koffeek** [comment]
@AlenaVolkova По договоренности с ДМС для электронной очереди портала выделена полоса в 2-4 часа в день, в остальное время принимаются люди из живой очереди. В электронную очередь попадают заявки как на получение/продление загранпаспорта от взрослых, так и на получение загранпаспорта для ребёнка. Если на время в электронной человек не пришел, то должны принимать человека из жавой.  До февраля получить загранпаспорта в Днепропетровской области можно было только в 8 местах (4 из которых в Днепропетровске), этим и объясняется высокая загруженность по записи на портале. Сейчас по области доступно 25 точек, поэтому интенсивность записи должна упасть.
