### ISSUE TITLE
Держгеокадастр

### ISSUE THREAD

**Issue by OnixRewa** [e-government-ua/iForum#272]
Держгеокадастр в м. Дніпропетровськ приймає оплату, але не видає через Ваш портал витяги з ДЗК з підстави: документи не відповідають вимогам, встановленим законом, при цьому єдиний необхідний документ - заява, оформлена через цей портал.

Держгеокадастр в м. Дніпропетровську не видає витяги з нормативної грошової оцінки, формально мотивуючи відсутністю у них документів про права на землю з 01.01.2013. Реально замість безкоштовної видачі витягу установа вимагає 1600 грн. і додатковий договір на послуги.

**Comment by AndreyPopovNew** [comment]
@OnixRewa вы бы номера заявок указали, чтобы было предметно.

**Comment by OnixRewa** [comment]
ок 

02 березня 2016, 16:25:59, від "Andrey Popov" < notifications@github.com >: 

@OnixRewa вы бы номера заявок указали, чтобы было предметно. — 
Reply to this email directly or view it on GitHub . 

-- 
Євген Базюкевич 
Правові послуги 

Baziukevych Ievgen 
Legal Services 

+38 067-634-44-13 
amparo@ukr.net

**Comment by OnixRewa** [comment]
9900041662016 - на отримання витягу з ДЗК
9800023452016 - на отримання НГО

**Comment by AndreyPopovNew** [comment]
@OnixRewa это номера заявок именно iGov?

**Comment by OnixRewa** [comment]
Це номери заявок, вказані на сайті http://e-gov.dzk.gov.ua, куди перенаправляє iGov.

**Comment by AndreyPopovNew** [comment]
тогда думаю iGov  ничем не поможет (пока)

**Comment by OnixRewa** [comment]
шкода 

03 березня 2016, 19:47:33, від "Andrey Popov" < notifications@github.com >: 

тогда думаю iGov ничем не поможет (пока) — 
Reply to this email directly or view it on GitHub . 

-- 
Євген Базюкевич 
Правові послуги 

Baziukevych Ievgen 
Legal Services 

+38 067-634-44-13 
amparo@ukr.net
