### ISSUE TITLE
Изменить е-майл в заявке на субсидию

### ISSUE THREAD

**Issue by zvicf** [e-government-ua/iForum#273]
При подаче заявки некорректно указал е-майл. Возможно ли его исправить или необходимо подать заявку заново?

**Comment by dmitrijzabrudskij** [comment]
нужно новую заявку создать
сообщите номер и район старой, чтобі ее можно біло оперативно забраковать

**Comment by zvicf** [comment]
Спасибо за ответ. 
Заявку подал 2016-02-09 21:52:29.309 
Статус Заявка подана - Взяти в роботу
№0-105941385  Днепропетровская обл. Кривой Рог Жовтневый район

**Comment by dmitrijzabrudskij** [comment]
если такая давняя заявка - то не нужно новую, эта уже в работе. напишите плиз в эту ветку через неделю примерно - я проверю есть ли решение, и, если будет, перешлю Вам на исправленную почту

**Comment by zvicf** [comment]
Ок! Спасибо.

**Comment by zvicf** [comment]
Добрый день. Посмотрите, пожалуйста, состояние заявки №0-105941385 Днепропетровская обл. Кривой Рог Жовтневый район. В заявке указал неверно е-майл. Обратной связи нет. За полтора месяца статус на портале не изменился - Заявка подана - Взяти в роботу. Стоит ли дальше ждать, или по-старинке идти в собес? Спасибо.

**Comment by dmitrijzabrudskij** [comment]
субсидия назначена. вчера район обработал заявку - вам отправлен имейл с расчетом субсидии

**Comment by zvicf** [comment]
Спасибо. Статус поменялся.  -  016-03-23 16:09:10.621	Заявка закрита
Только в заявке, как писал ранее, неверній е-майл. Возможно ли продублировать имайл с расчетом на zvicf2012@gmail.com   .  Спасибо.

**Comment by dmitrijzabrudskij** [comment]
отправил решение со своего имейла

**Comment by zvicf** [comment]
Спасибо. Там какая-то путаница. Написал Вам на е-майл.

**Comment by dmitrijzabrudskij** [comment]
блин(
надеюсь, не до конца перепутали - завтра разберусь и напишу
