### ISSUE TITLE
Ошибка при создании электронной очереди для загран паспорта.

### ISSUE THREAD

**Issue by MariaDudnichenko** [e-government-ua/iForum#275]
При попытке зарегестрироваться на эл.очередь на сайте iGov на подачу документов для получения загран паспорта в Днепропетровской обл. город Никополь в ячейках "оберіть дату та час" не высвечивается ни жата ни время. Что делать?

**Comment by Koffeek** [comment]
@MariaDudnichenko Уже добавлено.

**Comment by MariaDudnichenko** [comment]
Спасибо !!!

**Comment by MariaDudnichenko** [comment]
А ещё вопрос, не знаете ли вы где можно в интернете найти реквизиты на оплату госпошлин для загранпаспорта?На сайте ДМС Украины нет.

**Comment by Koffeek** [comment]
@MariaDudnichenko Все реквизиты по Днепропетровской области доступны по ссылке: https://docs.google.com/spreadsheets/d/1CyjBNPJFgNxZrnb8ARAIrlja5WD2tif7mkzHEiwU-us/edit#gid=0

**Comment by MariaDudnichenko** [comment]
Большое вам спасибо!

**Comment by MariaDudnichenko** [comment]
Скажите пожалуйста ещё по поводу реквизитов, где вы их берете и с какого числа эти реквизиты действуют? Спасибо!

**Comment by Koffeek** [comment]
@MariaDudnichenko реквизиты дает ДМС Днепропетровской области, новые реквизиты по оплате за админуслуги действуют с 4,02.

**Comment by MariaDudnichenko** [comment]
А вы не знаете платёж за інформаційно -консультаційні послуги (85грн), там ничего не поменялось?

**Comment by Koffeek** [comment]
@MariaDudnichenko с таким платежом не сталкивались, т.к. он не входит в категорию обязательных.

**Comment by MariaDudnichenko** [comment]
Спасибо большое за информацию!
