### ISSUE TITLE
Оформление заявки - Призначення соціальної допомоги при народженні дитини

### ISSUE THREAD

**Issue by FusionManager** [e-government-ua/iForum#276]
Добрый день. Оформляли заявку на Призначення соціальної допомоги при народженні дитини. Оформление со второго раза прошло успешно. Документы готовили. Позвонили с нашего районного собеса, попросили еще одну справку донести из собеса другого района, что не получаю пособия там (по месту прописки). Пока сделали справку, уже документы на оформление передали на область. И все затихло. Через полторы недели авторизировались на сервере https://igov.org.ua, написали запрос о состоянии заявки. Сегодня пришло письмо такого характера:
iGov
портал державних послуг
Шановний(-а) ЮЛІЯ ВІКТОРІВНА.
На жаль, Ваше звернення щодо отримання соціальної допомоги при народженні дитини відхилене через недостатню або неправильну інформацію..
Причина:
Звертаємо увагу, Ви можете заповнити заявку повторно на порталі iGov.org.ua
З повагою,
УПСЗН Дзержинського району,  Ріг
Команда Порталу державних послуг iGov.

К кому вообще можно обратиться, чтобы узнать что неправильно заполнили или сделали? Или нужно идти опять выстаивать день в собесе?
Спасибо.

**Comment by dmitrijzabrudskij** [comment]
здравствуйте
подскажите фамилию и номер заявки, пожалуйста

**Comment by FusionManager** [comment]
Номер заявки 0-114743316

**Comment by dmitrijzabrudskij** [comment]
а фамилия?

**Comment by FusionManager** [comment]
Данилова Юлія Вікторівна

**Comment by dmitrijzabrudskij** [comment]
заявку забраковали, так как Вам нужно выбирать центрально-городской район Кривого Рога при подаче заявки. подайте новую заявку, пожалуйста

**Comment by FusionManager** [comment]
Дело в том, что так и делали. Первую заявку забраковали, потому что не тот район был выбран от 15.02.2016 номер 0-111899023. Нам позвонили и попросили создать новую заявку, и выбрать центрально-городской район Кривого Рога. А старую заблокируют. Так и сделали 17.02.2016 создали новую заявку номер 0-114743316 на центрально-городской район Кривого Рога. Вот теперь выясняем ситуацию.

**Comment by dmitrijzabrudskij** [comment]
ну теперь понятно чего не находилась заявка 114743316 - не тот район называли. позже напишу что с ней

**Comment by dmitrijzabrudskij** [comment]
помощь назначили. сегодня должны прислать на имейл решение. если завтра до 15.00 его не будет, отпишитесь сюда

**Comment by FusionManager** [comment]
Хорошо. Спасибо большое за оперативность!

**Comment by FusionManager** [comment]
Письмо пришло с решением. В письме указана Юлія Вікторівна (правильно) и написано "Рішення про надання допомоги вказане у файлі, який прикріплено до цього листа" , В в вложенном вордовском файле "Юлія Сергіївна. Это ничего страшного? Нигде ошибочно не потянет в базу данных?

**Comment by dmitrijzabrudskij** [comment]
а можете мне его переслать на dmitrij.zabrudskij@gmail.com ?

**Comment by FusionManager** [comment]
Переслал.

**Comment by dmitrijzabrudskij** [comment]
ничего страшного. человеческий фактор при написании доковского документа

**Comment by FusionManager** [comment]
**Ну тогда все в порядке. Спасибо за помощь! Приятно, когда есть качественная обратная связь.**
