### ISSUE TITLE
Оформление заявки - Призначення соціальної допомоги при народженні дитини

### ISSUE THREAD

**Issue by aleksmakarenko** [e-government-ua/iForum#277]
Добрый день. 
Оформляли заявку три раза (**0-97664121, 0-120263320, 0-129988939**). По всем трем приходят отказы. 
По первой пришло письмо с просьбой уточнить данные, и следом за ним о том, что заявка закрыта. Никакой возможности исправить заявку нет. На комментарий к заявке ответа нет.
По двум последним приходит сообщение, что не возможно открыть копию паспорта, хотя копию делал сотрудник банка стандартного разрешения (авторизовывались через BankID и Приват24). Прикрепить копии паспорта, сделанные собственноручно, нет возможности, так как отсутствует такое поле.
Огромный минус в том, что заявка сразу бракуется без возможности внесения правок и какого-либо внятного пояснения от сотрудника обрабатывающего заявку, что с ней не так.
Помогите с решением вопроса подачи заявки, так как сервис очень перспективный и позволяет сэкономить свое время.
Спасибо.

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой район выбирали при подаче?

**Comment by aleksmakarenko** [comment]
АНД р-н г. Днепропетровск

**Comment by dmitrijzabrudskij** [comment]
Саша, ответил в личку
