### ISSUE TITLE
Не работает заказ услуги по оформлению субсидии

### ISSUE THREAD

**Issue by NataliaPedan** [e-government-ua/iForum#278]
Заполняю все графы - но кнопка "ЗАМОВИТИ ПОСЛУГУ" не работает. Месяц назад все сработало, но я получила ответ - "Період, за який заповнюється деклація, з -по вкажіть 2015 рік(січень-грудень)" , хотя я и так изменила с по умолчанию стоящего 2014 года на 2015, потому как оформляла заявку в начале февраля 2016 года.

"

**Comment by dmitrijzabrudskij** [comment]
проверьте все поля заявки и повторите попытку. разделители везде должны быть точки

**Comment by NataliaPedan** [comment]
Проверила, поменяла запятые на точки и НИЧЕГО опять не произошло. Кнопка ЗАМОВИТИ ПОСЛУГУ как не работала, так и не работает. (Все графы заполнены)

**Comment by NataliaPedan** [comment]
Единственное, что меня смущает - все графы либо белые, либо желтые ( которые с автозапоминанием), а графы периода заполнения декларации - не изменили цвет ( серые), хотя я набирала дату из встроенного календаря...

**Comment by dmitrijzabrudskij** [comment]
с датами это нормально. пришлите скрины всей страницы подачи заявки - именно после того, как у Вас не сработает кнопка "замовити послугу"

**Comment by mitrich2209** [comment]
сегодня ровно месяц,как подал заявку - тишина полная!
