### ISSUE TITLE
Почати збирати фідбек від тих хто надає послуги

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#28]
Надійшла скарга що була велика черга, людина не дочекалася поки їй нададуть послугу і пішла. Тому логічно якщо є черга то оператор з надання послуги (офлайн) мабуть не встигає і по вуха в милі, а тут ще йому додали електронні послуги, це йому ще більше роботи.

І тому логічно запитати того хто по вуха в милі, що слід покращити, щоб йому було легше працювати. 

--
Ось скарга:
https://www.facebook.com/igov.org.ua/posts/1629611617327715

‎Ольчик Белогурова‎:
Сегодня пришла в городе Днепроетрвске в 14 45 было назначено,по улице Поля 1,пришла,а там огромная очередь в окнах,я ждала пока меня вызовут,затем мне посоветовали отдать паспорт свой в окно,и тогда меня вызовут,прождала 2 часа и ушла ,забрав свой паспорт, когда мне можно будет снова прийти? Я оплатила все уже,и куда именно ?в эи окна без очереди?или как?

Портал igov:
Напевно вам треба туди звернутися, якщо в них черга мабуть вони на встигають, і тільки вони зможуть підказати коли в них прийомний день щоб до них прийти.

Ольчик Белогурова:
Тоесть я без проблем смогу прийти,и мне начнут делать биометрический паспорт?если дата явки была другая

Портал igov:
Це ви можете дізнатися в них коли запитаєте. Теоретично якщо була черга і ви не встигли логічно що на наступний день прийти треба. але по факту невідомо що вони там придумають.

**Comment by dmitrijzabrudskij** [comment]
граждане, которые записались на замену паспорта через портал, обслуживаются вне очереди. ей нужно было подойти в свое время к окошку и ее бы обслужили

**Comment by VadymVolos** [comment]
"граждане, которые записались на замену паспорта через портал, обслуживаются вне очереди."
А данная инфа где-то у нас написана большими красными буквами?
Лично я не знал. И аналогично тот кто заказывает услугу, ему нужно это писать большими буквами чтоб он знал.

**Comment by dmitrijzabrudskij** [comment]
ему это пишется в имейле

**Comment by VadymVolos** [comment]
Ок, спасибо за инфу, уточню, как было дело.

**Comment by alex-xander-dp-ua** [comment]
"Граждане, которые записались на замену паспорта через портал IGOV, обслуживаются в указанное в заявке время. Подойдите к окошку и передайте свой паспорт!"

Реально ли такую табличку повесить во всех отделах ДМС?
Или сорвут с целью саботажа?

**Comment by alexkorich** [comment]
Сегодня такая же ситуация, тоже Поля, 1. Ждал 30 минут, спросил в окне, сказали что сегодня приема документов уже нет и я опоздал.

**Comment by VadymVolos** [comment]
@alexkorich детали напишите пожалуйста. 

- Город
- Адрес гос организации, этаж, кабинет
- Номер заявки
- Какую услугу заказывали
- ФИО того кто сказал  "Ну запишитесь еще раз, это где-то на апрель"

**Comment by dmitrijzabrudskij** [comment]
@alexkorich можете подсказать дату/время, когда это происходило, и номер заявки?

**Comment by alexkorich** [comment]
Днепропетровск, 
Поля 1, 3 этаж, 2 окно.
 41643888
Оформлення паспорту для виїзду за кордон з електронним носієм
ФИО к сожалению, не могу сказать.

Просто не могу понять: моя ошибка в том, что я ждал вызова и не пошел сразу в окно?

**Comment by alexkorich** [comment]
Время: записывался на 2016-02-25 10:00:00.00, пришел в 9:45, в ~10:30 спросил в окне почему меня не вызывают и как бы мне сдать документы на паспорт.

**Comment by dmitrijzabrudskij** [comment]
@alex-xander-dp-ua записывающихся с igov приглашают подойти к окошку в их назначенное время невзирая на живую очередь в подразделении. видимо, пропустили вызов или сами не подошли в Ваше время

предлагаю следующие варианты решеия:
1. подойдите в удобное время на Поля сегодня или на следующей неделе, подойдите к Ярош Ирине Викторовне и опишите вкратце ситуацию - Вас примут без очереди (она в курсе)
2. можете записаться в любой другой район миграционной службы, где есть удобное Вам время (благо, сейчас районов уже 19 - есть из чего выбрать)

**Comment by dmitrijzabrudskij** [comment]
@alexkorich записывающихся с igov приглашают подойти к окошку в их назначенное время невзирая на живую очередь в подразделении. видимо, пропустили вызов или сами не подошли в Ваше время

предлагаю следующие варианты решеия:
1. подойдите в удобное время на Поля сегодня или на следующей неделе, подойдите к Ярош Ирине Викторовне и опишите вкратце ситуацию - Вас примут без очереди (она в курсе)
2. можете записаться в любой другой район миграционной службы, где есть удобное Вам время (благо, сейчас районов уже 19 - есть из чего выбрать)

**Comment by alexkorich** [comment]
Спасибо, уже записался  записался в другое отделение.
