### ISSUE TITLE
Ваша заявка 0-122618754 прийнята! Надання довідки про відсутність або наявніть судимості

### ISSUE THREAD

**Issue by mobilsin** [e-government-ua/iForum#280]
Доброго дня!
Який термін обробки заявки?
Заявка була подана 25 лютого.
Дякую!

**Comment by Koffeek** [comment]
@mobilsin Доброго дня, термін виготовлення довідки про несудимість до 20 робочіх днів.

**Comment by mobilsin** [comment]
Дякую! Сьогодні вже забрав.
