### ISSUE TITLE
Оформление загранпаспорта

### ISSUE THREAD

**Issue by helenapavlyuk** [e-government-ua/iForum#281]
Я подала заявку на оформление загранпаспорт моей дочери, заявка  0-131275782. Но мне не пришло письмо с уточнением даты и времени, в которое нужно подать документы. Как мне это выяснить? т.к ранее при подаче заявок отправлялось письмо с указанием всей необходимой информации. 
правда реквизиты уже были старые на момент подачи документов и придется возвращать деньги через бухгалтерию(

**Comment by Koffeek** [comment]
@helenapavlyuk В какое подразделение подавали заявку?

**Comment by helenapavlyuk** [comment]
Дніпропетровськ (Шевченківський), пр. П.Орлика (пр. Ілліча), 3

**Comment by helenapavlyuk** [comment]
вроде бы на 25 марта, время после 14-00

**Comment by helenapavlyuk** [comment]
Павлюк-Штурмина Елена, дочь Павлюк Алина Сергеевна

**Comment by Koffeek** [comment]
@helenapavlyuk Почта указанная helena.pavlyuk@gmail.com? Правильно?

**Comment by helenapavlyuk** [comment]
да

**Comment by Koffeek** [comment]
@helenapavlyuk Отправил письмо ещё раз.

**Comment by helenapavlyuk** [comment]
спасибо!

**Comment by Klochkovad** [comment]
Подала сегодня заявку на оформление загнан паспорта. В связи с тем, что страница никак не реагировала на этапе обработки заполненных данных, подала две заявки в один центр ДМС с разницей во времени посещения в 15 минут. В разделе "Мой журнал" отображаются обе заявки с датой NaN.NaN.0NaN NaN:NaN. Пришло письмо с номером заявки 0-142700109. Вводя в разделе "Статусы" вижу название заявки: "Отримання субсидії на оплату житлово-комунальних послуг", статус "Заявка подана - Взяти в роботу".
Корректно ли в данной ситуации работает система? Можно ли удалить одну из записей в Моем журнале на 14:30 (первая на 14:15)?

**Comment by Koffeek** [comment]
@Klochkovad Вам на почту после подачи заявки должно прийти письмо с номером заявки, а также письмо с указанием дальнейших действий, в котором будет содержаться кнопка "Скасувати заявку". При нажатии на эту кнопку заявка будет отменена. По поводу работы раздела статусы вопрос будет передан программистам.

**Comment by Klochkovad** [comment]
письмо пришло только с номером заявки. больше никаких писем не было. проверила папку спам. сейчас в разделе "Статусы" статус заявки "Заявка закрита"

**Comment by Koffeek** [comment]
@Klochkovad уточните в какое подразделение ДМС и на какую дату подавалась заявка?

**Comment by Klochkovad** [comment]
@Koffeek Дніпропетровськ (Шевченківський), пр. П.Орлика (пр. Ілліча), 3 , 31.03.2016, 14:15, 14:30

**Comment by helenapavlyuk** [comment]
Мне уже пришло письмо, чтр записана на 24.03, 14.45.
Наверное это письмо адресовано не мне. О приеме 31.03.

**Comment by Koffeek** [comment]
@helenapavlyuk просто в нашу тему обсуждения добавился другой человек с похожим вопросом

**Comment by Koffeek** [comment]
@Klochkovad  Письмо отправил на klochkova.d@gmail.com, правда отменить заявку из письма Вы не сможете. Прохождение верификации по каждому сервису на портале - это гарантия того, что этим сервисом пользуется именно данный конкретный гражданин, а не кто-либо зашедший под оставленным логином

**Comment by Klochkovad** [comment]
@Koffeek прошло 15 минут, если верить данной странице, письма нет. спам проверила

**Comment by Koffeek** [comment]
@Klochkovad Приношу свои извинения. Сейчас проверьте.

**Comment by Klochkovad** [comment]
@Koffeek спасибо. письмо пришло, ссылки работают

**Comment by Katee-ua** [comment]
Добрый день. Записала мужа (Кармазь Артём Олегович) на получение загран паспорта на 28.03 на 14:45 в Шевченковский Гмс на пр Илича 3. Но письмо с реквизитами на оплату и вообще что либо, кроме самого первого (что заявка принята) не приходило! Почту указывали inste@icloud.com
Жду ответ!

**Comment by Koffeek** [comment]
@Katee-ua Отправил письмо ещё раз на указанный Вами адрес. Проверяйте.

**Comment by Katee-ua** [comment]
Есть! Спасибо!

**Comment by Klochkovad** [comment]
Подъехала в отделение Бабушкиного района на Иллича, 3, уточнить достовернорность кол-ва платежей, реквизиты и расписание работы кабинета. На нем написано: прием документов пн, вт, чт, пт 09:00-13:00; выдача пн, вт, чт 14:00-18:00, пт 14:00-16:45. 
Вопрос: в заявке я выбрала время подачи документов на 14:15, меня примут в это время или стоит выбрать другой день со временем в первой половине дня?

**Comment by Koffeek** [comment]
@Klochkovad Это расписание не распространяется на людей, которые подают заявки через iGov. Приезжайте Вас примут.

**Comment by LebedevD** [comment]
Добрый день!
Я 7 марта оформлял заявку на получение загранпаспорта для ребенка, но кроме письма с подтверждением о создании заявки никаких больше писем не получал. Заявка 0-128837126.
Если можно, пришлите, пожалуйста, письмо с датой и временем, на которое я зарегистрировался. Электронный адрес torg-alkar@ukr.net правильный.

Заранее благодарен.

**Comment by Koffeek** [comment]
@LebedevD в какой район подавали заявку?

**Comment by Klochkovad** [comment]
еще возник вопрос. в разных источниках в интернете упоминают уплату за сохранение старого паспорта. в ДМС на стендах не увидела такой информации, в письме от вас тоже не было указано. нужно платить им или тоже в банке? нужно ли делать копии загран паспорта в этой ситуации?

**Comment by Koffeek** [comment]
@Klochkovad если у паспорта закончился срок действия, то вы обязаны его сдать. Если вы получаете второй паспорт, то решение о возможности оставить первый принимает сотрудник ДМС исходя из обстоятельств (наличие действующих виз, подтверждение необходимости частых командировок и т.п.). Поэтому мы не отправляем платеж за сохранение загранпаспорта, чтобы не получилось, что человек оплатил, а паспорт сохранить не получилось.

**Comment by LebedevD** [comment]
Добрый день!

Заявка подавалась в Жовтневый район Днепропетровска, пл. Красная, 2а

**Comment by Koffeek** [comment]
@LebedevD отправил письмо на torg-alkar@ukr.net

**Comment by LebedevD** [comment]
Спасибо большое, письмо получил. :-)

**Comment by iymel** [comment]
Добрый день! Подали заявку на получение загранпаспорта  в г. Никополь, на 29.03.2016 г. на 15;45. В связи с отсутствием света,  прием граждан не осуществлялся. На данный момент заново  встать в эл. очередь в Никополе,не получается. На сайте IGOV не возможно выбрать день и время. Если я не там задаю свой вопрос, перенаправьте пожалуйста. Буду благодарна за ответ.

**Comment by Koffeek** [comment]
@iymel Добрый день. Т.е. при отсутствии приема по причине ДМС Вам не назначили новое время для подачи заявки, а сказали подавать ещё раз?

**Comment by iymel** [comment]
Да сказали  в порядке живой очереди, или заново регистрироваться.

**Comment by iymel** [comment]
Заявку подавали 7 февраля.

**Comment by iymel** [comment]
---------- Forwarded message ----------
From: no reply <noreply@igov.org.ua>
Date: 2016-02-07 19:30 GMT+02:00
Subject: Звернення на тему: Отримання паспорта громадянина України для виїзда за кордон
To: romuald948@gmail.com

**Comment by Koffeek** [comment]
@iymel Связались с ДМС. На следующей неделе постараются найти время чтобы принять тех, кто не смог подать заявку 29,03. Как будет точная информация, я Вам сообщу.

**Comment by iymel** [comment]
Спасибо.

**Comment by LebedevD** [comment]
Добрый день!

Подскажите, пожалуйста, если я зарегистрировался через портал iGov, но в связи с изменившимися обстоятельствами у меня отпала необходимость в оформлении загранпаспорта - как я могу отменить свою заявку?

Заранее благодарен за ответ.

**Comment by Koffeek** [comment]
@LebedevD именно Вы никак. Обычно в письме приходит кнопка "Скасувати заявку", но Вам я отправлял письмо лично, поэтому такой кнопки нет. Попрошу работников ДМС закрыть вручную.

**Comment by LebedevD** [comment]
Благодарю Вас.

**Comment by Anastasiya-P** [comment]
Добрый день! Как долго приходит письмо на почту после подачи заявки на замену загранпаспорта и паспорта на ребенка для выезда за границу? Спасибо.

**Comment by Koffeek** [comment]
@Anastasiya-P Письмо должно  приходить максимум в течение часа после заказа услуги. Если его не было, напишите сюда в какое подразделение подавали заявку и её номер. Тогда я смогу Вам отправить письмо ещё раз. Спасибо.

**Comment by Anastasiya-P** [comment]
Подавала в РОВД Шевченковского района (пр. Ильича 3)
было две заявки:
0-153268972 заявка на получение загранпаспорта ребенка
0-153267301 заявка на замену загранпаспорта
Спасибо за помощь.


04.04.2016 10:02, Koffeek <notifications@github.com>
>@Anastasiya-P Письмо должно  приходить максимум в течение часа после заказа услуги. Если его не было, напишите сюда в какое подразделение подавали заявку и её номер. Тогда я смогу Вам отправить письмо ещё раз. Спасибо.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/e-government-ua/iForum/issues/281#issuecomment-205165087

-- реклама -----------------------------------------------------------
16 апреля в Киеве! Бесплатный семинар по недвижимости в Турции
 от крупнейшего застройщика. http://bit.ly/1SLYWuo

**Comment by Koffeek** [comment]
@Anastasiya-P Отправил оба письма

**Comment by Anastasiya-P** [comment]
Благодарю.

**Comment by iymel** [comment]
Добрый день! На всякий случай напоминаю о ДМС г. Никополя, прием по заявлениям который не состоялся по вине ДМС. Получается ли нас принять на этой неделе?

**Comment by iymel** [comment]
По Никополю отсутствует возможность в электронной заявке нет выбора  даты и времени.
