### ISSUE TITLE
Надання витягу з Єдиного державного реєстру МВС України

### ISSUE THREAD

**Issue by step1953** [e-government-ua/iForum#282]
заявка 0-134580209 - На жаль, інформація про зареєстровані авто відсутня. Але фактично транспорт на підприємстві є. І так по всіх попередніх запитах, жодного разу не отримано інформацію про транспортний засіб (навіть власний).

**Comment by AndreyPopovNew** [comment]
уже писали много раз, что сейчас в основном в электронной версии авто зарегистрированные с 2012 года.
те что зарегистрированы раньше в базу не внесены и будут вноситься постепенно.

**Comment by step1953** [comment]
Авто, по которому был запрос, куплено и зарегистрировано юридическим лицом в 2015 году!!! Плюс для проверки специально пробовали новое транспортное средство, 2 месяца из салона со свежими номерами - результат "ноль"! 

15 марта 2016, 11:50:34, от "Andrey Popov" < notifications@github.com >: 

уже писали много раз, что сейчас в основном в электронной версии авто зарегистрированные с 2012 года. 
те что зарегистрированы раньше в базу не внесены и будут вноситься постепенно. —
