### ISSUE TITLE
Задержка выплаты пособия

### ISSUE THREAD

**Issue by EvaSergeevna92** [e-government-ua/iForum#284]
Здравствуйте!хотела бы узнать,по какой причине задерживают выплаты пособия на ребенка и декретные?

**Comment by AndreyPopovNew** [comment]
вам их уже назначили?

**Comment by EvaSergeevna92** [comment]
Да,в феврале была выплата на ребенка и все,а в этом месяце ни на ребенка,ни дикретных((хотела узнать,может вы подскажете чего они задерживают
--
Отправлено из Mail.Ru для Android среда, 16 марта 2016г., 09:21 +02:00 от Andrey Popov < notifications@github.com> :

**Comment by AndreyPopovNew** [comment]
тут вам могут подсказать только по назначению при подаче заявки через iGov

по задержке уде назначенных пособий - это к собесу и казначейству.

**Comment by EvaSergeevna92** [comment]
Спасибо за ответ!)
--
Отправлено из Mail.Ru для Android среда, 16 марта 2016г., 09:33 +02:00 от Andrey Popov < notifications@github.com> :
