### ISSUE TITLE
Витяг з Єдиного державного реєстру МВС

### ISSUE THREAD

**Issue by leshko86** [e-government-ua/iForum#285]
Як отримувати витяги з Єдиного державного реєстру МВС від імені юридичної особи (банк перевіряє заставу)? 
Варіант авторизації по BankID фізичної особи не підходить, оскільки розкриває особу співробітника банку, що є не дуже добре. Запит потрібно робити саме від юридичної особи.

В [Кабінеті електронних сервісів](https://kap.minjust.gov.ua/)  банк зареєстрований за кодом ЕДРПОУ як юридична особа, і в довідці з Державного реєстру речових прав на нерухоме майно вказується, що саме юридична особа виконала пошук, а не конкретна людина. Така сама можливість цікавить і для Єдиного державного реєстру МВС. Які є можливості саме для юридичної особи?

**Comment by GrekD** [comment]
@kurbpa підкажи, будь ласка

**Comment by kurbpa** [comment]
Авторизуйтесь  через ЭЦП.
Но в любом случае при подаче запроса  нужно будет указать  ФИО  автора запроса.

Хочу отметить, что услуга  в принципе то и запущена была  с ориентиром на  работу с физлицами.
