### ISSUE TITLE
Дали субсидию, но деньги на нее не перечисляют 5 месяцев

### ISSUE THREAD

**Issue by MikeBa** [e-government-ua/iForum#286]
В сентябре я оформлял субсидию для своей бабушки, Гладилина Екатерина Ефимовна, через сайт igov.org.ua.   12.09   пришло подтверждение о начислении субсидии.К подтверждению был прикреплен файл с фотографией документа и подписью на нем уполномоченной Ковалева  .  Спустя пять месяцев денег нет, при звонке в районную соц. службу не нашли в компьютере ответа о начислении.

**Comment by dmitrijzabrudskij** [comment]
какой это был район соцзащиты?

и перешлите само уведомление мне на имейл dmitrij.zabrudskij@gmail.com

**Comment by MikeBa** [comment]
уведомление переслал неделю назад от babakatya36@yahoo.com ! Мне ответ какой то ждать?
