### ISSUE TITLE
заявка на субсидию!

### ISSUE THREAD

**Issue by mitrich2209** [e-government-ua/iForum#287]
сегодня ровно месяц, как подал заявку - тишина полная!

**Comment by dmitrijzabrudskij** [comment]
дайте номер заявки и район, в который отправляли

**Comment by mitrich2209** [comment]
номер заявки найти не могу,заявка подана 17.02.2016,Жовтневый (Соборный район),Лиходей Дмитрий Александрович, Набережная Победы 50,кв.84

**Comment by dmitrijzabrudskij** [comment]
номер заявки 114684598
она в работе у района, по факту обработки пришлют имейл

**Comment by GrekD** [comment]
субсидія погоджена
