### ISSUE TITLE
Блокируется выбор области

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#289]
при выборе области предоставления услуг, если вдруг "промазал" при выборе области, то возможности изменить свой выбор НЕТ!!!!

![image](https://cloud.githubusercontent.com/assets/8410116/13888043/c9232bee-ed47-11e5-9322-3ceda5c05b80.png)

чтобы изменить область надо переходить на какой-то другой пункт меню.

**Comment by Koffeek** [comment]
@AndreyPopovNew Там стоит механизм, позволяющий подбрасывать значения, если Вы начинаете писать в поле название области. Если промахнулись необходимо просто стереть заполненное название и список будет доступен вновь.

**Comment by AndreyPopovNew** [comment]
@Koffeek а зачем писать? зачем стирать? вот просто хотел сделать промотку вниз, а не попал на стрелочку - выбрало не ту область.
почему снова нажав на выбор списка - этого списка нет? а надо полностью стирать название?

**Comment by Koffeek** [comment]
@AndreyPopovNew А зачем мне листать список? Я начинаю писать название своей области и мне предлагают варианты. Шанс выбрать неверное значение при этом минимальный.

**Comment by AndreyPopovNew** [comment]
@Koffeek ну тогда надо вообще убрать возможность открытия списка - зачем список нужен?

**Comment by Koffeek** [comment]
@AndreyPopovNew а в список подбрасываются наиболее близкие значения по мере того как человек вводит какие-либо символы.

**Comment by AndreyPopovNew** [comment]
@Koffeek это все замечательно. но почему при выбранной области список блокируется?

**Comment by Koffeek** [comment]
@AndreyPopovNew так список и выпадает весь, но с учетом того, что введено в поле. Поэтому если в поле уже введено название области, то в списке будет пустота, т.к. все возможные значения уже выбраны.

**Comment by AndreyPopovNew** [comment]
@Koffeek логика работы "на сегодня" понятна, но вот с мое мнение, что надо поправить.
