### ISSUE TITLE
Фильтр по региону

### ISSUE THREAD

**Issue by dmitry-seven** [e-government-ua/iForum#29]
Очень удобно было бы получать список возможных услуг онлайн указав свой регион(город). Возможно в моем городе уже доступны некоторые услуги,но узнать об этом нет возможности.  Спасибо.

**Comment by VadymVolos** [comment]
В вікні пошуку справа натисніть стрілочку, відкриється віконце і там можете вибрати своє місто.
Поки реалізовано так.

**Comment by dmitry-seven** [comment]
Дуже дякую. Так робе. З першого погляду не було помітно.
