### ISSUE TITLE
Как узнать, принята ли заявка в работу

### ISSUE THREAD

**Issue by nusichka82** [e-government-ua/iForum#290]
16.03.2016 я подала заявку на услугу получения загранпаспорта в Шевченковском районе г. Днепропетровска. Подтверждения о принятии заявки в работу на электронную почту не было по сей день, номер заявке не присвоен, ответа от ДМС также нет. Есть только информация в моём журнале следующего содержания: "16.03.2016 10:37 Ви подали заявку на послугу Отримання паспорта громадянина України для виїзда за кордон. Cтатус: обробка дмс". Как узнать принята заявка в работу или её необходимо подавать заново?

**Comment by Koffeek** [comment]
@nusichka82 По данной услуге обработка означает готовность службы Вас принять. Приходите в выбранный день, с тем пакетом документов и оплаченными квитанциями, которые пришли Вам в письме.

**Comment by nusichka82** [comment]
Но у меня нет никакого письма ни с пакетом документов, ни с квитанциями, вообще ничего подтверждающего принятие данной заявки нет.

**Comment by Koffeek** [comment]
@nusichka82 Письмо должно было прийти, хотя бы одно с номером заявки. Проверьте папку спам. Если нет письма, укажите на какую дату у время, хотели приходить?

**Comment by nusichka82** [comment]
В том то и проблема, что не было ничего.Я уже не первый раз пользуюсь Igov, поэтому знаю, что должно быть письмо, но в этот раз не было ничего. Записывалась на 24 марта на 14-45.

**Comment by Koffeek** [comment]
Отправил повторно письмо на nusichka82@gmail.com

**Comment by nusichka82** [comment]
Спасибо, получила
