### ISSUE TITLE
"Код доступу до документу" вопрос о защите персональных данных

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#292]
Клиент говорит что его документ в открытом доступе:

>Юлька Матушка: этот документ не привязан ко мне, не привязан к моему аккаунту и не имеет никаких защит. он в свободном доступе!

>Юлька Матушка: это не правильно. при получении справки из банка меня даже не предупредили о том, что она будет вывешена на совершенно левом сайте.

Пост в фб:
https://www.facebook.com/igov.org.ua/posts/1681638275458382?comment_id=1681697888785754&reply_comment_id=1681738798781663&comment_tracking=%7B%22tn%22%3A%22R%22%7D

UPD
Вообщем если в двух словах, клиент не зарегистрирован на портале iGov, и не хочет регистрироваться, и не хочет чтоб его данные были на портале. А когда он в Привате взял справку там на ней был код доступа к этому документу на портале iGov, и собственно вопрос почему без разрешения персональные данные человека разместили на портале.

**Comment by VadymVolos** [comment]
>Юлька Матушка: Я не хочу создавать аккаунт на вашем портале, т.е. не смогу подписать данную заявку. Речь идет о документах, которые можно получить здесь: Документы -- Поиск документов по коду -- тип документа Справки/Выписки (выбрать оператора и вписать номер справки). все эти документы в свободном, не авторизированном доступе. Номер своей справки отправила личным сообщением Вадиму Волос.

**Comment by VadymVolos** [comment]
До меня дошло что клиент хочет.

![11](https://cloud.githubusercontent.com/assets/12669290/13951183/f19eedc2-f037-11e5-9a9e-9055e6b969cb.jpg)

Клиент говорит, что номер уникальный для документа "Введіть код доступу до документу"
может кто то подглядеть и получить доступ к документу,

У меня вопрос:

1. Как там в настроках дополнительно включить защиту для доступа к документу по смс?
2. Если кто-то уже подглядел "код доступу до документу" документу в личном кабинете можно ли сгенерировать новый номер, и старый номер сделать чтоб стал не рабочим?

**Comment by VadymVolos** [comment]
И еще вопрос:

>Юлька Матушка:
но ведь данный документ ко мне не привязан
нет связи хозяин--подчиненный документ
ну... допустим, авторизировалась, документа не будет у меня в личном кабинете
он останется в общей свалке справок

>Вадим Волос
Этот вопрос я тоже спрошу.
А как вы смогли увидеть код этого документа если в личном кабинете он не привязан, он же отображается там, поэтому и код смогли посмотреть?
Юлька Матушка

>Юлька Матушка
пошла в отделение банка Приват... недалеко от дома. попросила справку. при мне ее распечатали и поставили печать.
пришла домой и внизу справки увидела надпись, что эл.вид справки можно посмотреть на вашем сайте.
у меня на руках живая справка, а что она попала на сайт--я была в шоке
нет у меня личного кабинета на вашем сайте.

>Вадим Волос
а на той справке этот код написан?

>Юлька Матушка
да, это ее номер
в эл.виде видно

>Вадим Волос
Понял, ок.

Из этой переписки  я понял что Юлия не зарегистрирована у нас на портале iGov.
Также я понял что на квитанции которую распечатали в Привате был код доступа к документу. И поэтому Юлия переживает, что этот код который распечатали на квитанции может подглядеть или сфотографировать кто-то еще, пока она будет держать квитанцию в руках. И также Юлия не зарегистрирована на iGov, и не хочет регистрироваться, и не хочет чтоб ее документы были в общей свалке с документами.

**Comment by AndreyPopovNew** [comment]
читаю и понимаю, что под "угрозой" анонсированный доступ к справкам из банка работников посольств при выдаче визы?

ведь проверка по номеру документа для этого сделана и для похожих целей.

и документ не в свободном доступе вроде, а **защищен** кодом, которым распоряжается получатель справки. т.е. без его разрешения (кода) никто к справке доступ не получит.

а на счет сфотографировать код: ну так пин-код к карте тоже можно сфотографировать.

**Comment by VadymVolos** [comment]
По поводу фотографирования Дмитрий правильно написал, на портале расположена копия справки, и если сфотографируют справку на которой написан код доступа, то код доступа не нужен справка уже будет сфотографирована.

**Comment by AndreyPopovNew** [comment]
@VadymVolos ну так это относится к любой инфе. номер кредитной карты и ее данные. пин-код карты
номер паспорта, ИНН

все можно подсмотреть и сфотографировать.


основное что:
а) документ лежит в **закрытом** доступе
б) _доступ к_ нему может дать только владелец справки

**Comment by VadymVolos** [comment]
А по поводу вопроса о защите персональных данных?

>не забываем о защите персональных данных, о письменном соглашении на обработку персональных данных и запрет передачи персональных данных третьим особам (в данном случае на ваш сайт)

**Comment by dJulia55** [comment]
> AndreyPopovNew commented an hour ago
>основное что:
>а) документ лежит в закрытом доступе
>б) доступ к нему может дать только владелец справки

Еще раз повторюсь: 
1) документ был создан работником ПриватБанка и без моего ведома размещен на сайте В ОТКРЫТОМ ДОСТУПЕ, в общей свалке ОТКРЫТЫХ документов;
2) этот документ НЕ привязан к какому-либо аккаунту/владельцу и нет возможности изменения доступа к нему;
3) если б это была просто справка о счетах в банке -- пустое, помимо информации о счетах в шапке справки указаны ПЕРСОНАЛЬНЫЕ ДАННЫЕ: идентификационный код, паспортные данные, прописка (глядим п.1)  В ОТКРЫТОМ ДОСТУПЕ.

Есть два решения данной проблемы: 
- эти документы банка должны отправляться владельцу при запросе из личного кабинета;
или
- банк должен изменить шаблон своей справки так, что бы не светить персональные данные.

я доступно поясняю?

**Comment by AndreyPopovNew** [comment]
@dJulia55 давайте тогда подробнее про открытый доступ?

т.е. вы вот мне сейчас дадите ссылку и я без проблем открою вашу справку?

или все же система с начала попросит меня авторизоваться, а потом еще спросит код доступа к документу?

**Comment by VadymVolos** [comment]
Андрей там без авторизации можно смотреть, но ключ доступа для просмотра да попросит. 

Да идея хорошая, сделать чтоб гос органы были авторизированы, и только тогда смогли ввести ключ доступа и получить доступ к документу. И сделать чтоб записывалась история, какой гос орган, фамилия, должность оператора, время, и для какой цели.

**Comment by AndreyPopovNew** [comment]
@VadymVolos история доступа к документу обязательна в любом случае.

а нужна ли авторизация при запросе?

к примеру сотрудник визового отдела ДРУГОГО государства скажет: а какого лешего я там буду авторизиовываться, а ну-ка принисите мне заверенную нотирально справку. и будет прав - он не обязан там авторизовываться. а просто зайти и ввести код про проверки идентичности справки - это другое дело.

**Comment by VadymVolos** [comment]
Вот видите я не знал, за другие государства. Из ваших ответов я попробую потом сделать инструкцию, чтоб люди у которых подобный вопросы могли узнать ответы на эти вопросы. Если вы  поможете сделать инструкцию по данной проблеме будет хорошо. Сэкономим время и людям которые спрашивают и себе.

**Comment by AndreyPopovNew** [comment]
@VadymVolos и еще нюанс - документ НЕ размещен на iGov - документ лежит на сайте Приватбанка. просто портал iGov через API  может получить доступ к документу, но опять же доступ дается на основании кода!

**Comment by dJulia55** [comment]
> AndreyPopovNew commented 9 minutes ago
>
>а нужна ли авторизация при запросе?
>
>к примеру сотрудник визового отдела ДРУГОГО государства скажет: а какого лешего я там буду авторизовываться, а ну-ка принесите мне заверенную нотариально справку. и будет прав - он не обязан там авторизовываться. а просто зайти и ввести код про проверки идентичности справки - это другое дело - "на это он может пойтить"
>

1) авторизация при запросе НЕ нужна, просто вводится регистрационный номер выданной справки (в моём случае это живая, бумажная справка)
2) давайте разберемся, сотрудник визового отдела в качестве кого собирается проверять документ? если в качестве просто Васи Пупкина с улицы -- да, он не должен авторизироваться с цифровой подписью и не должен видеть моих документов. Если он представляет официальное лицо огранизации, выполняющее свои прямые обязанности -- он просто обязан авторизироваться.  Что значит "не хочу"? Обязан!

Что касается окна авторизации ПриватБанка, там есть защита--привязка к личному мобильному телефону владельца, без подтверждения кодом из СМС в приват24 не зайти.

**Comment by AndreyPopovNew** [comment]
@dJulia55 официальное лицо организации другого государства действует на основании законов **своего **государства и лично вам (гражданину другого государства) НИЧЕГО не обязан делать.

территория посольств считается территорией соответствующего государства и там действуют Законы именно этого государства.

**Comment by VadymVolos** [comment]
Андрей у меня такой вопрос.

А мы можем сделать чтоб по умолчанию доступ к документам через портал был отключен?

И только тогда когда человеку нужно дать кому-то доступ, он регистрируется на портале, и в списке своих документов ставит галочки к каким документам разрешить доступ через портал с помощью кодом доступа.

**Comment by AndreyPopovNew** [comment]
@VadymVolos опять возвращаемся к тому, что работник визового отдела другого государства должен быть зарегистрирован на портале, чтобы ему дали доступ?

**Comment by VadymVolos** [comment]
Не, не нужно. Просто если человек хочет дать доступ по коду он в личном кабинете включает доступ. И работнику достаточно только ввести код.

**Comment by AndreyPopovNew** [comment]
@VadymVolos тогда вопрос - **когда** это будет делать этот человек

с моей точки зрения процесс должен выглядеть так:
- по умолчанию доступ есть по коду
- предусмотреть, чтобы по окончанию **срока нужности справки** пользователь мог зайти и отменить доступ к справке

 или скажем предусмотреть "окно" из дат когда есть доступ - с момента выдачи справки и на две недели.

открыть снова доступ пользователь может задав новое окно.

**Comment by dJulia55** [comment]
давайте рассмотрим и мою позицию.
я сижу в своей стране, никуда не собираюсь, мне вообще наплевать на представителей других государств.
почему МОИ документы с МОИМИ ЛИЧНЫМИ данными должны светиться на вашем сайте?

**Comment by AndreyPopovNew** [comment]
@dJulia55 они НЕ светятся ни на каком сайте.

даже на сайте Приватбанка.

без кода доступа, которым владеете вы - никто этот документ увидеть не может.

**Comment by VadymVolos** [comment]
Как я понял, справка делается для предоставления в какой-то нужный вам орган. Все органы с бумажными документами не работают, а уже работают с электронными документами. Поэтому органу чтоб поработать с вашей справкой нужно получить электронную копию вашей справки. И вот этот орган с помощью кода получает доступ.

@AndreyPopovNew  Возможно нужно сделать возможность получать доступ к справке только разрешенному органу? И отдельно сделать правила для справок к которым нужен доступ других органов из других стран?

**Comment by AndreyPopovNew** [comment]
@VadymVolos а у нас есть Закон или решение, которое **обязывает **чиновника регистрироваться на сайте iGov?
или это все же "добрая воля"?

**Comment by dJulia55** [comment]
прямая ссылка на скачивание ЕСТЬ, но считаю достаточным уже то, что Вадим видел мой документ с моими данными.

**Comment by VadymVolos** [comment]
Не, я не смотрел я удалил код. Я думал вы номер заявки дадите, чтоб по номеру найти проблему. А оказывается вы не зарегистрированы, и вместо номера заявки код доступа прислали. Код доступа ни к чему он персональный, поэтому я не смотрел, удалил его.

**Comment by dJulia55** [comment]
AndreyPopovNew , а у нас есть Закон или решение, которое *обязывает автоматом, без предупреждения клиента давать доступ к личным данным с сайта iGov?
или это все же "добрая воля"?

**Comment by AndreyPopovNew** [comment]
@dJulia55 и в этой ссылке не участвует код документа?

т.е. можно вот таким запросом igov.org.ua/getfile.php?=567895 получить файл?

**Comment by AndreyPopovNew** [comment]
@dJulia55 кто и где дает доступ? без вашего кода доступ **НЕВОЗМОЖЕН**. а код знаете вы и кому вы даете код - тому и разрешаете.

**Comment by dJulia55** [comment]
код внутри ссылки, но прямая ссылка существует, ее можно скопировать, разместить, передать

**Comment by dJulia55** [comment]
код справки СТАТИЧЕСКИЙ, подлежит логике, алгоритму формирования.
любой статический, логически-закономерный код можно подобрать, взломать и т.д.
мне ли вас, технарей, учить защите информации?

**Comment by VadymVolos** [comment]
>@VadymVolos а у нас есть Закон или решение, которое *обязывает *чиновника регистрироваться на сайте iGov? или это все же "добрая воля"?
Думаю нет. Но в данном случае нам важнее отношение с клиентом, а чиновники это всего лишь обслуживающий персонал. Поэтому в первую очередь нужно фокусироватся на уровне счастья клиента.

**Comment by AndreyPopovNew** [comment]
@dJulia55 все можно скопировать и передать. ну и что, что статический.
любой код и пароль можно подобрать ЛЮБОЙ!

так что вы предлагаете?

все ваше предложение сводится к тому - что все электронные документы надо ЗАПРЕТИТЬ, а то вдруг кто-то сломает код?

**Comment by VadymVolos** [comment]
Андрей я думаю, как вариант нам нужно сделать как делает Гугл, он дает соглашение пользователю принять, если хотите пользоваться читайте и принимайте. если не хотите принимать, справку мы вам не дадим.

Возможно есть лучше варианты, но если клиент не хочет чтоб данные были доступны по коду, то нужно предусмотреть удалить их, чтоб клиент был спокоен.

**Comment by AndreyPopovNew** [comment]
@VadymVolos ну так это вопрос к банку! он должен спрашивать давать доступ к справке через Интернет или нет. и в зависимости от ответа клиента генерировать или НЕ генерировать код.

**Comment by dJulia55** [comment]
Предложение сводится к тому, что "доступ к электронным документам должен быть С СОГЛАСИЯ лица, на кого выдан документ"

**Comment by VadymVolos** [comment]
Ну вот, нашли ответственного. Это уже хорошо. Значит тогда нужно к банку претензии предъявить почему вы дали доступ без разрешения.

**Comment by dJulia55** [comment]
> Значит тогда нужно к банку претензии предъявить почему вы дали доступ без разрешения.

уже работаю в данном направлении.

**Comment by AndreyPopovNew** [comment]
@VadymVolos опять же банка никому доступ не давал. доступ закрыт кодом.

вопрос должен стоять по другому - предоставлять доступ к электронной версии документа через Интернет

и если клиент согласен:
- генерировать код и печатать его на документе и делать доступ к копии по коду

если клиент **не** согласен:
- то не генерировать код

**Comment by VadymVolos** [comment]
@AndreyPopovNew ну вот, это простое и правильное решение.
Я так понимаю это ответственность банка, запросить согласие перед тем как генерировать код на справке?

**Comment by AndreyPopovNew** [comment]
однозначно

**Comment by VadymVolos** [comment]
@AndreyPopovNew спасибо за помощь! Надо было нам сразу с ответственного начинать, сэкономили б себе время. Тогда я эту тему закрываю?

**Comment by dJulia55** [comment]
В моём конкретном случае...
можно ли закрыть доступ к моей справке с вашего сайта? что б не искалась вообще.

**Comment by VadymVolos** [comment]
Как я понял, если справка лежит на сайте банка, то доступ по коду к ней открыт там. Поэтому чтоб закрыть доступ это нужно говорить с оператором банка. Возможно там в личном кабинете есть такая функция, но это могут подсказать они.

**Comment by AndreyPopovNew** [comment]
@dJulia55 без кода ваша справка не найдется.

пишите заявление в банк, чтобы они убрали доступ по коду.

**Comment by AndreyPopovNew** [comment]
@dJulia55 

![privat24_dovidka_code](https://cloud.githubusercontent.com/assets/8410116/13983575/321e53bc-f0f9-11e5-8701-e43de4b1c307.jpg)

вы видите здесь логику формирования кода?
16 символов - 26 букв и 10 цифр

удачи вам в подборе ;)

хотя предусмотреть опцию для отказа доступа через Интернет думаю желательно.

интересно, а если заказывать печатную справку - то как там с кодом?

**Comment by dJulia55** [comment]
если вам интересно...
пообщалась с приватом.
все, что формируется в справках-выписках АВТОМАТОМ формирует о такой код и к документу открывается доступ. этот доступ закрыть нельзя. документы из архива справок удалить нельзя.
можно удалить аккаунт приват24, обещали, что удалятся и эти документы.

я брала справку бумажную, но формируют бумажные справки опять же через свою приватовскую систему, никто на компе ее набирать ручками не собирается.

**Comment by VadymVolos** [comment]
Ок, спасибо Юлия! 
Будем знать...

**Comment by dJulia55** [comment]
> AndreyPopovNew 
privat24_dovidka_code
>вы видите здесь логику формирования кода?
>16 символов - 26 букв и 10 цифр
>
>удачи вам в подборе ;)

"Информация для заполнения декларации"
недастающие символы "M" и "8"

Андрей Евгеньевич, вы все там же, на Минина обитаете?
а зачем вам аж... аж... 86 счетов ??? О_о
частный предприниматель? игрок на процентах?

**Comment by dmitrijzabrudskij** [comment]
6 дней ушло чтобы комбинацию из двух символов подобрать? сколько уйдет на 16?

**Comment by VadymVolos** [comment]
У меня вопрос. 

Там возле окошка для ввода кода доступа, есть ссылка "Докладніше про розділ Документи на порталі iGov" https://docs.google.com/presentation/d/17SPm-nD1awYllMNiuv3gQnckOC0VegHj7-SbLtjTOZs/
В инструкции на последнем слайде написано что пользователь может дополнительно включить защиту по смс.

Как включить защиту по смс? И если документы лежат не на портале а на серверах банка, то и защита по смс должна включатся в кабинете банка?

Тогда нам в инструкцию нужно добавить как пользоваться защитой по смс, и где она включается? И что сделать чтоб защита автоматом была включена, чтоб не тратить время на каждый документ, не заходить на сайт чтоб включить к нему защиту.

**Comment by dJulia55** [comment]
>dmitrijzabrudskij 
>6 дней ушло чтобы комбинацию из двух символов подобрать? сколько уйдет на 16?
2 символа из 16 - 1296 комбинаций.
если задаться целью, при желании... 1296 комбинаций кодов ... можно получить с сайта за 6--8 часов.
что б опросить все комбинации 16-разрядных символов, да, уйдет больше времени....(всего лишь вопрос времени),  но это уже будет вопрос не в поиске отдельного документа а слитии базы данных клиентов банка

**Comment by AndreyPopovNew** [comment]
@dJulia55 2 из 36!!!! вы подбирали 2 из 36 возможных! т.е. n из m , если меня не подводит память, то это m!/(n!*(m-n)!) (не подвела)

итого 2 из 36 36!/ (2! * 34!) -> (35*36)/2 = 630

это всего 630 комбинаций

а вот 16 из 36 это

36!/(16! 20!) = 7.3 миллиарда комбинаций (7307872110)

вот интересно, при вводе скольких неправильных кодов доступ к  документу блокируется на время?

**Comment by AndreyPopovNew** [comment]
@dJulia55 на ваши вопросы отвечаю
живу уже не на Минина, а на Шнеерсона ;)
устраиваю "стресс-тест" ;)
а обязательно быть частным предпринимателем? и что в вашем понимании игрок на процентах?

**Comment by AndreyPopovNew** [comment]
защита от ввода нескольких подряд неправильных кодов должна мониториться банком.

и после введенных подряд неправильных кодов 3 и 5 кодов, доступ с этго ИП должен блокироваться на 15 или 30 мин.

**Comment by dmitrijzabrudskij** [comment]
все так и есть - доступ за спам блокируется
доступ к самому документу - нет (то есть блокировка на уровне самого портала)
кроме того, на портале нигде не отдается ответ о том, найдена справка или нет - всегда в ответе pdf-файл (в случае отсутствия справки там информация об этом)

поэтому вариант с перебором - из области фантастики

не говоря о том, что в случае даже "попадания" в существующую справку, толку от нее все равно не будет -  она ведь на случайного человека и случайной формы

**Comment by dJulia55** [comment]
> AndreyPopovNew 
> ...если меня не подводит память, то это m!/(n!*(m-n)!) (не подвела)

память Вас подвела:
16 разрядный код у которого меняются два символа в диапазоне 0--9, a--z (36 символов)
36*36=1296 комбинаций
можете проверить простым перебором символов в том же экселе.

>вот интересно, при вводе скольких неправильных кодов доступ к документу блокируется на время?
>или через iGov он не блокируется вовсе?

1) доступ не блокируется вовсе;
2) запрос с другим кодом документа воспринимается, как совершенно новый запрос;
3) любой (истинный или ложный, все-равно) запрос отрабатывается формированием *.pdf файла.

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij реально же вот проверили, что доступ за неверно введенные коды НЕ блокируется!

толка от получения справки - это реальное сливание базы данных банка.
ее не надо воровать, к ней можно получить доступ методом подбора!
