### ISSUE TITLE
Декларация о доходах.

### ISSUE THREAD

**Issue by Ulia0807** [e-government-ua/iForum#293]
День добрый! Вопрос такой - при заполнении декларации о доходах за 2015 год обязательно ли указывать депозиты в банках. На что можно сослаться, отказываясь указывать депозиты? Что "грозит" за неуказание сумм на банковских счетах?.

**Comment by dmitrijzabrudskij** [comment]
неназначение (или отмену ранее назначенной) субсидии
с ваших депозитов банком платятся налоги, которые соцзащита увидит запросив в налоговой информацию

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij но у налоговой НЕТ информации по депозитам. банки пока не обязывают давать развернутый отчет по налогам с депозитов.

**Comment by dmitrijzabrudskij** [comment]
@AndreyPopovNew сорри, я ошибся. спасибо, что подсказали

**Comment by dJulia55** [comment]
Что касается налогов с депозитов:
точно знаю, что ПриватБанк подает суммы начисленного дохода и удержанных с них ПДФО (податок з доходів фізичних осіб) в налоговую.
эти суммы светятся в базе и привязаны к идентификационному коду получателя дохода.
социальные службы, делая запрос в налоговую, получают суммы, содержащию информацию банка.

**Comment by AndreyPopovNew** [comment]
@dJulia55 у вас есть этому подтверждение?

у вас есть справка о доходах из налогвой?

у меня есть! и там таких данных нет.

на сколько я зная Закон о банковской тайне вступил в силу с 01.01.2016 года и то непонятно обязывает ли это давать банки сразу развернутые данные или только по запросу.

опять же - субсидия назначается на основе данных за **предыдущий **год. а за 2015 никто никому уже никаких данных не даст.

**Comment by dJulia55** [comment]
меня ЕСТЬ справка о доходах из налоговой, и там светятся аж 40 грн 36 копеек дохода от ПриватБанка (пользование в течении года кредиткой, копилкой, бонус-плюсом)

**Comment by AndreyPopovNew** [comment]
@dJulia55 там может светиться к примеру когда у Приватбанка была акция "Счастливый код" - когда выигрыш облагался доходом и шел отдельной статьей.

доходы по копилке и депозитам, кредитке  там не светятся.

скажу вам даже больше - в моей справке НЕТ данных о пенсии, которую я получаю по инвалидности.
только зарплата.

**Comment by Ulia0807** [comment]
Пенсию налоговая и не покажет, они показывают только зарплату, а информацию о пенсии, процентах нужно брать в соответствующих службах.

**Comment by AndreyPopovNew** [comment]
@Ulia0807 в каких соответствующих?

мы ведь не о том, где брать, а о том где органы соц.защиты ее получают.
