### ISSUE TITLE
Нет ответа по заявке на субсидию 0-107304424

### ISSUE THREAD

**Issue by ajmakeev** [e-government-ua/iForum#294]
Добрый день!
Как узнать решение о начислении субсидии, так как на указанный мною адрес электронной почты письмо о решении не поступило?
2016-03-12 11:41:33.439	Заявка закрита -

**Comment by dmitrijzabrudskij** [comment]
здравствуйте
дайте номер заявки и район, куда ее отправляли

**Comment by ajmakeev** [comment]
номер завки 0-107304424
Бабушкинский район

**Comment by dmitrijzabrudskij** [comment]
на почту 29081960@i.ua 12.03.2016 отправлено решение по вашей заявке

проверьте спам на всякий случай - могло туда попасть письмо. если все равно не получили, отпишитесь - вышлю еще раз

**Comment by ajmakeev** [comment]
письма нет. Отправьте пожалуйста еще раз

**Comment by dmitrijzabrudskij** [comment]
сбросил со своего имейла

**Comment by ajmakeev** [comment]
письмо получено, спасибо
