### ISSUE TITLE
Приватизация

### ISSUE THREAD

**Issue by Inna-T** [e-government-ua/iForum#295]
Днепропетровск. На прошлой неделе решила по приватизации позвонить, заявка от 26.01.2016, они уже в курсе что такое айгов (месяц назад ещё не знали когда я звонила интересовалась судьбой документов), ничего они не знают, записали мое ФИО и телефон, обещали позвонить. Никто не звонил.
Сегодня звоню на тел указанный в письме в очередной раз-----
Ваше звернення щодо передачи у власність земельної ділянки було зареєстровано у системі.
Повідомлення про результат звернення буде спрямоване на Ваш e-mail.

Телефон для довідок: (056) 744-63-51-------
девушка Маргарита по указанному телефону пообещала на прошлой неделе узнать кто принял документы. Сегодня говорит что ей так и не удалось узнать у кого стоит программа и кто занимается регистрацией доков, которые пришли через айгов. Посоветовала обратиться в канцелярию 744-50-30. Там конечно же ничего не знают, во входящих моих документов нет. Дали телефон 744-01-13 Лариса Алексеевна, мол, возможно она может подсказать куда идут документы с айгов. Она НИЧЕГО вообще не знает, начала спрашивать на кого я письмо писала на Филатова и куда я его отдала. В общем, глухо как в танке.
я уже даже не знаю куда позвонить)

нашла кучу тел. Управления корпоративных прав, которые должны заниматься земельными вопросами. В приемной 744-63-51 ничего подсказать не могут, сказали звоните нач управления Широкову 744-75-68, там трубку не берут, по остальным телефонам сотрудников этого управления, тоже трубки не берут. 

В "моем журнале" на сайте эта заявка не отображается. 

услуга:Передача у власність земельної ділянки, що перебуває у законному користуванні громадянина Міська рада Дніпропетровськ
![1](https://cloud.githubusercontent.com/assets/18117218/14079221/bf9ea944-f504-11e5-8b01-9db32456b4ac.png)

**Comment by annastolbova** [comment]
Відповідь надана усно.
Якщо будуть ще питання по цій темі, прохання відкрити це issue через команду reopen.

Гарного дня.
