### ISSUE TITLE
Видача довідки про наявність у Державному земельному кадастрі  0-128110399

### ISSUE THREAD

**Issue by Inna-T** [e-government-ua/iForum#296]
Разыскивается заявка 0-128110399  Обзвонила сегодня с десяток телефонов, никто ничего не ведает.....
Назва: Видача довідки про наявність у Державному земельному кадастрі відомостей про одержання у власність земельної ділянки у межах норм безоплатної приватизації за певним видом її цільового призначення (використання)  Днепропетровск
2016-03-04 11:01:33.306	Заявка вiдкрита i отримала   ##зауваження вiд робiтника - Перевірка ЦНАП
Зауваження все ликвидировала в тот же день
2016-03-04 15:01:31.589 Запитання/коментар клієнта по заяві 0-128110399
місце реєстрації та проживання: м.Дніпропетровськ.......Прикріплено файл: "img325.jpg"

**Comment by GrekD** [comment]
@Inna-T я вижу, что Ваша заявка еше в работе в ЦНАПе. позвоните по номеру (056) 726-30-69

**Comment by annastolbova** [comment]
ситуація була вирішена на міському форумі,
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.

Гарного дня.
