### ISSUE TITLE
Надання витягу з Єдиного державного реєстру МВС України. Cтатус: Перевірка 

### ISSUE THREAD

**Issue by OlegKorzo** [e-government-ua/iForum#297]
Добрый день.
Создал заявку 14.03.2016 12:38, что означает текущий статус? Имеет ли смысл ждать?

**Comment by kurbpa** [comment]
@OlegKorzo 

Добрый день.
А какой текущий статус и какой номер заявки?

В очереди на обработку  заявок сейчас нет, следовательно всё отработано и ответы отправлены.
Емейл с ответом мог  попасть вам в спам - проверьте.

**Comment by OlegKorzo** [comment]
Добрый день.
На текщий момент статус такой-же Cтатус: Перевірка (запит по фізичним особам)
Номер заявки: 0-133790893

**Comment by kurbpa** [comment]
Пытаемся понять почему  не обновился статус... Вашу заявку мы нашли.
```Запит по фізичній особі: КОРЗО ОЛЕГ ЮРІЙОВИЧ
Результат:
На жаль, інформація про зареєстровані авто відсутня```

Эта информация была отправлена на емейл korzo.oleg@gmail.com

**Comment by OlegKorzo** [comment]
@kurbpa 
Спасибо.
А что означает "на жаль"? Вы не нашли данные о авто в базе? Или вы не нашли саму базу? Я пробовал эту услугу сразу после ее запуска и по человеку у которого 100% есть автомобиль в системе он не находился.

**Comment by kurbpa** [comment]
МВД  базы не перелили все - наполняют только.По их словам  в БД сейчас есть инфо за 3 последние года.
Кого в базе нет - по тем такой ответ

**Comment by OlegKorzo** [comment]
Спасибо за ответ и терпение.

**Comment by kurbpa** [comment]
@OlegKorzo 

Спасибо Вам за сигнал - каждый отзыв нам очень важен.
Хорошего Вам дня!
