### ISSUE TITLE
авторегистрация

### ISSUE THREAD

**Issue by VIKTOROVICH1979** [e-government-ua/iForum#298]
у меня вопрос-как можно официально зарегестрировать авто с поддельным тех. паспортом?я купил авто 2 года назад .и хотел поставить на учёт-оказалось что это двойник (не растоможен)как быть с этим авто?

**Comment by AndreyPopovNew** [comment]
я так понимаю, что "купили" вы оформив генеральную доверенность?

и документов, подтверждающих покупку (передачу) денег нет?

**Comment by VIKTOROVICH1979** [comment]
нет доверенести  остался только тех паспорт.

**Comment by VIKTOROVICH1979** [comment]
подтверждающих покупку (передачу) денег нет?-вопрос не понятен.
