### ISSUE TITLE
Автомобили

### ISSUE THREAD

**Issue by SergikBau** [e-government-ua/iForum#299]
Здравствуйте. На сайте  igov.org.ua информацию о транспортной средстве можно узнать только если известна информация о владельце (юр.  или физ. лицо). А если этой информации нет, а известен только вин код автомобиля. Скажите пожалуйста, как при помощи сайта https://igov.org.ua/service/1397/general или есть другой способ узнать историю владения автомобиля по Вин коду, наличие аварий, не наложен ли арест на автомобиль в связи с долгами текущего владельца и т.п.....
Спасибо за ответ.

**Comment by Koffeek** [comment]
@SergikBau На данный момент узнать информацию по этим данным на сайте невозможно.
