### ISSUE TITLE
Як з вами зв'язатися?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#3]
Часті питання, який в вас телефон, чи є в вас візитки щоб їх роздавати кому треба, як з вами зв'язатися, і тп.

Тому! На порталі знизу в нас є лінк "Немає якоїсь послуги?"
Замінити на текст "Я держ орган хочу замовити послугу"
чи щось таке. Можливо зробити форму на порталі для відправлення заявок.
Допишіть свій варіант.

**Comment by VadymVolos** [comment]
Можливо зробити кнопку червоною "Приєднатися"
 -як волонтер -як держорган -як волонтер і держорнган

**Comment by GrekD** [comment]
У разі необхідності Ви можете спрямувати питання та пропозиції до [групи підтримки iGov](https://docs.google.com/spreadsheets/d/15w9ui-Mz8fTWDHHpDNx52Fnn3lknKsyh68tsX5znKtY/edit?usp=gmail#gid=1246904557) у Вашій області
