### ISSUE TITLE
Сделать возможность делится ссылкой на услугу/ги

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#30]
На портале в фильтре, хочу поделится ссылкой на выбранный мной фильтр, например “Управління праці та соціального захисту населення”, а не могу, так как ссылка сверху без хвоста https://igov.org.ua

Это круто что фильтр работает без перезагрузки страницы, но как делится ссылкой?
Нужно как-то придумать чтоб люди могли поделится ссылкой на ту услуги/министерство которое выбрано в фильтре.

**Comment by GrekD** [comment]
такая задача так и не была поставлена в разработку
можно делиться ссылкой на конкретную услугу
