### ISSUE TITLE
Заявка на субсидию - Прошел месяц - Помилка по операції

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#300]
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1687743201514556&comment_tracking=%7B%22tn%22%3A%22R%22%7D

>Юлия Полигенькая 
Здравствуйте, 2.03.16 оставила заявку на субсидию. Обещали рассмотреть в течение 20 дней и дать ответ. Прошел месяц - ответа нет. Захожу в статусы на сайт выдает :"Помилка по операції: 'Перевірка авторизованості'.Интересует будет ли ответ и когда. Номер заявки 0-126690945, г.Днепропетровск, 2 марта 13:44.УПСЗН Чечелівського (Красногвардійського) району, м. Дніпропетровськ
49000, Дніпропетровськ, вулиця Уральська, 5
Режим роботи з 8.00 до 17.00
Телефон для довідок: (056) 373-68-64

**Comment by dmitrijzabrudskij** [comment]
Ваша заявка в работе у района. Ответ обычно приходит через 30-40 дней (поэтому сейчас в имейле после регистрации мы пишем уже про 30 рабочих). Подождите еще немного, пожалуйста
