### ISSUE TITLE
Не доступна справка про судимість

### ISSUE THREAD

**Issue by vitalijgalinskij** [e-government-ua/iForum#301]
Перше, що ця послуга в мойому регіоні не доступна( м. Дніпропетровськ). В чому проблема?

**Comment by kurbpa** [comment]
@vitalijgalinskij 

Временно отключил - актуализируем весь процесс для запуска на всю страну.

**Comment by vitalijgalinskij** [comment]
Коли відновите?

**Comment by kurbpa** [comment]
Доступно.
