### ISSUE TITLE
заявка 0-128319107

### ISSUE THREAD

**Issue by dnepropetrovsk** [e-government-ua/iForum#302]
День добрый. 
2016-03-04 15:09:52.892	Заявка подана - Взяти в роботу

Ответа никакого нет. Телефоны указанные для контакта, не отвечают. 
УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ
49000, Дніпропетровськ, вулиця Радистів, 8
Режим роботи з 8.00 до 17.00
Телефон для довідок: (056) 375-90-64, (056) 376-52-03

**Comment by dmitrijzabrudskij** [comment]
добрый день
Ваша заявка в работе у района
по наличию решения Вам его пришлют на имейл

**Comment by GrekD** [comment]
субсидія погоджена
