### ISSUE TITLE
На порталі дві форми, треба залишити одну.

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#304]
1. Перша форма знизу: NEW Станьте волонтером iGov!
2. Друга форма на сторінці https://igov.org.ua/about Якщо ви маєте досвід у розробці ІТ-продуктів та бажаєте приєднатися до команди ІТ-волонтерів, запрошуємо Вас заповнити цю форму.

Дві різні форми, я так зрозумів напевно другая форма стара і про неї забули, що там є лінк на неї...

**Comment by GrekD** [comment]
дякуємо, передано в роботу програмістам
