### ISSUE TITLE
Регистрация физического лица-предпринимателя

### ISSUE THREAD

**Issue by NataliaGaykalova** [e-government-ua/iForum#305]
Добрый день! Прошу Вашей помощи разобраться с регистрацией ФОПа. Я верифицируюсь с помощью BANKID, выбираю услугу "Регистрация физического лица-предпринимателя" и меня перебрасывает на регистрационный портал, где нужно ехать и получать ЭЦП. Где я допускаю ошибку? потому что в моем понимании, если мы используем BANKID - то нет необходимости ехать и получать ЭЦП. Заранее спасибо.

**Comment by debooger** [comment]
ЕЦП можна отримати не виходячи з дому https://docs.google.com/document/d/1Bai40Xw-XUcJfYR96CQD7-gSjsCtAlC3DMqbbcI-fxw/edit
Зі списка вибираєте Приватбанк і відкриваєте інструкцію. Там все детально описано. Таким чином сам отримував. Пішло відсили 10 хв. на все. Єдине треба бути клієнтом Приватбанку і мати активний Приват24
