### ISSUE TITLE
заявка 0-153281991

### ISSUE THREAD

**Issue by aleseya** [e-government-ua/iForum#306]
здравствуйте, 03,04,16 открыла заявку 0-153281991 Призначення соціальної допомоги при народженні дитини. 04,04,16 статус заявки Закрыта. предоставляла все , что требовалось, сканы документов.  почему закрыта?

**Comment by dmitrijzabrudskij** [comment]
добрый день
в какой район подавали заявку?

**Comment by aleseya** [comment]
здравствуйте, в Днепропетровский

**Comment by GrekD** [comment]
Рішення отримане, в допомозі відмовлено
причина:не вірно вказано особовий рахунок в банку
