### ISSUE TITLE
Заявка 0-154149888

### ISSUE THREAD

**Issue by fizko** [e-government-ua/iForum#307]
Добрий день. 2 запитання:
1. Яка звичайна тривалысть отримання відповіді на заявку?
2. Волонтером я у вас бути не зможу а ось певну суму буду дуже радий пожертвувати на проект. Як це можна зробити?

**Comment by GrekD** [comment]
Доброго дня!
1. По цій послузі зазвичай відповідь надходить впродовж декількох хвилин. Перевірте у пошті "кошик" та "спам".
2. Напишіть, будь ласка, на пошту start@igov.org.ua
