### ISSUE TITLE
Регистрирую загран паспорта - не выбирается дата

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#308]
>Володимир Бабушкін:
Добрый день. Регистрирую ребенка на получения загран паспорта, в последнем пункте "В який день Ви бажаєте звернутися до міграційної служби?:" не выбирается дата.
Підрозділ міграційної служби, в якому Ви будете отримувати паспорт: Нікополь, вул. Микитинська, 

https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1689677947987748&comment_tracking=%7B%22tn%22%3A%22R0%22%7D

**Comment by Koffeek** [comment]
@VadymVolos Для Никополя закончились слоты на май, уже открыли запись на июнь

**Comment by VadymVolos** [comment]
@Koffeek а можно там в кабинете выводить эту надпись? Чтоб люди понимали почему не выбирается дата. Что просто нужно выбрать следующий месяц.
