### ISSUE TITLE
Хотели как лучше, получилось ... (субсидия)

### ISSUE THREAD

**Issue by iValentin** [e-government-ua/iForum#309]
Привет!

То, что  расскажу, скорее не просьба о помощи, а просто маленький рассказ, который, надеюсь принесет пользу. Оформил субсидию через iGov в январе. Позвонили из местного райсобеса, попросили подойти и подписать бумажку. После подписи вручили писульку с долгожданной халявой на газ и свет. Все ок, iGov работает. 

Январь, февраль, март - исправно плачу минимальный платеж по газу, все ок. Счет на свет приходит полностью, но все равно плачу - ехать разбираться за 200 грн нет смысла. Живу спокойно, iGov работает. 

Начало апреля, стук в дверь. Открываю - стоят 2 дяди из газовой конторы, приехали отключать газ. Хорошо что был дома, пообещал оплатить в течении 20 минут, иначе отрезали бы не задумываясь. Но сразу в банк не поехал, заехал в райсобес - выяснить, почему газовики не видят субсидию. Мою заявку она видят, но - как оказывается, она ставится на паузу, пока я не приду подписать бумажку. Хм, бумажку же  подписал ... в чем проблема? А все просто - девушка, которая приняла от меня подпись и дала мне писульку с халявой на свет и газ забыла снять меня с паузы. Вот я на паузе и провисел 3 месяца. 

В итоге - пошел в банк и заплатил все до копейки. От газа не отключили. И вроде бы iGov и работает, но как-то не до конца, увы. Мой вывод - если переводим услугу в электронный вид, то людей из таких схем нужно выкидывать. И еще вывод - iGov я пока пользоваться не буду. Времени в итоге я потратил не меньше, а денег - значительно больше. 

Увы :( Хотели как лучше, получилось ... 

PS. Кстати, в свое время посылал дельные советы (тут - https://docs.google.com/forms/d/1ueU6PQa-OSA2Tsisxx2RbRWRJ9rLsFlPBlHsr7W-4gE/viewform), но так ответа и не получил. Дошли они до разработчиков или нет, непонятно.

**Comment by dmitrijzabrudskij** [comment]
доброй ночи!
что это за город и район был? и остался ли номер заявки у Вас?

по поводу дельных советов -  продублируйте сюда, пожалуйста

**Comment by iValentin** [comment]
№0-68895993 - там всю информацию найдете. 
По советам - текст не сохранил, а было это 3 месяца назад.

**Comment by dmitrijzabrudskij** [comment]
город и район укажите, пожалуйста
одного номера недостаточно

**Comment by iValentin** [comment]
Великая Михайловка, Одесская область

**Comment by dmitrijzabrudskij** [comment]
спасибо за информацию - проведем семинар для сотрудников соцзащиты по правильной отработке заявок. надеюсь, таких случаев в дальнейшем не будет. извините за неудобства

**Comment by AndreyPopovNew** [comment]
@iValentin такое могло случится и с подачей заявки через окошко в собесе.

другой вопрос - что вам надо было убедиться, что все службы знают о субсидии!

счета же вам приходили? а в счетах есть отдельная графа о субсидии!
тем более ее по правилам назначают с момента подачи заявления!

т.е. к примеру моя мама подала заявление в октябре 2015 года. бумажку о назначении субсидии уже получила в начале декабря. так вот в декабре сразу за ТРИ месяца начислили субсидию.

**Comment by iValentin** [comment]
@AndreyPopovNew в том то  и дело - газовики не дают счета, книжку я заполняю сам. Я заполнял с учетом субсидии, что отражал в математике счетов. Но у них разговор короткий - сначала тишина, потом ломик.

**Comment by AndreyPopovNew** [comment]
@iValentin 
кроме газовиков есть электричество, ЖЭК, отопление, вывоз мусора, лифт

я понимаю, что мы тут в городе "зажрались" и почти все смотрим через Интернет, в том числе через сайт 104,ua. но вообще-то ВСЕ службы обязаны выставлять и рассылать счета! и вы на основании выставленного счета должны платить.
