### ISSUE TITLE
Отримання субсидії на оплату житлово-комунальних послуг

### ISSUE THREAD

**Issue by vetalvas** [e-government-ua/iForum#31]
Вчера заполнял форму 
"Отримання субсидії на оплату житлово-комунальних послуг"

заполнял для пенсионера 
сделал такой выбор для полей

*Ваш вид доходу:  >>   [ пенсiя ]
*Назва організації, де Ви працюєте:  >>  [ не працюю ]

заполнял из таких соображений -  человек пенсионер, значит он не работает а получает пенсию, а значит заполнить надо так 
*Назва організації, де Ви працюєте:  >>  [ не працюю ]

Сегодня получил ответ на email от "Управління соціального захисту у Дніпропетровській області" 

мою заявку не приняли с таким пояснением, вот текст
"На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг відхилене через недостатню або неправильну інформацію..
Причина: Вкажіть назву організаціїї, де отримуєте пенсію, наприклад Пенсійний фонд Ленінського району" 

Оказывается если человек пенсионер то надо указывать Отделение пенсионного фонда, 
в поле
Назва організації, де Ви працюєте:  [ поле для заполнения ]

сама надпись "Назва організації, де Ви працюєте: "  имеет двусмысленность если заполняющий человек не работает 

Поэтому предлагаю переделать вот этот участок формы для заполнения 

*Ваш вид доходу:
*Назва організації, де Ви працюєте:

следующим образом

выбрали в поле 

*Ваш вид доходу:  >>   [ заробiтна плата ]

ниже должна открываться следующая строка

Назва організації, де Ви працюєте:  [ поле для заполнения ]

-------------------------------------------------------------------
выбрали в поле 

*Ваш вид доходу:  >>   [ стипендiя ]

ниже должна открываться следующая строка

Назва організації, де Ви отримуєте стипендiю:  [ поле для заполнения ]

--------------------------------------------------------------------
выбрали в поле 

*Ваш вид доходу:  >>   [ пенсiя ]

ниже должна открываться следующая строка

Назва організації, де Ви отримуєте пенсiю:  [ поле для заполнения ]

==============================================

и так далее для всех пунктов меню *Ваш вид доходу:

**Comment by dmitrijzabrudskij** [comment]
сейчас это сложно реализовать (нужно будет держать под каждого пользователя и под каждый тип выплаты поле с нужной формулировкой организации). давайте подумаем как его переформулировать, чтобы было понятно (или какую дать подсказку под ним)

**Comment by vetalvas** [comment]
а подобное уже работает с полями 
*Електроенергія:  [ Користуюсь / Не користуюсь ]
после выбора [ Користуюсь  ]
открываются поля 
Номер особового рахунка:  [       ]
Назва організації, що надає послугу:  [       ]
Примітки:  [       ]

я думал, может подобное сделать не займет много времени и сил

----------------------------------------------------
Переформулировать можно так 
вариант 1 
Назва організації, де Ви працюєте:
заменить на 
Назва організації, де Ви отримуете дохід:

Подсказки
Для працюючих вкажiть назву підприємства
Для пенсiонерiв назву пенсійного фонду вашого району
Для студентiв назву навчального закладу

а для других пунктов не знаю что написать

может другие подскажут???
