### ISSUE TITLE
не пришло подтверждение

### ISSUE THREAD

**Issue by alzarja** [e-government-ua/iForum#310]
Здравствуйте! 05.04.16 в 23.50 была подана заявка на переоформление загранпаспорта (Днепропетровск, Соборный р-н, Шевченко.7). Подтверждающее письмо на e-mail не пришло(в спаме нет). На портале  - " Cтатус: обробка дмс". Просьба отправить подтверждение на указанный при регистрации адрес

**Comment by AndreyPopovNew** [comment]
присоединюсь сюда - за последние неделю подал три заявки. ни по одной не пришло подтверждение на мыло. 


09.04.2016 17:18	Ви подали заявку на послугу Видача довідки про наявність у Державному земельному кадастрі відомостей про одержання у власність земельної ділянки у межах норм безоплатної приватизації за певним видом її цільового призначення (використання). Cтатус: Перевірка ЦНАП
06.04.2016 15:20	Ваша заявка №0-155426569 змiнила свiй статус на
05.04.2016 20:08	Ви подали заявку на послугу (Загальна послуга) - Надання витягу з Єдиного державного реєстру МВС України. Cтатус: Перевірка (запит по фізичним особам)
05.04.2016 11:32	Ви подали заявку на послугу Дніпропетровськ - Отримання довідки про доходи фіз. осіб. Cтатус: Обробка

**Comment by Koffeek** [comment]
@alzarja отправил на azarja@ukr.net

**Comment by alzarja** [comment]
@Koffeek  спасибо!
