### ISSUE TITLE
Заявка 0-154711334 - Перерегистрация ТС для получения нового техпаспорта взамен утраченого

### ISSUE THREAD

**Issue by 0-154711334** [e-government-ua/iForum#311]
Пока свежи воспоминания о посещении МРЭО, решил написать о своих впечатлениях и внести некоторые предложения о том, как, теоретически, можно улучшить данную услугу.

Поскольку нужно было получить новые техпаспорта на машину и прицеп(взамен украденых), вечером 04.04.2016 зарегистрировал на сайте 2 заявки, указав, что удобное для меня время для посещения сервисного центра будет 06.04.2016 г. в 10-00. Когда около 16 часов 05.04.2016  мне перезвонил сотрудник сервисного центра и сообщил, что моя заявка обработана и завтра я могу приехать к 10 часам в СЦ, изначально было желание ущипнуть себя для подтверждения того, что это реальность, а не снится.
Сразу оговорюсь, что мне просто повезло - утром 06.04. в СЦ было мало посетителей, посему все сложилось достаточно удачно. Со слов сотрудников центра, накануне 05.04. было не просто много посетителей, а ОЧЕНЬ много, поэтому к каждому окошку стояла очередь из 15-20 посетителей.
Когда я к 10-00 подошел к указанному мне по телефону окошку, у него не было посетителей, поэтому здесь все сложилось - записался на 10 часов, меня и приняли в 10-00. Дальнейший алгоритм был следующий:
1. Сотрудник СЦ выдает мне 2 бумажки ( одну на машину, вторую на прицеп) в которых указаны данные моих ТС из старых техпаспортов. Также мне выдается бумажка с двумя сумами, которые нужно оплатить - 391 грн за машину и 201 грн за прицеп. Пока радуюсь!
2. Рядом окошко банка - там мне доходчиво объясняют,что за каждое ТС дополнительно еще нужно заплатить за экспертное исследование, поэтому возникает еще 4 платежа - 197 грн за машину, 152 грн за прицеп, + 2 платежа по 54 грн за компьютерные услуги. Итого 6 платежей, за каждый из которых добрый банк берет комиссию по 20 грн - итого 120 грн за удобство расположения кассы в зале СЦ. Повезло и здесь - возле кассы никого не было, поэтому оплата заняла минут 5.
3. Спускаемся с 3-го этажа на первый этаж где находится условное ООО "ЧЕБУРАШКА", в котором, не покладая рук (и ног тоже!) трудится эксперт - здесь мне дают 4 пустых бланка - 2 заявления и 2 акта осмотра, в которые просят вписать данные тех ТС, которые будет осматривать эксперт. Рядом стойка с образцами заполнения этих опусов - минут 10 пишем, после чего меня отправляют на улицу искать мальчика в черной куртке - он эксперт, ищите, он должен подписать эти бумаги.
4. На улице опять повезло - увидел эксперта почти сразу, он сказал поднять капот в машине - это сигнал для него, когда будет проходить мимо - он подойдет. Минут через 10 ( моя машина и прицеп стояли рядом с теми, которые осматривал эксперт) я был осчастливлен осмотром ТС, результатом которого стали подписи эксперта на актах осмотра.
5. Возвращаюсь назад в ООО "Чебурашка" - там у меня забирают заявления, акты и платежки на 197, 152, 54 и 54 грн, взамен печатают 2  заключения, которые просят подписать у эксперта. 
6. Лечу на улицу, зорким взглядом достаточно быстро нахожу эксперта - на колене он подписывает их. Время 11-00.
7. Поднимаюсь в СЦ, посетителей уже больше, но примерно минут через 5 сдаю все бумаги - их проверяют, забирают для распечатки  и говорят мне подойти минут через 20.
8. 11-30 - подхожу к окошку - мне дают подготовленные бумаги - просят проверить правильно ли указаны все мои данные как паспортные так и на ТС, если да, то расписаться возле "галочек".
Проверяю, расписываюсь, отдаю назад бумаги - просят подождать минут 20, пока будут печатать техпаспорта.
9. 12-00 - о чудо!!!, новые техпаспорта получены.

Итого, что в сухом остатке -повторюсь, мне повезло что в данный день в СЦ было мало посетителей, поэтому вложился в 2 часа. Если бы все эти процедуры проходил на день раньше, большой вопрос, успел бы ли я все сделать за 4-5 часов. 

Насколько я понял, регистрация данной услуги через сайт позволила только подготовить сотруднику СЦ бланк, в котором были указаны данные на ТС из старых техпаспортов. Данный бланк не номерной, без подписей и печатей, он мне был выдан на руки в п.1 - его назначения не слишком понятно, за исключением того, что я из него брал данные когда заполнял бумажки для п.3.

Как, с моей точки зрения, можно упростить и ускорить услугу.

1. После регистрации заявки и проверки ее сотрудником СЦ, он высылает для оплаты необходимые платежки.
2. Заявитель оплачивает их он-лайн.
3. Сотрудник СЦ, увидев оплату, высылает заявителю заполненный бланк с данными ТС + форму заявления для ООО "Чебурашка" и Акт осмотра.
4. Заявитель, приехав в СЦ с готовыми бланками и оплаченными квитанциями, может начинать с п.4 - т.е. делать осмотр машины экспертом - в моем случае, это дало бы экономию времени минут 30-40, в реальной жизни около 2 часов стояния в очередях.
5. Пункты 7-8 также можно упростить, так как предложение проверить правильность заполнения данных и поставить подписи возле кучи "галочек" навевает старым дремучим совком!

В любом случае - ОГРОМНОЕ СПАСИБО за Вашу работу!!!! 
Так и хочется сказать - "Лед двинулся, господа присяжные заседатели"!!!! ))))

Ну и помним великие слова - "БОРІТЕСЯ - ПОБОРЕТЕ! ВАМ БОГ ПОМОГАЄ!"

С уважением
Виктор Копылов

**Comment by GrekD** [comment]
@kurbpa

**Comment by kurbpa** [comment]
@0-154711334 

Виктор, спасибо Вам за Ваш отзыв.
Сейчас вплотную идет работа как раз над резервированием времени у эксперта по электронной заявке и над  заблаговременным предоставлением заявителю всех платежек.

К сожалению, не всегда всё получается сделать сразу, но мы идем в этом направлении.

Ещё раз спасибо за   Ваш отзыв.
