### ISSUE TITLE
Видача/заміна паспорта громадянина для виїзду за кордон - додати інформацію

### ISSUE THREAD

**Issue by AnnaCheba** [e-government-ua/iForum#312]
На сайті залишила заяву на заміну загранпаспорту, і в листі на електронну адресу прийшли реквізити для сплати двох квитанцій і вказана сумма тількі для звичайної(не прискореної до 10 днів) процедури, і не вистачало інформаціі про сплату квитанції, якщо треба залишити старий паспорт. Будь ласка додайте цю інформацію!!!Бо мені треба було бігти і доплачувати, вітрачати час та нерви. Дякую!!!

**Comment by AndreyPopovNew** [comment]
думаю срочная выдача паспорта - это должна быть отдельная услуга

а оплату, чтобы оставить старый паспорт - это действительно нужно.

**Comment by Koffeek** [comment]
@AnnaCheba,  послуга термінового оформлення закордонного паспорта на iGov на даний час не передбачена, осільки час виготовлення рахується з моменту подання анкети, а не з моменту подання заявки на порталі. Щоб не було колізій ми надаємо лише реквізити для звичайного оформлення
@AndreyPopovNew Вы не можете оставить старый паспорт, Вы можете только получить второй, причем для его получения необходимо написать заявление с обоснованием (открытые визы, подтверждение частых поездок за границу и т.п.). Решение о возможности выдачи Вам второго загранпаспорта принимает сотрудник ДМС на месте. Сейчас готовим вариант получения второго паспорта, тогда и будут добавлены соответствующие реквизиты.

**Comment by AndreyPopovNew** [comment]
@Koffeek речь идет об старом уже недействительном паспорте.

у некоторых в нем к примеру стоят шенгенские визы и предоставление информации о том, что ты получал визы и исправно возвращался иногда помогает при получении новой!

**Comment by Koffeek** [comment]
@AndreyPopovNew Согласно Постанове КМУ от 7 травня 2014 р. № 152 "49. У разі закінчення строку дії паспорта для виїзду за кордон чи смерті особи паспорт для виїзду за кордон повертається територіальному органу або підрозділу ДМС, що здійснив його оформлення та видачу, а якщо така особа проживає (проживала) за кордоном, - закордонній дипломатичній установі України." Наличие в нём виз никак не влияет на этот факт. Вы можете себе его отксерить на память или "потерять", но оставить за плату не можете.

**Comment by AndreyPopovNew** [comment]
@Koffeek реальность немного другая!!!! и реально заплатив деньги можно себе оставить старый паспорт и такая услуга предоставляется.

пишешь заявление, платишь деньги - и тебе его оставляют.

**Comment by Koffeek** [comment]
@AndreyPopovNew мы не можем быть ответственны за нарушение законов отдельными сотрудниками ДМС.

**Comment by AndreyPopovNew** [comment]
@Koffeek так никто ничего не нарушает. заявление пишется официально и официально пошлина платится.

**Comment by Koffeek** [comment]
@AndreyPopovNew Я Вам дал ссылку на закон. По нему Вы должны сдать паспорт при окончании срока действия. Действующих загранпаспортов у Вас может быть два (закон это допускает), но просроченый должен быть сдан. Сотрудник ДМС, который позволяет оставить Вам паспорт, нарушает закон.

**Comment by AndreyPopovNew** [comment]
@Koffeek формально Закон соблюден. паспорт по окончании срока действия сдан!

но еще раз прежде чем обвинять кого-то в нарушении закона.

что предусмотрено ДАЛЬШЕ, когда паспорт сдан? ГДЕ это описано?
что орган ДМС должен и/или обязан с ним сделать?
это в Законе описано?

**Comment by Koffeek** [comment]
@AndreyPopovNew "61. Після оформлення особі паспорта для виїзду за кордон її попередній паспорт для виїзду за кордон вилучається та анулюється шляхом пробиття не менш як одного отвору в машинозчитуваній зоні (крім випадку оформлення в установленому порядку другого паспорта для виїзду за кордон), після чого списується та знищується.
За заявою особи її анульований паспорт для виїзду за кордон може не вилучатися, якщо в ньому проставлені одна чи декілька дійсних віз."
Т.е. если у Вас нет действующих виз - то Вы обязаны сдать паспорт. который будет потом уничтожен.

**Comment by AndreyPopovNew** [comment]
@Koffeek т.е. вы сами видите 
За заявою особи її анульований паспорт для виїзду за кордон може не вилучатися
что никто никакие законе НЕ нарушает.

тут же речь идет не о втором паспорте, а об АНУЛИРОВАННОМ!!!!!!
именно аннулированный паспорт(в котором пробивает хотя бы одно отверстие) по заявлению можно НЕ ИЗЫМАТЬСЯ!

вот об этом мы и говорим!

**Comment by Koffeek** [comment]
@AndreyPopovNew при наличии ДЕЙСТВУЮЩИХ виз. А если их нет - то нарушение закона налицо.

**Comment by AndreyPopovNew** [comment]
@Koffeek это уже второй вопрос - есть именно действующие визы или нет.
есть вариант, при котором СТАРЫЙ паспорт, у которого истек срок действия МОЖЕТ остаться у гражданина. и это твариант тоже должен быть предусмотрен на iGov в виде дополнительной опции.

**Comment by Koffeek** [comment]
@AndreyPopovNew если уж на то пошло, то в законе кроме заявления иных документов и платежей за оставление паспорта не предусмотрено, так что iGov  при окончании срока действия ничем помочь не может.

**Comment by iymel** [comment]
Добрый день! С сожалению не закрыт вопрос по Никополю (получение загранпаспорта) в топике Оформление загранпаспорта #281. Примут нас или нет?
 Связались с ДМС. На следующей неделе постараются найти время чтобы принять тех, кто не смог подать заявку 29,03. Как будет точная информация, я Вам сообщу.

**Comment by Koffeek** [comment]
@iymel Странно. Я свзывался во вторник с Никополем. мне сказали, что они обзвонили людей и всех приняли.

**Comment by iymel** [comment]
Нет никто не звонил.
