### ISSUE TITLE
Возможно ли изменить дату? (заявка для подачи документов на загран паспорт)

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#313]
Я не знаю ответа на этот вопрос, поэтому спрашиваю тут.

>Вероника Турагенство
Добрый день! Извините, не подскажите, если мы подали заявку для подачи документов на загран паспорт на одну дату, возможно ее изменить?

https://www.facebook.com/igov.org.ua/posts/1690475777907965

**Comment by AndreyPopovNew** [comment]
я думаю надо просто подать другую - так будет проще.

вопрос в другом - что надо бы как-то закрыть старую, чтобы освободить тайм-слот.

**Comment by VadymVolos** [comment]
1. А как закрыть старую?
2. Если подать новую придется опять сначала ждать (месяц или сколько-там)?
3. Мы со стоны iGov что можем сделать чтоб люди смогли сами переносить дату (без надобности ждать сначала)?

**Comment by AndreyPopovNew** [comment]
а при чем тут ждать с начала? назначается день прихода все равно по свободному тайм-слоту.

перенести - это значит найти ПЕРВЫЙ свободный тайм-слот или выбрать другой. это все равно, что подать новую заявку.

**Comment by AndreyPopovNew** [comment]
кстати, пока услуга и так НЕ работает! дата напрочь НЕ выбирается!

![image](https://cloud.githubusercontent.com/assets/8410116/14405020/4bfdd3c4-fe8d-11e5-9460-1382b90dd813.png)

**Comment by Koffeek** [comment]
@VadymVolos с января в письмах, которые приходят после заказа услуги есть кнопка "Скасувати заявку", которая освобождает слот и снимает заявку. Для новой записи необходимо подавать заявку заново.

**Comment by Koffeek** [comment]
@AndreyPopovNew на апрель для данного конкретного подразделения все слоты уже заняты. Можно поискать в соседних (там всегда есть места). После 15 апреля будет открываться очередь на май.

**Comment by VadymVolos** [comment]
@Koffeek мне пришла мысль, а можно там возле выбора дати писать количество свободных слотов на текущий и следующий месяц. Чтоб было понятно почему не выбирается дата. Ну или надпись выводить свободных слотов на этот месяц уже нет, выберите следующий месяц.

**Comment by Koffeek** [comment]
@VadymVolos писать количество слотов нельзя. В работе условная "заглушка" в том случае если даты заканчиваются. Такое "непродление" очередей зачастую носит вполне обоснованный характер.

**Comment by AndreyPopovNew** [comment]
@Koffeek ну такое НЕОПРЕДЕЛЕННОЕ состояние поля выбора даты вообще **НЕДОПУСТИМО**!

если нету свободных тайм-слотов - то об этом должно быть НАПИСАНО!!!!!

тем более я живу в Кировском(Центраольном) районе - потому документы у меня примут или на Красной или на Поля.
или вы мне посоветуете в Ленинский район съездить? потому что ближайший Бабушкинский, который еще и Жовтневый обслуживает - вообще без вариантов!

**Comment by Koffeek** [comment]
@AndreyPopovNew 1. Если Вы внимательно посмотрите на свой скрин, то увидите надпись, что при отсутствии дат проверьте их наличие в других подразделениях Вашего города..
2. Загранпаспорт - услуга экстерриториальная и подавать документы Вы можете в любом подразделении (хоть в Киеве или Одессе), где есть аппаратура для изготовления паспортов.
3. С 1 марта по области запустили ещё 17 подразделений, в которых изготавливают загранпаспорта, в частности их теперь можно заказать в любом районе Днепропетровска. Как можно донести информацию об этом людям, которые "всё и так знают". В середине марта на Поля был закрыт апрель, на Красной он заканчивался при этом в Соборном, Центральном и других районах можно было без проблем записаться на послезавтра. Для выравнивания этой ситуации и было принято решение закрыть очереди по центральным подразделениям.

**Comment by AndreyPopovNew** [comment]
@Koffeek ну так и читайте, что значит **если вы не нашли удобную дату?** - а **_# КАК_**  их этого можно понять, что они вообще отсутствуют????????? КАК?????

вот и надо, чтобы система выдавала - "на ближайшие 30 дней свободного времени нет"

а по-хорошему должно выдавать БЛИЖАЙШЕЕ СВОБОДНОЕ ВРЕМЯ. через месяц или через два.
и тогда человек может подумать о том, чтобы выбрать другое подразделение.

**Comment by Koffeek** [comment]
@AndreyPopovNew 1. Если дат нет, значит удобной тоже нет.  
2.Сейчас в разработке находится задача по отображению сообщения при отсутствии свободных дат. 
3. Повторю ещё раз, такая ситуация имела место в марте и в апреле. Никто не смотрел на наличие близких дат в других подразделениях. Все ломились на Поля и Красную. Поэтому было принято решение не открывать новых дат для этих подразделений.

**Comment by AndreyPopovNew** [comment]
@Koffeek может и правильное, но надо все же** корректно** его решать!!!!
