### ISSUE TITLE
заявка 0-157987481

### ISSUE THREAD

**Issue by aleseya** [e-government-ua/iForum#314]
Здравствуйте. Почему закрыта заявка № 0-157987481 (открыта 06,04 закрыта 07,04)? "Призначення соціальної допомоги при народженні дитини." Предыдущую заявку 0-153281991 тоже закрыли, уже добавила все что требовали - опять закрыли. На email кстати не приходит письмо ни об открытии и о закрытии заявки. Есть смысл пытаться оформить через  igov.org.ua или это не реально?

**Comment by GrekD** [comment]
добрый день!
Рішення отримане, допомогу призначено - вот решение по Вашей заявке.
подскажите, емайл, на который не пришло письмо об этом.
проверяли ли спам и корзину?
