### ISSUE TITLE
Перерасчет субсидии

### ISSUE THREAD

**Issue by badaboom007** [e-government-ua/iForum#315]
Извиняюсь если не то,или не там пишу.
Оформляли субсидию в октябре через igov (Спасибо большое разработчикам и всем кто принимает участие в проекте).Уже как пару месяцев материальное положение изменилось...
Можно ли сделать перерасчет субсидии?Доходы за сколько месяцев будут учитываться?Возможно ли в igov повторно подать заявку для перерасчета?Или подскажите где можно поискать ответы на вопросы.
Заранее спасибо)

**Comment by AndreyPopovNew** [comment]
расчет субсидии делается на основании доход за предыдущий год!

перерасчет субсидии будет производится автоматически службами соц.защиты :
а) по окончанию и по началу отопительного сезона
б) по итогам доходов за предыдущий год

1. поскольку декларации по доходам за предыдущий 2015 года надо подавать до 01.05.2016, то раньше 01.05.2016 никто перерасчет производить не будет.
2. с апреля закончился отопительный сезон

так что в мае органы соц.защиты начнут перерасчет субсидий без отопления и на основании новых данных о доходах.
