### ISSUE TITLE
Перерегистрация в связи с установкой ГБО

### ISSUE THREAD

**Issue by yozhik84** [e-government-ua/iForum#316]
Подали все необходимые документы, выбрали сегодняшнюю дату, а в ответ тишина. 
Позвонили в МРЕО, они говорят что не в курсе такого сервиса.
Подавали в Киеве, МРЕО на Туполева.
Возник вопрос: можно ли в Киеве зарегистрировать ГБО через ваш сервис, минуя всех жуликов у входа.

**Comment by AndreyPopovNew** [comment]
@yozhik84 вот эта услуга
https://igov.org.ua/service/1465/general
Перереєстрація транспортного засобу при переобладнанні без зміни ном.агрегатів

там при заказе надо выбирать МРЭО

**Comment by yozhik84** [comment]
Я именно по этой ссылке и работала: выбрала МРЕО на Туполева 17, прикрепила все запрашиваемые документы. 
А дальше мне должны позвонить, я должна подъехать в какое-то конкретное время?
Меня интересуют мои дальнейшие действия. Т.к. никаких подтверждений, звонков и инструкций что делать дальше нет.

**Comment by GrekD** [comment]
@kurbpa
