### ISSUE TITLE
Регистрация места жительства. Днепропетровск.

### ISSUE THREAD

**Issue by pvovlos** [e-government-ua/iForum#317]
Добрый день. Появилась необходимость сменить прописку. Раннее, данная услуга была доступна для Днепропетровска, но сегодня - нет. Хотелось бы узнать приблизительные сроки, когда она станет вновь активна, чтобы понимать - ждать мне или идти на адские муки очередей в паспортный стол.

**Comment by AndreyPopovNew** [comment]
@pvovlos этим теперь занимаются местные советы, а не милиция. где-то было объявление об этом, сейчас постараюсь найти.

**Comment by pvovlos** [comment]
ну, думаю, услуга актуальности не изменит. и походы в местный совет возможно в перспективе заменить визитом на этот портал?

**Comment by AndreyPopovNew** [comment]
ну поход для проставления штампа вы никуда не уберете. единственное - это назначенное конкретное время у вас будет. чтобы сдать паспорт ;)

а вот чтобы забрать ;)

**Comment by Koffeek** [comment]
@pvovlos В связи с изменением нормативной базы и формированием новых подразделений данная услуга планирует предоставляться для г. Днепропетровск с 1,05
