### ISSUE TITLE
Заполнение/исправление любой формы с данными на сайте igov.org.ua

### ISSUE THREAD

**Issue by vetalvas** [e-government-ua/iForum#32]
Представьте такую ситуацию

вы заполнили много полей в форме с данными и отправили все эти данные на рассмотрение в соответствующую службу 

через некоторое время к вам приходит письмо от службы с ответом о том что вы в форме допустили ошибки, например такие 
- неправильно заполнили какое то поле 
- не заполнили какое то поле 
- допустили грамматическую ошибку в каком то поле 

На почту вам приходит письмо с таким пояснением  (уже реализовано)
*****************************************************************
Шановний(-а) _______________

На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг відхилене через недостатню або неправильну інформацію..
Причина: Вкажіть назву організаціїї, де отримуєте пенсію, наприклад Пенсійний фонд Ленінського району
Звертаємо увагу, Ви можете заповнити заявку повторно на порталі iGov.org.ua
**************************************************************

После прочтения письма Вам предлагается зайти на сайт и создавать новую заявку и заполнять все поля формы заново.
Недостатки такой ситуации
- вы теряете время, заполняя повторно
- это раздражает: делать те же действия повторно

Предлагаю 2 варианта решения подобной ситуации
Простой и быстрый, но не функциональный (может быть временным решением)  
Вариант 1
Отправлять все данные, заполненные в форме, на email указанный пользователем в самой форме, тем более такое письмо уже отправляется пользователю с текстом 
=================================
Subject — Ваша заявка __номер__прийнята!
Текст письма
Ваша заявка __номер__  прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення.
==========================
к этому тексту достаточно прикрепить данные которые вводил пользователь в заявке

Если заявку пользователя отклонили, то он сможет скопировать/вставить свои данные из полученного письма, при создании новой заявки

Вариант 2 - более функциональный 

На странице "Мій журнал"  https://igov.org.ua/journal/content
Добавить еще один статус для заявки - "Відхилена"

На самой странице выводить возле каждой заявки ссылки:
Подивитися // Редагувати  //  Видалити

Для заявки со статусом "У роботi" все эти 3 ссылки 
Подивитися   //   Редагувати     //   Видалити
не активны (не кликаются)

Для заявки со статусом "Виконана" все эти 3 ссылки 
Подивитися   //   Редагувати     //   Видалити
имеют такой статус 
Ссылка  "Подивитися"  активна - можно перейти на страницу и просмотреть свою заявку
Ссылка  "Редагувати"  не активна - заявка  "Виконана"  зачем ее редактировать??
Ссылка  "Видалити"  активна - по клику просто удаляется заявка со страницы  "Мій журнал" 

Для заявки со статусом "Відхилена" все эти 3 ссылки 
Подивитися   //   Редагувати     //   Видалити
имеют такой статус 
Ссылка  "Подивитися"  активна - можно перейти на страницу и просмотреть свою заявку
Ссылка  "Редагувати"  активна - можно перейти на страницу с заявкой и отредактировать данные в форме и повторно отправить на рассмотрение в соответствующую службу
(при повторной отправке на рассмотрение, заявке присваивать новый номер, или оставлять   номер который уже есть у заявки - здесь как лучше сделать знают программисты)
Ссылка  "Видалити"  активна - по клику просто удаляется заявка со страницы  "Мій журнал"

**Comment by vetalvas** [comment]
Кстати в письме которое приходит пользователю

Шановний(-а) __________________.

Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг зареєстроване. Ви отримаєте відповідь протягом 20 робочих днів.
З повагою,
Управління соціального захисту у Дніпропетровській області,
Команда Порталу державних послуг iGov.org.ua.

Ссылка в конце письма iGov.org.ua  имеет такой адрес:   #current-page
<a href="#current-page">iGov.org.ua</a>

поставьте ссылку на портал  https://igov.org.ua/ 

<a href="https://igov.org.ua/">iGov.org.ua</a>

а в этом письме 

Ваша заявка 95423792  прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення.

вообще нет подписи / ссылки

надо в конец письма  добавить
З повагою,
Команда Порталу державних послуг iGov.org.ua.

естественно с ссылкой

**Comment by GrekD** [comment]
@vetalvas добрый день!
спасибо за Ваши предложения. В течении недели заработает предзаполненность полей (автоматически подтянутся те данные которые Вы раньше уже указывали) - нужно будет всего лишь исправить именно то поле, которое требуется.

Так же у гос. органа появится возможность "уточнить данные" у гражданина по конкретному полю, при этом гражданину подавать новую заявку не потребуется.
