### ISSUE TITLE
Звернення № 0-166845912 Видача довідкок про отримання/неотримання усіх видів державних соціальних допомог

### ISSUE THREAD

**Issue by HekuMo** [e-government-ua/iForum#320]
Добрый день.
Я оставил заявку на справку по получению или не получению денег на ребенка.
В Одессе малиновский район, но сначала не хотело отправлять заявку, выбивало ошибки. Потом отправило. Вот сейчас не могу понятно все ли нормально отправилось и принята ли заявка в том виде в котором я отправил.

**Comment by GrekD** [comment]
@HekuMo подскажите, пожалуйста, номер заявки (должен был прийти на почту) - я проверю

**Comment by HekuMo** [comment]
Добрый день.
Указал в названии темы
Вот дублирую
0-166845912
Спасибо:)

**Comment by GrekD** [comment]
:) не увидела заголовок.
Вы правы - в самой Одессе услуги соц.помощи недоступны, только в области. Я не вижу в какой район упала заявка, скорее всего, Вам по ней пришлют отказ. ((
