### ISSUE TITLE
Загранпаспорт 0-169779382

### ISSUE THREAD

**Issue by manannikov** [e-government-ua/iForum#321]
Добрый день. 16 апреля 2016 г. оформил заявку 0-169779382 на биометрический паспорт в отделении на пр. Ильича, 3, г. Днепропетровск.
Визит выбрал на утро 21 апреля (если не ошибаюсь. Не могу найти где посмотреть).
На почту еще ничего не пришло.
Все в порядке или потерялась заявка?

**Comment by Koffeek** [comment]
@manannikov Отправил письмо ещё раз на почту, указанную при заказе услуги.

**Comment by manannikov** [comment]
Спасибо, получил.
А первое письмо нашел в Спаме, хм, чет не догадался сразу там поискать.

**Comment by Koffeek** [comment]
@manannikov Иногда бывает, что письма попадают в Спам. На экране послу заказа услуги, есть даже упоминание об этом. В любом случае - хорошо, что всё прояснилось. Спасибо, за обратную связь
