### ISSUE TITLE
не пришло письмо по услуге "Отримання паспорта громадянина України для виїзда за кордон для дитини"

### ISSUE THREAD

**Issue by illiadp** [e-government-ua/iForum#323]
12.04.2016 17:04
Ви подали заявку на послугу Отримання паспорта громадянина України для виїзда за кордон для дитини. Cтатус: обробка дмс

это статус на сегодня, письмо так и не пришло, дату подачи я выбрал на 21 апреля 2016
город Днепропетровск, 
Кіровський районний відділ в місті Дніпропетровськ вул. Плеханова, 34, м

**Comment by illiadp** [comment]
паспорт выбрал - небиометрический

**Comment by illiadp** [comment]
пришло письмо 	20 квітня 2016, 11:17:29
там нет ни перечня документов которые необходимы
и нет ссылки чтобы отказаться от посещения так как я не собрал необходимые доки

**Comment by Koffeek** [comment]
@illiadp Приносим свои извинения за недоставленное письмо (они иногда попадают в Спам) и недостаточно оперативную реакцию на обращение. Вам видимо придется подать заявку ещё раз. В случае возникновения вопросов - обращайтесь.
