### ISSUE TITLE
Звернення № 0-165427696  13.04.2016 в 8-40 Дніпропетровськ

### ISSUE THREAD

**Issue by Samarovca** [e-government-ua/iForum#325]
Нет письма от ДМС при оформлении загранпаспорта ребенка. Статус "обробка ДМС". Дата визита в Центральное отделение 29.04 11-45.

**Comment by Koffeek** [comment]
@Samarovca Отправил пиьсмо ещё раз, на указанный в заявке адрес

**Comment by Samarovca** [comment]
Спасибо, сейчас проверю

**Comment by Samarovca** [comment]
Спасибо! Я сделала заявку еще раз. Можно ее удалить?

**Comment by Samarovca** [comment]
Я нашла в письме по вновь созданным заявкам такую опцию - Скасування заявки. Сделала.

**Comment by Samarovca** [comment]
Спасибо. Сервис очень удобный.

**Comment by Koffeek** [comment]
@Samarovca Вам, спасибо, за отзыв
