### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by anykonovych** [e-government-ua/iForum#328]
При использовании карты и сертификата ПриватБанка в качестве идентификации данные подтягиваются на русском. Будет ли это проблемой при регистрации?
Общался с тех поддержкой Приват24. Мне сказали, что информация у них собирается на 3 языках: рус, укр и англ. Сказали, что проблема на стороне портала igov и подтягиваться должны данные на украинском.

**Comment by dmitrijzabrudskij** [comment]
1. проблемой не будет
2. через bankid берутся все необходимые поля на украинском языке (хотя это и не исключает ошибку их изначального заведения - в таком случае пишите в поддержку банка, они исправят)
3. данные в эцп записываются один раз и на все врем действия сертификата. в таком же виде они подтянутся и в заявку на igov. должны браться на украинском языке. но тут  как и в п2 - если их изначально завели неправильно, то нужно исправлять, а потом перезаказывать эцп

**Comment by sector612** [comment]
Не сочтите за некропостинг, но до сих пор актуально. Была тоже проблема с данными на русском из приватбанка, но похоже что я ее поборол. Сделал ЭЦП в приват24, зашел с помощью нее в сервис iGov, в заголовке появилось "вы зашли как..." и мои ФИО на русском. При попытке регистрации ФОП также ФИО подтянулись на русском без возможности изменения. Адрес кстати тоже, но его менять хоть можно.  Заявка была закрыта и отклонена в итоге с комментарием "Пишите на государственном языке".
Дискуссия с техподдержкой приватбанка завершилась тем, что это проблема сервиса приват24, что ее будут решать, извините и все такое.
Однако если в сервисе приват24 изменить язык интерфейса на украинский и заново заказать ЭЦП, то и ФИО в ней тоже будет на украинском. Адрес правда остался на русском, но я его изменил. Теперь мне отказали в заявке уже по другой причине, но это уже оффтоп.
Пользуйтесь :)

**Comment by agerman-ua** [comment]
@sector612 
Спасибо за обратную связь.
