### ISSUE TITLE
Проблемы с получение справки о доходах

### ISSUE THREAD

**Issue by buslondey** [e-government-ua/iForum#329]
Здравствуйте. 
Столкнулся с проблемой получения справки о доходах для себя (из налоговой инспекции) и для своих родителей (из пенсионного фонда).
Свою справку я получил, запрос 0-149934798, но дело в том, что сейчас проживаю в Киеве, а справку готовы были отдавать только лично в руки в моем присутствии, пришлось тратить деньги на билет. Когда пришел в налоговую инспекцию г.Днепропетровска Жовтневого района, то девушка, которая выдает справки, была шокирована тем, что мне кто-то позвонил и сказал, что справка готова, т.к. выдает справки только она, но она никому и никогда не звонит. Заставила заполнить бланк на выдачу данной справки в ручную, хотя все данные были указаны мной в он-лайн форме. Вообщем справку я таки получил, но негативные впечатления конечно остались в избытки, не пойму, почему нельзя выслать мне данную справку заказным письмом (которое я сам и оплачу) или по электронной почте, ведья я идентифицировался через Банкинг-ИД и тем самым подтвердил свою личность?
Со справками для родителей дела обстоят еще хуже. Запрос на выдачу данных справок был отправлен 30 марта, Звернення № 0-149989909 и Ваша заявка 0-150008414, за каждую справку было оплачено по 17 грн за услуги Укрпочты, данные справки, вроде бы были готовы (не могу утверждать, т.к. в живую их еще никто не видел), и получены на укрпочте (Ви можете відстежити наджодження листа до Пенсійного фонду за цим кодом 4900041405967 перейшовши за цим посиланням, Ви можете відстежити наджодження листа до Пенсійного фонду за цим кодом 4900041405975 перейшовши за цим посиланням) уполномоченым лицом ПФ Жовтневого района, после чего, ПФ упаковал эти справки в конверт и отправил их обычным письмом по адресу проживания мои родителей, которое нет возможности отследить! Получается, что с момента подачи заявки, прошло уже 23 дня, справок все еще нет, родителям-пенсионерам пришлось самостоятельно ехать в ПФ и получать эти справки заново, при этом в самом ПФ их высмеяли, сказав, что данную услугу они через интернет не оказывают и что их просто "развели на бабки" (35 грн), это я процитировал выражение госслужащего. После этого я позвонил в ПФ и более-менее вменяемая женщина  дала мне информацию о том, что справки были получены работником ПФ на укрпочте и отправлены обычным письмом.
Вот такая ситуация, хочется все таки увидеть справки родителей (хотя они их уже сделали сами), только для того, чтоб они перестали думать, что их "развели на бабки".

**Comment by AndreyPopovNew** [comment]
@buslondey 
1. в описании получения справки о доходах через ДФС указано, что надо будет заполнять письменную форму и в ответе о готовности справки приходит ссылка на бланк заявления. его надо заполнить, распечатать и подписать.

то что вы живете в Киеве, а зарегистрированы в Днепропетровске - ну так это "ваша проблема". зарегистрируйтесь в Киеве и там ходите получать справки.

2. где вы прочли про позвонить? в описании услуги сказано, что через ПЯТЬ РАБОЧИХ дней ее можно забрать.

3. про справку из Пенсионног офонда поддержу вас. действительно такой МАРАЗМ надо придумать!!!!!! чтобы справка отправлялась с начала укрпочтой в Пенсионный фонд, а потом Пенсионным фондом отправлялалсь по адресу. МАРАЗМ МАРАЗМ И МАРАЗМ. тем более вид справки, который лично мне прислали - даже трудно назвать справкой!!!!!!!

с другой стороны непонятно для чего вашим родителям нужна справка?

**Comment by dmitrijzabrudskij** [comment]
@AndreyPopovNew спасибо, все правильно расписали. насчет справки из пенсионного - поделитесь, пожалуйста, через сколько после отправки письма от укрпочты на пф вы ее получили?

**Comment by AndreyPopovNew** [comment]
@dmitrijzabrudskij по коду что прислали в сообщении было видно, что Пенсионный фонд получил 22.03, на конверте из Пенсионного стоял штемпель 24.03. в почтовом ящике я нашел или 27 или 28 - уже точно не помню.
