### ISSUE TITLE
Пособие на ребенка

### ISSUE THREAD

**Issue by drover1988** [e-government-ua/iForum#33]
заявка  9319401 обработка этап 1 (у роботi), что это за этап такой? долго ожидать?

**Comment by dmitrijzabrudskij** [comment]
проверка заполненной информации. до 3 дней. потом ожидаение решения по всей заявке (10 рабочих дней)

**Comment by annastolbova** [comment]
Заявка закрита 25.01.2016, 

Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
