### ISSUE TITLE
Звернення № 0-169155355

### ISSUE THREAD

**Issue by InnaI** [e-government-ua/iForum#330]
Добрый день! Я подала заявку на получение Загранпаспорта на имя ребенка. Заявку приняли раза, в лучшем случае, с пятого (до этого постоянно обновлялась страница и приходилось начинать все сначала). Но это мелочи. И еще мелочи в том, что время для встречи предлагали то на Правде, то в Диевке, то еще где-то "рядом". По итогу выбрала самый ближайший РО к Победе - в Приднепровске. А вот дальше было самое интересное. По приезду в Самарский РО оказалось, что о ни о какой записи на время им не известно, и, что еще более интересно, у них уже 3 недели не работает оборудование. Отсюда вопрос: каким образом вы передаете информацию в гос.органы и передаете ли вы ее в принципе? Что мне теперь делать с оплатой в адрес Самарского РО, так как они понятия не имеют когда починят оборудование. а паспорт надо делать сейчас и поэтому надо будет идти в другое подразделение? В общем просветите меня о дальнейших моих действиях. Заранее благодарна.

**Comment by Koffeek** [comment]
@InnaI О неисправности аппаратуры в Самарском ДМС мы узнали сами только сегодня (обычно сотрудники предупреждают о таких ситуациях и мы закрываем запись), поэтому запись сейчас закрыли. Вам сказали некорректную информацию о том, что они не знают про запись, т.к. район подключен с 1 марта и люди уже делали там заявки. По поводу доступного времени: в каждом районе слоты занимают индивидуально, соответственно где-то более загружено, где-то менее.
Постараемся помочь с обращением в другой район. Можете указать свой номер телефона для более оперативной связи?
