### ISSUE TITLE
Проблемы с услугой "Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця)"

### ISSUE THREAD

**Issue by voloviktor** [e-government-ua/iForum#331]
После выбора города (Днепропетровск), и выбора опции "Увійдіть в систему через BankID" прохожу авторизацию в "Приватбанк", ввожу телефон-пароль (способ авторизации через QR-код тоже пробовал), далее переходит на новую страницу c адресом "https://igov.org.ua/service/29/general/place/built-in/region/1/city/0" и появляется всплывающее окно с надписью "TypeError: Cannot read property 'split' of undefined" и кнопкой "OK", после нажатия на которую всплывающее окно пропадает и я остаюсь на пустой странице.

**Comment by AndreyPopovNew** [comment]
поскольку с 04.04.2016 регистрацией места проживания занимаются местные советы, то думаю что услуга пока просто не работает.

**Comment by Koffeek** [comment]
@voloviktor По данной услуге проводим работы и она будет доступна, вероятнее всего с мая. Как точно будет известна дата - я отпишу здесь.
