### ISSUE TITLE
Видача/заміна паспорта громадянина для виїзду за кордон м.Тернопіль - не дає вибрати дату звернення до міграційної служби.

### ISSUE THREAD

**Issue by debooger** [e-government-ua/iForum#332]
Вибравши Тернопільську обл., м.Тернопіль, заповнюю всі необхідні поля. 
Після вибору **Оберіть Підрозділ міграційної служби, в якому Ви будете отримувати паспорт:**  в списку тільки 1 запис _Тернопіль, вул.Є.Коновальця,6_.   Вибираю його. 
Далі необхідно вибрати **дату звернення до міграційної служби. **  в цьому полі пусто. Не можливо нічого вибрати.

**Comment by AndreyPopovNew** [comment]
как говорят разработчики - значит свободных тайм-слотов нет. выбирайте пункт.

о том, что надо писать "что свободного времени нет" я разработчикам уже много-много раз говорил.

но они считают, что пустое поле выбора - это прваильно. :(

т.е. подоход "это не баг, это фича" процветает и тут :(((((

**Comment by debooger** [comment]
А ці тайм-слоти в принципі бувать вільні? Здається мені що це так само я к з електронною реєстрацією на співбесіду в посольство в принципі є а по факту зареєструватись неможливо через корупційний фактор. 
Є приклади успішної реєстрації на видачу паспорта по Тернополі?

**Comment by AndreyPopovNew** [comment]
ну тайм-слотов может реально не быть свободных.
вопрос в том, что если их нет об этом должно сообщаться!
а не пользователь должен догадываться, что если поле пустое - то времени нет :(

**Comment by debooger** [comment]
Логічно....
А хто подає  інформацію про вільні тайм-слоти? І як проконтролювати чи вони дійсно є? Чи не буде тут корупційної складової - вільні тайм-слоти  будуть лише для обраних?

**Comment by Koffeek** [comment]
@debooger ДМС Тернополя надало графік, згідно якого вони готові приймати лише 4 людини на день (крок черги 30 хв), тому вільні слоти були вичерпані у перший день. В п'ятницю додали ще 16 на проміжок до 1 травня (крок зменшили до 15 хвилин), але схоже їх теж вичерпали. Наразі чекаємо відгуку від ДМС, якщо вони будуть встигати опрацьовувати людей у новому режимі, то додаємо слоти із кроком у 15 хвилин на весь травень. Корупційна складова може бути лише, якщо працівники ДМС під своїм БанкІД будуть реєструватись, але там є обмеження на кількість заявок від однієї особи. Про час, коли ми додаємо вільні слоти ДМС не повідомляється.

**Comment by Koffeek** [comment]
@AndreyPopovNew Я уже писал Вам, что заглушка про отсутствие слотов находится в разработке. Не стоит писать об этом в каждой ветке.

**Comment by Vitaxa27** [comment]
В суботу вранці був вільний час на 27, 28 і 29 квітня, я зареєструвався на 27,04 на 14,15. В середу спробую як це працює.

**Comment by Gelezako** [comment]
подскажите, это для выдачи обычного загран паспорта? Есть ли сервис для заказа биометрического?

**Comment by sofiadanylevych** [comment]
@debooger Давайте нагадаємо собі те що якщо будь-хто зараз прийде записуватись на звичайну чергу (журнал) в ДМС то можна записатись згідно графіка в кращому випадку на грудень місяць, записувати в журнал людей вони почали тільки в лютому місяці і вже на записі людей по січень.
ДМС нам надали години з 14:00 до 16:00 на електронну чергу з вівторка по пятницю, відкриваємо ми її тільки на місяць наперед, тому в такому випадку не дивно що люди розбирають цю чергу за день.
@Gelezako Записуючись на чергу на закордонний паспорт немає різниці чи Ви будете виробляти звичайний закордонний чи біометричний, просто здійснюєте оплату на біометричний, заповнюєте заяви на біометричний паспорт і приходите в назначену годину.

**Comment by Koffeek** [comment]
@Gelezako Услуга загранпаспорта экстерриториальна, Вы не привязываетесь к месту регистрации. Просто срок изготовления может быть чуть большим чем 30 дней, т.к. требуется проверка Ваших данных, для чего ДМС отправляет запрос по месту регистрации. Вам придется приехать дважды. Один раз - подать заявку, второй - забрать готовый паспорт.

**Comment by Gelezako** [comment]
@sofiadanylevych @Koffeek спасибо за ответы, но вот что я прочитал вот тут:
http://dmsu.gov.ua/de-oformiti-biometrichnij-pasport
Звертаємо увагу, що для оформлення паспорта громадянина України для виїзду за кордон громадяни України звертаються до будь-якого підрозділу міграційної служби (зі списку, наведеного нижче), незалежно від місця проживання. Перший паспорт громадянина України у формі картки (ID) оформлюється лише за місцем проживання.

Лично у меня ситуация следующая, у меня есть загранпаспорт, но он скоро заканчивается и я хотел бы его обменять на биометрический. Под какое правило я попадаю как думаете? Могули не по прописке всё таки его получить?

**Comment by Koffeek** [comment]
@Gelezako Вы же оформляете биометрический паспорт, а не ИД-карту, значит попадаете под правила для загранпаспорта.

**Comment by Gelezako** [comment]
@Koffeek хм, подумал что это одно и тоже, спасибо большое!

**Comment by debooger** [comment]
Вчора успіщно зареєструвався. на кінець 20 травня. Ще питання по квитанціях платити можна вже чи чекати дату явки в ДМС?

**Comment by sofiadanylevych** [comment]
@debooger можете оплатити зараз, якщо Ви роздруковуєте собі квитанції для оплати з сайту ДМС бажано оплачувати якомога скоріше по роздрукованій квитанції, оскільки ДМС змінює реквізити для оплати неочікувано за ніч і не всі знаю коли саме вони їх змінюють таке відбувається 3-4 рази на рік, щоб не попасти в число "щасливчиків" які отримали реквізити а сплатили їх через тиждень а за цей час уже змінились рахунки. Якщо Ви вже оплатили а за цей час реквізити змінились Ваша оплата всерівно дійсна протягом, якщо не помиляюсь, 6 місяців.

**Comment by debooger** [comment]
**sofiadanylevych **  дякую за оператину відповідь.
Ще маю таке питання. Припустім я проплатив квитанції. Чи можливий випадок, коли ДМС може відмовити у видачі паспорта? Те що я оплатив послугу ж  не є 100% гарантією що мені видадуть паспорт. Що тоді буде з цєю оплатою? І ще строки видачі паспорта реальні? Якщо я вибрав опцію 20 днів то це буде реально 20 днів? Не буде відмовок немає бланків, не має того чи сього.

**Comment by sofiadanylevych** [comment]
@debooger Вони повинні дотримуватися строків розгляду якщо 20 днів то це 20 днів з дня подачі документів до підрозділу ДМС, є виключні випадки але гадаю Вам вони не потрібні оскільки вони повязані з лікуванням та еміграцією.
 Виключний перелік підстав для тимчасової відмови у видачі паспорта громадянина України для виїзду за кордон визначено статтею 6 Закону України "Про порядок виїзду з України і в'їзду в  Україну громадян України":
- обізнаність з відомостями, що становлять  державну таємницю, - до закінчення строку, встановленого Законом України "Про державну таємницю" (у разі виїзду за кордон на постійне проживання);
- діють  неврегульовані  аліментні,  договірні  чи інші невиконані обов'язання,  -  до  виконання  обов'язань  або розв'язання спору за погодженням сторін у передбачених законом випадках, чи забезпечення зобов'язань заставою, якщо інше не передбачено міжнародним договором України;
- стосовно  нього  у  порядку,  передбаченому  кримінальним процесуальним  законодавством,  застосовано  запобіжний  захід, за умовами якого йому заборонено виїжджати за кордон, - до закінчення кримінального провадження або скасування відповідних обмежень;
- засудження за вчинення злочину, -  до  відбуття покарання або звільнення від покарання;
- ухилення від виконання зобов'язань, покладених на нього судовим рішенням, рішенням іншого органу (посадової особи), - до виконання зобов'язань;
-свідоме сповіщення про себе неправдиві відомості, - до з'ясування причин і наслідків подання неправдивих відомостей;
- щодо громадянина подано цивільний позов до суду, - до закінчення провадження у справі;
- перебування  під адміністративним наглядом органів внутрішніх справ, - до припинення нагляду.

В інших випадках відмовити у видачі паспорта не мають права, якщо Ви принесли всі необхідні документи вказані в листі, який Вам прийшов після запису на електронну чергу.

**Comment by debooger** [comment]
**sofiadanylevych** ще раз дякую за оперативну і вичерпну відповідь.

**Comment by Vitaxa27** [comment]
Сьогодні в 14,15 здавав документи по запису онлайн. Оплатити можна наперед, сказали що квитанція дійсна протягом року.

**Comment by ostvind** [comment]
Надайте будь-ласка конкретну інформацію коли запрацює сервіс на травень по м.Тернопіль. Дякую!

**Comment by debooger** [comment]
**ostvind **
сервіс уже реально працює по Тернополю. Єдине вільних місць для запису уже на травень напевно не має. Минулого тижня були доступні місця для запису на 20-28 травня. Я сам записався на 20 число.

**Comment by ostvind** [comment]
Виходить так, що потрібно кожен день заходити, реєструватись та перевіряти наявність вільних місць, я правильно зрозумів? Хоча Дніпропетровська область має купу підрозділів та запис без проблем а Тернопіль тільки чомусь один підрозділ на вул. Коновальця.

**Comment by debooger** [comment]
Саме так, наразі лише реєструватись та перевіряти наявність вільних місць.
Тут вже вище розяснювали:
ДМС Тернополя надало графік, згідно якого вони готові приймати лише 4 людини на день (крок черги 30 хв), тому вільні слоти були вичерпані у перший день. В п'ятницю додали ще 16 на проміжок до 1 травня (крок зменшили до 15 хвилин), але схоже їх теж вичерпали. Наразі чекаємо відгуку від ДМС, якщо вони будуть встигати опрацьовувати людей у новому режимі, то додаємо слоти із кроком у 15 хвилин на весь травень

**Comment by sofiadanylevych** [comment]
@ostvind В Тернополі лише один міський відділ міграційної служби є пілотним в якому запрацювала електронна черга, наступним буде Кременецький районний відділ, перевезти абсолютно все на електронну чергу зразу по факту неможливо оскільки уже розписані люди по грудень включно в м.Тернополі, місця на травень люди зайняли буквально за 2 дня коли ми відкрили чергу на травень по 6 людей на день. Місця можуть появитися на травень тільки якщо хтось відмовиться від своєї черги. На червень черга в Тернополі відкриватиметься в кінці травня орієтовно 25 числа плюс мінус 3 дні, точно сказати не можемо. Щоб бути вкурсі новин радимо слідкувати за нами на нашій сторінці у фейсбуці https://www.facebook.com/iGovTernopil/
