### ISSUE TITLE
Надання будівельного паспорту забудови земельної ділянки а також подача в Держбуднагляд повыдомлення про початок будывельних робіт і Декларації про завершення будівництва.

### ISSUE THREAD

**Issue by debooger** [e-government-ua/iForum#333]
Цікавить коли планується запуск Надання будівельного паспорту забудови земельної ділянки  по Тернопільській області.
А також подача в Держбуднагляд повідомлення про початок будівельних робіт і Декларації про завершення будівництва.
Свого часу проходив усі ці кола пекла. Корупція на всіх цих етапах повальна.

**Comment by sofiadanylevych** [comment]
Надання будівельного паспорту забудови земельної ділянки по Тернопільській області вирішили вже давніше трохи призупинити розробку цього процесу оскільки там дуже багато оригіналів документів вимагається а на той момент коли планували її робити не було можливості обійти ці речі. Тому поки що нею не займаємося, "висить" на потім.

**Comment by debooger** [comment]
**sofiadanylevych,**
А чим відрізняється Тернопільська область від Івано-Франківської наприклад. де вже сервіс запущений? Хіба перелік документів нестандартизований для всіх?

**Comment by sofiadanylevych** [comment]
В Івано-Франківську ре-директ на їхній портал а до процесу Дніпропетровська ми ще не дивились оскільки зупинили роботу над цією послугою але наскільки я знаю в них оригінали документів людина приносить коли забирає відповідь, не у всіх містах державні органи згодні приймати копії документів замість оригіналів.

**Comment by sofiadanylevych** [comment]
@debooger доречі якщо Ви з Тернополя і маєте бажання допомогти, можете зайнятися цією послугою, архітектурними послугами на місцевому рівні, допомога не завадить.
