### ISSUE TITLE
Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця) 

### ISSUE THREAD

**Issue by terkin** [e-government-ua/iForum#334]
После авторизации через приватбанк получаю: `2a6fd1d0.app.js:1 stateChangeError TypeError: Cannot read property 'split' of undefined`

`Running command: ga("gtm1461570364427.require", "displayfeatures", undefined, {cookieName: "_dc_gtm_UA-62587678-1"})
analytics_debug.js:9 Set called on unknown field: "dcLoaded".
analytics_debug.js:9 Plugin "displayfeatures" intialized on tracker "gtm1461570364427".
analytics_debug.js:9 Running command: ga("gtm1461570364427.send", "pageview")
analytics_debug.js:9 
Sent beacon:
v=1&_v=j41d&a=1350025502&t=pageview&ds=website&_s=1&dl=https%3A%2F%2Figov.org.ua%2Fservice%2F29%2Fgeneral%2Fplace%2Fbuilt-in%2Fregion%2F1%2Fcity%2F0&dr=https%3A%2F%2Fbank24.privatbank.ua%2FLoginP24%2FloginNext%3FsidBi%3Dca6fb803-4408-4c49-b23a-8f58ebe6d2b7%26lang%3DUA&ul=en-us&de=UTF-8&dt=igov.org.ua%20%E2%80%93%20%D0%9F%D0%BE%D1%80%D1%82%D0%B0%D0%BB%20%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%B8%D1%85%20%D0%BF%D0%BE%D1%81%D0%BB%D1%83%D0%B3&sd=24-bit&sr=1440x900&vp=1440x533&je=0&fl=21.0%20r0&_u=QCCAgAAB~&jid=&cid=713013659.1461337959&tid=UA-62587678-1&gtm=GTM-WXGXTJ&cg1=Service&cd1=713013659.1461337959&cd3=713013659.1461337959_1461570364423&cd4=713013659.1461337959_1461570364423&z=1010312272

analytics_debug.js:9 <unknown>        (&gtm) GTM-WXGXTJ
analytics_debug.js:9 _j1              (&jid) 
analytics_debug.js:9 adSenseId        (&a)   1350025502
analytics_debug.js:9 apiVersion       (&v)   1
analytics_debug.js:9 clientId         (&cid) 713013659.1461337959
analytics_debug.js:9 contentGroup1    (&cg1) Service
analytics_debug.js:9 dataSource       (&ds)  website
analytics_debug.js:9 dimension1       (&cd1) 713013659.1461337959
analytics_debug.js:9 dimension3       (&cd3) 713013659.1461337959_1461570364423
analytics_debug.js:9 dimension4       (&cd4) 713013659.1461337959_1461570364423
analytics_debug.js:9 encoding         (&de)  UTF-8
analytics_debug.js:9 flashVersion     (&fl)  21.0 r0
analytics_debug.js:9 hitType          (&t)   pageview
analytics_debug.js:9 javaEnabled      (&je)  0
analytics_debug.js:9 language         (&ul)  en-us
analytics_debug.js:9 location         (&dl)  https://igov.org.ua/service/29/general/place/built-in/region/1/city/0
analytics_debug.js:9 referrer         (&dr)  https://bank24.privatbank.ua/LoginP24/loginNext?sidBi=ca6fb803-4408-4c49-b23a-8f58ebe6d2b7&lang=UA
analytics_debug.js:9 screenColors     (&sd)  24-bit
analytics_debug.js:9 screenResolution (&sr)  1440x900
analytics_debug.js:9 title            (&dt)  igov.org.ua – Портал державних послуг
analytics_debug.js:9 trackingId       (&tid) UA-62587678-1
analytics_debug.js:9 viewportSize     (&vp)  1440x533
2a6fd1d0.app.js:1 [merge]:(START)oDataOld={"sHead":"Завантаження акаунту по авторизації","sFunc":"account"},oDataNew={"asParam":["bankIDLogin: undefined","bankIDAccount: undefined"]}
2a6fd1d0.app.js:1 [merge]:(FINAL)oDataOld={"sHead":"Завантаження акаунту по авторизації","sFunc":"account","asParam":["bankIDLogin: undefined","bankIDAccount: undefined"]},oDataNew={"sHead":"Завантаження акаунту по авторизації","sFunc":"account","asParam":["bankIDLogin: undefined","bankIDAccount: undefined"]}
2a6fd1d0.app.js:1 [merge]:(START)oDataOld={"sHead":"Завантаження акаунту по авторизації","sFunc":"account","asParam":["bankIDLogin: undefined","bankIDAccount: undefined"]},oDataNew={}
2a6fd1d0.app.js:1 [merge]:(FINAL)oDataOld={"sHead":"Завантаження акаунту по авторизації","sFunc":"account","asParam":["bankIDLogin: undefined","bankIDAccount: undefined"]},oDataNew={"sHead":"Завантаження акаунту по авторизації","sFunc":"account","asParam":["bankIDLogin: undefined","bankIDAccount: undefined"]}`

**Comment by Koffeek** [comment]
@terkin Добрый день, это ошибка авторизации. Для уточнения подробностей специалист ПриватБанка просил уточнить номер телефона и примерное время, когда Вы пробовали войти. Спасибо.

**Comment by terkin** [comment]
последний раз пробовал минут 15-20 назад , проблема такая у меня и у жены -
используем разные аккаунты, номер телефона мой +380999506421  жены -
+380667444414 (пробовала сегодня часа 2-3 назад)

2016-04-25 11:00 GMT+03:00 Koffeek <notifications@github.com>:

> @terkin <https://github.com/terkin> Добрый день, это ошибка авторизации.
> Для уточнения подробностей специалист ПриватБанка просил уточнить номер
> телефона и примерное время, когда Вы пробовали войти. Спасибо.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/334#issuecomment-214195847>
>



-- 
С уважением, Дмитрий.
________________________________
Дмитрий Гунченко, mailto:terkin.web@gmail.com
PHP программист, веб-разработчик
тел. +38 (099) 950–64–21

**Comment by Koffeek** [comment]
@terkin Спасибо. Передал данные в ПриватБанк. Будем ждать от них ответа

**Comment by terkin** [comment]
вам спасибо, не ожидал такой оперативный ответ, пожелание - более
человекопонятные exceptions

On Mon, Apr 25, 2016 at 11:13 AM, Koffeek <notifications@github.com> wrote:

> @terkin <https://github.com/terkin> Спасибо. Передал данные в ПриватБанк.
> Будем ждать от них ответа
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/334#issuecomment-214200005>
>



-- 
С уважением, Дмитрий.
________________________________
Дмитрий Гунченко, mailto:terkin.web@gmail.com
PHP программист, веб-разработчик
тел. +38 (099) 950–64–21

**Comment by Koffeek** [comment]
@terkin Похоже проблема всё-таки на нашей стороне. Будем разбираться в чем именно. Услугу на время закроем. Вам в каком городе регистрироваться надо было?

**Comment by terkin** [comment]
Днепропетровск

2016-04-25 11:45 GMT+03:00 Koffeek <notifications@github.com>:

> @terkin <https://github.com/terkin> Похоже проблема всё-таки на нашей
> стороне. Будем разбираться в чем именно. Услугу на время закроем. Вам в
> каком городе регистрироваться надо было?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/334#issuecomment-214211640>
>



-- 
С уважением, Дмитрий.
________________________________
Дмитрий Гунченко, mailto:terkin.web@gmail.com
PHP программист, веб-разработчик
тел. +38 (099) 950–64–21

**Comment by Koffeek** [comment]
@terkin Для Днепропетровска будем завтра встречаться с начальником департамента регистрации, тогда точно станет понятно, когда запустится услуга (мы планируем с 1 мая)

**Comment by terkin** [comment]
спасибо, еще такой момент - в разделе этой услуги написано *Державна
міграційна служба, *а они говорят что с 4го числа уже не занимаются
пропиской, а эти обязанности были делегированы другим рай администрациям

2016-04-25 12:41 GMT+03:00 Koffeek <notifications@github.com>:

> @terkin <https://github.com/terkin> Для Днепропетровска будем завтра
> встречаться с начальником департамента регистрации, тогда точно станет
> понятно, когда запустится услуга (мы планируем с 1 мая)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/334#issuecomment-214236681>
>



-- 
С уважением, Дмитрий.
________________________________
Дмитрий Гунченко, mailto:terkin.web@gmail.com
PHP программист, веб-разработчик
тел. +38 (099) 950–64–21

**Comment by Koffeek** [comment]
@terkin С 4.04.2016 услугами регистрации/снятия с регистрации занимаются местные органы власти. В случае с Днепропетровском эти функции переданы в райсоветы, при этом в связи с нехваткой персонала было сделано объединение некоторых районов (АНД+Индустриальный, Соборный+Центральный, Шевченковский+Чечеловский).
