### ISSUE TITLE
ввод неправильного пароля на BankID

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#335]
если ввести неправильный пароль при входе по BankID, то вместо сообщения об не найденном логине/пароле выскакивает непонятная ошибка qr_code_err

![image](https://cloud.githubusercontent.com/assets/8410116/14781794/687732fe-0aed-11e6-9352-100f982fb7a7.png)

которая вообще ни о чем не говорит!

**Comment by debooger** [comment]
в мене така помилка була коли я неправильно ввів пароль від свого приват 24 ( не переключив розкладку) В результаті після 5 спроби акаунт привата заблокувало. Потрібно було пройти процедуру зміни пароля на приват24. Перевірте чи активний у вас приват24

**Comment by AndreyPopovNew** [comment]
@debooger вот вопрос именно в том, что форма НЕ пишет, что пароль или логин неправильный, а выдает непонятную ошибку qr_code_err, по которой только после того как заблокируется вход в Приват24 понимаешь, что это значит.

**Comment by Koffeek** [comment]
@AndreyPopovNew Проблема устранена на тестовом сервере и с новой версией исчезнет на основном портале
