### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iForum#336]
Владимир, нужно установить расширение для браузера, позволяющее работать с электронно-цифровыми подписями и тогда у Вас получится подтвердить заявку. (расширение браузер сам предложит установить - Вам только согласиться нужно)

**Comment by Jonhdubf** [comment]
Добрый день , подскажите 
у меня запорожская прописка 
проживаю в Вышгороде, хочу зарегистрировать ФОП в Вышгороде , как это сделать ?

**Comment by Jonhdubf** [comment]
Оперативность - не ваш конёк ...

**Comment by dmitrijzabrudskij** [comment]
сменить прописку. и потом уже регистрировать фоп
