### ISSUE TITLE
0-178106296 и заявка 0-179389256 Регистрация юрлиц, запрос отправили 22 апреля, статус и на сегодня - в оработке. 

### ISSUE THREAD

**Issue by personka999** [e-government-ua/iForum#338]

**Comment by GrekD** [comment]
0-178106296 Заява розглянута, прийнято негативне рішення
Причина: відсутній статут

0-179389256 Заява розглянута, прийнято негативне рішення
Причина:Некоректно заповнена заява та відсутній статут
