### ISSUE TITLE
0-176702820 отказ в приеме документ на загранпаспорт

### ISSUE THREAD

**Issue by OLgasak** [e-government-ua/iForum#339]
доброго дня. заявка 0-176702820. Замовлення закордонного паспорту. Тільки що замісник начальника ДМС заявила, що у Києві був збій, і мій час запису невірний, є запис тільки до обіду і мене ви (ІГов) мали попередити. Що мені робити?

**Comment by Koffeek** [comment]
@OLgasak Доброго дня. Подібна ситуація сталась, оскільки ДМС змінив розклад роботи для виділення окремого часу на видачу паспортів. Виникло непорозуміння, хто саме має сповіщати громадян. Приносимо свої вибачення.
