### ISSUE TITLE
Социальная помощь на ребенка

### ISSUE THREAD

**Issue by msova** [e-government-ua/iForum#34]
Можно ли отменить заявку, так как не правильно была заполнена?

**Comment by dmitrijzabrudskij** [comment]
дайте номер заявки и район, в который подавали - я забракую. и что именно неправильно было

**Comment by msova** [comment]
9690297

**Comment by msova** [comment]
район Индустриальный. хотим на жену оформить все. 
Заранее спасибо

**Comment by dmitrijzabrudskij** [comment]
а ее уже район и так забраковал:
"у зв`язку з тим , що Ви не зареєстровані та не мешкає в нашому районі. До Ваших документів необхідно додати копію паспорта вашої дружини, тому що виплату допомоги Ви оформляєте на себе."

**Comment by msova** [comment]
спасибо большое
