### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by max-yevdokimov** [e-government-ua/iForum#340]
Добрый день! Вчера подал заявку на регистрацию. Сегодня проверяю статус, написано:

> Ваша заявка №0-196729594 змiнила свiй статус на закрита

Что это значит, она удовлетворена или отклонена? И если отклонена, то по какой причине?

**Comment by dmitrijzabrudskij** [comment]
добрый день
по результату обработки Вам отправляется имейл. мог попасть в спам - проверьте, пожалуйста

**Comment by max-yevdokimov** [comment]
Проверил входящие и папку спам - ничего не приходило. Хотя статус заявки изменился час назад.

**Comment by dmitrijzabrudskij** [comment]
случайно закрыли заявку - сказывается неопытность специалистов на местах:(
подайте, пожалуйста, еще одну заявку и скиньте сюда ее номер - прослежу за ней

**Comment by max-yevdokimov** [comment]
Создал новую заявку № 0-202733242
Правда со второго раза, в первый раз на этапе подписания заявки сервер отдал ошибку.
![igovfail](https://cloud.githubusercontent.com/assets/9527497/14852691/8febf046-0c90-11e6-90ec-0cace9a7127a.PNG)

**Comment by dmitrijzabrudskij** [comment]
в работе новая, все в порядке. теперь ожидайте когда ответят

**Comment by GrekD** [comment]
202733242 Заява розглянута, прийнято негативне рішення
Причина: В заяві про реєстрацію Ви поставили відмітку щодо заяви про обрання спрощеної системи оподаткування, а сам файл не додали. Випрате та надішліть заяву ще раз.
