### ISSUE TITLE
Звернення № 0-184124702 від 24.04.2016 

### ISSUE THREAD

**Issue by Iren1986** [e-government-ua/iForum#341]
Подскажите пожалуйста, вот такая ситуация "Мій журналЗвернення № 0-184124702 25.04.2016 Закрита
Призначення соціальної допомоги при народженні дитини
Заявка закрита - обработка этап 2"
Что это означает?

**Comment by dmitrijzabrudskij** [comment]
это значит, что Ваши документы прошли первоначальную проверку на правильность и теперь заявка ожидает решения о назначении выплаты. итогом обработки заявки на этапе 2 будет отправка Вам на имейл решения о пособии при рождении

**Comment by GrekD** [comment]
Рішення отримане, допомогу призначено
