### ISSUE TITLE
Регистрация ОСМД

### ISSUE THREAD

**Issue by personka999** [e-government-ua/iForum#342]
Подала заявку на регистрацию ОСМД, 3 дня находилась в статусе в обработке, сейчас пришел ответ 

Для успішної обробки Вашого звернення, державний службовець потребує уточнення деяких даних.
Примітка:
Виявлені помилки при заповненні заяви

В жарнале, нет возможности внести правки, ди и вообще непонятно что конкретно не так. Как получить информацию?0-178106296- номер заявки

**Comment by dmitrijzabrudskij** [comment]
Вам перезвонят сегодня расскажут что не так с заяdrjq и что нужно добавлять при подаче

**Comment by GrekD** [comment]
0-178106296 Заява розглянута, прийнято негативне рішення
Причина: відсутній статут
