### ISSUE TITLE
Регистрация ФЛП

### ISSUE THREAD

**Issue by Plakhan** [e-government-ua/iForum#343]
Добрый день. Как заполнять поля  заявления "про застосування спрощеної системи опадаткування" которые мне еще недоступны, допустим "Номер реєстрації в органі держ. подат. служби" и т.д. Если я хочу подать заявление вместе с заявкой на регистрацию ФЛП?
Спасибо

**Comment by dmitrijzabrudskij** [comment]
добрый день
оставьте их пустыми
при регистрации в налоговую эту информацию отправит сам госрегистратор

**Comment by VadymVolos** [comment]
Ось ще запитання по недоступним полям:

https://www.facebook.com/igov.org.ua/posts/1695617230727153?comment_id=1698667117088831&comment_tracking=%7B%22tn%22%3A%22R%22%7D

>при подаче заявки не все поля анкеты отображались (название улицы проживания, номер дома, номер квартиры). Сейчас заявка в статусе закрыта. Без указания причины. Правильно ли я понимаю что она не выполнена?*
