### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by nekrich** [e-government-ua/iForum#344]
Добрый день.

При регистрации ФОП отсутствуют поля для заполнения 
1. Назва вулиці, проспекту, провулку тощо (только Тип елемента вулично-дорожньої мережі) 
2. Номер приміщення (только Тип приміщення)

Я не добавлял их в усиленный сертификат при оформлении ЕЦП физ. лица. Если их там нет, по идее должна быть возможность внесения этих данных вручную.

Но с другой стороны эти поля не помечены как обязательные, т.е. их можно не заполнять и они узнают эти данные у регистратора ЕЦП?

**Comment by dmitrijzabrudskij** [comment]
добрый день

у Вас есть возможность авторизоваться в заявке через bankid? если да, попробуйте через нее подать

**Comment by nekrich** [comment]
@dmitrijzabrudskij к сожалению bankID у меня нет ;(, только ЕЦП.

**Comment by dmitrijzabrudskij** [comment]
ок. тогда авторизуйтесь через эцп и впишите недостающие данные в какое-то свободное поле адреса на форме. после чего сбросьте сюда номер заявки

**Comment by nekrich** [comment]
@dmitrijzabrudskij, Добрый день. № заявки: 0-213252712

**Comment by dmitrijzabrudskij** [comment]
ок, взяли в работу уже

**Comment by nekrich** [comment]
Спасибо огромное :)

Но багу пофиксить нужно бы ;)
На http://rp.irc.gov.ua можно указывать данные адреса, если их нет в сертификате 

Yours sincerely, Vitaliy

29 квіт. 2016 р. о 14:07 dmitrijzabrudskij <notifications@github.com> написав(ла):

**Comment by dmitrijzabrudskij** [comment]
конечно пофиксим :)
с Вашего первого сообщения занимаемся
просто чтобы Вы не ждали лишнее время, немного "поможем" с заявкой

**Comment by nekrich** [comment]
Спасибо огромное. Теперь я ФОП.

Но тут "внезапно" возник вопрос: я прикреплял заявление на единый налог (Файл з заявою щодо обрання фізичною особою спрощеної системи оподаткування) 
Но в полученной выписке из реестра я не вижу данных о дате/номере записи в реестре плательщиков единого налога.

Я так подозреваю, что нужно заполнять заявление и все-таки бегом в налоговую?

**Comment by dmitrijzabrudskij** [comment]
Не нужно.  Может появиться позже записи в реестре
