### ISSUE TITLE
Заявка на ФЛП

### ISSUE THREAD

**Issue by keisi7** [e-government-ua/iForum#346]
Номер заявки 0-208214214
Необходимо уточнить некоторые поля:
Номер опису (або унікальний номер) : ? 
-------Уникальные номер чего?
У разі негативного рішення вкажіть, будь ласка, причину: 	Причина:країна реєстрація вказано іноземною мовою та відсутній підпис
Поле КРАЇНА подтянулась автоматически с банка UA
---------- Как  это можно поменять?
--------  ЭЦП подкреплялась. Где именно нужна подпись?
Помогите, пожалуйста, с заполнением этих полей.

**Comment by keisi7** [comment]
Теперь пришло письмо об отказе без указания причины.
Ваше звернення на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації.

Коментар держслужбовця (Причина:)

Что в таком случае делать? Помогите разобраться, пожалуйста.

**Comment by dmitrijzabrudskij** [comment]
подайте еще одну заявку, пожалуйста - и скиньте ее номер сюда

**Comment by keisi7** [comment]
0-213590016

**Comment by dmitrijzabrudskij** [comment]
ок, взяли в работу

**Comment by keisi7** [comment]
Спасибо большое, жду результат

**Comment by keisi7** [comment]
Здравствуйте.
Подскажите, как долго будет обрабатываться заявка 0-213590016?
очень жду позитивный результат.

**Comment by dmitrijzabrudskij** [comment]
в процессе - результат Вам пришлют после того, как предприятие появится в реестре. либо сегодня вечером либо завтра

**Comment by keisi7** [comment]
спасибо за ответ

**Comment by GrekD** [comment]
Заява розглянута, прийнято позитивне рішення
