### ISSUE TITLE
Безпричинна відмова в реєстрації ТОВ на підставі модельного статуту

### ISSUE THREAD

**Issue by xzibit54** [e-government-ua/iForum#347]
Мною вже 3 рази подається одна й та ж сама форма для реєстрації самої звичайної ТОВ на підставі МОДЕЛЬНОГО СТАТУТУ, що не передбачає подання його примірника під час державної реєстрації юридичної особи.

Спочатку мені відмовити виходячи з того, що : (1) немає статуту; (2) заявка невірно оформлена
Вдруге і втретє відмовили лише з підстави - що немає статуту (але весь час я вказував, що реєструюсь на підставі модельного статуту)
Вчетверте я знову подав форму і в коментарях окремо написав у заявці, що ТОВ створюється на підставі статуту. В цей раз мені відмовили з мотивів невірного заповнення заяви.

Звертаю увагу, що кожен раз я заповнював заяву однаково і вона для одного реєстратора заповнена невірно, а для іншого - вірно, проте йому статуту не вистачає.

Проблема в тому, що реєстратори не пишуть, в чому саме помилка, внаслідок чого її неможливо усунути.

Загалом дуже розчарований, що сервіс розробили гарні й розумні люди , а передали на виконання ідіотам.

Прошу допомогти:
Заявки
 0-212353825
0-211111999 
0-197940207

**Comment by GrekD** [comment]
@agerman-ua
прокоментуй, будь ласка

**Comment by agerman-ua** [comment]
Доброго дня, @xzibit54 

0-197940207 - Причина:Некоректно заповнена заява та відсутній статут
0-211111999 - Відсутній статут
0-212353825 - Причина:некоректно заповнена заява
Перші дві (при опції модельного статуту) це точно некоректні причини в частині статуту.
Третю зараз важно оцінити.
Загалом думаю ця ситуація виникла з причини непідготовленості держслужбовця до надання цієї послуги реєстрації юрособи (не через наш портал а взагалі).
Зараз відмови за таких підстав з такими даними заявки вже не зустрічаються.
З повагою, Август.

**Comment by xzibit54** [comment]
Дякую за відповідь)

З повагою,
Квітін Руслан Валерійович
+38 093 99 214 90
відправлено з iPhone
