### ISSUE TITLE
Регистрация ФЛП

### ISSUE THREAD

**Issue by Plakhan** [e-government-ua/iForum#348]
Добрый день. Заявка 0-209448489 была принята, а потом в "статусе" обнаружил что она закрыта...
?????

**Comment by agerman-ua** [comment]
Добрый день, @Plakhan . А что Вам пришло в почту?

**Comment by Plakhan** [comment]
Добрый.
Первое письмо:

Ваша заявка 0-195535861 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення.

Второе письмо:

Шановний(-а) ІРИНА ПЕТРІВНА

Ваше звернення на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації.

Коментар держслужбовця (Причина:країна громадянства- Україна)

Что это значит?

06.05.2016, 12:10, "agerman-ua" <notifications@github.com>:

**Comment by agerman-ua** [comment]
Отлично. Спасибо. 
Есть предположение что Ваша заявка была сформирована когда Вы не могли ввести в поле гражданство собственное значение и оно подтягивалось из BankID как "UA". 
В данный момент есть возможность Вам исправлять данную строку на "Україна".
Скорее всего это единственная причина. 
К сожалению заявку необходимо будет повторить. 
Если Ваша ситуация с регистрацией не срочная - лучше будет повторить попытку после праздников. Но это не обязательное условие.
