### ISSUE TITLE
Закордон паспорт - Поле В який день бажаєте не активно

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#35]
Фідбек:
https://www.facebook.com/igov.org.ua/posts/1630415860580624

> Дмитро Фабрикант‎, Dnipropetrovsk
Попытался подать заявку на замену/выдачу загранпаспорта. Поле *В який день Ви бажаєте звернутися до міграційної служби?: не активно, не дает ничего ввести. Так и не смог подать заявку ((

> Yuriy Zheleznyak
а я не смог оплатить услуги по оформлению загранпаспорта((( прийдется все оплачивать перед фотографированием!!!

**Comment by dmitrijzabrudskij** [comment]
попробуйте снова - добавили расписание на январь 2016

по оплате - какая ошибка была? возможно, был старый имейл, в котором неправильные реквизиты на оплату госпошлины. сейчас они такие:
Квитанція про сплату державного мита:
    Сума: 170 грн
    Отримувач: УК в Жовтневому районі м.Дніпропетровськ
    Р/р: 31415538700005
    ЄДРПОУ: 37989269
    МФО: 805012 в ГУДКСУ у Дніпропетровській області
    Призначення платежу:*; 101; 22090400; державне мито, пов’язане з видачею та оформленням закордонних паспортів
