### ISSUE TITLE
Реєстрація ФОП

### ISSUE THREAD

**Issue by Kulm** [e-government-ua/iForum#350]
Добрий день. 

Заявка № 0-213027865. Прийшла відповідь:
"Ваше звернення на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації.
Коментар держслужбовця (Причина:некоректно заповнена заява.)"

Але не зрозуміло, що саме некоректно заповнено :(

**Comment by max-yevdokimov** [comment]
+1
Сегодня получил такой же ответ по заявке 0-217302492. Насколько я понял, речь идёт о заявлении на упрощённый режим налогооблажения. Некоторые поля я оставил пустыми, так как их нельзя заполнить до того, как ФОП сам по себе будет зарегестрирован. Может из-за этого?

**Comment by Kulm** [comment]
UP? :)

**Comment by agerman-ua** [comment]
Добрий день, @Kulm, @max-yevdokimov  . 
На жаль, така відповідь держслужбовця дійсно не інформативна. На цю мить не готовий проаналізуівати Ваші закриті заявки. Прошу ще трохи зачекати.

**Comment by iValentin** [comment]
@agerman-ua, подскажите, пожалуйста. Если сгенерировать ключ в Приват24 (насколько вижу, это быстрее и дешевле всего), потом этот ключ можно использовать для подачи отчетов в налоговую? Или для этого нужно сделать другою ключ, уже в налоговой? Спасибо за ответ.

**Comment by agerman-ua** [comment]
Да, на мой взгляд, приватовский ключ самый доступный и к тому же бесплатный.
К сожалению не обладаю реальным опытом подачи таких отчетов, но с точки зрения законодательства все ключи ЭЦП которые сгенерированы сертифицированными центрами имеют взаимозаменяемость или взаимоприменимость :). Но зная способности налоговой - лучше ещё уточнить у бухгалтеров,

**Comment by Kulm** [comment]
Есть ли шанс зарегистрироваться? Или идти в живую в налоговую?
Просто время идет - не знаю что делать.

**Comment by dmitrijzabrudskij** [comment]
сделайте новые заявки и сбросьте сюда их номера, пожалуйста

**Comment by Kulm** [comment]
Ваше звернення 0-227642940 успішно зареєстровано

**Comment by Kulm** [comment]
Це на 2-гу групу

**Comment by dmitrijzabrudskij** [comment]
прошу прощения, не успел остановить нашего "бракователя заявок". уже отрезал им доступ. еще одну подайте, пожалуйста

**Comment by Kulm** [comment]
:)
подал еще одну
Ваше звернення 0-227703693 успішно зареєстровано

**Comment by dmitrijzabrudskij** [comment]
спасибо, взяли в работу

**Comment by max-yevdokimov** [comment]
При отправке заявки получил подряд 2 попапа с ошибками
![image](https://cloud.githubusercontent.com/assets/9527497/15145938/0cab743c-16c1-11e6-98e4-9fbde90bc6c5.png)

![image](https://cloud.githubusercontent.com/assets/9527497/15145962/3acf5d24-16c1-11e6-8b58-9ab24b087698.png)

Но в "моём журнале" запись появилась, её номер № 0-227743145. Уведомление на почту не пришло.

**Comment by dmitrijzabrudskij** [comment]
тоже взяли в работу

**Comment by max-yevdokimov** [comment]
Прошло три дня, заявка до сих пор в обработке. Есть какие-то новости?

**Comment by dmitrijzabrudskij** [comment]
все в порядке с Вашей заявкой. ответ отправят после появления данных о предпринимателе в реестре. вероятнее всего сегодня это и случится

**Comment by max-yevdokimov** [comment]
Нашёл себя в реестре ФОПов, наконец-то зарегистрировали. Спасибо за помощь! Это была моя пятая попытка:) Надеюсь все баги и недоразумения вы ликвидируете, потому что сервис очень облегчает процесс и экономит время.

**Comment by max-yevdokimov** [comment]
Ахах, пришло письмо о том, что мне отказали в регистрации) Но я больше верю реестру на сайте министерства юстиции, чем авто письмам. Надеюсь это просто какая-то ошибка.

> Доброго дня!
> 
> Нещодавно Ви замовляли послугу реєстрації юридичної особи або фізичної особи-підприємця на порталі igov.org.ua. На жаль, Ваше звернення було опрацьоване с некоректним коментарем і Вам було відмовлено в реєстрації. Приносимо вибачення за незручності та просимо Вас створити нову заяву на реєстрацію.
> 
> Якщо Ви вже отримали послугу по новій заяві або вона зараз очікує обробки, просимо її не дублювати.
> 
> З повагою, команда порталу igov.org.ua

**Comment by dmitrijzabrudskij** [comment]
письмо рассылалось всем, кому беспричинно отказали - туда могли попасть и люди с новыми успешными заявками. 
там внизу есть приписка про новые заявки - как раз Ваш случай

**Comment by max-yevdokimov** [comment]
Мне так и не пришло письмо о том, что меня успешно зарегестрировали. Насколько я понимаю, в нём должен находиться код админуслуги, по которому я смогу получить выписку из реестра. Если бы я регистрировался не через iGov, этот код я бы нашёл в документе "Опис документів, що надаються фізичною особою державному реєстратору для проведення реєстраційної дії "Державна реєстрація фізичної особи-підприємця". Я ещё как-то могу получить этот код?

**Comment by dmitrijzabrudskij** [comment]
письмо уходило. продублировал еще раз со своей почты на maksim.evdokimov@hotmail.com - проверьте

**Comment by max-yevdokimov** [comment]
Спасибо, получил. Первое письмо не приходило (спам смотрел).

**Comment by Kulm** [comment]
Получил письмо с подтверждением регистрации еще в пятницу. Коллеги, такой вопрос - а как получить Витяг із реєстру платників єдиного податку или хотя бы проверить являюсь ли я таковым и точно ли нужная группа?

**Comment by max-yevdokimov** [comment]
Про витяг не знаю, а проверить можно тут https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx

**Comment by Kulm** [comment]
да сюда чего то не пускает: Помилка авторизації користувача Невідома помилка

**Comment by agerman-ua** [comment]
А попробуй https://usr.minjust.gov.ua/ua/freesearch  и введи свой ИНН на
ФОПе

2016-05-17 13:57 GMT+03:00 Kulm <notifications@github.com>:

**Comment by Kulm** [comment]
Пробовал - там информации по налоговой группе и единому налогу нет :(

**Comment by dmitrijzabrudskij** [comment]
по вытягу у нас есть услуга на портале: https://igov.org.ua/service/368/general
но работает по Днепропетровской области и Хмельницкому
по другим территориям нужно в налоговую стучаться

**Comment by Kulm** [comment]
Если кому интересно. Звонил в консультацию налоговой - говорят что держрегистратор должен подать в электронной форме заявление про упрощенную систему в налоговою, но по факту такого механизма не существует. Поэтому пришлось ехать в налоговоую - писать заявление про выбор упрощенной системы, расчет доходов за прошлый год, запыт на выдачу вытяга с реестра единого налога, книгу облику доходов и т.д. То есть по факту через iGov удалась только государственная регистрация, все вопросы с налоговой нужно решать лично :(

**Comment by max-yevdokimov** [comment]
Не знаю, в моём случае упрощенку зарегестрировали - я могу себя найти в "Реєстрі платників єдиного податку".

**Comment by Kulm** [comment]
ну значит во Львове пока не работает :)
а про то что нет механизма передачи электронной копии заявления от госрегистратора в налоговую сказали на линии 0-800 налоговой

**Comment by dmitrijzabrudskij** [comment]
соврали. все есть. и всех, кто заходит через igov, регистрируют и в налоговой тоже. не делайте лишних движений
единственное зачем может понадобиться сходить в налоговую - это получить витяг о том, что вы плательщик единого налога. хотя по-хорошему можно это все проверить на сайте фискальной службы (только сервис у них работает нестабильно)

**Comment by Kulm** [comment]
> кто заходит через igov, регистрируют и в налоговой тоже.
До сих пор при проверке через https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx (Реєстр платників єдиного податку) выдает "Даних не знайдено за вказаними реквізитами". А регистрация ФОПа была 12.05.

**Comment by dmitrijzabrudskij** [comment]
вот выдержка из выписки о регистрации фопа: https://www.dropbox.com/s/i3hy307f85oom5f/kulchitskij.jpg?dl=0
налоговая ответила, что все в порядке. вполне возможно, что у них есть какая-то задержка с отображением данных на сайте

**Comment by Kulm** [comment]
как мне вчера объясняли в налоговой - это означает, что меня взяли на учет как плательщика налога на общей системе. Из смешного: на мо

**Comment by dmitrijzabrudskij** [comment]
))
но в итоге Вы же к ним все-таки приехали и написали заявление там? что они по нему сказали - когда должно появиться на сайте?

**Comment by Kulm** [comment]
Купил пакет документов:
1. Книга учета доходов
2. Заявление про упрощенку
3. Расчет доходов 
4. Запыт на выдачу мне вытягу

Потом пойти в консультацию заполнить все документы (хотя все равно не правильно, после консультаци при попытке сдать документы, пришлось опять покупать бланки и перезаполнять :) 
Регистрация должна быть на протяжении 2 рабочих дней, а выдадут вытяг и книгу через 10.
Но так как группа 2 - то деятельность можно вести с 01.06.

**Comment by dmitrijzabrudskij** [comment]
понятно, жесть конечно...
и это проделки отдельной налоговой
очень надеюсь, что скоро мы с ними начнем-таки работать по всей стране и эта ситуация начнет налаживаться

**Comment by Kulm** [comment]
Все, я уже появился в налоговой :)
