### ISSUE TITLE
Регистрация юр.лица

### ISSUE THREAD

**Issue by Balashow** [e-government-ua/iForum#351]
![1](https://cloud.githubusercontent.com/assets/19203619/15040215/990501a0-12bb-11e6-8dda-a709a04ae69e.png)
Была предпринята попытка регистрации юр.лица (ООО) в Киеве.
№0-213753353 
Заявка была корректно заполнена и подписана ЭЦП.
Исходя из пояснения к отказу возникает вопрос - возможно ли отправить заявку не подписав ее ЭЦП???

**Comment by agerman-ua** [comment]
Спасибо за подробный отчет о ситуации.
Короткий ответ на вопрос - нет, если заявка сформирована, должна быть подпись. 
К сожалению были непродолжительные сбои при взаимодействии портала и сервиса наложения подписи. Возможно это был Ваш случай.
