### ISSUE TITLE
Не могу зайти на сайт

### ISSUE THREAD

**Issue by nusichka82** [e-government-ua/iForum#352]
Добрый день! Второй день подряд не могу зайти на сайт. После ввода персональных данных и пароля из смс выдаёт ошибку (во вложении)
![-1](https://cloud.githubusercontent.com/assets/17982367/15071338/7df63cf2-1393-11e6-8d1f-046085058826.jpg)
Когда возможно будет войти?

**Comment by annastolbova** [comment]
Добрый день, @nusichka82 
попробуйте, пожалуйста, почистить cache and cookies в своем браузере и повторить попытку ввода, т.к. только что мы протестировали вход в браузере Google Chrome и все прошло успешно.
Также уточните, пожалуйста, через какой банк Вы авторизируетесь?

**Comment by nusichka82** [comment]
Очистка не помогла, выдаёт ту же ошибку (браузер Chrome). Авторизируюсь через Приватбанк.

**Comment by bvv4ik** [comment]
фаерыолы или антивирусы  какие-то стоят?
попробуйте отключить временно антивирусы или рекламные блокеры

**Comment by nusichka82** [comment]
не помогло, результат тот же

**Comment by iValentin** [comment]
Аналогичная ошибка и в режиме инкогнито.

**Comment by nusichka82** [comment]
Только что пробовал муж зайти на сайт под своими данными - всё загружается, при вводе моих данных - ошибка.

**Comment by nusichka82** [comment]
Проблема так и не решена. Кто-нибудь поможет решить?
