### ISSUE TITLE
Регистрация ТОВ

### ISSUE THREAD

**Issue by kakadudu** [e-government-ua/iForum#353]
Для регистрации указано, что нужно сделать ЕЦП.
По ссылке https://docs.google.com/document/d/1Bai40Xw-XUcJfYR96CQD7-gSjsCtAlC3DMqbbcI-fxw/edit
указано, что ЕЦП делают Приватбанк и Укрсиббанк. 
Укрсиббанк ЕЦП для физлиц не делает!
У Привата тех.проблемы уже 2 недели в Приват24 на регистрации ЕЦП. Тоже не делают временно. Пришлось заказывать, чтобы открывали компанию люди из интернета за 2 тыс грн.
Прошу как минимум убрать Укрсиббанк из списка.

**Comment by GrekD** [comment]
@kakadudu 
добрый день. Возможно, уже исправили, но сейчас в файле напротив Укрсиббанка уже стоит прочерк.
