### ISSUE TITLE
Дитячий закордонний

### ISSUE THREAD

**Issue by nata76** [e-government-ua/iForum#354]
При реєстрації на дитячий закордонний в 
Тернополі не можливо зайти в останні комірки де визначається дата на відвідування паспортного столу Вони пусті і дати не зявляються

**Comment by AndreyPopovNew** [comment]
тут уже несколько тем по Тернополю. там работает пока один отдел по электронной очереди и соответственно все даты быстро разбирают.

**Comment by sofiadanylevych** [comment]
Немає вільних дат для запису тому не можливо обрати дату на запис, черга на червень буде відкриватись в кінці травня
