### ISSUE TITLE
Пропали почти все онлайн услуги. 

### ISSUE THREAD

**Issue by Garvan1** [e-government-ua/iForum#355]
В городе Кривой Рог раньше было много онлайн услуг. Теперь при выборе в фильтре остаются лишь несколько незначительных.

**Comment by Koffeek** [comment]
@Garvan1 Добрый день. Это было связано с некорректной работой фильтра услуг (услуги людбого из городов области показывались как доступные по всей области). Сейчас ошибка устранена. Для г. Кривой Рог на данный момент доступны только общеобластные услуги: 
ДМС
Видача/заміна паспорта громадянина для виїзду за кордон
Видача паспорта громадянина для виїзду за кордон для дитини

ДФС
Видача довідки про відсутність заборгованості з платежів до бюджету, що контролюються органами державної фіскальної служби
Отримання довідки про доходи фізичних осіб
Надання витягу з реєстру платників єдиного податку

УПСЗН
Отримання субсидії на оплату житлово-комунальних послуг
Призначення соціальної допомоги при народженні дитини
Призначення державної соціальної допомоги інвалідам з дитинства та дітям-інвалідам віком до 18 років
Призначення державної соціальної допомоги малозабезпеченим сім’ям
Призначення допомоги на дітей одиноким матерям
Призначення допомоги на дітей, які перебувають під опікою чи піклуванням
Призначення допомоги на дітей-сиріт та дітей, позбавлених батьківського піклування та грошового забезпечення прийомним батькам
Призначення допомоги при усиновленні дитини
Призначення допомоги у зв'язку з вагітністю та пологами
Призначення компенсаційної виплати непрацюючій працездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку
Призначення надбавки на догляд за інвалідом з дитинства або дитиною-інвалідом
Призначення одноразової винагороди жінкам, яким присвоєно почесне звання "Мати-героїня"
Призначення соціальної допомоги особам, які не мають права на пенсію, та інвалідам
Призначення тимчасової державної допомоги дітям, батьки яких ухиляються від сплати аліментів, не мають можливості утримувати дитину або місце проживання їх невідоме
Щомісячна грошова допомога малозабезпеченій особі, яка проживає разом з інвалідом I чи II групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним
Видача довідок про отримання/неотримання усіх видів державних соціальних допомог.
Видача посвідчень інвалідам з дитинства та дітям інвалідам, особам, які не мають права на пенсію та інвалідам
