### ISSUE TITLE
Загран паспорт Никополь

### ISSUE THREAD

**Issue by AndreySerdyuk** [e-government-ua/iForum#356]
Добрый день! Пытаюсь зарегистрироваться на получение загран.паспорта в Никополе через Privat24 на IGOV, но IGOV не предлагает дату и время для подачи документов. 
Подскажите, пожалуйста, что мне делать в этой ситуации? 

Заранее благодарен, 
Андрей Сердюк

**Comment by Koffeek** [comment]
@AndreySerdyuk Добрый день. Для Никополя уже выбрана очередь на июнь. На июль пока не открывали, т.к. возможно появятся аппараты для загранпаспортов в соседних городах или увеличится полоса для iGov.

**Comment by AndreySerdyuk** [comment]
Спасибо за комментарий. Скажите, пожалуйста, если же мне удобно делать паспорт в Никополе, как мне зарегистрироваться на Июль, например?

**Comment by Koffeek** [comment]
@AndreySerdyuk Ближе к 15 мая будем открывать очередь на июль, тогда сможете.

**Comment by AndreySerdyuk** [comment]
Спасибо, @Koffeek

**Comment by Koffeek** [comment]
@AndreySerdyuk Очередь на июль для г. Никополь открыта. Можете заказывать.

**Comment by AndreySerdyuk** [comment]
Регистрация прошла успешно, спасибо @Koffeek
