### ISSUE TITLE
Двойной отказ при регистрации ТОВ

### ISSUE THREAD

**Issue by tatarchukihor** [e-government-ua/iForum#357]
Заявка 0-222796499 от 06.05.2016 - "причина відмови - на установчих докумнентах відсутній підпис". Как при наложении электронной подписи она может отсутствовать?!!!
Заявка  0-189822628  от 25.04.2016 причина отказа "відсутній статут" - указывали "модельний"!!! Это как понимать?

**Comment by dmitrijzabrudskij** [comment]
добрый день
подайте еще одну заявку, пожалуйста. и сбросьте сюда ее номер
здесь, к сожалению, сыграл человеческий фактор (не до конца человек знал как работать с заявками и проверять наложенность эцп) - поэтому обе заявки забраковали.

**Comment by tatarchukihor** [comment]
Здравствуйте! Спасибо за Ваше письмо! Заявка 0-229694583 от 11.05.2016 года.

**Comment by dmitrijzabrudskij** [comment]
подскажите - а Вы авторизировались в заявке через эцп или bankid?

**Comment by tatarchukihor** [comment]
))) Я ключ получил через систему  "Приват-банка".

**Comment by tatarchukihor** [comment]
ЭЦП

**Comment by dmitrijzabrudskij** [comment]
есть небольшая проблемка - в эцп у Вас фио записано на русском языке. а для регистрации нужно на украинском

можете еще раз заполнить заявку с авторизацией через bankid? (фио в этом случае на украинском будет)

**Comment by tatarchukihor** [comment]
так в банке заполнили((. ок, прямо сейчас заполню.

**Comment by tatarchukihor** [comment]
Шановний(-а) ІГОР ЛЕОНІДОВИЧ!
Ваше звернення 0-231104903 успішно зареєстровано

**Comment by dmitrijzabrudskij** [comment]
гуд. тут все нормально. заявка в работе

**Comment by tatarchukihor** [comment]
Спасибо за обратную связь)
