### ISSUE TITLE
Так и не могу зайти на сайт

### ISSUE THREAD

**Issue by nusichka82** [e-government-ua/iForum#358]
Добрый день! Уже неделю не могу пройти авторизацию через Приват24 на сайте со своими данными ни на одном устройстве (компьютер, ноутбук, телефон) - при вводе пароля из смс-сообщения выкидывает на страницу с ошибкой, другие пользователи Приват24 со своими данными на этих же устройствах проходят авторизацию без проблем. Скорее всего проблема во взаимодействии с BankID. Обращалась на форум 6 дней назад, выполняла все рекомендации, сообщала об ошибке на портале, но проблема так и осталась не решённой. Кто-то может решить этот вопрос? Или подсказать, куда ещё можно обратиться с моей проблемой?
![7df63cf2-1393-11e6-8d1f-046085058826](https://cloud.githubusercontent.com/assets/17982367/15208653/5e517424-1835-11e6-8e68-01ae26ed3237.jpg)

**Comment by Koffeek** [comment]
@nusichka82 Проблема на стороне ПриватБанка. Вам необходимо обратиться на 3700 или в техподдежку Приват24 с сообщением, что при авторизации по BankID у Вас выпадает ошибка.

**Comment by nusichka82** [comment]
Спасибо, обратилась, сказали, что не могут помочь в решении данного вопроса.

**Comment by Koffeek** [comment]
@nusichka82 Если можно, то напишите номер Вашего телефона для Приват24 и примерное время последней попытки. Попробуем с нашей стороны узнать. И отдельно когда и куда именно обращались в ПриватБанк за помощью (мы сейчас с ними плотно прорабатываем именно обращения пользователей и нужны конкретные кейсы)

**Comment by nusichka82** [comment]
Авторизируюсь по номеру +380506170252, попробовала зайти только что (в 18-00) - результат прежний. Обращалась в Приватбанк по номеру телефона 3700, оператор Оксана, время звонка 17-42.

**Comment by dmitrijzabrudskij** [comment]
а попробуйте еще раз пройти авторизацию и, если будет ошибка, сбросьте ее сюда

и еще Вы писали, что у других пользователей без проблем проходит авторизация с того же компьютера/браузера - можно их номер, пожалуйста?

**Comment by nusichka82** [comment]
Только что прошла авторизацию - ошибка осталась. 
![-1](https://cloud.githubusercontent.com/assets/17982367/15239165/e7dfd3a8-18e8-11e6-9532-881ab11c3a86.jpg)

**Comment by nusichka82** [comment]
Номер другого пользователя, который проходит авторизацию без проблем, +380950413329

**Comment by dmitrijzabrudskij** [comment]
попробуйте сейчас. только кеш почистите в браузере

**Comment by nusichka82** [comment]
Наконец-то))) Всё получилось) Спасибо!!!!!!!!
