### ISSUE TITLE
возврат денег

### ISSUE THREAD

**Issue by AnnaAnnach** [e-government-ua/iForum#359]
Я оплатила на лишние реквизиты на паспорт. Как мне вернуть деньги?

**Comment by Koffeek** [comment]
@AnnaAnnach Если Вы оплатили госпошлину или админуслугу, то для возврата Вас могут попросить обратиться в управление ДМС области (г. Днепропетровск, Троцикая площадь (Красная площадь), 2а) где необходимо написать заявление и приложить оригинал квитанции. Точный механизм возврата средств может подсказать только ДМС. Возможно разьяснения можно получить по контактым телефонам http://dmsu.gov.ua/kontakti/terytorialni-orhany

**Comment by AnnaAnnach** [comment]
Большое спасибо
