### ISSUE TITLE
Отримання субсидії на оплату житлово-комунальних послуг.

### ISSUE THREAD

**Issue by BenOZ** [e-government-ua/iForum#36]
До этого я с матерью ходили и консультировались. Заполняли буквально под диктовку. Решил оформить по интрнету.
20.10.15 - Оформил заявку, заполнил форму.
21.10.15 - Пришёл ответ: "На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг відхилене через недостатню або неправильну інформацію..
Причина: Не вірно:Період, за який Ви заповнюєте декларацію"
И это при том, что период я указал тот же, что и мне сказали нужно указать...
Теперь, при попытке регистрации новой заявки, появляется маленькая форма с адресом регистрации и адресом проживания. После подачи такой заявки на почту пришло письмо со ссылкой: "Опрацюйте це звернення на порталі". При переходе по ссылке требуется ввести логин и пароль. Что это за логин/пароль, если я захожу в систему через BankID?
Как быть?
Что делать?
Помогите, плз!
Большое спасибо!
ЗЫ: Ссылка в письмах "Звертаємо увагу, Ви можете заповнити заявку повторно на порталі iGov.org.ua" не рабочая.

**Comment by dmitrijzabrudskij** [comment]
какой город и какой район выбирали при заполнении заявки на субсидию?

**Comment by BenOZ** [comment]
Днепропетровск, Бабушкинский.

**Comment by dmitrijzabrudskij** [comment]
проверил - нормально отправляется заявка. так и не понял как вас перебросило на маленькую форму с адресами

насчет ссылки - спасибо за информацию - поправлю в ближайшей версии

**Comment by BenOZ** [comment]
Прилагаю скриншоты...
И всётаки, от кого я могу получить информацию по поводу заявки? Что именно я заполнил неправильно? Как правильно?
![01](https://cloud.githubusercontent.com/assets/15227034/10630937/37dc3cea-77e3-11e5-9ba4-d31c3aefa33e.png)
![02](https://cloud.githubusercontent.com/assets/15227034/10630939/37df333c-77e3-11e5-9e11-12154329366b.png)
![03](https://cloud.githubusercontent.com/assets/15227034/10630938/37dce726-77e3-11e5-8abf-e383f2610a47.png)
![04](https://cloud.githubusercontent.com/assets/15227034/10630940/37dfa31c-77e3-11e5-82a5-786e15f90cf5.png)
![05](https://cloud.githubusercontent.com/assets/15227034/10630994/72ace612-77e3-11e5-8a04-7ecdfebf3b49.png)
![06](https://cloud.githubusercontent.com/assets/15227034/10630942/37e4dc2e-77e3-11e5-9d44-c0cf9054fe13.png)

**Comment by BenOZ** [comment]
Стоит ждать тут помощи или нужно идти ножками и разбераться?

**Comment by dmitrijzabrudskij** [comment]
спасибо за информацию - ошибку с имейлом исправили в услуге получения справок о получении/неполучении помощи

по субсидиям - отправьте еще одну заявку с тем периодом, который запросила соцзащита, пожалуйста

**Comment by BenOZ** [comment]
Я же приложил скрины... Мне выдаёт короткую форму, заполнив которую на почту приходит два письма с сылкой, где нужно ввести логин и пароль: "Опрацюйте це звернення на порталі".
![01](https://cloud.githubusercontent.com/assets/15227034/10637850/82bab69c-7810-11e5-83e3-b3dc4b274c87.png)

**Comment by dmitrijzabrudskij** [comment]
короткая форма - это справка о получении/неполучении помощи

вы точно ее заказать хотите? или все-таки заявку на получение субсидии оформить хотите?

**Comment by BenOZ** [comment]
Я понял Вас...) Нужно подать заявку на получение субсидии! Я просто не смог найти нужную услугу сегодня - ещё раз проверил, но так и не нашёл её...
Ткните меня носом, пожалуйста! :)

**Comment by dmitrijzabrudskij** [comment]
в поиске сверху введите "субс" и Вы увидите услугу, которую ищете) ну а дальше авторизация и сама форма

**Comment by BenOZ** [comment]
Точно...) Завтра буду пробовать ещё раз...
Большое Вам спасибо за помощь и Ваши труды! :)

**Comment by dmitrijzabrudskij** [comment]
спасибо:-)

**Comment by s35mic** [comment]
Я подал заявку 01.10.2015 на получения субсидии.  В письмо было указано,  что ответ в течение 20 дней.  Срок истек. Статус - заявка подана и все.  Как узнать результат и когда?

**Comment by dmitrijzabrudskij** [comment]
в писье указано 20 рабочих дней
