### ISSUE TITLE
Отказ в получении загранпаспорта

### ISSUE THREAD

**Issue by ElizavetaM** [e-government-ua/iForum#360]
Здравствуйте! У меня сложилась такая ситуация: оформила заявку на загранпаспорт, собрала документы, оплатила взносы в приватбанке, когда приехала на место получения подачи документов, работник службы отказал в приеме моих документов ссылаясь на то, что кассир в банке провел платеж неправильно, т.е. в госслужбу деньги зашли, но конкретно на ее филиал они не поступили. Работник службы отправила меня обратно в банк, чтобы мне пробели цифры ее филиала. Когда я приехала в банк, показала квитанции платежа, объяснила ситуацию, работники банка мне сказали, что все реквизиты указаны верно и нет нужды в этих цифрах, тк деньги потом перераспределяются по филиалам. Подскажите, пожалуйста, что мне в этой ситуации делать? Данная ситуация произошла по адресу: Днепропетровский район, смт. Ювілейне, вул. Совхозна, 38. Кабинет № 3. Дата та час візиту: 2016-05-12 09:30:00.00. Заявка № 0-172779015

**Comment by Koffeek** [comment]
@ElizavetaM Если Вы неверно оплатили админуслугу (вбили не тот код подразделения), то действительно могут попросить переделать квитанцию, это зависит от начальника отделения. Дело в том, что при внутренней проверке у них обращают внимание на код подразделения в квитанции. Поведение сотрудников банка в данной ситуации непонятно. Вам удалось подать анкету?

**Comment by ElizavetaM** [comment]
Нет, так как оставалось мало времени: часть  времени она разговаривала по телефону, потом объясняла, что не так в квитанции, и я не успела оформить документ, тк пришла очередь нового посетителя, и мне сказали, что времени не осталось.

**Comment by Koffeek** [comment]
@ElizavetaM Связались с отделением. Действительно им принципиально, чтобы был в квитанции прописан код подразделения. Вам необходимо попросить сотрудника банка добавить его на квитанцию и потом прийти для оформления. Чтобы не стоять в общей очереди можете подать ещё одну заявку через портал.

**Comment by ElizavetaM** [comment]
Спасибо, но платеж уже прошел и банк не может добавит цифры филиала в перевод.

**Comment by Koffeek** [comment]
@ElizavetaM Я так понял, что им важно иметь квитанцию в которой будет номер подразделения. Сможет ли банк перепечатать квитанцию в таком виде?

**Comment by ElizavetaM** [comment]
Нет, тк платеж уже прошел и банк перепечатать не может.

**Comment by Koffeek** [comment]
@ElizavetaM Сегодня пятница, поэтому в ДМС уже никого нет. Я в понедельник попробую ещё раз связаться с ними и как-то решить Ваш вопрос. По итогу отпишу здесь. Спасибо.

**Comment by ElizavetaM** [comment]
Спасибо большое!

**Comment by ElizavetaM** [comment]
Здравствуйте! Позвонила в приватбанк сегодня, объяснила ситуацию, оператор приватбанка отправил запрос на возврат средств. Сказали, что в течении 21 дня, должно все решиться. Спасибо большое за помощь.
