### ISSUE TITLE
№ 0-142265749  Заявка  на   субсидию подана 22.03.16 статус заявки" Взяти до роботи" и никаких действий  больше нет .Что делать дальше?

### ISSUE THREAD

**Issue by 777leon** [e-government-ua/iForum#361]

**Comment by dmitrijzabrudskij** [comment]
какой район какой области выбирали при подаче?

**Comment by 777leon** [comment]
ленинский район  г. днепропетровск. 

13 мая 2016, 10:37:55, от "dmitrijzabrudskij" < notifications@github.com >: 

какой район какой области выбирали при подаче? —

**Comment by dmitrijzabrudskij** [comment]
с Вами район связался с уточнением какой справки не хватает?

**Comment by 777leon** [comment]
район связался после обращения к вам.Справки все есть ,идем к завершению ,Спасибо ВАМ!!!!!!

**Comment by dmitrijzabrudskij** [comment]
обращайтесь)
