### ISSUE TITLE
Для формы "Зняття з реєстрації місця проживання" в городе Киеве доступно всего 3 района

### ISSUE THREAD

**Issue by imposeren** [e-government-ua/iForum#362]
При заполнении формы есть обязательное поле "*Район м. Києва, в якому ви зареєстровані:". И там всего 3 района: Деснянский, Соломенский, Шевченковский. Для жителей остальных районов эта услуга не предоставляется?

**Comment by annastolbova** [comment]
зараз місто Київ взагалі припинило співпрацю по цих послугах
