### ISSUE TITLE
термін розгляду заяви по реєстрації ТОВ

### ISSUE THREAD

**Issue by PavloLobanov** [e-government-ua/iForum#364]
Скажіть будь ласка який термін розгляду заяви по реєстрації ТОВ???
Я подав заяву 0-228951685 11.05 о 9:26
Коли я можу отримати по ній відповідь?

**Comment by dmitrijzabrudskij** [comment]
вообще срок рассмотрения заявлений 1 рабочий день. но в виду новизны и популярности услуги сейчас он не выдерживается:( 
извините за неудобства, над этим мы работаем
заявку будет рассмотрена в ближайшее время

**Comment by PavloLobanov** [comment]
А приблизно зорієнтувати по термінах не зможете мене? для мене дуже важливо

**Comment by dmitrijzabrudskij** [comment]
она уже в работе - или сегодня, или в понедельник отработают

**Comment by PavloLobanov** [comment]
а там все ок з документами? :) все правильно подано? боюсь щоб не виникло якогось нюансу, бо дуже треба з 1.06 стати платником ПДВ :)

**Comment by dmitrijzabrudskij** [comment]
не могу сказать наверняка. в понедельник будет точно понятно.

**Comment by PavloLobanov** [comment]
Доброго дня! Чи є якісь новини по моїй заявці?

**Comment by dmitrijzabrudskij** [comment]
добрый день!

с самой заявкой все нормально, но, к сожалению, возникла ошибка наложения эцп на нее в момент подачи.
Вы могли бы создать новую заявку и сбросить ее номер сюда - сразу пущу в работу

**Comment by PavloLobanov** [comment]
зараз зроблю. документи треба по новій завантажувати всі?
Ви мене платником ПДВ зареєструєте з 1.06?

**Comment by PavloLobanov** [comment]
вже другий раз пробую завантажити і мене вибиває з системи

**Comment by PavloLobanov** [comment]
третій раз!
An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by PavloLobanov** [comment]
0-241080893 нове звернення! дуже дуже чекаю на відповідь. треба вже підписувати договори

**Comment by dmitrijzabrudskij** [comment]
и на этой заявке нет наложенной эцп. где Вы ее получали?

**Comment by PavloLobanov** [comment]
в приват банку. я наклав підпис. власне принакладенні підпису і виникали збої, але зараз все пройшло

**Comment by dmitrijzabrudskij** [comment]
попробуйте почистить кеш и куки браузера и переподать заявку с подписанием эцп

**Comment by PavloLobanov** [comment]
я встигну зареєструватись платником ПДВ з 1.06 чи ні? ви нічого ще внесли в єдр?

**Comment by dmitrijzabrudskij** [comment]
ничего не внесли. эцп на заявке нету. поэтому с ней не могут начать работать

**Comment by Tanya-Linza** [comment]
Подскажите, пожалуйста, когда можно будет получить ответ по заявке № 0-237764051 / 13.05.2016
Все ли там правильно заполнено? На почту (кроме первого письма про регистрацию) ничего не приходит.

**Comment by dmitrijzabrudskij** [comment]
она уже в работе - завтра/послезавтра будет ответ

**Comment by OlenaManuylyk** [comment]
Доброго дня, прошу сказати, коли буде опрацьована заявка за № 0-236057601. зареєстрована ще 13.05.2016р

**Comment by Jurcon** [comment]
Доброго ранку!
Таж сама проблема. Заявка № 0-249861043. Подано 19.05.2016 в 17:44. Місцезнаходження: м. Харків.
Можливо в мене теж помилка ЕЦП?

**Comment by agerman-ua** [comment]
@PavloLobanov 
Заявка №0-241080893 - отказ. Об этом должно было прийти письмо. Причина: повтор заявки №258112842
Заявка №0-258112842 закрыто успешно 26/05/2016. Поздравляем. Удачи.

@OlenaManuylyk 
Заявка №0-237764051 - отказ. Причина: Шановний заявник, Ви не коректно заповнили поля з адресою проживання. Разом з тим, повідомляємо, що для обрання третьої групи Вам необхідно до заяви про державну реєстрацію ФОП додати заповнену заяву про застосування спрощеної системи оподаткування де і зазначити бажану групу.

@Jurcon 
Заявка № 0-249861043 - отказ. Причина: на статуі відсутні електронні підписи всіх учасників підприємства (це обов'язкова умова обробки заявки)
Отказ некорректный. Такого требования от регистраторов изначально не было.

С уважением, Август.
