### ISSUE TITLE
Статус заявки - Закрыта

### ISSUE THREAD

**Issue by GossUA** [e-government-ua/iForum#366]
Надання довідки про відсутність або наявніcть судимості
Ваша заявка №0-176026115 змiнила свiй статус на закрита.

Что это значит? Никаких дальнейших инструкций на имейл не приходило.

**Comment by kurbpa** [comment]
Ваша заявка обработана.
Справка готова. с 12.05.2016 
Можете получить по адресу м. Дніпропетровськ, вул. Ворошилова, 21 з 15.00 до 17.00 
з оригіналом та копією паспорта.

К сожалению,  видимо при отправке емейла произошла ошибка.
