### ISSUE TITLE
ФОП живу в Киеве прописка в Харькове - ехать в харьковскую налоговую?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#367]
https://www.facebook.com/igov.org.ua/posts/1695617230727153?comment_id=1703917266563816&comment_tracking=%7B%22tn%22%3A%22R0%22%7D

Таня К:
>Подскажите, пожалуйста. У меня прописка в Харькове, а живу в Киеве. Хочу оформить онлайн ФОП, но останавливает примечание; "Стати на облік до податкової можна в будь-який момент після реєстрації та до самого початку діяльності підприємства." Я правильно понимаю, все равно нужно будет ехать в харьковскую налоговую?

**Comment by dmitrijzabrudskij** [comment]
в том случае, если Вы добавите к заявке заявление на постановку на учет в налоговую, ехать никуда не нужно будет - Вас и зарегистрируют, и поставят на учет в налоговой/пенсионном по месту прописки

фраза "Стати на облік до податкової можна в будь-який момент після реєстрації та до самого початку діяльності підприємства." добавлена для тех предпринимателей, которые не будут вместе с регистрацией начинать деятельность - они могут стать на учет (и, соответственно, платить налоги) позже

**Comment by Tanya-Linza** [comment]
Возникли сложности в поиске заявки - не знаю как она должна выглядеть. Боюсь заполнить не правильную. Помогите, пожалуйста! Где найти нужный шаблон? Или может у Вас есть образец?
Заранее спасибо

**Comment by agerman-ua** [comment]
@Tanya-Linza 
Звернення № 0-237764051 - отказ.
Причина: Шановний заявник, Ви не коректно заповнили поля з адресою проживання. Разом з тим, повідомляємо, що для обрання третьої групи Вам необхідно до заяви про державну реєстрацію ФОП додати заповнену заяву про застосування спрощеної системи оподаткування де і зазначити бажану групу.
