### ISSUE TITLE
Нет ответов с ЕГР МВД

### ISSUE THREAD

**Issue by Serg2090** [e-government-ua/iForum#368]
Добрый день! Скажите, пожалуйста, почему нет ответов с реестра МВД. Заявка меняет статус на "закрыта", а ответ не приходит.

**Comment by Serg2090** [comment]
До 1.05.16 ответы приходили,  в спам не попадает.

**Comment by kurbpa** [comment]
Добрый день.
 подскажите пожалуйста какое емейл использовался?

**Comment by Serg2090** [comment]
serg2090@gmail.com

**Comment by annastolbova** [comment]
зараз, навіть, якщо не приходять листи в спам, вся історія доступна в журналі по заявці.
https://igov.org.ua/journal
