### ISSUE TITLE
Реалізація входу через интернет-банкінг ФІДОБАНКу

### ISSUE THREAD

**Issue by nkartovskaya** [e-government-ua/iForum#37]
Добрий день, 
ФІДОБАНК є у списку банків, але вхід через його інтернет-банкінг ще не реалізовано. З ким можна було б контактувати, щоб обговорити цю тему? Я працюю у ФІДОБАНКу, можу організувати зустріч. Мої контакти: Надія Картовська, +380965633354, NadiiaI.Kartovska@fidobank.ua. Дякую.

**Comment by VadymVolos** [comment]
Ось тут це питання піднімалося https://github.com/e-government-ua/i/issues/872 

Як виявилось BankID - це не наше...
Жук Сергію можна написати...

https://bankid.org.ua/ (info@bankid.org.ua)

**Comment by nkartovskaya** [comment]
Дякую за інформацію!
