### ISSUE TITLE
Реестрація ФОП - успіх (інструкція)

### ISSUE THREAD

**Issue by mastir** [e-government-ua/iForum#371]
Почну спочатку для тих хто отримує відповіді з неінформативними коментарями від держ службовців "не коректно заповнена заява" і тп . Основна проблема (крім помилок в самій формі реестрації які вже виправили) це застаріла форма на єдиний податок, мені допомогла сторінка http://byhgalter.com/priklad-zapovnennya-zayavi-na-yedinij-podatok-zayava-pro-vibir-sproshheno%D1%97-sistemi-opodatkuvannya/ там є більшість необхідної інформації, також необхідно вказувати **УСІ** КВЕДи, я просто додав полів у таблицю. Хоч і в формі написано кведи 2005, заповнюємо актуальні кведи:2010 (я ще й в заяві виправив цю строку)

Після успішної реестрації приходить лист:

> Ваше звернення на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін.
> 
> Унікальний номер "Код" : (_тут ваш код_).
> 
> У будь-який час Ви можете отримати результат наданих адміністративних послуг використавши "Код" під час пошуку на офіційній сторінці Міністерства юстиції України.
> 
> Вам направлена копія рішення (додаток до листа).

в копії рішення теж є цей код, коли переходимо на сайт мінюсту і вводимо код: 
Результат надання адміністративних послуг

> Найменування: (_тут ваше ФІО_)
> Реєстраційна дія: Державна реєстрація фізичної особи-підприємця
> Дата дії: (_тут ваша дата реестрації_)
> 
> Документи:
> Відомості відсутні.

в реестрі дійсно можно знайти себе (написано по ФІО, або фамілії і ініціалалам, по факту знаходить тільки по фамілії, якшо вказати ініціали або імя - результатів нема)

для фомрування виписки на сайті мінюсту переходимо до "платний запит" ( https://usr.minjust.gov.ua/ua/paidextract ) і платимо 50грн, скачуемо витяг за номером який нам дали при сплаті. До "повного пакету" залишаеться виписка з налогової.

**Comment by agerman-ua** [comment]
Доброго дня, @mastir 
Щиро дякую за зворотній зв'язок. За довіру. Хоч подяка і з запізненням.
Бажаю успіхів. Впевнений багатьом Ваша інструкція допомогла. 
Просто вони дуже зайняті і не встигли подякувати. :)
Буду додатково користуватися посиланням на цю статтю.
З повагою, Август.

**Comment by YuriyPolo** [comment]
Доброго дня, хочу для себе дещо прояснити, якщо іде реєстрація ФОП і потрібно завантажити заяву про застосування спрощеної системи оподаткування  в якій треба вказати дані про ФОП, отримуємо замкнене коло, допоможіть розібратися?

**Comment by agerman-ua** [comment]
Доброго дня,  @YuriyPolo 
В чому саме проблема? Пишемо та обираємо в заяві на спрощену тільки те що відомо.
Робіть окрему тему. Обговоримо там проблему.
З повагою, Август.

**Comment by YuriyPolo** [comment]
я не знаю чи це проблема, просто я на цьому стопорнувся, спробуємо ці поля пропустити

**Comment by agerman-ua** [comment]
Думаю якщо подивитися навкруги знайдеться або бухгалтер або ФОП. Запитай в них.

**Comment by YuriyPolo** [comment]
Тут мова про реєстрацію через  https://igov.org.ua/service/1495/general  , думаю бухгалтер точно непоможе ))

**Comment by agerman-ua** [comment]
Заява на спрощену не має відмінностей від звичайного, паперового.
