### ISSUE TITLE
санпаспорт на прицеп-рефрежиратор

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#372]
а подскажите данная услуга присутствует в списке?
или ее планируется добавить?

**Comment by zolotovatatyana** [comment]
Здравствуйте. 
На данный момент СЭС находится в состоянии реорганизации в ДержСпоживСлужбу. 
Когда нормальный режим работы госоргана снова будет восстановлен, новые инфокарты написаны - мы обязательно займемся разработкой этой услуги.
