### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by Fichtenbaum** [e-government-ua/iForum#373]
Подскажите статус моей заявки 0-233171146 до сих пор в обработке, посмотрела в "Єдиний державний реєстр юридичних осіб, фізичних осіб-підприємців" и нашла себя там, это означает что ответ положительный? Или необходимо дождаться ответа на почту?

**Comment by dmitrijzabrudskij** [comment]
да. Вам было отправлено письмо о регистрации через 10 минут после этого поста
