### ISSUE TITLE
Державна реєстрація змін до відомостей про фізичну особу – підприємця

### ISSUE THREAD

**Issue by psergei** [e-government-ua/iForum#374]
> Ваша заявка №0-240627436 змiнила свiй статус на Надання послуги (2). 

Заявка теперь закрыта.
На мыло пришло сообщение что надо оплатить. У меня уже есть квитанция об оплате соответствующей суммы за госрегистрацию изменений. Мои дальнейшие действия?

**Comment by Ksellos** [comment]
Заявка № 0-240243487, уже второй день висит: Заявка подана - Перевірка наданих даних.
Согласно https://usr.minjust.gov.ua, изменения в реестр до сих пор не внесены.
В заявке указывалось только изменение контактных данных.

**Comment by dmitrijzabrudskij** [comment]
@psergei а в адрес какого регистратора Вы платили? или Вы уже ранее обращались для проведения этой процедуры куда-то еще?

**Comment by dmitrijzabrudskij** [comment]
@Ksellos потерпите, пожалуйста - слишком большой наплыв заявок получился

**Comment by psergei** [comment]
@dmitrijzabrudskij Да, я ранее платил админ сбор в Харькове, но провести процедуру не удалось, т.к. у меня были проблемы с регистрацией в паспорте из-за переименования улицы.

**Comment by dmitrijzabrudskij** [comment]
@psergei как давно это было? спрашиваю, потому что заявителю дается 14 календарных дней на донесение нужных документов (паспорта с правильным штампом в Вашем случае) - если они еще не истекли, то Вам нужно обращаться туда же в Харькове для завершения процедуры. Если же прошли, то нужно платить заново

эта комиссия поступает в районный бюджет и тот госорган, который оказывает услугу, не может проводить операцию, если оплатили не в его район. вот такая ситуация

**Comment by psergei** [comment]
@dmitrijzabrudskij это было аж 16 марта. Процедура вообще не была начата, меня сразу отослали в паспортный стол, а потом я забил на это дело и не было времени опять пол дня у регистратора в очереди сидеть, решил дождаться когда уже iGov это дело запустит. Вот и дождался :) Вообщем ладно, если я сейчас оплачу - то все получится?

**Comment by dmitrijzabrudskij** [comment]
@psergei конечно получится:) один вопрос - у Вас в паспорте значится номер дома 47/1 и корпус пустой, а в заявке дом 47 корпус 1 - как правильно?

**Comment by psergei** [comment]
@dmitrijzabrudskij  Сложно сказать, если написано что номер дома 47/1 - имеется ввиду 47 и корпус 1, или корпуса нет, а это номер дома такой через слеш. Местный регистратор говорил это корпус все-таки. я затрудняюсь сказать как правильно.

**Comment by dmitrijzabrudskij** [comment]
@psergei ок, тогда сделают как в заявке - с корпусом

**Comment by psergei** [comment]
@dmitrijzabrudskij может тогда лучше чтобы с паспортом совпадало, раз уж в паспорте корпуса нет, а просто 47/1. Мне новую заявку создать или эту можно подправить?

**Comment by dmitrijzabrudskij** [comment]
@psergei в таком случае новую нужно. как сделаете - сбросьте номер сюда. по новой заявке придет новое письмо для оплаты - по нему и нужно будет оплатить (это важно. информация о платеже тянется в ту заявку, из которой было отправлено письмо)

**Comment by psergei** [comment]
@dmitrijzabrudskij ОК, новая заявка № 0-247562387

**Comment by dmitrijzabrudskij** [comment]
@psergei отправили новое письмо для оплаты. старую заявку закрыли как повторную

**Comment by psergei** [comment]
@dmitrijzabrudskij готово, оплатил

**Comment by agerman-ua** [comment]
Добрый вечер, 23.05.2016 заявка успешно закрыта. 
Поздравляем и спасибо за понимание.
