### ISSUE TITLE
Не обработаны заявки по услугам ГФС уже почти месяц

### ISSUE THREAD

**Issue by Ksellos** [e-government-ua/iForum#376]
Заявка № 0-189408396 от 25.04.2016 - Довідка про відсутність заборгованості з податків, зборів, платежів, що контролюються органами доходів і зборів. Уже почти месяц висит со статусом "Заявка подана - надання адміністративної послуги". Уточнял непосредственно в ГНИ, которую указывал при оформлении заявки, ответили, что ничего не получали и не про какой такой iGov вообще не в курсе.
Заявка № 0-189179572 от 25.04.2016 - Надання витягу з реєстру платників єдиного податку. Также уже почти месяц ни ответа, ни привета, висит со статусом "Заявка подана - надання адміністративної послуги".

**Comment by dmitrijzabrudskij** [comment]
какая это налоговая?

**Comment by Ksellos** [comment]
Ленинская (0467), г. Днепропетровск.

**Comment by GrekD** [comment]
@YmNIK13 можешь, проверить, пожалуйста?

**Comment by annastolbova** [comment]
заявка вже закрита
