### ISSUE TITLE
Получение загранпаспорта

### ISSUE THREAD

**Issue by Vitalina88** [e-government-ua/iForum#378]
Не могу зайти через систему BankID...пробую зайти через приватбанк, но он мне выдает ошибку...в миграционной службе не знают, что за проблема...в приватбанке тоже (сверяли все данные у них)...в итоге не могу пройти аутентификацию, чтоб в дальнейшем получить квитанцию и занять очередь...

**Comment by AndreyPopovNew** [comment]
ну а в Приват24 вы попадаете нормально?

может вы вводили неправильный пароль и после трех раз аккаунт блокируется и требуется восстановление аккаунта.

**Comment by dmitrijzabrudskij** [comment]
@Vitalina88 какая ошибка?

**Comment by Vitalina88** [comment]
Вот такая ошибка  -- С уважением,Шевченко В.Ю.

**Comment by Vitalina88** [comment]
-- С уважением,Шевченко В.Ю.

**Comment by dmitrijzabrudskij** [comment]
@Vitalina88 ничего не вижу - попробуйте еще раз прикрепить скрин или описание

**Comment by Vitalina88** [comment]
Прикрепляю скрин

19.05.2016, 18:54, "dmitrijzabrudskij" <notifications@github.com>:
> @Vitalina88 ничего не вижу - попробуйте еще раз прикрепить скрин или описание
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Шевченко В.Ю.

**Comment by dmitrijzabrudskij** [comment]
все равно ничего нет

**Comment by Vitalina88** [comment]
Отправляю скрин jpg   -- С уважением,Шевченко В.Ю.

**Comment by Vitalina88** [comment]
šš÷ĎÔ ÔĹËÓÔ ĎŰÉÂËÉAn error occurred.Sorry, the page you are looking for is currently unavailable.Please try again later.If you are the system administrator of this resource then you should check theerror logšfor details.Faithfully yours, nginx.ššš-- ó Ő×ÁÖĹÎÉĹÍ,űĹ×ŢĹÎËĎ ÷.ŕ.š

**Comment by Vitalina88** [comment]
AndreyPopovNew в приват24 без проблем

**Comment by Vitalina88** [comment]
š÷ĎÔ ÔĹËÓÔ ĎŰÉÂËÉAn error occurred.Sorry, the page you are looking for is currently unavailable.Please try again later.If you are the system administrator of this resource then you should check theerror logšfor details.Faithfully yours, nginx.ššš-- ó Ő×ÁÖĹÎÉĹÍ,űĹ×ŢĹÎËĎ ÷.ŕ.š

**Comment by dmitrijzabrudskij** [comment]
067971**50 - Вы с этим телефонов пробуете залогиниться? мы его в логах не находим. попробуйте все-таки скрин прикрепить. или скажите с каким номером и во сколько получили последнюю ошибку

**Comment by Vitalina88** [comment]
Мой телефон 09552***70

20.05.2016, 10:14, "dmitrijzabrudskij" <notifications@github.com>:
> 067971**50 - Вы с этим телефонов пробуете залогиниться? мы его в логах не находим. попробуйте все-таки скрин прикрепить. или скажите с каким номером и во сколько получили последнюю ошибку
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Шевченко В.Ю.

**Comment by dmitrijzabrudskij** [comment]
dmitrij.zabrudskij@gmail.com
бросьте сюда полный номер и дату/время когда ошибка выскакивала

**Comment by Vitalina88** [comment]
Сегодня в 10.18

20.05.2016, 10:19, "dmitrijzabrudskij" <notifications@github.com>:
> dmitrij.zabrudskij@gmail.com
> бросьте сюда полный номер и дату/время когда ошибка выскакивала
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Шевченко В.Ю.

**Comment by Vitalina88** [comment]
https://igov.org.ua/auth/bankID/callback?link=https://igov.org.ua:443/service/176/general/place/built-in/region/1/city/0&code=BsucIa34181

20.05.2016, 10:19, "dmitrijzabrudskij" <notifications@github.com>:
> dmitrij.zabrudskij@gmail.com
> бросьте сюда полный номер и дату/время когда ошибка выскакивала
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Шевченко В.Ю.

**Comment by dmitrijzabrudskij** [comment]
вы в почту можете написать полный номер?

**Comment by Vitalina88** [comment]
0955292170

20.05.2016, 10:29, "dmitrijzabrudskij" <notifications@github.com>:
> вы в почту можете написать полный номер?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Шевченко В.Ю.

**Comment by dmitrijzabrudskij** [comment]
попробуйте сейчас

**Comment by Vitalina88** [comment]
та же самая ошибка(

20.05.2016, 12:05, "dmitrijzabrudskij" <notifications@github.com>:
> попробуйте сейчас
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Шевченко В.Ю.

**Comment by dmitrijzabrudskij** [comment]
попробуйте еще раз

**Comment by Vitalina88** [comment]
Ура, спасибо ВАМ БОЛЬШОЕ

20.05.2016, 14:07, "dmitrijzabrudskij" <notifications@github.com>:
> попробуйте еще раз
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
Шевченко В.Ю.

**Comment by dmitrijzabrudskij** [comment]
отлично!
пожалуйста

**Comment by Vitalina88** [comment]
Здравствуйте, подскажите, что делать если не снялись отпечатки паспорта для биометрического паспорта?   -- С уважением,Шевченко В.Ю.
