### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by Hanna033** [e-government-ua/iForum#379]
Что с этой заявкой? 0-247026742 статус: закрыта, но в реестре нет данных(

**Comment by dmitrijzabrudskij** [comment]
Причина:Відповідно до статті 15 Закону України "Про державну реєстрацію юридичних осіб, фізичних осіб-підприємців та громадських формувань" документи мають бути викладені державною мовою та додатково, за бажанням заявника, - іншою мовою (крім заяви про державну реєстрацію) В розділі "Країна громадянства" необхідно вказати громадянство заявника українською мовою. При виправлені зауважень, Ви можете повторно звернутися за отриманням даної адміністративної послуги.

такой ответ Вам вчера отправили

подайте новую заявку, пожалуйста - при подаче исправьте страну на Україна в форме подачи заявки

**Comment by Hanna033** [comment]
Большое спасибо!
