### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by 40257791** [e-government-ua/iForum#381]
Добрый день. Подскажите пожалуйста информацию по заявке: 0-246483824 ? Подали 18.05, но никакой информации нету. Спасибо.

**Comment by 40257791** [comment]
@dmitrijzabrudskij пожалуйста, подскажите стадию рассмотрения. Спасибо =)

**Comment by dmitrijzabrudskij** [comment]
добрый день
взяли в работу

**Comment by 40257791** [comment]
Добрый день. Получили отказ по текущей заявке. Подали новую под № 0-253986611 . Её провели. Регистрация прошла успешно. Выдали уникальный код, но по уникальному коду выписку скачать невозможно, т.к. она отсутствует. Подскажите как быть?

**Comment by dmitrijzabrudskij** [comment]
добрый день
подождать
выписка появится когда все остальные органы возьмут Вас на учет

**Comment by 40257791** [comment]
По сайту https://usr.minjust.gov.ua/ua/freesearch еще вчера все взяли. Может забыли выписку распечатать?) Спасибо.

**Comment by dmitrijzabrudskij** [comment]
налоговая
пенсионный фонд
статистика

я их подразумевал под "остальными органами"
