### ISSUE TITLE
Что делать если на втором шаге войти в систему через BankID в списке нет твоего банка?

### ISSUE THREAD

**Issue by krsevi** [e-government-ua/iForum#382]

**Comment by alex-xander-dp-ua** [comment]
Нужно или завести карточку в Приватбанке или обратиться в свой банк и потребовать от него подключиться к BANKID?

Или есть ещё варианты? :)

**Comment by dmitrijzabrudskij** [comment]
еще можно оформить себе эцп и авторизовываться с ней

**Comment by krsevi** [comment]
Как не крути а прейдется идти в Приватбанк
