### ISSUE TITLE
Реєстрація ФОП 

### ISSUE THREAD

**Issue by LidiaKach** [e-government-ua/iForum#383]
Добрий день. Підкажіть інформацію по заявці : 0-244218634 ? Подали 17.05, статут заявки "В обробці".

**Comment by LidiaKach** [comment]
Можна  взнати що там з заявкою? В роботі чи ні? Чи все правильно заповнено. 
Дякую.

**Comment by agerman-ua** [comment]
24.05.2016 звернення оброблено.
