### ISSUE TITLE
Регистрация фоп на http://rp.irc.gov.ua/

### ISSUE THREAD

**Issue by travka** [e-government-ua/iForum#384]
Подскажите поажлуйста, я подал заявление на фоп на этом портале, но не прикрепил заявление на переход на упрощенный налог, можно ли подать это заявление у вас?

**Comment by dmitrijzabrudskij** [comment]
отдельно - нет. только полная заявка на регистрацию

**Comment by travka** [comment]
Т.е если я зарегистрировался уже и скину вам заново полностью заявку, вы предоставите только заявку на упрощенный налог ?

**Comment by dmitrijzabrudskij** [comment]
уже нет. теперь Вам через налоговую это нужно делать
