### ISSUE TITLE
Довідка про відсутність або наявніcть судимості

### ISSUE THREAD

**Issue by simonych** [e-government-ua/iForum#385]
Очікую замовлену за допомогою IGOV "Довідку про відсутність або наявніcть судимості". 
На запитання зроблені у системі IGOV ніхто не відповідає 
У який термін вона повинна бути готова? 

Місто Дніпропетровськ.
Звернення № 0-228991627.
Дата замовлення: 11/05/2016

**Comment by GrekD** [comment]
@kurbpa  посмотри, пожалуйста

**Comment by kurbpa** [comment]
https://igov.org.ua/service/1/instruction - Обратите внимание на последний раздел

```
Зверніть увагу:
Зараз довідку можна отримати тільки в паперовому вигляді. Але ми працюємо над можливістю замовлення електронної копії з накладеним електронно-цифровим підписом МВС України.
Термін оброблення звернення складає до 20 робочих днів.
```

**Comment by simonych** [comment]
Дякую. Інструкцію бачив. Спатнеличує відсутність відповіді, коли, ставлю запитання безпосередньо у зверненні.
