### ISSUE TITLE
Не обрабатывается заявка на Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн), уже неделю

### ISSUE THREAD

**Issue by Ksellos** [e-government-ua/iForum#386]
Заявка № 0-240243487 от 16.05.2016 на Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн), уже неделю висит со статусом: Заявка подана - Перевірка наданих даних.
В заявке было изменение только контактных данных.
По информации с https://usr.minjust.gov.ua, изменения также до сих пор не внесены.

**Comment by dmitrijzabrudskij** [comment]
она уже в работе. ответят в течение пары дней

**Comment by Ksellos** [comment]
Статус изменился на Заявка закрита - Надання послуги. Но судя по информации с https://usr.minjust.gov.ua, изменения не внесены.

**Comment by dmitrijzabrudskij** [comment]
заявка еще в работе. ждите имел с уведомлением о проведенных изменениях

**Comment by agerman-ua** [comment]
25.05.2016 обработана.
