### ISSUE TITLE
Довідка про відсутність судимості - Сервіс працює?

### ISSUE THREAD

**Issue by adrenalin2003** [e-government-ua/iForum#387]
Скажіть, чи працює сервіс " Надання довідки про відсуність судимості".
Подав два запити, жодної реакції. Діалог теж відсутній.
Звернення № 0-247559235
Звернення № 0-232017248.
І чому на сайті iGov відсутні правила або інструкції  щодо порядку розгляду звернень?
Дякую

**Comment by kurbpa** [comment]
> чому на сайті iGov відсутні правила або інструкції щодо порядку розгляду звернень?

 https://igov.org.ua/service/1/instruction - всё есть. Вс

> Подав два запити, жодної реакції. Діалог теж відсутній.
> Звернення № 0-247559235
> Звернення № 0-232017248.
