### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by FZR** [e-government-ua/iForum#388]
Звернення № 0-241639125
с 16.05.2016. 
--- Заявка подана - Надання послуги. (в обробцi) ----

Можно пожалуйста узнать статус моего обращения? Живой не живой? Все ли у меня там правильно заполнено. 

Спасибо

**Comment by FZR** [comment]
@dmitrijzabrudskij Подскажите пожалуйста статус моего заявления. Скоро деньги получать и пока не знаю что делать т.к. нету ФОП. 
Спасибо

**Comment by dmitrijzabrudskij** [comment]
уже в работе. в течение пары дней будет ответ

**Comment by FZR** [comment]
Большое спасибо!

**Comment by agerman-ua** [comment]
25.05.2016 закрыта. Поздравляем.
