### ISSUE TITLE
Регистрация ФОП

### ISSUE THREAD

**Issue by Hanna033** [e-government-ua/iForum#389]
Доброго Дня!
Маю номер звернення № 0-249453469
від 19.05.2016.
Підкажіть будь ласка, все добре і процес реєстрації такий довгий, чи щось не вірно?

**Comment by dmitrijzabrudskij** [comment]
добрый день
заявка в работе. пока никаких дополнительных движений не требуется - дождитесь ответа, пожалуйста

**Comment by GrekD** [comment]
Заява розглянута, прийнято негативне рішення
Причина: Шановний заявник! Заповніть поля заяви державною мовою та відкорегуйте адресу
