### ISSUE TITLE
проблема при отправке заявки на субсидию по ЖКХ

### ISSUE THREAD

**Issue by Rublevskiy** [e-government-ua/iForum#39]
зашел через BANKid, заполнил заявку, при нажатии "замовити послугу" ничего не происходит. 
Также нет графы с суммой дохода, это так и должно быть? 
Адрес - Никополь, банк - Приватбанк

**Comment by dmitrijzabrudskij** [comment]
проверьте те поля, которые должны быть строго цифровыми - например, количество этажей в доме - причина такого поведения может быть в них (когда вводите туда буквы).
да, сумма дохода не указывается - соцзащита все равно ее берет из отчета налоговой

**Comment by Rublevskiy** [comment]
Спаси Бог, получилось. Дело было в цифрах - десятичные нужно отделять точкой, а не запятой
