### ISSUE TITLE
Долго обрабатывается заявка

### ISSUE THREAD

**Issue by Ovoshchnikov** [e-government-ua/iForum#390]
Добрый день. Номер заявки 0-243406480 от 17.05.2016. Всё ещё в обработке. Когда ожидать ответ?

**Comment by GrekD** [comment]
Заява розглянута, прийнято негативне рішення
причина: некоректно вказана адреса в заяві: не вистачає району області, назви вулиці та номеру будинку. просимо подати нову заяви з вказанними даними
