### ISSUE TITLE
Не обрабатывается заявка на Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн)

### ISSUE THREAD

**Issue by apolinFOP** [e-government-ua/iForum#391]
Заявка № 0-248339070   от 19.05.2016 на Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн),  висит со статусом: Заявка подана - Перевірка наданих даних ( в обробці)
В заявке было изменение только квед.
Позвонила местному держреєстратору ( г.Киев, Святошинский р-н). Держреестратор даже не знает, о чем я говорю. Не знает о существовании такого сервиса, и убедительно утверждает, что никаких изменений в електронном виде произвести нельзя и она даже не знает куда смотреть, что бы увидеть мою заявку.

**Comment by Viktoriy** [comment]
По заяві 0-251538567 від 20.05.2016 на Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн), висит со статусом: Заявка подана - Перевірка наданих даних ( в обробці). Я хочу додати КВЕД. Але заявка висить в обробці. И коли можна дізнатись, що зміни внесено?

**Comment by dmitrijzabrudskij** [comment]
@apolinFOP потому что участвует в обработке электронных заявлений только Днепропетровская область. из-за наплыва желающих они и висят в обработке. потерпите, пожалуйста

@Viktoriy см ответ выше по поводу сроков. о результатах Вы будете оповещены по имейлу

**Comment by alex-xander-dp-ua** [comment]
Звернення № 0-252950695
21.05.2016
В обробці
Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн)
Заявка подана - Перевірка наданих даних (1)
===========
Прошу проверить - эта заявка именно в обработке или таки где-то проглючила и потерялась?

**Comment by Viktoriy** [comment]
Добрий день. Пройшло вже десять днів з моменту подання заяви 0-251538567 від 20.05.2016 на Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн), висит со статусом: Заявка подана - Перевірка наданих даних ( в обробці).  Але заявка висить в обробці. Коли всеж таки будуть внесені зміни? Чи може моя заявка загубилась?

**Comment by dmitrijzabrudskij** [comment]
добрый день
все заявки из этого топика уже в работе - подождите еще пару дней, пожалуйста

**Comment by apolinFOP** [comment]
Если я не с Днепропетровской обл., а с Киева, то мне можно и не ждать?

**Comment by dmitrijzabrudskij** [comment]
@apolinFOP тоже ждать. я вам писал про обработку ранее (что только Днепропетровская), подавать могут люди из любых областей

**Comment by alex-xander-dp-ua** [comment]
@dmitrijzabrudskij , какое-то уведомление по факту предполагается? Или нужно просто мониторить реестр?

Формат уведомления будет просто "нотификатор" или некая бумажка в PDF отправленная по почте или на емайл?

**Comment by dmitrijzabrudskij** [comment]
будет письмо на имейл с номером описи и сканом бумажки от госрегистратора

**Comment by Viktoriy** [comment]
Ваша заявка №0-251538567 змiнила свiй статус на закрита. Що це ?

**Comment by apolinFOP** [comment]
Моя заявка тоже закрыта № 0-248339070. Я не закрывала. Обьясните, что это?

**Comment by dmitrijzabrudskij** [comment]
Ваши заявки обработаны, на имейл отправлено уведомление о внесенных изменениях (если письма нет во входящих, проверьте спам)

**Comment by apolinFOP** [comment]
Огромное спасибо. Все есть. Я очень рада.
