### ISSUE TITLE
Реєстрація ФОП

### ISSUE THREAD

**Issue by zatsniyvlad** [e-government-ua/iForum#393]
Доброго дня!
Мій номер звернення - Звернення № 0-247023306.
Не проходить статус "надання послуги", в чому може бути справа?

**Comment by zatsniyvlad** [comment]
Не зрозумів де саме некоректно заповнена адреса, у заяві на спрощену систему оподаткування?

Шановний(-а) Владислав Олегович

Ваше звернення на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.

Коментар держслужбовця (некоректно заповнена адреса: не вистачає району області, назви вулиці та номеру будинку. просимо подати нову заяву з цими даними)

**Comment by dmitrijzabrudskij** [comment]
в заявке на регистрацию, которую вы заполняли на igov

**Comment by zatsniyvlad** [comment]
Підскажіть будь ласка, подав знову, коли буде опрацьовано?

**Comment by dmitrijzabrudskij** [comment]
номер новой заявки есть?

**Comment by zatsniyvlad** [comment]
Звернення № 0-260424672

**Comment by dmitrijzabrudskij** [comment]
сегодня-завтра

**Comment by agerman-ua** [comment]
02.06.2016 успешно закрыта.
