### ISSUE TITLE
Реєстрація ФОП

### ISSUE THREAD

**Issue by Kavun1985** [e-government-ua/iForum#394]
Заява № 0-247499356 в обробці з 19.05.2016. до цього часу немає жодної відповіді. 
Також у зв'язку із нестабільною роботою серверу, заявка відображається як подана тричі під різними номерами: № 0-247502749, № 0-247506139, № 0-247499356.
Що робити? Звернутися краще до реєстратора? Чи ця заява таки буде погоджена?

**Comment by dmitrijzabrudskij** [comment]
247499356 - в работе. 2 другие закрыты как повторные

**Comment by agerman-ua** [comment]
26.05.2016 успешно закрыта.
