### ISSUE TITLE
Регестрация ФОП

### ISSUE THREAD

**Issue by dimaosa** [e-government-ua/iForum#395]
Заявка 0-246889506 принята 18 травня. Статус вже 6 днів не змінювався. В чому може бути проблема? 
![screen shot 2016-05-24 at 10 30 59 am](https://cloud.githubusercontent.com/assets/8642157/15495764/b0036430-219a-11e6-92df-38d52908f13d.png)

**Comment by SvyatoslavLynda** [comment]
Така сама ситуація Звернення № 0-251409889 20.05.2016 В обробці.

**Comment by dmitrijzabrudskij** [comment]
обе в работе. дождитесь ответов, пожалуйста

**Comment by SvyatoslavLynda** [comment]
Спасибо, а не подскажете ориентировочное время регистрации?

**Comment by dmitrijzabrudskij** [comment]
завтра-послезавтра

**Comment by dimaosa** [comment]
Спасибо! Буду ждать

**Comment by dimaosa** [comment]
Зарегистрирован! Спасибо большое

**Comment by dimaosa** [comment]
Спасибо большое за регистрацию ФОП, но мне еще не прислали копию документов где указан код(регистрационный номер). Имейла с igov не было. Проверял свою регистрацию через https://usr.minjust.gov.ua/ua/freesearch .

**Comment by dmitrijzabrudskij** [comment]
имейл был отправлен 26.05 - проверьте еще в спаме на всякий случай
также только что со своего имейла отправил регистрационный код и копию выписки от регистратора

**Comment by dimaosa** [comment]
Спасибо, только что получил имейл от вас)) 
@dmitrijzabrudskij проверил спам и письмо оказалось там. Странно что гугл решил отправить это в спам, с учетом того что до этого с igov приходили во входящие.
