### ISSUE TITLE
не получается авторизоваться в bankid. ошибка: http://static.privatbank.ua/files/question_20052016_151135.png

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iForum#396]

**Comment by acras01** [comment]
Добрый день! Есть ли какие-то подвижки?

**Comment by dmitrijzabrudskij** [comment]
добрый день
эта тема была создана для того, чтобы вы вышли на связь - поэтому подвижек не было

напишите, пожалуйста, ваш логин в пр24 и дату/время последней попытки авторизоваться (и последовавшей ошибки, соответственно)

**Comment by acras01** [comment]
Извините, я, видимо, неправильно понял.
Логин - +380950056481
Вот только что еще раз попробовал - 31/05 14:51. Ошибка та же.

**Comment by dmitrijzabrudskij** [comment]
странно...
а можете еще раз попробовать с чистым кешем?

**Comment by acras01** [comment]
Очистил в хроме кэш, попробовал еще раз, та же ошибка

**Comment by acras01** [comment]
Добрый день! Вы смогли разобраться в этой проблеме?

**Comment by dmitrijzabrudskij** [comment]
добрый день!

да, ошибка при обработке Ваших данных - спасибо за пример, благодаря ему нашли у себя проблему, которую будем исправлять. к сожалению, это будет не быстро:(

поэтому если услуга нужна срочно, то прошу обратиться в госорган очно

**Comment by acras01** [comment]
Большой срочности нет, могу и подождать

**Comment by acras01** [comment]
Добрый день! Решена ли уже проблема?

1 июня 2016 г., 16:25 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by agerman-ua** [comment]
Добрый вечер, @acras01 
Простите за задержку с ответом.
Да, конечно, проблему устранили - если ещё вопрос Ваш актуален.
С уважением, Август.
