### ISSUE TITLE
Заява по реєстрації ФОП в обробці вже тиждень 

### ISSUE THREAD

**Issue by anastasiia2016** [e-government-ua/iForum#397]
Добрий день! Зі дня подання заяви на реєстрацію ФОП пройшов вже тиждень, чому так довго триває реєстрація? Звернення №0-244059643

**Comment by dmitrijzabrudskij** [comment]
добрый день
заявка уже в работе, дождитесь ответа, пожалуйста

**Comment by anastasiia2016** [comment]
Ваше звернення на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.

Коментар держслужбовця (Причина: Шановний завник! В поданих вами заявах різняться дані адреси місця проживання. Вам необхідно звернутись до вашого банку для актуалізації особистих даних.)

Скажите пожалуйста какого банка и при чем банк вообще? И какие адресса и чем друг от друга отличаются?
Спасибо

**Comment by dmitrijzabrudskij** [comment]
про банк написали, так как авторизуется львиная доля пользователей через bankid, и данные о прописке поставляет банк (соответственно, если она у вас менялась, то нужно обновить данные и в банке тоже)

конкретно по вашей заявке - у вас разные адреса прописки в самой заявке и в том заявлении на упрощенную систему налогообложения, которое вы прикрепили

**Comment by anastasiia2016** [comment]
При проверке адрес сходится
Я подала повторно, можете просмотреть все ли верно?

**Comment by dmitrijzabrudskij** [comment]
нет.
адрес в заявке г.Киев, а в заявлении на упрощенку Кременчуг
зачем вы меняете адрес при подаче заявки? указывайте адрес прописки

**Comment by anastasiia2016** [comment]
Адрес прописки Кременчук, я его указываю при подаче Заявки, он же стоит и в Заявлении на ЕН

**Comment by dmitrijzabrudskij** [comment]
а авторизуетесь вы через bankid или эцп?

**Comment by anastasiia2016** [comment]
Через ЭЦП

**Comment by dmitrijzabrudskij** [comment]
пройдите процедуру через bankid, пожалуйста
и сбросьте номер заявки сюда

**Comment by anastasiia2016** [comment]
Нет банковского ключа, к сожалению

**Comment by dmitrijzabrudskij** [comment]
при чем тут банковский ключ? зайти в заявку можно по данным вашего интернет-банка

**Comment by anastasiia2016** [comment]
0-264574182

**Comment by anastasiia2016** [comment]
Нет открытого счета не в одном банке

**Comment by dmitrijzabrudskij** [comment]
все-таки у нас глюк. спасибо - благодаря вашему примеру его увидели
заявку завтра возьмут в работу

**Comment by anastasiia2016** [comment]
Спасибо !

**Comment by anastasiia2016** [comment]
Здравствуйте, регистрация прошла успешно, но не правильно по итогу указали в данных номер дома - в заявлении и по факту прописка по адресу - ул.Киевская 59, а при приверке регистрации на сайте https://usr.minjust.gov.ua/ua/freesearch - номер дома - 54. Вы это можете исправить?

**Comment by dmitrijzabrudskij** [comment]
да, исправят. я отпишусь когда сделают

**Comment by anastasiia2016** [comment]
Еще раз спасибо!

**Comment by dmitrijzabrudskij** [comment]
исправили. номер описи: 373580595090

**Comment by anastasiia2016** [comment]
На сайте минюста поменялись данные, спасибо, но в эллекронном кабинете, все еще стоит 54 дом.
И не показывает что является плательщиком ЕН

**Comment by dmitrijzabrudskij** [comment]
вопрос к налоговой. изменения везде проведены.
