### ISSUE TITLE
Заявка на изменение регистрационных данных 5 дней без ответа

### ISSUE THREAD

**Issue by yavwork** [e-government-ua/iForum#398]
Здравствуйте, зарегистрировал заявку 0-252005781 20.05.2016 и тишина. Задаю вопросы - никто не реагирует. Это техническая проблемма или регистратор не хочет отвечать?

**Comment by dmitrijzabrudskij** [comment]
добрый день
ни то, ни другое - набралось большое количество желающих, из-за чего сейчас есть очередь на обработку. потерпите, пожалуйста - обработают

**Comment by dmitrijzabrudskij** [comment]
Добрый день!

Вам 25.05 отправлено письмо для оплаты услуги внесения изменений по заявке 252005781 (на всякий случай проверьте его в спаме)  - Вы будете оплачивать (без оплаты госрегистратор не может запустить процедуру)?

если не готовы сейчас, то скажите - текущую заявку закроют, и в будущем нужно будет оплачивать уже после подачи новой заявки (из письма, которое Вам по ней придет)

**Comment by agerman-ua** [comment]
17.06.2016 закрыта заявка.
