### ISSUE TITLE
Регистрация ФЛП в статусе переселенца

### ISSUE THREAD

**Issue by Propeller-SV** [e-government-ua/iForum#399]
Какой адрес указывать переселенцу с донецкой пропиской в заявлениях? Реально ли вообще пройти все процедуры в таком статусе при помощи iGov?

**Comment by dmitrijzabrudskij** [comment]
регистрация проходит либо по месту прописки, либо по месту проживания. поэтому пробуйте

**Comment by Propeller-SV** [comment]
30 мая подал заявку № 0-277581305. Если не затруднит проверьте взята ли в работу, пожалуйста.

**Comment by Propeller-SV** [comment]
Подскажите пожалуйста, когда можно ожидать какой-нибудь результат по вышеуказанной заявке?

**Comment by Propeller-SV** [comment]
Что-то даже отвечать стали не так живо. Захлебывается сервис, похоже. Процесс хоть идёт? Кого-то регистрируют успешно? Дайте знать хотя бы когда процедура будет требовать больше 2 недель, пожалуйста.

**Comment by dmitrijzabrudskij** [comment]
процесс идет. тот район, которому была назначена ваша заявка, саботирует работу - из-за этого переназначил ее на другой. дождитесь ответа, пожалуйста (еще день-два)

**Comment by Propeller-SV** [comment]
Получил ответ по заявке:

Для успішної обробки Вашого звернення, державний службовець потребує уточнення деяких даних.
Примітка: назва області заповнюється державною мовою
Щоб уточнити дані, Вам потрібно перейти в розділ "Мій журнал" порталу iGov і внести інформацію у відповідні поля.
![screenshot 2016-06-08 17 00 24](https://cloud.githubusercontent.com/assets/11161652/15896828/98550e2c-2d9a-11e6-8620-bda36e029e96.png)

В журнале iGov нет никаких полей которые можно было бы исправить. Есть возможность прикрепить файл, но что прикреплять? Заявление на единый налог? Я проверил, в файле, который я прикреплял при подаче заявления названия областей указаны на украинском языке.

Что делать, подскажите пожалуйста.

**Comment by dmitrijzabrudskij** [comment]
Ваш коментар... - вот тут напишите что-нибудь и нажмите "Отправить"

на видном месте вроде это поле

**Comment by Propeller-SV** [comment]
Поле для комментария я конечно видел, просто ожидал нечто вроде поля "область". А в поле комментарий не понятно что писать: область прописки или область, где будет вести деятельность? Спасибо.

**Comment by dmitrijzabrudskij** [comment]
прописки

**Comment by Propeller-SV** [comment]
Отправил в комментарии название области по прописке на украинском языке. Прошли еще сутки. Чего ждать, подскажите пожалуйста.

**Comment by Propeller-SV** [comment]
И еще сутки. Друзья, что происходит? Новый регистратор снова саботирует работу?

**Comment by Propeller-SV** [comment]
Зарегистрирован! С донецкой пропиской. Спасибо большое всем причастным!

**Comment by agerman-ua** [comment]
Спасибо большое за терпение. Всех благ.
