### ISSUE TITLE
В переліку населених пунктів додати Дніпропетровської обл. додати смт.Покровске

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#4]
смт (селище міського типу)
.----------------------------
Вячеслав Лемешко
29 сентября г. 12:15
Здравствуйте. На портале iGov.org.ua в перечне населенных пунктов в Днепропетровской области отсутствует пгт.Покровское, это целый район Днепропетровской области. Возможно ли добавить его в перечень населенных пунктов, а то как-то целый район выпал)) Спасибо.
.----------------------------
Лінк 
https://www.facebook.com/igov.org.ua/messages/?index=0&mercurythreadid=user%3A100003079413138&threadid=100003079413138&timestamp=1443520345370
Але це внутрішне повідомлення, мабуть воно видо тільки адмінам фб сторінки

**Comment by GrekD** [comment]
доброго дня! Коли для цього району буде розкрита хоч одна послуга - обов'язково додамо
