### ISSUE TITLE
Отримання субсидії на оплату житлово-комунальних послуг.

### ISSUE THREAD

**Issue by SensibleOlga** [e-government-ua/iForum#40]
Зробіть можливість оформлювати субсидію, для студентів, що живуть у гуртожитках.

**Comment by dmitrijzabrudskij** [comment]
так а что сейчас мешает?

**Comment by SensibleOlga** [comment]
нет формы на сайте

**Comment by dmitrijzabrudskij** [comment]
на каком и какой формы? укажите последовательность действий как вы пробуете

**Comment by SensibleOlga** [comment]
лучше вы укажите все действия. так будет эфективнее

**Comment by dmitrijzabrudskij** [comment]
еще раз - что и где вы делаете на портале?

**Comment by SensibleOlga** [comment]
пыталась оформить субсидию для оплаты общежития, но формы специальной нет. заполнила ту, что есть, но наврядли получу положительный ответ

**Comment by dmitrijzabrudskij** [comment]
а можете дать ссылку на специальную форму? или скинуть мне на почту dmitrij.zabrudskij@privatbank.ua

**Comment by SensibleOlga** [comment]
ок... скину... меня поражают ваши "познания"

**Comment by SensibleOlga** [comment]
https://igov.org.ua/service/654/general

**Comment by SensibleOlga** [comment]
ну и?

**Comment by dmitrijzabrudskij** [comment]
так это единая форма для субсидий. вы же говорите о какой-то "специальной" для студентов в общежитиях - она есть вообще или вы сами ее придумали? по моей информации ее нет. 

если у вас есть пример ее - прошу предоставить

**Comment by SensibleOlga** [comment]
в первом сообщении есть и так ответ на вопрос. специальной формы нет, но она нужна, ведь у студента живущего в общежитии нет данных о:
*Загальна площа:
кв. м.

*Опалювальна площа:
кв.м.

*Разом з Вами мешкають інші особи?:
туи нужно указывать соседей по комнате?

*Утримання дому та придомової території:
около общежития есть несколько клумб... нужно указывать, что я пользуюсь этой услугой?

и еще у меня нет реквизитов на оплату коммунальных услуг. 

ну так как мне оформлять форму?

**Comment by dmitrijzabrudskij** [comment]
Форма заявления для всех одинаковая, по всем услугам в случае общежития вы платите по одной квитанции. Загальна площа и опалювальна площа по нормам общежития - это 6 кв. м. (1-но койкоместо). Эта информация есть в бухгалтерии каждого вуза (общежития). Все остальные услуги как по ОСМД: № л/с это номер комнаты, название предприятия это название и номер общежития такого-то ВУЗа

**Comment by Pensioner-P1** [comment]
Читаю вопросы и комментарии на портале и прихожу к выводу, что оформление субсидии на портале, трата времени. Пишется 20 рабочих, а подставляю номера заявок в графу статус и вижу время больше месяца. Кто нибудь оформил субсидию на портале? Сомневаюсь. Наша бумажная бюрократия непобедима. Пришла заявка в район и что? С кого спрос? Мы не получали и не видели.
Это моё личное мнение. И я больше ,чем уверен, что ещё никто не оформил субсидию на портале.

**Comment by dmitrijzabrudskij** [comment]
больше 100 одобренных субсидий с момента старта. еще несколько сотен в работе ожидающих решения. погуглите отзывы  - увидите, что есть по Днепропетровску уже счастливые обладатели субсидий, которые сделали это через портал
