### ISSUE TITLE
Регистрация ФЛП

### ISSUE THREAD

**Issue by koi8** [e-government-ua/iForum#400]
Добрый день,
подал заявку утром 23.05, судя по среднему таймингу уже должна была быть обработана :( Можете посмотреть в чем может быть задержка? Звернення № 0-254310525. Понимаю что у меня там есть интересный момент - работать ФЛП будет во Львове, а прописка у меня луганская.

**Comment by dmitrijzabrudskij** [comment]
добрый день
средний тайминг замеряется от момента взятия заявки в работу до ее закрытия
сейчас ситуация такая, что из-за наплыва желающих образовалась очередь заявок, которые еще не взяты в работу - поэтому потерпите, пожалуйста, в начале следующей недели отработают

по поводу прописки - это не будет проблемой, предприятие регистрируется либо по месту прописки, либо по месту жительства

**Comment by koi8** [comment]
У заявки как-то сменится статус когда она будет взята в работу? Пока такой:
23.05.2016 - В обробці

Я думал что уже в обработке :) Или будет еще какой-то статус?

**Comment by koi8** [comment]
Кажется начало недели уже прошло :( 
Можете уточнить прогноз? Заранее спасибо.

**Comment by dmitrijzabrudskij** [comment]
извините, насчет начала недели я погорячился - заявка только сегодня поступила в обработку.

**Comment by koi8** [comment]
Получил отказ с комментарием:
Коментар держслужбовця (Причина: Подання відомостей не в повному обсязі. В заяві про застосування спрощеної системи оподаткування не зазначено найменування органу державної податкової служби, а також поштовий індекс суб'єкта господарювання)
Но я понятия не имею "найменування органу державної податкової служби" на учет в которую меня поставят... Подскажите, как это выяснить? Очевидно же, что держслужбовец знал ответ на этот вопрос, но мне не сказал :(

**Comment by dmitrijzabrudskij** [comment]
это название вашей районной налоговой инспекции. вы можете найти ее тут: http://sfs.gov.ua/ru/pro-gfs/struktura/territorialnyie-organyi-gns/

индекс тоже нужно указывать. регистратор не может его угадывать

**Comment by koi8** [comment]
Какое именно учреждение мне нужно выбрать из списка, если прописка у меня луганская(жовтневый район), а регистрирую ФОП на адрес во Львове в Зализничном районе?

**Comment by dmitrijzabrudskij** [comment]
вписывайте информацию о налоговой по месту текущего нахождения
и индекс в адресе тоже от него

**Comment by koi8** [comment]
Спасибо, отправил новую заявку! Подскажите, ждать обработки придется примерно столько же?:(

**Comment by dmitrijzabrudskij** [comment]
нет, уже должно быть намного быстрее

**Comment by koi8** [comment]
Добрый день,
статус заявки №0-294923860 - закрыт, но емейл не пришел. Понимаю почему там может быть отказ, но все же хотелось бы посмотреть ответ держслужбовця.

**Comment by koi8** [comment]
письмо только что пришло, подал новую заявку с исправлениями.
