### ISSUE TITLE
Регистрация ООО. 

### ISSUE THREAD

**Issue by Jurcon** [e-government-ua/iForum#402]
Регистрация ООО проходит со значительной задержкой. Заявка  № 0-249861043 была подана 19.05.2016 в 17:44 (Харьков).
Прочитав несколько комментариев, понимаю, что не только у меня такая проблема. Дайте пожалуйста ответ по ситуации рассмотрения моей заявки. И исправьте ошибку: если не подтянулась ЕЦП, то предусмотрите соответствующее уведомление об этом. Судя по статистике, за день в Украине регистрируется только 1-4 предприятия. Это очень маленький показатель обработки заявок. Остальные получается просто "висят" без всякой перспективы.

**Comment by Jurcon** [comment]
Уже неделю жду... Будет ли позитивный результат рассмотрения моей заявки?..
Хочу обратиться к местному регистратору. Может подскажете как прояснить состояние дел на текущий момент? Или, как отказаться от заявки, чтобы не задвоить данные в реестре?

**Comment by dmitrijzabrudskij** [comment]
заявка обработана - на уставе не было подписей всех участников ООО, поэтому отказали в регистрации

задвоить заявку в реестре не получится - кто первый начнет регистрировать, того заявка и будет (я имею в виду "виртуального" регистратора или Вашего местного, к которому Вы пришли с оригиналами документов)

**Comment by agerman-ua** [comment]
26.05.2016 заявка закрыта.
