### ISSUE TITLE
Заявка 0-247545330  (регистрация ФОП) неделю в обработке!!!

### ISSUE THREAD

**Issue by Les398** [e-government-ua/iForum#403]
Прошу прояснить ситуацию по заявке 0-247545330 на регистрация ФОП, уже неделю статус не меняется. Вообще будет ли результат или идти по старой схеме и подавать заявление на регистрацию самостоятельно?

**Comment by dmitrijzabrudskij** [comment]
будет результат. заявка в работе. дождитесь ответа, пожалуйста

**Comment by Les398** [comment]
Пошел вчера к регистратору в г. Славянск, говорят нет заявки на мою фамилию. Есть большие опасения что ничего не получится онлайн! Кроме того регистратор заявляет что у них не работает  "программа" поэтому зарегистрировать ФЛП не могут.

**Comment by dmitrijzabrudskij** [comment]
еще раз - заявка УЖЕ в работе. славянск ее не увидит, так как регистрирует днепропетровская область.  дождитесь ответа

**Comment by agerman-ua** [comment]
27.05.2016 заявка закрыта.
