### ISSUE TITLE
Регистрация ТОВ, шла вторая неделя

### ISSUE THREAD

**Issue by ankormax** [e-government-ua/iForum#404]
Приветствую
Звернення № 0-244475590
Читал тикеты, понимаю, что перегружен сервис. Интересует статус заявки.
С уважением

**Comment by dmitrijzabrudskij** [comment]
добрый день
уже взята в работу - в начале недели будет ответ. еще немного подождите, пожалуйста

**Comment by ankormax** [comment]
Благодарю за ответ.
Дело крайне срочное, но я подожду, все понимаю.
Да, кстати. Человек без специального образования может быть волонтером и проверять заявки? Я бы помог сервису, дело то хорошее и полезное.

**Comment by agerman-ua** [comment]
27.05.2016 заявка закрыта.
