### ISSUE TITLE
Подводные камни при регистрации ФЛП онлайн

### ISSUE THREAD

**Issue by Les398** [e-government-ua/iForum#405]
Отказали в регистрации ФЛП, так как Приватбанк автоматически заполнил графу " гражданство" - UA, а оказывается нужно писать Україна. Кроме того в форме заявления на  "про застосування спрощеної системи оподаткування" скачиваемой по ссылке при регистрации на igov.ua, пункт №
10. Обрані види діяльності згідно з КВЕД ДК 009:2005, а оказывается нужно указывать коды КВЕД ДК 009:2010!  Я успешно указал коды согласно КВЕД ДК 009:2005 и так понимаю откажут во второй раз!

**Comment by agerman-ua** [comment]
Добрый вечер, @Les398 
Вопрос с гражданством достаточно давно снят. Вводит человек (если отличается от "Україна") и, дополнительно, можно исправить по уточнению от госслужащего.
КВЕДы сейчас проверка по шаблону, готовим на днях выложить полный справочник для выбора при вводе.
С уважением, Август.
