### ISSUE TITLE
Зміни в реєстраційних даних ФОП - Чому так довго обробляється заявка???!!!

### ISSUE THREAD

**Issue by alimov86** [e-government-ua/iForum#406]
Доброго дня! 24.05.2016 було відправлено заявку стосовно змін в реєстраційних даних ФОП № 0-258730715  Чому досі немає відповіді??? Терміново потрібно внести зміни а чекати доводиться вже 4-й день((((

**Comment by agerman-ua** [comment]
Доброго вечора, @alimov86 
Ваше звернення закрито ще 09.06.2016. Вибачте за затримки (відповідь та обробка). Наразі вже такої проблеми з затримкою не існує. Опрацьовуються за 2-3 робочі дні повністю онлайн.
Проблема була з виконавцями-урядовцями. Тому що всі послуги через портал надаються виключно державними органами.
З повагою, Август,
