### ISSUE TITLE
Уточнення даних заявки - Зміна КВЕД

### ISSUE THREAD

**Issue by roman-elena** [e-government-ua/iForum#407]
Доброго дня! У заявці № 0-243833513  від 17.05.2016 (Державна реєстрація змін до відомостей про фізичну особу – підприємця) - м. Запоріжжя, вказано декілька нових КВЕД для додавання, у тому числі один з них був помилково вказан повторно (63.99) - він вже був зареєстрований раніше.
Чи вважається це помилкою і треба оформити нове звернення?

**Comment by dmitrijzabrudskij** [comment]
добрый день!

формально должны отказать при такой ситуации, но вашу заявку обработают - в пн-вт, так как вы предупредили:)

**Comment by agerman-ua** [comment]
01.06.2016 звернення опрацьовано. Вітаємо.
