### ISSUE TITLE
Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн)

### ISSUE THREAD

**Issue by vrevych** [e-government-ua/iForum#408]
Доброго дня.
У мене є подано дві заявки:
- Звернення № 0-252449550
- Звернення № 0-243428932

Одна стосується зміни місця реєстрації, а друга додавання нових КВЕД.
Із 17 та 20 травня по них нічого не відбувається - статус як був Перевірка наданих даних (1) так і висить. Можливо реєстратори Яворівського району Львівської області не працюють у iGov чи просто потрібно очікувати.

Дякую. Ви робити просто величезну справу.

**Comment by dmitrijzabrudskij** [comment]
добрый день!

данные редактируют днепропетровские регистраторы - и так как желающих много, а регистраторов мало, образовалась очередь(
потерпите еще немного - в начале следующей недели обработают обе заявки

**Comment by vrevych** [comment]
Доброго дня по Звернення № 0-243428932 - реєстратор видалив старі види дільності, а заповняв форму на те, щоб додати нові види діяльності без видалення старих.

**Comment by dmitrijzabrudskij** [comment]
регистратор ничего не удалил. просто изменения внесли двумя действиями:
1. изменили адрес регистрации
2. изменили квэды (добавили новые)
поэтому п.1 уже появился в реестре, а п.2 появится завтра

**Comment by vrevych** [comment]
Я переглянув дані у Єдиному державному реєстрі юридичних осіб, фізичних осіб-підприємців та громадських формувань
 - у мене внесено 3 нові види діяльності на які я заповнював заявку,
- а старих 3 видів діяльності немає.

Можливо мені заповнити нову заявку на їх внесення. Тепер із новим класиікатором помінялись коди - можливо це причина їх видалення.

Дякую.

**Comment by dmitrijzabrudskij** [comment]
все верно - старые квэды стали недействительными. нужна еще одна заявка для добавления актуальных

**Comment by agerman-ua** [comment]
Звернення № 0-252449550 - закрито 01.06.2016
Звернення № 0-243428932 - закрито 01.06.2016
