### ISSUE TITLE
Отримання/заміна паспорта громадянина України для виїзду за кордон

### ISSUE THREAD

**Issue by Valadey** [e-government-ua/iForum#409]
заявка 0-238327064
Добрый день! 14.05.2016 я оформил заявку на загранпаспорт, но на почту мне не пришли реквизиты для оплаты услуг и дальнейшие действия. Моя почта vladimir.komashko.01@gmail.com. так же было указано что нужно прийти с оплатами и документами 6.06.2016, но нет информации с чем приходить. Заранее спасибо.

**Comment by Koffeek** [comment]
@Valadey проверьте, пожалуйста, папку "Спам" за 14,05. Если в ней ничего нет, то уточните, в какое подразделение ДМС подавали заявку и мы отправим письмо повторно.

**Comment by Valadey** [comment]
Спасибо! Нашел в спаме.
