### ISSUE TITLE
Оформление субсидии г. Киев Днепровский район

### ISSUE THREAD

**Issue by rez89** [e-government-ua/iForum#41]
Добрый день, пытался оформить  субсидию г. Киев Днепровский район. При выборе района Днепровского там не оказалось. Это ошибка? Или его еще не добавили? И если не добавили, то примерно когда добавят?

**Comment by dmitrijzabrudskij** [comment]
добрый день. Днепровского района пока нет. планируем за неделю-две подключить. если со стороны властей не будет проволочек

**Comment by rez89** [comment]
Понял, будем ждать. Спасибо за ответ.

**Comment by rez89** [comment]
dmitrijzabrudskij, добрый день. Подключить Днепровский район, г. Киев так и не удалось, может есть какая-нибудь информация по срокам?

**Comment by kurbpa** [comment]
@OlgaKhomenko
Ольга, планируется ли подключение новых районов по Киеву ?

**Comment by OlgaKhomenko** [comment]
У нас на данный момент всего три пилотных района: Шевченковский, Деснянский и Соломенский. Думаю, что в ближайшее время других районов не будет.

**Comment by rez89** [comment]
Очень жаль....
