### ISSUE TITLE
Уточнение по обработке заявки

### ISSUE THREAD

**Issue by aillinska** [e-government-ua/iForum#411]
Подано 2 заявки. Актуальная Звернення № 0-270011399. Пожалуйста ,уточните ориентировочную дату обработки. Очень срочный вопрос. Буду очень благодарна

**Comment by dmitrijzabrudskij** [comment]
что за заявка была?

**Comment by aillinska** [comment]
Заявка на изменение квэд. Сейчас ее закрыли/отклонили. Актуальный номер № 0-282332212

**Comment by dmitrijzabrudskij** [comment]
не вижу 282332212 - точно номер правильный?

**Comment by aillinska** [comment]
Звернення № 0-282332212 так

**Comment by dmitrijzabrudskij** [comment]
вам 20 минут назад уже ответили по этой заявке. поищите письмо в спаме, если не увидели

**Comment by aillinska** [comment]
да, спасибо, уже вижу
