### ISSUE TITLE
Виталий Гунько

### ISSUE THREAD

**Issue by vgunko** [e-government-ua/iForum#414]
заявка 0-255815528 от 23.05.2016г. Когда будет обработана.

**Comment by dmitrijzabrudskij** [comment]
на что подавалась заявка?

**Comment by vgunko** [comment]
на регистрацию юрлица (благотворительный фонд)

**Comment by vgunko** [comment]
Обращение было раньше - было отказано (причина - я будто бы дважды указал "область"),

13 мая мне с Днепра пришло такое письмо 
Доброго дня!

Нещодавно Ви замовляли послугу реєстрації юридичної особи або фізичної особи-підприємця на порталі igov.org.ua. На жаль, Ваше звернення було опрацьоване с некоректним коментарем і Вам було відмовлено в реєстрації. Приносимо вибачення за незручності та просимо Вас створити нову заяву на реєстрацію.

Якщо Ви вже отримали послугу по новій заяві або вона зараз очікує обробки, просимо її не дублювати.

З повагою, команда порталу igov.org.ua

**Comment by agerman-ua** [comment]
31.05.2016 заявка закрыта.
