### ISSUE TITLE
Когда обработают заявку?

### ISSUE THREAD

**Issue by Plakhan** [e-government-ua/iForum#415]
0-246990190
Добрый день. Когда обработают заявку? Спасибо

**Comment by dmitrijzabrudskij** [comment]
добрый день
тип заявки?

**Comment by Plakhan** [comment]
Добрый день, скажите, какие дальнейшие действия после того как пришло такое письмо:


Ваше звернення на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін.

**Comment by dmitrijzabrudskij** [comment]
никаких. работайте дальше с уже измененными данными - в реестр изменения внесены

**Comment by Plakhan** [comment]
У меня была заявка на регистрацию ФЛП.  Меня интересует, что нужно дальше делать после регистрации...
Как получить свидетельство о регистрации флп и о плательщике единого налога?

**Comment by dmitrijzabrudskij** [comment]
выписку о регистрации можете сами скачать и распечатать (ходить никуда не нужно за ней)

свидетельство из реестра плательщиков единого налога можете заказать в своей налоговой по месту регистрации (но его тоже в бумажном виде очень редко требуют)

**Comment by Plakhan** [comment]
Спасибо. Я  так понял, что становиться на учет в налоговую уже не нужно, уже все сделано?

**Comment by dmitrijzabrudskij** [comment]
да, все делается централизованно

**Comment by Plakhan** [comment]
Спасибо

**Comment by agerman-ua** [comment]
31.05.2016 - заявка закрыта.
