### ISSUE TITLE
заявка на добавление квед предпринимателя

### ISSUE THREAD

**Issue by ludmiladekhtyarenko** [e-government-ua/iForum#416]
Заявка 0-240790446 от 16 мая, висит статус "Перевірка наданих даних", хотелось бы понимать, будут ли вообще внесены даные, и если будут, то когда.

**Comment by dmitrijzabrudskij** [comment]
заявка в работе. сегодня-завтра будет обработана

**Comment by ludmiladekhtyarenko** [comment]
спасибо огромное)

**Comment by dmitrijzabrudskij** [comment]
такс, эту уже закрыли
