### ISSUE TITLE
Державна реєстрація змін до відомостей про ФОП - Звернення № 0-246541755, коли буде опрацьоване?

### ISSUE THREAD

**Issue by IgorUm** [e-government-ua/iForum#417]

**Comment by dmitrijzabrudskij** [comment]
добрый день
как называется заявка?

**Comment by IgorUm** [comment]
Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн) 
31 мая 2016, 15:21:02, от "dmitrijzabrudskij" < notifications@github.com >: 

добрый день 
как называется заявка? —

**Comment by dmitrijzabrudskij** [comment]
заявка уже в работе. завтра-послезавтра будет ответ

**Comment by IgorUm** [comment]
спасибо! 

31 мая 2016, 18:38:43, от "dmitrijzabrudskij" < notifications@github.com >: 

заявка уже в работе. завтра-послезавтра будет ответ —

**Comment by agerman-ua** [comment]
02.06.2016 заявка закрыта
