### ISSUE TITLE
заявка на добавление КВЕД предпринимателя

### ISSUE THREAD

**Issue by ludmiladekhtyarenko** [e-government-ua/iForum#418]
Здравствуйте. Я сегодня подавала заявку на добавление КВЕД предпринимателя, и случайно подала один и тот же запрос дважды. Прошу рассмотреть только один, заявки 0-285039213 и 0-285066934

**Comment by dmitrijzabrudskij** [comment]
добрый день еще раз
в работе осталась только 285039213 
ожидайте ответ, пожалуйста

**Comment by ludmiladekhtyarenko** [comment]
спасибо большое

**Comment by agerman-ua** [comment]
№285039213 02.06.2016 закрыто положительно. Поздравляем.
