### ISSUE TITLE
реєстрація ФОП. Звернення № 0-271114011

### ISSUE THREAD

**Issue by HelgaVa** [e-government-ua/iForum#419]
Добрий день!
Зареєструвала ФОП чз igov.org.ua 27.05. Проте не було повідомлення на пошті, про те що заявка успішно зареєстрована чи навпаки...В чому проблема ?

**Comment by dmitrijzabrudskij** [comment]
добрый день
прошу прощения, все из-за очереди - желающих оказалось больше, чем предполагалось(

но сегодня заявка уже попала в обработку - поэтому в течение 1-2 дней будет ответ

**Comment by HelgaVa** [comment]
Дякую.
Чекаємо

1 июня 2016 г., 16:08 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

> добрый день
> прошу прощения, все из-за очереди - желающих оказалось больше, чем
> предполагалось(
>
> но сегодня заявка уже попала в обработку - поэтому в течение 1-2 дней
> будет ответ
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-222986735>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxaKXY8ePO6Ib4yuQRtXcKZhV-6YgL_ks5qHYRrgaJpZM4IrUwv>
> .
>



-- 
З повагою, Ольга Фатерига !

**Comment by HelgaVa** [comment]
Скажіть будь ласка, статус заявки - закрита...це означає що заявка прийнята
?
І які наступні дії щодо отримання ФОП...Як отримати в пареровому вигляді
свідоцтво ФОП?



1 июня 2016 г., 16:16 пользователь Оля Фатерига <olhafateryga@gmail.com>
написал:

> Дякую.
> Чекаємо
>
> 1 июня 2016 г., 16:08 пользователь dmitrijzabrudskij <
> notifications@github.com> написал:
>
> добрый день
>> прошу прощения, все из-за очереди - желающих оказалось больше, чем
>> предполагалось(
>>
>> но сегодня заявка уже попала в обработку - поэтому в течение 1-2 дней
>> будет ответ
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-222986735>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ASxaKXY8ePO6Ib4yuQRtXcKZhV-6YgL_ks5qHYRrgaJpZM4IrUwv>
>> .
>>
>
>
>
> --
> З повагою, Ольга Фатерига !
>



-- 
З повагою, Ольга Фатерига !

**Comment by dmitrijzabrudskij** [comment]
поищите письмо по результату обработки (могло в спам попасть). при успешной регистрации в нем будет код и ссылка, где по нему можно проверить регистрацию
там же будет доступна и выписка. печатную ее форму уже не нужно у себя хранить - она всегда и всем доступна в реестре

**Comment by HelgaVa** [comment]
ще таке питання: в мене прописка Чернігівська, а живу в Києві. Додаткову
заяву потрібно додавати для онлайн реєстрації??

2 июня 2016 г., 12:43 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

> поищите письмо по результату обработки (могло в спам попасть). при
> успешной регистрации в нем будет код и ссылка, где по нему можно проверить
> регистрацию
> там же будет доступна и выписка. печатную ее форму уже не нужно у себя
> хранить - она всегда и всем доступна в реестре
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-223244595>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxaKfld4_zeYUZgTMNRWuhpNpRP2UUgks5qHqW5gaJpZM4IrUwv>
> .
>



-- 
З повагою, Ольга Фатерига !

**Comment by dmitrijzabrudskij** [comment]
регистрация проходит либо по адресу прописки, либо по адресу проживания. так что вас зарегистрируют по тому адресу, который указан в заявке. доп заявление не нужно

**Comment by HelgaVa** [comment]
добрий день!
Скажіть будь ласка, звернення № 0-295545752 та № 0-295162022, коли будуть
опрацьовані ?? Подані були : 03.06.16 і до сих пір в обробці.
Дякую.

2 июня 2016 г., 17:06 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

> регистрация проходит либо по адресу прописки, либо по адресу проживания.
> так что вас зарегистрируют по тому адресу, который указан в заявке. доп
> заявление не нужно
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-223302064>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxaKb9is8PfeMiF54oCxZhjh9uSBbq0ks5qHuNNgaJpZM4IrUwv>
> .
>



-- 
З повагою, Ольга Фатерига !

**Comment by dmitrijzabrudskij** [comment]
добрый вечер
это регистрация или внесение изменений?

**Comment by HelgaVa** [comment]
Це реєстрація

середа, 8 червня 2016 р. користувач dmitrijzabrudskij <
notifications@github.com> написав:

> добрый вечер
> это регистрация или внесение изменений?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-224422483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxaKTStdexHGBhJiKkSErc9rn9t0Tt-ks5qJeSqgaJpZM4IrUwv>
> .
>


-- 
З повагою, Ольга Фатерига !

**Comment by HelgaVa** [comment]
А також звернення № 0-300872067.
Будь ласка розгляньте їх якомога швидше.
Дуже вдячна.

2016-06-08 7:42 GMT+03:00 Оля Фатерига <olhafateryga@gmail.com>:

> Це реєстрація
>
> середа, 8 червня 2016 р. користувач dmitrijzabrudskij <
> notifications@github.com> написав:
>
> добрый вечер
>> это регистрация или внесение изменений?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-224422483>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ASxaKTStdexHGBhJiKkSErc9rn9t0Tt-ks5qJeSqgaJpZM4IrUwv>
>> .
>>
>
>
> --
> З повагою, Ольга Фатерига !
>
>


-- 
З повагою, Ольга Фатерига !

**Comment by HelgaVa** [comment]
Сьогодні по зверненню № 0-295162022, про яке я писала вище подзвонила зла
жінка з податкової Кривого Рогу з притензіями, що заява на спрощену систему
прийшла пуста до них, хоча ми її заповняли, і сказала що необхідно їхати в
Кривий Ріг нам з Києва заповнити заяву....((((
Хлопці та дівчата це не серйозно, я розумію що багато звернень ...((
До суті: Як можна виправити цю заяву онлайн, щоб не їхати в Кривий Ріг ?
І дайте відповідь по двох інших заявах : № 0-300872067 -  змiнила свiй
статус на закрита, але повідомлень на пошту не було, яке по ній рішення ? А
також звернення : 0-295545752
Дякую

2016-06-08 10:24 GMT+03:00 Оля Фатерига <olhafateryga@gmail.com>:

> А також звернення № 0-300872067.
> Будь ласка розгляньте їх якомога швидше.
> Дуже вдячна.
>
> 2016-06-08 7:42 GMT+03:00 Оля Фатерига <olhafateryga@gmail.com>:
>
>> Це реєстрація
>>
>> середа, 8 червня 2016 р. користувач dmitrijzabrudskij <
>> notifications@github.com> написав:
>>
>> добрый вечер
>>> это регистрация или внесение изменений?
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-224422483>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/ASxaKTStdexHGBhJiKkSErc9rn9t0Tt-ks5qJeSqgaJpZM4IrUwv>
>>> .
>>>
>>
>>
>> --
>> З повагою, Ольга Фатерига !
>>
>>
>
>
> --
> З повагою, Ольга Фатерига !
>



-- 
З повагою, Ольга Фатерига !

**Comment by HelgaVa** [comment]
Також звернення *№0-288915163* - вже зареєстрований, проте в листі бе був
вкладений лист з описом документів, що надаються була вказана лише :
1. Реєстраційна картка на проведення реєстрації
2.Копія довідки про включення заявника до Держреєстру

Але немає заяви щодо обрання спрощеної системи оподаткування

2016-06-08 16:41 GMT+03:00 Оля Фатерига <olhafateryga@gmail.com>:

> Сьогодні по зверненню № 0-295162022, про яке я писала вище подзвонила зла
> жінка з податкової Кривого Рогу з притензіями, що заява на спрощену систему
> прийшла пуста до них, хоча ми її заповняли, і сказала що необхідно їхати в
> Кривий Ріг нам з Києва заповнити заяву....((((
> Хлопці та дівчата це не серйозно, я розумію що багато звернень ...((
> До суті: Як можна виправити цю заяву онлайн, щоб не їхати в Кривий Ріг ?
> І дайте відповідь по двох інших заявах : № 0-300872067 -  змiнила свiй
> статус на закрита, але повідомлень на пошту не було, яке по ній рішення ? А
> також звернення : 0-295545752
> Дякую
>
> 2016-06-08 10:24 GMT+03:00 Оля Фатерига <olhafateryga@gmail.com>:
>
>> А також звернення № 0-300872067.
>> Будь ласка розгляньте їх якомога швидше.
>> Дуже вдячна.
>>
>> 2016-06-08 7:42 GMT+03:00 Оля Фатерига <olhafateryga@gmail.com>:
>>
>>> Це реєстрація
>>>
>>> середа, 8 червня 2016 р. користувач dmitrijzabrudskij <
>>> notifications@github.com> написав:
>>>
>>> добрый вечер
>>>> это регистрация или внесение изменений?
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-224422483>,
>>>> or mute the thread
>>>> <https://github.com/notifications/unsubscribe/ASxaKTStdexHGBhJiKkSErc9rn9t0Tt-ks5qJeSqgaJpZM4IrUwv>
>>>> .
>>>>
>>>
>>>
>>> --
>>> З повагою, Ольга Фатерига !
>>>
>>>
>>
>>
>> --
>> З повагою, Ольга Фатерига !
>>
>
>
>
> --
> З повагою, Ольга Фатерига !
>



-- 
З повагою, Ольга Фатерига !

**Comment by agerman-ua** [comment]
@HelgaVa 
"... звернення № 0-300872067" - Заявка оброблена позитивно 2016-06-06 15:03.
"... звернення № 0-295545752" - Заявка в роботі
"... звернення № 0-295162022" - Заявка оброблена позитивно 2016-06-03 14:29
"... звернення № 0-288915163" - Заявка оброблена позитивно 2016-06-01 17:03
По всім обробленим заявкам повинні були обов'язково прийти листи.
З повагою, Август.

**Comment by HelgaVa** [comment]
А чому не підтягнулися заяви про обрання спрощеної системи оподаткування ?

2016-06-10 15:59 GMT+03:00 agerman-ua <notifications@github.com>:

> @HelgaVa <https://github.com/HelgaVa>
> "... звернення № 0-300872067" - Заявка оброблена позитивно 2016-06-06
> 15:03.
> "... звернення № 0-295545752" - Заявка в роботі
> "... звернення № 0-295162022" - Заявка оброблена позитивно 2016-06-03 14:29
> "... звернення № 0-288915163" - Заявка оброблена позитивно 2016-06-01 17:03
> По всім обробленим заявкам повинні були обов'язково прийти листи.
> З повагою, Август.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/419#issuecomment-225175313>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxaKRXaaKmKCy-SQ5YIPQZsTNoZ_x6Qks5qKV-xgaJpZM4IrUwv>
> .
>



-- 
З повагою, Ольга Фатерига !

**Comment by agerman-ua** [comment]
@HelgaVa 
Доброго дня.
Можна тільки здогадуватися що саме відбулося.
Тут все повинно бути просто - якщо додавали відповідні файли при поданні, вони повинні бути "прикріплені" до заявки.
З повагою, Август.

**Comment by HelgaVa** [comment]
Так повинно бути просто- але все не так просто!!
Коли вже буде прийняте рішення по Звернення № 0-295545752, яке було подане
03.06.16р.
І скажіть чому підтягугнулися до вище вказаних заяв лише по одному КВЕДу,
хоча у всіх було вказано по 4???
Дякую.

2016-06-13 14:18 GMT+03:00 agerman-ua <notifications@github.com>:

> Closed #419 <https://github.com/e-government-ua/iForum/issues/419>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/419#event-690289320>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxaKcegkfZMCpYG4GZrKq3qUPKAnHvqks5qLTyIgaJpZM4IrUwv>
> .
>



-- 
З повагою, Ольга Фатерига !

**Comment by agerman-ua** [comment]
Про КВЕДи не можу відповісти, повинні бути всі що вказуються у заявці. Це мабуть людський фактор. На жаль.
