### ISSUE TITLE
ols1 

### ISSUE THREAD

**Issue by ols1** [e-government-ua/iForum#42]
Хоча б одну послугу зробіть для Закарпаття.Ну сором просто
Абож на сайті зробіть фільтр доступних послуг по регіонам

**Comment by dmitrijzabrudskij** [comment]
с радостью ждем от вас конкретных предложений с контактами чиновников, готовых ее запустить

**Comment by VadymVolos** [comment]
Фільтр є, в пошуку натисніть стрілку відкриється фільтр. Там доступно 2 послуги по Закарпаттю.
Якщо є бажання більше, ви можете домовтесь  з держустановами про впровадження, як тільки звернуться ми почнемо впроваджувати.

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
