### ISSUE TITLE
Работа с паспортами в подразделении ДМС.

### ISSUE THREAD

**Issue by ArmageddOK** [e-government-ua/iForum#420]
Добрый день. В начале марта я воспользовался услугами портала igov для заказа вклеивания фотографии в паспорт (заявка 0-126149584). Однако, прийдя в выбранное подразделение ДМС, я обнаружил, что никакой электронной очереди там не существует, ни о какой регистрации через интернет никто не слышал, а на указанное мной время своей очереди ожидали более 20 человек. В результате, я ждал полтора часа вместе со всеми.
А через несколько дней мне на электронную посту пришло письмо от портала igov о том, что я не явился в указанное время. Из этого я делаю вывод, что моя заявка вообще никак не была обработана подразделением ДМС.

Сейчас мне нужно оформлять загранпаспорт, и в связи с этим у меня вопрос: есть вообще смысл регистрировать заявку через igov, или это снова не будет иметь никакого смысла?

**Comment by Koffeek** [comment]
@ArmageddOK если Вы заказывали услугу, то должны проходить по своему времени, а не ждат в общей очереди. Для вклейки фото существовала стадия проверки данных (сейчас она убрана), на которой сотрудник видимо не досмотрел по Вашей заявке. В загранпаспорте Вы просто записываетесь на дату и время и приходите с оплаченными квитанциями и необходимыми документами. В какой район Вы подавали заявку на вклейку фото?

**Comment by ArmageddOK** [comment]
Бабушкинский район.
По поводу "проходить по своему времени". Я записался на 9:00, т.е. на время открытия "паспортного стола". Когда я пришел, оказалось, что там стоят люди, которые занимали очередь еще с 7 утра. Если бы я начал говорить им, что я пройду без очереди потому что где-то записывался - меня бы прикончили на месте. Никакой электронной очереди там нет.
В целом, я вас понял. Спасибо за ответ, в ближайшее время подам заявку.
