### ISSUE TITLE
Державна реєстрація створення фізичної особи – підприємця. Звернення № 0-286533065

### ISSUE THREAD

**Issue by SvyatoslavLynda** [e-government-ua/iForum#421]
Можно узнать когда будет обработано?

**Comment by dmitrijzabrudskij** [comment]
вы уже несколько постов на этом форуме написали. почему не пишите в той ветке, где были старые заявки? и какие ответы по ним пришли?

**Comment by SvyatoslavLynda** [comment]
Добрый день, я писал в другом Issues человека у которого была такая же проблема как и у меня,  мое заявление было не принято, и на момент создания моего он уже был закрыт, поэтому я решил создать новый, извините если что то не так сделал.
А заявка моя уже неделю весит в обработке и не чего не меняеться, можно узнать про ее статус.

**Comment by SvyatoslavLynda** [comment]
Добрый день, моя заявка уже висит 9й день, и статус в обработке, есть ли возможность получить результат какой то на следующей неделе, мне просто уже срочно нужен ФОП.

**Comment by dmitrijzabrudskij** [comment]
добрый день!
будет обработана максимум в понедельник, извините за задержку

**Comment by SvyatoslavLynda** [comment]
Добрый день!
моя заявка все еще не обработана

**Comment by agerman-ua** [comment]
Доброго дня, @SvyatoslavLynda 
Ми останнім часом дуже щільно працювали з реєстраторами і начебто таких формулювань вже немає. Вчимо людей.
Якщо ще актуально - можете подати нове звернення, зараз обробка триває в середньому до тижня.
З повагою, Август.
