### ISSUE TITLE
разные адреса в ЭЦП и ФЛП

### ISSUE THREAD

**Issue by PolinaKlitsakova** [e-government-ua/iForum#422]
Здравствуйте! Подскажите пожалуйста, могут ли отличаться адреса в сертификате ЭЦП (там указывается адрес прописки - Донецк), и адрес, который я указываю при регистрации ФЛП (киев)?

**Comment by dmitrijzabrudskij** [comment]
добрый день

могут зарегистрировать как по адресу прописки, так и по адресу проживания
