### ISSUE TITLE
Добрый день! Скажите пожалуйста, когда будет обработана заявка оформление ФЛП? 

### ISSUE THREAD

**Issue by MariiaVdovina** [e-government-ua/iForum#423]
Звернення № 0-273900051 (30.05.2016) Вдовіна Марія Вячеславівна 
Есть ли смысл ждать, что оформление пройдет успешно?
С уважением Мария Вдовина

**Comment by dmitrijzabrudskij** [comment]
есть смысл
заявка уже в работе - сегодня-завтра должен быть ответ

**Comment by MariiaVdovina** [comment]
Добрый день! Спасибо за ответ Дмитрий, однако к сожалению никаких изменений не произошло.

**Comment by MariiaVdovina** [comment]
Здравствуйте! Скажите пожалуйста есть ли какая-то возможность узнать, что происходит с заявкой т.к. на сайте не отображаются никакие изменения, уже прошла неделя с момента ее подачи, помогите пожалуйста!

**Comment by dmitrijzabrudskij** [comment]
добрый день, Мария!

прошу прощения за задержку, но с Вашей заявкой произошла накладка - район, который должен был ее обработать, саботирует процесс, из-за чего сегодня она поступит в работу другому району. Ответ будет завтра, скорее всего

**Comment by MariiaVdovina** [comment]
Хорошо, Спасибо!

**Comment by MariiaVdovina** [comment]
Здраствуйте!
Пришел ответ
Примітка:
Некоректно заповнена адреса, необхідно вказати індекс в заявах

Щоб уточнити дані, Вам потрібно перейти в розділ "Мій журнал" порталу iGov і внести інформацію у відповідні поля.

Скажите пожалуйста это мне нужно новую заявку подавать? т.к. не вижу функции внесения доп. информации в разделе "мой журнал"

С уважением, Мария

**Comment by dmitrijzabrudskij** [comment]
да, нужно новую подавать

**Comment by MariiaVdovina** [comment]
Хорошо, спасибо большое за помощь!
Новую заявку подала с уточнением необходимого индекса - Звернення № 0-308285256 (09.06.2016) Вдовіна Марія Вячеславівна 
Сколько может дней занять обработка нового заявления, просто очень спешу, т.к. уже больше недели ждала ответ. 
С уважением, Мария

**Comment by MariiaVdovina** [comment]
Добрый день! В общем уже третий раз подаю заявку... А нет случайно каких-то правил по заполнению заявки, т.к. немного неясно, что является обязательным полем для заполнения. Новая заявка  Звернення № 0-310729143 (09.06.2016)
Спасибо огромное за быстрый ответ!
С уважением, Мария

**Comment by agerman-ua** [comment]
Добрый день, очень жаль что с первого раза не получилось. 
Ваша заявка в работе. 
Правило простое :) если есть поле и Вы знаете что туда ввести - вводите. Ведь не всегда правильно ставить все поля обязательными. Есть разные случаи. 
Мы рассматриваем разные варианты более качественного решения для подачи "с первого раза". 
Если Вам будет приятно - то именно Ваш практический опыт и обратная связь от Вас делает жизнь следующих за Вами легче.
Хороших выходных.
С уважением, Август.

**Comment by MariiaVdovina** [comment]
Спасибо большое! надеюсь в этот раз заявка пройдет успешно

**Comment by agerman-ua** [comment]
Добрый день,
Встречно рассчитываем на такой-же результат. 
Вы уже подали новую заявку?

**Comment by MariiaVdovina** [comment]
Да, сразу в тот же день подала эту, заполнила все поля, которые были пустые и на которые знала, что писать :)  - Звернення № 0-310729143 (09.06.2016)

**Comment by MariiaVdovina** [comment]
И скажите пожалуйста, эту заявку (Звернення № 0-310729143 (09.06.2016)) в течении ближайших дней смогут рассмотреть? т.к. нужно открыть флп до конца месяца
С уважением Мария

**Comment by MariiaVdovina** [comment]
Да, сразу в тот же день подала эту, заполнила все поля, которые были пустые и на которые знала, что писать :) - Звернення № 0-310729143 (09.06.2016)
И скажите пожалуйста, эту заявку (Звернення № 0-310729143 (09.06.2016)) в течении ближайших дней смогут рассмотреть? т.к. нужно открыть флп до конца месяца
С уважением Мария

**Comment by agerman-ua** [comment]
Добрый день, @MariiaVdovina 
Поздравляю 14.06 заявка закрыта положительно, обязательно должно было прийти письмо.
Удачи в предпринимательстве.
С уважением, Август
