### ISSUE TITLE
Звернення закрито із запитом на документи

### ISSUE THREAD

**Issue by nikolaykovenko** [e-government-ua/iForum#425]
Доброго дня. Моє звернення № 0-286541010 на заміну посвідчення водія закрито із наступною відповіддю:

На жаль, Вам відмовлено в реєстраціі авто.
Підстава:
СКИНЬТЕ КОПІЮ ПАСПОРТА ДЕ ЗАЗНАЧЕНО ВАШУ ПРОПИСКУ,І КОПІЮ ПОСВІДЧЕННЯ ВОДІЯ.

Скажіть, будь ласка, куди я можу відправити дані документи?
Дякую.

**Comment by kurbpa** [comment]
@nikolaykovenko 

Добрий день.
Сотрудник сервисного центра  плохо ознакомился с процессом  по всей видимости. Благодаря Вашему сигналу мы провели с ним пояснительную беседу касательно бизнес-процесса данной услуги.

Пожалуйста, подайте заявку ещё раз.

**Comment by nikolaykovenko** [comment]
Конечно, спасибо.
