### ISSUE TITLE
внесение КВЕД предпринимателя

### ISSUE THREAD

**Issue by ludmiladekhtyarenko** [e-government-ua/iForum#426]
Здравствуйте.
Подскажите, пожалуйста, когда будут добавлены КВЕД по заявкам 0-256451849 и 0-256372364 от 23.05.2016?

**Comment by dmitrijzabrudskij** [comment]
добрый день

заявки уже в работе, но из-за очереди попадут на следующую неделю в работу. извините

**Comment by ludmiladekhtyarenko** [comment]
Спасибо большое)

**Comment by agerman-ua** [comment]
17.06.2016 закрито обидва звернення.
