### ISSUE TITLE
Зміна реєстраційних даних ФОП

### ISSUE THREAD

**Issue by KhrulenkoVlad** [e-government-ua/iForum#427]
Доброго дня!
Підкажіть будь ласка коли буде опрацьована заявка №0-279728919?
Дата розміщення 30 травня 2016 року.  Додавалися нові КВЕД. Юридична адреса ФОП - Згурівський район, Київська область.
"Ваше звернення №0-279728919 на тему "Державна реєстрація змін до відомостей про фізичну особу – підприємця" прийнято до розгляду"

Дякую за відповідь

**Comment by dmitrijzabrudskij** [comment]
добрый день
на следующей неделе сделают
извините, из-за количества желающих пока не получается быстрее...

**Comment by agerman-ua** [comment]
Звернення закрито 17.06.2016. Позитивно. Вітаємо.
