### ISSUE TITLE
РЕГИСТРАЦИЯ ФОП отказ звернення №0-288952034

### ISSUE THREAD

**Issue by Spetuschenko** [e-government-ua/iForum#428]
Добрый день, получили вот такое сообщение, при этом мы при заполнении формы на сайте igov все прописывали в ручную и указывали все на украинском. Возможно ли, то что эта заполненная форма не сохраняется, а регистратору уходит только та информация которая "подтягивается" из банка?

"Ваше звернення №0-288952034 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.

Коментар держслужбовця (Причина:в заяві не вказано - країна громадянства; назва вулиці; номер приміщення; всі дані вказуються державною мовою)"

Кстати перед этим, было вот такое сообщение: 
Для успішної обробки Вашого звернення, державний службовець потребує уточнення деяких даних.

Поле	                                     Значення	                             Коментар
Область	                                     ОДЕССКАЯ	
Назва населеного пункту	    КОНОПЛЯНОЕ	
Назва вулиці, проспекту, провулку тощо		

Примітка:
Щоб уточнити дані, Вам потрібно перейти в розділ "Мій журнал" порталу iGov і внести інформацію у відповідні поля.
Дякуємо за порозуміння

после которого мы перешли по ссылке и все исправили, хотя подчеркну, что при изначальном заполнении все данные были указаны и на украинском.
Заранее Вам спасибо за ответ и помощь

**Comment by dmitrijzabrudskij** [comment]
добрый день
Вы в заявке изначально авторизовывались через эцп или банкид?

**Comment by Spetuschenko** [comment]
Изначально через банкид, а потом был получен в приват банке эцп.

**Comment by dmitrijzabrudskij** [comment]
а подайте новую заявку, пожалуйста, вместе с исправлениями в полях адреса - я посмотрю в каком виде она придет
