### ISSUE TITLE
Регистрация ТОВ с 30.05.16

### ISSUE THREAD

**Issue by gralexiv** [e-government-ua/iForum#429]
Добрый день!

Заявка на регистрацию ТОВ 0-275375458 подана 30.05.16. Обратной реакции не было пока.
Можно узнать ее состояние? Будет ли принята в работу? Или нужно подавать повторно?

Спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день
заявка уже в работе. на следующей неделе обработают

**Comment by gralexiv** [comment]
Добрый день!
Есть какая-то информация о сроках прохождения моей заявки?
И, кстати, я не получал на почту уведомления при подаче заявки. Спам проверил.

**Comment by gralexiv** [comment]
Добрый день!

Текста будет много, потому что мне нравится этот проект и, возможно, мои проблемы/замечания/пожелания позволят хоть немного улучшить работу этого проекта
 В регистрации отказано, привожу все, что мне пришло (возможно это будет полезно для отладки услуги):
На почту пришло два письма:

1. В 16:10 от admin@igov.org:
> Шановний (-а) громадянин!
> 
> Для успішної обробки Вашого звернення, державний службовець потребує уточнення деяких даних.
> 
> Примітка:
> некоректно заповнено ПІБ (російська мова, а треба державною)
> 
> Щоб уточнити дані, Вам потрібно перейти в розділ "Мій журнал" порталу iGov і внести інформацію у відповідні поля.
> 
> Дякуємо за порозуміння

2. Через 6 минут  в 16:16 :
> Шановний(-а), АЛЕКСАНДР ИВАНОВИЧ
> 
> Ваше звернення №0-275375458 на тему "Державна реєстрація створення юридичної особи", опрацьовано і по ньому винесено рішення про відмову в реєстрації.
> 
> Коментар держслужбовця (Причина:)
>  
> З повагою,
> Команда Порталу державних послуг iGov 
> 
**Причина так и не указана.** Ощущение, что заявка 1,5 недели болталась и без рассмотрения отказано (может ошибаюсь)

На портале в моем журнале картина следующая:
![igov](https://cloud.githubusercontent.com/assets/19726339/15920800/8cc6608e-2e25-11e6-9df3-4826324043a2.png)

Еще из замечаний:
1. Не было самого первого письма с извещением, что заявка принята в работу
2. Очень раздражает отсутствие какой-либо информации в течение 1,5 недель. Нужно какое-то информирование.

Пожелания (что бы мне облегчило жизнь, если бы было):
1. Возможность оформить электронные версии протокола и устава (если это позволяет законодательство). Для модельного устава - достаточно протокола. Чтобы на сайте (или в папке24) была форма, в которой заполнил учредителей, доли, директора (может еще что-то), все участники заверили это электронными подписями и отправили регистратору.
2. Чтобы решить проблему задержек с регистрацией ТОВ, возможно нужно сделать, как при регистрации на получение паспорта:  сразу расписывается время, когда заявка будет рассмотрена. Тогда я не буду ждать в неизвестности - я буду знать, что такого-то числа в такое-то время мне нужно быть перед компьютером и за 15-30 мин выполнить те действия, которые скажет регистратор.

**Comment by gralexiv** [comment]
Добрій день!

Подал заявку повторно.
Дата подачи 13.06.16. Номер заявки 0-319745471.
Первое уведомление получил. Дальше тишина. Можно как-то сделать, чтобы с ней нормально поработали?
Спасибо!

**Comment by gralexiv** [comment]
Я так понимаю, с Вашего пинка процесс пошел. В заявке отказано.
Теперь подробнее: 
Я получил ответ:

> Шановний(-а),
>
>Ваше звернення №0-319745471 на тему "Державна реєстрація створення юридичної особи", >опрацьовано і по ньому винесено рішення про відмову в реєстрації.
>
>Коментар держслужбовця (Причина: не доданий установчий документ)
 

Мои действия при заполнении заявки
- В регистрационной форме заполнены все поля, 
- выбран модельный устав, 
- не плательщик НДС и ЕН 
- далее нажимаем на волшебную кнопку "**замовити послугу**", далее подпись и все: "заявка в обробці". 
Больше там ничего сделать было нельзя.
Где собственно нужно было загрузить "установчий документ" ?

Более того, сделано все как в инструкции "Як працює", в которой тоже ничего не упоминается о загрузке документов (только заявы для налоговой).

Так как я хочу, чтобы этот проект заработал и время мне позволяет, то я принципиально хочу, чтобы мое ТОВ было зарегистрировано через iGov
Я думаю, нам совместно нужно понять, где, что не так сработало. 
Перед тем как я подам заявку следующий раз, я хочу понять, в чем причина отказов мне:
1. Это был необоснованный отказ?
2. Если был выбран модельный устав, может все-таки необходимо что-то еще загрузить (например, протокол собрания учредителей)? Тогда необходимо указать явно поле, куда этот документ нужно загрузить в случае, если выбран модельный устав или откорректировать инструкцию, если скан протокола загружается уже после подачи заявки.
3. Может быть модельный устав не принимается и нужно обязательно делать свой устав и загружать скан? Тогда нужно об это явно сказать
4. Что-то еще? Давайте определим вместе

Надеюсь на плодотворное сотрудничество и ответы. Спасибо!

**Comment by gralexiv** [comment]
Так как здесь реакции нет, то я это обращение закрою и открою новое.
