### ISSUE TITLE
Срок обработки заявления.

### ISSUE THREAD

**Issue by Lilydp** [e-government-ua/iForum#43]
Я подала заявление на оформление субсидии 26 сентября. Вчера исполнился месяц. Есть ли надежда на завершение процесса? На сайте написано 20 рабочих дней :(

**Comment by dmitrijzabrudskij** [comment]
подскажите район и номер заявки - проверю. или фио, если нет номера

**Comment by Lilydp** [comment]
4835940
Спасибо.

**Comment by dmitrijzabrudskij** [comment]
так а район какой?

**Comment by Lilydp** [comment]
Днепропетровск, Жовтневый.

**Comment by dmitrijzabrudskij** [comment]
Вам назначили субсидию) решение о ее назначении лежит в районном отделе соцзащиты. но должны прислать Вам копию его на имейл - если в течение 2 дней не пришлют, поднимите снова эту тему

**Comment by Lilydp** [comment]
Большое спасибо.

**Comment by yarik1983** [comment]
У меня такая же ситуация. Подали заявку 21 сентября. Днепропетровск, Ленинский район, номер 4202273

**Comment by Lilydp** [comment]
Сегодня пришло такое письмо:

На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг відхилене через недостатню або неправильну інформацію..

Причина: Субсидия назначена. Сделан перерасчет на отопительный период. Получать пр.Героев, 40, 9 окно.

Звертаємо увагу, Ви можете заповнити заявку повторно на порталі iGov.org.ua

Объясните, пожалуйста.

**Comment by dmitrijzabrudskij** [comment]
объясняю: саботаж со стороны района -  должны были скан отправить без визитов
будем разбираться
спасибо за сигнал

**Comment by Lilydp** [comment]
Спасибо.

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
