### ISSUE TITLE
Державна реєстрація створення фізичної особи – підприємця. Звернення № 0-254940798

### ISSUE THREAD

**Issue by alexeyshapka** [e-government-ua/iForum#430]
Добрый день! 23.05.2016 подал заявку на регистрацию ФОП (Звернення № 0-254940798). Прошло уже почти 2 недели. Подскажите, когда можно ожидать ответ по заявке? Заранее спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день!

в начале следующей недели сделают, извините за задержку
