### ISSUE TITLE
Видача/заміна паспорта громадянина для виїзду за кордон

### ISSUE THREAD

**Issue by Valadey** [e-government-ua/iForum#431]
Добрый день! Подскажите пож-та когда обновится запись по ул. Поля 1. Дат на данный момент свободных нет. Или идти в порядке живой очереди?

**Comment by Koffeek** [comment]
@Valadey Добрый день. На данный момент полностью расписана очередь на июнь. На следующей неделе после совещания в ДМС мы сможем или увеличить количество записей на июнь или откроем запись на июль.

**Comment by Valadey** [comment]
Дело в том что я записывался на 3.06.2016 пришел со всеми оплатами и пакетом документов. Сотруднице не понравился оттиск на второй фотографией ( плохо видно ), сказали сделать новый. и теперь мне нужно опять делать запись и ждать месяц? Или идти в порядке живой очереди. реально вообще попасть к ним в порядке живой очереди. P.S. По времени записи очень трудно попасть т.к. людям которые стоят в очереди глубоко не интересно что у тебя запись на конкретное время.
