### ISSUE TITLE
Отримання/заміна паспорта громадянина України для виїзда за кордон

### ISSUE THREAD

**Issue by PilipOK** [e-government-ua/iForum#432]
Заява 0-182407061.
Моя заява була зареєстрована 23.04.16р. Дата прийому 24.06.16р. Залишилось менше 20 днів, але підтвердження, та бланків документів мені ще не надіслано. Мені вже кажуть що треба самому піти і звернутися до центру та встати на чергу. Що мені робити? Не зрозуміло навіщо створювати портал, якщо це не працює.

**Comment by Koffeek** [comment]
@PilipOK Подивіться уважно папку Спам за 23,04,2016 р. лист може знаходитись там. Якщо його там немає, то напишіть, будь ласка, до якого саме підрозділу ДМС Ви подавали заявку. Ми надішлемо листа ще раз.

**Comment by PilipOK** [comment]
Листа не було я перевірив. Заява подавалась до підрозділу ДМС м.Нікополь, вул. Микитинська, 5.

**Comment by Koffeek** [comment]
@PilipOK отправил повторное сообщение.
