### ISSUE TITLE
Державна реєстрація створення юридичної особи м. Харків

### ISSUE THREAD

**Issue by Anirma** [e-government-ua/iForum#433]
Звернення № 0-280085106 з 31.05.2016 в обробці. Який регламент щодо виконання цієї послуги ? Чи можна прискорити її виконання ?

**Comment by Anirma** [comment]
Добрий день,  заявку закрили, мотивуючи тим що не були вказані паспортні дані, але ж паспортні дані я вказувала при заповнені. Як це перевірити ? У кабінеті не відкривається подана заявка? Та що робити, заново подавати заявку, чи тільки написати у коментарі паспортні дані?

**Comment by dmitrijzabrudskij** [comment]
добрый день
подайте новую заявку и сбросьте ее номер сюда

**Comment by Anirma** [comment]
Номер нової заявки 0-302317251

**Comment by Anirma** [comment]
Добрый день, номер новой заявки   0-302317251, паспортные данные 2-ух учредителей указала, один за другим через запятую и еще поменяла адрес проживания, в прошлой заявке я указывала по прописке ( Луганск), в новой адрес фактического проживания в Украине, г. Глухов, Сумская обл. Очень буду благодарна за рассмотрения заявки в ближайшее время, так как хочу подать заявления на упрощенную систему налогообложения и НДС до 10 июня, для меня это очень важно. Надеюсь на понимание, спасибо за быстрый ответ, жду новостей. 

>Вторник,  7 июня 2016, 11:40 +03:00 от dmitrijzabrudskij <notifications@github.com>:июля начать работать
>
>добрый день
>подайте новую заявку и сбросьте ее номер сюда
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Ирина Землякова
22012410@mail.ru

**Comment by Anirma** [comment]
Добрый день, помогите зарегистрировать ООО. Подала заявку, аналогичную первой 0-302317251, ответ пришел следующий. 
Коментар держслужбовця (Причина: документи подані не в повному обсязі (відсутнє рішення засновника), заява заповнена некоректно (такий район області відсутній, двічі внесено засновника, КВЕДи внесені некоректно, чому дані про 2 паспорта) що за адреса м. Луганськ прослуджується при перевірці ЕЦП)
Мне хотелось бы уточнить?
1. Какое решение учредителя нужно дополнительно? Где оно отображается в форме или это письменный документ, который прикрепляется?
2. Не указано, какой именно район я указала не правильно, если Холодногорский г. Харькова, то да было 2 района Ленинский и Октябрьский, а теперь оба переименовали в Холодногорский.
3. Дважды внесен основатель. Не совсем понятно, можно скрин по форме.
4. КВЕДы, копировались с той ссылки которая предоставлена была для ознакомления, когда вбивалась цифра КВЕДа, так как я ранее отправляла аналогичную заявку, он автомотически подтягивался и горел желтым светом.
5. При подаче первой заявки, я указала только свой паспорт, но мне пришел ответ
Коментар держслужбовця (В заяві про державну реєстрацію створення юридичної особи не заповнені всі обов'язкові поля. Зверніть увагу, що серія та номер паспорта у відомостях про засновника є обов'язковими для заповнення (дивіться розшифровку зірочок). Рекомендуємо усунути недоліки та подати заяву повторно.)
При подаче второй заявки, я указала 2 паспорта 2-ух соучредителей.
6. По поводу ЕЦП. Я из Луганска, у меня Луганская прописка, и первую заявку я подавала с адресами по прописки, но прочитав на вашем сайте комментарий по https://github.com/e-government-ua/iForum/issues/439. А точнее: можно зарегистрировать как по месту прописки, так и по месту проживания - учтите это при подаче заявки. если же будете регистрировать по месту прописки, то возможен отказ - в том случае, когда Ваш адрес входит в число оккупированных территорий или зоны проведения АТО.
Я указала адрес проживания фактический по справке ВПО в Украине и  в форме написано, что нужно указывать фактическое место проживание. Юридический адрес указан согласно договору аренды по г. Харьков, где планируется открывать ООО.
 Возможно ли заново не подавать заявку, а просто выслать на почту паспортные данные, согласно первой заявки, т.к. замечаний по ней кроме паспортных данных никаких не было? И как быть с адресом для переселенцев, какой указывать по справке ВПО или по прописке?
Жду ваш ответ. Спасибо за понимание и помощь.

**Comment by Anirma** [comment]
Добрый день, помогите зарегистрировать ООО. Подала заявку, аналогичную первой 0-302317251, ответ пришел следующий. 
Коментар держслужбовця (Причина: документи подані не в повному обсязі (відсутнє рішення засновника), заява заповнена некоректно (такий район області відсутній, двічі внесено засновника, КВЕДи внесені некоректно, чому дані про 2 паспорта) що за адреса м. Луганськ прослуджується при перевірці ЕЦП)
Мне хотелось бы уточнить?
1. Какое решение учредителя нужно дополнительно? Где оно отображается в форме или это письменный документ, который прикрепляется?
2. Не указано, какой именно район я указала не правильно, если Холодногорский г. Харькова, то да было 2 района Ленинский и Октябрьский, а теперь оба переименовали в Холодногорский.
3. Дважды внесен основатель. Не совсем понятно, можно скрин по форме.
4. КВЕДы, копировались с той ссылки которая предоставлена была для ознакомления, когда вбивалась цифра КВЕДа, так как я ранее отправляла аналогичную заявку, он автомотически подтягивался и горел желтым светом.
5. При подаче первой заявки, я указала только свой паспорт, но мне пришел ответ
Коментар держслужбовця (В заяві про державну реєстрацію створення юридичної особи не заповнені всі обов'язкові поля. Зверніть увагу, що серія та номер паспорта у відомостях про засновника є обов'язковими для заповнення (дивіться розшифровку зірочок). Рекомендуємо усунути недоліки та подати заяву повторно.)
При подаче второй заявки, я указала 2 паспорта 2-ух соучредителей.
6. По поводу ЕЦП. Я из Луганска, у меня Луганская прописка, и первую заявку я подавала с адресами по прописки, но прочитав на вашем сайте комментарий по  #439 . А точнее: можно зарегистрировать как по месту прописки, так и по месту проживания - учтите это при подаче заявки. если же будете регистрировать по месту прописки, то возможен отказ - в том случае, когда Ваш адрес входит в число оккупированных территорий или зоны проведения АТО.
Я указала адрес проживания фактический по справке ВПО в Украине и в форме написано, что нужно указывать фактическое место проживание. Юридический адрес указан согласно договору аренды по г. Харьков, где планируется открывать ООО.
Возможно ли заново не подавать заявку, а просто выслать на почту паспортные данные, согласно первой заявки, т.к. замечаний по ней кроме паспортных данных никаких не было? И как быть с адресом для переселенцев, какой указывать по справке ВПО или по прописке?
Жду ваш ответ. Спасибо за понимание и помощь.

>Вторник,  7 июня 2016, 11:40 +03:00 от dmitrijzabrudskij <notifications@github.com>:
>
>добрый день
>подайте новую заявку и сбросьте ее номер сюда
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Ирина Землякова
22012410@mail.ru

**Comment by dmitrijzabrudskij** [comment]
добрый день
по вопросам:
1. прикрепить файлом. если такого отдельного поля на форме нет, то прикрепите архивом несколько документов. или дошлите в комментариях к заявке недостающие файлы
2. тут ошибка регистратора - в реестре, где они заводят данные о юридическом лице, районы указаны с названиями еще до переименования.
3. и правда дважды были Вы внесены (если выбираете, что заявитель совпадает с учредителем, то нет необходимости потом себя снова вписывать - допишите только второго учредителя)
4. только цифры через точку указывайте. у Вас были и расшифровки - этого не нужно
5. тоже свой не нужно заново вписывать, если авторизовывались через bankid 
6. это уже подозрительность регистратора - самое главное, чтобы подпись была действительной

нужна новая заявка, дослать в закрытые уже нельзя
сбросьте ее номер, когда сделаете - прослежу чтобы регистратор учла те ошибки, которые тут описаны

**Comment by Anirma** [comment]
Добрый день, отправила новую заявку    0-344625423 . Зашла через ID BANK, смотря на вышесказанное, мои документы должны подтянуться автоматически ( паспорт, инн), так как при заполнении формы отсутствует возможность прикрепить документ. Жду результат, спасибо за помощь.

>Пятница, 10 июня 2016, 15:52 +03:00 от dmitrijzabrudskij <notifications@github.com>:
>
>добрый день
>по вопросам:
>1. прикрепить файлом. если такого отдельного поля на форме нет, то прикрепите архивом несколько документов. или дошлите в комментариях к заявке недостающие файлы
>2. тут ошибка регистратора - в реестре, где они заводят данные о юридическом лице, районы указаны с названиями еще до переименования.
>3. и правда дважды были Вы внесены (если выбираете, что заявитель совпадает с учредителем, то нет необходимости потом себя снова вписывать - допишите только второго учредителя)
>4. только цифры через точку указывайте. у Вас были и расшифровки - этого не нужно
>5. тоже свой не нужно заново вписывать, если авторизовывались через bankid 
>6. это уже подозрительность регистратора - самое главное, чтобы подпись была действительной
>нужна новая заявка, дослать в закрытые уже нельзя
>сбросьте ее номер, когда сделаете - прослежу чтобы регистратор учла те ошибки, которые тут описаны
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Ирина Землякова
22012410@mail.ru

**Comment by agerman-ua** [comment]
Добрый день, @Anirma 
Простите за задержку с ответом, ещё 04.07 заявка закрыта по Вашему запросу.
Должно было прийти письмо с подтверждением.
С уважением. Август
