### ISSUE TITLE
Справки: 1. Про наличие или отсутствие судимости; 2. Про отсутствие задолженности по налогам

### ISSUE THREAD

**Issue by IaroslavOliinyk** [e-government-ua/iForum#434]
Добрый день. 
Скажите пожалуйста, разглядываются ли вцелом заявки №: 0-290625770, 0-288689535 ? 

Дело в том, что ранее были пробы получить выписки из реестров МВД. И ни одна из них не была обработана, хотя прошло более полугода. И есть опасение, что таким же образом не будут получены и вышеуказанные справки. Т.е. может есть смысл идти и получать вручную, не тратя зря время? Спасибо.

**Comment by kurbpa** [comment]
0-288689535 - Справка о несудимости - Дата создания 2016-06-01. Срок обработки заявки - до 20 рабочих дней. По Днепропетровску  услуга   действует.

> Дело в том, что ранее были пробы получить выписки из реестров МВД. И ни одна из них не была обработана, хотя прошло более полугода. 

К сожалению, емейлы с ответами часто попадают в спам. Заявки же по реестрам МВД обрабатываются все без исключения, т.к. отработка идет в автоматическом режиме без участия человека.

**Comment by IaroslavOliinyk** [comment]
Ну например заявка: 0-216470677. Дата подачи 02.05.16. Состояние - в обработке. На почте папка спам отключена. Более ранние запросы все тоже в статусе - в обработке, но переходя по ним пишет "Сторінку не знайдено".

**Comment by kurbpa** [comment]
Конкретно по услуге реестров МВД  есть дефект с обновлением состояния заявки. 
По факту заявка обработана и закрыта. 
Видимо используемый нами почтовый сервис, к сожалению, не обеспечил успешную отправку емейла на Ваш ящик. Мы боремся с этим.
Буквально на прошлой неделе нам удалось подключить к услугам СМС-информирование, как альтернативный канал оповещения об изменении   статуса заявки.
