### ISSUE TITLE
заявка № 0-291144495 - изменение прописки ФОП

### ISSUE THREAD

**Issue by VasilenkoLN** [e-government-ua/iForum#435]
Здравствуйте! 2 июня 2016 г на сайте igov.org.ua  в 13:12 подала заявку №  0-291144495 на изменение прописки ФОП.Заявку приняли и присвоили статус "в обробці" .Прошло уже три дня никаких изменений в статусе заявки так и не произошло.Я начала сомневаться работает ли этот сайт вообще?Сколько мне еще ждать чтоб прислали мне квитанцию к оплате? И потом сколько ждать чтоб изменения внесли в реестр? Мне нужно срочно внести изменения.Можно ли ускорить этот процесс? Заранее спасибо за ответ.

**Comment by VasilenkoLN** [comment]
Подскажите пожалуйста ,что означает  "Заявка закрита - Надання послуги (2)"

**Comment by dmitrijzabrudskij** [comment]
добрый день
это значит, что заявка прошла первичную проверку, она принята, и теперь госрегистратор ожидает поступления оплаты за внесение изменений в регистрационные данные (изменение адреса является платным) - после поступления оплаты заявку обработают окончательно и внесут изменения в реестр

Вам было отправлено письмо, в котором есть кнопка, через которую Вы можете в онлайне оплатить услугу

**Comment by VasilenkoLN** [comment]
Спасибо за разъяснение.Еще пожалуйста ответьте на один вопрос.В течении какого времени после оплаты будут внесены изменения? (а то сроки поджимают).Судя по вопросам на сайте -ждут больше двух недель.К сожалению у меня нет возможности столько ждать.Мне нужно в течении двух дней.Возможно ли в такие сроки?
с Ув.Лариса

06.06.2016 17:37, dmitrijzabrudskij <notifications@github.com>
>добрый день
> это значит, что заявка прошла первичную проверку, она принята, и теперь госрегистратор ожидает поступления оплаты за внесение изменений в регистрационные данные (изменение адреса является платным) - после поступления оплаты заявку обработают окончательно и внесут изменения в реестр
> 
> Вам было отправлено письмо, в котором есть кнопка, через которую Вы можете в онлайне оплатить услугу
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/e-government-ua/iForum/issues/435#issuecomment-223978415


-- реклама -----------------------------------------------------------
Дистанционный курс MINI-MBA. Акционная скидка 68%
Цена 7800 грн. http://goo.gl/1dpFdJ

**Comment by dmitrijzabrudskij** [comment]
да, после оплаты в течение 2 дней будет внесено. что касается вопросов на сайте - речь о том, чтобы заявка попала в работу - это бывает долго, да. но у Вас другая ситуация - заявка УЖЕ в работе. и ждет оплаты

**Comment by VasilenkoLN** [comment]
Подскажите пожалуйста,я только что оплатила.Как посмотреть ,прошла оплата или нет,потому что никаких сообщений не было.Извините за беспокойство,но непонятно работает сайт.
Спасибо!

07.06.2016 11:25, dmitrijzabrudskij <notifications@github.com>
>да, после оплаты в течение 2 дней будет внесено. что касается вопросов на сайте - речь о том, чтобы заявка попала в работу - это бывает долго, да. но у Вас другая ситуация - заявка УЖЕ в работе. и ждет оплаты
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/e-government-ua/iForum/issues/435#issuecomment-224213195


-- реклама -----------------------------------------------------------
Дистанционный курс MINI-MBA. Акционная скидка 68%
Цена 7800 грн. http://goo.gl/1dpFdJ

**Comment by VasilenkoLN** [comment]
Может Приват 24 не работает? Потому что нажимаю продолжить и тишина???Или оно автоматом должно снять??? Может я уже два раза оплатила??Подскажите пожалуйста!!!!!

**Comment by dmitrijzabrudskij** [comment]
Вы еще ничего не оплатили
нажмите на кнопку "оплатить" из письма, которое пришло от igov, и дальше следуйте инструкциям.

**Comment by dmitrijzabrudskij** [comment]
нужно будет ввести реквизиты карты, подтвердить оплату - автоматом ничего не спишется

**Comment by agerman-ua** [comment]
Добрый день,
Обращение успешно закрыто 10.06.2016.
