### ISSUE TITLE
Внесення нових КВЕД (ФОП)

### ISSUE THREAD

**Issue by kmm1974** [e-government-ua/iForum#436]
По заяві 0-245463430 з 18 травня йде перевірка наданих даних. Це взагаллі працює? Минулого року у державного реєстратора таке питання було вирішене протягом 2-х годин!

**Comment by dmitrijzabrudskij** [comment]
заявка в работе. в течение сегодня-завтра будет ответ
сроки такие из-за наплыва желающих - по правде говоря, не рассчитали.. извините

**Comment by kmm1974** [comment]
Спасибо, жду :)

**Comment by agerman-ua** [comment]
Заява №0-245463430 закрита позитивно 07.06.2016. Вибачте за загальну затримку. Тоді це було досить масове явище. Зараз такого вже немає.
