### ISSUE TITLE
Державна реєстрація створення фізичної особи – підприємця. Звернення № 0-274058439

### ISSUE THREAD

**Issue by IgGord** [e-government-ua/iForum#437]
заявка оформлена 30.05, досі немає відповіді. коли можна очікувати? дякую

**Comment by IgGord** [comment]
07.06.2016 16:49

Ваша заявка №0-274058439 змiнила свiй статус на закрита-   що це означає? ніякого листа не надходило. моя заявка відхилена? як можна дізнатись подробиці?

**Comment by dmitrijzabrudskij** [comment]
в любом случае (положительный/отрицательный) будет письмо в почту - проверьте спам на всякий случай

**Comment by IgGord** [comment]
в спамі теж пусто..

**Comment by IgGord** [comment]
нарешті отримав відповідь:
_____________
Ваше звернення №0-274058439 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.

Коментар держслужбовця (Причина: Заява заповнюється укр мовою (адреса). Не зазначені: назва вулиці, номер будинку та квартири. Позначено, що додається заява обрання спрощенної системи оподаткування, але файл не прикріплений.)
_______________
це при тому, що все було зазначено, файл було прикріплено
що взагалі відбувається? якщо щось не так, навіщо тягнути скільки часу? як можна перевірити? я точно все заповнив. це збій системи,помилка чиновника чи що?

**Comment by agerman-ua** [comment]
Доброго дня, @IgGord 
Вибачте за затримку.
Дійсно файл з заявою щодо обрання спрощенної системи оподаткування відсутній у Вашому зверненні. Ми дуже пильно це перевірили. На жаль це трапилось саме під час подання Вами звернення, скоріш за все Ви планували приєднати файл (або приєднали але файл був завеликий -більше 5 мб). Оскільки далі файли вже автоматично приєднані до звернення і ніхто на них не може вплинути або видалити.
А щодо адреси українською мовою (дійсно дані вказані російською мовою) - то зараз є можливість виправлення таких зауважени без закриття звернення громадянина.
На жаль раніше такої змоги не було.
З повагою, Август.
