### ISSUE TITLE
Что значает "Заявка закрыта" ?

### ISSUE THREAD

**Issue by VasilenkoLN** [e-government-ua/iForum#438]
Подскажите пожалуйста ,что означает "Заявка закрита - Надання послуги (2)" и  "Ваша заявка №0-291144495 змiнила свiй статус на Надання послуги (2)"

**Comment by agerman-ua** [comment]
В Вашем случае 10.06.2016 была закрыта полностью и успешно. Поздравляем. А описанное Вами состояние - был переход на следующий этап обработки.
