### ISSUE TITLE
Можно ли через вас оформить заявку на оформление ФОП переселенцу без регистрации переселенца.

### ISSUE THREAD

**Issue by demchenkoa** [e-government-ua/iForum#439]
Спасибо за быстрый ответ это важно, так как времени на оформление почти нет.

**Comment by dmitrijzabrudskij** [comment]
фоп можно зарегистрировать как по месту прописки, так и по месту проживания - учтите это при подаче заявки. если же будете регистрировать по месту прописки, то возможен отказ - в том случае, когда Ваш адрес входит в число оккупированных территорий или зоны проведения АТО

**Comment by koi8** [comment]
Если вам нужно быстро, то igov пока не лучший для этого вариант, пойти и сделать оффлайново гораздо быстрее :\

**Comment by demchenkoa** [comment]
Закройте мою заявку пожалуйста, уже открыл фоп оффлайново, тему открывал уже
