### ISSUE TITLE
Видача паспорта дитини для поїздок за кордон

### ISSUE THREAD

**Issue by roman-vs** [e-government-ua/iForum#440]
Не можу вибрати день для звернення до міграційної служби і замовити послугу "видача паспорта громадянина для виїзду за кордон для дитини". Змінював підрозділи ДМС - безрезультатно. Дніпро. Савенко Роман Володимирович для Софії Романівни.

**Comment by Olexii1980** [comment]
Та же ситуация. Днепр. Не активно поле для выбора даты. Соответственно, услугу заказать нельзя.
![_](https://cloud.githubusercontent.com/assets/19856755/15963699/b0104a3a-2f1c-11e6-9ac9-e02b6096c5ca.JPG)
