### ISSUE TITLE
Реєстрация ФОП

### ISSUE THREAD

**Issue by Hanna033** [e-government-ua/iForum#441]
Звернення № 0-259151421 від 24.05 вже 2 тижні і все в обробці! З чим пов'язане?

**Comment by dmitrijzabrudskij** [comment]
Валерия, извините за задержку - в понедельник обработают

**Comment by agerman-ua** [comment]
Доброго дня, @Hanna033 
Бачу що Вам знову тоді відмовили.
З того часу ми зробили певні зміни враховуючи статистику тому зараз є можливість внесення змін до введених даних без закриття звернення.
З повагою, Август.
