### ISSUE TITLE
Не приходит оповещение с номером на почту

### ISSUE THREAD

**Issue by stepanchenko1** [e-government-ua/iForum#444]
Здравствуйте! Отправил сегодня заявку на открытие ФОПа. 
На последнем шаге регистрации получил нотификейшн об успешном завершении + о получении номера заявки на почту. Оповещение на почту так и не пришло. 

Скрин прикрепляю:
http://image.prntscr.com/image/3cefd1e308a64f5fb10a625b944f8b1f.png

**Comment by dmitrijzabrudskij** [comment]
добрый день!

искали письмо в спаме?

**Comment by stepanchenko1** [comment]
конечно
http://prntscr.com/bdfkax
может есть возможность изменить имел на домен @gmail?

**Comment by koi8** [comment]
на gmail тоже перестало приходить..

**Comment by stepanchenko1** [comment]
Надеюсь,что эту багу они пофиксят.

@mitrijzabrudskij, ждем обратной связи

**Comment by agerman-ua** [comment]
Обращение № 0-304256582 закрыто 10.06.2016. Отказ - "Заява заповнюється на державній мові"
