### ISSUE TITLE
Отримання довідки про доходи фіз. осіб. Заявка №0-294951397

### ISSUE THREAD

**Issue by primeanton** [e-government-ua/iForum#445]
03.06.2016 13:50 подал заявку №0-294951397 в налоговую инспекцию г.Марганца Днепроп.обл. на получение справки о доходах физ лица. Заявка имела статус "в обробці". 07.06.2016 17:04 статус заявки изменился на "закрито". Означает ли это, что я могу уже сейчас прийти в налоговую и получить готовую справку о доходах? Или это означает, что моя заявка забракована? или другие какие-либо варианты? Подскажите, пожалуйста, значение статуса заявки "закрито". Спасибо

**Comment by dmitrijzabrudskij** [comment]
это значит, что заявка ушла в налоговую (Вам в этот момент приходит имейл с инструкциями что и когда нужно сделать)

**Comment by primeanton** [comment]
На эл.почту сообщения с инструкцией не поступали. Только в личном кабинет igov 07.06.2016 в 17:04 пришло уведомление "Ваша заявка №0-294951397 змiнила свiй статус на закрита". Вы можете прислать инструкции?

**Comment by dmitrijzabrudskij** [comment]
проверьте спам

**Comment by primeanton** [comment]
проверял, конечно. пусто.

**Comment by dmitrijzabrudskij** [comment]
дайте почту

**Comment by primeanton** [comment]
primeanton@gmail.com

**Comment by dmitrijzabrudskij** [comment]
отправил инструкцию

**Comment by primeanton** [comment]
читаю, спасибо
