### ISSUE TITLE
Регистрация в очереди на получение загранпаспорта

### ISSUE THREAD

**Issue by AnnaKamluk** [e-government-ua/iForum#447]
Добрый вечер! Не могу зарегистрироваться в очередь на получение загранпаспорта, так как являюсь владельцем карты Альфа-банк, банк отсутствует в перечне банков. Есть ли еще какая-то возможность регистрации?Спасибо!

**Comment by koi8** [comment]
Вы можете получить ЕЦП бесплатно в центре http://acskidd.gov.ua
