### ISSUE TITLE
получение паспорта сыну в 16 лет

### ISSUE THREAD

**Issue by 76Alex** [e-government-ua/iForum#449]
Добрый день. Подскажите почему не получается выбрать дату и время при оформлении заявки на получение паспорта сыну в 16 лет

**Comment by 76Alex** [comment]
И подскажите еще, пожалуйста, есть ограничения по времени оформления? См 9 до 17 или в любое время?

**Comment by AndreyPopovNew** [comment]
потому что нет свободных тайм-слотов (все уже разобрали)

**Comment by 76Alex** [comment]
Так можно же через 2 или 3 недели дату и время установить?Программа же не дает так4ой возможности выбора.......... Или я что-то не понимаю? Прошу ответить разработчиков!

**Comment by AndreyPopovNew** [comment]
открывают запись на месяц. на июнь уже все разобрали, раз пусто в списках. когда откроют на июль - наверное после 20-25 числа.

**Comment by 76Alex** [comment]
Спасибо, Андрей, за комментарии. Это непонятное ограничение  в оформлении заявки только на месяц............

**Comment by AndreyPopovNew** [comment]
@76Alex по словам разработчиков:
- каждое отделение ДМС выделяет на электронную очередь ограниченное часовое окно - 4 часа (из 8-ми приемных )
- на каждого человека отводится 10-15 мин 
- т.е. 4-5 человека в час
- до 20 человек в день

ну а запись возможна только на один месяц.
по словам разработчиков КАЖДЫЙ месяц размер окна и количество тайм-слотов каждый месяц уточняются
