### ISSUE TITLE
ПОМИЛКА SYSTEM_ERR For input string "+380 99 1

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#45]
![2](https://cloud.githubusercontent.com/assets/12669290/10788610/336bec48-7d81-11e5-8aa3-534dcd6f5e01.jpg)
Пост у ФБ: https://www.facebook.com/photo.php?fbid=988688917862116&set=o.1589199384702272&type=3
Автор Ольчик Белогурова‎ https://www.facebook.com/belagolga

**Comment by dmitrijzabrudskij** [comment]
телефон без пробелов нужно вводить.

**Comment by VadymVolos** [comment]
Дякую! 
Але там нам треба написати це зрозумілою мовою. Або приклад написати як вірно телефон вводити.

**Comment by dmitrijzabrudskij** [comment]
я сейчас как раз занимаюсь этим процессом. добавлю валидатор. но вообще - если номер вводить по цифрам, а не копировать, там все нормально получается

**Comment by kilotaras** [comment]
@dmitrijzabrudskij якщо дасте мені напрям то можу https://github.com/googlei18n/libphonenumber прикрутити. Демо тут https://libphonenumber.appspot.com/
