### ISSUE TITLE
Заявка на изменение данных ФОП пошла 3 неделя

### ISSUE THREAD

**Issue by NicolayM** [e-government-ua/iForum#450]
Здравствуйте! 23.05.16 в 10.45 была отправлена заявка №0-254215175 (державна реєстрація змін до відомостей про ФОП (з заповненням заяви онлайн) - добавление номера телефона. До сих пор статус - перевірка даних. С удивлением прочитал, что заявка №0-291144495 от 02.06.16 (изменение прописки ФОП) уже в обработке данных, хотя подана значительно позже. Ребята, как вы выбираете заявки к обработке. Явно не в порядке очереди. Сколько еще ждать?

**Comment by dmitrijzabrudskij** [comment]
добрый день
сегодня сделают
не в порядке очереди получилось, потому что было обращение от автора 291144495  на форуме (собственно, ровно такое же, как и Ваше)

**Comment by NicolayM** [comment]
Здравствуйте! 08.06. заявка была закрыта и получила статус  "надання послуги". Но на e-mail нет никакого сообщения об этом. Папка спам пустая. На сайте минюста изменения не внесены. Подскажите, когда можно ожидать окончательный результат. Спасибо.
