### ISSUE TITLE
Звернення № 0-305441362 - заявка закрита, листів немає, змін у держреєстрі - також.

### ISSUE THREAD

**Issue by sauveteur** [e-government-ua/iForum#451]
08.06.2016 00:23
Ви подали заявку на послугу Державна реєстрація змін до відомостей про фізичну особу – підприємця (з заповненням заяви онлайн). Cтатус: Перевірка наданих даних (1)

- на пошті листа немає (так, спам перевіряв).

08.06.2016 09:40
Ваша заявка №0-305441362 змiнила свiй статус на закрита

- на пошті так само ніц немає. У держреєстрі змін немає (подавав нові кведи).
Що з тим робити? Яким чином дізнатися результат?

**Comment by agerman-ua** [comment]
Добрий день, 
Вам було відмовлено.
Вибачте але лист повинен бути. 
Можливо він вже прийшов за цей час?
З повагою.

**Comment by sauveteur** [comment]
Доброго дня!

Лист досі не прийшов.
Як я можу дізнатися про причину відмови? 

10 червня 2016, 17:28:20, від "agerman-ua" <notifications@github.com>:

**Comment by agerman-ua** [comment]
@sauveteur 
Доброго дня.
Реєстратором була сформульована така відповідь "Причина: Не має даних електроного підпису".
А Ви отримували хоч якогось листа? Можливо Ви вказали помилкову адресу при поданні заявки?
З повагою.

**Comment by sauveteur** [comment]
Доброго дня!

Заявку було підписано електронним підписом, отриманим у Приват24, інакше вона просто не була би прийнята системою, наскільки я розумію - чи не так?

Ніяких листів не надходило, адресу я написав вірно і перевірив перед відправленням, папку "спам" постійно моніторю.

Що треба зробити, щоб заявка була прийнята? Чи є прийнятним підпис від Приват24, чи треба отримувати якийсь інший?

13 червня 2016, 14:30:49, від "agerman-ua" <notifications@github.com>:

**Comment by agerman-ua** [comment]
Ні. ЕЦП від Привата не є обов'язковою умовою для надання послуги.
Можете використати будь-яку наявну дійсну ЕЦП.
На жаль, після закриття заявки ми обмежені в діях щодо листів. Наразі відпрацьовується механізм зберігання відправлених листів у журналі заявки. Щоб не залежити від поштовиків.

**Comment by sauveteur** [comment]
Доброго дня!

Питання, скоріше, у тому, чи є ЕЦП Привата достатньою умовою, бо її єдину можна отримати, не виходячи з дому.
Гаразд, спробую згодом ще раз подати зміни, тіко вже з ґуґлопошти, бо, може, просто на укрнет воно не ходить.

Дякую!

14 червня 2016, 07:37:05, від "agerman-ua" <notifications@github.com>:

**Comment by agerman-ua** [comment]
Доброго дня, @sauveteur 
Як Ваші (наші) справи?
Якщо все в нормі - закрийте цю тему.
З повагою, Август.
