### ISSUE TITLE
Звернення № 0-303631959

### ISSUE THREAD

**Issue by roman-vs** [e-government-ua/iForum#453]
Доброго дня. Звернення є, але далі нічого не відбувається. Воно "в обробці", листів на имейл немає. Не зрозуміло приходити нам дату (13.06.), чи ні.

**Comment by Koffeek** [comment]
@roman-vs Доброго дня. Перевірте будь-ласка папку Спам, можливо лист знаходиться там. Якщо його немає, то вкажіть послугу, яку Ви замовляли, і в який підрозділ державного органу звертались. Дякую.

**Comment by roman-vs** [comment]
Теку я звісно перевірив. Послуга "Отримання паспорта громадянина України для виїзду за кордон для дитини". Звертався в Новокодацький ДМС м. Дніпро.

**Comment by Koffeek** [comment]
@roman-vs Відправив листа ще раз.

**Comment by roman-vs** [comment]
Дякую. Сьогодні отримав (і не в спамі :-)).
