### ISSUE TITLE
Державна реєстрація створення фізичної особи – підприємця - закрита

### ISSUE THREAD

**Issue by Byelyakov** [e-government-ua/iForum#454]
06.06.2016 13:06
Ви подали заявку на послугу Державна реєстрація створення фізичної особи – підприємця. Cтатус: Надання послуги (Звернення № 0-300001860)

08.06.2016 10:01
Ваша заявка №0-300001860 змiнила свiй статус на закрита

И всё, объяснений нет, регистрации нет, проверял на https://usr.minjust.gov.ua/ua/freesearch

непонятно, что с этим счастьем делать, пойду регистрироваться пешочком по старинке, жаль три дня потерял. В любом случае всем сопричастным - Спасибо, боритесь и поборите :-)

**Comment by dmitrijzabrudskij** [comment]
проверьте спам, пожалуйста - при любом исходе заявки отправляется имейл

**Comment by Byelyakov** [comment]
Я проверил, папка спама пустая, это новый почтовый ящик, есть только письмо про регистрацию заявки

>no reply <admin@igov.org.ua>
>Ваша заявка 0-300001860 прийнята!

**Comment by Byelyakov** [comment]
дякую тобі невідомий друг, після звернення сюди, я отримав листа:
>16:20
Ваше звернення №0-300001860 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
Коментар держслужбовця (Причина: п.5 ч.4 ст.9 місцезнаходження п.1 ч. 1 ст.15 державна мова)

якщо я отримав цього листа одразу то я би не звертався на github, тому що я відразу знайшов помилку, я сподіваюсь це вона і вона одна :-)
моє місто знаходження було заповнено російською, не зовсім моя помилка, тому що ця інформація прийшла з приват банку, прийдеться і туди зайти

**Comment by Byelyakov** [comment]
цирк продолжается, ну не хотят наши государевы мужи работать, на вторую заявку пришел ответ, 

>Ваше звернення №0-308056340 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
Коментар держслужбовця (Причина:Заява заповнюється на державній мові, не всі поля заповнені)

я только что проверил, все поля заполнены, все слова, все поля - на державній мові
не знаю что делать, в третий раз закинул я невод, буду ждать еще, платить им деньги и быть частью цепочки коррупции, мне принципиально не хочется

можно как то узнать, где они увидели отсутствие государственного языка и на какое поле они жалуются? Сложно пройти квест, если не знаешь правил

**Comment by Byelyakov** [comment]
кста в форме всего 5 мандаторных полей
-Прізвище
-Ім'я
-По Батькові
-Дата народження
-ІПН

я то заполнил все возможные, но в принципе пока мы не будем видеть, на кого была распределена заявка и кто ответственный за принятие решения, то ничего не будет и спросить не с кого. всем добра.

**Comment by agerman-ua** [comment]
Добрый день, @Byelyakov 
У Вас в заявке единственное русское слово КИЕВ.
Конечно неправильно так неконкретно отвечать, и отказывать тоже. Можно спокойно уточнить любое поле в адресе.
Мы работали всё это время плотно с чиновниками и сейчас уже редкость когда сразу отказывают по причине русских слов в адресе.
Но конечно какое-то количество людей положили своё личное время на алтарь для общей пользы.
В любом случае спасибо за использование нашего портала.
С уважением, Август.
