### ISSUE TITLE
Видача/заміна паспорта громадянина для виїзду за кордон

### ISSUE THREAD

**Issue by Valadey** [e-government-ua/iForum#455]
Добрый день! Если я сделал оплаты на один центр по выдачи паспорта, могу ли я сделать оплаты на другой и перезаписатся? Т.к. в данный отдел ( поля 1 ) дат нет для записи. Дело в том что я записывался на 3.06.2016 пришел со всеми оплатами и пакетом документов. Сотруднице не понравился оттиск на второй фотографией ( плохо видно ), сказали сделать новый. и теперь мне нужно опять делать запись и ждать месяц? Или идти в порядке живой очереди. реально вообще попасть к ним в порядке живой очереди?

**Comment by AndreyPopovNew** [comment]
ну другие ж как-то попадают в порядке живой очереди.

а так все конечно от сотрудника зависит.
дело было в прошлом году и на Красной - делал паспорт для ребенка.
фото ребенка не подошло, фотограф сделал именно портретный снимок, а надо чтобы лицо занимало не более 80% площади.
пришлось идти переделывать фото. так сотрудница сказала, если успеете переделать сегодня, то приходите в тот же день, я вам без очереди приму. вот так бывает.

**Comment by Koffeek** [comment]
@Valadey я задавал вопрос по Вашему случаю, ДМС обещали ответить, но пока ответа нет. Буду добиваться далее.

**Comment by Koffeek** [comment]
@Valadey На Поля попросили подойти в удобное время, и объяснить ситуацию "вы приходили по iGov, но не смогли подать заявку, по Вашей причине". Вас должны принять.
