### ISSUE TITLE
заявки №0-306489679, №0-306351561 (Надання витягу з Єдиного державного реєстру МВС України)

### ISSUE THREAD

**Issue by shevchenkobsn** [e-government-ua/iForum#457]
08.06.2016 р. подала заявки №0-306489679 та №0-306351561 на послугу:
(Загальна послуга) - Надання витягу з Єдиного державного реєстру МВС України
СМС-повідомлення про обробку на мій телефон надійшло, заявки змінили статус на "закрита", але витяги на електронну адресу не надійшли. Папка спам пуста, жодних листів в ній немає.

**Comment by annastolbova** [comment]
помилка виправлена ще у червні 2016, зараз все працює коректно
