### ISSUE TITLE
Регистрация изменений ФОП

### ISSUE THREAD

**Issue by belit** [e-government-ua/iForum#459]
Добрый день. Хотела бы узнать когда будут обработаны заявки на регистрацию изменений ФОП - №0-295763109
- №0-295601421

**Comment by dmitrijzabrudskij** [comment]
добрый день!
обе заявки приняты в работу и ждут оплаты

**Comment by belit** [comment]
Добрый день, а как оплатить картой? Я ввожу реквизиты карты, но не могу отправить платеж.

**Comment by dmitrijzabrudskij** [comment]
что пишет в качестве ошибки?

**Comment by belit** [comment]
Мне пришли смс о подтверждении платежа. Я их ввела по обеим заявках. Потом пишет что введя смс я соглашаюсь на условия этой платежной системы. Но деньги так и не списались.

**Comment by dmitrijzabrudskij** [comment]
отказ в оплате с карты от Вашего банка. не прошло завершение платежа. свяжитесь, пожалуйста, с Вашим банком

после того как карта будет готова к оплате, сформируйте новые заявки, пожалуйста (в этих обновить статус неуспешного платежа уже нельзя, к сожалению)
