### ISSUE TITLE
Призначення соціальної допомоги при народженні дитини

### ISSUE THREAD

**Issue by yalanskaya** [e-government-ua/iForum#46]
заявка 7944712, подана 2015-10-12, с 2015-10-15 "змiнила свiй статус на обработка этап 1 (у роботi)". просьба помочь узнать решение по заявке. спасибо!

**Comment by dmitrijzabrudskij** [comment]
какой район выбирали при подаче?

**Comment by yalanskaya** [comment]
самарский

**Comment by annastolbova** [comment]
Заявка закрита 25.11.2015, після звернення пройшло більше 60 днів
