### ISSUE TITLE
Заявка № 0-243446488 на додавання нових КВЕДІВ

### ISSUE THREAD

**Issue by Grishalinets** [e-government-ua/iForum#460]
Доброго дня!
Підкажіть, будь-ласка, коли буде опрацьована заявка № 0-243446488 від 17.05.16, м. Суми? Додавалися нові КВЕДИ. Статус заявки до цього часу в обробці.

**Comment by dmitrijzabrudskij** [comment]
добрый день
сегодня внесли изменения (проверьте почту - должно было прити письмо с деталями) - извините, что пришлось так долго ждать

**Comment by agerman-ua** [comment]
Заявка успешно закрыта 10.06.2016
