### ISSUE TITLE
Заявка ФЛП закрыта. Ответ на почту не пришел.

### ISSUE THREAD

**Issue by keisi7** [e-government-ua/iForum#461]
Здравствуйте.
Помогите с заявкой 0-299982943 на регистрацию ФЛП.
Статус - закрыта. Но на почте ответа нет.
Проверьте, пожалуйста.

**Comment by keisi7** [comment]
Ответ пришел. С отказом в регистрации.
Уточните, пожалуйста,комментарий:
"Причина: п.5 ч.4 с.9 місцезнаходження п.1.ч.1 ст. 15 державна мова"
Это касается полей заявки или документа с "ЗАЯВА про застосування спрощеної системи оподаткування"?

**Comment by dmitrijzabrudskij** [comment]
добрый вечер
заявки

**Comment by keisi7** [comment]
спасибо Вам за ответ

**Comment by keisi7** [comment]
Пришло еще одно письмо с текстом:

В разделе "Мой журнал" нет активных полей, заявка закрыта.
Подскажите, надо создавать новую заявку илли все таки возможно внести правку в данную?

**Comment by keisi7** [comment]
Пришло еще одно письмо с текстом:
Для успішної обробки Вашого звернення, державний службовець потребує уточнення деяких даних.
Примітка:
п.5 ч.4 ст.9 місцезнаходження п.1 ч. 1 ст.15 державна мова
Щоб уточнити дані, Вам потрібно перейти в розділ "Мій журнал" порталу iGov і внести інформацію у відповідні поля.

В разделе "Мой журнал" нет активных полей, заявка закрыта.
Подскажите, надо создавать новую заявку или все таки возможно внести правку в данную?

**Comment by dmitrijzabrudskij** [comment]
нужно создавать новую

**Comment by keisi7** [comment]
Здравствуйте!
По Вашей рекомендации создали новую заявку 0-311240599 , 
где внимательно прописали все поля на укр. яз.
Волнует момент того, что приват сначала выдавал Країна Громадянства: UA и город был прописан на рус.яз.
Но эти поля удалось отредактировать и написать в правильном формате.
Большая просьба, проконтролируйте заявку 0-311240599.
Очень надо начать работу, надеемся на Ваш ресурс.

**Comment by agerman-ua** [comment]
Добрый день. Спасибо за доверие, и за терпение. Должно быть уже нормально.

**Comment by keisi7** [comment]
Здравствуйте!
Ждем решения по заявке 0-311240599.
Подскажите, как скоро будет результат?

**Comment by keisi7** [comment]
Здравствуйте!
Пожалуйста, помогите с заявкой 0-311240599.
Жизненно необходима регистрация. Пошла вторая неделя(

**Comment by agerman-ua** [comment]
Добрый день, @keisi7 
Простите за задержку с ответом, Ваша заявка закрыта 21.06 отрицательно из-за неправильного формата КВЕДа. Должно было прийти письмо.
Если актуально - можете подать новую заявку.
Закрываю данную тему.
С уважением, Август.
