### ISSUE TITLE
Заявка 01.06.16 -№0-288372372 на тему "Державна реєстрація змін до відомостей про ФОП" г.Винница

### ISSUE THREAD

**Issue by 271011** [e-government-ua/iForum#462]
Ваше звернення №0-288372372 на тему "Державна реєстрація змін до відомостей про фізичну особу – підприємця" прийнято до розгляду. Якщо з'являться зауваження або уточнення Вам будуть надходити відповідні листи, просимо перевіряти пошту. - получено 01.06.2016. Сколько времени должна обрабатывться заявка? г.Винница

**Comment by agerman-ua** [comment]
Ваша заявка в обробці, всі зміни будуть супроводжуватися відповідними листами. Термін на жаль точний не можемо зараз назвати - скоріш за все до середини наступного тижня все вирішиться.
З повагою.

**Comment by agerman-ua** [comment]
Звернення №0-288372372 закрито 29.06.2016. Вітаємо та бажаємо успіхів.
