### ISSUE TITLE
Бех Александр

### ISSUE THREAD

**Issue by 76Alex** [e-government-ua/iForum#463]
Добрый день, подскажите как выбрать дату и время при оформлении заявки на оформление паспорта сыну в 16 лет? В какое время суток оформляется заявка, или это не важно?
Прошу ответить...............

**Comment by Koffeek** [comment]
@76Alex Добрый день. Время суток не влияет. В какое подраздление пытались подать заявку?

**Comment by AndreyPopovNew** [comment]
@76Alex  вы же уже создали одну тему

ну нет свободных дат на июнь.

@Koffeek @GrekD **КОГДА**  вы уже сделаете обещанное и вместо ПУСТОГО списка для отделения будет появляться надпись, что для данного отделения ДМС на текущий месяц свободных дат(тайм-слотов) нет !?!?!?!?!?!?!?!?!?!?

**Comment by Koffeek** [comment]
@AndreyPopovNew с ближайшей версией будет на боевом. Человек задает вопросы так как считает нужным.

**Comment by 76Alex** [comment]
Кировский ДМС, спасибо за ответ.  Только непонятно, я что не могу выбрать дату уже на июль, если уже все занято на июнь? Дождусь июля и опять все будет занято в июле? Так и 30 дней пройдет с дня рождения сына, а потом будут требовать штраф...................
