### ISSUE TITLE
№ 0-289154768 Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця) 

### ISSUE THREAD

**Issue by Polietaiev** [e-government-ua/iForum#464]
В особистому кабінеті (розділ "Мій журнал") в статусі послуги написано "Ви подали заявку на послугу Київська ДМС - Реєстрація місця проживання/перебування особи. Cтатус: Формування пакету документів для ДМС"

В той же час на електронну пошту прийшов лист "На жаль, Ви не з'явились в зазначений термін для отримання послуги. Ваше звернення було автоматично відхилено. Будь ласка, подайте нове звернення у разі необхідності отримання послуги."

Питання в тому куди я не з'явився ? коли мав з'явитися ? чи це технічна помилка, а документи в обробці ?

**Comment by annastolbova** [comment]
зараз місто Київ не співпрацює по цих послугах
