### ISSUE TITLE
Заявка №0-254215175 закрыта. Нет сообщения на почте.

### ISSUE THREAD

**Issue by NicolayM** [e-government-ua/iForum#465]
Здравствуйте! Заявка №0-254215175 была закрыта 08.06 в 13.25. Но никакого сообщения на почте нет. Папка спам пустая, на сайте минюста изменений нет. Подскажите, когда можно ожидать окончательный результат. Спасибо.

**Comment by agerman-ua** [comment]
Добрый день, Заявка на регистрацию закрыта успешно. Наверняка дошло письмо.
