### ISSUE TITLE
Звернення № 0-293817380

### ISSUE THREAD

**Issue by shvetsova2016** [e-government-ua/iForum#466]
Добрый день
Попыталась зарегистрироваться на сайте https://igov.org.ua/service/1495/general  еще 03.06.16
Державна реєстрація створення фізичної особи – підприємця

Судя по информации с сайтов, то регистрация осуществляется, обычно, в течение пары дней. Сегодня уже 9-е число, а мне не приходили никакие уведомления ни о регистрации ни об отказе в регистрации. 
Просто задерживается обработка или есть проблемы в оформлении?

**Comment by stepanchenko1** [comment]
поддерживаю
хотелось бы узнать все ли корректно работает

**Comment by asemenyuk** [comment]
У меня таже ситуация

**Comment by stepanchenko1** [comment]
очень огорчает то что из-за заполнения заявы на русском языке, может прийти отказ.

https://github.com/e-government-ua/iForum/issues/461

при том что приват прописывает город на русском.

**Comment by agerman-ua** [comment]
Добрый день,
В начале недели думаю будет решение.
Да, есть такая ситуация с адресами на русском. Но если аккуратно заполнять то всё будет нормально.
Регистраторы тоже привыкают к новому инструменту. Это обоюдный процесс.
Хороших выходных.

**Comment by stepanchenko1** [comment]
>Добрый день,
В начале недели думаю будет решение.
Да, есть такая ситуация с адресами на русском. Но если аккуратно заполнять то всё будет нормально.
Регистраторы тоже привыкают к новому инструменту. Это обоюдный процесс.
Хороших выходных.


как быть с заявками со статусом "закрыта" без обьяснения каких-либо причин?

**Comment by shvetsova2016** [comment]
Подскажите, пожалуйста, в чем может быть проблема. При поиске на сайте МинЮста по идентификационному коду я могу видеть свою регистрацию (там где поиск по номеру ИНН или паспорту физ.лица), а при поиске по результату наданих адміністративних послуг  я вижу только ФИО и "Документи: Відомості відсутні."
Как же мне получить Витяг?

**Comment by stepanchenko1** [comment]
@shvetsova2016 "Документи: Відомості відсутні." - подождите немного, позже придут. У меня была точно такая же ситуация

**Comment by shvetsova2016** [comment]
stepanchenko1, Действительно, через 1,5 дня сама собой появилась выписка в документах. Спасибо
