### ISSUE TITLE
Реєстрація ФОП

### ISSUE THREAD

**Issue by MartaBesaha** [e-government-ua/iForum#467]
Доброго дня,
чи підтримується послуга реєстрації ФОП для усіх регіонів України? Зокрема цікавить м. Львів та Львівська область.
Чи є сенс подавати заявку на реєстрацію? Бо вже отримали тричі відмову((

**Comment by agerman-ua** [comment]
Доброго дня.
Так, дана послуга доступна по всій території України.
Сенс є, жаль що з першого разу не вийшло.
Ми викладаємо днями оновлену версію послуги, будемо вдячні за зворотній зв'язок.

**Comment by MartaBesaha** [comment]
Гаразд, дякую за відповідь. Пробуватиму ще.
