### ISSUE TITLE
Звернення № 0-277690238 немає відповіді вже 18 днів!!!

### ISSUE THREAD

**Issue by asemenyuk** [e-government-ua/iForum#468]
Добрий день
Намагався зареєструватися на сайті https://igov.org.ua/service/1495/general  ще 30.05.2016р.
Державна реєстрація створення фізичної особи – підприємця. Звернення № 0-277690238 
Вже минуло **18!!!** днів а відповіді ніякої немає. На сайті подається інформація про те що реєстрація відбувається за декілька днів.
Можливо сервіс не працює? Чи є якісь затримки в обробці звернення?
Очікувати надалі? Чи йти фізично до реєстратора?

**Comment by asemenyuk** [comment]
Мені чекати на реєстрацію, чи йти фізично і реєструвати підприємця?

**Comment by asemenyuk** [comment]
Доброго дня, є якись шанс на реєстрацію..., вже третій тиждень немає відповіді. Надайте якусь відповідь чи очікувати, чи йти до реєстратора? Який стан заявки взагалі?

**Comment by agerman-ua** [comment]
Доброго дня, @asemenyuk 
Вибачте за величезну затримку.
08.07 Вам цікаво закрили заявку. :)
Ви повинні були побачити листа. Зверніть увагу саме на причину.
З повагою, Август.
