### ISSUE TITLE
Заявка на регистрацию ФЛП № 0-311240599

### ISSUE THREAD

**Issue by keisi7** [e-government-ua/iForum#469]
Здравствуйте!
По Вашей рекомендации создали новую заявку 0-311240599 ,
где внимательно прописали все поля на укр. яз.
Волнует момент того, что приват сначала выдавал Країна Громадянства: UA и город был прописан на рус.яз.
Но эти поля удалось отредактировать и написать в правильном формате.
Большая просьба, проконтролируйте заявку 0-311240599.
Очень надо начать работу, надеемся на Ваш ресурс

**Comment by agerman-ua** [comment]
Добрый день,
Заявка №0-311240599 закрыта еще 21.06.2016.
