### ISSUE TITLE
"Заявка №0-304256582 змiнила свiй статус на закрита". Письмо на почту не пришло.

### ISSUE THREAD

**Issue by stepanchenko1** [e-government-ua/iForum#470]
"Заявка №0-304256582 змiнила свiй статус на закрита". Письмо на почту не пришло.
Папка спам также пуста. Подскажите, каковы дальнейшие действия? 

Если она закрыта по причине завершения или же из-за неправильного заполнения документов - сообщите.

**Comment by agerman-ua** [comment]
Добрый день, @stepanchenko1 . Услуга регистрации ФОП. Заявка действительно закрыта. "Причина:Заява заповнюється на державній мові". Письмо обязательно должно было прийти. А вообще письмо хоть одно было?

**Comment by stepanchenko1** [comment]
Здравствуйте. Письмо не пришло. Спам проверял - его там тоже нет.

Большая просьба на будущее: Укажите что заполнение должно быть на украинском языке в обязательном порядке.

Что касается меня, я уже подал лично в администрацию. 
За сервис спасибо. Но багов еще немало, удачи в развитии портала.

**Comment by agerman-ua** [comment]
@stepanchenko1 
Спасибо за пожелания.
