### ISSUE TITLE
Заявка № 0-309162604, (Регистрация юридического лица) как понять на каком этапе?

### ISSUE THREAD

**Issue by smartukraine** [e-government-ua/iForum#471]
Добрый день, подскажите как понять заявка Регистрация юридического лица нового № 0-309162604 на каком этапе, дошла она до получателя или нет, что может еще быть, так как заявка должна быть рассмотрена в течении 24 часов. Что делать?

**Comment by agerman-ua** [comment]
Добрый день,
Заявка на этапе обработки регистратором действительно не задерживается обычно более суток.
Проблема была в том, что сначала её принимают администраторы ЦНАПа и только после проверки она попадает к регистратору. Вот эта первая часть и занимала столько времени.
Сейчас уже получше.
По заявке № 0-309162604. Закрыта ещё 05.07.2016. Успешно. Поздравляем.
