### ISSUE TITLE
Заявка на субсидию

### ISSUE THREAD

**Issue by ole77** [e-government-ua/iForum#472]
Заполняла (2 раза) заявку на субсидию по оплате комунальных.
Номера не выдало.  Во вкладке  "Мой журнал"  висят 2 сообщения
"09.03.2016 в обробці" и "10.03.2016 в обробці".
При нажатии на "Детальніше" выдает код 0404.
Как мне проверить статус заявок и что с ними.

**Comment by zolotovatatyana** [comment]
Здравствуйте. А в Моем журнале указаны номера заявки? скопируйте их сюда, попробую поискать

**Comment by ole77** [comment]
Спасибо за ответ. Номеров  заявок нет, а просто  "10.03.2016 в обробці"

**Comment by zolotovatatyana** [comment]
@ole77 Странно. А скриншот можно?

**Comment by ole77** [comment]
![2016-06-10_13-55-17](https://cloud.githubusercontent.com/assets/19854087/15962362/45fe79a4-2f13-11e6-91f8-070579948095.png)

**Comment by zolotovatatyana** [comment]
Елена, судя по дате подачи, могу предположить, что Ваша заявка закрыта Отказом, с комментарием чиновника 
> "Провулок Поліський не відноситься за територіальною належністю до Деснянського району міста Києва."

Вам должны были прийти письма на емейл, который Вы указывали при заполнении заявки, с сообщением решения госоргана. Проверьте пожалуйста папку Спам: к сожалению, иногда письма попадают туда.

Не отображается у вас из-за странного сбоя в базе, данные о которых я подала разработчикам для исследования. Спасибо за сообщение.

**Comment by ole77** [comment]
Спасибо за ответ. К сожалению, писем от чиновников не было. 

10 июня 2016, 14:50:14, от "zolotovatatyana" < notifications@github.com >: 

Елена, судя по дате подачи, могу предположить, что Ваша заявка закрыта Отказом, с комментарием чиновника "Провулок Поліський не відноситься за територіальною належністю до Деснянського району міста Києва." Вам должны были прийти письма на емейл, который Вы указывали при заполнении заявки, с сообщением решения госоргана. Проверьте пожалуйста папку Спам: к сожалению, иногда письма попадают туда. Не отображается у вас из-за странного сбоя в базе, данные о которых я подала разработчикам для исследования. Спасибо за сообщение. —
