### ISSUE TITLE
 Вже **2,5 ТИЖНЯ** в обробці! 

### ISSUE THREAD

**Issue by Hanna033** [e-government-ua/iForum#473]
Звернення № 0-259151421. Скажіть, будь ласка, в чому трабли. Перший раз була відмова із-за мови країни громадянства через тиждень. Тепер, в цілому, минув місяць( Може є сенс закрити заявку та відкриватися самостійно.  Заздалегіть вдячна за відповідь!

**Comment by dmitrijzabrudskij** [comment]
в понедельник обработают. уже писал это [здесь](https://github.com/e-government-ua/iForum/issues/441). поэтому эту ветку закрываю
