### ISSUE TITLE
Заявка №0-293521270 змiнила свiй статус на закрита, але ніякого листа не надійшло

### ISSUE THREAD

**Issue by gpilgrim** [e-government-ua/iForum#475]

**Comment by gpilgrim** [comment]
Як визначити результат розгляду заявки?

**Comment by agerman-ua** [comment]
@gpilgrim 
Добрий день, 
У Вас відмова. 
З поясненням від реєстратора "Причина: документи не відповідають вимогам ст. 27 п.2 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб-підприємців та громадських формувань\""
Але листа Ви повинні були отримати обов'язково.
З повагою,
