### ISSUE TITLE
Онлайн заявка на загранпаспорт

### ISSUE THREAD

**Issue by Alinka1990** [e-government-ua/iForum#477]
Не могу подать онлайн заявку на загранпаспорт. Пишет что нет свободного времени, как быть?

**Comment by AndreyPopovNew** [comment]
или выбрать другое отделение ДМС , или идти в живую очередь, или ждать когда появится время.

**Comment by Koffeek** [comment]
@Alinka1990 Добавили слотов на ближайший свободный месяц
