### ISSUE TITLE
Видача/заміна паспорта  за кордон

### ISSUE THREAD

**Issue by xc6Smail** [e-government-ua/iForum#478]
Нет возможности оформить заявку.  Т.к. в разделе 
*В який день Ви бажаєте звернутися до міграційної служби?  не ставится дата и время.

**Comment by AndreyPopovNew** [comment]
нет свободных тайм-слотов.

**Comment by Koffeek** [comment]
@xc6Smail Добавили слотов на ближайший свободный месяц
