### ISSUE TITLE
Немає відповіді на запит реєстрації ФОП 0-292857822

### ISSUE THREAD

**Issue by k0rabas** [e-government-ua/iForum#479]
Доброго дня,
Дев'ять днів тому оформив запит на реєстрацію ФОП і не отримав зворотього зв'язку.
Чи є проблеми/затримки в роботі сервісу?
Як можна вирішити проблему і прискорити завершення реєстрації?
Дякую.

**Comment by agerman-ua** [comment]
@k0rabas 
Доброго дня
Ваша заявка зареєстрована, та на даний момент знаходиться в обробці у держреєстратора.

**Comment by agerman-ua** [comment]
Звернення закрито 07.07.2016
