### ISSUE TITLE
Регистрация ФОП: где ошибка?

### ISSUE THREAD

**Issue by sector612** [e-government-ua/iForum#480]
Подавал заявку на регистрацию ФОП с приложением заявления на единыйй налог.
Ответ: Ваше звернення №0-305658741 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
Коментар держслужбовця (Причина:Заява заповнюється на державній мові, не всі поля заповнені)
Подскажите, какие поля не заполнены были и где в заявке не гос. язык?
Сама заявка на регистрацию ФОП заполнена на украинском, не понимаю в чем причина.

По заявлению на единый налог:
- Поле "Дата взяття на облік в органі державної податкової служби" надо заполнять и где взять эти данные?
- В каком формате загружать эту заявку - многостраничный .tiff или .doc или в каком виде?
- Какую дату ставить в пункте 5.1 если неизвестно когда госслужащий заявку возьмет в работу?

**Comment by sector612** [comment]
Начитавшись интернетов создал новую заявку № 0-320911705. В этот раз зашел через банк-айди, ФИО на украинском (капсом почему-то), все данные тоже на украинском. Заява на единый налог приложена в многостраничном .tiff тоже на украинском.
Неплохо было бы конечно какой-то гайд краткий по регистрации ФОП онлайн, а то в инете инфа разрозненная и в основном в отношении личного посещения госрегистратора и налоговой.

**Comment by agerman-ua** [comment]
@sector612 
Добрый вечер,
Вы правильно всё сделали.
Хотя служащий мог не закрывать Вашу первую заявку, а просто уточнить данные, но тут просто формально подошли, мы стараемся уменьшить такие причины закрытия.
Ждём вторника, уточним статус по Вашему новому обращению..
Спасибо за терпение.
С уважением, Август.

**Comment by sector612** [comment]
@agerman-ua Позитивный ответ пришел на электропочту еще на прошлой неделе 21 июня, но второго письма не было и в ЕДР я себя не нахожу. Можно что-то с этим сделать? Пнуть кого-то например или как? :(

**Comment by sector612** [comment]
@agerman-ua Ситуация не изменилась. Второго письма нет, в реестре меня нет. Прошло уже две недели с момента получения первого письма о положительном решении. Что делать? Куда звонить? Кто этот человек, который этим занимается и где его искать?

**Comment by sector612** [comment]
Позвонил госрегистратору в ЦНАП по месту прописки. Приветливая девушка сказала, что электронных заявок не было уже давно, спросила мой ИНН, говорит что от меня заявок не поступало.

**Comment by sector612** [comment]
Позвонил госрегистратору в ЦНАП по месту прописки. Приветливая девушка сказала, что электронных заявок не было уже давно, спросила мой ИНН, говорит что от меня заявок не поступало.

**Comment by agerman-ua** [comment]
@sector612 
Добрый день,
По файлу с заявлением пока непонятная ситуация. 
Сотрудники ЦНАПа не смогли его открыть (по их словам все 3 листа были чёрными и нигде приложенный файл не открывался). 
Сейчас совместно перепроверяем. Это не займёт много времени. 
Благодарю за терпение и понимание.
С уважением, Август

**Comment by sector612** [comment]
@agerman-ua Если речь идет о заявлении на единый налог, то там уже все равно дата желаемой постановки на учет просрочена. Я так понимаю, что в налоговой его уже не примут.

**Comment by agerman-ua** [comment]
@sector612 
Скорее всего именно так.

**Comment by sector612** [comment]
То може я новую заявку подам, без даты в заяве на единый налог? Или так нельзя?

**Comment by agerman-ua** [comment]
@sector612 
У меня тоже файл открылся, но вариантов "на местах", к сожалению, много.
Думаю вариант с DOC (именно DOC а не DOCX) и картинками один из хороших вариантов. Но наверное более стандартный - многостраничный pdf из нескольких jpg (онлайн конвертеров куча), 
Да. Вам лучше подать новое обращение (поскольку по факту не было выполнено регистрационных действий). Сейчас всё происходит намного стабильнее чем пару недель назад. Не указывая в заявлении даты постановки на учет в налоговую. Или (если так комфортнее) можете сами лично его подать в бумажном виде сразу после регистрации. 
С уважением, Август.

**Comment by sector612** [comment]
Хотелось бы довести этот электронный квест до конца, но времени нет. Сходил 12 числа ногами к регистратору, там совершенно бесплатно приняли все документы и 14 я уже появился в реестре. Всем спасибо.
