### ISSUE TITLE
Заявка №0-293521270 змiнила свiй статус на закрита, але ніякого листа не надійшло

### ISSUE THREAD

**Issue by gpilgrim** [e-government-ua/iForum#483]
м. Київ
03.06.2016 10:20 була зроблена заявка на реєстрацію ФОП №0-293521270.
03.06.2016 10:20 був отриман лист електронною поштою про те що заявка прийнята.
09.06.2016  заявка змінила свій статус на "Закрита", але листа з підтвердженням або аргументованою відмовою не надійшло. В БД ЄДР ФОП відповідного запису не з'явилось.

Як дізнатися результат обробки заявки?

**Comment by agerman-ua** [comment]
@gpilgrim 
Доброго дня,
Про результати обробки Ви повинні дізнаватися з листів. Вони формуются автоматично в момент появи додаткової інформації в процесі надання послуги.
У Вас відмова. Підстава "Причина: документи не відповідають вимогам ст. 27 п.2 Закону України \"Про державну реєстрацію юридичних осіб, фізичних осіб-підприємців та громадських формувань\"".
До листа повинно бути додано файл з рішенням.
