### ISSUE TITLE
заявка на регистрацию ФОП обрабатывается уже 10 дней без результата

### ISSUE THREAD

**Issue by Harkavenko** [e-government-ua/iForum#484]
Заявка № 0-292939114 от 03.06.2016 до сих пор находится в статусе "в обработке". Мне для работы необходима регистрация, и у меня нет времени ждать еще 10 дней. Я могу параллельно подать заявку в гос администрацию по месту жительства или теперь должен дожидаться ответа с портала о результате рассмотрения моей заявки?

**Comment by salkat** [comment]
Аналогично. Звернення № 0-291351841 - 11 дней без изменений. При заявленных "в среднем 4 дня и 30 минут"

**Comment by agerman-ua** [comment]
@Harkavenko 
Добрый день, У нас в другой теме #499 Ваш вопрос уже плотно рассматривается - поэтому здесь тему закрою.

@salkat 
Добрый день, простите в теме #486 Ваш вопрос уже принят в работу.

С уважением, Август.
