### ISSUE TITLE
Не обоснованные отказы в регистрации ФОП

### ISSUE THREAD

**Issue by Maestra86** [e-government-ua/iForum#485]
Добрый день!

Вчера писала на Фейсбуке https://www.facebook.com/dubilet/posts/10154269486318552?comment_id=10154277649393552&reply_comment_id=10154283072588552&comment_tracking=%7B%22tn%22%3A%22R9%22%7D

решила продублировать ещё здесь:

№0-286992517 от 01.06.2016 10:42, закрыта с комментарием, что не указан тип населенного пункта, хотя он был указан. 
Возможно, при сохранении формы Система обнуляет часть полей?

№0-290175958 от 02.06.2016 10:33, закрыта 07.06.2016 17:40 без комментариев

№0-298427904 от 06.06.2016 00:20, закрыта 10.06.2016 08:35 без комментариев

№0-306534128 от 08.06.2016 12:29, закрыта 10.06.2016 09:28 с комментарием "Вашу заяву опрацьовано 06.06.2016 р"

№0-314122284 от 10.06.2016 10:46 - пока в работе, 
я попросила в комментариях "Доброго дня! внесено зміни згідно коментарів держслужбовця, прохання не відхиляти заявку, а подивитися скан у вкладенні. дуже дякую!"

Что надо сделать или заполнить, чтобы заявка на регистрацию была оформлена?
Складывается впечатление, что сотрудники даже не открывают эти заявки, а сразу всем отказывают, судя по этому форуму и стандартным отпискам.

Если регистрацией ФОП ещё нельзя пользоваться - напишите, пожалуйста, чтобы люди не теряли время. Я, например, уже 2 недели пытаюсь зарегистрировать ФОП.
Неужели надо бросать всё это, брать на работе день отгула и идти подавать документы вживую?

Спасибо большое!

**Comment by ionafan2** [comment]
У меня была такая же ситуация. Два раза пробовал - два раза завернули с кментариями типа: "Не верно заполенно заявлние". И пойди пойми, что именно не так заполненно.

**Comment by agerman-ua** [comment]
Регистраторам предоставлен инструмент для общения с заявителями. Это в дополнение к письмам из системы. Мы стараемся повлиять на данную ситуацию.

**Comment by Maestra86** [comment]
Добрый вечер!
Подскажите, пожалуйста, если ли какие-то сподвижки, или гиблое это дело и идти регистрировать по-старинке?

**Comment by agerman-ua** [comment]
@Maestra86 
Добрый день,
Простите за неоперативный ответ.
"Сподвижки" есть. Пока заявка в работе.
С уважением, Август.

**Comment by Maestra86** [comment]
Спасибо, буду ждать :)

**Comment by Maestra86** [comment]
Добрый день!
Ну что, очередной отказ, с формулировкой, что данные заполнены на русском языке, хотя такого быть не может, все 5 раз я заполняла только на украинском!!!

Подала очередную, шестую заявку, № 0-348530985.
Уже дело принципа. Более 3-х недель я пытаюсь зарегистрировать ФОП.

Это не сервис, а издевательство :(

**Comment by agerman-ua** [comment]
Добрый день, @Maestra86 
Не могу определить как именно, да это наверное уже и не важно, но Вы зарегистрировались еще 06.06.
В любом случае поздравляю.
Приношу извинения за причинённые неудобства и задержку с ответом.
И, конечно, спасибо большое за то что изначально поддержали наш портал своим обращением.
Благодаря Вам и таким как Вы мы смогли стабильно добиться реальной обработки заявки в среднем стабильно "до недели" а также снизили до минимума формальные ответы госслужащих.
Сейчас работаем чтобы формальных ответов не было а заявки обрабатывались до двух рабочих дней.
С уважением, Август.
