### ISSUE TITLE
Звернення № 0-291351841 в обробці вже 11 днів замість заявлених 4

### ISSUE THREAD

**Issue by salkat** [e-government-ua/iForum#486]

**Comment by agerman-ua** [comment]
На порталі вказано час обробки вже закритих заявок. Проміжок між початком обробки та її закриттям.

**Comment by salkat** [comment]
Моя заявка (Звернення № 0-291351841), о которой я написал в (#486), висит с 02.06.16, то есть три недели. До сих пор в обработке. Хорошо что неделю назад я потратил кучу своего времени, приехал сам в Николаев, отстоял 5 раз в очереди за 4 полных дня (2-6 часов ожидания за раз) и таки зарегистрировал юр.лицо. 
В принципе, если всё сделать правильно с первого раза, то можно за день. 
Заявку можете снимать.
