### ISSUE TITLE
звернення №0-296266096. закрито з відмовою. що тепер робити - не ясно [RESOLVED]

### ISSUE THREAD

**Issue by zalexua** [e-government-ua/iForum#488]
На 10-й день після подачі запиту, отримав на email:

> Ваше звернення №0-296266096 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
> 
> Коментар держслужбовця (Невідповідність відомостей (в адресі) у заяві для проведення державної реєстрації ФОП і заяві про застосування спрощеної системи оподаткування. Просимо усунути розбіжності та подати заяву повторно.)

При реєстрації одразу подавав також і заяву на платника ЄП.
І от не ясно - чи реєстрація як ФОП також не здійснена чи все ж здійснена?
По ідеї заявку на платника ЄП можна подати тільки коли вже зареєстрований, тому логічно припускаю що ФОП мав би бути зареєстрованим.

Тим більше термін очікування 9 днів міг би пояснити саме очікування реєстрації саме ЄП.
Інакше, якщо тільки реєстрація ФОП займає 9 днів .... то це дуже прикро, і ідею робити реєстрацію електронно зводить на нівець.

В реєстрі інформацію не знайдено (не впевнений чи це правильне місце для перевірки)
https://usr.minjust.gov.ua/ua/freesearch

**Comment by zalexua** [comment]
З другої спроби за 2 дні зареєстрували.
Дякую волонтерам-колегам які можливо допомогли зробити це оперативніше.

Сподіюваюсь так буде і надалі.

Побажаю щоб тут було більше фідбеку в чому проблеми, люди до цього ставляться зрозумінням.
А от майже повна тиша в більшості тікетів - це дуже погано. Сподіваюсь причиною є лише брак людей (волонтерів).

Дякую, можна закривати.

**Comment by agerman-ua** [comment]
@zalexua 
Добрий день,
І Вам, на взаєм, дякуємо за оптимізм та зворотній зв'язок.
З повагою, Август.
