### ISSUE TITLE
Звернення № 0-198152035 (выплата на ребенка) не обробляється

### ISSUE THREAD

**Issue by jamhak** [e-government-ua/iForum#489]
НА сайті зазначено - розгляд документів до 20 днів. Наразі пройшло уже більше ніж півтора місяці - ніяких зрушень

**Comment by zolotovatatyana** [comment]
@jamhak Здравствуйте!
К сожалению, иногда чиновники саботируют обработку заявок, сопротивляясь переходу на электронный документооборот. Мы, со своей стороны, проводим работу  для того чтоб стимулировать их к скорейшей обработке поступивших обращений.

**Comment by jamhak** [comment]
@zolotovatatyana я все понимаю, но что делать мне? Вы можете как-то повлиять именно на эту заявку? ОЧень нужна Ваша помощь, поскольку скоро ВООБЩЕ заканчивается срок подачи документов = невозможность получить выплату на ребенка

**Comment by annastolbova** [comment]
заявка закрита 05.07.2016
