### ISSUE TITLE
Лицензия проекта (ліцензія проекту, project license)

### ISSUE THREAD

**Issue by uazure** [e-government-ua/iForum#49]
Под какой лицензией публикуется код? С какими условиями соглашаются котрибьюторы?
Наиболее свободной из всех свободных лицензий на мой взгляд сейчас является лицензия GPLv3. Под такой линцензией мне было бы наиболее комфортно делать вклад в проект, поскольку это гарантирует и мне и любому другому человеку свободу доступа к коду этого продукта, свободу улучшать и делиться этими улучшениями, пользоваться улучшениями других.
Думаю было бы разумно использовать лицензию GPLv3 для проекта в целом.

**Comment by kilotaras** [comment]
>Наиболее свободной из всех свободных лицензий...GPLv3

Не бачу, як вірусна ліцензія є "найвільнішою."  Пропоную Apache/MIT - робіть, що хочете, як хочете.

**Comment by yurikoles** [comment]
@kilotaras Можешь пометить, что твои коммиты можно рассматривать под MIT, это не помешает нам их перелицензировать под AGPLv3.

**Comment by yurikoles** [comment]
@uazure Для сайта лучше AGPL https://www.gnu.org/licenses/why-affero-gpl.html
>Стандартная общественная лицензия GNU Афферо — модифицированная версия обычной GNU GPL версии 3. В ней добавлено одно требование: если вы выполняете измененную программу на сервере и даете другим пользователям общаться на нем с этой программой, ваш сервер должен также позволять им получить исходный текст, соответствующий той модифицированной версии программы, которая выполняется на сервере.

>Назначение GNU GPL Афферо — предотвратить возникновение проблемы, которая встает перед разработчиками тех свободных программ, которые часто применяются на серверах.
