### ISSUE TITLE
скільки ще буде звернення в обробці і як його або відкликати або отримати результат

### ISSUE THREAD

**Issue by optuma** [e-government-ua/iForum#491]
заявка 0-302357659

**Comment by agerman-ua** [comment]
@optuma 
Добрий день,
Вибачте за затримку.
Ваша заявка в роботі, уточнити стан та статус розгляду у урядовця раніше вівторка не вийде.
З повагою, Август.

**Comment by optuma** [comment]
Гаразд. чекаю вівторка

**Comment by optuma** [comment]
чи можна дізнатись про стан справи?

**Comment by agerman-ua** [comment]
Доброго дня, @optuma 
Вибачте за затримку з відповіддю.
06.07 звернення закрито за Вашим бажанням.
Жаль не встигли підтягнутись до цього моменту.
Наразі зараз реєстрація ФОП до тижня опрацьовуються.
З повагою, Август.
