### ISSUE TITLE
Звернення № 0-302259400 - сім днів немає оновлень

### ISSUE THREAD

**Issue by IaroslavShchevych** [e-government-ua/iForum#493]
Сім днів як немає оновлень по моєму зверненню. Писав 5 днів тому через портал запит в журналі звернення, але ніхто не відповів. 
Чи є можливість дізнатися, чи йде обробка звернення? Чи взагалі підтримується ця послуга в Рівненській області? Можливо швидше скасувати звернення і написати паперове подання (реєстрація ФОП)?
Дякую

**Comment by agerman-ua** [comment]
@IaroslavShchevych 
Доброго дня,
Вибачте за затримку з відповіддю Ваша заявка зараз в роботі.
Скоріш за все вже не можна скасувате звернення, але точніше можно сказати не раніше вівторка.
Так ця послуга надається в Рівненьскій області також.
З повагою, Август.

**Comment by agerman-ua** [comment]
Звернення опрацьовано 07.07.2016
