### ISSUE TITLE
Нет документов

### ISSUE THREAD

**Issue by PolinaKlitsakova** [e-government-ua/iForum#494]
Здравствуйте! Вчера получила положительный результат по своей заявке №0-306027180 (регистрация ФЛП), но в разделе Документы копии документов не подгружены.

**Comment by optuma** [comment]
сколько времени прошло от подачи до решения?

**Comment by PolinaKlitsakova** [comment]
подала 08.06, ответ пришел вчера 13.06

**Comment by agerman-ua** [comment]
@PolinaKlitsakova 
Добрый день,
Простите не понятен Ваш вопрос.
Вас зарегистрировали.
Проверьте на https://usr.minjust.gov.ua/ua/freesearch/
введите свой ИНН - должны увидеть статус.
Вам больше ничего не нужно.
С уважением, Август.

**Comment by PolinaKlitsakova** [comment]
Спасибо. Просто мне госрегистратор когда звонила, сказала что будет подгружена какая-то копия документа о регистрации ФЛП...

**Comment by agerman-ua** [comment]
@PolinaKlitsakova 
Добрый день,
Спасибо и Вам, что воспользовались нашим сервисом.
Возможно что она не подгрузила файл или ошиблась при выборе статуса что он есть. Письмо формируется на основании того что выбирает обрабатывающий заявку чиновник.

Тему закрываю, если по этому обращению будут вопросы - можете её открыть. Или создать новую.

С уважением, Август.

**Comment by agerman-ua** [comment]
Вопрос решён.
