### ISSUE TITLE
Звернення № 0-315667128 висить 5-й день

### ISSUE THREAD

**Issue by kavunchik05** [e-government-ua/iForum#495]
Вітаю! Скільки необхідно чекати на опрацювання завки на зміну кведів? Звернення "в обробці" вже 5-й день. Статус: Перевірка наданих даних (1)

**Comment by agerman-ua** [comment]
@kavunchik05 
Якщо у Вас відсутні жорсткі вимоги до часу, прошу зачекати.
Ваше звернення точно ніхто не зможе загубити або залишити без розгляду.
Вам обов'язково надійде лист при зміні статусу звернення.
До речі, Ви вже можете знайти всі надіслані Вам листи у розділі "Мій журнал" - це стосується листів відправлених починаючи з учора. 
Зараз проводиться цілий комплекс мір, навчання держслужбовців, їх вмотивування, пошук інших каналів обробки. Це питання організаційного характеру.
З повагою, Август.

**Comment by agerman-ua** [comment]
Добрий день, @kavunchik05 
Оскільки Вам надали позитивну відповідь ще 01.07 - закриваю цю тему.
Якщо будуть питання - пишіть.
З повагою, Август.
