### ISSUE TITLE
Звернення № 0-303715073: в обработке 7 дней

### ISSUE THREAD

**Issue by wor4yn** [e-government-ua/iForum#496]
Неделю висит статус "В обробці". Подскажите, как скоро можно ожидать оформления СПД?

**Comment by agerman-ua** [comment]
@wor4yn 
Добрый день, гарантированного срока, к сожалению, в данный момент назвать нет возможности. Все заявки обязательно будут обработаны госслужащими.
Благодарю за понимание.
С уважением, Август.

**Comment by agerman-ua** [comment]
Доброго дня, @wor4yn 
Вибачте за затримку з відповіддю.
21.06. Вам було відмовлено. Щодо цього обов'язково повинен був надійти лист.
Можете подати нову з урахуванням причин відмови на попередню.
Просто зазначте існуючий КВЕД. Це єдина причина відмови.
З повагою, Август.
