### ISSUE TITLE
Заявка 0-324439129

### ISSUE THREAD

**Issue by Krasnyanska** [e-government-ua/iForum#497]
Добрый день! Сколько будет обрабатываться заявка на регистрацию ФОП № 0-324439129, дата подачи 14.06.16?

**Comment by agerman-ua** [comment]
@Krasnyanska 
Добрый день, точный срок, к сожалению назвать нет возможности.
Мы стараемся найти способ уменьшения сроков обработки всех заявок.
С уважением, Август.

**Comment by agerman-ua** [comment]
Добрый день, @Krasnyanska 
Простите за задержку с ответом.
29.06 Вам ответили. Были замечания озвученные Вам по телефону, но в любом случае должно было прийти письмо.
Кстати на текущий момент заявка на регистрацию ФОП рассматривается уже не более 5-7 дней.
Если останутся вопросы - спрашивайте. Эту тему закрываю.
С уважением, Август.
