### ISSUE TITLE
Оформление субсидии ЖКХ

### ISSUE THREAD

**Issue by ArtemRuban** [e-government-ua/iForum#498]
В выпадающем списке,  в начале страницы  на шаге 3 "Оберіть свій район або місто:" нет города Одесса ...  Т.е. я не могу оформить субсидию онлайн?

**Comment by ArtemRuban** [comment]
Не выбрав в данном поле ничего ( оставил пустым) заявка принялась...интуитивно понятно...спасибо.

**Comment by ArtemRuban** [comment]
Звернення на тему "Отримання субсидії на оплату житлово-комунальних послуг"
iGov
портал державних послуг
Шановний(-а) АРТЕМ ІГОРОВИЧ.

Ваше звернення №0-329856013 щодо отримання субсидії на оплату житлово-комунальних послуг зареєстроване. Ви отримаєте відповідь протягом 30 робочих днів.

Контакти підрозділу соцзахисту, яке буде займатися обробкою Вашого звернення:

УПСЗН Арцизький район
вул. Будівельників, 15 Б м. Арциз, Одеська область, 68404
Режим роботи з 8.00 до 17.00
Телефон для довідок: (4845) 3-12-50

З повагою,
УПСЗН Арцизький район
Команда Порталу державних послуг iGov

**Comment by ArtemRuban** [comment]
Почему Арциз если я оставил поле пустым? Т.е. по заявке будет отказ?

**Comment by zolotovatatyana** [comment]
@ArtemRuban Здравствуйте!
Действительно, в г.Одесса услуга оформления субсидии на портале iGov  недоступна (в связи с отказом чиновников идти навстречу гражданам в области электронного документооборота).

Относительно второго Вашего вопроса: технические специалисты вплотную занимаются решением описанной Вами проблемы: на сегодняшний день реализован механизм, согласно которому если поле остается пустым, то заявка не уходит, и заявителя просят заполнить пустое поле. Однако, если Вы выбрали Арцизский район, потом помотали список других районов, и наконец удалили запись чтоб оставить поле пустым - в системе "запомнился" Арцизский район. Устранение этого дефекта еще в работе.  

По Вашей заявке Вы получите отказ, т.к. обращения должны подаваться по месту регистрации граждан.
![image](https://cloud.githubusercontent.com/assets/17428210/16115274/b1da462a-33ce-11e6-9826-fcae3e50f78a.png)
