### ISSUE TITLE
Открытие ФОП 0-292939114 03.06.2016

### ISSUE THREAD

**Issue by Harkavenko** [e-government-ua/iForum#499]
Моя заявка две недели в обработке. Результатов нет. Время открытия ФОП "вживую" с подачей бумажного заявления и походом в налоговую- неделя. Из-за вашего сервиса я потерял время и деньги. Перед тем как громко пиарить услугу надо позаботиться о ее работоспособности. Ваш "средний тайминг" опубликованный в статистике не соответствует действительности. Причем, все это время прошло без всяких гарантий на то, что регистрация пройдет успешно. Электронные сервисы должны работать 1) быстро 2)эффективно 3)прозрачно для пользователя. У вас три в одном- медленно, непонятно, безрезультатно. Сейчас вы заняты тем что дискредитируете прогрессивный и нужный государству сервис. Я никому не порекомендую пользоваться порталом АйГов, и, думаю, многие кто столкнулся с подобной проблемой- тоже.

**Comment by Harkavenko** [comment]
ЗЫ Ко всем предыдущим пунктам: отвратительная обратная связь: я уже писал о проблеме 4 дня назад и до сих пор не получил ответа от тех. поддержки.

**Comment by agerman-ua** [comment]
Добрый день,
Сожалею о произошедшем.
Обработку Вашей и иных заявок выполняют не портал и волонтёры а госслужащие,
Мы разными, доступными нам, способами стараемся поднять качество их работы и мотивацию.
Понимаю что это не изменит Ваше впечатление в конкретном случае. 
Только добавлю, для понимания работы статистики, что считается количество предоставленных услуг и среднее время именно предоставленных "от начала до конца". Это то что мы однозначно можем посчитать и показать.

**Comment by Maestra86** [comment]
конечно Вы можете посчитать время...
А знаете, откуда оно такое получается? за счет заявок, которые закрываются мгновенно без единого комментария

**Comment by dmitrijzabrudskij** [comment]
"начало" - это взятие заявки в работу
Ваши случаи - это как раз нахождение заявки в очереди

**Comment by Anakalivto** [comment]
Возможно тогда следует добавить инф. о том сколько находиться в очереди? 
И инф. о том сколько обработано за день. 
Сделать какой-то график... Что бы человек понимал реальную скорость обработки заявок.

Вот например я сегодня заходил с утра (около 10) по ФОП было 825 выполненных заявок, сейчас (около 18) показывает 831 выполнена... Это 6 заявок по всей Украине за рабочий день. Как-то мало... 

Мне до конца месяца очень нужно стать ФОПом. 
Специально не выбирал пункт (перейти на ЕСВ) и не прикладывал заявку - дабы упростить работу гос.служащему и обезопасить себя от возможной ошибки в заявлении и последующему отказу без объяснений, как тут уже писали много раз. Но моя заявка (0-323016683) висит в работе, комментариев нет, гарантии что она будет обработана так же нет...
И что самое интересное - я уже согласен забить на работу и пойти постоять в очереди но не могу так как наверно будет дубликат и откажут по обоим заявкам...
Может еще необходимо добавить функционал отзыва заявки?

**Comment by Harkavenko** [comment]
Спасибо всем за дискуссию. Проблема в том, что рассматривать заявки должен алгоритм а не чиновник, иначе теряется смысл проекта. Алгоритм не надо мотивировать к работе. Вторая проблема в пиар компании которую организовал некий дубилет, где сервис рекламируют как рабочий проект, в то время как  он, очевидно, на ранней стадии тестирования. По опыту общения с тех поддержкой приват банка, сотрудником которого является дубилет, у меня сложилось впечатление что треп и ложь являются нормальным корпоративным поведением в привате. Меня сейчас интересует в первую очередь могу ли я подавать заявку традиционным способом, пока моя заявка на айгов находится в рассмотрении, и если нет, то как эту заявку отозвать.

**Comment by olenmoisen** [comment]
Аналогичная ситуация с подобной заявкой.
Я понимаю, что альфа, что волонтеры, но укажите большими красными буквами, что сервис на данный момент ничего не гарантирует. Где можно ознакомиться с регламентом? Где конкретно находится заявка? У кого? Как отозвать?

**Comment by agerman-ua** [comment]
@Harkavenko 
Исходя из ранее написанных Вами постов можно сделать однозначный вывод о Вашей несомненной грамотности и ясном уме. Как Вы правильно заметили единственно правильный вектор развития всех госуслуг это предоставление их в полностью электронном виде. Где нет задержек связанных с отпусками, болезнями и иными человеческими влияниями на процесс. Т.е. основанная на понятной и прозрачной последовательности событий. 
Однако Вы пишете с позиции или "человека из будущего" или иностранца. В нашей стране есть объективная реальность, да она мягко говоря не идеальна, но она объективна и никакая система не может существовать в данной среде игнорируя её возможности и требования.
Чтобы изменить это нужны последовательные шаги в этом направлении. Вы можете привести пример системы предоставления госуслуг в нашей стране которая полностью автоматизирована и работает без сбоев. Мы все сейчас в режиме теста. Теста на гражданскую позицию, на терпимость, на вежливость и корректность.
Также, пользуясь случаем, прошу не счесть за труд и имена собственные начинать с заглавных букв. Заранее благодарю за понимание.

@olenmoisen 
По поводу отзыва заявок.
Просто укажите номер заявки и своё желание отозвать заявку. Если стадия рассмотрения позволит - госчиновник, надеюсь  с извинениями, закроет заявку и Вы получите на почту соответствующее извещение. 
Кстати. Начиная со вчерашнего дня все отправленные письма дублируются в разделе портала "Мой журнал", там где Вы видели статус заявки. Это новшество направлено для того чтобы не зависеть от политик различных почтовых сервисов. И гарантировать получения всей информации по услуге. К сожалению письма отправленные из системы ранее вчерашнего дня там не появятся.

С уважением, Август.

**Comment by Harkavenko** [comment]
Уважаемый Август!
Я хочу быть правильно понятым. Я не имею целью упрекнуть Вас лично или Вашу команду разработчиков, работающих, как я понимаю, на волонтерских началах. Напротив, я искренне желаю Вам успеха, это очень важное начинание с точки зрения развития гражданского общества и облегчения бизнес процессов в государстве. Именно поэтому я сам решил воспользоваться Вашим порталом для регистрации. Вам сделали неудачный пиар- наверное, это не Ваша вина, и это поправимо. Мне кажется, надо правильно информировать пользователей о возможностях портала, и тогда будет меньше ситуаций непонимания.
Я не человек из будущего и не иностранец. Просто имея некоторый опыт в работе с инновационными технологиями и сервисами, я хочу сказать, что инновации не терпят компромиссов с устаревшими решениями. Такой комромисс выглядит более дешевым ситуативным решением, но на практике всегда оказывается дороже за счет потраченного времени, усилий, неудач на старте проекта. Запуская новые сервисы во всем мире инноваторы руководствуются только наилучшими практиками в своей области- благо в айти сфере много удачных примеров для подражания. Если мы хотим завтра жить в культурной стране, то применять культурные решения надо уже сегодня. А компромисс в таких случаях всегда выглядит как гибрид коня с "Мерседесом", который и не едет и не скачет, зато ржет и гадит на улице.
Искренне желаю Вам победы над нашей неидеальной реальностью и скорейшего запуска данного сервиса уже в рабочем режиме. Это важно и нужно.
С уважением.

**Comment by agerman-ua** [comment]
@Harkavenko 
Добрый день,
Спасибо за добрые слова о нас, но мы ведь не случайно собрались в одном месте. Как не случайна, наверное, и наша переписка.
По поводу инноваций - Вы смешали бизнес-инновации и инновации в госсекторе. Это, надеюсь  пока, несравнимые понятия. В первом случае чистая логика заказчика или автора, рыночные правила и время как арбитр "жизнеспособна инновация" или "нет". Госсектор - инерция и ещё раз инерция.
Мы полностью открыты для экспертных организаций, это часть идеи, сделать инновационный инструмент для людей, которым пользуется государство. Это не бизнес-проект который будет иметь конкретных бенефициаров, На каждой странице портала внизу Вы можете видеть тех, кто часть своих финансовых успехов вкладывает в этот проект. 

Кстати !!!! Вчера нам был ровно один год. Т.е. 12 месяцев от начала и уже столько сервисов не выходя из дома. Да не быстро (иногда очень не быстро) но гарантированно. Хотелось бы просто поделиться с Вами этой радостью.

И, возвращаясь к предыдущим постам есть несколько важных моментов, которые мы сейчас "потеряли из виду":
1. "... Сейчас вы заняты тем что дискредитируете прогрессивный и нужный государству сервис..." - во первых не государству а людям, а во-вторых именно госслужащие дискредитируют сервис.
2. "... Проблема в том, что рассматривать заявки должен алгоритм а не чиновник, иначе теряется смысл проекта. Алгоритм не надо мотивировать к работе..." - вот где в нашем государстве условия для этого? Где готовая база для инноваций? Или нам остановить проект и подождать когда сойдутся все условия? Именно данная фраза и дала основание для сравнения Вас с человеком из будущего (для которого это базовые и необходимые условия предоставления любых госуслуг) или иностранцем (которому это в той или иной степени доступно) не учитывающему реальную ситуацию в Украине.
3. "...Вам сделали неудачный пиар- наверное, это не Ваша вина, и это поправимо..." - :) Скорее государство нам предоставило людей-исполнителей из бумажного прошлого и вот это - действительно поправимо. :) А цель пиара - привлечь внимание! Как раз с этим и не было проблем.
4. "... Запуская новые сервисы во всем мире инноваторы руководствуются только наилучшими практиками в своей области- благо в айти сфере много удачных примеров для подражания..." - посмотрите доклад о проекте и скажите где именно в проекте использованы "старые практики"?!
https://youtu.be/_w8PfhlWEK4?t=1 (проект большой, поэтому просмотр займёт больше часа)

Вернусь к началу своего текста о том что мы не случайно собрались в одном месте. Такова жизнь, никто особенно в Украине не знает отдельно каждого из нашей многочисленной команды, какими бы чистыми и светлыми не были бы наши помыслы. :) Мы не могли выйти с ними за пределы наших семей. По разным причинам. И мы искренне благодарны Дмитрию Александровичу Дубилету за то, что он использовал все доступные ему возможности для начала изменения существующей абсурдной и неидеальной реальности в нашей стране.
И если произойдёт Чудо и Вы услышите меня "сердцем", я буду очень счастлив. Думаю по Вашим следующим постам это будет видно даже невооруженным и неискушенным взглядом.

Заранее благодарен за понимание.
С уважением,
Август.

**Comment by salkat** [comment]
Моя заявка (Звернення № 0-291351841), о которой я написал в (#486), висит с 02.06.16, то есть три недели. До сих пор в обработке. Хорошо что неделю назад я потратил кучу своего времени, приехал сам в Николаев, отстоял 5 раз в очереди за 4 полных дня (2-6 часов ожидания за раз) и таки зарегистрировал юр.лицо. 
В принципе, если всё сделать правильно с первого раза, то можно за день. 
Заявку можете снимать.

**Comment by agerman-ua** [comment]
@salkat 
Добрый день, 
В Вашем случае была возможность и регистратор закрыл заявку - Вам должно прийти письмо с причиной.
С уважением, Август.

**Comment by agerman-ua** [comment]
@Harkavenko 
Добрый день, получил промежуточный статус по Вашей заявке.
Была существенная задержка со стороны обрабатывающего органа, есть возможность снять обращение.
Снимать?
С уважением, Август.

**Comment by salkat** [comment]
Добрый день

Да, снимайте. Я уже сам всё сделал

2016-06-23 18:08 GMT+03:00 agerman-ua <notifications@github.com>:

> @Harkavenko <https://github.com/Harkavenko>
> Добрый день, получил промежуточный статус по Вашей заявке.
> Была существенная задержка со стороны обрабатывающего органа, есть
> возможность снять обращение.
> Снимать?
> С уважением, Август.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/499#issuecomment-228080794>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGouJhqNeRTjuhXaAZjMbpe1e8_5wslNks5qOqFtgaJpZM4I3Odh>
> .
>



-- 
С уважением,
Сергей Катков
+38 (067) 403 86 46
sergey.katkov@gmail.com <sergey.katkov@vox-line.net>

**Comment by Harkavenko** [comment]
Добрый день!
Если Вы имели ввиду мою заявку, то да, снимайте, я уже начал процесс оформления ФОП традиционным способом.
С уважением.

**Comment by agerman-ua** [comment]
@Harkavenko 
Хорошо. Вам будет отправлено письмо с отказом.
С уважением, Август.
