### ISSUE TITLE
Не працює оформлення субсидії

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#5]
https://www.facebook.com/igov.org.ua/posts/1625058211116389

Василий Великий
29 сентября г. 10:18
не работает оформление субсидии

Портал igov
29 сентября г. 10:23
Доброго дня!
Якщо хочете щоб ми допомогли, напишіть будь ласка деталі
Що саме не працює, і за допомогою якого банка ви ввійшли.

Василий Великий
29 сентября г. 10:34
заходил через приват.поиск не может найти субсидии.

**Comment by dmitrijzabrudskij** [comment]
https://www.dropbox.com/s/hlk7kuxikffxazx/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-09-29%2014.29.58.png?dl=0

субсидии нормально работают

он мог попасть на обновление процесса - как раз в это время я выкладывал его обновленную версию (то есть попал в промежуток в пару минут)

**Comment by VadymVolos** [comment]
А зараз субсидії тільки в Дніпропетровську працюють?
https://igov.org.ua/service/654/general
Там зеленим тільки Дніпропетровськ...

**Comment by dmitrijzabrudskij** [comment]
там еще и Киев зеленым

**Comment by VadymVolos** [comment]
Так можливо людина з іншого міста тому і не працює?

**Comment by VadymVolos** [comment]
PS виділіть будь ласка у випадаючому списку міст, зелені міста більш яскраво. Тому що Чорний і Темно зеленій зливаються, і їх погано видно.

**Comment by dmitrijzabrudskij** [comment]
если человек из другого города, ему выведется сообщение, что услуга скоро будет (но не ошибка)

проверил на нескольких устройствах - не сливается ничего. какие предложения по выделению у вас?

**Comment by VadymVolos** [comment]
Предложения очень простые, в ксс дописать бекграунд:

.color-green {
    color: #080!important;
    background: #F5F5F5;
}

**Comment by bvv4ik** [comment]
у нас планируется большой редизайн, так что все цвета будут подбираться в комплексе, дизайнером...  потому пока менять не будем отдельные (тут еще много от монитора зависит, и потому лучше чтоб это все в комплексе профи продумывал)

**Comment by VadymVolos** [comment]
А ссылку на дизайнерам можно? Мне интересно поучаствовать.
