### ISSUE TITLE
Сроки выполнения заявки

### ISSUE THREAD

**Issue by yarik1983** [e-government-ua/iForum#50]
Здравствуйте! Заявка на субсидию номер 4202273
подали 21 сентября. Днепропетровск, Ленинский район. До сих пор не получили ни одного уведомления об изменении статуса. Можно узнать, на каком этапе заявка?

**Comment by dmitrijzabrudskij** [comment]
добрый день
в понедельник ответят по вашей заявке - наконец-то связались с районом, но на месте их уже нет, поэтому перенесли на пон

**Comment by yarik1983** [comment]
здравствуйте! Ну что можете сказать по заявке?

**Comment by dmitrijzabrudskij** [comment]
добрый день
отвечу как только будет информация

**Comment by dmitrijzabrudskij** [comment]
субсидию согласовали. но так как пока само решение не дошло в район, ответ не отправляли

**Comment by yarik1983** [comment]
Спасибо. Такой вопрос: счета за коммуналку октября будут уже с учетом субсидии?

**Comment by dmitrijzabrudskij** [comment]
эта информация будет в решении, которое пришлют вам на почту. я его не видел, поэтому подсказать точно не могу. но так как оно принято в октябре, то субсидия должна пойти с ноября

**Comment by yarik1983** [comment]
спасибо!
