### ISSUE TITLE
№ 783066: про видачу повторного свідоцтва про смерть

### ISSUE THREAD

**Issue by AnnaKusraeva** [e-government-ua/iForum#500]
Днепропетровская область
https://igov.org.ua/service/714/general

1) без скана документа заявка не отправляется: Виявлено помилки.Загальне. Не додано скан-копію паспорту або паспортного документу

**при нажатии "Додати файл" ничего не происходит**

2) "Сплатити" - галка "Мені відомо, що за державну реєстрацію..." - "Сплата послуги":
**Ви впевненні, що тут має щось бути?**

**Comment by zolotovatatyana** [comment]
@AnnaKusraeva 
для того, чтоб воспользоваться этой услугой, Вы переходите на портал «Звернення у сфері державної реєстрації актів цивільного стану», и за работу портала отвечает МинЮст. 

На сайте есть кнопка "Допомога", которая рекомендует:
_

> У випадку виникнення проблем під час роботи з сайтом просимо зателефонувати:
> - черговому інженеру за телефоном: (+38 044) 206-71-10

_
