### ISSUE TITLE
Регистрация ФЛП - не обновляется документ при повторной заявке.

### ISSUE THREAD

**Issue by koi8** [e-government-ua/iForum#501]
Добрый день,
отправлял заявку с исправлениями, но держслужбовцу почему-то была видна старая версия файла, с неправильным указанием города. Я на 100% уверен что добавлял измененный файл, других версий файла на ноутбуке нет. Есть подозрение, что из-за того что использовалось такое же имя файла - из системы каким-то образом подтянулась старая версия. Спасибо держслужбовцю которая позвонила мне и описала что видит старый файл :(
Я переименовал файл и подал новую заявку, но теперь она почему-то уже неделю висит "в обработке"...
https://igov.org.ua/search?sID_Order=0-314247627

**Comment by koi8** [comment]
Номер заявки, в которой держслужбовцю почему-то была видна старая версия файла -  0-307953969.

**Comment by agerman-ua** [comment]
@koi8 
Добрый день, 
Госслужащей можно было не закрывать заявку, Вы могли прислать новую версию файла.
Просим Вас немного подождать.
Скорее всего реакция будет не ранее вторника. 
Понедельник - выходной. 
Кстати с праздниками Вас. :)

**Comment by koi8** [comment]
Получил ответ:

> Ваше звернення №0-314247627 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
> 
> Коментар держслужбовця (Причина: не заповнені обов'язкові поля: громадянство, адреса (Назва вулиці, проспекту, провулку тощо; Будинок ))
> 

Но при этом это все указано в заявке, прикладываю скриншоты! Какой-то саботаж.. Уже месяц пытаюсь ФОП сделать..

![wat1](https://cloud.githubusercontent.com/assets/2856182/16256509/3831c55a-385b-11e6-85ee-b6b6657193f2.png)
![wat2](https://cloud.githubusercontent.com/assets/2856182/16256511/3ca11d66-385b-11e6-99a3-fac20a327b3a.png)
