### ISSUE TITLE
Звернення № 0-317620466

### ISSUE THREAD

**Issue by olenmoisen** [e-government-ua/iForum#502]
В обработке с 10 утра 13.06.
Время  обработки превысило средний показатель рассмотрения.

Покажите дополнительные данные по статистике: количество обработанных в день, распределение по количеству дней согласования, чтобы понимать можно ли данным сервисом в принципе  пользоваться.

**Comment by agerman-ua** [comment]
@olenmoisen 
Добрый день, 
В статистике действительно указано среднее время рассмотрения уже полностью именно закрытых заявок.
Изменения, связанные с данными статистики, касаются абсолютно всех предоставляемых услуг, процессы в которых имеют разную структуру. Поэтому, к сожалению, пока более детальную информацию (нестандартную) мы не можем использовать на них. Хотя, конечно, это потенциально повысит юзабилити услуги. Мы это понимаем.
Также прикладываем все возможные усилия чтобы ситуация стала более стабильной и предсказуемой.
Заранее благодарны за понимание.

**Comment by olenmoisen** [comment]
Какой смысл предоставлять среднюю температуру по палате? Кому это в принципе интересно?
Не вижу никаких проблем в группировке статистики по типу заявки.

**Comment by agerman-ua** [comment]
@olenmoisen 
Не могу, к сожалению, поддержать беседу о технической стороне вопроса.
Есть минимальная информация. 
Она, у стабильных услуг, абсолютно релевантна и достаточна. Ну и необходима, конечно.
Проблема на самом деле не в статистике. Повторюсь - работаем над качеством и обратной связью.
С уважением, Август.

**Comment by olenmoisen** [comment]
Разумеется, проблема не в статистике. 
Проблема - от несбывшихся ожиданий. Если бы пользователя предупреждали, что заявки могут рассматриваться неделю, две и более (по разным причинам), то проблемы бы не было. 
Просто нужно сказать об этом на главной странице. Если вы спешите, то в настоящий момент - это не к нам.

**Comment by agerman-ua** [comment]
@olenmoisen 
Добрый день,
Указывать то что Вы предлагаете, тоже не совсем правильно. 
У нас есть госорганы которые прекрасно работают и используют портал как и планировалось. 
Много людей уже оперативно получили данную услугу и просто не пишут об этом. Наверное считают что это так очевидно, не выходя из дома (работы) получить госуслугу с регистрацией в налоговой. Но, повторюсь, мы не останавливаемся на текущем положении вещей. 
И... Если Вы ожидали не выходя из дому получить услугу, то Вы её обязательно получите и Ваши ожидания сбудутся.

Ещё раз огромное спасибо за Ваше понимание общей ситуации.
С уважением, Август.

**Comment by agerman-ua** [comment]
Добрый день, @olenmoisen 
23.06 Вам заявку закрыли с положительным результатом.
Должно было прийти письмо с деталями.
Закрываю Вашу тему, но если вопросы остались - спрашивайте.
С уважением, Август.
