### ISSUE TITLE
Звернення № 0-329772103 Державна реєстрація змін до відомостей про фізичну особу – підприємця

### ISSUE THREAD

**Issue by ibragimKherson** [e-government-ua/iForum#503]
16.06.2016 було відправлено заяву для зміни місця реєстрації  ФОП. в м Херсон.
Ця послуга виявилась платно, але знайти рекізити  та суму для оплати не вдалося ні на порталі ://igov.org.ua, ні на сайтах реєстраційної служби.
У коментарі від 17/06/2016 були надіслані реквізити Дніпропетровської області, але сума не вказана. 
Прохання надіслати вірні реквізити і суму для сплати послуги!!!!!!!

**Comment by agerman-ua** [comment]
@ibragimKherson 
Доброго дня,
Вам не треба хвилюватися щодо відсутності реквізитів.
Після аналізу Вашого звернення і взяття в роботу платної послуги Вам обов'язково буде надіслано листа з кнопкою для сплати. 
Вам знадобиться для проведення платежу просто платіжна картка з наявністю на ній достатньої суми коштів. Суму оплати буде видно до її проведення.
Для гарантування отримання заявниками абсолютно всіх листів, які були відправлені до них, ми запровадили з учора :) нові можливості розділу "Мій журнал", зараз там будуть доступні всі листи. 
У Вашому випадку лист дуже важлива частина послуги оскільки саме там можливість для сплати.
З повагою, Август.

**Comment by ibragimKherson** [comment]
Нажаль ніякого листа з кнопкою не отримали, натомість є таке: 
    17.06.2016 10:42

    Зауваження по заяві 0-329772103
     

    Необхідно уточнити дані, за коментарем: РЕКВІЗИТИ РАХУНКІВ ПО СПЛАТІ БАНК: ГУДКСУ у Дніпропетровській області МФО: 805012 КОД ПЛАТЕЖУ: 22010300 КОД ОТРИМУВАЧА (ЄДРПОУ): 36916755 ОТРИМУВАЧ ПЛАТЕЖУ: УК у м. Жовтих Водах / місцевий бюджет м. Жовті Води РАХУНОК: 31417501700018 Сума ______________ Адміністративний збір за проведення державної реєстрації ЮО та ФОП

iGov
    17.06.2016 09:27

    Зауваження по заяві 0-329772103
     

    Необхідно уточнити дані, за коментарем: Вам треба прикріпити квитанцію про сплату за виконання послуги. Адже без квитанції послуга не буде виконана!

**Comment by ibragimKherson** [comment]
Що робити щоб не відклонили заяву????. адже є терміни подання документів, які у понеділок вже закінчуються

**Comment by dmitrijzabrudskij** [comment]
поищите письмо в папке спам, пожалуйста - должно быть
важно оплатить именно по той кнопке, которая сгенерировалась в письмо

насчет сроков не беспокойтесь - есть 14 календарных дней на подачу любых недостающих документов после принятия заявления в работу (а оно принято у Вас вчера)

**Comment by ibragimKherson** [comment]
Дякую за допомогу, лист прийшов, змогли заплатити, тепер будемо чекати на результат.

**Comment by ibragimKherson** [comment]
Доброго дня, заявку обробили і зміни внесли, хоч і не так швидко як сподівалися, але все одно дякуємо, сподіваємося далі буде краще!!! . Підскажіть, як тепер забрати оригінал Виписки, просто прийти в реєстраційну палату з "унікальним кодом" ?

**Comment by dmitrijzabrudskij** [comment]
добрый день!

а для чего она в оригинале - при любом запросе в реестр по Вашему флп будут отображаться актуальные данные.

**Comment by ibragimKherson** [comment]
Ну например, для заключения договоров. втч с банками нужна заверенная копия выписки, все-таки хотелось бы её иметь при себе.

**Comment by Propeller-SV** [comment]
@ibragimKherson 
Вчера оформил предпринимательский счет в Приват Банке без выписки. Все необходимые данные берутся из базы министерства юстиции автоматически. Также по [ссылке](https://usr.minjust.gov.ua/)  имеется текст:

> Електронні документи мають таку ж юридичну силу, як і паперові. Автентичність кожного електронного документу підтверджується його номером, завдяки можливості повторного завантаження сформованого документу. Номер документу надається заявнику одразу після оплати та міститься на кожному аркуші документу.

Там же можно заказать этот самый документ, оплатив картой всего 50 гривен (в ЦНАП это стоит 75 грн, если не ошибаюсь, оплатив в кассе по старинке)  без очередей, походов и ожидания, мгновенно. Отказываться от бумажек страшно, понимаю, но от этого никуда не деться, если мы хотим эволюционировать.

**Comment by agerman-ua** [comment]
Добрий день, @ibragimKherson 
Розумію так що у Вас питань щодо отриманої послуги більше немає?
Якщоя неправий - відкрийте знову цю гілку форуму або створіть нову.
З повагою, Август.
