### ISSUE TITLE
заявка 0-302294301

### ISSUE THREAD

**Issue by ihormelnyk** [e-government-ua/iForum#504]
Доброго дня! Коли чекати на рішення по заявці 0-302294301? Які граничні терміни? заявка була створена 	6 червня 2016 р. о 21:43, Львівська обл. Кобзар-Мельник Марія, реєстрація ФОП.

**Comment by ihormelnyk** [comment]
Чи можу я отримати хоч якусь відповідь!? Чи йти мені в ЦНАП і подавати особисто всі документи? Цю тоді заявку можна відмінити?

**Comment by agerman-ua** [comment]
@ihormelnyk 
Доброго дня,
Ваша заявка вже в роботі. До вівторка новин точно не буде. Думаю вже запізно відміняти її.
В перший робочий день зроблю запит до урядовця про статус Вашої заявки. 
І тоді повернемося з Вами до питання її відміни.
З повагою, Август.

**Comment by ihormelnyk** [comment]
Дякую, дуже чекаю на Вашу відповідь.

**Comment by ihormelnyk** [comment]
Доброго дня. Може є якісь новини по заявці? Дякую.

**Comment by ihormelnyk** [comment]
Доброго дня @agerman-ua 
Ви робили запит до урядовця? є якась інформація про статус заявки?
Дякую

**Comment by ihormelnyk** [comment]
Ваше звернення №0-302294301 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін.
Дякую

**Comment by agerman-ua** [comment]
@ihormelnyk І Вам хай щастить.
З повагою, Август.
