### ISSUE TITLE
Звернення № 0-328614450  АВГУСТ КОГДА ОТВЕТИТЕ НА ВОПРОС???

### ISSUE THREAD

**Issue by IvanMalovichko** [e-government-ua/iForum#506]
Який строк здійснення реєстраційної дії реєстратором (реєстрація ФОП)??? Потрібно терміново! Очікували 24 години, як зазначено в Законі, проте до сих пір в обробці - з 15.06!
Коли буде оброблене звернення?
Наперед вдячний!

**Comment by agerman-ua** [comment]
Доброго дня.
На жаль ми не можемо гарантувати такий строк у 24 години. Оскільки момент подання Вами звернення це не той момент коли держслужбовець почав його обробку. Воно попадає в чергу, з якої її i беруть в обробку. 
Ми гарантуємо тільки те що жодну заявка не може бути загублено випадково або спеціально.
Також від 16.06.2016 ми можемо гарантувати надання Вам всієї історії листування щодо Вашого звернення безпосередньо на порталі в розділі "Мій журнал".
Якщо терміновість питання Вам не дозволяє дочекатися - Ви можете прямо тут чітко зазначити своє бажання щодо закриття Вашої заявки. У випадку коли справа ще не передана до держреєстратора ми ініціюємо її закриття і Ви отримаєте від системи повідомлення в листі.
Після цього Ви зможете або персонально звернутися до держреєстратора або подати нове звернення.
Також Ви можете задавати питання безпосередньо держслужбовцеві в розділі "мій журнал" але гарантувати ті чи інші дії та термін відповіді від урядовця ми не можемо.

Впевнений що вся команда порталу на взаєм теж вдячна Вам.
З повагою, Август.

**Comment by IvanMalovichko** [comment]
Какой срок регистрации??? Интересует непосредственно моя заявка - как долго ждать? Мне нужно знать - или это будет день-два - тогда отменять не нужно, или это будет больше - тогда нужно???

**Comment by IvanMalovichko** [comment]
Как узнать, передана ли заявка госрегистратору или нет?? Очень прошу уточнить статус по заявке!

**Comment by IvanMalovichko** [comment]
Прошла неделя с момента оформления заявки на регистрацию ФОП на едином налоге (Киевская область). Сколько еще ждать??? Что за отношение???

**Comment by IvanMalovichko** [comment]
# **ЕСТЬ КТО ЖИВОЙ?????**

**Comment by agerman-ua** [comment]
@IvanMalovichko 
Добрый день,
Да. Слава Б-гу все-все живы. 
У нас у всех мультизадачность но процессоры "с завода" только с одним ядром.
:)
Сейчас разберёмся. Спасибо за терпение.
С уважением, Август.

**Comment by agerman-ua** [comment]
@IvanMalovichko 
Обещали сегодня уточнить сроки у регистратора.
Если коротко - статус "в работе".
Простите что не могу ответить более точно.
С уважением, Август.

**Comment by IvanMalovichko** [comment]
Спасибо! 
Я статус сам могу проследить. 
Регистрация просто горит!!! Можно ли ускорить???

**Comment by IvanMalovichko** [comment]
РЕБЯТА ЗАРАБОТАЛО!!! Регистрация прошла УСПЕШНО!!! 
СПАСИБО!!!!!!!!!!!!!!!!!!!
Даже не верилось что это работает))
К заявке на регистрацию прикрепляли завление на регистрацию плательщиком единого налога. Пока данных о регистрации плательщиком единого налога нет. 
КОГДА БУДЕТ???)))))

**Comment by IvanMalovichko** [comment]
# Так что там с регистрацией плательщика единого налога? Заявление было подано одновременно с заявлением на регистрацию ФОП. Уже конец месяца! Как найти контактное лицо??? Кто решает этот вопрос???

**Comment by Propeller-SV** [comment]
А где вы проверяете данные? [Это](https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx) и [это](http://www.sfs.gov.ua/anulsv) не работает. А [здесь](https://usr.minjust.gov.ua/ua/freesearch) я вижу, что поставлен на учет, но про единый ничего нет.

**Comment by IvanMalovichko** [comment]
Первая ссылка - работает (по ней как раз нужно проверять). В последней ссылке видно, что вас просто поставили на учет, но не зарегистрировали плательщиком единого налога.

**Comment by agerman-ua** [comment]
@IvanMalovichko 
Добрий вечір,
Вибачте що з таким запізненням відповідаю.
Або вже все нормально, або не туди дивлюсь.
В реєстрі мінюсту видно що ви на обліку в податковій як платник єдиного внеску з 23.06.
Виправте мене, будь ласка, якщо я неправий.
У будь-якому випадку вибачаюсь за затримку з відповіддю.
З щирою повагою, Август.
