### ISSUE TITLE
не загружена скан копия свидетельства о регистрации ФЛП

### ISSUE THREAD

**Issue by PolinaKlitsakova** [e-government-ua/iForum#509]
уже обращалась по этому вопросу в теме #494 . Все же не пойму, что мне сделать, чтобы получить свидетельство о регистрации ФЛП. Куда обратиться?

**Comment by agerman-ua** [comment]
@PolinaKlitsakova 
Добрый день,
Простите, давайте сначала. В дополнение к ответу Вам в теме #494.
Вы получили письмо с положительным решением?

**Comment by PolinaKlitsakova** [comment]
Да, получила. И нахожу себя в едином реестре.

**Comment by Propeller-SV** [comment]
Поддержу вопрос. В какой-то из веток видел, что через некоторое время после регистрации, если выбрать "Результат надання адміністративних послуг" вот здесь - [МинЮст](https://usr.minjust.gov.ua/ua/freesearch) , то можно будет скачать нужные документы. В моем случае я вижу следующее:
Реєстраційна дія: Державна реєстрація фізичної особи-підприємця
Дата дії: 10.06.2016
Документи: Відомості відсутні.

Что-то не так?

**Comment by agerman-ua** [comment]
Всем добрый день,
@PolinaKlitsakova 
Думаю наш разговор не разрешится пока не получу ответ от самого регистратора. Прошу подождать.
@Propeller-SV 
"Некоторое время" - очень обтекаемое понятие. Думаю лучше всего просто убедиться в наличии записи в реестре. Всё остальное - это дополнительно. Всё равно при необходимости все будут проверять именно запись в реестре.
Насколько я понял, не всегда есть такой файл у чиновника.
Прошу, если не трудно, обосновать необходимость для ФОП иметь файл после регистрации.
Спасибо заранее.
С уважением, Август.

**Comment by PolinaKlitsakova** [comment]
Хорошо, спасибо, подожду.

**Comment by Propeller-SV** [comment]
@agerman-ua 
В реестре запись есть. Я впервые оформляю ФЛП и насколько понтиаю выписка из реестра нужна для открытия счета в банке для работы с юридическими лицами и заграницей. Или я не прав и она уже не нужна, банк может проверить электронный реестр самостоятельно?
Спасибо.

**Comment by agerman-ua** [comment]
@Propeller-SV 
Как Вы понимаете, при наличии интернета и Вашего ИНН проверить может любой.
И банк и человек. 
По поводу документов - по "коду опису" должны быть доступны.
С уважением, Август.

**Comment by Propeller-SV** [comment]
@agerman-ua 
Понимаю, что проверить могут. Понимаю также, что этого может быть не достаточно, "нужна бумажка". Проверка по "коду опису" к сожалению возвращает такое:
Реєстраційна дія: Державна реєстрація фізичної особи-підприємця
Дата дії: 10.06.2016
Документи: **Відомості відсутні.**
Звонок в Приват Банк подтвердил: для открытия предпринимательского счета необходима выписка из реестра.

**Comment by agerman-ua** [comment]
@Propeller-SV , @PolinaKlitsakova 
Постараюсь разобраться в целом с ситуацией, это уже за пределами базы iGov.
Изначально предполагалось что если у Вас есть "код опису" по нему должно быть всё доступно.
Вам обоим были отправлены эти коды но, судя по всему, по ним вы не видите "Свідоцтво про державну реєстрацію СПД / Виписка".
Уверен что всё нормально, но разобраться, конечно, стоит.
С уважением, Август.

**Comment by Propeller-SV** [comment]
Зарегистрировав ФЛП через iGov oткрыл предпринимательский счет в Приват Банке вообще без каких-либо дополнительных документов. Являясь клиентом как физическое лицо просто назвал идентификационный код и расписался на планшете. Никаких справок, выписок и копий не нужно. Заняло 10 минут. Приятно, черт побери.

**Comment by PolinaKlitsakova** [comment]
@agerman-ua по коду пока что ничего не находит, а сегодня я вообще не могу зайти в раздел Документы. Пишет title error 
((((

**Comment by agerman-ua** [comment]
@PolinaKlitsakova 
Как сейчас? Находит?
С уважением, Август.

**Comment by agerman-ua** [comment]
Проверил - всё нормально, раздел на минюсте не пустой. Закрываю.
Всем спасибо.
