### ISSUE TITLE
После подачи заявки прошло 5 недель

### ISSUE THREAD

**Issue by masliyka** [e-government-ua/iForum#51]
Здравствуйте! Подали заявку на субсидию 24 сентября. До сих пор нет ответа по ней. Номер заявки 4758607. Днепропетровск , АНД район. Подскажите, когда  будет известен результат заявления?

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой район?

**Comment by masliyka** [comment]
АНД район (Амур-Нижнеднепровский)

**Comment by masliyka** [comment]
что-нибудь известно по моей заявке?

**Comment by masliyka** [comment]
Номер заявки 4758607. ДНЕПРОПЕТРОВСК, АМУР-НИЖНЕДНЕПРОВСКИЙ район. Заявка в работе с 25 сентября

**Comment by dmitrijzabrudskij** [comment]
жду ответ от района. отпишусь как только получу его

**Comment by masliyka** [comment]
Хорошо! Буду ждать!
