### ISSUE TITLE
Люди жаліються що не можуть обрати дату візиту

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#510]
Привіт! Люди жаліються що не можуть обрати дату "Зазначте бажану дату / час візиту до сервісного центра". Людям не зрозуміло чому вони не можуть обрати дату. Там біля дати треба написати червоними літерами якщо дата не обирається оберіть іншу філію потрібної вам установи, або оберіть інший проміжок часу.

Простою мовою - треба там написати щоб людина зрозуміла чуму не обирається дата, і що потрібно щоб вона обралася.

**Comment by VadymVolos** [comment]
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1719292795026263&reply_comment_id=1719302208358655&comment_tracking=%7B%22tn%22%3A%22R9%22%7D

**Comment by denysenkok** [comment]
))) Не червоними літерами писати!!! 
А треба забрати це поле - ВЗАГАЛІ!!!! Або хоча б зробити не обов'язковим...
Все одно, дату візиту повинен назначити виконавець СЦ, у зворотньому листі...
- Як, до прикладу, бути тим у кого законодавчо обмежено час перереєстрації 10 днів????
Чи ви хочете сказати, що коли я звернусь в СЦ безпосередньо в мене не приймуть заяву?
Ба більше - ще й запропонують послугу з "термінового виготовлення", позачергово так би мовити... ;)

**Comment by AndreyPopovNew** [comment]
@VadymVolos тут @Koffeek уже скоро как пол-года будет обещанию исправить эту ситуацию!!!

проблема поднималась давным давно и давным давно было обещано, что вместо выпадения ПУСТОГО поля будет писать, что свободных тайм-слотов нет!!!

и это должно быть написано не где-то рядом, а именно когда ПУСТОЙ список - нажимаешь на поле выбора времени, а тебе выскакивает окно - "В этом месяце доступных дат уже нет. Ождайте открытия дат в следующем месяце или попробуйте другое подразделение ДМС"

**Comment by AndreyPopovNew** [comment]
еще [25 апреля](https://github.com/e-government-ua/iForum/issues/332#issuecomment-214181631) мне было "поставлено на вид" , что не надо "даставать" разработчиков.

но как оказалось, проблему НИКТО не хочет решать.

**Comment by denysenkok** [comment]
@Koffeek - а знаєте, чомусь, Ваша відповідь мене не здивувала...
Все просто - це "Український підхід" до справи !!! "Це Україна - детка"!!!
- БРАВО! - БІС!
**в уряді та пресі, поставили дУже жИрну гАлочку - "Електронне обслуговування", "Боротьба з корупцією"!!!, що там ще, нагадайте... !!!???**

І **нАсрати** що вОно не працює - відзвітували!!! Бабло європи можна списати... при нагоді...

А чи знаєте вИ, що при зверненні в сЕрвісний цЕнтр м. Львів (для оформлення "переобладнання без заміни номерів агрегатів") - мене/тебе/його - ще змусять пройти "експерта", власне для перевірки цих номерів.... Бо рАптом вОни змінились...  В Києві, Одесі, Дніпрі - не змінюються, а у Львові чомусь дуже часто змінюються.... 
Розумію, що вАм пофіг,,, ну подумаєш, сЕрвісний центр лишніх 200грн на кожному зАробить...  Що тепер - 200 грн... - тьху, в туалет в пАрижі сходити... пОдумаєш...

Зате у вАс - є, альтернатива!!!!

дАвайте лише - без образ, без нарікань, без жаління....
- хіба ж можна ображатись і жалітисьна - вОлОнтерів? Які й тАк займаються цим у вільний від роботи час, безоплатно... Ми ж маєм - в ноги кланятись, - по гроб вдячними бути...

P.S.
Вибачайте, й не ображайтесь,,, просто, аж дуже цікаво - А нахера, й кому ви це робите????
- Нема більше чим зайнятись????

**Comment by Koffeek** [comment]
@denysenkok Так проект волонтерський і коли ми просимо долучитись і допомогти - то щось бажаючих замало. Увесь Львів тягне на собі один координатор. Бабло Європи - то не до нас, то ж і тут мимо. Якщо Ви знаєте як без проблем запускати послуги з державними органами - запрошуємо в команду, або чекаємо на Ваш проект. Робимо для того, щоб змінювалось ставлення людей (і громадян і держслужбовців) до процесу надання послуг. Так само можна казати про людину, яка висаджує квіти біля будинку, бо напевне їй це більше за усіх треба.

**Comment by denysenkok** [comment]
@Koffeek  - радий буду допомогти, звертайтесь... Правда, не знаю чим зможу зарадити, але бажання - є!

- Для початку, аж дуже цікаво - Хто придумав це поле при заповненні анкет?
- Хіба заявки не можуть накопичуватись у "виконавця", по мірі їх надсилання сЕрвісом????
- Хай "виконавець" сам назначає "час звернення в сЕрвіс", в терміни вказані в законодавстві.... 
- А головне - кількість виконаних заявок (через сЕрвіс, і без) - має бути "прозора"!

- чи я щось не з тією корупцією пропоную боротись???

**Comment by kurbpa** [comment]
@denysenkok 

> 
> А чи знаєте вИ, що при зверненні в сЕрвісний цЕнтр м. Львів (для оформлення "переобладнання без заміни номерів агрегатів") - мене/тебе/його - ще змусять пройти "експерта", власне для перевірки цих номерів.... Бо рАптом вОни змінились... В Києві, Одесі, Дніпрі - не змінюються, а у Львові чомусь дуже часто змінюються....
> Розумію, що вАм пофіг,,, ну подумаєш, сЕрвісний центр лишніх 200грн на кожному зАробить... Що тепер - 200 грн... - тьху, в туалет в пАрижі сходити... пОдумаєш...

А знаете ли Вы, что меня/тебя/его заранее предупреждают об этой экспертизе в емейле ?
А знаете ли Вы, что  обязательные осмотры это не прихоть Сервисных Центров?
А знаете ли Вы сколько сил и нервов тратится на запуск каждой услуги хотя бы просто для того чтобы сократить время обслуживания с сохранением существующего процесса? На первом этапе - хотя бы просто сократить время и дать опалить  стоимость услуги удобным для  гражданина способом без комиссий карманных банков? Мы делаем всё, всё что можем в рамках закона. 
И если  что-то не получается так гладко как хотелось бы - поверьте нам не наплевать. 

> хіба ж можна ображатись і жалітисьна - вОлОнтерів? Які й тАк займаються цим у вільний від роботи час, безоплатно... Ми ж маєм - в ноги кланятись, - по гроб вдячними бути...

И опускаются руки у меня, как у волонтера, что-то делать после таких слов. 
Спасибо за столь "подбадривающие" эмоции.

**Comment by zolotovatatyana** [comment]
@denysenkok 
В Вашем потоке возмущения текущей ситуацией  и желания борьбы с коррупцией... нет ни единого конкретного предложения как побороть эту самую коррупцию.

**Comment by AndreyPopovNew** [comment]
@denysenkok 

> Все одно, дату візиту повинен назначити виконавець СЦ, у зворотньому листі...

пишите большую глупость, даже НЕ зная логики процесса!

вам назначат через три месяца - вас это устроит? 

вы тут про борьбу с коррупцией пишите, а сами предлагаете самый коррупционный метод оставить!!!

от этого как раз и хотят уйти!!!!!!!!!!!

**Comment by denysenkok** [comment]
Можливо Вам буде цікаво...  вчора перереєстрували...
Заодно - провели експеримент, оскільки був з колегою, з яким разом ставили ГБО, на двух однакових машинах. - "Машина 1" - все "по закону", "Машина 2" - "по експрес методу".
Заїхали на "огляд експерта", 9:00, разом.
      "Машина 2" - пояснюємо причину приїзду і питаємо експерта допомоги пришвидшити процес.
Експерт показує пальцем на хлопчину, що п'є каву на підвіконні, під стендом з мордою авякіна і великим надписом "Не бери хабарі"! ))). Хлопчині розказуємо що потрібно, він дає заготовлений список платежів, топаєш в касу оплачуєш 3 платіжки: Експерта 189, Зміна свідоцтва 396, Консультація 300. Показуєш платіжки хлопчині, дві перші несеш експерту. - Все! 
Далі відбувається - "магія"! Виїжджаєш на паркінг, п'єш каву, рівно через 40 хвилин дзвінок - в яке вікно підійти, підписатись, і забрати нове свідоцтво. Загалом потрачено часу - 1 година, та 700 грн.

     "Машина 1" - 1 годину машина стояла в експерта, після чого він повертає тобі документи з актом огляду й заготовкою р/рах. Йдеш в касу плотиш 189, повертаєшся в вікно до експертів 2, які тримають документи ще 1 годину. Направляють тебе в "ВІКНО ЕЛЕКТРОННОЇ РЕЄСТРАЦІЇ" де тобі дають талончик з номером. Сидиш чекаєш коли воно з'явиться на табло. +/- 1,5 години...
Підходиш до вказаного вікна. Де тобі повідомляють що треба оплатити заміну свідоцтва 396 грн. Люб'язно повідомляють що приймуть поза чергою. Повертаєшся з платежкою і тут - сюрприз! Так як машина бралась в кредит (закрито в 2011р), на старому Свідоцтві є позначка, тобі повідомляють що без довідки з банку про погашення кредиту- нічим не допоможуть! 
Супер!!!
Люб'язно повідомляють, що допомогти може тільки "цей правильний нотаріус", дають адресу контори... (дзвонимо, ціна 400 грн).
Дзвониш в банк, виявляється що відділення де ти обслуговувався вже закрито. Переводять справу в зручне для тебе відділення. Їдеш... Там тобі розповідають як тяжко жити і приймають заяву. Право підпису цієї довідки є тільки в якогось мудака в Києві, і навіть якщо він сьогодні підпише, вона 3 дні буде йти почтою....
Йдеш в магазин, береш коробку цукерок за 60 грн, йдеш до керівника відділення, сльозно умовляєш, + 200 грн допомагають схилити керівника стати на твій бік... Виписують довідку + копія доручення про право підпису.
Їдеш знову в ТСЦ, здаєш документи - без черги. Чекаємо 2 години, дають надруковану заяву - перевіряємо правильність даних, підписуємо, здаємо. 
Чекаємо ще 2,5 години коли на табло з'явиться твоє прізвище та номер віконця.
Загалом страчено - 7 годин 20 хвилин, та 660 грн.

А тепер саме цікаве - "Машина 2" теж була в кредиті, і теж була позначка...!!! ;) 

То хто в цьому випадку - лох, "машина 1" чи "машина 2" ???  )))

**Comment by denysenkok** [comment]
@kurbpa - привіт!
А що не сподобалось? "Назвався когутиком - лізь в борщ" (с) укр.приказка
- для кого Ви це все робите? Не для мене - ні?
Ото-ж бо!!!...
Поки що ви все гарно зробили - "для них"... 
А як жеж - Увесь ТСЦ, всі урядові портали, завішані рекламою iGov, - альтернативний варіант, нема корупції...
"Задумано - добре, а зроблено - .........." (с)
Я тільки не полінувався дати оцінку Вашій роботі... не більше...
І перестаньте робитись схожими на "піндосів"... Це їм ні в якому разі не можна прямо показати на проблему. Завжди треба хвалити й десь ненароком натякати - "а може тут треба поправити"...
Рано нам ставати схожими на них... ! Ще дуже багато треба зробити...

@AndreyPopovNew 
Пробачте, так, Ви праві... Мені не відомі "таїнства" і "нюанси"...

Загалом - дозволю собі дати пораду: - Спрощувати все потрібно. Як можна більше... Бо чим більше "закутків", тим більше в них можливостей викручуватись, ставити людину в безвихідь.
Хорошу справу почали, от би ще трошки менше "пристосовуватись під бюрократів".
Радий буду допомогти, чим зможу.

**Comment by denysenkok** [comment]
@AndreyPopovNew 

> вам назначат через три месяца - вас это устроит? вы тут про борьбу с коррупцией пишите, а сами предлагаете самый коррупционный метод оставить!!! от этого как раз и хотят уйти!!!!!!!!!!!
Чому назначить через 3 місяці? Якщо в нього заявка поступить в такій-то годині і автоматом попаде в загальну чергу виконання...
Тут треба думати... 
Напевно має бути два етапи "справи", 1 - консультативний (збір необхідних даних), 2 - на виконанні (коли заявка перевірена й зареєстрована).
Вікно подачі заявки могло-б бути персональним за кожним клієнтом (з унікальним посиланням доступу) і інтерактивним, з полями коментарів до кожно офіційного поля заявки, де можна вести діалог із спеціалістом СЦ, де він (спеціаліст) вказує - що не вірно. І коли клієнт вірно вносить/справляє/закачує вірні копії, дані - заявка автоматом реєструється. І від цього часу тікає годинник виконання.
Коли заявка виконана - клієнту приходить повідомлення - прийди забери.

Як до прикладу робиться в лабораторіях Sinevo....

**Comment by kurbpa** [comment]
@denysenkok 
Полемика бесполезна.
Простите, но Вы в розовых мечтах живете, если считаете что всё так просто сделать и запустить.
Мою работу оценили  в "ноль" - мне это не нравится.

Вы сможете лучше  наверное. 
Я готов Вам дать контакты коллег в Сервисных Центрах Львова - сделайте всё как надо и научите меня как надо делать в остальных регионах.

мой емейл kyrbatsky@gmail.com
Я с радостью приму Вашу помощь для  приведения услуг к идеальному виду.

**Comment by denysenkok** [comment]
@kurbpa  
Павел, я же извинился за то что многого не знаю... 
Оценка, простите - реальная. А как можно дать другую оценку продукту которым не возможно воспользоватся?
Давайте будем реалистами...
Спасибо за возможность связаться с Вами. Обязательно воспользуюсь.
Еще не знаю как, но очень бы хотелось помочь...
