### ISSUE TITLE
"Книга обліку доходів" в Державна реєстрація фізичної особи – підприємця

### ISSUE THREAD

**Issue by ionafan2** [e-government-ua/iForum#511]
На сколько мне известно у ФОП на 3-ей группе должна быть "Книга обліку доходів".
Да не просто так а заргегестрированная в налоговой (там что-то с ней делают, печати нумерация...)
Так вот вопрос после онлайн регистрации - куда нести книгу на регистрацию?
В какую налоговую?

**Comment by Maestra86** [comment]
я носила по месту регистрации ФОП

**Comment by sector612** [comment]
[Тут](https://taxer.ua/ru/kb/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%B8_%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BA%D0%BD%D0%B8%D0%B3%D0%B8_%D1%83%D1%87%D0%B5%D1%82%D0%B0_%D0%B4%D0%BE%D1%85%D0%BE%D0%B4%D0%BE%D0%B2) толково описано, в том числе ведение книги в электронном виде :)

**Comment by ionafan2** [comment]
@sector612  Спасибо за ссылку! 

http://zakon3.rada.gov.ua/laws/show/z0800-15/paran28#n28
>  4. У разі обрання платником податку ведення Книги в електронній формі:
> 
> 1) платник податку зобов’язаний отримати в акредитованому центрі сертифікації ключів, включеному до системи подання податкових документів в електронному вигляді, посилені сертифікати відкритих ключів; укласти договір про визнання електронних документів з контролюючим органом за основним місцем обліку; сформувати та надіслати до такого контролюючого органу заяву про обрання способу ведення Книги в електронній формі засобами електронного зв’язку в електронній формі з дотриманням умови щодо реєстрації електронного підпису підзвітних осіб у порядку, визначеному законодавством, використовуючи такий електронний сервіс;
> 
> 2) контролюючий орган за основним місцем обліку реєструє заяву про обрання способу ведення Книги в електронній формі в реєстрі поданих заяв та протягом 3 робочих днів формує і надсилає платнику податку повідомлення про реєстрацію Книги із зазначенням реєстраційного номера Книги та дати її реєстрації;
> 
> 3) після отримання платником податку повідомлення про реєстрацію Книги така особа здійснює операції з її ведення згідно з цим Порядком. Внесення даних за підсумками робочого дня здійснюється щоденно, але не пізніше наступного календарного дня;
> 
> 4) у Книзі в електронному вигляді допускаються виправлення помилок або коригування шляхом доповнення рядка, в якому відображається від’ємне або позитивне значення.
