### ISSUE TITLE
Заявка №0-307779411

### ISSUE THREAD

**Issue by ConstantineCher** [e-government-ua/iForum#512]
Добрый день!

Оставил заявку 8 июня на внесение дополнительных видов деятельности КВЕД в разделе "Державна реєстрація змін до відомостей про фізичну особу – підприємця". 
Недавно появилось сообщения, что заявка Заявка №0-307779411 закрыта. Это значит, что мне добавили КВЕД? Или произошла какая-то ошибка?

**Comment by agerman-ua** [comment]
Добрый день, @ConstantineCher 
Простите за задержку с ответом, Вам отказали 17.06 по причине неправильных формата кведа. Должно было сразу прийти письмо на почту которую Вы указывали при подаче обращения.
Если есть вопросы - обращайтесь. Тему закрываю.
С уважением, Август.

**Comment by ConstantineCher** [comment]
Письмо к сожалению, не пришло((

20 июля 2016 г., 18:02 пользователь agerman-ua <notifications@github.com>
написал:

**Comment by agerman-ua** [comment]
Хм. Тогда у нас ещё почта не дублировалась в разделе "мой журнал". Может в спаме?
В любом случае там отказ и причина связана форматом кведа. Если ещё актуально, будет на этой неделе новая версия услуг - там формат будет уже контролироваться. Но адекватность кода остается на Вас. Ссылка там есть в самой услуге на справочник.
Подавайте новую заявку, если не торопитесь то с понедельника. Если хотите - подавайте сейчас, просто помните что код в формате ЧЧ.ЧЧ пишется. четыре цифры с точкой посередине. И вдогонку - все поля которые Вы знаете как заполнить - обязательные.
С уважением, Август.

**Comment by ConstantineCher** [comment]
Понял, спасибо!
Уже все сделал в оффлайне.

20 июля 2016 г., 19:31 пользователь agerman-ua <notifications@github.com>
написал:
