### ISSUE TITLE
заявка № 0-289154768 в обработке 20 дней ( Реєстрація місця проживання/перебування особи)

### ISSUE THREAD

**Issue by Polietaiev** [e-government-ua/iForum#513]
Звернення № 0-289154768
01.06.2016
В обробці
Київська ДМС - Реєстрація місця проживання/перебування особи
Заявка подана - Формування пакету документів для ДМС

На почту приходило сообщение что я не явился в нужный срок. Но куда и когда я должен был явиться непонятно, при этом статус самой заявки на сайте не меняется.

**Comment by annastolbova** [comment]
м. Київ на даний момент не співпрацює вже по цих послугах
