### ISSUE TITLE
какими законами регулируется деятельность iGov ?

### ISSUE THREAD

**Issue by ArtemOstapiuk** [e-government-ua/iForum#514]
Добрый день, 
Какими НПА регулируется деятельность вашей платформы  iGov ? В интернете я смог найти только информацию о том, что для сотрудничества с местными властями, волонтеры iGov подписывают меморандумы. Но меморандум о сотрудничестве с Киевом, найти не могу.
Меня интересует вся информация о законодательном регулировании деятельности iGov. 
Прошу прислать ответ на paralegal@glagos.com.ua или artem.ostapiuk@gmail.com.
Спасибо.

**Comment by AndreyPopovNew** [comment]
нет никакой регуляторной базы.

это волонтерский проект, и к сожалению нет НИКАКИХ рычагов для воздействия на гос.органы власти, кроме "доброй воли" этих органов власти :(
