### ISSUE TITLE
Прошу удалить заявку 0-323016683 о регистрации ФОП.

### ISSUE THREAD

**Issue by Anakalivto** [e-government-ua/iForum#515]
Добрый день.

Прошу удалить заявку 0-323016683 о регистрации ФОП.
Не дождался и сам сходил в администрацию...
Там 2 разных чиновника сказали что ничего не слышали об онлайн заявках... 

Прошу подтвердить удаление онлайн заявки.

Спасибо.

**Comment by agerman-ua** [comment]
Добрый день, @Anakalivto 
Простите за задержку.
Было закрыто ещё 22.06, Вам было сразу отправлено письмо.
С уважением, Август.
