### ISSUE TITLE
заявка 0-311985909, две недели жду, в ответ тишина...

### ISSUE THREAD

**Issue by 0672901026** [e-government-ua/iForum#516]
прошу Вас, на какой стадии регистрация?
будет ли она?

**Comment by 0672901026** [comment]
заявка на регистрацию ФОП с ЕСВ, Киев.

**Comment by agerman-ua** [comment]
@0672901026
Добрый день, Ваше обращение в работе у госслужащего.
Более точный статус сегодня не получится дать.
Завтра уточним.
С уважением, Август.

**Comment by 0672901026** [comment]
спасибо за ответ. надеюсь, сламаем корупцию в стране. :)

**Comment by 0672901026** [comment]
Причина:некоректно введено назву міста та номер будинку в адресі.

Це такий жарт? Реєстратору повилазило? Що роботи? Відкривати нову заявку?

**Comment by agerman-ua** [comment]
@0672901026 
:( Похоже что не шутка.
После закрытия госслужащим "реанимировать" заявку невозможно.
Прошу повторно подать. 
Сейчас мы взаимодействуем с госорганами в налаживании процесса с более качественной обработкой обращений  - надеюсь ситуация не повторится.
С уважением, Август.

**Comment by agerman-ua** [comment]
Добрый день, @0672901026 
Закрываю вашу тему, если есть вопросы - откройте либо новую или заново откройте эту.
С уважением, Август.
