### ISSUE TITLE
При залогинивании от карты Привата - ошибка

### ISSUE THREAD

**Issue by SashaRIS** [e-government-ua/iForum#518]
![21-06-2016 15-32-13](https://cloud.githubusercontent.com/assets/20066925/16229726/b398dea8-37c6-11e6-919f-5e4496ec04e1.png)

При залогинивании от карты Привата - ошибка.
На этапе заказа "формы 3", когда я выбираю область и город (Киев, Киев) - ничего не происходит. Как мне тогда заказать форму 3?

**Comment by AndreyPopovNew** [comment]
скорее всего форма не доступна для Киева.

она доступна только в нескольких пилотных областях в нескольких городах.

**Comment by Koffeek** [comment]
@SashaRIS Услуга по выдаче Формы 3 недоступна для г. Киев.
