### ISSUE TITLE
Звернення №0-538019605 (Державна реєстрація створення юридичної особи).

### ISSUE THREAD

**Issue by gralexiv** [e-government-ua/iForum#519]
Добрый день!

По заявке №0-319745471 в регистрации отказано.
Теперь подробнее:
Я получил ответ:

>    Шановний(-а),
>
>    Ваше звернення №0-319745471 на тему "Державна реєстрація створення юридичної особи", >опрацьовано і по ньому винесено рішення про відмову в реєстрації.
>
 >   Коментар держслужбовця (Причина: не доданий установчий документ)

Мои действия при заполнении заявки

- В регистрационной форме заполнены все поля,
- выбран модельный устав,
- не плательщик НДС и ЕН
-  далее нажимаем на волшебную кнопку "замовити послугу", далее подпись и все: "заявка в обробці". Больше там ничего сделать было нельзя. Где собственно нужно было загрузить "установчий документ" ?

То есть, сделано все как в инструкции "Як працює", в которой тоже ничего не упоминается о загрузке документов (только заявы для налоговой).

Так как я хочу, чтобы этот проект заработал и время мне позволяет, то я принципиально хочу, чтобы мое ТОВ было зарегистрировано через iGov
Если у Вас такое же желание, тогда я думаю, нам совместно нужно понять, где, что не так сработало.
Перед тем как я подам заявку следующий раз, я хочу понять, в чем причина отказов мне:
1. Это был необоснованный отказ?
2. Если был выбран модельный устав, может все-таки необходимо что-то еще загрузить (например, протокол собрания учредителей)? Тогда необходимо указать явно поле, куда этот документ нужно загрузить в случае, если выбран модельный устав или откорректировать инструкцию, если скан протокола загружается уже после подачи заявки. (для этого случая неплохо бы еще шаблон протокола иметь)
3. Может быть модельный устав не принимается и нужно обязательно делать свой устав и загружать скан? Тогда нужно об это явно сказать.
4. Что-то еще? Давайте определим вместе

Надеюсь на плодотворное сотрудничество и ответы. Спасибо!

**Comment by agerman-ua** [comment]
Добрый день, @gralexiv 
Очень прошу простить за задержку с ответом.
Характер ответа, к сожалению, достаточно частый для этого периода.
Вы всё правильно сделали. Просто госслужащий так интерпретировал отсутствие файла. Хотя мог и перезвонить и с помощью портала задать уточняющий вопрос.
Сейчас такие случаи очень редки, и если вопрос ещё актуален - можно подавать новую заявку на регистрацию.
Спасибо за поддержку нашего проекта.
С искренним уважением, Август.

**Comment by gralexiv** [comment]
Добрый день!
Спасибо за ответ. Еще актуально. 
Через некоторое время попробую еще раз.
По результату отпишусь в эту ветку.

**Comment by agerman-ua** [comment]
@gralexiv 
Хорошо. Тогда переименуйте её потом под новый номер обращения.
С уважением, Август.

**Comment by gralexiv** [comment]
Добрый день!

Разместил новое обращение по тому же поводу 0-538019605. Жду результат.

**Comment by agerman-ua** [comment]
Добрый день.
Принял.
С уважением, Август.

**Comment by agerman-ua** [comment]
Добрый день, @gralexiv 
30.08.2016 зарегистрировали - поздравляю.
Удачи.
С уважением, Август.

**Comment by gralexiv** [comment]
Спасибо! Вчера поздно ночью увидел. 
Уведомления на е-майл не было. Хорошо, что в журнале хранится копия.
Удачи проекту!

**Comment by agerman-ua** [comment]
Спасибо. Вот для таких случаев и делали. :)
