### ISSUE TITLE
Назначение помощи при рождении ребенка !! НЕТ ОТВЕТА!!

### ISSUE THREAD

**Issue by maks2617** [e-government-ua/iForum#52]
Заявка 9144945
Днепропетровск - АНД район 
нет ответа 
заявка подана и всё 
Помогите пожалуйста

**Comment by maks2617** [comment]
Мне кто то ответить ? Пожалуйста

**Comment by dmitrijzabrudskij** [comment]
жду район. как только будет ответ - напишу

**Comment by maks2617** [comment]
Спасибо жду

**Comment by annastolbova** [comment]
Заявка закрита 04.11.2015.
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
