### ISSUE TITLE
СОС!!! тут взагалі хтось отриав послугу?

### ISSUE THREAD

**Issue by optuma** [e-government-ua/iForum#520]
звернення № 0-302357659, як відкликати, втомилась чекати!

**Comment by olenmoisen** [comment]
https://www.facebook.com/dubilet/posts/10154308938668552?pnref=story

**Comment by optuma** [comment]
а как узнать на какой стадии моя заявка?

**Comment by olenmoisen** [comment]
Похоже, на той, что и моя

**Comment by zolotovatatyana** [comment]
Здравствуйте.
Есть две стадии: "Заявка подана" и "Заявка в работе". 

 Электронная стадия "В работе" включает в себя фактическую обработку документов сотрудниками ЦНАП, уточнение данных у заявителя (при необходимости), передачу сведений гос.регистратору,  фактически проведение регистрации, передачу сведений обратно в ЦНАП, и направление ответа Заявителю. Узнать, какой именно из этих этапов проходит Ваша заявка, пока висит со статусом " в работе" технической возможности нет.

 После этого "Заявка закрыта".

Мы, волонтеры iGov, можем видеть только электронную стадию заявки "В работе", и со своей стороны, можем только оказывать чиновникам помощь в освоении работы портала, чтоб не было задержек из-за технических вопросов, а также уговорами и убеждениями чиновников активнее работать ускорять прохождение дел. Этим мы, поверьте,занимаемся постоянно не жалея сил.

В своем посте, на который дана ссылка выше, Дмитрий Дубилет анонсировал изменения в прохождение процесса, которые, мы надеемся, значительно ускорят предоставление услуг.

**Comment by koi8** [comment]
>> уточнение данных у заявителя (при необходимости),
на самом деле они просто отказ сразу делают, ничего не уточняют.

**Comment by agerman-ua** [comment]
@koi8 
Добрый день,
Это не так. Конечно Ваш личный опыт может быть именно таким, но разные госслужащие используют предоставленный им инструмент по разному. Есть такие которые и перезванивают и пишут запросы на уточнение. Мы стараемся их выделить перед руководством. Чтобы мотивировать остальных. Процесс улучшений не моментальный. Но уверен - необратимый.
С уважением, Август.

**Comment by IvanMalovichko** [comment]
Сегодня заявку было закрыто с положительным результатом!

**Comment by optuma** [comment]
мої вітання!!! скільки тривав розгляд?

**Comment by IvanMalovichko** [comment]
Документы были поданы 15.06 (появился статус "документы принято"), 16.06 статус изменился на "в обработке", 23.06 - "заявка закрыта"

**Comment by optuma** [comment]
вам круто пощастило, моя заявка з 07.06 ще досі в обробці ((

**Comment by agerman-ua** [comment]
@optuma 
Добрый день, есть возможность отменить Вашу заявку - прошу просто подтвердить здесь.
С уважением, Август.

**Comment by optuma** [comment]
а сколько потом еще подтверждения ждать об отмене?

**Comment by agerman-ua** [comment]
@optuma 
Именно эта операция будет проведена быстро.
Подтверждаете отмену?
С уважением, Август.

**Comment by kavunchik05** [comment]
Додавали КВЕДи. Чекати довелося довго, але все вирішилось позитивно. Сподіваюсь, і у вас все буде добре!
