### ISSUE TITLE
Ошибка авторизации через bankid

### ISSUE THREAD

**Issue by pavolegv** [e-government-ua/iForum#521]
Добрый день!
Оформляю услугу для дочери 16 лет (паспорт обычный украинский есть), "Видача/заміна паспорта громадянина для виїзду за кордон", для входа в Приват24 вводим номер телефона и пароль, код из смс, дальше выдает ошибку.
![err](https://cloud.githubusercontent.com/assets/19302831/16294273/6192efa0-3928-11e6-8506-22b794ef5e99.png)

страница с ошибкой
https://igov.org.ua/auth/bankID/callback?link=https://igov.org.ua:443/service/177/general/place/built-in/region/1/city/0&code=giRF1M91530

У меня и супруги через Приват24 зарегистрировалась заявка без ошибки. В паспортном столе сказали, что дочери обычный загранпаспорт нужно делать, как для взрослых.
Подскажите, в чем причина, спасибо.

С уважением,
Павленко Олег.

**Comment by Koffeek** [comment]
@pavolegv На самом деле детский загранпаспорт он выдается гражданам до 16 лет по обращению родителей. Те, кто старше 16 обращаются лично, как взрослые. Если Вы подаете заявку от имени дочери, то необходимо убедиться, что в банке есть данные о ёё паспорте (это может блокировать передачу данных от банка на портал).

**Comment by pavolegv** [comment]
Спасибо большое, скорее всего в этом проблема, так как карточку Приватбанка, получила раньше чем свой паспорт.
