### ISSUE TITLE
держслужбовцю не видны поля формы при регистрации ФОП

### ISSUE THREAD

**Issue by koi8** [e-government-ua/iForum#522]
Получил ответ:

> Ваше звернення №0-314247627 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
> 
> Коментар держслужбовця (Причина: не заповнені обов'язкові поля: громадянство, адреса (Назва вулиці, проспекту, провулку тощо; Будинок ))
> 

Но при этом это все указано в заявке, прикладываю скриншоты! Какой-то саботаж.. Уже месяц пытаюсь ФОП сделать..

![wat1](https://cloud.githubusercontent.com/assets/2856182/16256509/3831c55a-385b-11e6-85ee-b6b6657193f2.png)
![wat2](https://cloud.githubusercontent.com/assets/2856182/16256511/3ca11d66-385b-11e6-99a3-fac20a327b3a.png)

**Comment by agerman-ua** [comment]
@koi8 
Это уже переработано полностью.
Ранее мы предлагали "преднабор" из БанкАйДи.
Теперь заявитель полностью сам вводит адрес. 
Поскольку из БанкАйДи тянутся часто на русском и когда люди не исправляют некоторые чиновники отказывают под этим предлогом.
В новых заявках такого нет. 
С уважением, Август.

**Comment by koi8** [comment]
Что мне теперь делать? Как видно по скриншотам - все данные и так введены руками и на украинском языке. Вы можете повторно открыть эту заявку?

**Comment by Maestra86** [comment]
я 5 раз перезаполняла заявки, каждую закрывали под предлогом, что то поля не заполнены, то на русском заполнены.
Сегодня подала заявку в 6-й раз.....................

**Comment by koi8** [comment]
Это моя 4-ая заявка. Уже нет времени делать пятую, т.к. полтора месяца не могу получить от работодателя денег. При таком саботаже со стороны чиновников теряется смысл всего проекта.

**Comment by koi8** [comment]
Я все понял, спасибо за ваше время. Пойду оформлять офлайново. Мою заявку в работу прошу не возвращать, если вдруг были такие планы.
