### ISSUE TITLE
Какой адрес где забирать справку о не судимости

### ISSUE THREAD

**Issue by Levchenko65** [e-government-ua/iForum#524]
Статус заявки закрытый! Где в Днепропетровске забирать справку о не судимости?

**Comment by kurbpa** [comment]
Благодарим, что воспользовались он-лайн сервисом.

Хотелось бы отметить следующее:
адрес  присутствует как на форме заказа заявки  
![1](https://cloud.githubusercontent.com/assets/11442397/16302382/816d9b74-3953-11e6-8443-32a30107331c.PNG)


так  и в емейле, где Вас оповещают о готовности справки
![2](https://cloud.githubusercontent.com/assets/11442397/16302404/9c7dd172-3953-11e6-8e56-cdacd3e43eed.PNG)
