### ISSUE TITLE
заявка 0-344673433 - неверно внесен номер квартиры

### ISSUE THREAD

**Issue by sshumov** [e-government-ua/iForum#525]
В реестр неверно внесен номер квартиры. В скане паспорта четко видно другой номер. Прощу исправить.

**Comment by agerman-ua** [comment]
Добрый день, @sshumov 
Простите за такую задержку с ответом.
Не могу сходу точно определить - проблема именно у Вас не устранена?
С уважением, Август.

**Comment by sshumov** [comment]
Добрый день.
Меня ж налоговая оштрафует за несовевременное уведомление ;)


На сайте минюста -
Місце проживання 40024, Сумська обл., місто Суми, ВУЛИЦЯ СКД, будинок 14,
квартира 14
что не является верным. должно быть будинок 14 квартира 81
при попытке посмотреть детали заявки так и вываливается:

Unexpected token s in JSON at position 0 (caused by "undefined")


Час: "2016-07-20T11:01:07.965Z"






20 июля 2016 г., 8:13 пользователь agerman-ua <notifications@github.com>
написал:

**Comment by agerman-ua** [comment]
Добрый день, @sshumov 
Во-первых отдельное спасибо за мягкое чувство юмора и спокойствие. :)
Так. Теперь по сообщению вижу два момента:
1. Проблема осталась
2. Не можете зайти в раздел "мой журнал" на нашем портале.
По п.1. постараюсь поднять файлы и понять кто герой?! Если регистратор то нужно будет ему формальное заявления для бесплатного внесения изменений в реестр по адресу. Это озвучу после разбора.
По п.2. скорее всего Вам нужно почистить кэш браузера. Но и в этом случае Вы много не увидите, текущий статус "закрыто" и вряд-ли что-то ещё новое. Но он работает точно.
С уважением, Август.

**Comment by sshumov** [comment]
Спасибо.

по п.1 - Тут очень скользкий вопрос. В заявке фигурирует фото страницы
паспорта с текущей пропиской. Получается - если я ошибся в полях ввода и
ввел неправильные данные - то регистратор "профукал" этот момент. а это
приводит к очень сложному вопросу - доверию регистратору.


по п.2 - Признаюсь я сам часто даю такой совет, но в данном случае это не
помогает. Возможно дело в использовании "не Windows" системы. Сегодня
попробую от другого пользователя с чистого окружения зайти.

PS. я без наездов. все мы люди все можем ошибаться.



20 июля 2016 г., 18:41 пользователь agerman-ua <notifications@github.com>
написал:
