### ISSUE TITLE
Люди добрые что тут происходит?!!!

### ISSUE THREAD

**Issue by NazarYuzvyshyn** [e-government-ua/iForum#526]
14,06 Ваша заявка 0-324336706 прийнята!
Спасибо огромное,но мне сколько еще ждать.....
Заявка даже не в обробке...Друг пошол ножками и на следующий день ети ножки несли уже ФОПа....
Мне может кто то обьяснить для чего етот ресурс....Наверное для матов которые держиш при себе

**Comment by agerman-ua** [comment]
@NazarYuzvyshyn 
Добрый день,
Сейчас уже не отвечу. Завтра постараюсь уточнить более детально что с Вашей заявкой.
Держать в себе плохое это конечно нехорошо, но мы Вам реально благодарны за сдержанность.
Цель ресурса предоставить прозрачный инструмент для получения услуг от органов власти не тратя время на походы к ним. Видимо немного органы сопротивляются новшествам.
Если Вам ну очень срочно нужно получить, пишите сюда о желании отозвать обращение, если есть возможность - мы инициируем её закрытие.
С уважением, Август.

**Comment by Propeller-SV** [comment]
Так и вижу: зашел как-то вечером в сарай Генри Форд с суперклеем, стеклорезом и разводным ключем и к утру выехал на новеньком мустанге.

Не все делается быстро, пока ножками можно быстрее. Но движение очень хорошее и правильное. И результаты есть. Мне для регистрации ФЛП понадобилось 11 дней. Не выходя из дома. В скором будущем, уверен, эти 11 дней превратятся в часы. А пока - вам решать, пользоваться или нет.

**Comment by agerman-ua** [comment]
Ооо. Очень приятно читать такие слова. 
Спасибо за понимание, за реальный кейс для сомневающихся и за то что разделяете наш оптимизм.
С уважением, Август.

**Comment by olenmoisen** [comment]
Еще один реальный кейс
Заявка с 13.06 (8 раб. дней) Сегодня - положительный результат, не выходя...

**Comment by NazarYuzvyshyn** [comment]
Я очень рад за людей которые получили своё законное в адекватные сроки.....
А я вот не получу зарплату 27.06 так как нет документов.....
Понимаю,что ето мои проблемы,но вы лучше укажите реальные средневзвешаные сроки получения документов,полный цикл процедуры,и пусть тогда человек решает

**Comment by sector612** [comment]
@Propeller-SV Прям все-все оформили за 11 дней удаленно? И свидетельство плательщика единого налога получили и книгу доходов? Фантастика, а можете набросать какой-то гайд с точки зрения практики? Меня зарегистрировали только с третьего раза (4 дня назад) и то до сих пор себя в реестре не нахожу.

**Comment by Propeller-SV** [comment]
@sector612 нет. 11 дней (календарных) это регистрация ФЛП с единым налогом через iGov. С 01.01.2014 [отменили](https://dou.ua/forums/topic/7175/) свидетельства плательщика единого налога. Вместо него Вы бесплатно получаете в органах Миндоходов (налоговой) вытяг с Реестра плательщиков единого налога. Но для чего он нужен? Я не получал. Так же как и книгу.
