### ISSUE TITLE
заявка  0-309901367

### ISSUE THREAD

**Issue by rmorkva** [e-government-ua/iForum#527]
Заявка  0-309901367, на зміну видів діяльності ФОП подана 09.06.2016. І більше жодної інфо. На якій стадії, розгляд заявки.

**Comment by agerman-ua** [comment]
Доброго дня, @rmorkva 
Послуга надана, закриваю Вашу гілку.
Якщо є питання - відкрийте або нову гілку форуму або цю наново.
З повагою, Август.
