### ISSUE TITLE
Необхідне уточнення данних - що це означає

### ISSUE THREAD

**Issue by kavunchik05** [e-government-ua/iForum#528]
По заявці на зміну кведів 0-315667128 прийшов лист, де просять уточнити дані. Конкретно написано "Необхідно уточнити дані, за коментарем: Реєстраційний номер справи *цифри-цифри-цифри-цифри* Код *цифри*" Що це означає? Що це за дані? Яким чином їх уточнити?

**Comment by kavunchik05** [comment]
Також в листі, що прийшов на e-mail зазначено "Щоб уточнити дані, Вам потрібно перейти в розділ "Мій журнал" порталу iGov і внести інформацію у відповідні поля." Але при переході жодних полів не відкривається.

**Comment by agerman-ua** [comment]
@kavunchik05 
Добрий день.
Не хвилюйтесь. Це держреєстратор намагається надати Вам інформацію для можливості зробити запит по наданій послузі.
Можете код використати для перевірки надання послуги. Якщо це вже виконана заява то скоро прийде і лист про це.
Перевірити можно на порталі мінюсту https://usr.minjust.gov.ua/ua/freesearch/ введіть отриманий код опису. Повинно спрацювати.
З повагою, Август.

**Comment by kavunchik05** [comment]
Ага, дуже дякую!
