### ISSUE TITLE
Заявка на регистрацию ФЛП № 0-341780017

### ISSUE THREAD

**Issue by keisi7** [e-government-ua/iForum#529]
Здравствуйте!
Сформировали уже  3-тью заявку на регистрацию ФЛП. Пожалуйста, не отклоняйте 0-341780017, все данные максимально внимательно заполнены.  Сколько еще ждать результат по заявке? взята в работу 22.06.

**Comment by keisi7** [comment]
Когда будет обработана заявка № 0-341780017 ?

**Comment by koi8** [comment]
Я месяц мучался, 4 заявки слито. Советую пойти и сделать в офлайне.

**Comment by keisi7** [comment]
Полтора месяца назад помогла зарегистрироваться знакомому через этот ресурс.
с 3-ей попытки, но на них уходило по 2 дня.
тоесть за неделю был Фопом.
А сейчас по 2 недели нет ответа и уже 2  отказа(

**Comment by keisi7** [comment]
Получилось! Регистрация прошла, выписку получили.
Огромное спасибо!!

**Comment by Maestra86** [comment]
а Вам для получения выписки код прислали в письме?

**Comment by keisi7** [comment]
код прислали, но он начал работать не раньше, чем через 6 часов.

**Comment by agerman-ua** [comment]
@keisi7 
Поздравляю.
Вот не могу никак понять у каждого по разному код начинает работать, у некоторых до недели доходит. Если не ошибаюсь тут даже не в регистраторе дело. Скорее всего это связано с налоговой. Буду проверять догадку.
Вам безусловно удачи.
И благодарю за доверие и настойчивость. 
С уважением, Август.
