### ISSUE TITLE
Субсидии. Заявка не отправляется, номер заявки не высвечивается

### ISSUE THREAD

**Issue by booratyna** [e-government-ua/iForum#53]
Днепропетровск, Бабушкинский р-н. Заявка оформлена, поля заполнены. Но при нажатии "Замовити послугу" ничего не происходит, заявка висит, номер не появляется. Что делать? Спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день
проверьте вводимые поля - там, где по смыслу должны стоять числа, их и нужно писать  - слова не пропустит (разделитель точка, на всякий случай). попробуйте еще раз и отпишитесь по результату, пожалуйста

**Comment by booratyna** [comment]
Здравствуйте! Все получилось, просто более тщательно подошли к заполнению полей, также сменили компьютер (если это имеет значение!). Если Вас интересуют замечания - то возникали некоторые сложности с заполнением данных относительно детей, в полях с  обязательным заполнением насчет места дохода и места работы (может, указать, что именно писать, если заполнение идет на ребенка?). СПАСИБО ЗА ВАШУ РАБОТУ, УДАЧИ!

**Comment by annastolbova** [comment]
Дякуємо за Вашу пропозицію, 
але після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
