### ISSUE TITLE
Регистрация ООО г. Харьков

### ISSUE THREAD

**Issue by Anirma** [e-government-ua/iForum#530]
Добрый день, подавала 2 заявки (  0-344625423 и 0-345479873) от 22 июня 1016, в первой указала новое название района, во второй старое название района. Подскажите когда будет результат?

**Comment by Anirma** [comment]
Добрый день, отзовите заявки ( 0-344625423 и 0-345479873), есть изменения при регистрации. Заранее благодарю.

**Comment by Anirma** [comment]
Добрый день, отзовите заявки от 22 июня, они все еще в обработке. 0-344625423 и 0-345479873

**Comment by agerman-ua** [comment]
@Anirma 
Добрый день,
Закрыли обе. Ждите писем. :)
С уважением, Август.

**Comment by Anirma** [comment]
Спасибо, письма пришли
