### ISSUE TITLE
Звернення 0-349273668: Реєстрація ФОП

### ISSUE THREAD

**Issue by eugenemarko** [e-government-ua/iForum#532]
Доброго дня!

Я зареєстрував звернення №0-349273668: Державна реєстрація створення фізичної особи – підприємця, м.Київ, Дарницький район, 23.06.16.
Сьогодні зранку я отримав листа про успішне виконання і закриття звернення. В пошуку usr.minjust.gov.ua я себе знайти можу, але там немає реєстраційних данних платника єдиного податку, хоча опція "Ви бажаєте обрати спрощену систему оподаткування?" і додано сканований файл з заявою на реєстрацію.

Підкажіть, будь-ласка, чи все правильно відпрацювало, ця інформація з'явиться пізніше?

**Comment by Propeller-SV** [comment]
Доброго дня. Мене зареєстрували 10.06, інформація щодо податкової з'явилася 13.06. Так що почекайте.

**Comment by eugenemarko** [comment]
Доброго дня, Сергію!

@Propeller-SV, дякую за інформацію. Дещо хвилює той факт, що окремо зареєструватись як платник єдиного податку я не можу - ця послуга недоступна. Хоча повний цикл реєстрації мій знайомий через igov пройшов, але він з Дніпра, а там ці процеси дещо краще заорганізовані.
@Propeller-SV, а Ви з якого міста, прошу пробачення за нескромність?

**Comment by Propeller-SV** [comment]
@eugenemarko зараз з Кременчука, прописка донецька. По ній і подавав заяву. Окремо в податковій можно зареєструватись оффлайново після реєстрації ФОП, якщо я вирно розумію.

**Comment by eugenemarko** [comment]
@Propeller-SV, ок, дякую

**Comment by eugenemarko** [comment]
Реєстраційні дані платника єдиного податку з'явилися сьогодні, на наступний день після закриття звернення.

**Comment by Propeller-SV** [comment]
@eugenemarko скажіть будь ласка, де ви перевіряєте цю інформацію? [Тут?](https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx) Я думав що воно не працює бо коли шукав себе то дуже швидко отримував негативну відповідь. Але перевірив дані приятеля і знайшов його.  Сподіваюся що просто ще не оновили базу(так мені сказали на гарячій ліній податкової), бо в "описі документів" від реєстратора моя заява на спрощену систему оподаткування є.

**Comment by eugenemarko** [comment]
@Propeller-SV, в цьому інтерфейсі https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jsp мене також поки що не знаходить.
На https://usr.minjust.gov.ua/ua/freesearch вчора поле "Дані про реєстраційний номер платника єдиного внеску, клас професійного ризику виробництва платника єдиного внеску за основним видом його економічної діяльності" було пустим, а сьогодні вже: "Дані про реєстраційний номер платника єдиного внеску: хххххххх"

**Comment by Propeller-SV** [comment]
@eugenemarko точно! дякую, все добре.
