### ISSUE TITLE
Видача/заміна паспорта громадянина для виїзду за кордон

### ISSUE THREAD

**Issue by nadinvin** [e-government-ua/iForum#535]
Когда заполняю форму на получение загранпаспорта, выбираю дату и время, но всплывает окно "Неможливо вибрати час. Спробуйте обрати інший або пізніше, будь ласка". Попробовала выбрать все предложенные даты и время, но результат не меняется. Позвонила в свой городской отдел ДМС (г. Днепродзержинск), говорят, что нужно записываться через сайт igov.org.ua либо стоять в живой очереди. Как же записаться через сайт, если форма не работает?! Стоять в очереди нет времени. 
Кто сталкивался с подобной проблемой? Как решить?

**Comment by Koffeek** [comment]
@nadinvin Добрый день. Подскажите, какую дату и время выбираете?

**Comment by nadinvin** [comment]
Меня интересует ближайшая возможная дата.
При первом заполнении была доступна 04/07, время не помню какое было. Когда она перестала быть доступной, ближайшей уже стала 12/07 и другие даты до конца месяца. Перепробовала все - не дает возможности выбрать время.

**Comment by Koffeek** [comment]
@nadinvin Попробуйте почистить кеш браузера и выбрать 05,07,2016, 9:45. У меня дата выбралась без ошибки

**Comment by nadinvin** [comment]
Получилось выбрать 05/07 время 10:00. Спасибо! :)
