### ISSUE TITLE
Реєстрація ФОП

### ISSUE THREAD

**Issue by anastasiia2016** [e-government-ua/iForum#536]
здравствуйте, посмотрите пожалуйста заявку № 0-344714125,  уже неделю в обработе, спасибо!

**Comment by agerman-ua** [comment]
Добрый вечер, @anastasiia2016 
Заявку закрыли 06.07.2016 с положительным результатом. Поздравляю.
Должно было прийти письмо.
Успехов на предпринимательском поприще.
С уважением, Август.
