### ISSUE TITLE
реєстрація ФОП

### ISSUE THREAD

**Issue by rushech** [e-government-ua/iForum#537]
заявка в обробці з 22.06.2016
Звернення № 0-345776145
м.Київ

**Comment by optuma** [comment]
моя ще з 07.06((( висить

**Comment by agerman-ua** [comment]
Добрий вечір, @rushech 
Вибачте за затримку з відповіддю.
Вам було відмовлено ще 04.07. Повинен був прийти лист з причиною.
Отримали?
З повагою, Август.
