### ISSUE TITLE
Когда будет реакция на обращение № 0-328614450 ???

### ISSUE THREAD

**Issue by IvanMalovichko** [e-government-ua/iForum#538]
Прошу отреагировать! https://github.com/e-government-ua/iForum/issues/506

**Comment by IvanMalovichko** [comment]
# **ТУТ ВООБЩЕ КТО-ТО ЕСТЬ???????? 
ЧТО ЗА БЕСПРЕДЕЛ?????????????????**

**Comment by agerman-ua** [comment]
Добрый вечер, @IvanMalovichko 
Отвечаю в #506, там детали про налоговую.
Тут только отмечу что Вас зарегистрировали :) и закрою ишью.
С уважением. Август.
