### ISSUE TITLE
не смог заявку подать на субсидию

### ISSUE THREAD

**Issue by kvaded** [e-government-ua/iForum#54]
не зміг заповнити і відправити заявку на субсидію через BankID Приватбанк. У мене сімья з 7 (семи) осіб, а електронна заявка через BankID дозволяє вибір (1-5 осіб і "ні") і не дозволяє ввести самому  6 чи більше осіб . при попитках ввести більше осіб, набір заявки, зник у невідомому напрямі

**Comment by dmitrijzabrudskij** [comment]
на данный момент максимум 6 человек возможно вписать в декларацию - Вы можете обратиться в Ваше управление соцзащиты для того, чтобы записать бОльшее число людей

**Comment by kvaded** [comment]
Когда будет расширена возможность вписывать любое число прописанных в доме человек в декларацию? В бланк декларации вписать больше трёх человек тоже невозможно.Обратился  сегодня в управление соцзащиты Самарского района г.Днепропетровска с вопросом  что делать?По телефону получен ответ-заполните на 7 человек 2-3 декларации.

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем
