### ISSUE TITLE
Реєстрація ФОП № 0-336694591

### ISSUE THREAD

**Issue by nkostiuk** [e-government-ua/iForum#540]
Доброго дня, можете будь ласка розглянути мою заявку № 0-336694591 (м. Київ), взята в роботе ще 19.06. Дуже треба! Дякую.

**Comment by agerman-ua** [comment]
Доброго дня, 
06.07.2016 заявка оброблена. Позитивно. Вітаємо. 
Вибачте що не дуже швидко вийшло. Зараз вже значно краще з цим.
