### ISSUE TITLE
СРОЧНО!!! Зарегистрировали ФОП по НЕСУЩЕСТВУЮЩЕМУ адресу!

### ISSUE THREAD

**Issue by alexeyshapka** [e-government-ua/iForum#541]
Добрый день!

Сегодня ПОЗВОНИЛИ ИЗ НАЛОГОВОЙ С ПРЕТЕНЗИЕЙ, что адреса моей регистрации НЕ СУЩЕСТВУЕТ!

Я подал заявку на регистрацию ФОП 13.06.16 (Звернення № 0-320607001). По данному обращению мне вынесли положительное решении о регистрации 1.07.16, чему я был очень рад.

НО...

Сегодня мне позвонили из налоговой и выяснилось, что меня зарегистрировали не в г. Харькове, а в смт. Шевченково (Харьковская область). При этом адреса, который я указывал по г. Харьков, естественно нету в смт. Шевченково.

В выписке адрес моей регистрации выглядит так:
"Місце проживання фізичної особи-підприємця:
61103, ХАРКІВСЬКА ОБЛ., ШЕВЧЕНКІВСЬКИЙ РАЙОН, ВУЛИЦЯ 23-ГО СЕРПНЯ, БУДИНОК ..."

Я действительно при регистрации указывал Шевченковский район, НО НЕ в графе "Найменування району в області:", а в графе: "Назва району в місті:".

На сайте регистрации это выглядит так:
![image](https://cloud.githubusercontent.com/assets/19610392/16539231/883256ae-4045-11e6-9944-d80266506b63.png)

Как видите, графа "Найменування району в області:" осталось пустым, при  этом я указал конкретно город Харьков.

Мой "Реєстраційний номер облікової картки платника податків та інших обов'язкових платежів":
3401409650

Скажите, как можно исправить адрес регистрации (СРОЧНО) и что требуется от меня?

**Comment by agerman-ua** [comment]
@alexeyshapka 
Добрый день,
Взяли "в работу". 
В понедельник, не раньше, будет более подробная информация.
Нужно будет разобраться как лучше поступить.
Но понадобится подать заявку на внесение изменений точно.
Спасибо за скрин. Это поможет.
С уважением, Август.

**Comment by alexeyshapka** [comment]
Спасибо за быстрый ответ!

**Comment by Maestra86** [comment]
подать заявку и заплатить 140 грн или сколько там за чужую ошибку? или бесплатно изменят?

**Comment by agerman-ua** [comment]
@Maestra86 Это будет бесплатно. Исправление ошибки регистратора.

**Comment by Maestra86** [comment]
@agerman-ua А можете, пожалуйста, ответить на мой вопрос https://github.com/e-government-ua/iForum/issues/543 ? Спасибо!

**Comment by agerman-ua** [comment]
@Maestra86 Ответил.

**Comment by agerman-ua** [comment]
@alexeyshapka 
Добрый день,
В личку Вам отправил файлик, прошу распечатать, проставить дату и свою подпись. Потом сфотографируйте или отсканируйте и верните обратно. Изменения должны появиться затем в течении дня.
С уважением, Август.

**Comment by alexeyshapka** [comment]
@agerman-ua 
Спасибо за оперативность! Сделаю в кротчайшее время!

**Comment by alexeyshapka** [comment]
@agerman-ua 

Отправил файлик (подписанный с датой) в ответе на Ваше письмо!

**Comment by agerman-ua** [comment]
@alexeyshapka 
Файлик у регистратора.
Ждём от неё подтверждения.

**Comment by agerman-ua** [comment]
@alexeyshapka 
Регистратор отработала.

**Comment by agerman-ua** [comment]
@alexeyshapka 
Прошу Вас дать обратную связь по результату.

**Comment by alexeyshapka** [comment]
@agerman-ua 
Скачал новую выписку, и проверил в "Єдиному державному реєстрі юридичних осіб, фізичних осіб-підприємців та громадських формувань". Ничего не изменилось. Вот скрин с выписки:
![image](https://cloud.githubusercontent.com/assets/19610392/16699920/b7f57f32-455f-11e6-99d8-364634df6cc6.png)

А вот скрин из "Єдиного державного реєстру юридичних осіб, фізичних осіб-підприємців та громадських формувань":
![image](https://cloud.githubusercontent.com/assets/19610392/16699967/f2f861d0-455f-11e6-8ba6-193a896a975c.png)
![image](https://cloud.githubusercontent.com/assets/19610392/16700004/38b6bd8e-4560-11e6-943f-680efebffac8.png)

По-прежнему Шевченковский район в Харьковской области! Без г. Харькова. Т.е. ничего не поменяли...

**Comment by alexeyshapka** [comment]
@agerman-ua

Так в выписке и в реестре что-то поменяют? Мне еще нужно заявление на единый налог подать до 1 августа, а адрес неправильный...

**Comment by agerman-ua** [comment]
@alexeyshapka 
Не понимаю в чём дело. Регистратор убедила что уже исправила. Как выясним - напишу.
С ув. Август.

**Comment by agerman-ua** [comment]
@alexeyshapka 
В реестре исправили. Проверьте.
Проблема в том что в реестре до сих пор старые районы городов. Это и сбило регистратора.
У Вас был Дзержинский вот в реестре он и остался. :(
Налоговая должна отработать в течении нескольких дней.
Но лучше убедиться потом лично.
С уважением, Август.

**Comment by alexeyshapka** [comment]
@agerman-ua

Добрый день. Проверил в реестре. "Місцезнаходження реєстраційної справи" поменялось. А "місцe проживання" eщe нe помeняли нe в выписке, не в реестре. Я так понимаю должны поменять скоро, да?

А что значит "Налоговая должна отработать в течении нескольких дней"? Меня зарегестрируют на единый налог? Там просто была проблема с датой, т.к. я указывал с 1 июня в заявлении на единый налог, а предпринимателем меня зарегистрировали только 1 июля (долго регистрировали), и сказали что только с 1 августа я могу быть на едином налоге. Или просто отправят мое дело в налоговую и нужно уже с той налоговой решать этот вопрос?

**Comment by alexeyshapka** [comment]
"Місцe проживання" так и не изменили не в выписке не в реестре ФОПов.

**Comment by agerman-ua** [comment]
@alexeyshapka 
"...Или просто отправят мое дело в налоговую и нужно уже с той налоговой решать этот вопрос?..."
Вот этот вариант более жизнеспоспособен.
По "местожительству" повторно обращу внимание регистратора. Но уже только в понедельник.
С ув. Август.

**Comment by alexeyshapka** [comment]
@agerman-ua 

Спасибо!

**Comment by alexeyshapka** [comment]
@agerman-ua 
Добрый день! Местожительство все еще не изменили.
![image](https://cloud.githubusercontent.com/assets/19610392/17015272/e8038378-4f31-11e6-8a29-984fa2c4b822.png)

**Comment by agerman-ua** [comment]
Добрый день, @alexeyshapka 
Через пару часов проверьте. 
Регистратор просто не знал как быть с новым названием района в городе и ждала изменений в программе. А мы с Вами ждали когда она изменит. :)
В реестре сейчас можно выбрать только старый (коммунистический) район.
Думаю Вы не будете возражать против такого развития событий.
Кстати смена этого района сейчас не обязательна, если будут заставлять то должна быть бесплатной. Иначе услуга была бы платная.
Буду рад обратной связи.
С уважением, Август.

**Comment by alexeyshapka** [comment]
@agerman-ua 
В реестре поменяли!) А вот в выписке пока нет: 
![image](https://cloud.githubusercontent.com/assets/19610392/17023738/856d9524-4f5d-11e6-9d70-40bb3f15301a.png)

**Comment by agerman-ua** [comment]
@alexeyshapka 
Это пока норм.
Там день-два кажется должно пройти (там с налоговой ещё как-то связано).
Держи на контроле.
С уважением Август.

**Comment by alexeyshapka** [comment]
@agerman-ua 
Ок, спасибо! Буду следить. Спасибо!

**Comment by alexeyshapka** [comment]
@agerman-ua
Адрес в выписке так и не поменяли...

**Comment by agerman-ua** [comment]
@alexeyshapka 
Понял, уточню.

**Comment by agerman-ua** [comment]
Добрый день, @alexeyshapka 
А сейчас проверьте, пожалуйста.
Должен быть адрес с городом.
С ув.Август.

**Comment by alexeyshapka** [comment]
@agerman-ua 
Адрес все еще без города.
![image](https://cloud.githubusercontent.com/assets/19610392/17429185/fae47cc0-5af5-11e6-80c6-850bc9210ddc.png)

**Comment by agerman-ua** [comment]
@alexeyshapka 
Місце проживання	
61103, Харківська обл., місто Харків, ВУЛИЦЯ 23-ГО СЕРПНЯ, будинок 63, квартира 72
Это данные из реестра.
А выписка откуда берётся? Расскажи как получаешь?

**Comment by alexeyshapka** [comment]
@agerman-ua
Захожу на сайт https://usr.minjust.gov.ua/ua/freesearch,
В списке:
-Фізична особа-підприємець
-Юридична особа
 -Результат надання адміністративних послуг
выбираю ""

**Comment by alexeyshapka** [comment]
@agerman-ua

![222830762_116995-001](https://cloud.githubusercontent.com/assets/19610392/17434865/9aa3a4e2-5b15-11e6-9cf2-1c9606713bcc.jpg)

**Comment by agerman-ua** [comment]
@alexeyshapka 
Теперь понятно. Передам (уже в понедельник) регистратору а то она уже не понимает что мы от неё хотим. :)
Хороших выходных.
С ув.Август.

**Comment by alexeyshapka** [comment]
@agerman-ua 
Добрый день! В выписке по-прежнему неправильный адрес. Что говорит регистратор, когда адрес будет изменен на правильный (с городом Харьков)?

**Comment by agerman-ua** [comment]
Добрый день, @alexeyshapka 
Регистратор не может заменить уже приложенный файл. Мы договорились что она отсканирует правильный (бумажный) который находится в Вашем деле и я его Вам сразу перешлю  Надеюсь это окончательно закроет Ваш вопрос.
С уважением, Август.

**Comment by agerman-ua** [comment]
Добрый день, Алексей.
Отправил Вам файлы "от регистратора".
Если что - пишите. Тему закрываю.
С уважением, Август.
