### ISSUE TITLE
!!! звернення № 0-302357659 хочу відкликати, місяць чекаю без результату !!!!

### ISSUE THREAD

**Issue by optuma** [e-government-ua/iForum#542]

**Comment by agerman-ua** [comment]
@optuma 
Добрий день,
Отримано підтвердження про можливість закриття Вашого звернення.
Вибачте за незручності та загальну затримку.
Чекайте на лист. 
Він повинен надійти сьогодні Вам в пошту та у "Ваш журнал" на порталі.
З повагою, Август.
