### ISSUE TITLE
получила письмо с положительным решением по заявке №0-290175958, но без кода

### ISSUE THREAD

**Issue by Maestra86** [e-government-ua/iForum#543]
где искать код, чтобы получить выписку из ЕДР?
спасибо!

**Comment by Propeller-SV** [comment]
@Maestra86 Добрый день. [Здесь](https://usr.minjust.gov.ua/ua/freesearch) можете проверить (бесплатно) по ИНН или паспортным данным. [Здесь](https://usr.minjust.gov.ua/ua/extractedr) заказать и получить документ по тем же данным (50 гривен).

**Comment by Maestra86** [comment]
спасибо большое!
всё верно, но меня интересует вопрос, можно ли каким-то образом получить код?
администраторы Системы его видят?

**Comment by Propeller-SV** [comment]
Если вы имеете ввиду код из "Опису документів" от регистратора, то он должен был прийти в письме с положительным решением по заявке. Но вот мой код, например, похоже бесполезен. По первой ссылке из предыдущего моего сообщения при выборе "Результат надання адміністративних послуг" и вводе этого кода я вижу лишь ФИО, дату регистрации и "Документи: Відомості відсутні."

**Comment by optuma** [comment]
когда заяву создавали? сколько была в обработке?

**Comment by Propeller-SV** [comment]
@optuma если вопрос ко мне, то 30.05.16 создана, 10.06.16 - положительное решение.

**Comment by Maestra86** [comment]
**@Propeller-SV** , когда я для мужа подавала заявку на изменение регистрационных данных, то мне пришел вполне рабочий код. по этому коду выписку можно получать сколько угодно раз и бесплатно - вдруг потерял или ещё что. потому и спрашиваю админов, как можно этот код получить. насколько я понимаю, этот код генерируется каждый раз при предоставлении услугу, значит, где-то он таки есть.

**Comment by agerman-ua** [comment]
@Maestra86 
Этот номер не генерируется внутри портала.
Его вносят (или не вносят) госслужащие. И - да, иногда достаточно долго нет ничего в графе "Документы". Это от нас не зависит.
