### ISSUE TITLE
Добрый день! Можно ли подать заявку на получение загранпаспорта в ДМС не по месту прописки, а где есть удобные даты подачи?

### ISSUE THREAD

**Issue by ANDRIINAZ** [e-government-ua/iForum#544]

**Comment by Koffeek** [comment]
@ANDRIINAZ услуга экстерриториальна и не зависит от места регистрации

**Comment by ANDRIINAZ** [comment]
Провеврил - так и есть. Заявление приняли без всяких вопросов. Всем спасибо за ответы
