### ISSUE TITLE
Реєстрація створення фізичної особи – підприємця: Звернення № 0-315805421

### ISSUE THREAD

**Issue by vsgdp** [e-government-ua/iForum#545]
Добридень! Звернення № **0-315805421** с **10.06.2016** В обробці: Державна реєстрація створення фізичної особи – підприємця  - Заявка подана - Надання послуги.
Є сенс чекати або краще по-старому? Ідея igov.org.ua хороша, але знову виконання підводить.
З найкращими побажаннями, Артур (м. Дніпро)

**Comment by vsgdp** [comment]
Доброго Вам дня! Прошу откликнуться компетентных в моём вопросе людей: на моё письмо на данном форуме #545 - никакой реакции, просто обидно. Через 2 дня будет календарный месяц как я подал заявку 0-315805421 на регистрацию ФОП. Полное неведение действий, или регистрация ФОП, или обоснованный отказ. Первый вариант меня больше устраивает, много времени потрачено.
С наилучшими пожеланиями, Артур (г. Днепр)

**Comment by agerman-ua** [comment]
Добрий вечір @vsgdp .
Приносимо вибачення за таку велику затримку з відповіддю.
Ваша заявка була оброблена і Вам було направлено 11.07 листа з мотивованою відмовою.
На жаль Ви попали в группу з декількох людей, які чекали обробки так довго.
Зараз вже немає звернень з таким терміном очікування, всі нові звернення обробляються в термін до одного тижня, і ми продовжуємо співпрацювати з держустановами над скороченням цього терміну до максимум двох робочих днів після подання.
Ви можете повторно подати звернення, впевнений стільки часу вже не пройде. Звісно якщо Вам це ще актуально.
У будь-якому випадку дякуємо Вам за довіру та бажання змінити нашу країну на краще.
З повагою, Август.
