### ISSUE TITLE
    Звернення № 0-354596292  27.06.2016 В обробці Державна реєстрація змін до відомостей про фізичну особу – підприємця

### ISSUE THREAD

**Issue by sauveteur** [e-government-ua/iForum#546]
Доброго дня! З момента подання заявки пройшов тиждень, хоча за правилами зміна відомостей проводиться в день подання заяви. Хотілося би зрозуміти, скільки ще очікувати реакції, позаяк від цього залежить багато планів. Можливо, краще подати заяву до ЦНАП, але тоді яка процедура відкликання заяви тут?
З повагою, Юрій.

**Comment by sauveteur** [comment]
Зміни до реєстру сьогодні внесено, дякую!

**Comment by agerman-ua** [comment]
Радий за Вас.
Успіхів.
З повагою, Август.
