### ISSUE TITLE
Сколько дней нужно??

### ISSUE THREAD

**Issue by LisRaP** [e-government-ua/iForum#547]
Вітаємо, РАЇСА, Ваша заявка 0-358235227 прийнята!

це було 29го червня. Вказано було, що реєстрація Юрособи займає 4 дні. Воно точно так?

Скільки чекати реально?

**Comment by agerman-ua** [comment]
Добрий вечір, Раїсо ( @LisRaP )
Вам було відмовлено, написав про це в листі до Вас ще 15.07.
Якщо ще залишаться питання - прошу задавати. 
Тут або в пошту, як Вам зручніше.
З повагою, Август.

**Comment by LisRaP** [comment]
Так, було таке, на github.com писали давно. Нову заяву надіслали, чекаємо знов.

19.07.2016 23:45, agerman-ua <notifications@github.com>
>Добрий вечір, Раїсо ( @LisRaP )
> Вам було відмовлено, написав про це в листі до Вас ще 15.07.
> Якщо ще залишаться питання - прошу задавати. 
> Тут або в пошту, як Вам зручніше.
> З повагою, Август.
> 
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/e-government-ua/iForum/issues/547#issuecomment-233759919


-- реклама -----------------------------------------------------------
ЖК «Нова Англія» - обери свою додаткову знижку до 11%!
http://h.holder.com.ua/c?tz&z1585&b121206&s03908&r[rndID]&u

**Comment by agerman-ua** [comment]
Добрий день, Раїсо ( @LisRaP )
Добре, зараз юрособи в середньому десь за тиждень-півтори реєструються.
Дякую за віру в нас.
З повагою, Август.

**Comment by agerman-ua** [comment]
Доброго дня.
Якщо будуть ще питання пишіть в нову тему, цю закриваю.
З повагою, Август.
