### ISSUE TITLE
Звернення № 0-301766173 вже місяць в обробці

### ISSUE THREAD

**Issue by OlegYu** [e-government-ua/iForum#548]
Звернення № 0-301766173 вже місяць в обробці. Прокоментуйте цю ситуацію.

Якщо ви не плануєте обробляти заявку то так і напишіть: не можемо / не хочемо / послуга фіктивна і заявки реально не обробляюьться.

І ще один момент: в статистиці послуги неправильно розраховується таймінг.
Враховуючи те що дві мої попередні заявки оброблялися 4 і 11 днів, нінішня заявка 30 днів (і ще в обробці) і заявки іших громадян також обробляються довго (судячи зі звернень на форумі) то середній таймінг 4 дні, 21 година, 35 хвилин нереальний.

І ще одна пропозиція: в статистиці відображати кількість поданих заявок і кількість заявок що успішно завершилися, а також показувати реальний таймінг. Тоді громадянам буде простіше приймати рішення про користування порталом.

**Comment by agerman-ua** [comment]
@OlegYu 
Добрий вечір.
Нда. Добрався до Ваших перших звернень. 
Вибачте що відразу не зміг відповісти. Причини не важливі, просто вибачаюсь.
Маю надію що Ви отримали мого листа 15.07 щодо останньої відомої мені "екзотичної" відмови Вам.
Не знаю як в інших випадках по життю у Вас виходить, але Ви дійсно отримали всі можливі варіанти відмов які тільки траплялися та ще й від різних держслужбовців.
Можу тільки сказати, що зараз ми з Вашою допомогою та допомогою інших волонтерів змогли виділити працьовитих та старанних держслужбовців від інших. Перших стараємось мотивувати - других або обмежуємо або щільно інструктуємо.
У будь-якому випадку, зараз обробка не займає більше тижня.
Щодо статистики - вона правильно вираховується просто з часом та більшою кількістю наданих послуг буде краще відповідати дійсності.
З повагою, Август.

**Comment by OlegYu** [comment]
19.07.2016 23:41, agerman-ua пишет:
>
> @OlegYu <https://github.com/OlegYu>
> Добрий вечір.
> Нда. Добрався до Ваших перших звернень.
> Вибачте що відразу не зміг відповісти. Причини не важливі, просто 
> вибачаюсь.
> Маю надію що Ви отримали мого листа 15.07 щодо останньої відомої мені 
> "екзотичної" відмови Вам.
>
15.07 Від вас листів не було. В спамі теж перевіряв.

**Comment by agerman-ua** [comment]
Дивно, Начебто саме 15 липня 2016 р. о 14:11 повинен був прийти лист.
Ну це вже не важливо.
Щасти Вам у підприємництві.
З повагою, Август.
