### ISSUE TITLE
Вопрос по заявке 0-373182054 (Услуга - Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця))

### ISSUE THREAD

**Issue by pvovlos** [e-government-ua/iForum#549]
" Якщо раптом Вам буде відмовлено у заявці, Вам пояснять причини. "
В заявке отказано, причины не оглашены. Как это понимать?

**Comment by Koffeek** [comment]
@pvovlos Добрый день. Подскажите какую услугу заказывали, а также по возможности подразделение, в которое обращались? Спасибо.

**Comment by pvovlos** [comment]
Добрый день.
Услуга - Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця) Органи місцевого самоврядування
Формы заполнял - тут https://igov.org.ua/service/29/general

**Comment by Koffeek** [comment]
@pvovlos Какой город и, при наличии, район?

**Comment by pvovlos** [comment]
Днепр, Самарский район

**Comment by pvovlos** [comment]
И как там? Ответов нет, или ждем таки?

**Comment by Koffeek** [comment]
@pvovlos Как мне сказали, Вы не добавили основание для регистрации и документы по военно обязанному. Попробуйте переподать заявку ещё раз.

**Comment by pvovlos** [comment]
договор дарения был прикреплен. а по поводу военного то в приписном отметка что снят с учета по приказу такому-то. не проблем, я так понял скинуть скан приписного

**Comment by pvovlos** [comment]
все обработали. ждут в указанное время

**Comment by Koffeek** [comment]
@pvovlos Вот и хорошо. Если не сложно, отпишитесь потом как всё прошло. Спасибо.

**Comment by pvovlos** [comment]
Вчера сходил. Появилось 2 важных ньюанса.
1. Квитанцию об оплате пошлины потребовали исключительно с мокрой печатью банка. Никакие распечатки с приват24 не котируются. Т.е. обязательно необходимо посещение кассы банка.
2. С военкомата сняли с учета в 2007 году по приказу. При регистрации в другом районе по новому места жительства при посещении военкомата никаких отметок не ставили. В итоге вчера заставили идти в военкомат ставать на учет.
1й пункт актуален, стоит гдето Вам добавить в инструкцию. 2й - чисто информативный

**Comment by Koffeek** [comment]
@pvovlos Спасибо за отзыв. По мокрой печати, ДМС их требовало, но после передачи на места стало попроще. Добавим. По военкомату, тут в каждом районе/городе своя специфика взаимодействия с военкомами и тяжело сделать универсальную инструкцию.

**Comment by pvovlos** [comment]
В итоге, специалист по регистрации держит мою заявку, я в понедельник бегу в военком а потом обратно к спецу. Радует что там написан график работы и отдельно вынесена инфа, что по заявкам с iGov прием 16,00-18,00

**Comment by Koffeek** [comment]
@pvovlos Мы вчера значит Вашу ситуацию обсуждали. Без согласования отдельного графика мы услугу не могли запустить полтора месяца.
