### ISSUE TITLE
Отказ в регистрации плательщиком единого налога.

### ISSUE THREAD

**Issue by Propeller-SV** [e-government-ua/iForum#550]
Хочу поделиться своей историей, может кому-то это поможет избежать неприятностей.
30.05.16 я подал через iGov заявку на регистрацию ФЛП с прикрепленным заявлением на единый налог (в электронном виде с ЭЦП). 10.06.16 я получил от регистратора положительный ответ. Через пару дней я увидел себя в реестре ФЛП [здесь](https://usr.minjust.gov.ua/ua/freesearch). Однако в реестре плательщиков единого налога [здесь](https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx) себя НЕ находил. Позвонил на горячую линию налоговой. где мне сказали, что раз отказа из налоговой не было, значит все нормально, просто сервис проверки работает в тестовом режиме. Однако я все же решил задать вопрос своей налоговой (Мариуполь) по почте, отправил письмо 30.06.16. И вот 05.07.16 мне позвонили из налоговой и сообщили, что дата в моем заявлении на единый налог была РАНЕЕ даты моей регистрации ФЛП (спасибо тебе, регистратор!), и поэтому в регистрации единщиком мне отказано. И сообщают они мне об этом вот таким образом, после моего обращения, спустя почти месяц. Таким образом я теперь должен платить налог на общих основаниях этот квартал, и перейти на единый смогу только со следующего. Есть ли более подходящее слово для этого, чем издевательство?

**Comment by IvanMalovichko** [comment]
У нас ситуация один в один.
Оставили жалобу на "пульсе" налоговой (044) 284-00-07, обещают ответ через 3 дня
Налоговая обязана была уведомить плательщика об отказе, но этого не сделала.

**Comment by Propeller-SV** [comment]
@IvanMalovichko Так. Спасибо за наводку. Оказывается налоговая согласно пункта 299.5 налогового кодекса обязана была меня уведомить об отказе в течение 2 дней. Теперь нужно подавать письменную жалобу в свою налоговую.

**Comment by agerman-ua** [comment]
@Propeller-SV 
Добрый день. 
Очень и очень досадно констатировать такой случай. :(
Мы в ближайшей версии услуги добавим комментарий на загрузку файлов с заявлениями эту информацию. Чтобы повторно не попадали люди в подобную неприятную и неожиданную ситуацию.

@IvanMalovichko 
Спасибо что поделились информацией. 
Тоже подумаем, как добавить сразу в услугу для использования людьми.

С уважением, Август.

**Comment by IvanMalovichko** [comment]
Как вариант - указать, что в заявлении на единый налог ни в коем случае НЕ УКАЗЫВАТЬ с какой даты поставить на учет плательщоком единого налога!!! Оставлять это поле пустым!!! Возможно, в этом случае проблемы не будет.

**Comment by Propeller-SV** [comment]
Дозвонился в мариупольскую налоговую. Там сказали, что сделать уже ничего нельзя, можете жаловаться хоть Президенту. Не уведомили, потому что "вы думаете вы один такой", "просто не успели", "когда смогли - тогда и уведомили" (спустя месяц, после персонального обращения).

@IvanMalovichko что вы собираетесь делать? Держите в курсе результатов в связи с жалобой, пожалуйста.

**Comment by Propeller-SV** [comment]
Так, похоже наша группа растёт. Невесело это... И что-то мне подсказывает, что еще не раз зарегистрировавшиеся через портал предприниматели внезапно обнаружат эту проблему.

@agerman-ua скажите пожалуйста, нет ли среди руководства iGov компетентных в этих вопросах людей? Или способных донести эту проблему до вышестоящих чиновников ДФС? 45% налога вместо 5% это ведь не шутки!

**Comment by Maestra86** [comment]
в общем, позвонила я в "пульс" налоговой (044) 284-00-07, там мне дали номер 0 800 501 007 - дальше нажимаете 5 - и рассказываете оператору свою ситуацию.

мне ответили, что при отказе, налоговая в течении 2-х дней должна предоставить заявителю ПИСЬМЕННЫЙ ответ по почте, укрпочтой.
если этого не произошло - надо идти к начальнику налоговой, в которую подавалось заявление, и писать скаргу.

далі буде...

**Comment by agerman-ua** [comment]
@IvanMalovichko 
Как-то так и будет, хотя смущает фраза "возможно ... проблем не будет". Но на текущий момент это пока единственный вариант уменьшить шанс наличия проблем практически на пустом месте.
С уважением, Август.
P.S. Присоединяюсь к @Propeller-SV - держите нас в курсе событий по жалобе.

**Comment by anna-libra** [comment]
@agerman-ua  подскажите, как поступить - подавала заявку № 0-376305505 на создание ФОП 5.07.2016 и заявление на единый налог. Так как нет никаких инструкций касательно даты, которую нужно вписывать в заявление на единый налог, я вписала дату подачу заявки 05.07, и теперь понимаю, что налоговая скорее всего меня не зарегистрирует, и не уведомит об этом. 
Что сделать, переподписать заявку на единый налог и прикрепить к заявке? Если да, то какую дату вставлять? 
Второй вопрос - мне нужна срочно регистрация, я так понимаю, вы мне не сможете сказать сроки рассмотрения. Если я пойду на след.неделе регистрироваться офлайн, что делать с заявкой на igov.ua, отменять ее посредством данного форума?

**Comment by Propeller-SV** [comment]
Отправляю жалобу в свою налоговую и киевский офис ценным письмом с описью вложения. Возможно кому-то будет полезен образец - вот он.
[Example.zip](https://github.com/e-government-ua/iForum/files/354027/Example.zip)
Возможно кто-то может подсказать как отправить в электронном виде так, чтобы жалоба имела вес наравне с бумажной?

**Comment by Maestra86** [comment]
@anna-libra вбейте свои ИНН здесь https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx;CABINET=t-LKPTDUUbU-PAMPgPrmDpdJB9I9bzjO2QDrkQTXbTfiWRgzbAt1!1575935461 - если покажет Ваши данные, значит есть

**Comment by agerman-ua** [comment]
@anna-libra 
Поздравляю, Вас уже зарегистрировали. 
Но лучше убедиться что с постановкой на учет в налоговой нет проблем.
С уважением, Август.

**Comment by anna-libra** [comment]
Спасибо @Maestra86 . В онлайн реестре себя нашла только как зарегистрированный налогоплательщик, но в реестре единого налога меня нет :(. 
@agerman-ua Можно ли все-таки онлайн зарегистрироваться как единщик сейчас, после регистрифии ФЛП, или теперь надо все-таки ехать в налоговую по месту прописки лично?? 
И еще вопрос - по рез-ту надання адміністративних послуг написано, что меня зарегистрировали, но нет выписки, написано "Документи: Відомості відсутні.". 
Надо подождать пока там появится выписка или это какой-то сбой и надо тоже идти ее отдельно получать?...

**Comment by Propeller-SV** [comment]
@anna-libra вобщем ситуация у вас та же, только у вас есть еще несколько дней (10 со дня регистрации ФЛП) для подачи заявки на единый налог. Думаю, теперь это нужно делать офлайн. Лично или бумажной почтой.
Ситуация с "Документи: Відомості відсутні." у меня за месяц не изменилась. Делайте выводы.

**Comment by anna-libra** [comment]
@Propeller-SV значит, Ваш пост все-таки кому-то помог избежать неприятностей )
если бы не зашла на форум и ваше сообщение не увидела бы, то тоже узнала бы, что меня не зарегистрировали на единый налог, когда уже поздно....

**Comment by agerman-ua** [comment]
@anna-libra 
1. Правильнее сходить по месту в налоговую. 
Просто потому что отдельно нет такой услуги на портале. 
Это изначально неплохой комплект - но только во время регистрации. И не разделяемый.
2. По разделу "документы" это не единичный случай. Несколько дней - была норма. Значит, к сожалению, и больше бывает. 
Увы мы никак на это повлиять не можем.
С уважением, Август.

**Comment by Maestra86** [comment]
@anna-libra , выписку можете получить здесь за 50 грн - https://usr.minjust.gov.ua/paidextract

**Comment by anna-libra** [comment]
@Maestra86 спасибо большое, хоть за этой бумажкой не надо будет никуда идти.
А в налоговую придется ехать за 500 км.... 
Хотя именно отсутствие необходимости идти в налоговую по месту прописки лично было для меня основным аргументов регистрации ФОП онлайн :(

**Comment by Propeller-SV** [comment]
@anna-libra думаю ехать, все-таки не обязательно. Позвони сначала в свою налоговую, спросите. Мне в мариупольской сказали, что заявление о переходе на единый налог (со следующего квартала) можно прислать по почте до 15 сентября.

**Comment by Maestra86** [comment]
@Propeller-SV а мне сказали обязательно принести лично до 5-го октября (дата регистрации ФОП - 6-е июня)...

**Comment by Propeller-SV** [comment]
@Maestra86 не знаю, я бы перепроверил. 1 октября начинается 4 квартал, как они могут принять заявление после начала квартала? Почему тогда мне в начале июля сказали, что 3-й квартал (июль-сентябрь) я на общей системе, без вариантов? Про "лично" - тоже думаю что чушь. Есть ценное письмо с описью вложения.

**Comment by agerman-ua** [comment]
@Propeller-SV 
Добрый день,
Хотел поблагодарить и проинформировать. 
На прошлой неделе изменили страницу подачи обращения на регистрацию ФОП (благодаря Вашему случаю не будет уже случайностей от налоговой связанных с датой постановки на учёт).
"Не вказуйте дату взяття на облік в органі державної податкової служби в заяві. Залишайте це поле незаповненим."
Надеюсь это уменьшит Ваш дискомфорт от сложившейся ситуации, т.к. поможет другим. Желаю удачи с налоговой. На самом деле они явно нарушили процедуру, но сейчас тяжело это изменить.
С уважением, Август.

**Comment by agerman-ua** [comment]
@Propeller-SV 
Добрый день, Сергей.
Данную тему закрою, для порядка. 
С уважением, Август.
