### ISSUE TITLE
Обращение о субсидии, поданное 06.06 - "не найдено"

### ISSUE THREAD

**Issue by juistet** [e-government-ua/iForum#552]
Звернення № **0-302262837** (Хмельницкий, субсидия ЖКП)

**06.06.2016** - Заявка на субсидию ЖКП подана.

В тот же день на мою электронную почту пришло сообщение о её принятии и сообщён её номер - Звернення № 0-302262837

**24.06.2016** в "Мой журнал" на igov.org.ua пришло сообщение,; "Доброго дня, ваші дані заповнені вірно для остаточної здачі документів та призначення ви маєте підійти за адресою Інституцька 18, для надання оригіналів документів і підписання заяви. Дякуємо."

Я его увидел не сразу, так как руководствовался написанным в "Крок 3" на сайте igov.org.ua на вкладке "Як працює", а именно - "Після остаточного опрацювання Вашої заяви та прийняття рішення щодо призначення Вам субсидії _Ви отримаєте_ ще одне _повідомлення на email_, в якому буде додатком прикріплене _рішення про надання Вам субсидії"_.

**07.07.2016** я приехал на указанный мне адрес, (Институтская, 18), где сначала прошёл по всем доступным кабинетам сам (и меня не очень понимали), а затем по кабинетам прошёлся работник Слубы - ходил долго, а когда вышел, то сказал - нет обращения, становитесь в очередь...

Месяц - утерян? А кто будет оплачивать ЖКП за этот месяц?

**Comment by zolotovatatyana** [comment]
Доброго ранку

**Comment by juistet** [comment]
Здравствуйте, благодарю за ответ.

Имею сообщить, что на igov.org.ua возможность подачи заявлений на Субсидию для города Хмельницкого - ОТКЛЮЧЕНА, по крайней мере, со вчерашнего дна (по моим наблюдениям).
Вот скриншот:
![01](https://cloud.githubusercontent.com/assets/20340660/16686416/ac003130-451a-11e6-9a9f-5b8e6517cc2f.PNG)

Скриншот Вкладки "Статистика":
![02](https://cloud.githubusercontent.com/assets/20340660/16686446/dd697fb0-451a-11e6-83f4-a5420c78e229.PNG)

**Comment by juistet** [comment]
Да, и я, как Пользователь **igov.org.ua** , хотящий не только решить свой личный вопрос, но и помочь её массовой имплементации - готов звонить, писать, ходить, жаловатся...

**Comment by zolotovatatyana** [comment]
УПСЗН г.Хмельницкого попросил отключить им услугу :(

Мы не в силах настаивать - иначе они просто не будут обрабатывать заявки.
Сейчас ведется работа по тестированию для них новой версии услуги, может быть запустим снова.

**Comment by juistet** [comment]
Так следует ли мне ждать удовлетворения моей заявки, поданной 06.06.2016? Или "сдаться" и пойти обычным путём?

**Comment by juistet** [comment]
Часики - тикают, денежка - капает...

**Comment by zolotovatatyana** [comment]
Вы можете пойти, заставить их найти заявку в дашборде, распечатать Заявление (оно датировано 6/06), и пустить именно  его в ход, раз без подписи не хотят отрабатывать, а не июльское дело.
 Ждать тут не поможет, к сожалению. никто не умеет "ждать" лучше чем госслужащие  :(

**Comment by juistet** [comment]
Так я уже был... Работник, сидевший на приёме заявок на субсидию, сам пошёл по кабинетам, а я его сопровождал - и не нашлось...  и - ПОЖАЛТЕ В ЧЕРГУ.

А чтобы ЗАСТАВИТЬ зайти в Инет, найти, распечатать, и прочее - нужно автомат брать. Тем более, что сам работник, ходивший и искавший, и остальные служащие, к кому он обращался - ну не знали, кто из них конкретно работает с АйГов. Кого заставлять?

Спасибо за участие.

**Comment by juistet** [comment]
:)

**Comment by zolotovatatyana** [comment]
@juistet я дописала: Ответственный за обработку заявок - Веремчук Олег Борисович. Ему координатор уже звонил.

**Comment by juistet** [comment]
О, спасибо!

**Comment by zolotovatatyana** [comment]
Поделитесь потом результатами визита, пожалуйста. и удачи!

**Comment by juistet** [comment]
Ок, Спасибо.

**Comment by juistet** [comment]
Здравствуйте!
Получил сегодня:
------------------
12.07.2016 12:50
Зауваження по заяві 0-302262837
 
Доброго дня, Пробачте за представлені незручності, ми знайшли вашу заяву і декларацію. Підійдіть за адресою Інститутська 18, каб.10. Якщо виникнуть проблеми телефонуйте тел. 380964672016. Дякую.
------------------
Отмечу, что с Веремчук О. Б. я не разговаривал, то есть система сама "починилась".

**Comment by zolotovatatyana** [comment]
"Само" в системе ничего не "чинится" ;)  Благодарить нужно команду iGov и волонтеров-коррдинаторов по г.Хмельницкому за профилактические беседы с чиновниками :)

**Comment by juistet** [comment]
Говоря "в системе" я имел в виду систему iGov.
Именно благодаря iGov госсистема и "починилась".

**Comment by juistet** [comment]
Здравствуйте!
Только что получил письмо от notifycation@igov.org.ua (от 29.08) с текстом:

Шановний(-а) ЮРІЙ ІВАНОВИЧ.

На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг відхилене.
Причина вказана у файлі, який прикріплено до цього листа.

А в прикреплённом файле - 
![attach_54477605](https://cloud.githubusercontent.com/assets/20340660/18087880/0bba1ea0-6ec0-11e6-98fb-1c9cd0d73932.jpg)

**Comment by zolotovatatyana** [comment]
@juistet И это после того как вы приезжали подписать бумажную заявку?

**Comment by juistet** [comment]
Да. Подписал я её 27 июля, И "донёс" справку о размере пенсии (1580). Так что ещё месяц без  субсидии - это будет весело...

**Comment by zolotovatatyana** [comment]
пожаловалась координатору, жду его комментариев.

**Comment by juistet** [comment]
Спасибо. Я, как компьютерщик, болею за ЭЛЕКТРОННЕ ВРЯДУВАННЯ, а не только за субсидию. Но субсидию ХОЧУ!

**Comment by zolotovatatyana** [comment]
Значит, нам с вами по пути :) Спасибо за настойчивость и обратную связь.

**Comment by juistet** [comment]
Спасибо. Если нужно будет привлечь старого системного администратора что-то потестировать, например - то я "завсегда в чужое дело встряну" © из фильма

**Comment by juistet** [comment]
Здравствуйте.
Сообщаю просто в порядке информирования.
При "личной явке" мне было разъяснено, что размер субсидии вычисляется исходя из моих доходов за прошлый год, когда я ещё работал. И то, что сейчас мой доход - 1580, так как с 15.02.2016 я не работаю, ничего не значит.

**Comment by zolotovatatyana** [comment]
Совершенно верно. Это по закону - для расчета берется доход за прошлый год.

Так может потому и отказ у Вас, что Ваш доход выше чем необходимый для назначения?

**Comment by juistet** [comment]
Ну да, мотивация именно такова. То, что с 15 февраля доход всего 1580 - не важно. :(

**Comment by zolotovatatyana** [comment]
Ну так что ж вы меня путаете. я уже пол-Хмельницкого на уши подняла из-за необоснованого отказа. Так проблема то только в том что они не правильный аттач прикрепили к отказу.

Сочувствую размеру Вашей пенсии, однако против закона не попрем :(

**Comment by juistet** [comment]
На момент написания Вам (в понедельник) я и сам не знал, что ранее действовавшее правило о исчислении величины дохода за предыдущие три месяца было отменено (очевидно, для "удобства" получающих).

**Comment by zolotovatatyana** [comment]
нынче по закону так: 

"якщо субсидія для відшкодування витрат на оплату житлово-комунальних послуг призначається у першому кварталі року, середньомісячний сукупний дохід визначається за перші три квартали попереднього року, в інших випадках - за попередній календарний рік"

**Comment by juistet** [comment]
Спасибо.
Все те, у кого "сукупний дохід" с начала 2016 года резко упал, проживут весёлый год.
