### ISSUE TITLE
Получила письмо с положительным решением по заявке №0-377623329, код не рабочий

### ISSUE THREAD

**Issue by Smirnusha** [e-government-ua/iForum#554]
Добрый день!
Получила письмо с положительным решением о регистрации ФОП по заявке №0-377623329, код не рабочий.
Нашла себя по ИНН. А какие дальнейшие действия, подскажите, пожалуйста? Как получить все документы?

**Comment by agerman-ua** [comment]
@Smirnusha 
Добрый день.
Проверьте ещё раз код из письма по указанной там ссылке - всё есть. 
Прошу после проверки подтвердить что всё в порядке.
С уважением, Август.

**Comment by Propeller-SV** [comment]
@agerman-ua уважаемый Август, а как это работает? По моей заявке № 0-277581305 при проверке по коду уже больше месяца "Документи: Відомості відсутні." Уже и не измениться статус?

**Comment by agerman-ua** [comment]
@Propeller-SV 
Знал бы точно - ответил с удовольствием. 
Просто у @Smirnusha прямо сейчас всё в норме.
А как и когда оно стало так - можно только гадать.
То что не сразу появляется - уже факт.
И похоже что это совсем не фиксированный параметр.
Увы - эта процедура происходит за пределами видимости портала.
С уважением, Август.

**Comment by Smirnusha** [comment]
Да, уже все ок. Спасибо

**Comment by agerman-ua** [comment]
Отлично.
Спасибо за то что воспользовались порталом. :)
Всего наилучшего, Август.
