### ISSUE TITLE
Заявка 0-327719546

### ISSUE THREAD

**Issue by SpeakSimple** [e-government-ua/iForum#555]
Что означает статус "закрыта" на обращении?

**Comment by agerman-ua** [comment]
@SpeakSimple 
Добрый день, 
Простите за задержку.
Если просто ответить про статус "закрыто" то это означает что Ваше обращение обработано полностью. 
В результате обработки Вы обязательно должны получить письмо на почту которую указали при подаче обращения и, одновременно, оно же доступно у Вас в журнале (после авторизации) по данной заявке. Положительное или отрицательное решение - видно в письме.
С уважением, Август.
