### ISSUE TITLE
Вопрос относительно регистрации ФОП

### ISSUE THREAD

**Issue by vsgdp** [e-government-ua/iForum#558]
В заполняемых полях есть строка: 
1) Тип приміщення:я - что нужно указать КВАРТИРА  (приватизированная квартира) ???
2) Город, указівать Діпро или Дніпропетровськ ?
Спасибо за ответ

**Comment by agerman-ua** [comment]
@vsgdp 
Добрый день,
1) Нормально просто "квартира". Варианты самые часто встречающиеся "квартира, кімната, кабінет, офіс". Может однако у кого-то быть и что-то другое.
2) Дніпро - правильно. В программе внесения данных в реестр уже изменён город. Есть проблемы с районами города (там ещё старые) поэтому район города лучше указывать так "новый (старый)", регистратору легче разбираться. Можно и город так-же "Дніпро (Дніпропетровськ)".
С уважением, Август.
