### ISSUE TITLE
Заявка почти месяц в работе 0-329748578????

### ISSUE THREAD

**Issue by yuluaki** [e-government-ua/iForum#559]
Добрый день, заявку подала 16 июня 0-329748578 , подскажите ждать ответа или нет????

**Comment by zolotovatatyana** [comment]
Добрый день
Ваша заявка находится в работе у сотрудников управления соцзащиты:

Управління праці та соціального захисту населення Амур-Нижньодніпровської районної у м. Дніпропетровську ради
вул. Радистів, 8, 
м. Дніпропетровськ
(056) 375-90-61

**Comment by yuluaki** [comment]
спасибо
