### ISSUE TITLE
Нет ответа по вопросу оформления субсидии

### ISSUE THREAD

**Issue by Dufa** [e-government-ua/iForum#56]
Добрый день! Подал заявку на оформление субсидии №6082741 г. Днепропетровск, Бабушкинский район. До сих пор нет ответа. В статусе висит - взять в работу. Подскажите пожалуйста на какой стадии моя заявка.

**Comment by dmitrijzabrudskij** [comment]
добрый день
Ваша заявка в работе. сейчас ожидается ответ по Вашему обращению

**Comment by dkfl** [comment]
Добрый день! Подал заявку на оформление субсидии №7402944 г. Днепропетровск, Бабушкинский район. До сих пор нет ответа. В статусе висит - взять в работу. Подскажите пожалуйста на какой стадии моя заявка.

**Comment by dmitrijzabrudskij** [comment]
добрый день. она в работе

**Comment by dkfl** [comment]
спасибо


>Среда,  4 ноября 2015, 7:53 -08:00 от dmitrijzabrudskij <notifications@github.com>:
>
>добрый день. она в работе
>—
>Reply to this email directly or  view it on GitHub .


С уважением, Влад

**Comment by annastolbova** [comment]
Заявка закрита 18.11.2015, 
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
