### ISSUE TITLE
Заявка №0-399140310 Уникальная формулировка отказа!

### ISSUE THREAD

**Issue by OlegYu** [e-government-ua/iForum#560]
Заявка №0-399140310 (это уже четвёртая заявка на регистрацию ФОП)
По трём предыдущих заявкам отказ с формулировкой "Не заполнены поля", Поля заполнены не на государственном языке" и.т.п. Хотя все поля заполнены, и заполнены правильно. Я даже к последней заявке прикрепил скриншоты на которых это видно.

И вот! Отказ по очередной заявке. Формулировка просто убила:

> **Коментар держслужбовця (Причина:Зареєструвати неможливо. Не бачимо в Єдиному державному реєстрі юридичних осіб, фізичних осіб-підприємців та громадських формувань справи для опрацювання, яку надіслав адміністратор ЦНАПу)**

Написать, как обычно "поля не заполнены" уже будет смешно, поэтому госслужащий (если до него конечно эта заявка дошла) придумал новую формулировку. Сервис становится всё забавнее.

Кстати, а разве госслужащий не должен был "сформувати справу" для того чтобы потом её "опрацювати" ???

Может кто-то что-то объяснить? Понятно что сервис волонтёрский, экспериментальный, альфа-версия и т.д.  Зачем тогда сырой и не рабочий сервис так нахваливает Дмитрий Дубилет?

**Comment by Maestra86** [comment]
у меня приняли заявку после того, как я заявление заполнила в бумажном виде, распечатала, подписала, скан прикрепила к заявке и в комментариях попросила посмотреть вложение.

**Comment by koi8** [comment]
> у меня приняли заявку после того, как я заявление заполнила в бумажном виде, распечатала, подписала, скан прикрепила к заявке и в комментариях попросила посмотреть вложение.
@Maestra86 , спасибо за наводку! Будем пробовать! Ключем тоже подписывали или просто подписали рукой заяву и отсканили?

**Comment by agerman-ua** [comment]
@OlegYu 
Да. Эксклюзивная формулировка. :( 
Не встречалось пока такого. Нужно действительно понять в чём дело.
С незаполненными полями (туда же не "на украинском") была проблема, чиновники просто не пользовались возможностью уточнять любое поле (кроме ФИО).
Пытаемся это донести им в каждом разговоре.
@Maestra86 
Похоже Вас нормальный сотрудник обслужил. Использовал правильно инструмент. Мы стараемся анализировать статистику и "плохие показатели" привлекают наше внимание но самое грустное - за каждым "плохим случаем" стоит живой человек. Стараемся. Уже осталось всего несколько обращений сроком более недели.

**Comment by OlegYu** [comment]
Оформил заявку ещё раз. 14.07.2016. Это уже пятая попытка.
Сегодня, 19.07.2016 заявку выполнили! Сервис всё-таки работает!
Заявку оформлял как и две предыдущие: со скриншотом на котором видно что все поля заполнены, и заполнены на украинском языке. Видимо на этот раз попался нормальный госслужащий, либо госслужащий который не хотел глупо выглядеть если напишет отказ "не все поля заполнены, заполнены не на государственном языке".

**Comment by OlegYu** [comment]
Если бы госслужащих штрафовали за отказы по правильно заполненым заявкам, думаю сервис работал бы лучше.

**Comment by agerman-ua** [comment]
@OlegYu Оооо, хорошая новость на ночь. Спасибо.
Как раз это и есть сейчас средний срок обработки - около недели.
Мы стараемся и постепенно вводим то что формальный отказ - это и некрасиво и непрактично.
По крайней мере в моих беседах всё именно так.
Ну а лучших мы просто стараемся поощрять. Наказывать штрафами и нельзя и практически не с чего было бы. Зарплаты у рядовых чиновников совсем небольшие.
С уважением, Август.
