### ISSUE TITLE
BUG. Ошибка в разделе "Видача витягу з Єдиного державного реєстру юридичних осіб та фізичних осіб – підприємців"

### ISSUE THREAD

**Issue by KonstantinPopov** [e-government-ua/iForum#561]
при попытки оформить заявку на услугу 
"Видача витягу з Єдиного державного реєстру юридичних осіб та фізичних осіб – підприємців"
https://igov.org.ua/service/80/general
получаю js ошибку  "0d8859d8.app.js:1 stateChangeError TypeError: Cannot read property 'split' of undefined(…)" 
версия браузера  Google Chrome  51.0.2704.106 (64-bit)

![8a3dd9de91](https://cloud.githubusercontent.com/assets/6975005/16846457/3d5dee04-49f5-11e6-9f3a-10d35e73363b.jpg)

**Comment by zolotovatatyana** [comment]
Иногда такая ошибка возникает из-за нечищеных куков и кеша. Проверила - работает корректно. Спасибо за обращение.
