### ISSUE TITLE
заявка №0-408131058. Державна реєстрація створення фізичної особи – підприємця

### ISSUE THREAD

**Issue by Rehina8** [e-government-ua/iForum#562]
Подавала заявку на регистрацию ФОП. Получила очень странный ответ.

Ваше звернення №0-408131058 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.

Коментар держслужбовця (Причина:Зареєструвати неможливо. Не бачимо в Єдиному державному реєстрі юридичних осіб, фізичних осіб-підприємців та громадських формувань справи для опрацювання, яку надіслав адміністратор ЦНАПу)

В чем может быть причина? Как я могу быть в указанном реестре, если я только подаю заявку на регистрацию?

**Comment by agerman-ua** [comment]
Добрый вечер. @Rehina8 .
Проверьте почту, я ещё 15.07.2016 Вам написал письмо по этому поводу.
Если ещё останутся вопросы - конечно прошу задавать или там или тут.
С уважением, Август.

**Comment by Rehina8** [comment]
Здравствуйте.Я получила Ваш ответ и создала новую заявку на регистрацию
фоп,прошло 2 дня ,жду ответа,надеюсь на этот раз все будет хорошо.Спасибо.

19 июля 2016 г. 23:04 пользователь "agerman-ua" <notifications@github.com>
написал:

**Comment by agerman-ua** [comment]
@Rehina8 
Добрый вечер, снова.
Спасибо за доверие и быстрый ответ.
Не могу пока ещё обещать что всё будет хорошо. :)
Но то что будет намного быстрее и с более адекватным ответом - обещаю.
С уважением. Август.

**Comment by agerman-ua** [comment]
@Rehina8 
Добрый день,
Поздравляю с регистрацией, хоть поздравление и запоздало больше чем на месяц. :) Удачи.
С уважением, Август.

**Comment by Rehina8** [comment]
Добрый день.
Спасибо,зарегистрироваться со второй попытки и правда получилось,спасибо за
помощь.
Правда прикрепляла заявление про желание встать на эдиный налог,но оно
почему то не прошло.Пришлось ехать в свою налоговую заполнять его в
ручную.Но и тут не все хорошо,когда уехала,оказалось что моего вида
деятельности с процентной ставкой нет по месту прописки и программа из-за
этого не может принять моё заявление.Говорят нужно что-бы мой сельсовет
принял решение и вписал мой вид деятельности себе,тогда все
получится.Вообщем у меня ещё все продолжается:)

31 авг. 2016 г. 17:37 пользователь "agerman-ua" <notifications@github.com>
написал:

@Rehina8 <https://github.com/Rehina8>
Добрый день,
Поздравляю с регистрацией, хоть поздравление и запоздало больше чем на
месяц. :) Удачи.
С уважением, Август.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/e-government-ua/iForum/issues/562#issuecomment-243784656>,
or mute the thread

**Comment by agerman-ua** [comment]
Ого. Держите в курсе. Возможно кому-то это очень поможет.
Удачи.
