### ISSUE TITLE
Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця)

### ISSUE THREAD

**Issue by 090579** [e-government-ua/iForum#563]
Добрый день. Подскажите можно ли оформить заявку на бабушку? У нее нет карточек банковских и  мобильного телефона. Когда захожу через свой приват24, то автоматом подтягивает мои данные (которые нельзя изменить)

**Comment by Koffeek** [comment]
@090579 С целью недопущения злоупотреблений заявка подается только от себя.
