### ISSUE TITLE
В анкете постановки нового транспортного средства на учет поле для файлов внизу, которое говорит что может ZIP ругается что формат только JPG, PNG и PDF

### ISSUE THREAD

**Issue by YuriyBit** [e-government-ua/iForum#564]
Неплохо-бы сделать 3 поля для файлов или мультигрузилку (там 3 документа обычно). Или если нет - то убрать фразу "у вигляді ZIP архіву" т.к. ZIP не принимает форма.
![postanovka_na_uchet](https://cloud.githubusercontent.com/assets/12912658/16902938/7b2d8580-4c77-11e6-93f0-8dd047dff3a9.JPG)

**Comment by kurbpa** [comment]
@YuriyBit 
Мне не удалось воспроизвести ошибку с прикреплением ZIP файла
Без проблем прикрепил.

![default](https://cloud.githubusercontent.com/assets/11442397/16979379/6c0fc894-4e69-11e6-9806-441731c223bc.PNG)
