### ISSUE TITLE
Спрощена система оподаткування (куди можна надіслати заяву)

### ISSUE THREAD

**Issue by stopanko** [e-government-ua/iForum#566]
При реєстрації ФОП можна одразу прикріпити заяву щодо переходу на спрощену систему оподаткування. При реєстрації, заяви я не прикріпив. Тепер в мене виникають запитання як мені це зробити? Спробував ще раз відправити звернення із прикріпленим документом та мою заявку зразу ж закрили не звернувши уваги на коментарі. Звернення № 0-405686634
Було б непогано добавити можливість відіслати заяву в послузі внесення змін до ФОП.

**Comment by agerman-ua** [comment]
@stopanko 
Доброго дня.
На жаль все правильно. 
Вам відповіли що Вас вже зареєстрували. 
Розумієте послуга "реєстрація ФОП" тому ми можемо тільки зареєструвати і саме в момент реєстрації Вам надається змога обрати систему оподаткування (в самій заяві на реєстрацію). Та додати заповнену заяву на систему оподаткування до звернення. Така процедура. 
Окремо можна змінити загальну систему тепер тільки безпосередньо в податковій (можно спробувати й через лист "з повідомленням" але не знаю напевне чим це скінчиться). 
Додатково зазначу, що коли податкова піде назустріч змінам, які ми пропонуємо, то з великим задоволенням наша команда додасть на портал онлайн послугу по зміні системи оподаткування (і не тільки її).
З повагою, Август.

**Comment by Maestra86** [comment]
слава Богу, що не прикріпили.
почитайте https://github.com/e-government-ua/iForum/issues/550

**Comment by agerman-ua** [comment]
@Maestra86 
Так теж буває. Але це не правило. 
Вже змінили сторінку формування звернення - для виключення випадків з відмовою податкової на реєстрацію спрощеної системи оподаткування які пов'язані з датою в заяві (дякуючи випадку @Propeller-SV).
З повагою, Август.

**Comment by Maestra86** [comment]
@agerman-ua , причина може бути не тільки в даті. 
Мені в Податковій відповіли, що моєї заяви в очі не бачили, про igov нічого не знають і їм діла не має до того, чому заява не була подана протягом 10-ти днів з дати реєстрації ФОП.

**Comment by agerman-ua** [comment]
Добрий вечір, @Maestra86 
Мені дуже прикро читати про те що Ви пишете, з одного боку тому що це правда яка з Вами трапилась, і тому що співробітник податкової так відповів. 
Так вони не отримують дані від iGov - тут все правильно. Вони отримують заяви звичайним чином від реєстратора. Тобто у спосіб який визначено законодавством. Це стосується саме процедури реєстрації. Після реєстрації надалі реєстратор не має ніякого відношення до зміни обраної системи оподаткування. 
Може в реєстрі Вам треба впевнитися що обрана правильна податкова? Можливо зараз йде реорганізація податкової та вони просто не можуть налагодити стабільну роботу або Ви просто не сподобалися податковому інспектору?! На жаль не маю точної відповіді. 
Де бачимо що можемо запобігти негативній ситуації - стараємося це зробити, на жаль частіше це вже після реальних випадків з нашими заявниками.
Одне можу сказати що дуже багато людей вже пройшли цю процедуру успішно. Тобто подавали звернення про реєстрацію онлайн через iGov, додавали заяву на спрощену систему та їх ставили на облік в податковій без їх безпосередньої участі. Це теж факт. Мені немає чого до цього додати.
З повагою, Август.

**Comment by Maestra86** [comment]
@agerman-ua , дякую Вам за Вашу роботу і сподіваюсь, що у цього проекту велике майбутнє!

**Comment by agerman-ua** [comment]
@Maestra86 
Вам теж наснаги та успіхів в усіх Ваших започаткуваннях.
З повагою, Август.
