### ISSUE TITLE
Получено положительное решение по ФОП

### ISSUE THREAD

**Issue by vsgdp** [e-government-ua/iForum#567]
Регистрация ФОП через данный сервис прошла удачно и быстро. спасибо, чуть больше недели. (в первом случае, почти месяц и отрицательный ответ - хотя поля заполнялись точно так же).
Теперь вопрос: каковы мои дальнейшие действия, в плане получения "Свидетельство о Госсударственной регистрации" и т.д. на бумаге или это уже не актуально? С чем тогда идти в банк, т.к. нужен расчётный счёт? На сайте usr.minjust.gov.ua - все свои данные по регистрации видел в разделе: Фізична особа-підприємець, где указаны все постановки на учёт.
Спасибо за ответ.

**Comment by agerman-ua** [comment]
@vsgdp 
Добрый день,
Да. Действительно сейчас уже не так актуальны бумажные документы.
Если у Вас в письме был указан "уникальный код" по нему можете получить и ссылку на документ по операции. Банк всё равно запрос делает в реестр. Если Вы там есть - вопросов быть не должно.
Конечно иногда есть ньюансы (у юрлиц может быть связано с уставом), но не вдаваясь в подробности могу только поздравить и пожелать успехов на ниве предпринимательства. На всякий случай проверьтесь в налоговой всё ли так как Вы ожидали.  https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx можете тут попробовать проверить.
С уважением, Август.

**Comment by vsgdp** [comment]
Спасибо, УДАЧИ!
