### ISSUE TITLE
Заявка 0-419089399 - никакого движения - завтра (2016-07-22) будет последний рабочий день для регистрации нового авто

### ISSUE THREAD

**Issue by yuuuuser** [e-government-ua/iForum#568]
Заявка 0-419089399 - Реєстрація транспортного засобу придбаного в торгівельній організації (нові транспортні засоби)
Покупка совершена в Пт. 2016-07-15 (во второй половине дня)
Заявка подана утром Пн. 2016-07-18
Завтра Пт. 2016-07-22 последний рабочий день, когда истекает время отведенное на регистрацию.
И до сих пор даже не присланы квитанции на оплату.
Т.е. практически невозможно будет выполнить регистрацию в установленный срок - 10 дней.

Как мне получить документы, подтверждающих отсутствие возможности своевременной регистрации?

**Comment by yuuuuser** [comment]
Сходил ногами в Територіальний сервісний центр 1242 регіонального  сервісного центру  МВС в Дніпропетровській області	
49041, м. Дніпропетровськ, проспект Праці, 16

**Comment by VadymVolos** [comment]
@kurbpa Павел, людина запитує по авто, можете допомогти з цим питанням?

**Comment by VadymVolos** [comment]
@yuuuuser коли сходили що вам там сказали, до чого домовились?

**Comment by yuuuuser** [comment]
Я не расследовал на счет заявки - пришел, заплатил в кассе сборы, занесли данные.
Там, правда номеров не оказалось - так что как появятся - нужно будет еще раз съездить.
Я думаю, что вам сподручнее понять, что там случилось - вы должны хоть знать кому заявка должна была попасть, попала ли и т.п.

**Comment by yuuuuser** [comment]
Тут может нужно убедиться, что никто другой не начал заводить эти данные....
