### ISSUE TITLE
не могу подать Звернення у сфері державної реєстрації актів цивільного стану сайт http://dracs.minjust.gov.ua/Appeal/Edit/871027

### ISSUE THREAD

**Issue by yablonix** [e-government-ua/iForum#569]
блокируется ввод Орган ДРАЦС, до якого Ви бажаєте звернутися

**Comment by zolotovatatyana** [comment]
Здравствуйте
Сайт МинЮста http://dracs.minjust.gov.ua/ администрируется техподдержкой минюста, связаться с которой можно: (+38 044) 206-71-10
