### ISSUE TITLE
Заявка на субсидию.

### ISSUE THREAD

**Issue by greengirls** [e-government-ua/iForum#57]
Подали заявку на субсидию  ещё в сентябре месяце. Почему нет ответа до сих пор?
Номер заявки 4202273. Бабушкинский район.

**Comment by dmitrijzabrudskij** [comment]
вам отправили ответ 8 минут назад. и район ленинский

**Comment by greengirls** [comment]
А где смотреть ответ? На почту мне ничего не пришло?

**Comment by dmitrijzabrudskij** [comment]
а на какую почту вы ждете ответ и от кого отправлялась заявка?

**Comment by greengirls** [comment]
я ошиблась с номером заявки 5328665 .

**Comment by dmitrijzabrudskij** [comment]
эта заявка в работе еще. подана 13.10

**Comment by greengirls** [comment]
Радионова Елена

**Comment by greengirls** [comment]
Подана 29 сенября

**Comment by dkfl** [comment]
Подали заявку на субсидию ещё 13 октября . Почему нет ответа до сих пор?
Номер заявки 7402944. Бабушкинский район.

**Comment by dmitrijzabrudskij** [comment]
потому что они обрабатываются в течение 20 рабочих дней

**Comment by dkfl** [comment]
спасибо.


>Среда,  4 ноября 2015, 7:50 -08:00 от dmitrijzabrudskij <notifications@github.com>:
>
>потому что они обрабатываются в течение 20 рабочих дней
>—
>Reply to this email directly or  view it on GitHub .


С уважением, Влад

**Comment by Elyzaveta** [comment]
Подскажите пожалуйста, если в квартире приписано 3 человека, все получают заработную плату, где это указывается в заявке?

**Comment by dkfl** [comment]
ВЫ НЕ ОШИБЛИСЬ!? Я ТАКОЙ ЖЕ КАК И ВЫ !!!


>Среда,  4 ноября 2015, 9:10 -08:00 от Elyzaveta <notifications@github.com>:
>
>Подскажите пожалуйста, если в квартире приписано 3 человека, все получают заработную плату, где это указывается в заявке?
>—
>Reply to this email directly or  view it on GitHub .


С уважением, Влад

**Comment by greengirls** [comment]
С 29 сентября уже 20 рабочих дней прошло.

**Comment by dmitrijzabrudskij** [comment]
не понимаю почему в этой ветке разнобой такой, поэтому отвечаю всем:

Елизавета: выберите внизу сколько с вами в квартире живет людей и появятся необходимые поля под каждого из них

дкфл: вопрос был в общем. не принимайте болезненно на свой счет:)

зеленыедевушки: определитесь с номером заявки - вы только в этой ветке 3 назвали. сколько еще у вас в запасе?

**Comment by greengirls** [comment]
Я ошиблась  только первый раз .
Еще раз моя заявка 5328665.

**Comment by dmitrijzabrudskij** [comment]
она в работе с 13.10. подождите еще, пожалуйста

**Comment by dkfl** [comment]
Здравствуйте. 13 октября я подала заявку на получении субсидии (сенюта е.и.). Сразу пришло письмо от  Noreply@igov.org.ua  о регистрации моей заявки (номер заявки 7402944), . 20 дней давно истекли, а никакой информации о моей заявке нет. В каком состоянии заявка, рассматривалась ли, ?!
сегодня поменялась дата принятия заявки в работу с 13.10.15. на 06.11. 15 . -  как это понимать ???!!!

>Среда,  4 ноября 2015, 23:46 -08:00 от dmitrijzabrudskij <notifications@github.com>:
>
>она в работе с 13.10. подождите еще, пожалуйста
>—
>Reply to this email directly or  view it on GitHub .


С уважением, Влад

**Comment by dkfl** [comment]
здравствуйте. . я подала заявку на субсидию ( сенюта е.и. ) № 7402944. заявку приняли к работе 13.10.15. сегодня исполнился ровно месяц со дня принятия к работе . подскажите пожалуйста окончательный вердикт по моей заявке. спасибо.


>Среда,  4 ноября 2015, 23:46 -08:00 от dmitrijzabrudskij <notifications@github.com>:
>
>она в работе с 13.10. подождите еще, пожалуйста
>—
>Reply to this email directly or  view it on GitHub .


С уважением, Влад

**Comment by dkfl** [comment]
Здравствуйте! Почему я, Сенюта Е. И. ул юн. ленинцев 28 кв91 не получаю субсидию.? Доходы такие же как и в прошлом году.


>Пятница, 13 ноября 2015, 10:09 +02:00 от Влад Сенюта <vlad_senyuta@mail.ru>:
>
>здравствуйте. . я подала заявку на субсидию ( сенюта е.и. ) № 7402944. заявку приняли к работе 13.10.15. сегодня исполнился ровно месяц со дня принятия к работе . подскажите пожалуйста окончательный вердикт по моей заявке. спасибо.
>
>
>>Среда,  4 ноября 2015, 23:46 -08:00 от dmitrijzabrudskij < notifications@github.com >:
>>
>>она в работе с 13.10. подождите еще, пожалуйста
>>—
>>Reply to this email directly or  view it on GitHub .
>
>
>С уважением, Влад


С уважением, Влад

**Comment by GrekD** [comment]
@dkfl  адресуйте, пожалуйста, Ваш вопрос в управление соц.помощи согласно места Вашей регистрации
