### ISSUE TITLE
Реєстрація ФОП - тільки через 8 днів прийшло повідомлення не заповнено поле район

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#570]
Привіт!

Суть скарги така. Я так зрозумів що автор вже поїхав постояв в черзі і офлайн подав документи (можливо я помиляюсь, але я так зрозумів з коментаря). Але! Коли автор подав заявку на айГов не було ніякої реакціі, і друга проблема, що тільки через 8 днів надішло повідомлення що під час реєстрації не заповнено поле район.

==
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1732449740377235&comment_tracking=%7B%22tn%22%3A%22R%22%7D

Леся Тылина
 На форумі не можу зареєструватись, на IGOV залишила заявку на ФОП тиждень назад, ніякої реакції, а час обмежений, щоб податись і в податкову... Куди звертатись? Заявка 0-408152281

Портал igov
Добрий день, написано заявка в обробці
https://igov.org.ua/search?sID_Order=0-408152281
На сайті IGOV можете ввійти в свій профіль і там передивитися листи які вам присилали на емейл, можливо ви не отримали лист, а в ньому є всі інструкції, дата коли прийти та ін. 
Для більш детальної консультації, вам потрібно зареєструватися на форумі і там запитати https://github.com/e-government-ua/iForum/issues

Леся Тылина
Нажаль, так я і не змогла розібратись. На форумі я не змогла зареєструватись, а лист не відкривався - перекидував менезнову на хід до порталу. Шкода, бо ідея дуже класна, а я була вимушена їхати до адміністрації і сидіти 3 години в черзі. Можливо це я до чогось не допетрила, а можливо і в сайті проблема.

Леся Тылина
Вже після того, як я написала попередній коментар, пртйшла відповідь, що в анкеті я не заповнила поле район міста. З моменту реєстрації пройшло 8 днів, поки відреагували на мою заяву(
/------

**Comment by agerman-ua** [comment]
Доброго дня, @VadymVolos 
Тут важливо зрозуміти логіку подій.
1. Звернення було подано 14.07.2016 
2. Відразу порталом було відправлено **автоматичний** лист про те що звернення зареєстровано.
3. Деякий час зареєстроване звернення було в черзі з якої її взяв держслужбовець.
4. Після аналізу він опрацював звернення з відмовою, після чого портал **автоматично** відправив сформований лист (з причиною відмови) згідно рішенню держслужбовця. Це сталося 21.07.2016. 
Тобто **система** як бачила зміни - інформувала про це заявника відповідними листами.
Для окремого спілкування (питання та інше) існує спеціальний форум (цей), про що й повідомили заявника.
Таким чином від п.1 до п.4 пройшло 7 календарних діб. Термін дуже прийнятний. Зараз ми досягли стану коли звернення опрацьовуються від 5 до 7 календарних діб. На меті дійти до гарантованого терміну 2 робочих доби.
Не знаю що ще додати. 
Начебто тільки те що людина не зрозуміла "як це працює", можливо треба ще не один раз переглянути текст допомоги для запобігання можливості таких непорозумінь, не більше.
З повагою, Август.

**Comment by VadymVolos** [comment]
@agerman-ua справа в тому, що губиться 8 днів поки держслужбовець побачить що там не заповнено одне поле. Тому стосовно полів це можна автоматично перевіряти, а не чекати 8 днів пока це поле перевірить вручну держслужбовець.

**Comment by agerman-ua** [comment]
@VadymVolos 
Для приблизного терміну очікування є розділ статистика по кожній послузі. На самому початку (перший-другий місяць) після запуску послуги вона накопичує інформацію та поступово починає коректно відпрацьовувати. Наприклад зараз на реєстрацію ФОП видає таймінг (5 днів, 12 годин, 36 хвилин) в дійсності 5-7 діб. От людині і перша інформація про термін очікування. Це працює бо багато питань на початку було про 4 дні з таймінгу а чекали довгенько.
Оскільки питання вийшло до більш технічного стану - наведу простий приклад чому важко реалізувати автоматичну та безпомилкову перевірку деякої інформації.
Наприклад райони.
Є випадки коли повна адреса включає до себе і район області і місто і район в місті.
Є випадки коли тільки район області та населений пункт
Є випадки коли просто місто і район в ньому.
Це дуже різні комбінації, тому навіть не можемо зробити деякі поля обов'язковими з цих причин.
З повагою, Август.

**Comment by VadymVolos** [comment]
@agerman-ua Шановний Август. Підкажіть команда по впровадженню що думає про ці пункти:
1. Потрібно додати текст "Держслужбовець ще не взявся за вашу заявку, чекайте, приблизний час стільки то днів". Щоб люди знали держслужбовець бачив чи ні.
2. По можливості перевіряти поля, і якщо вони не заповнені, казати щоб людина заповнила, тоді не потрібно буде чекати 8 днів.

**Comment by agerman-ua** [comment]
@VadymVolos 
1. Варіант "не дуже". Можу відправити з листа про реєстрацію до статистики конкретної послуги і там буде наведено актуальну інформацію. Ми не можемо проінформувати заявника про момент взяття в роботу. Система цього не виділяє. Так як і немає можливості визначити кількість послуг "в черзі" на момент подання звернення.
2. Зараз заплановано внутрішній редизайн бізнес-послуг. Подивимось що зможемо покращити в цьому напрямку. На швидкість "взяття в роботу" це не вплине. І, вибачаюсь, чому ми увесь час говоримо про 8 діб. Тут було 7 діб.
З повагою, Август.

**Comment by VadymVolos** [comment]
@agerman-ua мета цього issues покращити надання послуг. Якщо всі питання ви знаєте, і впроваджуєте, тоді можна закривати цей issues? Чи цей issues ще потрібен?

**Comment by agerman-ua** [comment]
Ні. Дякую Вадиме щиро. Мені зрозуміло що можна зробити, а що ні. Закриваю цей ішью.
З повагою, Август.
