### ISSUE TITLE
Заявка № 0-401087505 (ФОП) в обработке от 12.07

### ISSUE THREAD

**Issue by alexkomis** [e-government-ua/iForum#571]
Здравствуйте. Подскажите, пожалуйста, как продвигается заявление, есть ли результат? Писем после уточнения данных по заявке не получал (в спаме тоже нету). 
Заранее спасибо.

**Comment by agerman-ua** [comment]
Добрый день, @alexkomis 
Простите, заявка уже точно в обработке у госслужащего. 
Уточнить более точно статус сможем уже только в понедельник.
Письмо будет обязательно, и в почту и дополнительно в  разделе "Мой журнал" по Вашему обращению.
С уважением, Август.

**Comment by alexkomis** [comment]
Добрый день, @agerman-ua 
Хотел бы еще раз уточнить как обстоят дела, потому что с понедельника никакого прогресса, увы.
С моей стороны в разделе "Мой журнал" к госслужащему есть вопрос от 15.07.2016 , на который я пока ответа не получил. Не могли бы Вы пролить больше света на ситуацию или подсказать сколько нужно ждать.
Спасибо.

**Comment by agerman-ua** [comment]
Добрий день, @alexkomis 
Вітаю, Вас вже зареєстрували, просто ще звернення держслужбовець не закрив. 
Листа після обробки отримаєте обов'язково.
Можете перевірити на порталі мінюсту https://usr.minjust.gov.ua/ua/freesearch/
З повагою, Август.
