### ISSUE TITLE
Звернення # 0-345984717 отримання закордон паспорта

### ISSUE THREAD

**Issue by aotsvietkov** [e-government-ua/iForum#572]
Звернення # 0-345984717. Заказал услугу получения паспорта с электронным носителем данных. Г. Кривой Рог, отделение ДМС Саксаганский район, Мелкие 47 к, посещение отдела ДМС 19.08.2016 14:45. Хочу уточнить все ли хорошо с моим обращением и в выбранное время меня обслужат и у отделения ДМС будет возможность снять данные. Но буду ли я отправлен домой. Так как прецеденты такие были по Украине. Спасибо!

**Comment by Koffeek** [comment]
@aotsvietkov Ваше обращение зарегистрировано и прием должен быть по расписанию. Портал, к сожалению, не может предположить некоторые обстоятельства (отстутствие света, работоспособность ЕГДР), но в остальном предпосылок для отказа в визите нет.
