### ISSUE TITLE
Как можно заказать и получить справку о составе семьи в Днепре?

### ISSUE THREAD

**Issue by Doxtyp** [e-government-ua/iForum#573]
Точнее говоря нужна справка о количестве лиц, зарегистрированных в квартире

**Comment by Doxtyp** [comment]
Точнее говоря нужна справка о количестве лиц, зарегистрированных в квартире

**Comment by Koffeek** [comment]
@Doxtyp Необходимо обращаться в свой ЖЕК, кооператив, ОСМД. Органы регистрации пока не дают такую справку.

**Comment by Doxtyp** [comment]
@Koffeek спасибо, пойду в ЖЭК.
Мне кажется, что органы регистрации, например, Міграційна служба, не выдает - так как эта справка ни в одном законе/ постановке не упоминается, а требуют её только некоторые коммунальные службы.
