### ISSUE TITLE
Звернення № 0-316574231

### ISSUE THREAD

**Issue by OBezdietko** [e-government-ua/iForum#574]
Заява на реєстрацію ФОП була подана 11.06.2016 через портал в м.Дніпро. З того часу ніякого позитивного руху. Через три тижні мені дзвонили і сказали що треба ще досканувати якісь папірці бо потрібен "живий" підпис. ЕЦП як я бачу то незнайомий звір для реєстратора. Потім подзвонив менеджер порталу і сказав що аби прискорити виконання перевели мою заявку на іншого реєстратора. Обіцяв що за максиму 5 днів все буде вирішено. Пройшло майже два тижні і результату 0. Коли буде результат? Хто саботує оброблення звернення? Чи довго ще мені чекати?

**Comment by agerman-ua** [comment]
Доброго дня, @OBezdietko 
Не розумію, чому досі Вас не зареєстрували. Начебто питань у нового реєстратора не виникало.
Зранку перевірю стан Вашого звернення.
Вибачте за ситуацію. 
З повагою, Август.

**Comment by agerman-ua** [comment]
Доброго дня, @OBezdietko 
Нарешті зрозумів. Непередбачені обставини.
Реєстратори раптово почали переїжджати до іншого приміщення (вже закінчують). 
Обіцяли завтра обробити.
Вибачаюсь за ситуацію та дякую за розуміння.
З повагою, Август.

**Comment by agerman-ua** [comment]
Доброго дня, @OBezdietko 
По-перше. Вас зареєстрували. Можете безкоштовно перевірити на порталі мінюсту https://usr.minjust.gov.ua/ua/freesearch/.
По-друге. Термін надання послуги який склався (складеться після закриття урядовцем звернення).
З Вами та ще кількома заявниками склалась унікальна ситуація. Ваши звернення почали обробляти але виконавець-реєстратор відмовилась проводити реєстрацію, оскільки Ви особисто не подавали заяву. Ми намагалися переконати її - на це окремо пішло майже чотири тижні. :( До того ж цей реєстратор призупинив Вашу реєстрацію і ми не могли просто передати Ваше звернення до іншого, "більш прогресивно налаштованого" виконавця. Навіть якщо б Ви подали нове звернення на порталі. 
Нарешті після того, коли вдалося зняти призупинення ми відразу передали Ваше електронне звернення до іншого ЦНАПу (тиждень тому), але їх раптово переселили на іншу адресу, тому жодного звернення не оброблялося під час переїзду. Вчора вони остаточно переселилися і реєстратор провів свої дії. 
У будь-якому випадку вибачаюсь за незручності під час надання послуги. 
Багато тексту привів тільки для того щоб мої слова про унікальність ситуації були хоч чимось підтверджені.
Бажаю успіхів в бізнесі.
З повагою, Август.
