### ISSUE TITLE
Звернення № 0-444209136  Державна реєстрація змін до відомостей про фізичну особу – підприємця

### ISSUE THREAD

**Issue by 5018870** [e-government-ua/iForum#575]
Заявка подана 26.07.2016 р. о 03:35  вже дві доби статус заявки -  "В обробці.  Заявка подана - Перевірка наданих даних (1)".  
Вона хоч попала до реєстратора? Там всього лише зміна місця проживання. Як довго оброблятиметься заявка? Чи є сенс очікувати далі? 
На відміну від цієї заявки, попередня заявка на реєстрацію місця проживання була оброблена на протязі декількох годин, вибрана дата відвідування реєстратора, а сама реєстрація зайняла 10 хвилин, за що команді iGov велика подяка.

**Comment by agerman-ua** [comment]
Доброго дня, @5018870 
Дуже радий за позитивний відгук про отриману раніше послугу.
У послугах повязаних з держреєстром трохи інакше побудовано процес.
Ви отримаєте послугу повністю онлайн, нікуди йти не треба.
Оріентовно послуга надається протягом 5-7 діб. 
Після перевірки Ви отримаєте або листа з мотивованою відмовою, або лист з кнопкою для сплати онлайн.
З повагою, Август.

**Comment by 5018870** [comment]
Дякую. 
Було б непогано якби під час формування заявки, хоча б орієнтовно, вказувався термін її розгляду. 
Бо через деякий час після подачі звернення не зрозуміло чи воно десь в черзі, чи десь загубилося і потрібно подавати вдруге.
Та й питань би менше люди надсилали :) 
З повагою, Ярослав.

**Comment by agerman-ua** [comment]
Ми звичайно працюємо над ще більш зручною інформаційною підтримкою громадян порталом, це дуже цікава, корисна та нескінченна :) справа. І для цього нам дуже потрібні питання людей, щоб впевнитись що буде корисно а що зайве. 
Але точно та принципово можу сказати що нічого на порталі не губиться. :)
Так що пишіть. Це не буде зайвим.
З повагою, Август.
