### ISSUE TITLE
Звернення № 0-440076935 - Перереєстрація транспортного засобу на нового власника за договором купівлі-продажу

### ISSUE THREAD

**Issue by sabretus** [e-government-ua/iForum#576]
Система написала що заявка прийнята, пройшло 2 дні але реакції немає, статус залижається "в обробці". Як дізнатись скільки потрібно часу на обробку? Дякую. Існують якісь телефони куди можна подзвонити і запитатись ?

м. Львів. 
МРЕВ на Данила апостола.

Наперед дякую за відповідь.

**Comment by sabretus** [comment]
Люди! А-у! Я отримав відповідь на свій лист з пропозицією оплатити державний збір, але ні реквізитів ні розміру оплати немає, де мені його взяти !? Допоможіть будь ласка!

**Comment by kurbpa** [comment]
@sabretus 

В письме по идее  должен быть файл со всеми реквизитами для оплаты.

**Comment by sabretus** [comment]
![screen shot 2016-07-28 at 5 01 45 pm](https://cloud.githubusercontent.com/assets/3483923/17215226/d41c12c2-54e4-11e6-8dd6-76dd0994ef5f.png)

Ось так виглядає лист, я на всякий випадок попробував його відкрити не тільки в Chrome (Version 52.0.2743.82 (64-bit)) але і в Firefox (47.0.1). Ні вкладок ні лінків не видно

**Comment by sabretus** [comment]
Є лист в поштовій скринці, сорі, туплю

Дякую величезне
