### ISSUE TITLE
Має бути чітко прописаний мінімайльнй і максимальний термін для обробки заявки

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#577]
Надійшло таке зауваження:

> Lev Petrushchak:
> Має бути чітко прописаний мінімальний і максимальний термін для обробки заявки, і він має бути вказаний в формі подачі, без цього вся ця система не працюватиме

https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1735382073417335&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by Koffeek** [comment]
@VadymVolos прохання додати у https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&theater цей пост посилання на форму для громадян (https://docs.google.com/forms/d/e/1FAIpQLScUAB7YbehGAvVcZW0W7NOwlLbcT1vHOBxzDt3Rp0cMewGpLA/viewform), бо для багатьох Гітхаб трохи заскладний. Дякую

**Comment by VadymVolos** [comment]
@Koffeek ок, додати можна. Але э декілька пропозиції

1. Можливо лінк на цю формі слід ще додати у особистому кабінеті біля тексту "заявку в обробці", і зразу коли будуть запитання людина зможе написати.

2. Ви впевнені що приймати запитання по формі гарна ідея? Чому запитую, раніше була форма для запитань, на неї надходило стільки запитань що не було кому відповідати і її закинули. У запитання через форму є недоліки, якщо людина помилиться в одній букві свого емейл, конфіденційна інформація може надійти не тій людині, або людина буде чекати відповідь і так і не отримає тому що при заповнені емейл вписала з помилкою.

**Comment by Koffeek** [comment]
1. Лінк знаходиться зараз у футері і має назву "Маю питання щодо мого звернення" 
2. Раніше ми не знали, хто мав доступ до тієї форми, до того ж вона більше призначалась для волонтерів, ніж для громадян. Наразі ми зробили її саме для відповідей по зверненнях і активно працюємо з новою формою. Помилки у написанні емейлу звичайно виключити неможна, але тут власне людині потрібно проявити уважність. До того ж ми не скасовуємо канал комунікації на ГітХабі.

**Comment by VadymVolos** [comment]
@Koffeek ок, лінк вже додали. Це звернення я закриваю, відповідь вже дели на фейсбуці, дякую всім за допомогу!
