### ISSUE TITLE
Скажите когда будет помощь при рождении ребенка доступна в Киеве?

### ISSUE THREAD

**Issue by bulya** [e-government-ua/iForum#578]
Скажите хоть примерно? стоит ли вопрос на повестке?
В собес-ах  очереди и бюрократия просто убивают...
Вся надежда на вас))) Могу помочь Python/JS =)

**Comment by zolotovatatyana** [comment]
Здравствуйте!
Пока что это скорее политический вопрос, чем технический. Нужна добрая воля местных властей, а ее пока нет. 
_Питоном их разве что придушить можно ))))_

**Comment by Maestra86** [comment]
конечно нет доброй воли.
оформляла помощь на Янтарной - заявление купи, кучу ксерокопий за деньги наделай у них же, в очереди пару часов постой, хотя звонила и записывалась за полтора месяца (!!!!!!!!).
хорошо что у меня муж с грудничком в это время гуляли на улице, а многие мамы, которым так же по телефону сказали, что они попадут в кабинет в четко определенное время, пришли одни с детьми, которые изнывали от жары, духоты и трехчасового ожидания в узком страшном коридорчике в древнем здании на краю стремного переулка возле Окружной.

**Comment by zolotovatatyana** [comment]
@Maestra86 очень много волонтеров работают над как можно скорейшим продвижением iGov во все структуры. Будем надеяться на скорейшее разрешение всех вопросов
