### ISSUE TITLE
Скарга, не внесли місто

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#579]
Надійшла така скарга:
> Ирина Гаспар‎
> Ваши сотрудники (конкретно Чміль І.Б.)отвратительно относятся к своим обязанностям, по моей заявке забыли внести город (заявка 0-290554913). Теперь я не знаю куда платить налоги. Для чего я посылала скан паспорта? Услуга: внесение изменений в реестр ФОП.На мои просьбы разобраться - не реагируют! Теперь всем советую не пользоваться этим ресурсом!

https://www.facebook.com/igov.org.ua/posts/1735522280069981
https://www.facebook.com/gasparira

**Comment by agerman-ua** [comment]
Зранку будемо розбиратися. Дякую.

**Comment by agerman-ua** [comment]
Проблема пов'язана з відсутністю декомунізованих назв районів у довідниках программи в якій працюють реєстратори. Будемо змінювати.

**Comment by agerman-ua** [comment]
Питання вирішено. 
Зміни безкоштовно внесені до реєстру.
Всім причетним дякую.
З повагою, Август.
