### ISSUE TITLE
Помощь при рождении ребенка

### ISSUE THREAD

**Issue by tatianarybalka** [e-government-ua/iForum#58]
Здравствуйте!посмотрите, пожалуйста, результат по заявке №9173042. Заявка была подана 16.10.2015, но результат на электронную почту так и не пришел. Заранее благодарна!

**Comment by tatianarybalka** [comment]
Выбирала Петриковский район

**Comment by dmitrijzabrudskij** [comment]
добрый день. посмотрят, спасибо за сигнал

**Comment by tatianarybalka** [comment]
Спасибо, буду ждать!
