### ISSUE TITLE
Нет района в списке

### ISSUE THREAD

**Issue by liosharp** [e-government-ua/iForum#580]
Заказываю услугу по вклеиванию фото в паспорт по достижению возраста.
В списке ДМС нет Ленінського (ныне Новокодацького) РВ у м. Дніпропетровську. Не заполняя это поле (не выбирая значение из списка) - в заявке устанавливается первый по алфавиту район, совсем не тот.
И что выбирать и что делать тогда? Как быть?

**Comment by Koffeek** [comment]
@liosharp Новокодацкий район только недавно дал согласие на прием граждан по этой услуге. Завтра ночью добавим на портал. В среду сможете подать заявку.
