### ISSUE TITLE
Кнопка "Скасувати заявку!" не работает.

### ISSUE THREAD

**Issue by kraina** [e-government-ua/iForum#581]
Невозможно удалить себя из очереди на получение загран. паспорта, если что-то поменялось и не сможешь прийти. Вместо меня мог пойти получить паспорт другой человек, но функция "Удалить меня из очереди" не работает и ваши программисты знают об этом. Причина, почему не работает эта функция мне видится в том, что информацию о клиенте из письма клиента на сайт igov.org.ua программисты пытаются передать через адресную строку (так передают данные из формы методом GET), но в форме на отправку стоит метод POST <form method="POST" ... Я, конечно, не вижу весь ваш код и не знаю ваши идеи, примеры GET POST здесь https://github.com/e-government-ua/i/issues/720#issuecomment-236177666

**Comment by Koffeek** [comment]
@kraina Добрый день, подскажите, пожалуйста, номер заявки, когда и в какое подразделение подавали? Я лично проверяю раз в неделю. у меня отрабатывает.

**Comment by kraina** [comment]
0-403943140 - Днепропетровск, Шевченківський (Бабушкинский) р-н - 26.07.16 11-15
"Прийти за адресою: м. Дніпро, пр. П.Орлика (пр. Ілліча), 3 з необхідними документами.
Деталі зустрічі:
День та час - 2016-07-26 11:15:00.00" 
Потом где-то 20.07.16 пыталась удалить себя из очереди, но получаю пустую белую страницу с текстом ошибки {"code":"SYSTEM_ERR","message":null}. 
Себя из очереди удалить не получилось, поэтому мне пришло 25.07.16 письмо: "Чекаємо Вас за адресою: м. Дніпро, пр. П.Орлика (пр. Ілліча), 3
для оформлення закордонного паспорта

Дата та час візиту: 2016-07-26 11:15:00.00.

Реквізити для сплати держмита та адміністративної послуги доступні за посиланням Зверніть увагу: В квитанції дані платника повинні бути написані українською мовою, а також ..."

Gif картинка и описание проблемы можно посмотреть здесь: http://dnipro.ucoz.net/igov/BugReport_20160720_International_Passport_Task_Can.html

**Comment by Koffeek** [comment]
@kraina Спасибо за такой подробный ответ. Я передам программистам. Возможно эту ситуацию уже устранили, т.к. я отменял заявки на прошлой и позапрошлой неделе без каких-либо проблем.
