### ISSUE TITLE
2 МЕСЯЦА В ОБРАБОТКЕ Звернення № 0-289154768 

### ISSUE THREAD

**Issue by Polietaiev** [e-government-ua/iForum#582]
Последнее сообщение:
 
"01.06.2016 18:25 
 
Ви подали заявку на послугу Київська ДМС - Реєстрація місця проживання/перебування особи. Cтатус: Формування пакету документів для ДМС"

- если нет возможности обработать, то отмените заявку.

**Comment by Koffeek** [comment]
@Polietaiev К сожалению чиновники из Киева на данный момент не обрабатывают заявки с портала, поэтому услуги будут закрыты. Приносим свои изменения.
