### ISSUE TITLE
Подал заявку на регистрацию ФОП, но без заявки на упрощенку.

### ISSUE THREAD

**Issue by Ceperrra** [e-government-ua/iForum#583]
Подал заявку на регистрацию ФОП.

Думал - сначала зарегистрироваться и сразу после этого перейти на упрощенку. 

Для перехода на упрощенную систему мне надо создать снова заявку на регистрацию фоп? Или только ехать в налоговую?

Была сноска что потом я могу добавить нужные документы, а так как большинство граф в файле заявки на упрощенку были пустые, решил что нужно ее подавать в процессе, на IGOV. когда получу полную информацию.

**Comment by Ceperrra** [comment]
Было указано что потом я могу добавить нужные документы, а так как большинство граф в заявке были пустые, решил что нужно ее подавать в процессе, на IGOV.

**Comment by agerman-ua** [comment]
Добрый день, @Ceperrra 
Нет, после регистрации ФОП все последующие заявки на регистрацию будут закрыты по причине состоявшейся регистрации. По закону только в сам момент регистрации можно (определившись с системой налогообложения) воспользоваться "упрощением" подав документы и на регистрацию и на учет в налоговую в одном месте. Именно это отражается в заявлении на регистрацию. Там стоят отметки о наличии файлов с соответствующим заявлением в налоговую.
Сейчас Вам, для того чтобы сменить общую систему налогообложения на другую, действительно необходимо ехать в налоговую. Пока налоговая не предоставляет подобные услуги через наш портал.
Постараемся, в дальнейшем, учесть выявленную с Вашей помощью неоднозначность формулировки про добавление документов. 
С уважением, Август.

**Comment by Ceperrra** [comment]
Спасибо за разъяснения, как всегда "дурная голова ногам покоя не даёт". Мог изначально сюда обратиться:)

**Comment by agerman-ua** [comment]
@Ceperrra 
Очень жаль что непонятно было с самого начала.
Но с таким положительным, спокойным и философским отношением к жизни Вам нипочём любые препоны. Желаю удачи.
С ув. Август.
