### ISSUE TITLE
Питання по заявці на отримання закордонного паспорту

### ISSUE THREAD

**Issue by SaffoF** [e-government-ua/iForum#584]
Добрий день!
Як дізнатись дату отримання закордонного паспорту по заявці  0-232622888 ? 
Обіцяний термін пройшов, а сповіщення про те, що документ готовий, не надійшло.

м. Дніпропетровськ
Державна міграційна служба у Дніпропетровській області

Дякую.

**Comment by Koffeek** [comment]
@SaffoF Портал не надсилає сповіщення про готовність документу. Ми лише забзпечуємо можливість подати документи. Стан готовності закордонного паспорту Ви можете перевірити самостійно на сайті ДМС України (https://dmsu.gov.ua/perevirkastanu.php). Якщо там написано, що паспорт готовий, то можна йти до підрозділу, де подавали заяву, та забирати.
