### ISSUE TITLE
Скільки часу займає додавання кведу ФОП? Звернення № 0-461602015

### ISSUE THREAD

**Issue by Paicynet** [e-government-ua/iForum#585]
Доброго дня! Скажіть, будь ласка, скільки часу обробляється заявка на додавання кведу? Звернення № 0-461602015

**Comment by agerman-ua** [comment]
Доброго дня, @Paicynet.
Станом на цей час, в середньому по цій послузі, від 7 до 10 діб. Певний час звернення знаходиться в загальній черзі з якої попадає в обробку до урядовця.
З повагою, Август.
