### ISSUE TITLE
Проблема со входом через BANK ID

### ISSUE THREAD

**Issue by Piret12353** [e-government-ua/iForum#586]
Здравствуйте. Не получается зайти на сайт через Приват 24.  Выдает ошибку сразу после ввода кода из СМС. Может ли это быть связано с отсутствием ИНН у человека?

**Comment by Piret12353** [comment]
Выдает такую ошибку:

An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by Koffeek** [comment]
@Piret12353 Представители банка говорят. что это связано с отсутствием ИНН. Извините, что так долго отвечали, ждали их комментария.
