### ISSUE TITLE
Відміна заявки

### ISSUE THREAD

**Issue by Paicynet** [e-government-ua/iForum#587]
Доброго дня! Можна пошвидше відмінити Звернення № 0-461602015, або провести його. Бо мені терміново треба. А у вас треба чекати 7-10 днів. 
Я би хотіла зробити це через реєстратора. Але там заблокована вами картка. І ніякі дії не можуть бути проведені.

**Comment by agerman-ua** [comment]
Доброго дня, @Paicynet 
Вам не треба відміняти Ваше звернення, так як вже дії по внесенню змін почались і не пізніше ніж завтра все буде готово.
З повагою, Август.

**Comment by Paicynet** [comment]
Добре, дякую! 
Буду чекати.

**Comment by GrekD** [comment]
позитивне рішення по зверненню
