### ISSUE TITLE
Звернення № 0-452087329

### ISSUE THREAD

**Issue by Mentrix** [e-government-ua/iForum#589]
Прошло 5 дней, никакого движения,хотя было написано при подаче заявки,что заявку обрабатывают 1-3 дня,заявка до сих пор в обработке,так пишет в журнале... За это время приходила смс,что заявка обработана,ожидаем визит,детали в вашем журнале или эмейл..Захожу в журнал,пишет в обработке,там ничего нету,куда спрашивается визит? Ни адреса ничего нету,на вопрос что с моей заявкой,представитель данной службы не отвечает,глухо как в танке..На эмейл прислали бланки те что я заполнял при  подаче заявки,но никаких инструкций там нету вообще,ни адреса куда обращаться и что делать..Что с моей заявкой непонятно вообще,обработана она или нет,что делать дальше,куда ехать и с чем,какие документы нужны??? Вообще ничего не продумано у вас.....

**Comment by Koffeek** [comment]
@Mentrix Вам на почту mentrix@i.ua должно было прийти письмо с подтверждением визита, адресом для явки, реквизитами для оплаты админсбора и списком необходимых документов, а также формами заявлений для печати. Возможно оно находится в папке "Спам". Если на почте письма нет, напишите, пожалуйста, - я отправлю его ещё раз.

**Comment by Mentrix** [comment]
В папке Спам ничего нету...

**Comment by Koffeek** [comment]
@Mentrix Продублировал письмо на почту.

**Comment by Mentrix** [comment]
@Koffeek Спасибо за помощь..
