### ISSUE TITLE
Вопрос по заявке

### ISSUE THREAD

**Issue by ur5evw** [e-government-ua/iForum#59]
Заявка 9231872. 
Пришел ответ:
На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг відхилене через недостатню або неправильну інформацію..
Причина: Потрібно заповнити всі поля форми. Без цього подальша обробка не можлива
Звертаємо увагу, Ви можете заповнити заявку повторно на порталі iGov.org.ua

Прошу уточнить какие поля формы небыли заполнены?
Повторно заполнил заявку 13647360, прошу проверить правильность заполнения.

**Comment by dmitrijzabrudskij** [comment]
какой район?

**Comment by ur5evw** [comment]
г.Желтые Воды

2015-11-04 23:23 GMT+02:00 dmitrijzabrudskij <notifications@github.com>:

> какой район?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iForum/issues/59#issuecomment-153869767>
> .
>



-- 
Лягушин Вячеслав Валериевич
+380970093518
+380954020871
