### ISSUE TITLE
Зявка 0-346729354

### ISSUE THREAD

**Issue by SidorenkoI** [e-government-ua/iForum#590]
Добрый день!
23.06.16 оставила заявку на послугу Призначення соціальної допомоги при народженні дитини. 01.07.16 мне прислали ответ: "Необхідно уточнити дані, за коментарем: необхідно надати заяву з банку про відкриття соціального рахунку". 02.07.16 я прикрепила файл - фото заявления с банка. И с тех пор тишина. 24.07.16 я спросила о статусе моей заявки, но так же тишина. Когда будет ответ? Вообще моей заявкой кто-то занимался? Где можно получить ответы?

**Comment by SidorenkoI** [comment]
тут тоже тишина... Глядя на другие заявки, отвечают быстрее. День в день.

**Comment by zolotovatatyana** [comment]
@SidorenkoI  Здравствуйте! 

Ваша заявка находится в работе у УПСЗН АНД района. Заявка уже переведена на второй этап 04/08.  Скоро должен быть результат.

**Comment by SidorenkoI** [comment]
Спасибо. А скоро - это когда?

**Comment by zolotovatatyana** [comment]
Как только чиновники подготовят Ваше Дело к передаче в расчетный центр.

**Comment by SidorenkoI** [comment]
спасибо
