### ISSUE TITLE
не подписалась заявка 

### ISSUE THREAD

**Issue by olchikb** [e-government-ua/iForum#591]
добрый день пыталась сегодня два раза написать одну заявку ( гос регистрация юр лица ) дохожу до момента эцп , файл подтягивает, пароль, затем подвисает и неизвестная ошибка , прийдется в понедельник к регистратору

**Comment by agerman-ua** [comment]
@olchikb 
Добрый день, спасибо что дали обратную связь, а какой браузер используете?

**Comment by olchikb** [comment]
хром , подпись из налоговой

**Comment by agerman-ua** [comment]
Добрый день, @olchikb 
Хром это правильно, да и подпись норм.
Так и не смогли воспроизвести озвученную ситуацию.
Если есть желание повторить, или осталась потребность в регистрации - буду очень благодарен.
Просьба только дополнительная - сделать, в таких случаях, снимки экранов с ошибкой и хорошо видимым путём в браузере.
С ув.Август.
