### ISSUE TITLE
заявка 0-456721417 14й день не могу получить ответ. ПОМОГИТЕ ПОЖАЛУЙСТА 

### ISSUE THREAD

**Issue by IgorRazdo** [e-government-ua/iForum#592]
1. подал заявку 0-456721417  28.07.2016 19:48
"Ви подали заявку на послугу Державна реєстрація створення юридичної особи. Cтатус: Надання послуги"
Регистрация ТОВ "СІНЕМА 6К". я в г. Одесса. 
2 .08.08.2016 12:06 Уточнил  когда ожидать ответ  
Запитання/коментар клієнта по заяві 0-456721417
"Добридень! 11 днів тому я подав на реєстрацію ТОВ "СІНЕМА 6К". Повідомьте, будь ласка, у який термін мені чекати на відповідь?"
3. Вчера уточнил сколько ждать в "Маю питання щодо мого звернення".
никаких ответов не было, а  
мне 13 августа НАДО ПОДАТЬ ДОКУМЕНТЫ  в ГОС ФОНД МАКЕДОНИИ НА ПРОИЗВОДСТВО УКРАИНСКО-МАКЕДОНСКО-НЕМЕЦКОГО фильма. ДОКУМЕНТЫ ДОЛЖНЫ БЫТЬ ОТ имени ТОВ "СІНЕМА 6К". ПОМОГИТЕ ПОЖАЛУЙСТА

**Comment by agerman-ua** [comment]
Добрый день, @IgorRazdo .
Уже уточняем статус. 
С ув. Август.

**Comment by IgorRazdo** [comment]
Август, спасибо за  оперативность 
с нетерпением жду 
Игорь

**Comment by IgorRazdo** [comment]
Август, спасибо вам что помогли!
час назад пришел Опис от регистратора.
изготовитель печати утверждает что там должен быть адрес, который мы указывали при регистрации, но его там его нет( 
ну это уже мелочи.
Еще раз большое спасибо. Большое и правильное дело делаете!

Best regards,
Igor Razdorozhnyy 
producer 
CINEMA 6K

e-mail:  R <mailto:R@cinema6k.com>@cinema6k.com <mailto:R@cinema6k.com>
                www.cinema6k.com <http://www.cinema6k.com/>

**Comment by agerman-ua** [comment]
Спасибо и Вам, Игорь, за изначальное доверие. 
Желаю потрясающих успехов Вашей компании.
С ув.Август.
