### ISSUE TITLE
Звернення № 0-444209136  "Державна реєстрація змін до відомостей про фізичну особу – підприємця" подане 26.07.2016

### ISSUE THREAD

**Issue by 5018870** [e-government-ua/iForum#593]
Звернення № 0-444209136  "Державна реєстрація змін до відомостей про фізичну особу – підприємця" подане 26.07.2016  

04.08.2016 0 15:38 на адресу моєї електронної пошти надійшло повідомлення з електронної адреси notifycation@igov.org.ua (Ваше звернення №0-444209136 на тему "Державна реєстрація змін до відомостей про фізичну особу – підприємця" пройшло перевірку.
Для отримання послуги просимо її оплатити.
З повагою,
Команда Порталу державних послуг iGov ) 

04-08-2016 18:08:20 була здійснена сплата адміністративного збору (id платежу: 220014443), а квитанція надіслана через форму "Ваш коментар або звернення до співробітника держ. органу" на сторінці "Мій журнал" порталу iGov .

До цього часу (10.08.2016) статус заявки не змінився і вказаний як:  "Перевірка наданих даних (1)". 

Як довго ще чекати виконання вже СПЛАЧЕНОГО звернення?

Який сенс вказувати на порталі цю послугу як "послугу доступну онлайн", якщо реальні строки її виконання просто не сумісні зі здоровим глуздом, при тому що отримання цієї послуги у звичайний, не онлайн, спосіб можливо здійснити за одне відвідування реєстратора чи нотаріуса?

Якби ця послуга не була вказана як доступна на порталі iGov, то, звернувшись до реєстратора, цю послугу мені б було надано ще 26-27.07.2016р.

Така невизначеність і такі терміни надання послуги зводять нанівець увесь сенс їх отримання за допомогою iGov, що дуже засмучує. 

А ще, вказуючи цю послугу як "послугу доступну онлайн", ви вводите людей в оману, та ставите їх під загрозу протерміновати усі строки проведення Державної реєстрації змін, а відповідно і змін до Реєстру платників єдиного податку, і отримання фінансових санкцій з боку фіскального органу.

**Comment by 5018870** [comment]
Пройшло 5 днів з моменту мого попереднього звернення на форумі. 
Ніякої відповіді стосовно моєї заявки я не отримала. 
Сьогодні (15.08.2016р) статус заявки не змінився і вказаний як: "Перевірка наданих даних (1)". 
Я розумію всі складності роботи з держ. органами, але хіба не можна надати хоча б якусь інформацію стосовно заявки,  якщо Ви вже взялися вести підтримку користувачів iGov?

**Comment by agerman-ua** [comment]
Доброго дня, @5018870 
Вибачте, повинні були опрацювати через добу від Вашого звернення на форум.
Завтра більш точно дам відповідь по строкам.
З повагою, Август.

**Comment by agerman-ua** [comment]
Доброго дня, @5018870 
Прошу вибачення за таку довгу затримку.
У Вашому випадку є проблема загального характеру, на жаль вона досі не вирішилася.
Були підстави очікувати позитивного вирішення ще від самого початку.
З повагою, Август.

**Comment by 5018870** [comment]
Доброго дня, Август.
Дякую за відповідь , але з неї не зрозуміло, що робити далі.
Мною була здійснена сплата адміністративного збору через форму з порталу iGov (id платежу: 220014443 від 04-08-2016 18:08:20).
Що мені робити тепер?
Чи дійсно моє звернення попадало до реєстратора?
Яким чином можливо відмінити послугу?
Куди мені звернутися для відміни платежу за послугу (TaskActiviti_44420913) і повернення коштів? Або, якщо кошти вже були перераховані до казначейства, як мені отримати квитанцію, щоб використати її при поданні нового звернення до реєстратора на паперовому носії?

**Comment by agerman-ua** [comment]
Доброго дня, @5018870 
Зараз, з Вашого боку ніяких дій не очікується.
Сплату в системі видно.
Звернення Ваше дійсно було перевірено держслужбовцем, внаслідок чого Ви і отримали листа з кнопкою для сплати.
На цьому етапі вже відміняти звернення не треба.
Щодо квитанції. Її Ви могли отримати на свою пошту під час проведення операції сплати.
Ще раз наголошую, зачекайте. 
Думаю Ваше питання вирішиться сьогодні-завтра або у будь-якому випадку на цьому тижні.
З повагою, Август.

**Comment by GrekD** [comment]
Заява розглянута, прийнято позитивне рішення
