### ISSUE TITLE
есть ли услуга по проверки авто в розыске или аресте?

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#594]
столкнулся тут с проблемой такой.

в 2013 был Административный протокол. потом оказалось, что по нему приходили сумма на оплату и потом дело было передано в исполнительную службу. а исполнительная служба подала мое авто в розыск (еще в ноябре 2013 года). ну я об этом соответственно не в курсе, потому что никаких уведомлений не получал.

как понимаю теперь на постах полиции стоят камеры с распознаванием номеров и теперь на каждом посту тормозят.

штраф уже оплачен (+ затраты исполнительной службы), дело закрыто. письмо о снятии ареста получено. но когда оно попадет в полицию и когда снимут арест - НЕПОНЯТНО.

так вот вопрос - есть ли услуга по проверки авто в розыске?

прискорбно во всем этом и то, что розыск (арест) по авто **НЕ** отображается в Едином реестре обременений на движимое имущество!!!

**Comment by kurbpa** [comment]
@AndreyPopovNew 

Пока такой услуги нет.
Но будем пробовать запустить обязательно.

**Comment by AndreyPopovNew** [comment]
прискорбно,... придется брать письмо исполнительной службы и ножками топать в полцию для выяснения когда же они снимут розыск.
