### ISSUE TITLE
Нажаль, в електронній черзі тимчасово відсутні вільні місця

### ISSUE THREAD

**Issue by Stagest** [e-government-ua/iForum#595]
Місяць часу немає вільних дат в поданні документів на закордонний паспорт дитині? Таке взагалі можливо? 2 рази на день одну і ту ж процедуру роблю і "Нажаль, в електронній черзі тимчасово відсутні вільні місця" . я можу стати не на електронну чергу шоб подати документи для дитини?З якої дати стають чи відкриваються черги

**Comment by Koffeek** [comment]
@Stagest Какой населенный пункт или район выбираете? Возможно стоит посмотреть соседние районы.

**Comment by Stagest** [comment]
Тернопіль. Вул.коновальця. черги нема ніводному з тернопільських відділів

**Comment by Koffeek** [comment]
@Stagest По Тернополю ситуація така. Відкриваються слоти на наступний місяць десь 25-27 поточного. В них є 6 людей на добу. Оскільки сервіс популярний, то слоти вибирають за 3-4 години на увесь місяць. Якщо Ви залишите свій е-мейл, то можемо надіслати повідомлення перед відкриттям черги на вересень.

**Comment by Stagest** [comment]
stagest@ukr.net

**Comment by GrekD** [comment]
@Koffeek  не забудь ))

**Comment by Stagest** [comment]
дякую.став на чергу. куда шоколадку відправити?

**Comment by GrekD** [comment]
це вже корупція ))
удачі!
