### ISSUE TITLE
Не работает загрузка изображений в заявке на оформление помощи по рождению ребенка и из за этого невозможно оформить заявку

### ISSUE THREAD

**Issue by aalextr** [e-government-ua/iForum#597]
Лог ошибки находится на фейсбуке
<iframe src="https://www.facebook.com/plugins/comment_embed.php?href=https%3A%2F%2Fwww.facebook.com%2Figov.org.ua%2Fphotos%2Fa.1601562290132648.1073741827.1589199384702272%2F1623034644652079%2F%3Ftype%3D3%26comment_id%3D1741909562764586%26reply_comment_id%3D1742346472720895&include_parent=false" width="560" height="181" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

**Comment by zolotovatatyana** [comment]
Спасибо за сигнал, разбираемся.

**Comment by zolotovatatyana** [comment]
Уже работает. Попробуйте подать снова, пожалуйста.

**Comment by aalextr** [comment]
Повторная попытка (после сообщения: Уже работает. Попробуйте подать снова, пожалуйста.)
Помилка по операції: 'Сабміт форми послуги'
Помилка при запиті!

Час: "2016-08-17T10:36:06.003Z" , Функція: submitForm
Відповідь сервера:
Код: SYSTEM_ERRІнші дані (обь'єкт): {"code":null,"message":null}
Значення параметрів:
nID_Service: 752,nID_ServiceData: 350,processDefinitionId: socialhelp_kidsUkraine:1:1,

**Comment by zolotovatatyana** [comment]
Ошибку устранили
