### ISSUE TITLE
Призначення соціальної допомоги при народженні дитини - ошибка

### ISSUE THREAD

**Issue by eugene-fedko** [e-government-ua/iForum#598]
Заполняю все поля, загружаю сканы, подключаю приватовский BankId.
Текст ошибки:
*личные данные заменены на *******
Помилка по операції: 'Сабміт форми послуги'
Помилка при запиті!

Час: "2016-08-14T14:25:35.511Z" , Функція: submitForm
Відповідь сервера:
Код: SYSTEM_ERRІнші дані (обь'єкт): {"code":null,"message":null}
Значення параметрів:
nID_Service: 752,nID_ServiceData: 350,processDefinitionId: socialhelp_kidsUkraine:1:1,saField: [{"sID":"sID_Public_SubjectOrganJoin","sType":"select","sValue":"s5"},{"sID":"bankIdlastName","sType":"string","sValue":"*******"},{"sID":"bankIdfirstName","sType":"string","sValue":"АННА"},{"sID":"bankIdmiddleName","sType":"string","sValue":"ЮРІЇВНА"},{"sID":"bankIdbirthDay","sType":"string","sValue":"27.02.1986"},{"sID":"bankIdPassport","sType":"string","sValue":"********"},{"sID":"bankIdinn","sType":"string","sValue":"*********"},{"sID":"adress1","sType":"string","sValue":"*******"},{"sID":"adress2","sType":"string","sValue":"м. Дніпропетровськ, ******"},{"sID":"email","sType":"string","sValue":"********"},{"sID":"bankId_scan_passport","sType":"file","sValue":{"id":"7531d58e-7bcd-4bcc-9c52-748e18d39595","signInfo":null,"fromDocuments":false}},{"sID":"inn_scan","sType":"file","sValue":{"id":"4f027121-27d5-4e28-a808-4926b493fe0f","signInfo":null,"fromDocuments":false}},{"sID":"birthdocument_scan","sType":"file","sValue":{"id":"b76ef582-cbc2-4e0a-8910-71951a7c344b","signInfo":null,"fromDocuments":false}},{"sID":"transfer_type","sType":"enum","sValue":"attr2_bank"},{"sID":"post_office","sType":"string","sValue":"-"},{"sID":"bank_name","sType":"string","sValue":"ПАТ КБ \"ПРИВАТБАНК\""},{"sID":"bank_mfo","sType":"long","sValue":"305299"},{"sID":"bank_okpo","sType":"long","sValue":"******"},{"sID":"bank_account","sType":"long","sValue":"*********"},{"sID":"bankticket","sType":"file","sValue":{"id":"21025ce2-9daa-4e20-a764-3a1e06a44801","signInfo":null,"fromDocuments":false}}],

после нажатия "закрыть" выскакивает второе окошко:
Помилка по операції: 'Сабміт форми послуги'
Повернен пустий об'ект!

Час: "2016-08-14T14:25:35.513Z" , Функція: submitForm(UI)
Значення параметрів:
nID_Service: 752,nID_ServiceData: 350,processDefinitionId: socialhelp_kidsUkraine:1:1,

**Comment by zolotovatatyana** [comment]
Спасибо за сигнал, разбираемся.

**Comment by zolotovatatyana** [comment]
Уже работает. Попробуйте подать снова, пожалуйста.

**Comment by eugene-fedko** [comment]
Все по-прежнему:

Помилка по операції: 'Сабміт форми послуги'
Помилка при запиті!
 
Час: "2016-08-17T08:33:20.980Z"   , Функція: submitForm
Відповідь сервера:
Код: SYSTEM_ERR Інші дані (обь'єкт): {"code":null,"message":null}
Значення параметрів:
nID_Service: 752, nID_ServiceData: 350, processDefinitionId: socialhelp_kidsUkraine:1:1, saField: [{"sID":"sID_Public_SubjectOrganJoin","sType":"select","sValue":"s5"},{"sID":"bankIdlastName","sType":"string","sValue":"*******"},{"sID":"bankIdfirstName","sType":"string","sValue":"АННА"},{"sID":"bankIdmiddleName","sType":"string","sValue":"ЮРІЇВНА"},{"sID":"bankIdbirthDay","sType":"string","sValue":"27.02.1986"},{"sID":"bankIdPassport","sType":"string","sValue":"*******"},{"sID":"bankIdinn","sType":"string","sValue":"3146905227"},{"sID":"adress1","sType":"string","sValue":"Дніпропетровська обл., Дніпропетровський р-н, ********"},{"sID":"adress2","sType":"string","sValue":"м. Дніпропетровськ, п*******"},{"sID":"email","sType":"string","sValue":"anna_videmeer86@mail.ru"},{"sID":"bankId_scan_passport","sType":"file","sValue":"c44c45eb-82ad-4cd9-8df3-d45d0258dc2e"},{"sID":"inn_scan","sType":"file","sValue":{"id":"ff623a0c-e1fa-4368-9d9d-af3ede511a82","signInfo":null,"fromDocuments":false}},{"sID":"birthdocument_scan","sType":"file","sValue":{"id":"ad1aceeb-88a0-451a-8fd0-018376be0c49","signInfo":null,"fromDocuments":false}},{"sID":"transfer_type","sType":"enum","sValue":"attr2_bank"},{"sID":"post_office","sType":"string","sValue":"-"},{"sID":"bank_name","sType":"string","sValue":"ПАТ КБ \"ПРИВАТБАНК\""},{"sID":"bank_mfo","sType":"long","sValue":"*****"},{"sID":"bank_okpo","sType":"long","sValue":"*****"},{"sID":"bank_account","sType":"long","sValue":"*******"},{"sID":"bankticket","sType":"file","sValue":{"id":"0498d599-a93a-480f-bd7c-b241bc6d1387","signInfo":null,"fromDocuments":false}}],
и дальше
Помилка по операції: 'Сабміт форми послуги'
Повернен пустий об'ект!
 
Час: "2016-08-17T08:33:20.981Z"   , Функція: submitForm(UI)
Значення параметрів:
nID_Service: 752, nID_ServiceData: 350, processDefinitionId: socialhelp_kidsUkraine:1:1,

>Среда, 17 августа 2016, 9:40 +03:00 от zolotovatatyana <notifications@github.com>:
>
>Уже работает. Попробуйте подать снова, пожалуйста.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .




**Comment by zolotovatatyana** [comment]
Ошибку устранили
