### ISSUE TITLE
Чому послуга раптом не працює для Дніпра?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#599]
Надійшло таке запитання:
Чому послуга раптом не працює для Дніпра?

https://www.facebook.com/photo.php?fbid=1257095840967897&set=p.1257095840967897&type=3&theater

![1](https://cloud.githubusercontent.com/assets/12669290/17661470/0927964c-62e8-11e6-964b-a132b92d7e39.jpg)

**Comment by Koffeek** [comment]
@VadymVolos ответил под постом в ФБ
