### ISSUE TITLE
Потрібен механізм збереження та редагування заяв

### ISSUE THREAD

**Issue by katebutenko** [e-government-ua/iForum#6]
Зараз можливо тільки заповнити заяву за 10 хвилин та відправити. Не можна відредагувати вже відправлену (це може бути і правильно). Але потрібен бути механізм, що дозволяє користувачу зберегти заяву та повернутись до її заповнення пізніше. І відправити тільки коли всі поля будуть заповнені та документи завантажено.

**Comment by katebutenko** [comment]
також не можна досилати документи до вже надісланої заяви, якщо щось забув. Тільки робити нову. А також немає механізму видалення помилково доданого файлу, можна тільки замінити його іншим. 
Ці всі механізми потрібно доробити для зручності користувачів.

**Comment by Doxtyp** [comment]
А где и как можно узнать номер заявки?

**Comment by LamronNu** [comment]
@Doxtyp 
номер заявки указывается в последнем окне после нажатия кнопки "замовити послугу" (что-то типа "Ваша заявка №___ успешно зарегистрирована!"
плюс он приходит в письме на указанный Вами е-мейл: http://prntscr.com/8npjah

**Comment by Doxtyp** [comment]
Вот где тут Вы номер заявки видите? Просто я не знаю как мне поступать
дальше: я могу заполнить бумажный вариант и отправить почтой
рекомендованной, НО, если электронная заявка всё же существует и находится
на оформлении? Что тогда?
 Кто может проверить статус заявки на сайте? Ни одного телефона или адреса
эл.почты для обратной связи 😧.
Подскажите, пожалуйста, к кому обратиться?
Заранее благодарю,
Юрий 0688575102; doxtyp70@gmail.com

4 октября 2015 г., 21:38 пользователь Olga P. <notifications@github.com>
написал:

**Comment by LamronNu** [comment]
Номер заявки на скриншоте выделен, по этому номеру можно искать её состояние в разделе Статусы: https://igov.org.ua/order/search
У Вас же есть этот номер? шести- или семизначное число должно быть..
По остальному -- уточняю, но, скорей всего, нужно знать название услуги и сам номер заявки, чтобы разобраться. Отпишусь, какая информация еще нужна.

Насчет обратной связи -- над этим работаем. Проект в пилоте, поэтому не все функции пока доступны.

**Comment by bvv4ik** [comment]
@Doxtyp да, @LamronNu все верно сказала, можете узнать состояние заявки на:
https://igov.org.ua/order/search
введя там номер Вашей заявки (который так-же должен был прийти к Вам на электронный адрес)

а по поводу обратной связи(точнее возможность правок своих заявок) - реализация идет полным ходом. осталось реализовать две задачи из шести. скоро будет)

**Comment by Doxtyp** [comment]
@bvv4ik и @LamronNu Еще раз заявляю: № заявки на е-мэйл не приходит!!!
7 октября я повторно подавал заявку на субсидию - её номер высветился на последнем этапе подачи. Я записал его ручкой в блокнот, т.к. в пришедшем е-мэйл номер не УКАЗАН. И заявка называется "звернення". Это второй раз происходит. Из-за такого пустяка я потерял месяц времени. Но мне непонятно одно: почему Вы не можете проверить наличие "Номера" в е-мэйле вместо того, чтобы убеждать меня в том, что он {"так-же должен был прийти к Вам на электронный адрес"}?
На скриншотах е-мэйлы от 02сен и 07окт:
![ins1](https://cloud.githubusercontent.com/assets/14942871/10383318/03dbf996-6e36-11e5-9b35-03ef10f56184.png)
![ins2](https://cloud.githubusercontent.com/assets/14942871/10383319/03f72bc6-6e36-11e5-83a0-e4c2ecf639ec.png)

**Comment by LamronNu** [comment]
Мы просто говорили о разных письмах..
При создании заявки высылается два письма. В одном (скрин которого я прикрепляла) -- этот номер, такое письмо приходит во всех услугах "автоматом"; второе -- уже Ваше "личное", т.е. что за услуга, ФИО и другая информация по самой заявке.

Судя по всему, письма с номером заявки у Вас не было. Т.е., либо оно попало к Вам в Спам (например), или в какие-то другие папки на почте; либо что-то с самой услугой и там такое письмо не высылается -- этот вариант уточним/перепроверим.

По поводу 
>И еще хотел узнать, если возможно, о количестве поданных на портале заявок на субсидию и количестве рассмотренных положительно, и фактические сроки..

Количество поданных заявок и их рейтинг можно увидеть во вкладке "Статистика" по услуге (https://igov.org.ua/service/654/statistics).
Колонка "рейтинг" сейчас везде 0, т.к. она только сделана, а данных по ней еще нету (т.е. механизм "оценивания" еще в процессе и не запускался).
"фактические сроки" -- тут не подскажу, т.к. отвечаю за разработку..

Судя по вопросу в другой ветке (вроде в #9), Ваш вопрос решен/сдвинулся с места? 

Спасибо за Ваш отзыв.

**Comment by Doxtyp** [comment]
Про два письма первый раз слышу, честно говоря, попадание в спам исключено,
т.к. я всегда просматриваю тщательно (бывает что квитанции приват24
частенько попадают), тем более, что письма я получал на разные адреса
эл.почты.
По поводу:

>
>
> *>>>> Ваш вопрос решен/сдвинулся с места?>> -*


 можно и так сказать (заявку на субсидию подать таки удалось и есть её №),
а по факту просто все сделано заново спустя месяц с хвостиком, в результате
к началу отопительно-"грабительного" сезона не успели и ругаю себя за то,
что поленился отправить по Укрпочте заказным.
​ ​Но уверен, что больше(благодаря Вашей поддержке) проблем не будет.

 И все-таки интересно: кто-то оформил субсидию через портал? есть
первопроходцы?
​*Ещ**е раз спасибо за Ваш труд и успехов!*

>


9 октября 2015 г., 9:50 пользователь Olga P. <notifications@github.com>
написал:

**Comment by dmitrijzabrudskij** [comment]
есть. подавшие в конце августа-начале сентября уже получили назначение. около 100 человек по Днепру.

насчет письма с номером - оно идет с альфа-именем admin@igov.org.ua
попробуйте так поискать у себя в почте

**Comment by nika65** [comment]
Уже несколько раз отправляла заявку на субсидию, были ошибки. Приходил отказ по ошибке. 
ОГРОМНАЯ ПРОСЬБА !!!
Сделайте возможность редактировать прежнюю заявку.
За ранее благодарна.
С уважением, Виктория
