### ISSUE TITLE
Заявка на субсидию нет ответа

### ISSUE THREAD

**Issue by Denisshv** [e-government-ua/iForum#60]
Добрый день.  в журнале запись : 06.10.2015 20:36	Ви подали заявку на послугу Київ МДА - Отримання субсидії на оплату житлово-комунальних послуг!. Cтатус: Заявка подана.
Ответа до сих пор нет, хотя 20 дней истекло. Я не могу понять где смотреть номер заявки.. Вроде все уже облазил..

**Comment by dmitrijzabrudskij** [comment]
добрый день. поищите письмо от admin@igov.org.ua - в нем номер заявки. его Вам отправляли в момент подачи

**Comment by Denisshv** [comment]
Вот ответ из письма номера тоже нет...
Шановний(-а) ....
Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг зареєстроване. Ви отримаєте відповідь протягом 20 робочих днів.

З повагою,
Управління соціального захисту м.Києва
Команда Порталу державних послуг iGov.org.ua

**Comment by dmitrijzabrudskij** [comment]
какую почту указывали при подаче?

**Comment by Denisshv** [comment]
deshvets@gmail.com

**Comment by Denisshv** [comment]
Проверил почту. Письма от  admin@igov.org.ua нет. Скажите как я могу узнать статус моей заявки если нет номера? Извините за беспокойство.

**Comment by sol1210** [comment]
Здравствуйте. 28 августа 2015 я подала заявку на получении субсидии (Селихова В.К.). Сразу пришло письмо о регистрации моей заявки (номер заявки в письме указан не был). 20 дней давно истекли, а никакой информации о моей заявке нет. В каком состоянии заявка, рассмативалась ли, нужно ли заново заполнять форму? И можно ли подавать заявку с ОС Андроид, или только с ОС Windows?

**Comment by dmitrijzabrudskij** [comment]
Денису: номер вашей заявки 6871542. как будет больше информации по ней - напишут в эту ветку

sol1210: дайте почту, с которой Вы отправляли заявку и район, который выбирали при подаче?

**Comment by sol1210** [comment]
Почта olya.sol1210@mail.ru. Красногвардейский район г. Днепропетровск

**Comment by dmitrijzabrudskij** [comment]
28 августа еще не было в списке красногвардейского района. его включили 03.09. подайте заявку заново, пожалуйста

**Comment by sol1210** [comment]
Сейчас у меня нет возможности подать заявку с ОС Windows. А с андроида пыталась с двух разных браузеров, но не получилось. Как подать заявку с андроида? Есть ли приложение, или какой-то конкретный браузер для андроида?

**Comment by Denisshv** [comment]
Добрый вечер по, заявке  6871542 нет больше информации?

**Comment by Ksellos** [comment]
Заявка 7887121. 20 рабочих дней прошло, а статус до сих пор: "Взяти в роботу".

**Comment by dmitrijzabrudskij** [comment]
7887121 - какой район выбирали?

**Comment by Ksellos** [comment]
7887121 - Ленінський, м. Дніпропетровськ.

**Comment by dmitrijzabrudskij** [comment]
она еще в работе у района

**Comment by Doxtyp** [comment]
Здравствуйте! Заявка №7201725 Жовтневый р-н Днепропетровск уже больше месяца как статус "взято в работу" не меняется, письма с отказом не было, помогите выяснить причину задержки

**Comment by GrekD** [comment]
@Doxtyp вопрос еще актуален?

**Comment by Denisshv** [comment]
Вопрос неактуален. 1,5 мес рассматривали...а потом написали вы неправильно
заполнили какие-то данные... Причем непонятно, что заполнено неправильно
и.т.д.  бред полный. Кому нужна такая услуга?

2016-01-19 17:44 GMT+02:00 Darja Grek <notifications@github.com>:

**Comment by sol1210** [comment]
У меня все получилось, хотя из-за ошибок в заполнении пришлось подавать заявку дважды. Услугой очень довольна!!
--
Отправлено из Mail.Ru для Android вторник, 19 января 2016г., 17:52 +02:00 от Denisshv < notifications@github.com> :

**Comment by Doxtyp** [comment]
Актуален частично. Т.е. субсидия назначена, платежи проводятся, но нет
письма, в котором должны быть указаны суммы обязательных платежей и т.д.
Поэтому буду благодарен Вам, если сможете мне его отправить на
doxtyp70@gmail.com
Заранее спасибо!!!

**Comment by dmitrijzabrudskij** [comment]
к сожалению, не могу найти Вашу заявку.. попробуйте перезвонить в район 056 377 08 37 и попросить их повторить отправку

**Comment by Doxtyp** [comment]
Я бы уже сам решил бы вопрос, но я нахожусь за рубежом и разница во времени
неудобная для звонков.

**Comment by Volchkov** [comment]
Доброго дня, подскажите пожалуйста, заявка подана 2015-12-26 14:05:08.740, как долго ждать результат по заявке (0-55836186) ? Контактные номера АНД отделения не отвечают :(
