### ISSUE TITLE
Заявка № 0-493144448

### ISSUE THREAD

**Issue by Elenka021** [e-government-ua/iForum#600]
Доброго дня!
Заявку подано 9.08.2016...до сьогодні статус в обробці. Два рази писала через форму підтримки-теж повна тиша. Допоможіть будь ласка!

**Comment by agerman-ua** [comment]
Доброго дня, @Elenka021 
Не хвилюйтесь. Ваше звернення в роботі у урядовця. Повинні обробити сьогодні-завтра. 
З повагою, Август.

**Comment by Elenka021** [comment]
Добре! 
Дякую!

**Comment by Elenka021** [comment]
Перевірила-так мене вже зареєстровано як ФОП. Але чомусь немає повідомлення за яким маю завантажити виписку.

**Comment by agerman-ua** [comment]
Доброго дня @Elenka021  .
Чекайте на листа з порталу.
В ньому повинно бути вказано код та посилання.
З повагою, Август.
