### ISSUE TITLE
Звернення на тему: Реєстрація нового місця проживання

### ISSUE THREAD

**Issue by Mentrix** [e-government-ua/iForum#601]
Коментар Державного службовця:
РЕЄСТРАЦІЯ МІСЦЯ ПРОЖИВАННЯ БУДЕ ЗДІЙСНЕННА ПІСЛЯ ВЗЯТТЯ НА ВІЙСЬКОВИЙ ОБЛІК.

А якщо в мене у військовому квитку написано,що я знятий з обліку за станом здоров"я! Навіщо тоді мені ставати на військовий  облік???

**Comment by Koffeek** [comment]
@Mentrix Ви додавали сканкопію військового квитка? Можливо реєстратори не додивились. Зараз порядок такий, що кожного відправляють до військомату, тому можливо реєстратори вирішили перестрахуватись

**Comment by Mentrix** [comment]
@Koffeek Не додавав,я думаю на місці можна буде пред'явити копію і орігінал.

**Comment by Koffeek** [comment]
@Mentrix Тоді Вам надали стандартну відповідь. Під час візиту думаю вдастся все владнати.
