### ISSUE TITLE
Звернення  0-507253683

### ISSUE THREAD

**Issue by nv0683952775** [e-government-ua/iForum#602]
Зареєструвався Звернення  0-507253683 прийшов лист який пропонує перейти на "Портал обробки звернень громадян " а я туди не можу зайти! Що робити? на якій стадії знаходиться моя реєстрація?

**Comment by agerman-ua** [comment]
Доброго дня, @nv0683952775 
Цей лист Вас не стосується. Там же відсутнє звернення безпосередньо до Вас.
Просто в розділі "Мій журнал" відображно всі листи та повідомлення пов'язані з Вашим зверненням.
До Вашої поштової скриньки цей лист не надійде.
Після обробки зверення Ви отримаєте зрозумілого листа та ще в процесі обробки до Вас може звернутися урядовець через "зауваження".
З повагою, Август.
