### ISSUE TITLE
Ошибка при входе на страницу "Державна реєстрація фізичної особи – підприємця"

### ISSUE THREAD

**Issue by alcorrius** [e-government-ua/iForum#603]
При входе на страницу "Державна реєстрація фізичної особи – підприємця" по адресу https://igov.org.ua/service/1495/general/place/built-in/region/0/city/0 возникает следующая ошибка:

Помилка

[ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: property in activitiForm.formProperties track by property.id, Duplicate key: fVarDod1, Duplicate value: {"id":"fVarDod1","name":"Файл з заявою щодо обрання фізичною особою спрощеної системи оподаткування","type":"file","value":null,"readable":true,"writable":true,"required":false,"datePattern":null,"enumValues":[],"sFieldLabel":"Файл з заявою щодо обрання фізичною особою спрощеної системи оподаткування","sFieldNotes":null} http://errors.angularjs.org/1.3.15/ngRepeat/dupes?p0=property%20in%20activitiForm.formProperties%20track%20by%20property.id&p1=fVarDod1&p2=%7B%22id%22%3A%22fVarDod1%22%2C%22name%22%3A%22%D0%A4%D0%B0%D0%B9%D0%BB%20%D0%B7%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BE%D1%8E%20%D1%89%D0%BE%D0%B4%D0%BE%20%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D1%8F%20%D1%84%D1%96%D0%B7%D0%B8%D1%87%D0%BD%D0%BE%D1%8E%20%D0%BE%D1%81%D0%BE%D0%B1%D0%BE%D1%8E%20%D1%81%D0%BF%D1%80%D0%BE%D1%89%D0%B5%D0%BD%D0%BE%D1%97%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8%20%D0%BE%D0%BF%D0%BE%D0%B4%D0%B0%D1%82%D0%BA%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F%22%2C%22type%22%3A%22file%22%2C%22value%22%3Anull%2C%22readable%22%3Atrue%2C%22writable%22%3Atrue%2C%22required%22%3Afalse%2C%22datePattern%22%3Anull%2C%22enumValues%22%3A%5B%5D%2C%22sFieldLabel%22%3A%22%D0%A4%D0%B0%D0%B9%D0%BB%20%D0%B7%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BE%D1%8E%20%D1%89%D0%BE%D0%B4%D0%BE%20%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D1%8F%20%D1%84%D1%96%D0%B7%D0%B8%D1%87%D0%BD%D0%BE%D1%8E%20%D0%BE%D1%81%D0%BE%D0%B1%D0%BE%D1%8E%20%D1%81%D0%BF%D1%80%D0%BE%D1%89%D0%B5%D0%BD%D0%BE%D1%97%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8%20%D0%BE%D0%BF%D0%BE%D0%B4%D0%B0%D1%82%D0%BA%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F%22%2C%22sFieldNotes%22%3Anull%7D (caused by "undefined")

Час: "2016-08-18T05:51:37.612Z"

**Comment by agerman-ua** [comment]
Дякую. Дивимось.

**Comment by agerman-ua** [comment]
Зараз працює. Можете подавати.
З повагою, Август.

**Comment by alcorrius** [comment]
Спасибо, заработало, но завершилось ошибкой:
"Невідома помилка: Ошибка при получении данных пользователя External service error : null"
https://igov.org.ua/service/1495/general/place/built-in/region/0/city/0?formID=6e48a9eb-8bc7-4715-af89-86b7c2fb3d94&signedFileID=7d3432c0-1f84-4770-a4f5-24243795565b

ЭЦП от АЦСК ІДД.
Я так понимаю нужно подавать данные еще раз?

**Comment by alcorrius** [comment]
Ошибка возникала в Firefox.
Через Chrome всё отправилось успешно.

**Comment by agerman-ua** [comment]
Какой номер заявки?
