### ISSUE TITLE
Звернення 0-437554778 - Допомога при народженні дитини. м. Дніпропетровськ

### ISSUE THREAD

**Issue by denis-ryabenko** [e-government-ua/iForum#604]
Зареєструвався Звернення 0-437554778 Не має жодної відповіді, Що робити? на якій стадії знаходиться моя реєстрація? Пройшло вже 19 днів.

**Comment by zolotovatatyana** [comment]
Яка послуга і населений пункт?
і дайте будь ласка скріншот з розділу "Мій Журнал", який там статус має Ваше Звернення?

**Comment by denis-ryabenko** [comment]
Допомога при народженні дитини. м. Дніпропетровськ

**Comment by denis-ryabenko** [comment]
![image](https://cloud.githubusercontent.com/assets/21100528/17769715/aae61074-6542-11e6-8672-f8ff07514172.png)

**Comment by denis-ryabenko** [comment]
![image](https://cloud.githubusercontent.com/assets/21100528/17769741/c2d44c1e-6542-11e6-8814-e1a8c79b99e4.png)

**Comment by denis-ryabenko** [comment]
Там було декілько спроб подачі заявки із-за помилки і була зареєстрована аж 7 разів 0-437554778 ; 0-437556805 ; 0-437566681; 0-437576809; 0-437582077; 0-437588643; 0-437604825; але не на одну заявку не має відповіді.

**Comment by zolotovatatyana** [comment]
Ав розділі "Мій Журнал", якщо ви пройдете аторизацію БанкАйді або ЕЦП,ви побачите хоча б одну з цих  заявок?

І ще, чи можна докладніше про помилку, яка виникала під час подачі заявки?

**Comment by denis-ryabenko** [comment]
ЖОДНОЇ заявки немає. Помилка стосувалася некоректному заповненню полів, і висвічувалось багато символів "коди" які мені не зрозумілі, тому робили всілякі поправки для вирішення проблеми і так 7 разів. аж поки не побачили  на почті 7 зареєстрованних заяв.

**Comment by zolotovatatyana** [comment]
На жаль, жодна з заявок в базу, і відповідно, на обробку, не потрапила. 
Будемо розбиратись, чому Вам прийшли листи, котрі ввели Вас в оману, і не дали можливість одразу перевірити статус заяви.

Зараз єдиний вихід - це переподати звернення знову. Якщо в ході заповнення заявки буде помилка - прошу скріншот і я спробую допомогти.

**Comment by denis-ryabenko** [comment]
Доброго панку підскажіть по звявці 0-538636511 чи вірно все заповненно.

**Comment by zolotovatatyana** [comment]
Доброго ранку.
Ваше звернення переведено на другий етап розгляду, отже Заява заповнена вірно. 
"Заповнені дані вірні, інформація направлена на розгляд, очікується рішення"

**Comment by denis-ryabenko** [comment]
дякую за відповідь. гарного дня.

**Comment by denis-ryabenko** [comment]
Доброго дня по зверненню  0-538636511 цікавить скільки чекати відповідь.

**Comment by zolotovatatyana** [comment]
Доброго дня. Заява ще на другому етапі.
Телефони УПСЗН для довідок:

+380 (56) 372–19–70
приемная
+380 (56) 372–19–75

**Comment by denis-ryabenko** [comment]
Доброго дня по зверненню 0-538636511 цікавить скільки чекати відповідь.
На тих телефонах не хто не відповідає то є приймальня, вони кажуть приїжджайте та взнавайте, на жаль не має можливості. Підкажіть що далі робити, Дякую

**Comment by zolotovatatyana** [comment]
[](http://dp.ric.ua/cat/CompanyPage/5933)  372-19-67-детские пособия

**Comment by denis-ryabenko** [comment]
Доброго дня по зверненню 0-538636511 прийшла відповідь на е-мейл але не має вкладень. а заявку закрили.

**Comment by zolotovatatyana** [comment]
Допомогу за вашим зверненням  призначено.
Дуже дивно що не дійшло вкладення, адже без нього відправити листа неможливо.
