### ISSUE TITLE
Звернення №0-521897383 - "Державна реєстрація створення фізичної особи – підприємця"

### ISSUE THREAD

**Issue by alcorrius** [e-government-ua/iForum#605]
Получил ответ по зверненню:
"Ваше звернення №0-521897383 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.

Коментар держслужбовця (Доброго дня! На жаль, не виходить обробити Вашу заявку, так як не відкривається заява з ЕЦП та неможливо перевірити ЕЦП.)"

Не подскажете с чем это может быть связано?
Браузер Chrome
ЭЦП от АЦСК ІДД ДФС

**Comment by alcorrius** [comment]
Подписал через программу АЦСК ІДД ДФС файл.
Сервис https://ca.informjust.ua/verify даёт ответ: "Результат перевірки підпису: Підпис перевірено успішно. Цілісність даних підтверджено"
А на https://igov.org.ua/ecp - "УВАГА! На цьому файлі немає електронно-цифрового підпису"
[test.txt.p7s.zip](https://github.com/e-government-ua/iForum/files/426880/test.txt.p7s.zip)

**Comment by agerman-ua** [comment]
Добрый вечер @alcorrius .
У Вас просто сформировался файл некорректно. 
Даже не открывается тот файл который Вы присоединили на упрощенку.
Но для чиновника это эквивалентно.
Просто переподайте заявку.
Если заявка сформировалась, значит ЭЦП валидный.
С уважением. Август.

**Comment by alcorrius** [comment]
Спасибо. Новое звернення прошло успешно.

**Comment by agerman-ua** [comment]
Поздравляем. И Вам спасибо. 
Удачи в предпринимательстве.
С уважением, Август
