### ISSUE TITLE
Звернення № 0-489728867 (Регистрация ФОП) Нет выписки

### ISSUE THREAD

**Issue by zukitu** [e-government-ua/iForum#606]
Здравствуйте,
Я зарегистрировалась ФОП через iGov (заявку подала 08.08.2016) - дата регистрации 11.08.2016. Вся информация уже есть в реестре, налоговая и статистика на учет взяли, а выписки по номеру на сайте минюста нет. Насколько я знаю, часто такое происходит по причине "регистратор забыл распечатать выписку", но так я подавала документы через iGov - я не знаю, какой именно регистратор занимался мое заявкой и не могу с ним связаться. 

Помогите, пожалуйста, добыть выписку.

Спасибо,
Анна.

**Comment by agerman-ua** [comment]
Добрый день Анна ( @zukitu ). 
Не нужно уже никого искать. :)
Да, конечно, обязательно поможем.
В понедельник уточним как именно. 
Однако Вы всегда можете независимо заказывать выписку на портале https://usr.minjust.gov.ua/ua/paidextract
про условия и стоимость тут https://usr.minjust.gov.ua/ua/help
С уважением, Август.

**Comment by zukitu** [comment]
Спасибо, буду ждать))
А насчет независимо заказать выписку - уже нельзя таким образом получить выписку, только вытяг(

**Comment by zukitu** [comment]
Понедельник заканчивается, есть какие-то новости?

**Comment by agerman-ua** [comment]
Нет, к сожалению, сегодня новостей не было для Вас. 
Завтра до обеда свяжусь с Вами. Спасибо за терпение.

**Comment by agerman-ua** [comment]
Ещё раз добрый день.
Как мы и договорились в телефонном разговоре - пишу сюда.
Проверьте по уникальному коду на портале минюста - обещали что должен появиться искомый Вами документ.
И, пожалуйста, дайте обратную связь в любом случае.
С уважением, Август.

**Comment by zukitu** [comment]
Проверила по коду - есть документ.
Большое спасибо, Август!)

**Comment by Propeller-SV** [comment]
Прошу прощения, речь о коде - это о коде из "опису" от регистратора? Был зарегистрирован 10.06.2016 и до сих пор не вижу никаких документов на сайте МинЮста при проверке своего кода. Оказывается это можно исправить? Или я не правильно понял?

**Comment by agerman-ua** [comment]
@zukitu очень рад за Вас. Удачи с контрагентом.

@Propeller-SV
Вот-вот. 
Именно это сейчас и произошло. Также думал что момент не корректируемый. Готов был сам пересылать искомый файл заявителю.
Складывается впечатление что есть загрузка и регистраторы просто не успевают сразу два этапа выполнить (внести данные в реестр и сформировать ссылку на документ). Второй откладывается и не всегда обрабатывается в разумные сроки (иногда день-два, иногда несколько недель).
Так что давайте Вами теперь опять займёмся. Прошу сделать отдельную тему по этому вопросу на форуме (надеюсь в спокойных выражениях :) ) и постараемся исправить ситуацию.
Тут я закрою тему.
С уважением, Август.
