### ISSUE TITLE
Заявка 0-496409172 - полный игнор

### ISSUE THREAD

**Issue by demydovd** [e-government-ua/iForum#607]
Гос. служащий, походу, уснул. Разбудите пожалуйста. И научитесь работать "Для людей". а не делать одолжения.
Потрачено две недели ожидания. Очень жаль, что в Украине не популярны судебные иски на "не полученную прибыль", т.к. срываются заказы.

0-496409172 - номер заявки. Никакой реакции ВООБЩЕ, даже отказа.
На форму в гуглдоксе с сайта тоже писал - и тоже ноль реакции.

**Comment by agerman-ua** [comment]
Добрый вечер, @demydovd 
С утра проясним ситуацию. В любом случае - простите за отсутствие реакции с нашей стороны. В основном стараемся здесь на форуме отслеживать проблемы и предложения.
С ув.Август.

**Comment by agerman-ua** [comment]
Добрый день, @demydovd 
По Вашей заявке с 10.08.
Практически всё время она провела в общей очереди куда она попала после регистрации. Из неё госслужащие и берут их в порядке "живой" очереди. Момент взятия из очереди никак не отражается на статусе. Понимаю, что данный момент был бы очень нагляден, но технически это пока невыполнимо. Портал отражает более явные моменты такие как "обработка этапа процесса". В Вашем случае пока этого не произошло.
В связи с этим "будить" некого. Мы просто стараемся разными косвенными способами чтобы чиновники гарантированно уделяли онлайн обработке обращений часть рабочего времени.
По поводу сроков. 
Сегодня/завтра Вы получите ответ. Просто не знаю каким он будет.
С ув.Август.

**Comment by agerman-ua** [comment]
Добрый день, @demydovd 
Поздравляю Вас с регистрацией (23.08.2016).
С уважением, Август.

**Comment by demydovd** [comment]
Дякую. Все пройшло швидко, як тільки заявку почали опрацьовувати.
