### ISSUE TITLE
Заявка 0-500460907 - добавление КВЕДов для своего СПД (закрыта без каких-либо уведомлений). 

### ISSUE THREAD

**Issue by emakarenko** [e-government-ua/iForum#608]
Я подавала заявку на добавление КВЕДов для своего СПД. Подача заявки прошла удачно, получила емейл о том, что заявка принята к рассмотрению. После этого никаких имейлов не получала. Сегодня посмотрела на сайте и увидела что моя заявка в статусе "закрыта". Что это означает и почему не удалось добавить КВЕды?

**Comment by agerman-ua** [comment]
Добрый вечер, @emakarenko 
Вам должно было обязательно прийти письмо с указанием причины отказа.
В любом случае (даже если в почте не находите) на портале в разделе "Мой журнал" Вы и только Вы можете после авторизации просмотреть все сообщения по данному обращению. Включая письмо. Посмотрите там.
С ув.Август.

**Comment by emakarenko** [comment]
Зашла в личный кабинет, разобралась как читать письма. Тоже была проблема. Нужно было отключить всплывающие окна чтобы прочитать. На имейл я получила единственное письмо, когда заявка была принята. Причина отказа - заявка заполнена на русском языке. Хотелось бы увидеть что именно я заполнила на русском языке. Ведь в заявке было просто добавление Кведов.

**Comment by emakarenko** [comment]
Создала повторную заявку. Номер  0-529594340. Ни одного русского слова в ней не было. Следила специально. Вообще не понимаю тогда предыдущую причину отказа.

**Comment by agerman-ua** [comment]
Добрый вечер,
Единственное что было на русском в предыдущем заявлении - это Ваши фамилия, имя, отчество.
В новой заявке это уже на украинском. Тоже не вижу проблем со сменой кодов. 
Спасибо что подали повторную заявку и разобрались с просмотром писем в разделе "мой журнал".
С уважением, Август.

**Comment by emakarenko** [comment]
Будем надеяться, что вторая попытка будет удачной)


22.08.2016 22:00, agerman-ua пишет:

**Comment by emakarenko** [comment]
Хочу поделиться впечатлениями/
Вчера подала заявку на добавление КВЕдов к своему СПД, сегодня уже изменения видны в реестре физлиц. Молодцы. Спасибо!

**Comment by emakarenko** [comment]
Вот только еще 1 вопрос остался - а в налоговой уже не нужно ничего регистрировать?

**Comment by agerman-ua** [comment]
Спасибо большое за отзыв.
По вопросу есть варианты ответов.
Если общая система налогообложения  то ничего не нужно.
А если упрощенка то нужно, поскольку в свидетельстве об уплате единого налога указаны кведы.
А выдает свидетельство налоговая. Не онлайн, насколько мне известно.
С уважением, Август.

**Comment by emakarenko** [comment]
У меня к сожалению, упрощенка(

**Comment by agerman-ua** [comment]
Тогда проконсультируйтесь ещё с кем-то из профессионалов. 
Может есть надежда обойтись без визита.

**Comment by agerman-ua** [comment]
@emakarenko 
Добрый день,
Мы на форуме обсуждали тему заявлений в налоговую.
Без ви
https://github.com/e-government-ua/iForum/issues/615
Может это Вам поможет?!
С уважением, Август.
P.S. Тему закрываю, если что - открывайте новую. :) Удачи.

**Comment by emakarenko** [comment]
спасибо!


31.08.2016 17:49, agerman-ua пишет:
