### ISSUE TITLE
Заявка №0-517272017 на регистрацию ФОП

### ISSUE THREAD

**Issue by AratKruglik** [e-government-ua/iForum#609]
Подал заявку  №0-517272017 на регистрацию ФОП еще 17.08.2016. До сих пор не обработана! Хоть кто-то вообще эти заявки обрабатывал или я зря делал электронную подпись и выстоял в очередях?!

**Comment by nv0683952775** [comment]
Через неделю после подачи регистрации пришло: "Шановний(-а) ИГОРЬ СЕРГЕЕВИЧ

Ваше звернення №0-507253683 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін.
" и молчек!

**Comment by nv0683952775** [comment]
Что дальше?

**Comment by AratKruglik** [comment]
А почему решили об этом спросить в моей теме? ))

**Comment by nv0683952775** [comment]
А шде спрашивать?

2016-08-22 21:36 GMT+03:00 Oleksii Kruhlyk <notifications@github.com>:

**Comment by nv0683952775** [comment]
Кто подскажет что дальше?

2016-08-22 21:41 GMT+03:00 Nata Vili <nv0683952775@gmail.com>:

**Comment by agerman-ua** [comment]
@nv0683952775 
Вам ответил в Вашей теме.

**Comment by agerman-ua** [comment]
Добрый вечер, Алексей ( @AratKruglik )
Конечно Вы не зря получили ЭЦП.
Сейчас только самое начало, в дальнейшем этим способом очень много сможете сэкономить времени. Государство ещё даже не вполсилы даёт нам использовать услуги онлайн и документооборот в электронном виде.
По Вашему обращению, сейчас обращение в активной фазе обработки - думаю завтра будет ответ. Если бы были замечания - уже отказали бы. Но лучше дождаться письма в почту.
С уважением, Август.

**Comment by AratKruglik** [comment]
Спасибо за информацию, Август!

**Comment by AratKruglik** [comment]
За сегодня ничего не обработали, информации нет. А насколько быстро вообще и кто именно обрабатывает эти заявки? Регистраторы по месту прописки?

**Comment by agerman-ua** [comment]
Алексей,
Ваше обращение сейчас точно уже прошло проверку и находится у регистратора.
Этот этап занимает максимум день-два. Думаю всё-же сегодня регистрация состоится. А письмо с положительным решением Вы получите только после гарантированного подтверждения проведения регистрационных действий. Т.е. теоретически возможно что в реестре Вы уже будете а чуть позднее придёт письмо с подтверждением и возможными деталями.
Обрабатывают регистраторы того ЦНАПа который взял из общей очереди Ваше зарегистрированное на портале обращение себе в работу. Т.е. это скорее всего будет не район заявителя. Но поскольку услуга экстерриториальна мы её таким образом помогаем оказывать по всей Украине (без ограничения по регионам).
С уважением, Август.

**Comment by agerman-ua** [comment]
Алексей,
Заявка закрыта 25.07.2016
Поздравляю с регистрацией. Успехов и удачи.
С уважением, Август.
