### ISSUE TITLE
Регистрация автомобиля

### ISSUE THREAD

**Issue by jhonlab** [e-government-ua/iForum#61]
Во превых, хочу сказать, что идея хорошая. Но кто сабботирует вашу работу незнаю, наверно работники ЦНП 1203 3 ВРЕР. Моя заявка по регистрации авто c пробегом №8806944 оформлена 16.10.2015. Статус изменился 2015-10-17 14:46:58.216 Перевірка наявності обтяжень (у роботi). И всё!!! На сегодня 05.11.15 ничего не изменилось. В ЦНП 1203 3 ВРЕР долгое время отсутствовал пластик (бланки для печати техпаспартов), но за это время он появлялся и я думал, что хотябы электронные заявки пройдут внеочереди. Мы приехали в ЦНП 1203 3 ВРЕР 31.10.15 и узнали, что наша заявка лежит во вновь принятых. Плюнули на вашу электронную регистрацию, и в рабочее время, взяв отгул, 03.11.15 отстояв все очереди зарегистрировали авто. 
Вопрос - кому нужна ваша работа? Второй - как я могу оставить свой гневный отзыв к своей заявке №8806944?

**Comment by GrekD** [comment]
@kurbpa можешь помочь?

**Comment by kurbpa** [comment]
Боюсь. то высказывать некому - большая часть сотрудников  переведены в другие сервисные центры или уволены в связи с реформой. Планируем обучать новых сотрудников  сервисных центров для работы с заявками.
