### ISSUE TITLE
Звернення №0-507253683 на тему "Державна реєстрація створення фізичної особи – підприємця" - (Что дальше?)

### ISSUE THREAD

**Issue by nv0683952775** [e-government-ua/iForum#610]
ПРишло на електронку письмо:"Шановний(-а) ИГОРЬ СЕРГЕЕВИЧ

Ваше звернення №0-507253683 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін.

З повагою,
Команда Порталу державних послуг iGov"
Что дальше делать?

**Comment by agerman-ua** [comment]
Добрый вечер, @nv0683952775 
У Вас странная ситуация.
Вам пришёл положительный ответ, т.к. госслужащим был выбран вариант "положительное решение", по этой причине до Вас не дошёл комментарий - "Причина:В ЗАЯВІ ПРО ДЕРЖАВНУ РЕЄСТРАЦІЮ ФІЗИЧНОЇ ОСОБИ-ПІДПРИЄМЦЯ ПІБ НА РОСІЙСЬКІЙ МОВІ". 
Насколько мне понятно из произошедшего - Вам было отказано, но неправильно обработано.
Не знаю каким именно способом Вы авторизовались, но после авторизации портал использовал именно русский вариант Ваших данных (ФИО). Если это банкАйДи - обратитесь в Ваш банк для изменения, если ЭЦП - используйте другой или также исправьте на украинский. Других замечаний не вижу.
С уважением, Август.

**Comment by nv0683952775** [comment]
Потрібно змінити ПІП на українську і знову подати заяву? На igov?

**Comment by nv0683952775** [comment]
Потрібно змінити ПІП на українську ( в Приват) і знову подати заяву? На igov?

**Comment by agerman-ua** [comment]
Добрий вечір, @nv0683952775 
Так. Думаю це буде дуже доречно. Подайте нове звернення, та перед цим, змініть в будь-якому відділенні ПриватБанку свої персональні дані.
З повагою, Август.
