### ISSUE TITLE
Попытка подключить ЕЦП от ДФС: ошибка TypeError: b is null

### ISSUE THREAD

**Issue by dpotikha** [e-government-ua/iForum#611]
Пытался достучаться до сервиса "Державна реєстрація земельної ділянки з видачею витягу з Державного земельного кадастру".
После выбор региона попробовал установить ЕЦП от ДФС. Получил ошибку **TypeError: b is null**.
После повторной попытки выбрать регион эту же ошибку получил уже на выборе региона. А затем еще одна ошибка вывалилась. На том и остановился.

![clip2net_160823095230](https://cloud.githubusercontent.com/assets/3133321/17882897/f2ca7fe6-6917-11e6-8a41-70ab2e364938.png)
![clip2net_160823095358](https://cloud.githubusercontent.com/assets/3133321/17882896/f2c8ee74-6917-11e6-9580-910d11b105d3.png)
![clip2net_160823095412](https://cloud.githubusercontent.com/assets/3133321/17882895/f2c824bc-6917-11e6-8dbc-c176a5517dae.png)

**Comment by annastolbova** [comment]
зараз все працює коректно
