### ISSUE TITLE
Звернення № 0-473200537. Державна реєстрація створення фізичної особи – підприємця

### ISSUE THREAD

**Issue by roman-movchan** [e-government-ua/iForum#612]
Отримав дві відповіді по зверненню. 
Перша:
"Ваше звернення №0-473200537 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін.
Вам направлена копія рішення (додаток до листа)."

Ніякої копії рішення не направлено, додатку немає

Через 15 хвилин інша відповідь по тому ж самому звененню:
"Ваше звернення №0-473200537 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
Коментар держслужбовця (Причина: Шановний заявник, на вашу заяву не накладено ЄЦП)"

Спроби з'ясувати що мені робити і прохання закрити заявку що б можна було подати нову нічим не закінчились, я пишу але відповіді не отримую.

**Comment by agerman-ua** [comment]
Добрий день, Романе (@roman-movchan )
Дуже дивна комбінація у Вас трапилась. У будь якому випадку повинен був надійти тільки один лист.
В журналі вже не треба писати, після листа про опрацьовану заявку вважайте що держслужбовець вже нічого не побачить (вона для нього опрацьована).
Зараз вирішимо питання для можливості подання нового звернення.
Зачекайте, будь-ласка - поки зміниться статус в журналі, тоді зможете подати нове звернення.
З повагою, Август.

**Comment by roman-movchan** [comment]
дякую

**Comment by agerman-ua** [comment]
Романе ( @roman-movchan )
Можете подавати нове звернення.
Після успішного подання прошу проінформувати, щоб впевнитися.
З повагою, Август.

**Comment by roman-movchan** [comment]
подав. про результат відпишу

**Comment by roman-movchan** [comment]
тепер прийшов лист такого змісту

"Шановний колего!
У черзі на обробку зареєстровано нове звернення
Опрацюйте це звернення на порталі"

Здається, система мене сприймає як держслужбовця

**Comment by agerman-ua** [comment]
Добре. Тут тоді тему закрито.

**Comment by agerman-ua** [comment]
"тепер прийшов лист такого змісту
"Шановний колего!
..."
Здається, система мене сприймає як держслужбовця"

Ні. То в журнал попадають всі листи пов'язані з Вашим зверненням, в тому числі і до держслужбовця. Листи до Вас завжди персоналізовані. :)
На Вашу пошту такі листи не надійдуть.
