### ISSUE TITLE
Выписка по номеру на сайте МинЮста

### ISSUE THREAD

**Issue by Propeller-SV** [e-government-ua/iForum#613]
Был зарегистрирован 10.06.2016 с вашей помощью, но до сих пор не вижу никаких документов на сайте МинЮста при проверке по коду от регистратора. Помогите пожалуйста исправить, если можно.
Обращение номер 0-277581305.

**Comment by agerman-ua** [comment]
Принял. Постараемся. Ага. Сейчас Ваш администратор в отпуске, с понедельника поспрашиваем.

**Comment by agerman-ua** [comment]
Завтра с утра общаюсь с регистратором.

**Comment by agerman-ua** [comment]
@Propeller-SV 
Добрый день, Сергей.
Пообщался с регистратором. Выяснились пару обстоятельств.
Оказывается она физически не могла распечатать выписку, т.к. регистрировать в других регионах у них есть возможность, а генерирование номера выписки при формировании осталось привязанным к региону (и регион не её) и вот это и есть проблема. Где-то так.
Она пообещала что-то придумать. Чуть подождём. 
Номер уникальный у тебя есть чтобы проверять периодически на портале минюста?
С ув. Август.

**Comment by Propeller-SV** [comment]
@agerman-ua 
Спасибо большое, Август. "Свідоцтво про державну реєстрацію СПД / Виписка" стало доступно для скачивания.

**Comment by agerman-ua** [comment]
Отличная новость, Сергей. Удачи во всём.
