### ISSUE TITLE
заявка 0-417681907 -  Отримання/заміна паспорта громадянина України для виїзду за кордон (: JSON.parse: unexpected character )

### ISSUE THREAD

**Issue by sh112** [e-government-ua/iForum#614]
В журнале заявок, при нажатии на кнопку "Детальніше",   получаю окно с сообщением

JSON.parse: unexpected character at line 1 column 1 of the JSON data (caused by "undefined")
Час: "2016-08-25T06:22:45.742Z"

**Comment by Koffeek** [comment]
@sh112 Ваша заявка закрита, що саме Ви хотіли дізнатись?

**Comment by sh112** [comment]
@Koffeek , во-первых, интересно, почему заявка закрыта, если паспорт еще мною не получен (и никак не мог быть получен на момент закрытия заявки).
Во-вторых, сообщение о битом json'е - хоть не критическая, но ошибка, и с ней что-то надо делать.

**Comment by Koffeek** [comment]
@sh112 Заявка закрывается по факту подачи документов. Получение паспорта портал не отслеживает. По битому json'у передал программистам
