### ISSUE TITLE
Регистрация ФЛП (Вопрос по v1_zajava_EP)

### ISSUE THREAD

**Issue by iValentin** [e-government-ua/iForum#615]
Добрый день!

_Пытаемся открыть ФЛП, но застряли на "ЗАЯВА про застосування спрощеної системи податкування". Если верно понимаю, она нужна, чтобы налоговая посадила на единый вместо общего, верно?_ 

Вопросы:
1. Подписывать ее не нужно, просто заполнить? Или печать-заполнить-скан?
2. Кто ее делал? Что за, извините, совковая ахинея? Ну это же можно с подсказками в google-форму засунуть или прямо на сайте сделать ...

По полям в файле:
`1. Номер реєстрації в органі державної податкової служби`
Это ИНН? 

`2. Найменування органу державної податкової служби`
Это что? Моя налоговая? Я его не знаю. Идти в налоговую спрашивать? Я же хочу все сделать удаленно. 

`3. Дані документа, що підтверджують державну реєстрацію юридичної особи та/або фізичної особи – підприємця (назва, номер, дата)`
Я же только оформляюсь, тут что писать? 

`4. 5. Підстави подання заяви`
Это как? Почему хочу быть на едином? Это дешевле. Что там писать? 

`5. Місце провадження господарської діяльності (індекс, найменування населеного пункту, адреса):`
А это как? Допустим, регистрация у меня донецкая, а хочу работать в Киеве. Что там писать и зачем это налоговой нужно? 

`6. 12. Обсяг доходу за попередній календарний рік становить (пункт 5 Розрахунку доходу за попередній календарний рік, що передує року переходу на спрощену систему оподаткування)** `
Я только регистрируюсь - что тут писать? Зарплату на предыдущем месте? А если еще не работал, студентом был - стипендию? 

`7. Розрахунок доходу за попередній календарний рік, що передує року переходу на спрощену систему оподаткування за попередній календарний рік додається (“” або “-”)**`
Аналогично вопросу выше. 

**Спасибо за ответы и ваш труд.**

**Comment by agerman-ua** [comment]
Добрый день, @iValentin 
"... Если верно понимаю, она нужна, чтобы налоговая посадила на единый вместо общего, верно?..."
Да, абсолютно верно, чтобы и зарегистрироваться и сразу стать на упрощенную форму налогообложения.
Вопросы:
1. Лучше  печать-заполнить-подписать-скан. Или заполнить-печать-подписать-скан. Как удобнее.
2. Документ официальный. С сайта налоговой. Просто не буду подливать масло в огонь.

По полям в файле:
1. Нет это не ИНН. Это поле и поле ниже не заполняется Вами. ИНН - п.2 Код за ЄДРПОУ, або реєстраційний номер облікової картки платника податків (ідентифікаційний номер), або серія та номер паспорта*
2. Да Ваша налоговая. Идти не обязательно. Узнать можно по разному, например http://sfs.gov.ua/ru/pro-gfs/struktura/territorialnyie-organyi-gns/ или http://sfs.gov.ua/others/kontakti/ или позвонить в местную налоговую.
3. Ничего. Документ рассчитан и на случаи изменения системы налогообложения уже зарегистрированных лиц, поэтому такие поля присутствуют.
4. Ничего писать не нужно. Можно поставить дату но поскольку мы не знаем точно дату регистрации можно поставить дату (сегодня+10 дней).
5. Если нет офиса или цеха просто указать адрес регистрации. Зачем - возможно они и сами не знают.
6. На нет и суда нет. Причины см.п.5.
7. Аналогично ответу выше. :)

Спасибо и Вам за доверие. Удачи.
А поскольку вижу абсолютно разную реакцию сотрудников налоговых - то что нормально проходит в одной может вызвать истерику в другой, лучше (определившись с налоговой) или найти знакомого бухгалтера или зарегистрировавшегося там ФЛП, которые подскажут по реальным действиям в конкретной налоговой.

С уважением, Август.

**Comment by iValentin** [comment]
`1. Лучше печать-заполнить-подписать-скан. Или заполнить-печать-подписать-скан. Как удобнее.`
А как же ЭЦП? Разве не должен заменять? 

`А поскольку вижу абсолютно разную реакцию сотрудников налоговых - то что нормально проходит в одной может вызвать истерику в другой, лучше (определившись с налоговой) или найти знакомого бухгалтера или зарегистрировавшегося там ФЛП, которые подскажут по реальным действиям в конкретной налоговой.`
Печально все это, будем пробовать.

**Comment by agerman-ua** [comment]
Заменяет но только для сотрудника ЦНАПа и регистратора, Но документ-то для другого органа, который не видит Ваше обращение и Ваше ЭЦП под заявкой. Это будет лишний повод придраться.
Удачи.

**Comment by roman-movchan** [comment]
Может вопрос не по теме, но как перейти на единій налог уже после регистрации ФЛП? Єто возможно?

**Comment by Propeller-SV** [comment]
@roman-movchan если после регистрации ФЛП прошло более 10 дней, то перейти можно уже только со следующего квартала. Для этого заявление о переходе нужно подать в свою налоговую (лично или по почте) не позднее 15 числа последнего месяца текущего квартала.

**Comment by agerman-ua** [comment]
@roman-movchan 
Роман, Вопрос очень по теме.
Тяжело что-то добавить к предыдущему посту.
Разве что, если заказным отправляешь - то дата считается не на момент получения адресатом а в момент отправки. 
С уважением, Август.

**Comment by Propeller-SV** [comment]
@agerman-ua я думаю здесь вы ошибаетесь, в данном случае лишь дата получения будет играть роль. Дата отправки играет роль в случае отправки налоговой отчетности.

**Comment by agerman-ua** [comment]
@Propeller-SV 
Специально побеспокоил одну замечательную женщину, профессионального бухгалтера-аудитора.
**Именно момент отправки и есть дата о которой мы говорим. Это точно.**
По третьей группе (не плательщики НДС) с дня регистрации 10 дней на **отправку письма**. И регистрация плательщиком в налоговой с момента регистрации.
По первой-второй группам (плательщики НДС) **отправка письма** до последнего дня месяца. С 1 числа следующего месяца вступает в силу.

Согласно Налогового кодекса полный ответ таков. Текст ниже ссылки.
http://zakon2.rada.gov.ua/laws/show/2755-17/page41
"298.1.2. Зареєстровані в установленому порядку фізичні особи - підприємці, які до закінчення місяця, в якому відбулася державна реєстрація, подали заяву щодо обрання спрощеної системи оподаткування та ставки єдиного податку, встановленої для першої або другої групи, вважаються платниками єдиного податку з першого числа місяця, наступного за місяцем, у якому відбулася державна реєстрація.
Зареєстровані в установленому законом порядку суб’єкти господарювання (новостворені), які протягом 10 днів з дня державної реєстрації подали заяву щодо обрання спрощеної системи оподаткування та ставки єдиного податку, встановленої для третьої групи, яка не передбачає сплату податку на додану вартість, вважаються платниками єдиного податку з дня їх державної реєстрації."

С уважением, Август.

**Comment by Propeller-SV** [comment]
@agerman-ua при всем уважении, Август, в вашей цитате нет ответа на вопрос о дате подачи отправленного по почте заявления. Поэтому я все же рекомендую заглянуть по нижеприведенным ссылкам, чтобы не подставлять людей на основании мнения одной замечательной женщины. Кеш гугла с сайта ГФС.

"Якщо заява про обрання або перехід на спрощену систему оподаткування направлена поштою, то датою подання такої заяви вважається дата її надходження до органу фіскальної служби, яка проставляється на першому аркуші оригіналу документа."

[Раз](http://webcache.googleusercontent.com/search?q=cache:http://tr.sfs.gov.ua/media-ark/news-ark/print-192313.html) [Два](http://webcache.googleusercontent.com/search?q=cache:http://kyivobl.sfs.gov.ua/npp-gariachi-linii/print-67445.html) [Три](http://webcache.googleusercontent.com/search?q=cache:http://sfs.gov.ua/ebpz/107--ediniy-podatok-dlya-fizichnih-osib-/107-08-stroki-podannya-zvitnosti-ta-poryad/5287.html) [Четыре](http://minfin.com.ua/taxes/-/ediniy_qw/ed_1_16.html)

С уважением, Сергей.

**Comment by agerman-ua** [comment]
Сергей ( @Propeller-SV )
:)
Думаю ниже чётко демонстрируется чем одно почтовое отправление отличается от другого. Если письмо не заказное с уведомлением о вручении и вложенной описью - то будет дата подачи равна дате получения.
Очень прошу прокомментировать. Мне важно убедиться достаточно ли аргументов. Спасибо.

Вот что отвечают на официальный ресурсе http://zir.sfs.gov.ua/ на запрос по ссылке
http://zir.sfs.gov.ua/main/bz/view/?src=ques
**запрос** "Яка дата вважається датою подання заяви про застосування спрощеної системи"

**Коротка відповідь:**
     При надсиланні заяви щодо обрання спрощеної системи оподаткування поштою з повідомленням про вручення та з описом вкладення датою подання заяви вважається дата відправлення, яка відбивається на повідомленні про вручення та на описі.
**Повна відповідь:**
Відповідно до п.п. 298.1.1 п. 298.1 ст. 298 Податкового кодексу України від 02 грудня 2010 року № 2755-VI із змінами і доповненнями (далі – ПКУ) заява подається за вибором платника податків, якщо інше не передбачено цим Кодексом, в один з таких способів:
1) особисто платником податків або уповноваженою на це особою;
2) надсилається поштою з повідомленням про вручення та з описом вкладення;
3) засобами електронного зв’язку в електронній формі з дотриманням умови щодо реєстрації електронного підпису підзвітних осіб у порядку, визначеному законодавством;
4) державному реєстратору як додаток до реєстраційної картки, що подається для проведення державної реєстрації юридичної особи або фізичної особи - підприємця з урахуванням вимог п. 291.5 ст. 291 ПКУ. Електронна копія заяви, виготовлена шляхом сканування, передається державним реєстратором до контролюючого органу одночасно з відомостями з реєстраційної картки на проведення державної реєстрації юридичної особи або фізичної особи - підприємця згідно із Законом України «Про державну реєстрацію юридичних осіб та фізичних осіб – підприємців».
Згідно з п.п. 298.1.2 п. 298.1 ст. 298 ПКУ зареєстровані в установленому законом порядку суб’єкти господарювання (новостворені), які протягом 10 днів з дня державної реєстрації подали заяву щодо обрання спрощеної системи оподаткування та ставки єдиного податку, встановленої для третьої групи, яка не передбачає сплату податку на додану вартість, вважаються платниками єдиного податку з дня їх державної реєстрації.
**Отже, при надсиланні заяви щодо обрання спрощеної системи оподаткування поштою з повідомленням про вручення та з описом вкладення датою подання заяви вважається дата відправлення, яка відбивається на повідомленні про вручення та на описі.**"

**Comment by Propeller-SV** [comment]
@agerman-ua о да, этот ответ выглядит как аргумент.
:)
Остается лишь надеятся, что он будет аргументом и для работников налоговой. Просто налицо очевидное противоречие в ответах на официальном сайте ГФС на один и тот же вопрос. Разве нет?
Спасибо вам огромное!
С уважением, Сергей.

**Comment by agerman-ua** [comment]
:) Спасибо за комментарий, Сергей.
На самом деле тут есть некая неприятная небрежность со стороны налоговой. 
Пишут об отправке почтой, но не уточняют варианты. У меня же сразу вопрос появился "о каком виде почтового отправления идёт в их ответе"? Но этот вопрос не всем приходит в голову.
Надеюсь что это просто непрофессионализм а не попытка манипулирования налогоплательщиками.
Всем удачи. Боритесь за себя.
С уважением, Август.
P.S. Вот теперь спокойно можно закрыть тему. :)
