### ISSUE TITLE
Звернення № 0-519611328. Державна реєстрація створення фізичної особи – підприємця.

### ISSUE THREAD

**Issue by rapita** [e-government-ua/iForum#616]
Доброго дня, подав заявку 17.08.2016, помилився при заповненні і залишив коментар: "Потрібно внести зміни в подану мною заявку, вказати Спрощену систему оподаткування 3 группа 5%. Підкажіть будьласка як я це можу зробити. Дякую.".

Будьласка дайте відповідь на коментар або скасуйте заявку.

**Comment by agerman-ua** [comment]
Доброго дня.
Додзвонився до адміністратора, Вас зареєстрували вже. На загальну систему. Коли ви написали то вже дані були у реєстратора. 
Тепер після того як побачите листа з порталу та перевірите стан у реєстрі за безкоштовним запитом можна йти до податкової та писати там заяву про спрощену систему.
З повагою, Август

**Comment by rapita** [comment]
Доброго дня. А через iGov є можливість написати "Заяву про спрощену систему"?

**Comment by rapita** [comment]
Допоможіть будьласка вирішити проблему. 

Після подання заявки не було можливості її відмінити, щоб внести зміни. Коментар щодо змін, я залишив одразуж після подання заявки... 

Піти до податкової в мене немає можливості...

**Comment by agerman-ua** [comment]
Доброго дня.
"А через iGov є можливість написати "Заяву про спрощену систему"?"
Ні, наразі така можливість відсутня. Ми працюємо над можливістю пропонувати послуги які пов'язані безпосередньо з податковою (фіскальною) службою. Але це точно не станеться найближчим часом.
"Піти до податкової в мене немає можливості..."
Це ж не обов'язково фізично йти. Знайдіть хто Вам допоможе скласти документ та правильно відправити до податкової звичайною поштою з повідомленням. Це теж працює. 
З повагою, Август.
