### ISSUE TITLE
Покращення інтерфейсу для регіонів

### ISSUE THREAD

**Issue by olagodiyenko** [e-government-ua/iForum#617]
Зараз логіка системи наступна - спочатку послуга - потім обираєш регіон. і маєш ефект розчарування, бо не все ще працює.
краще навпаки - обрав регіон - і відразу бачиш перелік доступних послуг за місцем проживання

**Comment by zolotovatatyana** [comment]
Дякуємо  за Ваш коментар,
Це вже реалізовано на порталіза допомогою фільтрації послуг

![image](https://cloud.githubusercontent.com/assets/17428210/18007561/47036ca2-6bad-11e6-8f6b-442d0ccdd0ae.png)

![image](https://cloud.githubusercontent.com/assets/17428210/18007591/65305ab4-6bad-11e6-8d7a-103d8e5aa44b.png)

**Comment by olagodiyenko** [comment]
Дякую. відразу не побачив.


2016-08-26 16:52 GMT+03:00 zolotovatatyana <notifications@github.com>:
