### ISSUE TITLE
Заява 0-480284270 (Державна реєстрація створення фізичної особи – підприємця)

### ISSUE THREAD

**Issue by nibiru2104** [e-government-ua/iForum#618]
Добрий день! 

5 серпня подала заявку на послугу Державна реєстрація створення фізичної особи – підприємця (Заява 0-480284270).
8 серпня мені відмовили, через те, що сертифікат банку був виданий російською мовою.
Я замінила сертифікат у банку на український. 11 серпня зайшла до системи з новим сертифікатом і надіслала виправлену форму заяви. Відповіді не отримала, написала звернення через Гугл-форму, але на це звернення ніякої відповіді також не отримала.
Спробувала відкрити нову заяву, але на сайті встановлено ліміт.
Вже скоро місяць, як заява висить без жодних змін зі статусом "в обробці", ніякої можливості звернутись до службовців в інший спосіб немає.
Дуже прошу допомогти продовжити процес реєстрації або видалити мою заяву, щоб я могла почати реєстрацію знову! 
З повагою, 
Наталя

**Comment by agerman-ua** [comment]
Добрий день, @nibiru2104 
Прийняли. Зачекайте трошки.

**Comment by agerman-ua** [comment]
@nibiru2104 
Все. 
Можете подавати нове звернення.
З повагою, Август.

**Comment by nibiru2104** [comment]
Дякую за швидке вирішення мого питання!
