### ISSUE TITLE
Оформление заявок на услуги с ОС Андроид

### ISSUE THREAD

**Issue by sol1210** [e-government-ua/iForum#62]
Попытка подать заявку на получение субсидии с ОС Андроид (с браузера Chrome) оказалась неудачной. Есть ли какой-то браузер, который с Андроида работает корректно или специальное приложение для Андроида?

**Comment by dmitrijzabrudskij** [comment]
пока нет. сделайте пожалуйста с планшета или пк - с телефона пока затруднительно заявки подавать

**Comment by sol1210** [comment]
С планшета у меня и не получилось

**Comment by dmitrijzabrudskij** [comment]
подскажите тогда какая модель и какую ошибку вернуло при заполнении заявки?

**Comment by sol1210** [comment]
Планшет Prestigio PMT 5001_3G. С хрома не получается войти в BankID (приват24 в хроме не работает), соответственно, все тормозится сразу. А с встроенного браузера престижио форма заполнена, а нажатие кнопки "подать заявку" не срабатывает, так и зависает.

**Comment by sol1210** [comment]
Я разобралась в проблеме. Для того, чтобы с браузера хром подать заявку, нужно в настройках открытой вкладки нажать галочку "требуется полная версия".

**Comment by dmitrijzabrudskij** [comment]
спасибо - будем знать теперь:)
