### ISSUE TITLE
(Реєстрація ФОП) Заява 0-526002440 - закрита, в чому причина?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#620]
> Ольга Фатерига:
> Заява 0-526002440 була закрита 29.08 але на сайті Міністерства Юстиції немає, а також в податковій сказали, що такий ФОП в них не зареєстрований. Скажіть, будь ласка, в чому може бути причина?

https://www.facebook.com/olhafateryga
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1746464578975751&reply_comment_id=1750124558609753&comment_tracking=%7B%22tn%22%3A%22R9%22%7D

**Comment by agerman-ua** [comment]
Доброго дня Ольга.
Так, Вашу заяву було оброблено.
За результатами розгляду Вам було відмовлено, "Причина: Не всі поля заяви заповнені, що унеможливлює її роздрукування та оброблення."
Про це Ви повинні були отримати листа в поштову скриньку, яку вказали при поданні звернення, а також копію цього листа до Вашого розділу "Мій журнал" на порталі.
Перевірте, будь ласка. 
Можете подати нове звернення. Та написати сюди його номер. Прослідкую щоб не було швидкої відмови.
З повагою, Август.

**Comment by VadymVolos** [comment]
@agerman-ua можливо замість слова "Закрито" треба писати "Відхилено, причини дивіться в листі або в особистому кабінеті"? Тому що люди думають що якщо закрито значить виконано, і це слово закрито вводить в оману.

**Comment by agerman-ua** [comment]
@VadymVolos 
Ну я б так не казав. Це концепт досить вірний. Або "відкрито" або "закрито". 
Ця інформація відносно відкрита, та не потребує авторизації. Нащо давати зайву незахищену інформацію.
А от деталі кожна людина без перешкод (крім персональної авторизації) може подивитися в розділі "Мій журнал" або автоматично отримати в листі на персональну скриньку яку вказала при поданні звернення.
Здається досить повна картина.
З повагою, Август.
