### ISSUE TITLE
Реєстрація місця проживання особи для Киева перестала працювати.

### ISSUE THREAD

**Issue by AndriyShatrov** [e-government-ua/iForum#621]
Перестала працювати послуга "Реєстрація місця проживання особи" для м.Киева. Для проходження авторизацii я зробив картку в ПiвденБанку, але на жаль послуга зараз недоступна для даного регiону, якщо навiть для Киева не працюе, тодi де ж працюе. I коли полагодять.

**Comment by Koffeek** [comment]
@AndriyShatrov Доброго дня. Послуга працює для деяких міст Дніпропетровської та Харківської областей. Для м. Київ наразі місцева влада не може гарантувати безперебійну роботу послуги, тому було прийнято рішення тимчасово її закрити.
