### ISSUE TITLE
Звернення на тему: Зняття з реєстрації місця проживання особи  0-562731653

### ISSUE THREAD

**Issue by Yuriyz3** [e-government-ua/iForum#622]
Добрый день!
На сегодня выбрано время, но никто не перезвонил и не сообщил куда идти. Услуга работает?
Подавали в г.Днепр 2 сентября

**Comment by Koffeek** [comment]
@Yuriyz3 услуга работает. В какое подразделение подавали?

**Comment by annastolbova** [comment]
немає відповіді
