### ISSUE TITLE
Нет мест в электронной очереди на загранпаспорт

### ISSUE THREAD

**Issue by Katarzyna17** [e-government-ua/iForum#623]
День добрый. Уже около недели пытаемся подать заявку на замену загранпаспорта, но все подразделения в Днепропетровске выдают "Нажаль, в електронній черзі тимчасово відсутні вільні місця". Планируется добавление новых мест для записи в ближайшее время, и если да, то когда примерно?

**Comment by Koffeek** [comment]
@Katarzyna17 в связи со вступлением с 1 октября в силу ЗУ 1474-VIII, согласно которому вводится выдача гражданам ID-карт, с учетом того, что оформление производится на одной аппаратуре, очередь на оформление загранпаспортов на октябрь будет открыта после решения областного ДМС о порядке работы в новых условиях (скорее всего начало-середина следующей недели)
