### ISSUE TITLE
Не приходят уведомления на почту (Реєстрація місця проживання особи) и про военкомат ни слова в описании

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#624]
заявка Звернення № 0-600262738

на мыло admin@csa.dp.ua не пришло ни одного уведомления.

СМС получил. мыла нет.

причем уведомления на этот адрес не приходят уже давненько.

снова поменялся рассыльщик уведомлений и на некоторые адреса некорректно отсылает.

такое уже было и смотрю, что вернулось снова.

**Comment by AndreyPopovNew** [comment]
вижу в журнале, что заявка принята.

![image](https://cloud.githubusercontent.com/assets/8410116/18663682/2a2d3624-7f28-11e6-87cc-2fc08600dce3.png)


в журнале фразы:
заяву про реєстрацію місця проживання, що знаходиться у додатках до листа;
якщо Ви реєструєте нове місце проживання з одночасним зняттям з попередньго, то заяву про зняття з реєстрації (знаходиться у додатках до листа);

но ссылок на файлы не видно в открывшемся окне.

а на мыло опять же ничего не пришло!

**Comment by zolotovatatyana** [comment]
В спаме искали?

**Comment by AndreyPopovNew** [comment]
искал. проблема не в спаме.

эта проблема уже была.
когда рассылка уведомлений производится с аккаунта, у которого нет мыла.
провайдер просто режет сообщений от адресата, на которого нельзя отослать ответ.

**Comment by AndreyPopovNew** [comment]
а в ответ тишина!

**Comment by AndreyPopovNew** [comment]
@dubilet @GrekD 

никто не поспешил на помощь. ну не пришли бланки заявлений - "сами виноваты".
даже если вы об этом везде спросили
![image](https://cloud.githubusercontent.com/assets/8410116/18716456/8db062e0-8025-11e6-80cc-23d320d9d96c.png)

также НИГДЕ не написано, что надо с принятыми заявлениями ехать в военкомат.

и странно почему заявка закрыта, если меня еще не выписали и не прописали!

еще работник службы посоветовала из ЖЭКа принести карточку учета, чтобы она там поставила сразу печать, что я выписан.
на мой вопрос, а что ж об этом нигде не написано?
ответила: можете не нести, хотя потом все равно с этой карточкой ко мне прийдете.

**Comment by Koffeek** [comment]
@AndreyPopovNew по поводу заявлений, если у Вас их нет, то могут распечатать на месте. 
По настройкам Вашего ящика мы ничего сделать не можем. 
Военнообязаных снимают с регистрации только после снятия в военкомате. 
Об этом сообщают органы регистрации после принятия Вашей заявки в работу, Вас не снимут с учета в военкомате без подписаных органом регистрации заявлений.
Заявку до проставления штампа закрывать не должны. 
По ЖЕКу - они сами должны передавать информацию. 
В какой район Вы подавали заявку?

**Comment by GrekD** [comment]
@AndreyPopovNew 
подскажите, есть у Вас альтернативный электронный ящик?

**Comment by AndreyPopovNew** [comment]
@Koffeek 

1. на месте НЕ печатают, а рекомендуют купить!
2, до этого же приходило! нет никаких настроек ящика. есть провайдер, который НЕ пропускает почту без обратного "живого" адреса. только давайте не предлагать менять провайдера(который и ведет домен dp.ua) и почтовый ящик, которые работает уже 20 (двадцать) лет!
3. о том, что надо ехать в военкомат с подписанными заявлениями - стоит наверное тоже хоть где-то написать!!! может я бы тогда не на 16:30, а на 16:00 записался, чтобы успеть в военкомат ;)
хотя для iGov  время отведено с 16 до 18 и успеть в тот же день в военкомат просто НЕреально!
4. как видите, заявку закрыли, не смотря на то, что никаких штампов не поставили.
5. должны, но как сказал работник: не хотите не надо, но вы сами потом ко мне прибижите с этой карточкой, потому что вам нужна будет справка о составе семьи (как понимаю передача информации из центра в ЖЭК может занять не одну неделю)
6. при подаче заявления выбирал Центральный, но у нас же Соборный и Центральный в одном месте объединены.

**Comment by AndreyPopovNew** [comment]
@GrekD у меня много "альтернативных", но admin@csa.dp.ua  основной и ему уже 20 лет.

andrey.popov@ukrpost.ua
andrey.popov@email.com.ua
andrey.evg.popov@gmail.com
andrey.popov123@voliacable.com
2569800674@mail.gov.ua

вопрос в том, что iGov  должен работать со всеми ящиками, а не с избранными.

**Comment by AndreyPopovNew** [comment]
@dubilet 
а вот эта требование меня честно говоря вообще убила!
квитанцію про сплату адміністративного збору з мокрою печаткою банку;

**Comment by Koffeek** [comment]
@AndreyPopovNew 
1. По Соборному району есть сложности в наличии интернета (райсовет никак не определится с провайдером), возможно поэтому не напечатали заявления.
2. "iGov должен работать со всеми ящиками, а не с избранными" портал нормально работает на Firefox и Chrome, есть проблемы при работе в Safari под ІЕ его будут допиливать в последнюю очередь. Портал должен покрывать максимальное количество стандартных ситуаций, отсылка на экзотические домены будет настраиваться в последнюю очередь. Специально для этого и было сделано сохранение писем в "Мой Журнал". Задачу по подгрузке туда файлов уже создали, постараемся в ближайшее время реализовать. 
3. "для iGov время отведено с 16 до 18" Время устанавливалось по согласию с регистраторами распоряжением горсовета.
4. Вам пришло письмо с фидбеком или так поменялся статус в Моем журнале? Будем разбираться.
5. Информацию они обычно передают раз в неделю, но тут многое зависит от ЖЕКа

"а вот эта требование меня честно говоря вообще убило! :(
квитанцію про сплату адміністративного збору з мокрою печаткою банку;"
они действуют согласно Постанове КМУ и при проверке им необходимо иметь документальное обоснование. Надо менять законодательство, тогда будут принимать любые квитанции.

**Comment by AndreyPopovNew** [comment]
@Koffeek 

2. а при чем тут броузеры, если речь идет о e-mail? ну а то что по ссылкам в Журнале нет ссылок на документы - надо бы исправить.

3. это распоряжение понятно, но тут ДВА нюанса:
а) раз нужна отметка военкомата, то об этом должно быть ПРЕДУПРЕЖДЕНИЕ в описании услуги, что после регистрации заявления военнообязанный должен поехать в военкомат, чтобы поставить отметку военкомата на заявлении  "Снят с учета"  и/или "Принят на учет".
а военкоматы у нас работают до 17-ти часов!!!!! т.е. физически нереально успеть в тот же день туда-обратно. отсюда вытекает вывод, что **НЕОБХОДИМ ПОВТОРНЫЙ ВИЗИ**Т!!!
б) а кто будет назначать или выбирать время повторного визита? и как это отражено в заявке?
мне новую заявку подавать для повторного визита? или в общую очередь со всеми?

и еще по военкомату - они попросили копии зарегистрированных заявлений!
опять же это надо добавить в описание!!!! **что перед походом в военкомат надо снять копии с зарегистрированных заявлений**.


4. письма ко мне НЕ приходят! выше же есть скриншот из Журнала - где у заявки статус "закрыта".

**Comment by GrekD** [comment]
@AndreyPopovNew 
> вопрос в том, что iGov должен работать со всеми ящиками, а не с избранными.
я с Вами полностью согласна, но у нас нет своего почтового сервера или платного аккаунта, который позволил бы рассылать на такие корпоративные аккаунты как у Вас.
Наш бесплатный аккаунт может блокироваться Вашим корпоративным доменом.
Заполняйте, пожалуйста, джемейловский ящик в заявках.

**Comment by Koffeek** [comment]
@AndreyPopovNew 
1. Браузеры это был пример того, что портал не может работать со всеми случаями. Мы стараемся закрвать наиболее распространенные.
2. а) Военкомат Вам не поставит отметку без наличия заявления, заверенного у регистраторов. Поэтому пометка не имеет смысла
б) повторный визит обычно оговаривается с регистратором на месте, когда Вам удобнее. Все документы они уже смотрели.
Тонкости работы военкоматов нам неведомы. Если необходимо - добавим. 
1. Почему закрыли заявку без проставления Вам штампа я сегодня узнаю

**Comment by AndreyPopovNew** [comment]
@Koffeek 
2. что именно не имеет смысла? указать, что надо будет еще идти в военкомат? что в военкомат надо копию зарегистрированного заявления принести?

**Comment by Koffeek** [comment]
@AndreyPopovNew О посещении военкомата сообщают сотрудники при регистрации (снятии с регистрации), они же ставят штамп на Вашем заявлении. Без этого штампа военкомат не снимет Вас с учета. Мы можем добавить формулировку, что регистрация и снятие выполняется только после посещения военкомата. В 99% случаев после этого гражданин пойдет в военкомат не имея заявления и ему там откажут, т.к. нужно иметь заявление. И гражданин пойет в орган регистрации, попутно сожалея о потерянном времени

**Comment by AndreyPopovNew** [comment]
@Koffeek мы о каких-то разных вещах говорим!

я вам о том, что в описании услуги НИГДЕ про военкомат НЕ упоминается! и его посещении тоже!!


вот, что написано в журнале при подтверждении услуги:
Прийти до органу реєстрації за адресою: м. Дніпро, пл. Шевченко, 7 з необхідними документами та звернутись до відповідального співробітника.
Підписати необхідні документи та отримати печатку у громадянський паспорт або паспортний документ.

где тут про военкомат и повторный визит?

в описании как работает услуга:
Крок 3
Під час візиту до органу реєстрації Ви:
Підписуєте усі документи, які необхідні для завершення процесу реєстрації;
Отримуєте печатки про нове місце реєстрації у паспортний документ.


где тут про военкомат и повторный визит?


в Журнале про необходимые документы:

Необхідні документи, які треба принести до органу реєстрації при реєстраціі місця проживання:

оригінал та копію документа, до якого вносяться відомості про місце проживання;
квитанцію про сплату адміністративного збору з мокрою печаткою банку;
оригінал та копію одного з трьох документів, який підтверджує право на проживання за новим місцем реєстрації:
оригінал та копію військового квитка або посвідчення про приписку (для громадян, які підлягають взяттю на військовий облік або перебувають на військовому обліку);

ГДЕ тут написано, что надо будет брать зарегистрированое заявление и идти с ним в военкомат?

хоть в одной строчке об это упомянуто?


@GrekD что скажите вы о карте услуги? есть в ней упоминание про военкомат

**Comment by Koffeek** [comment]
@AndreyPopovNew Я могу только посоветовать перечитать мой предыдущий комментарий. Упоминание о военкомате отсутствует, чтобы гражданин не делал лишнего похода туда.

**Comment by AndreyPopovNew** [comment]
@Koffeek что значит лишнего похода?

я о том, что НИГДЕ не сказано, что туда вообще ходить надо хоть когда-то!

**Comment by AndreyPopovNew** [comment]
@Koffeek @GrekD @dubilet 

И так итог: когда я пришел в следующий раз со штампами из военкомата и карточкой из ЖЭКа выяснилось, что вместе со мной прописан ребенок и выписаться и прописаться я могу только вместе с ним.
а для этого надо заполнять еще пару заявлений, платить еще один сбор, брать с собой маму ребенка, чтобы она подтвердила, что не возражает....

и я решил НЕ выписываться/прописываться.

и тут встал вопрос: **а что теперь делать с военкоматом?** который уже получил информацию, что я буду зарегистрирован по другому адресу?

P.S. вся эта затея с выпиской/пропиской затевались исключительно из следующих соображений:
- я с ребенком зарегистрирован и **живу** в квартире, которая принадлежит маме
- мама зарегистрирована в квартире и **живет** , которая принадлежит мне
в прошлом году в получении субсидии было отказано, потому что субсидия оформлялась только на владельца лицевого счета. вот мы и хотели перепрописаться, чтобы регистрация и владелей лицевого счета совпадали.
но.... как оказалось правила назначения субсидий поменялись и теперь в независимости от владельца лицевого счета субсидия назначается на зарегистрированных по адресу.
вот теперь проверим это.

**Comment by AndreyPopovNew** [comment]
@Koffeek @GrekD @dubilet 

вот официальный ответ postmaster'a домена dp.ua по поводу того, что почта не доходит:

- за рассматриваемый интервал зафиксировано несколько неуспешных доставок корреспонденции из домена iGov.org.ua. Причина неуспешных доставок - невозможность подтверждения отправителя валидности отправителя. Как только на серверах, через которые выполняется доставка корреспонденции от имени iGov.org.ua будут внесены изменения - почта будет доставляться. 
Сервера, с которых происходит рассылка, находятся в облаке и потому связь между администрацией ресурса  iGov.org.ua и конкретным сервером-отправителя, с которым фиксируется проблема, не очевидна (быть может, зафиксированные рассылки являются попыткой SPAM рассылок от имени iGov.org.ua). Если у вас есть связь с собственником ресурса или вы являетесь пользователем данного ресурса - возможно, вам стоит к ним обратиться или переслать описание проблемы. Описания проблемы, совместно с логами почтового сервера отправителя, может быть достаточно для решения проблемы. Если же необходима дополнительная информация - собственники ресурса могут обратиться на postmaster@trifle.net с изложением сути вопроса и мы готовы рассматривать её предоставление

**Comment by GrekD** [comment]
@bvv4ik @OlgaTurenko 
Владимир, Оля, посмотрите, пожалуйста последнее сообщение от Андрея Попова.
Суть проблемы: Андрей подавал несколько боевых заявок через iGov и указывал почту
admin@csa.dp.ua, на которую не пришло ни одного письма.
Он обратился к своему провайдеру и они говорят, что проблема на нашей стороне.
Можете помочь разобраться?

**Comment by AndreyPopovNew** [comment]
@bvv4ik @OlgaTurenko @GrekD 
естб новости по этой проблеме?

**Comment by GrekD** [comment]
@AndreyPopovNew 
передали проблему программистам

**Comment by GrekD** [comment]
@AndreyPopovNew 
Андрей добрый день!
Можно я на Ваш адрес admin@csa.dp.ua подам одну заявочку?
Я хочу попробовать проследить по логам что становится с письмами, которые на этот Ваш адрес не доходят.

**Comment by AndreyPopovNew** [comment]
@GrekD конечно можно.

но письма УЖЕ стали приходить.

![image](https://cloud.githubusercontent.com/assets/8410116/20039000/89e15bf8-a445-11e6-8bd2-c9fd24d31538.png)


по логам провайдер ответил и я давно писал, что почта от отправителя, который не может подтвердить "свое существование" блокирутеся провайдером.

а проще говоря, если на адрес отправителя нельзя отправить письмо, или как это делает провайдер запрос HELO или EHLO (вроде так) - то почта от этого отпраителя "сбрасывается".

**Comment by GrekD** [comment]
@AndreyPopovNew 
похоже, удалось решить проблему.
спасибо
