### ISSUE TITLE
Нет ответа на заявку уже больше месяца

### ISSUE THREAD

**Issue by Gesslow** [e-government-ua/iForum#625]
# **Звернення №0-507776071 .** щодо отримання субсидії на оплату житлово-комунальних послуг.

Контакти підрозділу соцзахисту:
УПСЗН Новокодацького (Ленінського району), м. Дніпропетровськ.
Адреса: 49000, Дніпропетровськ, вулиця Трудова, 1-А
Графік роботи: понеділок-п’ятниця: з 8.00 до 17.00
Телефон(и): (056) 775-55-86

г. Днепр (Днепропетровск), заявка была подана 15 августа в 16:38 .
По данной заявке никаких коментариев, SMS или результатов больше не приходило. На номер УПСЗН никак не дозвониться:(((
Подскажите пожалуйста на каком этапе рассмотрения данная заявка? Спасибо!

**Comment by zolotovatatyana** [comment]
Добрый день.  Ваша заявка успешно переведена на второй этап рассмотрения. 
Если не находите писем в электронной почте, в том числе в папке "Спам", Вы можете просмотреть их в разделе  ["Мой журнал"]( https://igov.org.ua/journal )

**Comment by Gesslow** [comment]
Спасибо за ответ! Но дело в том, что в разделе "Мой журнал" , после ввода номера заявки, система выдаёт сообщение, что заявка не найдена:((

**Comment by Gesslow** [comment]
Спам проверяю тоже регулярно.

**Comment by zolotovatatyana** [comment]
странно что не найдена. я вижу ее в системе. могу просить вас сделать скриншот из Моего Журнала и ошибку при поиске заявки по номеру? Я передам разработчикам информацию о проблеме

**Comment by Gesslow** [comment]
![igov](https://cloud.githubusercontent.com/assets/19761533/18668839/85353068-7f40-11e6-8c81-5d803e7fbe45.png)

**Comment by Gesslow** [comment]
И ещё, подскажите пожалуйста, а сколько всего этапов рассмотрения будет для данной заявки? Спасибо!

**Comment by zolotovatatyana** [comment]
Заявка рассматривается в два этапа:
1. предварительная проверка документов, после которой вносятся уточнения, исправления, и когда все в порядке - соцпомощь рассылает запросы по всем органам, чтоб подтвердить данные, которые вы внесли в заявление и декларацию
2. после получения ответов, производится расчет субсидии и выносится решение: назначить или отказать.

**Comment by Gesslow** [comment]
Спасибо Вам большое за информацию! Всего доброго.

**Comment by Gesslow** [comment]
Было приятно пообщаться.

**Comment by zolotovatatyana** [comment]
Взаимно :)
