### ISSUE TITLE
Звернення № 0-600240888 Реєстрація ФОП (Уточнення інформації про терміни виконання)

### ISSUE THREAD

**Issue by AMelnich** [e-government-ua/iForum#628]
Доброго дня, прошу повідомити мені терміни виконання звернення № 0-600240888 на послугу Державна реєстрація створення фізичної особи – підприємця.

**Comment by agerman-ua** [comment]
Добрый вечер, @AMelnich 
Гарантированных и точных сроков, к сожалению, нет. В среднем обращения обрабатываются до 4-х рабочих дней. Есть иногда редкие исключения, но это не система. Зависит от чиновника, если он начал обрабатывать то другие уже эту заявку не видят.
С ув. Август.

**Comment by AMelnich** [comment]
Спасибо за ответ. Но есть определенная неясность в том плане, что исходя из статуса заявки не видно принял ли чиновник мою заявку, и все ли в порядке с заявкой? Или через, например, 4 дня заявка может быть отклонена?

**Comment by AMelnich** [comment]
Заявка закрыта, спасибо.
