### ISSUE TITLE
Видача/заміна паспорта "В який день" не активне

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#63]
Iryna Hodovanets:
Доброго дня! Виникла проблема. 
При заповненні у "Видача/заміна паспорта громадянина України для виїзду за кордон" - поле "В який день Ви бажаєте звернутися до міграційної служби?" не активне
https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1634468280175382&offset=0&total_comments=10&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by dmitrijzabrudskij** [comment]
выберите район, куда будете подавать документы, и подтянется его график

**Comment by VadymVolos** [comment]
Iryna Hodovanets Побачила відповідь там, що потрібно просто вибрати район, а тоді вже й графік відображатиметься. 
Я, звісно, й без підказки це розуміла, кілька разів перепробувала. А поле з вибором дня все одно не активне!

![11209419_882819451787270_3882031749884363914_n](https://cloud.githubusercontent.com/assets/12669290/11003313/59783f50-84ba-11e5-9c6b-b3eb395964fa.jpg)

**Comment by dmitrijzabrudskij** [comment]
добавил очередь в это отделение дмс. можно записываться

**Comment by MariaDudnichenko** [comment]
Такой же случай только город Никополь, Днепропетровская обл. Помогите пожалуйста!
