### ISSUE TITLE
Звернення № 0-609763993 (Регистрация ФЛП)

### ISSUE THREAD

**Issue by TatianaKosh** [e-government-ua/iForum#630]
отправила сегодня заявку на регистрацию, она висит в статусе "в обробці", статус заявки не меняется, Звернення № 0-609763993

**Comment by TatianaKosh** [comment]
Звернення № 0-609763993, від 21.09.16 в 13:18 м. Харків

**Comment by agerman-ua** [comment]
Добрый вечер, @TatianaKosh 
Ваше обращение действительно в работе. 
Если у чиновников нет замечаний, обработка займёт максимум день-два. 
С уважением, Август.

**Comment by agerman-ua** [comment]
Добрый день, @TatianaKosh 
Вас зарегистрировали ещё 22.09.2016.
С ув.Август.
