### ISSUE TITLE
Ошибка при получении данных пользователя.

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#631]
> Адріан Добрєв
> После того как вставляю ключ прошла проверка и на странице ОШИБКА!
> Здорово. Потратил время на заполнение, а в итоге ошибка. На прошлой неделе друг точно так же "зарегистрировал" ФОП. И снова ножками нужно идти, старым дедовским методом. СПАСИБО

![14364637_1718118448513150_3853024826172477215_n](https://cloud.githubusercontent.com/assets/12669290/18714970/2277b078-8020-11e6-9b22-68deeb35a037.jpg)

https://www.facebook.com/igov.org.ua/posts/1695617230727153?comment_id=1759630340992508&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by Koffeek** [comment]
@VadymVolos ответил на ФБ
