### ISSUE TITLE
Назначение социальной помощи при рождении ребенка

### ISSUE THREAD

**Issue by AlinaDymar** [e-government-ua/iForum#632]
Добрый день. Оформили заявку 9 сентября, через несколько дней звонят мне с собеса Кировского р-н г.Днепр. Женщина представилась Людмилой Васильевой,  говорит,  что я должна прийти к ним с полным пакетом документов. Мол,все равно они должно увидеть документы в живую. Как с этим быть? В журнале статус -"Заявка подана -обработка этап 1".
Обращение № 0-577373856

**Comment by zolotovatatyana** [comment]
> с полным пакетом документов. 

[ П О С Т А Н О В А   від 27 грудня 2001 р. N 1751       Про затвердження Порядку призначення і виплати         державної допомоги сім'ям з дітьми](http://zakon5.rada.gov.ua/laws/show/1751-2001-%D0%BF )
 11.  Для  призначення  допомоги  при народженні дитини органу 
соціального  захисту  населення за умови пред’явлення паспорта або 
іншого документа, що посвідчує особу, подається: 

     1) заява одного з батьків (опікуна), з яким постійно проживає 
дитина,  що  складається  за  формою, затвердженою Мінсоцполітики; 
{   Абзац   другий  пункту  11  в  редакції  Постанови  КМ  N  355 
( 355-2015-п ) від 04.06.2015 } 
     2)  копія  свідоцтва  про  народження дитини (з пред’явленням 
оригіналу). 
 

Никакие другие документы требовать они не имеют права.

**Comment by AlinaDymar** [comment]
Проблема не в дополнительных документах, а в том что требуют моего визита в собес, электронной заявки недостаточно.
