### ISSUE TITLE
Звернення 0-591675495 (Реєстрація ФОП)

### ISSUE THREAD

**Issue by Cinotrus** [e-government-ua/iForum#634]
Доброго дня. 15.09 отримав лист на пошту про прийняття моєї заявки щодо реєстрації ФОП в обробку. На порталі iGov статус заявки значиться як закритий. На сайті ЄДР за номером заявки бачу такий результат: Реєстраційна дія: Державна реєстрація фізичної особи-підприємця; Дата дії: 15.09.2016; Документи: Відомості відсутні.

Інших листів мені не надходило. На звернення через форму на сайті iGov відповіді вже тиждень як немає. 

Скажіть, будь ласка, що з заявкою та який подальший алгоритм дій? Чи можете Ви повідомити про орієнтовний час очікування завершення процедури реєстрації, оскільки це терміново необхідно для розпочатку підприємницької діяльності.

Наперед дякую

**Comment by Cinotrus** [comment]
відповіді ні тут, ні через форму, ні через імейл мого територіального ЦНАПу, ні через його телефон, який просто не відповідає,  я так і не отримав. Електронність послуги завершилася сьогоднішнім походом у міський ЦНАП, котрий дав багато незабутніх вражень. Основне з яких - "приходьте завтра, у нас не працює база".

**Comment by agerman-ua** [comment]
Добрый вечер, @Cinotrus 
Простите за задержку, 
По обращению 0-591675495 проведена успешная регистрация ещё 15-09-2016.
По всей видимости сказались сбои в самом реестре минюста.
С уважением, Август.

**Comment by Cinotrus** [comment]
Доброго вечора!

Дякую за інформування. Позавчора вдруге фізично відвідав місцевий ЦНАП - там мені надали номер результату надання адмінпослуг, за яким отримав виписку з ЄДР. Але ще день після цього за моїм ПІБ у ЄДР запит результату не давав, хоча зараз усе працює. 

Свої коментарі щодо комунікації всередині системи я вже надав - зверніть, будь ласка, на це увагу. Адже ніхто не застрахований від виникнення подібних збоїв, а єдиним шляхом вирішення ситуації для мене виявився фізичний візит до чиновників (навіть Ваша відповідь мені інформації щодо того, що робити, не дала), що нівелює всю ідею електронності адмінпослуг.

Наперед дякую.

**Comment by agerman-ua** [comment]
Доброго дня, @Cinotrus 
Повністю погоджуюсь з тим, що завжди треба мати додатковий варіант комунікацій, на всяк випадок. Ми всією командою намагаємось органічно та системно це вирішувати. У багатьох послугах це вже реалізовано досить непогано.
Дякую за розуміння та вітаю з реєстрацією. 
Бажаю успіхів на ниві підприємництва.
З повагою, Август.
