### ISSUE TITLE
Обмін паспорта громадянина України в разі зміни (переміни) прізвища. Запрос 0-621573475.

### ISSUE THREAD

**Issue by Katee-ua** [e-government-ua/iForum#635]
Добрый день. Оформила вчера запрос на замену паспорта в связи со сменой фамилии. После нажатия кнопки "Отправить" выдало какую-то ошибку но на почту и в смс пришло подтверждении о успешной регистрации запроса в системе. Но сейчас по номеру ее не находит. Запрос № 0-621573475.

**Comment by Koffeek** [comment]
@Katee-ua Добрый день. Похоже, что при передачи заявки в базу данных произошел сбой. Приносим свои извинения. Просьба подать заявку ещ раз, только стоит учесть, что до 1 октября при оформлении паспорта по смене фамилии Вы получите паспорт-книжечку, а после 1 октября - ID-карту (на портале услуга сейчас готовится).

**Comment by Katee-ua** [comment]
Спасибо. Уже подала новую заявку но решила ее отменить - все-таки лучше получу с 1го октября ID-карту.
