### ISSUE TITLE
Звернення № 0-522695928 (Призначення соціальної допомоги при народженні дитини)

### ISSUE THREAD

**Issue by ArtyomLebid** [e-government-ua/iForum#636]
Добрый день. 

**18.08.2016 мы с женой подали заявку через iGov на получение помощи при рождении ребёнка.** Женой был открыт целевой счёт в ПриватБанке для получения данной помощи, авторизовались мы в iGov через её BankID также в Привате. 

**31.08.2016 мы получаем следующее сообщение:**
Зауваження по заяві 0-522695928
Необхідно уточнити дані, за коментарем: Вам необхідно прийти на вул.Радистів,8, каб. 2 з оригіналом паспорта та поставити підпис у заяві, так як відсутній електронний підпис. Та дооформіть заявку сканованою копією заяви з банку про відкриття соціального рахунку.

После этого, через форму "Маю питання щодо мого звернення" я оставил вопрос, общий смысл которого сводится к - в чём смысл оформления помощи онлайн, если всё равно матери необходимо искать, возможность оторваться от ребёнка и куда-то ехать. Также, для каких целей нужны какие-то "заявы с банка", если мы авторизовались через BankID и банк уже должен был передать всю необходимую информацию по заявителю?

**Какое-то время ничего не происходило. Однако 06.09.2016 в Журнале появилась новая запись:** 
Ваша заявка №0-522695928 змiнила свiй статус на обработка этап 1.

Подскажите, пожалуйста, что происходит с нашим обращением? На данном этапе прошло 20 дней с момента изменения его статуса. Больше никаких изменений не происходило.

**Comment by annastolbova** [comment]
Добрый день, на данный момент необходимо будет обратиться в АНД район лично для подписания заявления. В дальнейшем измениться сама схема взаимодействия с УПСЗН, но по существующей заявке необходим визит по адресу: вул.Радистів,8, каб. 2
