### ISSUE TITLE
Запрос 0-621573475. (смена паспорта) Не могу отменить.

### ISSUE THREAD

**Issue by Katee-ua** [e-government-ua/iForum#637]
Пытаюсь отменить запрос на смену паспорта. Пишу: "Прошу відмінити моє звернення. Планую з 1го жовтня подати запит на отримання ID-картки."
Но мой запрос продолжает обрабатываться, и меня сегодня ждут в указанное время и т.д. 
Ошибка следующая : {"code":"BUSINESS_ERR","message":"Entity with id=394263 does not exist"}

**Comment by Koffeek** [comment]
@Katee-ua Ваша заявка отменена. Запись на ID-карту пока закрыта, т.к. Кабмин не принял размер админсбора за его оформление.
