### ISSUE TITLE
Обращение 0-621870179 (Регистрация ФЛП)

### ISSUE THREAD

**Issue by RomnS** [e-government-ua/iForum#638]
Добрый день. Получил отказ по заявке 0-621870179. Комментарий: Неверный ЭЦП. Без подписи заявка не была бы принята, т.е. заявку я подписывал. Полученная электронно-цифровая подпись на уполномоченных сайтах проходит все проверки. Хотелось бы понять - что имеется в виду? Не был подписан файл о упрощенной системе налогообложения или другая причина?

**Comment by agerman-ua** [comment]
Добрый вечер, @RomnS 
В Вашем случае чиновник получил информацию о наличии ЭЦП но с соответствующей отметкой о некорректности. Вам необходимо переподать заново заявку. И можно указать тут её номер. Чтобы можно было убедиться в отсутствии проблемы до того как обращение будет принято в работу. Причина скорее всего была на стороне сервиса наложения подписи.
С уважением, Август.

**Comment by RomnS** [comment]
Добрый день. Заявка 0-647175786

**Comment by agerman-ua** [comment]
Добрый день, @RomnS 
Заявка уже в работе. Проблемы с ЭЦП не наблюдаю.
C уважением, Август.
