### ISSUE TITLE
Заявка 0-651634869 (Держреєстрація ФОП)

### ISSUE THREAD

**Issue by lena146146** [e-government-ua/iForum#639]
Заявка  0-651634869. Держреєстрація ФОП. м. Харків. Завку було подано та прийнято в обробку 1.10.2016, Будь ласка. коли чекати відповіді? (Форма "Маю питання" на питання не выдповідає)

**Comment by agerman-ua** [comment]
Доброго дня, @lena146146 
Так. Ваше звернення було зареєстровано 01.10.2016.
На вихідних обробка звернень урядовцями не проводиться.
Приблизний термін опрацювання 3-4 дні. Вихідні можуть додати строк.
У Вашому випадку (реєстрація ФОП) якщо відсутні зауваження то відповідь відразу про результат. 
З повагою, Август.

**Comment by lena146146** [comment]
Дякую)

**Comment by lena146146** [comment]
Моя реєстрація вже відбулася 5.10.2016 (я перевірила через безкоштовний запит Міністерства юстиціі), але ніяких листів на пошту не було (у спамі також)). Будь ласка, у чому справа?

**Comment by agerman-ua** [comment]
Все нормально.
Як Ви можете впевнитись перевіривши в розділі "Мій журнал" Ваше звернення на порталі ще не закрито. 
Реєстраційні дії провів реєстратор, а тепер отримавши підтвердження від нього адміністратор ЦНАПу обробить Ваше звернення на порталі, після чого Ви й отримаєте окремого листа.

**Comment by lena146146** [comment]
Дякую, мабуть, дуже поспішаю))

**Comment by lena146146** [comment]
Листа досі немає. Коли чекати на відповідь? (у мого знайомого вся процедура реєстрації тут зайняла дві доби. Мабуть тому я очікувала і для себе геть інші терміни).

**Comment by agerman-ua** [comment]
Добрий день. 
Повторюю. Ви вже зареєстровані. 
Ще 01.10.2016.
Статус на порталі вже Вам ніяк не заважає.
Тобто ця частина процесу реєстрації просто зручний інструмент отримання повідомлення від реєстратора. 
Чи правильно я Вас зрозумів?
З повагою, Август.

**Comment by lena146146** [comment]
01.10.2016 було зареєстровано мою заявку на сайті на реєстрацію ФОП. А 05.10.2016 я вже побачила свою реєстрацію як ФОП на сайті міністерства юстиції. Ось тут https://usr.minjust.gov.ua/ua/freesearch. Проте ніяких листів від igov про те, що реєстрація відбулася, я не отримала. 
Тож, що ви маєте на увазі: "Ви вже зареєстровані"?

**Comment by lena146146** [comment]
Мене цікавіть, коли завершиться процес реєстраціі мене, як ФОП). На якому етапі цей процес? Він має бути завершений  надсиланням листа з випискою з державного реєстра, так?

**Comment by agerman-ua** [comment]
Ні. Для Вас він завершений отриманням підтвердження про реєстрацію безпосередньо з реєстру.
Ви обов'язково отримаєте лист з порталу, але після того як урядовець закриє Ваше звернення.

**Comment by lena146146** [comment]
"Ні" - це відповідь на моє останнє питання? Не зрозуміла: "завершений надсиланням листа з випискою з державного реєстра," та "завершений отриманням підтвердження про реєстрацію безпосередньо з реєстру"  - не одне й те саме? І коли урядовець закриє звернення???

**Comment by lena146146** [comment]
Все зрозуміла. Дякую).

**Comment by lena146146** [comment]
До заяви про реєстрацію я додавала заяву про перехід на спрощену систему оподаткування. У даних про взяття на облік платників податку моє прізвище є, а у реєстрі платників единого податку  - немає. Можливо, це відображатиметься з 01.11.2016....  До кого звертатися з цим питанням? Де повинна відображатись інформація про систему оподаткування та заявлену групу платника податку? Чи зареєстрували мене саме так, як треба? Ця інформація буде у тому довгоочікуваному листі?)

**Comment by agerman-ua** [comment]
Ні. Про систему оподаткування там не буде інформації.
Тільки про реєстрацію в реєстрі юросіб.
Інформацію про систему оподаткування треба дивитися на порталі податкової служби.
https://cabinet.sfs.gov.ua/cabinet/faces/index.jspx;CABINET=YQSwJFYqTb0DFx1ZbXVBsfdra0pshaj336RxdlnQyEM-6VkZ3tTO!-949193641

**Comment by Propeller-SV** [comment]
@lena146146 у довгоочікуваному листі інформації про систему оподаткування не буде. Перевіряти можете за ІПН за лінком з попереднього повідомлення. Зможете себе знайти після успішної реєстрації вашої заяви в вашій податковій одразу, а не з 01.11.2016. Тобто якщо вас зараз в базі нема, то вашу заяву не прийнято. Краще за все зателефонувати в податкову за місцем реєстрації і запитати. І зробити це треба протягом 10 днів після реєстрації ФОП. Інакше перейти на спрощену систему ви зможете лише з наступного кварталу, тобто з 01.01.2017. А до того будете змушені працювати на загальних умовах оподаткування.
[От така історія](https://github.com/e-government-ua/iForum/issues/550)
