### ISSUE TITLE
Субсидія - відхилили із за повторно, але пропонують заповнити повторно

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#64]
Татьяна Сбоева:
Добрый день, сделала как показано на картинке- просит " Password (forgot password)"- и на этом все... Может здесь получу ответ. Подавала заявку на субсидию. Не разобралась, период стоял по умолчанию, я поставила другой(год, но дата подачи минус год). Вобщем неправильно. Пришел отказ с обоснованием неправильной даты. Подала повторно, уже правильно. Через неделю пришел отказ- : На жаль, Ваше звернення щодо отримання
субсидії на оплату житлово-комунальних послуг відхилене через недостатню або неправильну інформацію..
Причина: повторно надано пакет документів
Звертаємо увагу, Ви можете заповнити заявку
повторно на порталі iGov.org.ua Это как????? Отказали из-за повторной подачи, и снова- приходите повторно? Очень бы хотелось получить ответ. заявка 11466175

https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1634150363540507&offset=0&total_comments=10&comment_tracking=%7B%22tn%22%3A%22R0%22%7D

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой это район?

**Comment by VadymVolos** [comment]
Татьяна Сбоева:
Спасибо. Сегодня перезвонили, сказали что субсидию назначили, сказали куда обратиться за документом.

**Comment by dmitrijzabrudskij** [comment]
так за документом ходить не нужно
они его на имейл должны отсканированный прислать
какой это район все-таки был?

**Comment by VadymVolos** [comment]
Автор не побажала написати свій район, можете їй написати особисто і запитати.
https://www.facebook.com/lolitasfs
