### ISSUE TITLE
Звернення № 0-507776071 щодо отримання субсидії на оплату ЖКП

### ISSUE THREAD

**Issue by Gesslow** [e-government-ua/iForum#640]
Здравствуйте! 

Звернення **№ 0-507776071** щодо отримання субсидії на оплату житлово-комунальних послуг. Дніпропетровськ, дата та час звернення -> 15.08.2016р. в 16:38.

Контакти підрозділу соцзахисту, який обробляє Ваше звернення:
УПСЗН Новокодацького (Ленінського району), м. Дніпропетровськ.
Адреса: 49000, Дніпропетровськ, вулиця Трудова, 1-А
Графік роботи: понеділок-п’ятниця: з 8.00 до 17.00
Телефон(и): (056) 775-55-86

Подскажите пожалуйста на каком этапе рассмотрения находится данная заявка и когда можно ожидать какого-либо решения по ней?
Спасибо!

**Comment by zolotovatatyana** [comment]
Добрый день. 
Ваше обращение на втором этапе рассмотрения. Документы прошли предварительную проверку и ждут принятия решения о назначении субсидии.
За подробностями можете звонить напрямую в УПСЗН

**Comment by Gesslow** [comment]
Cпасибо большое за информацию. Я бы с удовольствием пообщался с сотрудниками УПСЗН, да вот только дозвониться туда никак((
