### ISSUE TITLE
Обращения через e-contact.dp.gov.ua не доступны к просмотру

### ISSUE THREAD

**Issue by pavlentij** [e-government-ua/iForum#641]
Я отправлял ряд обращений через e-contact.dp.gov.ua и они автоматически попали в igov.
В них значится мой емейл tkachenko.pasha@gmail.com, также этот емейл используется в моём профайле на igov, который создался при авторизации через bankid/приватбанк.

Но обращения созданные через e-contact.dp.gov.ua не доступны для отслеживания статуса.

Подскажите как можно связать их с моим основным аккаунтом на igov?

**Comment by msvidran** [comment]
@pavlentij Добрый день. В данный момент статус обращений, которые поданы через e-contact.dp.gov.ua, невозможно просмотреть (задача находится в разработке). Вы можете презвонить в колл-центр ДМР по одному из телефонов (+380 56 732 12 12, ‎+390 95 732 12 12, ‎+380 96 732 12 12, ‎+380 73 732 12 12) и уточнить на какой стадии Ваша заявка.
