### ISSUE TITLE
Заявки 0-654394137,0-654441076,0-654481406 (Держреєстрація ФОП)

### ISSUE THREAD

**Issue by ksystemscomua** [e-government-ua/iForum#642]
Фізичні особи отримали сертифікати ЕЦП в нашому АЦСК ТОВ "КЛЮЧОВІ СИСТЕМИ" для держреєстрації ФОП. Ними було подано заяви №№ 0-654394137, 0-654441076, 0-654481406, всі від 03.10.16. Під час авторизації та підписання, зі слів користувачів, помилок не виникало.
05.10.2016 надійшла однотипна відповідь:
"Зауваження по заяві №... Необхідно уточнити дані, за коментарем: Термін дії ЕЦП відсутній".
Проте, в сертифікатах завжди вказується термін їх дії, у цих користувачів це з 29.09.2016 до 29.09.2017.
Хочемо з'ясувати, в чому причина помилки.

**Comment by agerman-ua** [comment]
Доброго дня.
Дякуємо за таку кліентооріентованість.
Дійсно були отримані вказані звернення і дійсно по ним, при перевірці, не видає дат початок/закінчення дії.
Оскільки всі вони були сформовані на протязі однієї години скоріш за все це сталося під час накладання ЕЦП на заяву та пов'язано з сервісом його накладання. 
Після того у жодному зверненню, з ЕЦП, не було відмічено таких особливостей. 
Всі проблемні звернення будуть закриті а заявникам будуть відправлені листи, з проханням їх переподати використовуючи той же самий ЕЦП.
З повагою, Август.

**Comment by ksystemscomua** [comment]
Дякуємо за оперативність.
Заяви подали заново, ось нові №№ 0-662957921, 663010278, 0-663070658, щоб була можливість їх відслідкувати. Звертайтесь, якщо буде потрібна додаткова інформація щодо сертифікатів. Ми зацікавлені у вирішенні можливих проблем.

**Comment by agerman-ua** [comment]
Зараз перевіримо.

**Comment by agerman-ua** [comment]
На жаль ситуація повторилась.
Беру тайм-аут щоб сформулювати точніше проблему.

**Comment by ksystemscomua** [comment]
Доброго дня, Августе. Пробував ще один користувач зареєструвати ФОП з сертифікатами АЦСК ТОВ "КС", та сама помилка. Чи вдалося з'ясувати її причину?

**Comment by agerman-ua** [comment]
Доброго дня.
Вже відкинули половину можливих підстав.
Є дві групи розробників. 
Перша група (відповідальна за перевірку ЕЦП) обгрунтовано відкинула всі претензії до сервісу.
Зараз працюють ті, хто обробляє отриманий від сервісу результат і видають урядовцю готовий документ при перевірці ЕЦП.
Ми пам'ятаємо що чекають живі люди. Відразу по факту виявлення причини та усунення проблеми урядовці почнуть обробку всіх звернень, а я Вас відразу попереджу про це.
З повагою, Август.
