### ISSUE TITLE
Черга на отримання загранпаспорта

### ISSUE THREAD

**Issue by dayana021078** [e-government-ua/iForum#643]
З 14. вересня намагаюсь записатися у електронну чергу у м. Дніпрі.
У вересні місць вже не було, а про чергу на жовтень пишуть що вона буде відкрита після узгодження з відділеннями ДМС.

Сьогодні 07 жовтня. При спрбі зробити заявку читаю таке: "У зв'язку з набуттям чинності ЗУ 1474-VIII, черга на жовтень буде відкрита лише після погодження режиму роботи ДМС"

Чи існує ця електронна черга взагалі?

**Comment by annastolbova** [comment]
з 1 жовтня мав змінитися розмір адмінзбору, який сплачується за оформлення паспорта.
Але він невідомий до того моменту, як кабінет міністрів прийме відповідний наказ. 
Маємо надію, що це буде відбудеться найближчим часом.
Як тільки він вийде, то ми відкриємо чергу на жовтень, сподіваємось, що це буде вже наступного тижня.
Спробуйте зареєструватися пізніше.
Дякуємо за порозуміння.

**Comment by dayana021078** [comment]
Дякую

**Comment by dayana021078** [comment]
Нарешті відкрилася черга та я вибрала дату у яку зможу прийти до ДМС. Але що я бачу в тексті листа, який підтверджує реєстрацію моєї заявки: "Для отримання реквізитів для сплати Вам потрібно з'явитись у підрозділ ДМС за 15-20 хвилин до обраного часу та сплатити за послугу. "
Що відбувається? Реквізити для сплати адмінсбору є такою таємницею, яку можна отримати тільки з рук у руки? Я розумію, в реквізитах має бути номер ДМС куди я звертаюсь, але я його ВЖЕ вибрала. Чому не можна ці реквізити вислати у листі де є номер моєї заявки? Чому потрібно бігати навколо ДМС у пошуках банку, якщо сплатити можна заздалегідь? Чому я повинна користуватися послугами того банку що буде поряд (або у самому приміщенні ДМС), а не того який виберу сама? Це є профанацією самої ідеї  електронної черги.

**Comment by dayana021078** [comment]
Також невідомо скільки тепер складає адмінсбір.

**Comment by Koffeek** [comment]
@dayana021078 наразі закордонний паспорт оформлюється за умови сплати адміністративної послуги, після прийняття КабМіном змін до постанови по закордонному паспорту оформлення буде відбуватись при сплаті адмінсбору (інші реквізити та інша сумма). Дата прийняття КабМіном постанови - невідома, тож вони можуть прийняти її завтра, а Ви замовили візит на 25 жовтня. Сплату не буде зараховано і Вам доведеться сплачувати ще раз, та писати заяву на повернення своїх грошей. Наврядчи Ви будете в захваті від такої ситуації. Варіант отримання реквізитів у день візиту був компромісним для поновлення електронної черги, оскільки інакше ДМС не готово було співпрацювати до виходу постанови КабМіну.

**Comment by dayana021078** [comment]
Зрозуміло. Дякую за відповідь.
