### ISSUE TITLE
Реєстрація ФОП [Feature Request|Usability improvement]

### ISSUE THREAD

**Issue by ArtemKobz** [e-government-ua/iForum#645]
Вже зареєстрований як ФОП, авторизувався через BankID.
Вважаю що система має повідомити що ФОП за поточним ІПН вже зареєстровано, та не запитувати жодних додаткових даних. 

Дякую! :)

**Comment by agerman-ua** [comment]
Доброго дня, @ArtemKobz 
Повністю згоден. Дійсно непогана пропозиція. 
Ми вже самі поставили собі таку задачу. 
Наразі тільки стримують ресурси розробників та питання "нащо подавати звернення якщо Ви вже зареєстровані?".
Але з часом, коли будуть дійсно великі обсяги, ми обов'язково, прийдемо до цього.
З повагою, Август.
