### ISSUE TITLE
реєстрація ФОП 

### ISSUE THREAD

**Issue by yuliyaherasymova** [e-government-ua/iForum#646]
Інструкція досить дивна - таке враження, що розрахована на досвідчених підприємців, які вже не вперше реєструються, як фізична-особа підприємець.  Доходиш до фрази"оберіть систему оподаткування та завантажте скан-копії відповідних заяв;
оберіть вид(и) діяльності - згідно до КВЕД;" без відповідних посилань на законодавство, чи хоча б натяку, де це можна прочитати, і розумієш, що зареєструватися, як фоп зможе тільки досвідчений юрист

**Comment by agerman-ua** [comment]
Доброго дня.
Обсяг інструкції досить обмежений.
Для загальної освіти треба користуватися доступними інтернет-ресурсами.
Послуга реєстрації - це "остання крапка". Тобто Ви вже точно знаєте що Вам потрібно і отримуєте послугу.
Мета  інструкції - знаючи що потрібно, підказати як це зробити саме на порталі.
У випадку коли заявник не розуміє що таке КВЕД або система оподаткування - краще звернутися до спеціалістів (бухгалтерів, аудиторів) які і беруть на себе інформаційну складову процесу.
З повагою, Август.
