### ISSUE TITLE
На многих услугах выскакивает ошибка

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#647]
после того как сменили интерфейс все время выскакивает ошибка при выборе многих услуг

![image](https://cloud.githubusercontent.com/assets/8410116/19223510/70d95ec0-8e7a-11e6-80cc-67a0b8e4c856.png)

а к примеру при выборе загранпаспорта не выскакивает

после нажатия ОК в выскочивгем дмалогвом окне пишет:
Крок 1. Ви обрали Всю країну.

**Comment by bvv4ik** [comment]
![image](https://cloud.githubusercontent.com/assets/4208821/19311647/f2de7f58-9097-11e6-9500-5658e80864de.png)

**Comment by bvv4ik** [comment]
все нормально открывается...

нужен точный сценарий воспроизведения ошибки(если она вообще воспроизводима), что-б чтоб было понимание что именно нужно ченить

важно так-же понимать какой обозреватель, операционка и все-ли нормально с сетью(например не глючит-ли прокся или анибанер или еще какая-то ерунда на компе)

а еще стоит почистить куки в обозревателе и попробовать в другом обозревателе..

**Comment by AndreyPopovNew** [comment]
Windows 10
Хром
куки как раз чистил в понедельник.



если зайти на сайт без логина, то выдает такое:
![image](https://cloud.githubusercontent.com/assets/8410116/19312069/96dd62b2-9099-11e6-81aa-233f3fbac1b2.png)

**Comment by AndreyPopovNew** [comment]
@bvv4ik попробовал на другом компе, где вообще НИ разу не запускался портал, в MS IE:
"все та же фигня"

![image](https://cloud.githubusercontent.com/assets/8410116/19346861/45d5343e-914e-11e6-85f5-8d3e67221f16.png)

**Comment by AndreyPopovNew** [comment]
@GrekD @dubilet @Koffeek @bvv4ik 
уже неделя прошла, а кроме **отписки** "почистите куки" больше никаких действий не видно.

пусть проект и аолонтерский, но таким отношением вы просто отпугиваете людей от пользования порталом.

если он выдает ошибки, а на сообщения об ошибках никто не реагирует - то люди не будут пользоваться порталом.

**Comment by GrekD** [comment]
@AndreyPopovNew извините если не очень быстро реагируем, это связано с большим потоком крупных и мелких задач, приоритет которых меняется ежедневно.
Те задачи или баги, которые уже попали в работу конкретному исполнителю, можете отслеживать здесь:
https://github.com/e-government-ua/i/issues

По багу:
окно которое показывается если Вы не авторизованы (на незапущенной услуге) - правильное
по ошибке которая вылазит в случае авторизованности пользователя (на незапущенной услуге) - это баг.
Передала в работу разработчикам с описанием воспроизведения ошибки:
1. авторизоваться подБанкИД или ЕЦП
2. зайти в незапущенную услугу
вылазит ошибка
Невідома помилка: TypeError:Cannot read property 'nID_Server' of null

**Comment by AndreyPopovNew** [comment]
@GrekD думаю, что когда на 30-40% услуг из списка выдает ошибку - то это суперприоритетная задача?

тем более в вашем описании проблемы есть неточность.

когда заходишь НЕавторизованным, то на указанных услугах выскакивает:
Крок 1. Ви обрали Всю країну.
На жаль, поки що у Вашому регіоні неможливе надання цієї послуги в електронному вигляді.


откуда берутся в данном случае данные про регион?

**Comment by GrekD** [comment]
@AndreyPopovNew 
у сожалению, приоритеты определяю не я,  а наш главный разработчик. Проблема передана и входит в топ-10 доработок.

> откуда берутся в данном случае данные про регион?

ни откуда, поэтому там и пишет про всю країну - это просто стандартная фраза для незаупущенной услги

**Comment by AndreyPopovNew** [comment]
@GrekD добавлю еще ошибку.

выбираем к примеру:
- Паспорт громадянина України
- ставим фильтр Днепропетровская область, Днепр
![image](https://cloud.githubusercontent.com/assets/8410116/19732597/e5aeafd4-9ba9-11e6-9aac-caaaf2458075.png)
(лирическое отступление - можно сделать, чтобы в списке Связанные услуги серые квадратики подсвечивались соответсвующим цветом - какие услуги доступны, какие скоро, а какие недоступны)
- снова жмем меню Услуги
- и выбираем Индивидуальный налоговый номер
получаем
![image](https://cloud.githubusercontent.com/assets/8410116/19732677/3b1d8454-9baa-11e6-8b6e-c4939b8753e5.png)

**Comment by GrekD** [comment]
@AndreyPopovNew  спасибо за  описание
передали уже так же в проработку разработчику
