### ISSUE TITLE
Фильтр - выбор организации пустой, "залипает" выбор города, при сворачивании фильтра он не сбрасывается

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#648]
1. это так задумано, что в фильтре выбора организации пусто?

![image](https://cloud.githubusercontent.com/assets/8410116/19223586/f61c8d2c-8e7b-11e6-9712-4f35cd7483b3.png)

2, 
- если включить фильтр, выбрать область (и выбрать город), 
- потом перейти на закладку Мой Журнал
- вернуться на закладку Услуги то:
  а) все фильтры можно выбирать, нажам на стрелку слева поля, кроме фильтра город. пока снова не выберешь область
  б) если был выбран город, то его значение сбрасывается и получается п.а)
1.  при сворачивании фильтра, нажатием в поле фильтра ^ фильтр не сбрасывается.

**Comment by AndreyPopovNew** [comment]
фильтр послуг поменялся, а проблемы остались.

но добавились новые:
фильтрует неверно - выбрал Днепропетровская область, Днепр - снятие с учета РВК, постановка на учет в РВК, изменени данных в РВК - есть в списке, когда кликаешь на них, то на следующей странице пишет - "недоступна в вашем регионе"

**Comment by AndreyPopovNew** [comment]
- выставили параметры Фильтра - отфильтровали.
- потом перешли в раздел Мой Журнал
- снова переходим на Услуги и:

а) если фильтр был открыт, то получаем фот такую картинку:
![image](https://cloud.githubusercontent.com/assets/8410116/19311850/b6483fba-9098-11e6-8374-1a994fe17fe1.png)

б) если фильтр был закрыт, то или такая каритнкак как выше или пишет "Услуг не надено"

**Comment by AndreyPopovNew** [comment]
@GrekD @dubilet @Koffeek @bvv4ik 
фильтр будут доделывать или пусть глючит дальше?

может лучше его совсем убрать? кому он нужен в таком виде?

**Comment by GrekD** [comment]
@AndreyPopovNew доделываем
на тестовом вроде уже все ок, в течении недели будет на боевом

**Comment by AndreyPopovNew** [comment]
@GrekD стало по-лучше. по крайней мере теперь при включении области и города число доступных услуг корректируется.

хотя все равно попадают услуги, которые недоступны!
Днепропетровская
Днепр

к примеру Справка о месте регистрации и составе семьи (Форма 3)


также непонятно ЗАЧЕМ при выборе из отфильтрованных услуг СНОВА просит сделать выбор области и города ?
можно этот вопрос решить? чтобы на услугу переходило уже с параметрами фильтра?

**Comment by GrekD** [comment]
@AndreyPopovNew  добрый день

> хотя все равно попадают услуги, которые недоступны!
так и задумывалось. зачем показывать человеку список услуг, которые недоступны для выбранного нас.пункта?

> также непонятно ЗАЧЕМ при выборе из отфильтрованных услуг СНОВА просит сделать выбор области и города ?
потому что не все переходят на услугу после фильтра, некоторые напрямую переходят.

**Comment by GrekD** [comment]
я сразу неправильно поняла (насчет формы 3)
согласна, что это ошибка. Напишу разработчикам

**Comment by AndreyPopovNew** [comment]
@GrekD я понимаю, что не все переходят из фильтра.

но по логике - если я **отфильтровал** и _выбрал_ услугу, которая доступна именно в нужном городе - то переход к услуге **из фильтра** уже должен содержать данные фильтра.

ведь фильтр отсортировал именно доступную для данного региона и города услугу - так зачем снова это **еще раз** подтверждать?
