### ISSUE TITLE
Звернення 0-646369528 (Реєстрація ФОП)

### ISSUE THREAD

**Issue by Roma-Lis** [e-government-ua/iForum#649]
Заява створена 30.09.2016. Досі в статусі "Надання послуги". Як довго і чому вона може в ньому залишатись?

**Comment by agerman-ua** [comment]
Добрий день, @Roma-Lis 
Ваше звернення на порталі дійсно не закрито та в має статус "в роботі".
Але Вас зареєстровано ще 2016.10.04. Вітаю.
Зв'язатися з урядовцями поки не вийшло щоб з'ясувати причини затримки обробки процесу реєстрації на порталі.
З повагою, Август.
