### ISSUE TITLE
Оформление социальной помощи при рождении ребенка

### ISSUE THREAD

**Issue by AndreyPotapenk** [e-government-ua/iForum#65]
Добрый день!
13.10.15г. мною на сайте igov.org.ua была оформлена заявка на получение социальной помощи при рождении ребенка. В тот же день с адреса : "admin@igov.org.ua" <dnipro.egov.ua@gmail.com было получено письмо с подтверждением: "Ваша заявка 8270572 прийнята!
Ви завжди зможете переглянути її поточний статус у розділі "Статуси". Також на кожному етапі Ви будете отримувати email-повідомлення." 
До настоящего времени никаких других действий по данной заявке №8270572 не происходит.
В разделе "Статуси" на сайте данная заявка имеет следующий статус: 
"Статус 2015-10-13 14:31:35.825	Заявка подана".
Прошу разъяснить мои дальнейшие действия, т.к. на сайте никакой информации невозможно найти, либо ускорить выполнение моей заявки.

**Comment by dmitrijzabrudskij** [comment]
добрый день
какой район выбирали при подаче?

**Comment by AndreyPotapenk** [comment]
Жовтневый район города Днепропетровска

**Comment by AndreyPotapenk** [comment]
Жовтневый район города Днепропетровска

06.11.2015 11:22, dmitrijzabrudskij <notifications@github.com>
>добрый день
> какой район выбирали при подаче?
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/e-government-ua/iForum/issues/65#issuecomment-154353396


-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by AndreyPotapenk** [comment]
Не понял смысла троеточия...

**Comment by AndreyPotapenk** [comment]
Когда можно ожидать реакции на мой запрос?

**Comment by dmitrijzabrudskij** [comment]
реакция пошла с того момента как я здесь написал. отпишусь либо сюда, либо с вашей женой созвонится соцзащита (по их словам, дозвониться они ей не могут)

**Comment by AndreyPotapenk** [comment]
Уже созвонились. Спасибо!
