### ISSUE TITLE
UX покращити на порталі.

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#650]
UX (User Experience)

Привіт! Я не знаю як інших, але мене дратує, коли я хочу зайти на портал і просто обрати послугу потрібну зі списку, зараз замість послуги мені дають купу макулатури (тексту) щоб я гортав і його читав. Але я не хочу читати, мені треба просто обрати послугу.

Зробіть якось зручніше, щоб кому потрібно зразу потрапляли на послугу потрапляли на послугу, а кому нема чого робити і хоче почитати, дати можливість читати.

Можемо разом подумати, і придумати щось.

Наприклад я хочу замовити Паспорт громадянина, натискаю на цей пункт, а мені там дають щось довге читати. І саме головне на тій сторінці так і не видно а де ж лінк на саму послугу, Якщо дуже уважно читати то в 5 пункті можна побачити лінк на послугу. Але ми у людей забираємо купу часу, їм треба читати і видивлятися, шукати лінки. Лінки на послугу мають бути зразу згори.

**Comment by zolotovatatyana** [comment]
![image](https://cloud.githubusercontent.com/assets/17428210/19260560/38394516-8f93-11e6-8547-b3952e5ea1c2.png)

**Comment by VadymVolos** [comment]
Я ж закрив цю таску. У UX дизайні є поняття баннерна сліпота. Тому з точки зору UX, якщо користувач інтуїтивно не знайшов, то є куди поліпшувати. Якщо розробник користувачу починає малювати стрілочки, UX треба поліпшувати. Це моє імхо.
