### ISSUE TITLE
Звернення 0-668776231 (Реєстрація ФОП)

### ISSUE THREAD

**Issue by Gordtata** [e-government-ua/iForum#651]
Доброго дня! 07.10.16 зареєстрували звернення, але відповіді до сьогодні не маємо. Чи можливо перевірити у якому стані реєстрація і дізнатися коли вона можливо буде? Дуже дякую.

**Comment by agerman-ua** [comment]
Доброго дня. @Gordtata 
За звичай це триває 3-4 дні. Від подання до закриття. Але, як у Вашому випадку, бувають затримки.
До кінця тижня опрацюють.
З повагою, Август.
