### ISSUE TITLE
Неработающая кнопка "Оплатить" (Державна реєстрація змін до відомостей про ФОП)

### ISSUE THREAD

**Issue by Danil-Seledkov** [e-government-ua/iForum#652]
Доброго дня.
Виникли **труднощі з проведенням оплати за зміну реєстраційних даних ФОП** по
**Зверненню № 0-671559768, від 07.10.2016 р. о 23:36 год., від Селедкова Данила Володимировича,
м. Горишні Плавні, Полтавська обл., 39800, Україна**.
Кнопка "Оплатить" у листі, який надійшов у відповідь, не працює в жодному браузері. Спроби сплатити здійснював у наступних браузерах:

- Google Chrome 53.0.2785.143 m (64-bit);
- Mozilla Firefox 49.0.1;
- IE - версія на знімку екрану;
- Microsoft Edge 25.10586.0.0;
- Chrome для Android 53.0.2785.124.

Також у Microsoft Edge є можливість увійти у свій обліковий запис тільки за допомогою BankID, але кожного разу система видає помилку "**undefined**". Така ж помилка з'являється і у IE. При використанні ЕЦП у IE з'являється помилка, що наведена у знімку екрану у попередньому повідомленні.
Як мені здійснити оплату? Прошу допомогти вирішити це питання.

![2016-10-12 1](https://cloud.githubusercontent.com/assets/22791955/19309534/217e3056-908e-11e6-976c-b33b25f3498f.png)

![2016-10-12 2](https://cloud.githubusercontent.com/assets/22791955/19309535/21815d62-908e-11e6-9100-985c7ae2ca01.png)

**Comment by agerman-ua** [comment]
Доброго дня. @Danil-Seledkov 
А Ви використовуєте кнопку з поштової скиньки або з розділу "Мій журнал"?

**Comment by Danil-Seledkov** [comment]
Благодарю за скорый ответ. В разделе "Мій журнал", т.к. в письме никакой кнопки или ссылки для оплаты нет.

![2016-10-12 3](https://cloud.githubusercontent.com/assets/22791955/19316447/20e2d1e4-90aa-11e6-99ac-688678c81837.png)

**Comment by agerman-ua** [comment]
Так. Добре. Дуже дякую за скріни.
Кнопка є і там і там. Є ймовірність того, що вона не працює саме в розділі "мій журнал", бо головна місія цього розділу - незалежно від поштових сервісів зберігати всі поштові повідомлення від порталу та зауваження від урядовців.
Прошу самостійно знайти опцію на поштовому сервісі для відображення графічних елементів у листах кнопка в листі є.
Чекаю на відповідь.
З повагою, Август.

**Comment by Danil-Seledkov** [comment]
На Freemail от Ukr.net возможности скрывать изображения нет вовсе. Этот же ящик добавлен в Gmail для Android. Там включено отображение.
Для наглядности ниже добавил снимок экрана с письмом от другого адресата, от которого изображения скрыты, см. кнопку "Показать картинки" под шапкой. Если изображение отображаются, то такой кнопки нет. И раз уж Gmail не видит кнопку "Оплатить", то, скорее всего, её там нет.

![screenshot_20161013-112222](https://cloud.githubusercontent.com/assets/22791955/19341809/c0e0bdb8-9137-11e6-81a0-91e5cd99c715.png)

![screenshot_20161013-112619](https://cloud.githubusercontent.com/assets/22791955/19341999/9e24f0b8-9138-11e6-94ce-65c04c947d8b.png)

![screenshot_20161013-112648](https://cloud.githubusercontent.com/assets/22791955/19342008/a799c5ce-9138-11e6-95e0-558dcc7d3b3c.png)

![screenshot_20161013-112712](https://cloud.githubusercontent.com/assets/22791955/19342011/adcc669a-9138-11e6-9af2-33b5d4236cb2.png)

**Comment by Danil-Seledkov** [comment]
Добрый день, Август Герман.
Можно ли мне рассчитывать на решение вопроса с кнопкой здесь или нужно обращаться непосредственно физически к госрегистратору?

**Comment by agerman-ua** [comment]
Добрый день, Данил (@Danil-Seledkov)
Функционал кнопки из раздела "Мой журнал" является дополнительным. Его восстановление в ближайшие день-два ожидать не стоит.
Кнопка точно была сформирована и отправлена в письме на Ваш почтовый ящик. Что именно ukr.net делает с объектами аналогичными платёжным кнопкам - вопрос остался открытым, но благодаря скринам однозначно видно что в письме упоминания о ней нет. Но сомнений в том что было отправлено у меня нет.
Быстро можно решить данный вопрос только двумя способами:
1. Переподать заново заявку с указанием другого почтового ящика - и прислать номер новой заявки сюда. если необходимо чтобы заявка попала к тому-же чиновнику, который начал обработку первой версии. Это, конечно, ускорит процесс обработки повторной заявки.
2. Обратиться непосредственно физически к госрегистратору.

С уважением, Август.

**Comment by Danil-Seledkov** [comment]
Добрый день, Август.
Только получилось вырваться и заполнить новое обращение № 0-699216432. Но **ОНО ОТЛИЧАЕТСЯ ОТ ПРЕДЫДУЩЕЙ**:

1. В общий перечень добавляемых КВЭД добавлен тот, который устанавливается основным "80.20", т.к. на сей день его нет вообще. В предыдущем обращении он указан только в графе изменения основного вида деятельности.

2. В перечень удаляемых КВЭД добавлен тот, который ранее был основным "61.10", т.к. он должен быть удалён. В предыдущем обращении он лишь не указывается как основной.

3. Изменён адрес новой эл. почты на Gmail, т.к. Freemail от Ukr.net не всегда полностью отображает письма от сервиса iGov.

Поэтому, я не знаю можно ли ходатайствовать перед госрегистратором об ускорении рассмотрения обращения на основе старого. Но все же, вам решать. Буду ждать новостей.

Хорошего вам дня.

**Comment by agerman-ua** [comment]
Принял.
Взаимно.

**Comment by Danil-Seledkov** [comment]
Спасибо за такое быстрое решение вопроса. В новом письме на Gmail кнопка работает. Только что оплатил. Всего доброго!

**Comment by agerman-ua** [comment]
Ура. :) Теперь ждём обработки. День-два обычно.

**Comment by Danil-Seledkov** [comment]
Первая заявка изменила статус на "Закрита".

**Comment by agerman-ua** [comment]
Это норм.

**Comment by Danil-Seledkov** [comment]
Вчера внесли изменения и закрыли заявку.
