### ISSUE TITLE
Звернення на реєстрацію ФОП №0-678041869

### ISSUE THREAD

**Issue by BeZZik** [e-government-ua/iForum#653]
Добрий День, чи можна якось з'ясувати на якому єтапі звернення на реєстрацію ФОП №0-678041869, Коли очікувати рішення? Дякую!

**Comment by agerman-ua** [comment]
Доброго дня. @BeZZik 
Ваше звернення в роботі.
Ще потрбіно день-два на опрацювання реєстратором та отримання Вами рішення.
З повагою, Август.

**Comment by BeZZik** [comment]
Сьогодні завтра чи завтра післязавтра ? Можливо до них треба піти з паперовою версією ? Дякую за відповідь!
