### ISSUE TITLE
При реєстрації через картку киянина не виходить зайти до журналу

### ISSUE THREAD

**Issue by AndriiZ** [e-government-ua/iForum#654]
https://igov.org.ua/journal?error=%7B%22error%22:%22%7B%5C%22code%5C%22:%5C%22ESE%5C%22,%5C%22message%5C%22:%5C%22Access%20Token%20is%20empty%5C%22,%5C%22nested%5C%22:%5C%22invalid_request%5C%22%7D%22%7D

**Comment by annastolbova** [comment]
чи не могли б Ви надати скрін помилки сюди в чат, бо за посиланням переходить просто у розділ Мій журнал
