### ISSUE TITLE
Вхід через NBU BankId не працює

### ISSUE THREAD

**Issue by AndriiZ** [e-government-ua/iForum#655]
При кліку на https://igov.org.ua/auth/bankid-nbu?link=https://igov.org.ua:443/journal перекидає на сторінку НБУ.
Там можна вибрати банк для ідентифікації
Вибираю Ощад
Перекидає на сторінку ощада
Ідентифікуюся
Повертаюсь на сторінку НБУ. Все. Перехід на портал послуг відсутній

**Comment by GrekD** [comment]
@bvv4ik посмотрите, пожалуйста

**Comment by annastolbova** [comment]
зараз авторизація через Ощад працює коректно
