### ISSUE TITLE
Звернення на реєстрацію ФОП №0-682593707

### ISSUE THREAD

**Issue by urazo** [e-government-ua/iForum#656]
Добрий День, чи можна якось з'ясувати на якому етапі звернення на реєстрацію ФОП №0-682593707, 12.10.2016 зареєстрували звернення, але відповіді до сьогодні не маємо. Коли очікувати рішення? Дякую!

**Comment by agerman-ua** [comment]
Добрий вечір, @urazo 
Зараз важко точно визначити термін надання послуги. Попередні терміни на які ми орієнтували всіх (три-чотири доби) зараз не витримано. Ми поки прогнозуємо до кінця тижня.
З повагою, Август.

**Comment by urazo** [comment]
Добрий день! прошу повідомити, чи вiдкрита справа на реєстрацію ФОП №0-682593707 та №0-683047650, чи краще подати документи в паперовій формi?

**Comment by agerman-ua** [comment]
Добрий день, @urazo 
На ці звернення справ ще не відкрито.
Якщо є можливість зачекати - то краще отримати послугу онлайн.
Якщо треба дуже швидко - прямо зараз ще можна, без проблем, закрити звернення та звернутися до реєстратора з паперовою заявою.
Але що краще вирішувати тільки Вам.
З повагою, Август.

**Comment by urazo** [comment]
@agerman-ua у якому станi знаходяться заявки на регiстрацiю ФОП 0-682593707 та 0-683047650 ? Якщо стан не змiнився, то ми можемо закрити заявки, та звернутися в найближчу податкову?

**Comment by agerman-ua** [comment]
Доброго дня, @urazo 
0-683047650 вже відкрита справа, закрити звернення не вийде.
0-682593707 ще не відкрита справа (але прогноз на опрацювання  не більше 3-х діб)
Другу заявку можна ще закрити, але звертатися до податкової треба тільки після реєстрації.

**Comment by urazo** [comment]
@agerman-ua  0-683047650 по цiй справi треба додати нову заявку з новою датою (нам потрiбна 3 группа) ?
0-682593707 по цiй справi треба теж додати нову заявку з новою датою? Якщо так, то яку дату краще поставити?

**Comment by agerman-ua** [comment]
Так. Краще замінити, бо податкова із задоволенням та тихо відмовиться ставити на облік по спрощеній системі.
По 683047650 вже чекають новий файл.
По 682593707 не можу поки зв'язатися - але теж відправляйте.
З розділу "Мій журнал".
По даті ставте 27-31 жовтня.

**Comment by urazo** [comment]
@agerman-ua  по цiй заявi 683047650 теж ставити  27-31 жовтня?

**Comment by agerman-ua** [comment]
Так. Вони у різних реєстраторів, але терміни приблизно однакові будуть.
