### ISSUE TITLE
Ошибка при записи на получение второго загранпаспорта в Киеве

### ISSUE THREAD

**Issue by westvk** [e-government-ua/iForum#657]
При записи на получение второго загранпаспорта в Киеве после выбора времени постоянно выбивает ошибку.
![image](https://cloud.githubusercontent.com/assets/22932061/19512204/77d589a8-95f3-11e6-940f-e71271a4be39.png)

**Comment by annastolbova** [comment]
добрый день,
уже разбираемся. сообщим о результатах позже.

**Comment by annastolbova** [comment]
ситуація виправлена
