### ISSUE TITLE
Звернення на реєстрацію ФОП №0-676754904

### ISSUE THREAD

**Issue by Bhdltk** [e-government-ua/iForum#658]
Доброго дня.
Заява була подана 11.10.16, проте вже більше тижня статус її на сайті "В обробці".
Надайте, будь ласка, інформацію коли буде прийняте рішення по даній заявці. 
Дякую.

**Comment by agerman-ua** [comment]
Добрий вечір, @Bhdltk 
Ви обов'язково отримаєте повідомлення з порталу про виконання Вашого звернення.
Важко надати точну інформацію по термінам обробки. Попередній рогноз - до кінця тижня.
З повагою, Август.
