### ISSUE TITLE
Звернення на реєстрацію ФОП №0-689334070

### ISSUE THREAD

**Issue by anna1085** [e-government-ua/iForum#659]
Добрий День, я подавала звернення на реєстрацію ФОП №0-689334070, 14.10.2016 о 21:12. Досі статус : «В обробці». Коли очікувати рішення? Дякую!

**Comment by agerman-ua** [comment]
Добрий День, @anna1085 
На жаль зараз в опрацюванні велика кількість звернень. Урядовці, яких підключено до послуги - не встигають в нормальні строки (3-4 доби).
Прогнозуємо обробку Вашого звернення на початку наступного тижня.
З повагою, Август.

**Comment by anna1085** [comment]
Добрий день, прошу повідомити, чи можу я не дочекавшись відповіді на звернення на реєстрацію ФОП №0-689334070, подати документи в паперовій формі, щоб пришвидшити реєстрацію?

**Comment by agerman-ua** [comment]
Зачекайте, зараз треба уточнити. 
Якщо справа реєстратором відкрита то ні. Інший реєстратор не зможе Вам допомогти. 
Якщо справу ще не відкрили то можна скасувати звернення і звернутися звичайним чином (з паперовою заявою) до свого реєстратора.

**Comment by agerman-ua** [comment]
Так, перевірив. 
Ще є змога закрити звернення. Якщо Ви цього бажаєте - дайте швидше знати сюди про це.
Після отримання повідомлення про закриття Ви можете отримати послугу у паперовому вигляді.
Дякую за розуміння.

**Comment by anna1085** [comment]
Прошу закрити звернення на реєстрацію ФОП №0-689334070

**Comment by agerman-ua** [comment]
Ок. Зачекайте на лист-підтвердження про закриття.

**Comment by anna1085** [comment]
Дякую, Чекаю,
