### ISSUE TITLE
Помощь при рождении ребенка

### ISSUE THREAD

**Issue by lesia87** [e-government-ua/iForum#66]
Добрый день!
Была подана заявка на получение выплаты при рождении ребенка, номер заявки 10966817.
На сайте указано, что ответ будет предоставлен в течение 10 дней. На данный момент, на 06.11, ответ не получен. Подскажите, пожалуйста, как скоро будет предоставлен ответ?
Заранее благодарна.

**Comment by lesia87** [comment]
заявка подана по Ленинскому району

**Comment by dmitrijzabrudskij** [comment]
добрый день
подразумевается 10 рабочих дней (хотя практика покажет сколько в реале будет). Ваша заявка в работе сейчас, первый этап по принятию документов она прошла

**Comment by lesia87** [comment]
спасибо за ответ.

**Comment by lesia87** [comment]
Здравствуйте. Будьте добры, подскажите на каком этапе моя заявка находится в данный момент? Прошло уже более 3 недель.

**Comment by dmitrijzabrudskij** [comment]
добрый день
помощь назначена - Вам сегодня отправили на почту копию решения

**Comment by lesia87** [comment]
Да, спасибо за ответ и за работу!
