### ISSUE TITLE
Звернення на реєстрацію ФОП №0-678041869

### ISSUE THREAD

**Issue by BeZZik** [e-government-ua/iForum#660]
Добрий День, подав  звернення на реєстрацію ФОП №0-678041869 ще 11.1016, Коли очікувати рішення? Дякую! Можливо простіше звернутись до них з паперовой заявою?

**Comment by agerman-ua** [comment]
Доброго дня.
Прогноз - до кінця цього тижня.
Справу вже відкрили - тому інший реєстратор не зможе допомогти.
Звернення зараз з паперовою заявою вже не прискорить реєстрацію. 
Вибачте за загальну затримку.
З повагою, Август.
