### ISSUE TITLE
ТОВ Адвокатська фірма Правовий континент

### ISSUE THREAD

**Issue by Den1989** [e-government-ua/iForum#661]
Я подавав заявку # 0-648708429 на реєстрацію юридичної особи.
Юридичну особу зареєстровано, внесено до ЄДР, зареєстровано в податковій.
Виникла проблема : за кодом наданим в описі, на Порталі мінюсту, мала бути розміщена інформація, а саме : сканкопія статуту та виписка з ЄДР по даному підприємству. При вході на Порталі мінюсту за кодом, надісланим держреєстратором в описі, відсутній статут та виписка з ЄДР.
В зв'язку з цим я не можу відкрити рахунок в банку, завірити в нотаріуса картку зі зразками підписів та відтиском печатки і врешті решт , проводити комерційну діяльність.
Допоможіть в вирішенні даної проблеми.

**Comment by agerman-ua** [comment]
Доброго дня, @Den1989 
Постараємось допомогти. Перевірте ще раз через деякий час сьогодні.

**Comment by Den1989** [comment]
Добре, Дякую !

**Comment by Den1989** [comment]
Не можу потрапити на сайт ЄДР - немає доступу, або сторінка не існує

**Comment by Den1989** [comment]
Зайшов, є свідоцтво... Статут відсутній

**Comment by Den1989** [comment]
Вибачаюсь, є Виписка з ЄДР... Статуту немає

**Comment by agerman-ua** [comment]
З'ясуємо.

**Comment by Den1989** [comment]
Доброго ранку !
Статут до цього часу не внесено....

**Comment by agerman-ua** [comment]
Добрий день,
Реєстратор додасть. Коли зробить - дам знати.

**Comment by Den1989** [comment]
Підприємство взагалі зникло з ЄДР

**Comment by agerman-ua** [comment]
Добрий вечір. Не хвилюйтесь. Як раз писав відповідь.
Розібралися. Справи такі.
Реєстратор відразу не отримав від адміністраторів всі надіслані документи від Вас.
Тому реєстрація відбулася без додавання статуту.
Зараз додавання статуту "постфактум" нічого не міняє. Така логіка роботи реєстраційної програми. Тобто ми коригуємо (три рази) а статут не може відобразитися якщо цього не було зроблено відразу. 
Єдиний варіант - скасувати реєстрацію та знову зареєструвати. В понеділок з ранку все буде повністю зроблено.
Вибачте за незручності.
З повагою, Август.

**Comment by Den1989** [comment]
А що робити з реєстрацією в Податковій ? я вже печатку зробив...

**Comment by Den1989** [comment]
код же змінеться...

**Comment by agerman-ua** [comment]
Реєстрація в податковій - клопіт, в нашому випадку, вже реєстратора.
На жаль, іншого варіанту вже не існує.
Щодо коду - може й не зміниться. Просто не стикався с такою дивною ситуацією.

**Comment by Den1989** [comment]
Будемо надіятися на краще. Дякую за допомогу !

**Comment by agerman-ua** [comment]
Так! Буде!
І Вам дякую за розуміння.

**Comment by agerman-ua** [comment]
@Den1989 
Новий код наданої послуги вислав Вам на поштову скриньку.
Зараз там Статут. Через півгодинки-годину з'явиться і виписка.
І приємнє наостанок. У Вас залишився Ваш ЕДРПОУ. :) Тобто печатку переробляти не треба.
Ще раз дякую за розуміння. 
Залишилося тільки порозумітися з податковою. Там можуть залишитися питання по спрощеній системі. Обов'язково проконтролюйте самі. Тут вже не зможемо допомогти.
З повагою, Август.

**Comment by Den1989** [comment]
Щиро вдячний Вам за допомогу і розуміння !
