### ISSUE TITLE
Заявка 0-645214972 Отримання інформації про призначення субсидії на оплату житлово-комунальних послуг

### ISSUE THREAD

**Issue by BorisJay** [e-government-ua/iForum#662]
Заявка была подана 29.09.2016, но до сих пор никакого ответа не пришло.

**Comment by zolotovatatyana** [comment]
Ваша заявка в работе у АНД УПСЗН

УПСЗН Амур-Нижньодніпровського району, м. Дніпропетровськ.
Адреса: 49000, Дніпропетровськ, вулиця Радистів, 8
Графік роботи: понеділок-п’ятниця: з 8.00 до 17.00
Телефон(и): (056) 375-90-64, (056) 376-52-03

**Comment by BorisJay** [comment]
Было указано, что время обработки заявки 5 дней. Прошло гораздо больше.
Мне продолжать ждать или сразу звонить по указанным Вами телефонам?

**Comment by zolotovatatyana** [comment]
Можно звонить, раз регламентированный срок истек

**Comment by BorisJay** [comment]
телефоны у них не работают. Отключены за неуплату. Есть альтернативные мобильные номера?

**Comment by annastolbova** [comment]
заявка закрита
