### ISSUE TITLE
Надання довідки про відсутність або наявніcть судимості №0-680741369 

### ISSUE THREAD

**Issue by PilipOK** [e-government-ua/iForum#663]
На e-mail не прийшло повідомлення про регістрацію заявки. Спам перевірено, теж немає. Мій е-mail: pilipok16@ukr.net

**Comment by agerman-ua** [comment]
Доброго дня, @PilipOK 
Зайдіть, будь ласка, в розділ "мій журнал" (після авторизації) там повинна бути копія відправленого Вам листа.
До речі відправлений він був "2016-10-11 18:41:39".
На жаль поштовий сервіс @ukr.net досить "вибагливий", тому ми, для таких випадків, зробили додаткову, гарантовану, можливість отримати інформацію яка була надіслана Вам.
З повагою, Август.
