### ISSUE TITLE
Сервис получения субсидии

### ISSUE THREAD

**Issue by tytarenkoigor** [e-government-ua/iForum#664]
Пытаюсь воспользоваться сервисом получения субсидии. Регистрацию пытаюсь сделать с подписанием электронным ключом (получен в Привате). И в конце после выбора ключа, вываливает ошибку. Проверял на 2 компьютерах (Win7/Win8)- браузеры IE и Opera (Java точно установлена и последней версии). Буду очень благодарен за помощь
Короткое видео с полученными ошибками https://youtu.be/EgIdythIEQE

**Comment by zolotovatatyana** [comment]
@tytarenkoigor  Здравствуйте.
Прошу проверить в Chrome (с ним практически никогда не возникает проблем). Если ошибка останется - сообщите пожалуйста.

**Comment by tytarenkoigor** [comment]
Для подписи документа мне нужно, чтобы браузер был с поддержкой Java. Chrome с Java не дружит - https://www.java.com/ru/download/faq/chrome.xml

**Comment by zolotovatatyana** [comment]
Я настаиваю на Google Chrome.

**Comment by AndreyPopovNew** [comment]
@tytarenkoigor 

для подписи igov.org.ua использует вроде как **свой** crypto plugin

так что действительно попробуйте Chrome.

у меня нормлаьно подписалось ЭЦП ДФС.
