### ISSUE TITLE
Звернення на реєстрацію ФОП №0-698316011

### ISSUE THREAD

**Issue by imayorov** [e-government-ua/iForum#665]
Доброго дня! Можна запитати щодо сроків розглядання звернення по реєстрації ФОП №0-698316011. Також питання щодо заяви на спрощену систему оподаткування - можна якось змінити заяву? Прочитав, що необхідна власноручна підпис, яку я забув зробити - тобто завантажив тільки DOC-файл. Дякую.

**Comment by agerman-ua** [comment]
Доброго дня, @imayorov .
Строк виконання зазвичай до 4 робочих діб. Зараз трохи більше - займає до 7-8 робочих діб.
Змінити не можна. Можна додати новий файл, але є ризик що урядовець обере перший варіант. Пропоную переподати звернення. При переподанні врахуйте нові строки реєстрації. За законом Ви маєте до 10 діб на обрання системи оподаткування. Для цього треба написати сюди що Ви просите закрити звернення. Якщо на той час справу реєстратор не відкриє.
З повагою, Август.
