### ISSUE TITLE
Звернення № 0-703450676 (Внесення змін до реєстру ФОП - Додавання кведів)

### ISSUE THREAD

**Issue by belit** [e-government-ua/iForum#666]
Доброго дня. Скажіть, будь ласка, коли буде оброблено Звернення № 0-703450676 ?

**Comment by dsdas** [comment]
Аналогічне питання по зверненню № 0-706630475. Заявку подава ще в п*ятницю

**Comment by agerman-ua** [comment]
Доброго дня, @belit 
Тільки прогноз. На цьому тижні. На жаль точніше сказати не можна.
@dsdas 
Прогноз такий-же. Пропоную далі відкрити для себе іншу тему. Разом два звернення незручно обговорювати.

**Comment by dsdas** [comment]
Дякую за відповідь. Наступного разу обов*язково відкрию нову тему. Але оскільки виникла подібна ситуація, не хотів заспамлювати :)

**Comment by belit** [comment]
Доброго дня. Кведи досі не додали, Скажіть, будь ласка, скільки ще часу треба? Мені з початку місяця потрібно працювати по новим кведам, Звернення № 0-703450676.

**Comment by dsdas** [comment]
Те саме... Питань до самого сервісу i-gov немає, але хто "тормозить"? Держреєстратор?

**Comment by dsdas** [comment]
Таке відчуття, що самий ефективний спосіб - це йти до реєстратора...

**Comment by agerman-ua** [comment]
@belit 
Зараз вже Ваша дата звернення в роботі. Доба-дві на опрацювання.

@dsdas 
Ніхто не тормозить конкретно. Просто багато звернень, та не всі ЦНАПи які підключені до системи встигають працювати і в звичайному режимі (паперові заяви) і онлайн (портал). Пріоритет віддають більше на людей які прийшли ногами. Ми зробили максимально децентралізовану систему.

"Таке відчуття, що самий ефективний спосіб - це йти до реєстратора..."
Не згоден з таким формулюванням. Більш прогнозований - так згоден.

По термінам - як у @belit 

З повагою, Август

**Comment by dsdas** [comment]
Ахах, це було круто. Вчора отримав відповідь, що внесення змін можливе лише для мешканців Дніпропетровської області. Оце таке #перемога. Витратив 12 днів, а результат просто феєричний! Піду завтра до реєстратора... Ідея вашого сервісу крута, але поки система пробуксовує. До Європи ще як до Києва рачки.

**Comment by agerman-ua** [comment]
@belit - Вас встигли зареєструвати до обмеження
@dsdas - і Вас теж зареєстрували. Тому вітаю.
Ми вибачилися перед усіма в листах, і ще раз вибачаюсь перед усіма зараз за незручності.
Таку поведінку програми з якою працюють реєстратори ми не могли передбачити.
Це абсолютно окрема система.
Вчора ми, після багаторазових спроб обійти обмеження, вимушені були швидко всіх попередити, навіть тих, у кого реєстраційні дії були виконані, але точно ми цього не могли по всіх перевірити.
З повагою, Август.

**Comment by dsdas** [comment]
А підкажіть ще, де можна перевірити цю інформацію (про зареєстровані КВЕДи)?

**Comment by dsdas** [comment]
Тому, що на сайті https://usr.minjust.gov.ua/ua/freesearch бачу тільки основний вид діяльності

**Comment by agerman-ua** [comment]
Якщо не помиляюсь, там повинно бути видно всі КВЕДи які є.

**Comment by dsdas** [comment]
Може ще не оновилися дані, але бачу поки один свій основний КВЕД. Почекаю ще до завтра, а як ні то піду до реєстратора :) Бо вже треба договір заключати.

**Comment by agerman-ua** [comment]
@dsdas 
Так. Це буде правильно. Додати/змінити КВЕД - безкоштовно.

**Comment by dsdas** [comment]
ЦНАП яких змін не вніс, довилося подавати заявку на місці. Шкода. Нажаль перший досвід користування з І-Гов не вдалий :) Бажаю вам перебороти хребет паперолюдям і хомосовєтікус, що засіли по всіх установах!

**Comment by agerman-ua** [comment]
Дякуємо за підтримку.
