### ISSUE TITLE
Проблемы при попытке заказать смену внутреннего паспорта

### ISSUE THREAD

**Issue by wordsbridge** [e-government-ua/iForum#667]
Услуга Обмін паспорта громадянина в разі зміни (переміни) прізвища, імені або по батькові
https://igov.org.ua/service/173/general/place/built-in/region/1/city/1
1. в пункте 
   *Оберіть підрозділ ДМС або ЦНАП району (міста), до якого належить Ваше місце реєстрації:
   невозможно выбрать (нет в списке) САМАРСКИй РОДГУ УМВД УКР. по Днепропетровску
2. независимо от выбора
   *Оберіть підрозділ ДМС або ЦНАП району (міста), до якого належить Ваше місце реєстрації:
   в поле 
   *Оберіть день та час, коли Вам буде зручно з'явитись для отримання послуги?:
   нет выбора - показан текст:
   На жаль, по обраній послузі більше не залишилось місць в електронній черзі. Спробуйте пізніше, коли з'являться нові доступні місця у черзі, або інше територіальне відділення.
   Необхідно заповнити.

т.е. заказать услугу невозможно!

![ig2](https://cloud.githubusercontent.com/assets/23060479/19697668/f1b894f8-9af4-11e6-8caa-44e42e09aa84.jpg)
![ig1](https://cloud.githubusercontent.com/assets/23060479/19697667/f1b2dca2-9af4-11e6-9a6d-c599343d52fa.jpg)

**Comment by AndreyPopovNew** [comment]
@wordsbridge количество тайм-слотов по квоте iGov для услуг ограничено. и на текущий месяц всё время уже занято.

на следующий месяц тайм-слоты откроются как понимаю завтра-послезавтра (в ближайшее время)

**Comment by Koffeek** [comment]
@wordsbridge на данный момент по паспортным услугам очередь открывается только на неделю вперед из-за ожидания постановления КМУ о переходе на ИД-карты, которое может быть принято в любой день. Запись на неделю с 31,10-4,11 появится 28,10.
