### ISSUE TITLE
не проходит авторизация через ЭЦП

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iForum#669]

**Comment by almozavr** [comment]
"Зависает" на этой урле https://biprocessing.org.ua/IdentDigitalSignature/pbds?sidBi=7a16b1d3-bd1e-4048-beab-80670843890c&agent=iGov
Видео: https://monosnap.com/file/KDA0rM9NXdVbkuz7r2m1A6qJcuR7QZ

Пробовал в разных операционных системах и браузерах – одно и то же.

**Comment by agerman-ua** [comment]
Добрый день, @almozavr 
Подскажите, пожалуйста, чей ключ Вы используете. Какой АЦСК?

**Comment by almozavr** [comment]
@agerman-ua ТОВ "Центр сертифікації ключів Україна"

**Comment by agerman-ua** [comment]
Ок. Спасибо. Может ещё поможет совет от разработчика ... "Если он на маке, посоветуйте удалить руками криптоплагин непосредственно из ОС, после - скачать новый установщик и установить."
Попробуйте.

**Comment by almozavr** [comment]
@agerman-ua а можно уточнить путь, куда ставится плагин?

**Comment by almozavr** [comment]
Кстати, я удалил расширения для хрома от приват-банка – банк-айди сайт предложил установить свой плагин https://chrome.google.com/webstore/detail/bankid-cryptoplugin/pgfbdgicjmhenccemcijooffohcdanic
Но ситуация не поменялась.

**Comment by almozavr** [comment]
В консоль вылазит следующая ошибка при загрузке странички
https://monosnap.com/file/uQaACMMtS1gxsgQ1LjEFcN5ouYJ5s9.png

**Comment by almozavr** [comment]
@agerman-ua подскажите, какие файлы мне нужно удалить, чтобы переустановить плагин?
https://github.com/e-government-ua/iForum/issues/669#issuecomment-256327418

**Comment by agerman-ua** [comment]
Добрый день, Алексей @almozavr 
В браузере удаляете.
![image](https://cloud.githubusercontent.com/assets/17760437/20306202/c78bc40e-ab41-11e6-89f6-2d5af1f7e16c.png)

**Comment by almozavr** [comment]
@agerman-ua я имел в виду вот это
> Ок. Спасибо. Может ещё поможет совет от разработчика ... "Если он на маке, посоветуйте удалить руками криптоплагин непосредственно из ОС, после - скачать новый установщик и установить."

Потому что ситуация не поменялась

**Comment by agerman-ua** [comment]
Хм. Это именно на мак. 
И тут я просто дословно передал фразу.
Просто не разбираюсь в маках и их осях.
А переустановка из магазина не помогает?

**Comment by almozavr** [comment]
Разобрался: ключ от ЦСК "Україна" нельзя использовать напрямую – его надо конвертировать.
http://uakey.com.ua/index.php?num_text=7458&lang=ukr

Было бы классно, если бы плагин выдавал ошибку и разрешал только .dat файлы.

Думаю, ишью можно закрыть.

**Comment by agerman-ua** [comment]
Ок. Спасибо за обратную связь. Передам разработчикам пожелания.
