### ISSUE TITLE
Пособие при рождении ребенка - как правильно заполнить банковские реквизиты?

### ISSUE THREAD

**Issue by alex0405** [e-government-ua/iForum#67]
Возможно, глупый вопрос, но пугает цена ошибки...
Есть Приватовская социальная карта для выплат. К ней есть полученная в банке "Заява" в собес с реквизитами для перечисления - указан "поточний рахунок" и "рахунок установи уповноваженого банку".
В форме заявки iGov есть поле для ввода поточного рахунку/номера карти и кнопка загрузки скана "Заяви".
Как правильно ввести реквизиты: 
Что указывать в поле - номер поточного рахунку или номер карты? Или и то и другое?
Нужно ли загружать скан "Заяви"?
Заполнять и поле и загружать скан? Или что-то одно?

**Comment by dmitrijzabrudskij** [comment]
можете заполнить либо, либо то (либо все вместе - лишним не будет) - поле для загрузки скана добавляли специально, так как районы соцзащиты привыкли получать к заполненному заявлению еще эту справку об открытии социальной карты

**Comment by alex0405** [comment]
А в поле ввода - номер карты или номер счета?
И еще: 
- сканы цветные должны быть или можно ч/б?
- формат tif можно загрузить или только jpeg?

**Comment by dmitrijzabrudskij** [comment]
номер счета

ч/б подойдут
формат любой - только помните о размере - до 2 мб

**Comment by alex0405** [comment]
Спасибо.
