### ISSUE TITLE
Звернення на реєстрацію ФОП № 0-698390307

### ISSUE THREAD

**Issue by Mitsik** [e-government-ua/iForum#670]
Доброго дня! Подавав заявку 19.10.2016, досі в обробці. Про загальну чергу я знаю. Підкажіть, будь-ласка, чи відкрита вже справа реєстратором? якщо ні, то я б хотів скасувати заявку та відвідати реєстратора оффлайн. Здається так буде швидше? 
Дякую

**Comment by Mitsik** [comment]
Хоча ні, не скасовуйте заявку :)

**Comment by agerman-ua** [comment]
:) Доброго дня, @Mitsik .
В даний момент статус "в черзі". Але це може змінитися в будь-який час.
Прогноз - 2-3 дні. Тобто до кінця тижня.
Вибачте за загальну затримку.

**Comment by Mitsik** [comment]
Дякую, зрозумів. Скажіть, будь-ласка, реєструючись, я додав заяву на спрощене оподаткування, але без підпису (просто заповнений .doc ), та відразу додав пдф з підписом, чи побачить реєстратор додану з підписом заяву?

**Comment by agerman-ua** [comment]
Побачить тільки останній файл який було завантажено.

**Comment by Mitsik** [comment]
Доброго дня! Підскажіть, статус заявки, будь ласка. Можливо швидше буде звернутись до реєстратора оффлайн?
Дякую

**Comment by agerman-ua** [comment]
Доброго дня.
Вже ні, не швидше. Сьогодні-завтра повинні опрацювати.
Дивіться в пошту, можливі уточнення.

**Comment by Mitsik** [comment]
Доброго дня,
дуже дяку, ФОП було зареєстровано вчора, але не можу знайти себе в Реєстрі платників єдиного податку. Коли, зазвичай, дані з'являються в реєстрі? Я хвилююся про заяву на спрощене оподаткування чи коректно вона була заповнена

**Comment by agerman-ua** [comment]
Доброго дня.
Не можу точно сказати термін коли з'являються дані в реєстрі платників єдиного податку. 
Але пропоную перевірити, безпосередньо звернувшись до податкової.
Теоретично можливо що Ви помилилися в заяві, реєстратор не виправляє такі помилки.
Тільки в цьому випадку отримаєте точну відповідь.
З повагою. Август.

**Comment by Mitsik** [comment]
Сьогодні податкова додала мене до реєстру платників єдиного податку. Я обрав третю групу 5%, але в реєстрі в мене друга група та 20%. Зателефонував до податкової, співробітник податкової звірилась з заявою яку вона опрацювала в ній вказаний не мій номер телефону, адреса та група і податкова ставка. Чи могла виникнути помилка зі сторони реєстратора? та що мені робити?

**Comment by Mitsik** [comment]
це помилка податкової, не igov :) 
Дякую за сервіс
