### ISSUE TITLE
Изменение группы единого налога

### ISSUE THREAD

**Issue by M03G1** [e-government-ua/iForum#671]
Добрый день. Необходимо произвести изменение группы единого налога, перейти с 1-й группы во 2-ю, как это можно осуществить? Очевидно нужно подать заявление на применение упрощенной системы налогообложения с указанием критериев перехода, однако не понятно куда это заявление необходимо отправлять?

**Comment by agerman-ua** [comment]
Добрый день, @M03G1 
К сожалению сейчас нет такой услуги и, соответственно, возможности через портал провести такие действия. Пока с налоговой у нас только опосредованные отношения. Согласно законодательства мы используем возможность передать заявление в налоговую о первичном выборе системы налогообложения только в момент регистрации через регистратора. Т.е. заявление налоговая получает не с портала а именно от регистратора. При смене выбранной системы такой опции нет - необходимо непосредственно обратиться в налоговую с данным заявлением. Можете, кстати, отправить заявление по почте (заказным, с уведомлением и вложением описи содержания).
С уважением, Август.
