### ISSUE TITLE
Реєстрація змін до відомостей про ФОП № 0-708306409

### ISSUE THREAD

**Issue by akoshlo** [e-government-ua/iForum#672]
Доброго дня!

Подала заявку № 0-708306409 'Державна реєстрація змін до відомостей про фізичну особу – підприємця' 21.10 для зміни прізвища, її статус на сайті досі в обробці. Хотілося б дізнатися актуальний статус заявки, чи була вона прийнята до розгляду реєстратором та хоча б приблизний термін розгляду. 

Також мені не надходило ніякої інформаціі щодо сплати послуги, про що це може свідчити? 

Дякую,
Олександра.

**Comment by agerman-ua** [comment]
Доброго дня. @akoshlo 
Зараз склалась досить велика затримка, тому звичайні 3-4 дні не витримуються. Звідси й відсутність змін у статусі.
Оскільки Ви замовили платну послугу - тільки після розгляду і відсутності зауважень у адміністратора Ви отримаєте листа з кнопкою для онлайн-сплати за її отримання.
Не раніше. Це зроблено щоб Ви не сплачували наперед.
З повагою, Август.

**Comment by akoshlo** [comment]
Доброго дня.

Підкажіть будь ласка чи відкрито вже справу реєстратором за моїм зверненням?

Дякую,
Олександра.

**Comment by agerman-ua** [comment]
Доброго дня, Олександра ( @akoshlo  ) .
Ще ні. Прогноз - п'ятниця-вівторок.
Вибачте за отримані незручності.
З повагою, Август.

**Comment by akoshlo** [comment]
Доброго дня.

Чи не могли б ви тоді скасувати мою заявку?

Дякую,
Олександра.

**Comment by agerman-ua** [comment]
Доброго дня, Олександра.
Заявка закрита.
З повагою, Август.
