### ISSUE TITLE
Регистрация ФОП, заявка №0-711685723

### ISSUE THREAD

**Issue by c4boomb** [e-government-ua/iForum#673]
Добрый день!
Подскажите, пожалуйста, как я могу отправить повторное заявление на переход на единый налог 3 группу. Так как похоже это(№0-711685723) заявление уже принято, ФОП открыт, но на единый налог не перевели.
Дату в заявлении не указывал.
Спасибо,
Лев

**Comment by agerman-ua** [comment]
Добрый день, Лев. @c4boomb 
Нет, к сожалению, такого понятия как "повторное заявление на переход на единый налог 3 группу".
Мы с налоговой непосредственно не контактируем. Данные которые Вы передаете через портал попадают к регистратору и он добавляет их в госреестр и уже оттуда их получает налоговая. Это только в момент регистрации. Позже ничего регистратор не может добавить "для налоговой" а только внести изменения в регистрационные данные. После регистрации всё по налоговой решается непосредственно в налоговой. Можно конечно отправить туда письмо с заявлением, но  необходимо соблюсти некоторые формальности (заказное и опись вложения). Почему не зарегистрировали на упрощёнку ответ можно получить только в налоговой. Разные налоговые ведут себя по разному в одной и той-же ситуации.
С уважением. Август.
