### ISSUE TITLE
Регистрация ФОП, заявка № 0-694527017

### ISSUE THREAD

**Issue by sFiFty** [e-government-ua/iForum#674]
Києво-Святошинський район, село Софіївська Борщагівка
Дата и час оформлення заяки - 18.10.2016 10:51
Вже 10тий день чекаю рішення, можна хоча б дізнатись причину такої затримки?

**Comment by agerman-ua** [comment]
Доброго дня, Олександр. @sFiFty 
Вибачте, дійсно останні два тижні склалась ситуація з загальною затримкою по обробці звернень.
Враховуються робочі дні. Зараз термін приблизно 7-8 робочих діб.
Ваше звернення буде оброблено в найближчі 1-2 робочі дні.
З повагою, Август.

**Comment by sFiFty** [comment]
@agerman-ua Дякую!

**Comment by sFiFty** [comment]
@agerman-ua Доброго дня. А якщо були зауваження то наступної обробки звернення знову доведеться чекати 7-8 днів?

**Comment by agerman-ua** [comment]
@sFiFty 
Не зрозумів. Якщо зауваження по цьому зверненню то чекати додатково не треба. Вона вже в роботі і тому з'явилися зауваження.

**Comment by sFiFty** [comment]
@agerman-ua Я вніс коррективи по зауваженням і звернення перейшло у статус "В обробці". Питання у тому, скільки часу займе перевірка моїх корректив?

**Comment by agerman-ua** [comment]
@sFiFty 
Зрозумів. Після початку роботи з Вашою заявою термін 1-2 робочі доби (в залежності від наявності зауважень) термін 7-8 діб це загальний термін (включаючий очікування в загальній черзі).
Олександр, думаю сьогодні питання буде закрито. 
З повагою, Август.

**Comment by sFiFty** [comment]
Відповідь 
"Ваше звернення №0-694527017 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін."

Але я знаходжу себе у списку зареєстрованих підприємців - https://usr.minjust.gov.ua/ua/freesearch
І є інформація про взяття на облік платників податків - https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx 

Не поясните як таке може бути?

**Comment by agerman-ua** [comment]
Олександр, доброго дня (@sFiFty) .
:) Авжеж можу пояснити. Нам потрібно було якнайшвидше попередити всіх централізовано, тому на всі незакриті на порталі звернення з регіонів, в яких не підключені місцеві реєстратори ми зробили закриття та попередження. Ваша була теж вже в роботі, але з ранку реєстратори вже не могли виконати реєстраційні дії за межами своїх областей. А у Вашому випадку реєстратор виконав дії в самому реєстрі напередодні, але не встиг зробити це на порталі до централізованого попередження. Тобто Вас встигли опрацювати. Вітаю.
З повагою, Август.

**Comment by sFiFty** [comment]
@agerman-ua Доброго дня, 
Тоді чому прийшло на пошту повідомлення про відмову? Можна мені відіслати виписку?

**Comment by agerman-ua** [comment]
Сформулюю по іншому. 
1. Відмова була всім звернення яких були не закриті та які надійшли не з Дніпропетровської області.
Тому відмова була не персонально Вам.
2. Постараюсь дістати унікальний код Вашої справиі з його допомогою будемо шукати відповідь. В будь-якому випадку завжди можна підстрахуватися платним витягом з реєстру (50 грн та онлайн).

**Comment by sFiFty** [comment]
Август, дякую Вам!
