### ISSUE TITLE
Справка о доходах из налоговой для ФОП: объясните пожалуйста как ее запросить?

### ISSUE THREAD

**Issue by ezik** [e-government-ua/iForum#675]
Добрый день!
Помогите пожалуйста: не могу понять по какой ссылке надо перейти чтобы запросить справку о доходах за определенный период из налоговой?

Спасибо!

**Comment by AndreyPopovNew** [comment]
@ezik а вам для каких целей справка нужна?

**Comment by ezik** [comment]
Для визы, требования посольства к документам.

**Comment by agerman-ua** [comment]
Добрый день,
Не вижу никаких проблем Вам воспользоваться услугой для физлиц.
https://igov.org.ua/service/655/general
"Надання довідки з Державного реєстру фізичних осіб - платників податків про джерела та суми отриманих доходів фізичних осіб(довідка про доходи фізичних осіб)"
