### ISSUE TITLE
Регистрация ФОП, заявка № 0-698362575

### ISSUE THREAD

**Issue by serhiipalash** [e-government-ua/iForum#676]
Київ, Святошинський район
Дата и час оформлення заяки - 19.10.2016 13:25
10-ий немає рішення за моєю заявкою. В чому причина затримки і що треба зробити для прискорення розгляду?
Сергій

**Comment by agerman-ua** [comment]
Доброго дня.
Вже в роботі.
За добу-дві - буде результат. Перевіряйте, будь ласка, свою пошту.
Вибачте це загальна затримка. 
З повагою, Август.
