### ISSUE TITLE
Регистрация ФОП, заявка № 0-704918115

### ISSUE THREAD

**Issue by Cordovec** [e-government-ua/iForum#677]
Здравствуйте. Подавал заявку на регистрацию ФЛП 20.10.2016. Во время подачи заявления на регистрацию произошел сбой в работе компьютера. После перезагрузки браузер повторно отправил запрос на регистрацию. В итоге оказалось две заявки №0-704918115 и №0-704872872. Возможно, ли отменить одну из них и узнать когда будет результат по второй.

**Comment by agerman-ua** [comment]
Добрый день.
Да, конечно, можно отменить дубль.
Отменить 0-704872872? 
Как более раннюю!

**Comment by Cordovec** [comment]
Да, давайте отменим 0-704872872. Когда ориентировочно можно ожидать ответ по второй заявке?

**Comment by agerman-ua** [comment]
1. Отменили.
2. Уже день-два.

**Comment by Cordovec** [comment]
Добрый день. Вчера пришло уведомление. 
"Ваше звернення №0-704918115 на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено рішення про відмову в реєстрації змін.
Коментар держслужбовця (Причина: У зв'язку зі змінами до Закону України "Про державну реєстрацію юридичних осіб, ФОП та громадських формувань" згідно до яких скасована екстерриторіальність послуги. Тимчасово надання послуги на порталі iGov.org.ua обмежується Дніпропетровською областю. Приносимо вибачення за незручності.)"
Обратился в исполком по месту жительства. Сказали, что ФЛП зарегистрировано, а документов, которые это подтверждают они дать не могут, но в течении 10 дней выписка из ЕГР должна прийти по почте от лица, которое проводило регистрацию. Подскажите пожалуйста, что делать в данной ситуации, учитывая, что ранее было уведомление об отказе регистрации?

**Comment by agerman-ua** [comment]
Добрый день,
Всё нормально. Нам необходимо было сразу предупредить людей о системной проблеме. Есть несколько случаев когда регистрационные действия успели провести, но не успели отразить на портале. Это и в Вашем случае произошло. Поэтому не переживайте. Если будут вопросы - спрашивайте.
С уважением, Август.

**Comment by Cordovec** [comment]
Добрый день. Когда я был в исполкоме, мне сказали, что регистрация была проведена 2 ноября. В течении 10 дней по почте должны прийти документы, подтверждающие регистрацию. Сегодня 15 ноября, прошло 13 дней, но ничего не приходило. Подскажите пожалуйста, что делать в подобной ситуации.

**Comment by agerman-ua** [comment]
Добрый день,
Факт регистрации смотрите в реестре. По бесплатному запросу. Используйте свой инн.
https://usr.minjust.gov.ua/ua/freesearch
По почте бумажное дело тоже должно прийти, но сроки тут не берусь предсказать. 
С уважением, Август.

**Comment by Cordovec** [comment]
Добрый день. Прошел месяц с момента регистрации, но документы до сих пор не пришли. Может можно узнать номер почтового отправления, что бы можно было разбираться с почтой. Или контакты, кто проводил регистрацию и отправлял документы. Клиенты требуют скан-копию выписки, а у меня ее нет, не могу работать. Подскажите пожалуйста, что делать.

**Comment by agerman-ua** [comment]
Добрый день. @Cordovec 
Завтра постараюсь помочь. 
С уважением, Август.

**Comment by Cordovec** [comment]
Добрый день. Скажите пожалуйста, удалось что то выяснить?

**Comment by agerman-ua** [comment]
Добрый день. Удалось-удалось. В личку отправляю код "Результат надання адміністративних послуг". После проверки очень прошу дать обратную связь.

**Comment by Cordovec** [comment]
Огромное спасибо за помощь. Выписку с сайта минюста скачал. Последний
вопрос. Я так понимаю, что бумажный вариант, можно не ждать, нужно ли в
таком случае обратится в местный исполком и заверить скаченную выписку
печатью?

2 декабря 2016 г., 10:06 пользователь agerman-ua <notifications@github.com>
написал:

**Comment by agerman-ua** [comment]
Бумажный вариант должен быть в деле, а дело по месту хранения.
Как и почему не доехало - не смогу определить.
Вариант обратиться по месту и заверить - правильная мысль. 
Держите в курсе.

**Comment by volodiaD** [comment]
Добрий день! Моя заявка  2 дні в статусі обробки. Принята 11.01.17  № 0-914104172 Перевірте будь ласка чи є вона в черзі.
З повагою, Володимир.

**Comment by agerman-ua** [comment]
@volodiaD 
Доброго дня.
У Тернопільскій області черга невелика, тому максимум до понеділка опрацюють.
Прошу. Не користуйтесь, будь ласка, темами які відкриті під конкретні звернення.
Створюйте нову.
Тому цю тему вже закрию.
З повагою, Август.
