### ISSUE TITLE
Реєстрація ФОП, заявка 0-723313751

### ISSUE THREAD

**Issue by ViktoriiaMoshkina** [e-government-ua/iForum#678]
Добрий день, 
Я подала заявка на реєстрацію ФОП у Києві, Солом'янський район, 25 жовтня.
Коли можна буде очікувати результат? 

І ще питання, чи потрібно додавати якісь скани паспорту чи ідентифікаційного коду? Цікавить саме паспорт, бо змінився штамп за місцем прописки (перейменовано вулицю). Дякую!

**Comment by agerman-ua** [comment]
Доброго дня, Вікторія. @ViktoriiaMoshkina 
Термін очікування, приблизно, 3-4 робочі доби.
Ні. Скан паспорту не треба.

**Comment by ViktoriiaMoshkina** [comment]
Дякую, а моя заява вже пішла в обробку чи ще ні?
Бо від цього залежить, чи можу я прискорити процес, подавши документи особисто в ЦНАПі. Дякую.

**Comment by agerman-ua** [comment]
Доброго дня.
Так. Її почали обробляти, але реєстратор не зміг виконати реєстраційні дії за межами своєї області. Вам відправлено листа з детальною причиною відмови.
З повагою, Август.
