### ISSUE TITLE
Ошибка в услуге

### ISSUE THREAD

**Issue by DaryaLukyanenko** [e-government-ua/iForum#679]
При попытке подать заявку "послуга "Реєстрація дитини у садок"" https://igov.org.ua/service/700/general 
возникает ошибка - на скрине. Возникает на любой области/городе, сразу после выбора города. Браузер Хром, перезагрузка, кеш/куки проблему не решают.
![1](https://cloud.githubusercontent.com/assets/23175493/19866610/7bc40ec6-9fa9-11e6-891d-30534673d230.jpg)

**Comment by AndreyPopovNew** [comment]
@DaryaLukyanenko  вопрос поднят уже https://github.com/e-government-ua/iForum/issues/647

периодически пинаем разработчиков

**Comment by GrekD** [comment]
услуга не запущена через iGov, поэтому вылазит эта ошибка
можете попробовать через сайт, но я не ручаюсь за корректность его работы
https://reg.isuo.org/ru/preschools
