### ISSUE TITLE
Заявка на реєстрацію ФОП №0-705971717

### ISSUE THREAD

**Issue by Bhdltk** [e-government-ua/iForum#680]
Вітаю.
Заявка розглядається уже 13-й день.
Чи можете допомогти з прискоренням її розгляду?

**Comment by agerman-ua** [comment]
Доброго дня.
Зараз розбираємось зі змінами в Законі України щодо реєстрації.

**Comment by annastolbova** [comment]
заявка закрита 02.11.2016
