### ISSUE TITLE
заявка реєстрація ФОП 0-758702541 

### ISSUE THREAD

**Issue by Zhanna92** [e-government-ua/iForum#681]
Доброго дня! Сьогодні, 02.11 подала заяву на реєстрацію ФОП+ заяву на єдиний податок. Як скоро можна очікувати результату?  І як можна отримати виписку про реєстрацію?
І ще 1 питання, чи можете Ви проінформувати про статус реєстрації в податковій, так як хочеться все таки встигнути зареєструватись на спрощеній системі з самого початку, а не стати на загальну систему і бути на єдиному тільки з наступного кварталу. Дякую!!!

**Comment by agerman-ua** [comment]
Доброго дня. Сьогодні внесені зміни до законодавства. Просимо зачекати.

**Comment by Zhanna92** [comment]
Відпишіть будь ласка, коли буде щось відомо, дякую!

**Comment by agerman-ua** [comment]
@Zhanna92 
Вам відправили листа. 
На жаль звернення ми вимушені були закрити, реєстратори не можуть опрацювати її в своїй програмі, ми саме перевіряли всі можливості щоб не закривати надані звернення.
Причину в листі детально вказали.
Ще раз вибачте за незручності.
З повагою, Август.

**Comment by Zhanna92** [comment]
Дякую! Якщо, знову появиться можливість реєстрації, повідомте будь ласка, тут, буду дуже вдячна!

**Comment by agerman-ua** [comment]
Добре. 
Нагадайте, будь ласка, Вашу область, і коли будуть підключені реєстратори по цьому регіону - дам знати.
З повагою, Август.

**Comment by Zhanna92** [comment]
Доброго дня, Волинська область, м. Луцьк
Тобто вони точно будуть задіяні,(реєстратори/податкові) просто невідомо коли, так?

**Comment by agerman-ua** [comment]
Занотував.
Так, впевнений що це точно станеться. Невідома тільки точна дата.
Нам досить одного місцевого реєстратора на всю область, щоб відкрити послугу на регіон. 
Якщо є така можливість - можете посприяти. :) Багато людей будуть Вам вдячні.
З повагою, Август.

**Comment by Zhanna92** [comment]
спробую набрати свою реєстраційну службу, будуть якісь новини-дам Вам знати

**Comment by agerman-ua** [comment]
Дякую.

**Comment by Zhanna92** [comment]
Вони не знають про те, що такий ресурс існує і взагалі з реєстрацією в електронному вигляді ніколи не стикались.:(

**Comment by agerman-ua** [comment]
Запропонуйте їм, дайте нам контакт керівництва. 
Ми підключимось - розкажемо, покажемо. 
Головне щоб була зацікавленість. 
Скажіть що вся платня за послуги по області піде в їх місцевий бюджет. :) 
Якщо вони будуть перші - вся слава буде їм.

**Comment by Zhanna92** [comment]
Контакти керівництва: 0332 777 894 або 0332 77 895 і попросити начальника

Про платню не зрозуміла, я думала цей сервіс безкоштовний?

**Comment by agerman-ua** [comment]
Є державне мито. Якщо змінювати ПІБ або адресу то треба платити. 140 грн в місцевий бюджет.
А реєстрація ФОП так, правильно, безкоштовна дія.
Обов'язково подзвоню. Дякую.

**Comment by Zhanna92** [comment]
Дякую за інформацію
Чекаю новин:)
