### ISSUE TITLE
№0-645306860, файл не прикреплен

### ISSUE THREAD

**Issue by ValerijL** [e-government-ua/iForum#682]
Оформил заявку №0-645306860 на субсидию 29.10.2016. Город Днепр, район Индустриальный. Пришло письмо 02.11.16 о том, что субсидия назначена, размер в прикрепленном файле. Но никаких файлов в письме нет. Кто поможет? Не охота ехать на место и брать вручную.

**Comment by annastolbova** [comment]
доброго дня,
відповідь відправлена Вам на пошту.

**Comment by ValerijL** [comment]
Спасибо! Оперативненько! Но есть пару вопросов, возможно не к Вам. Во вложении 2 листа и второй лист пустой. Задаю вопрос т.к. на первой странице указан размер субсидии, но только на сентябрь 2016 и в графе отопление стоит "0". А как дальше платить социальную норму? Еще письмо должно прийти? Сомневаюсь. Если можете, помогите.
![attach_75797225_ _1](https://cloud.githubusercontent.com/assets/15772103/19933343/a93a7e4e-a11b-11e6-8a9b-56e4cabd2a19.jpg)

**Comment by annastolbova** [comment]
Вам надіслан розрахунок на неопалювальний період (вказано у файлі), наскільки ми знаємо, то зараз відділи УПСЗН завершують  автоматичний перерахунок на опалювальний період, тому є сенс направити пізніше (через тиждень, наприклад) просто інформаційний запит про розмір субсидії за посиланням:

https://igov.org.ua/service/21/general

**Comment by ValerijL** [comment]
Спасибо! Буду пробовать.
