### ISSUE TITLE
Як адвокату отримати відомості про номерний знак транспортного засобу-по Постанові КМУ від 19 жовтня 2016 р. № 735

### ISSUE THREAD

**Issue by dimadv** [e-government-ua/iForum#684]
На урядовому порталі розміщена наступна інформація, хоча на iGov досі не можу знайти як мені, адвокату, отримати таку інформацію по номерному знаку авто. Допоможіть будь ласка.
http://www.kmu.gov.ua/control/uk/cardnpd?docid=249418948
Уряд розширив обсяг інформації стосовно зареєстрованих транспортних засобів та їх власників, що можуть отримувати посадові особи органів державної влади, органів місцевого самоврядування, адвокати, нотаріуси із Єдиного державного реєстру Міністерства внутрішніх справ задля здійснення ними повноважень, визначених законом. Компетентні органи відтепер мають можливість отримувати відомості про номерний знак транспортного засобу, що раніше було неможливим при здійсненні запитів. Нововведення дозволить забезпечити державні органи повним обсягом даних про транспортний засіб, необхідних при складанні процесуальних документів щодо накладення на нього арешту, оголошення в розшук, визнання речовим доказом або знаряддям злочину. Отримання відомостей про номерний знак спростить роботу нотаріусів та покращить якість перевірки документів під час укладення правочинів, предметом яких є транспортні засоби. Інформація про номерні знаки транспортних засобів дозволить адвокатам прискорити процедуру підготовки процесуальних документів щодо забезпечення позову шляхом накладення арешту на майно.

**Comment by AndreyPopovNew** [comment]
@dimadv вот эта услуга

https://igov.org.ua/service/1397/general  
Надання витягу з Єдиного державного реєстру МВС

![image](https://cloud.githubusercontent.com/assets/8410116/20030404/f4af791c-a36c-11e6-96fd-c216fa488208.png)


но на сегодня там реализован поиск только по ИНН или ФИО для физлий или ОКПО или названию для юрлиц

и то наполненность базы данных оставляет желать лучшего :(

а указанному постановлению КМУ от 19 октября всего две недели, так что тут вряд ли скоро появиться возможность поиска по номеру. в лучшем случае к Новому году :(
