### ISSUE TITLE
Заявка на реєстрацію ФОП №0-753239651

### ISSUE THREAD

**Issue by Svyatogor777** [e-government-ua/iForum#685]
Добрий день! Скажіть, будь ласка, коли буде доступна послуга по всій Україні, зокрема в Донецькiй областi, мiсто Словянськ?

**Comment by agerman-ua** [comment]
Доброго ранку, 
На жаль жодна конкретна інформація щодо термінів початку надання в зазначеному регіоні реєстрації ФОП онлайн - наразі відсутня.
Але ми працюємо над тим, щоб отримати технічну можливість це робити.
Слідкуйте за інформацією у ФБ.
З повагою, Август.
