### ISSUE TITLE
регистрация ФОП в Харькове и Запорожье

### ISSUE THREAD

**Issue by querida9** [e-government-ua/iForum#686]
когда возможно зарегистрировать ФОП через портал  iGov в Харькове? в Запорожье?

**Comment by agerman-ua** [comment]
Добрый день,
Пока вопрос открыт. Возможно получится в Запорожской области достаточно скоро. Зависит от чиновников.
С уважением, Август.

**Comment by querida9** [comment]
а в Харькове?

**Comment by agerman-ua** [comment]
По Харькову ока нет активных переговоров. Но если будет добрая воля - вопрос одного дня с нашей стороны.
