### ISSUE TITLE
Заявка №0-507776071 для получение субсидии на оплату ЖКУ

### ISSUE THREAD

**Issue by Gesslow** [e-government-ua/iForum#687]
Наконец-то дозвонился в УПСЗН . Но на мою просьбу предоставить информацию о заявке я получил сухой ответ, что в этом отделе телефонов нет и нужно только лично приезжать за уведомлениями((. Как-то не особо хочется потерять пол дня в очереди и узнать, что по заявке решение ещё не принято(ведь такой вариант очень вероятен). Подскажите пожалуйста, не появились ли новые результаты рассмотрения заявки, у Вас есть же доступ к системе:

**Звернення №0-507776071**  щодо отримання субсидії на оплату житлово-комунальних послуг.

Контакти підрозділу соцзахисту:
УПСЗН Новокодацького (Ленінського району), м. Дніпропетровськ.
Адреса: 49000, Дніпропетровськ, вулиця Трудова, 1-А
Графік роботи: понеділок-п’ятниця: з 8.00 до 17.00
Телефон(и): (056) 775-55-86, 372-19-70

г. Днепр (Днепропетровск), заявка была подана 15 августа в 16:38 
---
Спасибо огромное!

**Comment by zolotovatatyana** [comment]
Добрый день

я помню вашу ситуацию, что  в Журнале отсутствует информация о вашей заявке.
Обновления в системе пока не было. Так и висит на втором этапе. Как только у соц.помощи будет решение - его Вам сразу же отправят, Вы получите письмо.

**Comment by Gesslow** [comment]
Спасибо большое за информацию.
