### ISSUE TITLE
Звернення № 0-783795293

### ISSUE THREAD

**Issue by malegadmitrij** [e-government-ua/iForum#688]
Звернення № 0-783795293
08.11.2016
Реєстрація місця проживання дитини до чотирнадцяти років
Досі в обробці.
Чекати чи їти самому?

**Comment by smoktii-igov** [comment]
Ваше звернення не було опрацьовано вчасно. В найближчий час Ваше звернення повинно бути опрацьовано, чекайте на відповідь.
Рекомендація: або йти до ЦНАП  з комплектом документів або спробуйте ще раз надіслати електронне звернення
