### ISSUE TITLE
Видача паспорта громадянина України замість утраченого або викраденого

### ISSUE THREAD

**Issue by maxsharov** [e-government-ua/iForum#689]
Доброго дня.
Я намагаюсь замовити видачу паспорту замість викраденого у м. Києві. Я зареєстрований у Дарницькому районі. Але бачу, що "На жаль, по обраній послузі більше не залишилось місць в електронній черзі. Спробуйте пізніше, коли з'являться нові доступні місця у черзі, або інше територіальне відділення.".
Тим часом звернув увагу на те, що "Дана послуга доступна лише за місцем реєстрації, якщо Ви не можете обрати свій район, то у ньому послуга на iGov відсутня".

Через це я маю питання, чи можу я замовити паспорт у вигляді ID-картки у будь-якому районі, чи тільки у Дарницькому? Якщо ні, то коли чекати на  появу вільних місць у електронній черзі?

**Comment by KoshevoySergey** [comment]
Я пытаюсь зарегистрироваться в любом отделении Днепропетровской обл и там ответ  "На жаль, по обраній послузі більше не залишилось місць в електронній черзі. Спробуйте пізніше, коли з'являться нові доступні місця у черзі, або інше територіальне відділення." Зачем сделали электронную очередь, если ее нужно вылавливать или она не работает?

**Comment by annastolbova** [comment]
по Дніпропетровській області:

у м. Дніпро -  в районах Шевченківський, Новокодацький та обласний на Поля - черга повністю електронна і щоденно додається 1 день (+14 днів), якщо вільної дати та часу немає, то можна спробувати подати заявку після 00:00, коли оновлюється інформація на наступну дату.

по всім іншим районам Дніпра та області - черга електронна і щоденно додається 1 день (+14 днів), якщо вільної дати та часу немає, то можна спробувати подати заявку після 06:00, коли оновлюється інформація на наступну дату.
