### ISSUE TITLE
довідки про склад сім’ї

### ISSUE THREAD

**Issue by Denis-Qirimli** [e-government-ua/iForum#69]
В розділі "Громадянам: Посвідчення особи, Громадянство, Місце проживання" передбачена видача наступних довідок (пов'язаних з реєстрацією місця проживання):
- Видача довідки щодо реєстрації/зняття з реєстрації місця проживання фізичної особи;
- Видача довідки про реєстрацію місця проживання;
- Видача довідки про реєстрацію місця проживання/перебування особи.

Відповідно до п.1.9 гл.2 розд. ІІ Порядку вчинення нотаріальних дій, затвердженого наказом Міністерства юстиції України 22.02.2012  № 296/5 "з метою перевірки відсутності прав малолітніх та неповнолітніх дітей, недієздатних чи обмежено дієздатних осіб на користування відчужуваними житловим будинком, квартирою, кімнатою або їх частиною нотаріус вимагає подачі йому довідки про склад сім’ї житлово-експлуатаційної організації, квартального комітету або іншого уповноваженого органу з питань реєстрації місця проживання".

Таким чином, було б доцільним передбачити технічну можливість щодо видачі електронних довідок про склад сім'ї з інформацією актуальною на вибрану заявником дату. Доступ до такої інформації повинен бути тільки у заявників, які зареєстровані за зазначеною адресою, власників, а також у нотаріусів, у разі оформлення ним спадщини. Більш того у нотаріусів повинна бути можливість перевірки дійсності довідки, виданої такому заявнику (власнику).

**Comment by Denis-Qirimli** [comment]
Готовий обговорити власне бачення з цього питання

**Comment by Koffeek** [comment]
@Denis-Qirimli 
Доброго дня, Дениc. Справа в тому, що для надання такої довідки повинна бути єдина база або картотека, якої наразі немає. До 2012 року усі дані зберігались у ЖЕКах або їм подібних установах, після 2012 року дані збиралися у адресно-довідковому бюро і якщо людина не змінювала місце реєстрації після 2012 року, то даних по ній у ДМС немає. Запити у ЖЕКи та їм подібні установи не завжди обробляються коректно. З боку ДМС розпочата робота по створенню єдиної бази зареєстрованих осіб і коли вона буде готова iGov з радістю зможе надавати наведені Вами довідки.

**Comment by Denis-Qirimli** [comment]
Добрий день!
Дякую Вам за відповідь. Однак, при розробці подібної бази, слід передбачити
внесення даних родинних відносин та внесення дати народження. Для
обговорення цього питання можу організувати круглий стіл з боку
нотаріальної спільноти.

З повагою та сподіванням на порозуміння,

колишній кримський нотаріус, нині нотаріус Львівщини Сєйдалієв Денис

18 листопада 2015 р. 13:32 Koffeek <notifications@github.com> написав:
