### ISSUE TITLE
Довідка про місце реєстрації та склад сім’ї (форма 3) для владельца квартиры

### ISSUE THREAD

**Issue by AndreyPopovNew** [e-government-ua/iForum#691]
при переоформлении лицевых счетов в коммунальных предприятиях, если владелец квартиры не зарегистрирован по этому адресу, то все равно нужна справка о составе семьи и о том, что владелец не зарегистрирован.

@GrekD данный вариант будет предусмотрен в услуге?

![001](https://cloud.githubusercontent.com/assets/8410116/20455534/fa93cbc6-ae66-11e6-8f5c-c364ebfa2c60.jpg)

**Comment by Akylish88** [comment]
Добрый день Андрей.
Предложение логично.  Проработаю в ближайшее время. Но точную информацию могу дать в понедельник, так как нужно сконтактировать с исполнителями.
