### ISSUE TITLE
отримання інформації про призначення субсидії 

### ISSUE THREAD

**Issue by pogrenat** [e-government-ua/iForum#693]
Заявка 0-772149402 от 5.11.2016. В ответ - тотальная тишина. 0 реакции на обращения через *Мой журнал* окно *ваш коментар або запитання..*, Заполнение формы *Маю питання щодо мого звернення* тоже ничего не дало. Когда и от кого нужно ждать ответа? Или лучше не ждать, а возвращаться к старым добрым традициям - стоянием в километровых очередях за бумажными распечатками?

**Comment by zolotovatatyana** [comment]
Добрый вечер.
Ваша заявка в работе у служащих. Возможно в вашем районе еще не до конца проведен автоматический перерасчет субсидий на отопительный сезон. Как только у чиновников будут данные по вашей заявке - вы сразу же получите ответ по электронной почте. 
Безусловно, вы можете пойти за бумажной распечаткой в километровую очередь, если считаете необходимым.

**Comment by pogrenat** [comment]
Добрый вечер и вам. Я уже была два раза в очередях, где мне выдавали уже перерасчитанное в бумажной версии, помесячно октябрь и ноябрь. Или эти месяцы не входят в отопительный сезон? или там проводят ежемесячный перерасчет? Кроме того, мои соседи, которые тоже живут в нашем районе, такие распечатки уже получили .
