### ISSUE TITLE
 Заявка 0-645214972 про начисление субсидии

### ISSUE THREAD

**Issue by masliyka** [e-government-ua/iForum#694]
5.10.2016 подала заявку № 0-645214972 АНД район г. Днепропетровска)  о вопросе начисления субсидии (продлевается ли субсидия автоматически с прошлого года или нужно заново подавать заявку.) До сих пор нет ни ответа, ни привета. Скажите, сколько еще ждать? Отопительный сезон длится уже больше месяца

**Comment by AndreyPopovNew** [comment]
субсидия должна персчитываться(и продлеваться) автоматически

если у вас возникли какие-то изменения в составе семьи, то тогда надо подавать заявку снова.

**Comment by zolotovatatyana** [comment]
Подавать повторно смысла нет. Заявки обрабатываются в порядке очередности поступления. Если не ответили - значит или у ответственного сотрудника не дошли руки, или в системе нет данных.
