### ISSUE TITLE
Как зарегистрироваться , что бы получить очередь на фотографию на паспорт для ребенка 14 лет ?

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#695]
Здравствуйте. Как зарегистрироваться , что бы получить очередь на фотографию на паспорт для ребенка 14 лет ?

https://www.facebook.com/igov.org.ua/posts/1791694011119474

**Comment by AndreyPopovNew** [comment]
в конце месяца на этот месяц свободных тайм-слотов не осталось скорее всего.

запись на следующий месяц наверное откроется на следующей неделе.

а вообще вся инфа тут
https://igov.org.ua/service/177/instruction

**Comment by VadymVolos** [comment]
Спасибо Андрей!
