### ISSUE TITLE
Подавал заявление при регистрации на 3 группу ЕН ставка 5%. А зарегистрировали почему то на общей системе?

### ISSUE THREAD

**Issue by lupolov-ivan** [e-government-ua/iForum#696]
Добрый день!
Поясните почему так получилось?

**Comment by Propeller-SV** [comment]
@lupolov-ivan это видели? [Отказ в регистрации плательщиком единого налога.](https://github.com/e-government-ua/iForum/issues/550)

**Comment by lupolov-ivan** [comment]
@Propeller-SV Благодарю за ответ, буду звонить в свою налоговую.

**Comment by agerman-ua** [comment]
@lupolov-ivan 
Иван, добрый день.
В указанном выше ишью действительно всё есть.
Налоговая особняком. Обязательно нужно их самостоятельно проверять/дёргать.

@Propeller-SV 
Спасибо, Сергей.

С уважением, Август.
