### ISSUE TITLE
Субсидия Синельниковский район 0-841747971

### ISSUE THREAD

**Issue by Inna-T** [e-government-ua/iForum#697]
26 ноября благополучно отправила заявку на субсидию (Синельниковский район). Все присоединила, заполнила. Сегодня приходит ответ На жаль, Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг було відхилено через недостатню або неправильну інформацію.

Коментар працівника УПСЗН (за наявності): НЕМАЄ ЗАЯВИ ТА ДЕКЛАРАЦІЇ
А что я заполняла и отправляла?
Заявка подавалась от имени отца, из доходов только пенсия  его и мамы. Дозвониться по телефону ,который указан при регистрации заявки -нереально.

**Comment by Inna-T** [comment]
В общем нашла в интернете другой телефон 05663 4-23-04, там мне дали кто занимается субсидиями 0994187904 (еле на него дозвонилась). Им нужна "живая" заявка и декларация, справка о составе семьи и скоросшиватель. По интеренту не принимают (говорит Вы у нас третьи такие с айгова ). Можете говорят через сельсовет подать, а в интернет мы не ходим и не понимаем. Вот такая история-------------Родители живут в селе (не в Синельниково), пенсионеры, дабы их не гонять воспользовалась айгов, а вот так вышло ,через интернет не хотят. В а живую это им день убить на поездки и на те очереди и столпотворения.

**Comment by zolotovatatyana** [comment]
Не спешите пока ехать, попробую разобраться.

**Comment by Inna-T** [comment]
Буду благодарна.
Я действительно не понимаю, неужели им легче с людьми вживую работать и объcнять, нежели через интернет принимать и рассматривать.  Да и папа мне уже высказал, мол, видишь неэффективность интернета, всё вживую надо ходить.

**Comment by zolotovatatyana** [comment]
Пока еще не дозвонилась до исполнителя, но посмотрела внимательно на Вашу заявку - при подаче Вы не подписали ее Электронно-цифровой подписью. В этом случае служащие все равно будут приглашать вас приехать и поставить свою подпись на бумажном экземпляре заявления. Так что пока я разбираюсь с их нежеланием  - вам имеет смысл озаботиться получением Электронно-цифровой подписи, с тем чтобы точно никуда не ходить.  

Инструкции по получению ЭЦП: https://docs.google.com/document/d/1Bai40Xw-XUcJfYR96CQD7-gSjsCtAlC3DMqbbcI-fxw/edit

**Comment by zolotovatatyana** [comment]
@Inna-T  Связалась с исполнителями. Они ждут Вашу новую заявочку и приносят извинения за ошибку.

Еще раз обращаю внимание на целесообразность оформления заявочки с ЭЦП, чтоб совсем никуда не ездить

**Comment by Inna-T** [comment]
Спасибо, подам. По поводу ЕЦП обязательно получу, на момент подачи заявки Приватбанк ,написал что в их базе название села по русск, поэтому сертификаты не получилось загрузить, написали они поправят и я скачаю.

**Comment by Inna-T** [comment]
Добрый день ,отправила я заявку на субсидию 0-848921683 30.11.2016г. 
С тех пор тишина,  отправила 19.12.2016   0-882463123   заявку про надання  інформації про субсідію- тиша. Дозвонится не реально.
Новую тему не стала заводить ,если надо-поправьте. Спасибо.

**Comment by Inna-T** [comment]
тишина, да?

**Comment by zolotovatatyana** [comment]
Позвонила, напомнила, обещали отработать в ближайшее время

**Comment by Inna-T** [comment]
Пришел сегодня расчет, спасибо.
А так же пришло письмо "Ваше звернення №0-848921683 щодо отримання субсидії на оплату житлово-комунальних послуг розглянуте, правильність заповнення документів перевірена, документи пройшли процедуру попередньої реєстрації.

Оскільки при заповненні заяви на порталі iGov.org.ua Ви не підписали заявку електронно-цифровим підписом, Вам необхідно навідатись до УПСЗН і надати підписані особисто Заяву і Декларацію (можна зберегти локально і потім роздрукувати додатки до цього електронного листа) не пізніше ніж у 30-денний термін від дати, вказаної на заяві."
Вроде подписывала ЕЦП....

**Comment by zolotovatatyana** [comment]
> Вроде подписывала ЕЦП....

наверное промахнулись кнопкой (в этом районе заявки не частые). Все рассмотрено как положено по процедуре с ЭЦП - в удаленном режиме. 

Рассказывайте друзьям и знакомым, популяризуйте сервис в вашем населенном пункте: больше практики - меньше ошибок :) :) :)

**Comment by Inna-T** [comment]
Еще раз спасибо, стараюсь как могу) и всем рассказываю как замечательно. По Днепру чем уже только не пользовалась, даже приватизацию добила. А в районе видать тяжко, сложно еще то, что телефоны у них "мертвые". Еще раз дяк, думаю можно заявку насовсем закрыть)

**Comment by zolotovatatyana** [comment]
"мертвые" городские телефоны у многих госструктур, к сожалению. 
Спасибо что воспользовались нашим сервисом, и благодарим за обратную связь!
