### ISSUE TITLE
Субсидия Днепр 0-494541281 Как расшифровать прикрепленный файл?

### ISSUE THREAD

**Issue by shymanov** [e-government-ua/iForum#698]
Добрый день.
Пришло письмо с текстом, что субсидию назначили, а тарифы смотрите во вложении. Файл с расширением d72.
Попробовали расшифровать с помощью https://igov.org.ua/journal/answer/DFS , подгружаем файл, но спотыкаемся на авторизации. Имя пользователя и пароль требует.
Так как можно заглянуть внутрь файла?
Спасибо за Ваши труды!

**Comment by zolotovatatyana** [comment]
Добрый день! Измените расширение файла с .d27 на .doc и открывайте с помощью MS Word.
Спасибо что воспользовались порталом :)
