### ISSUE TITLE
Електронна реєстрація ФОП

### ISSUE THREAD

**Issue by DmytroKovb** [e-government-ua/iForum#699]
Як зареєструвати ФОПа в електронному вигляді на igov.org.uа або на якому сайті це можна зробити найменш проблематично?Тому що крім Дніпропетровської області із списку неможливо вибрати іншу область.

**Comment by agerman-ua** [comment]
@DmytroKovb 
Доброго дня.
На жаль зараз дійсно працюють реєстратори тільки по Дніпропетровській області.
Не можу щось порекомендувати по онлайн-реєстрації.
А з якої саме Ви області?
З повагою, Август.

**Comment by DmytroKovb** [comment]
Доброго вечора. Я з Хмельницької області. Але така ж ситуація і з Івано-Франківською областю. Немає можливості особисто держреєстратору подати заяву в паперовому вигляді.

**Comment by agerman-ua** [comment]
Так. На жаль по цим регіонам новин поки особливо не чекаємо. 
Завтра перепитаю в мінюсті Хмельницької області. 
Може вже готові, просто ще не знають про це?!

**Comment by DmytroKovb** [comment]
Дуже шкода(

**Comment by agerman-ua** [comment]
Ви можете дати доручення і інша особа виконає реєстрацію.

**Comment by DmytroKovb** [comment]
Це я розумію, але зараз також немає такої можливості. Дякую за відповідь!
