### ISSUE TITLE
Получение помощи при рождении ребенка

### ISSUE THREAD

**Issue by CBeTJIaHa** [e-government-ua/iForum#70]
Добрый день! Подаю 2й раз заявку "Получение помощи при рождении ребенка", номер заявки 13567650, АНД район. И 2й раз приходит ответ  "К сожалению, Ваше обращение о получении социальной помощи при рождении ребенка отклонено из-за недостаточного или неправильную информацию". Заполняла вроде всё как положено. В чём может быть проблема?

**Comment by GrekD** [comment]
@CBeTJIaHa 
кроме указанного Вами комментария, должно быть укзано более конкретное замечание там же в письме.
можете, пожалуйста, переслать это письмо на адрес 88@igov.org.ua
?

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
