### ISSUE TITLE
0-620513436 субсидия

### ISSUE THREAD

**Issue by lizayampol** [e-government-ua/iForum#700]
не получили ответа по субсидии - хотя она уже назначена и неясно сколько и чего назначили. Оформляли через iGOV
Для мамы это важно - она хочет точно знать не в деньгах, а в площади на отопление, кубы по воде и киловатты льготной электроэнергии.

Ваше звернення №0-620513436 щодо отримання субсидії на оплату житлово-комунальних послуг розглядається працівниками УПСЗН, надані Вами відомості перевіряються. Незабаром Ви отримаєте результат розгляду Вашої заяви.

Коментарі держслужбовців щодо Вашої заяви (за наявності):

Контакти підрозділу соцзахисту, який обробляє Ваше звернення:

УПСЗН Шевченківського (Бабушкінського) району, м. Дніпропетровськ.
Адреса: 49000, Дніпропетровськ, вулиця Героїв Сталинграду, 116-А
Графік роботи: понеділок-п’ятниця: з 8.00 до 17.00
Телефон(и): (056) 763-05-79

(Ви можете зберегти файли, що долучено до цього листа, на комп'ютер, та роздрукувати заповнені Вами Заяву і Декларацію на папері за потреби)

**Comment by AndreyPopovNew** [comment]
@lizayampol пошлите запрос на информацию по субсидии

**Comment by zolotovatatyana** [comment]
@lizayampol  Здравствуйте
Ваша заявка еще не закрыта, она в обработке, на втором этапе рассмотрения. Результат назначенной субсидии придет после закрытия   заявки. В разделе "Мой Журнал" статус заявки изменится на "Заявка закрита", и вам в почту придет письмо вида "Субсидію призначено, результат нарахування в прикріпленому файлі". Нужно еще немножко подождать.

@AndreyPopovNew  Андрей, я Вас очень прошу: не рекомендовать пользователям портала забрасывать госорганы множественными подачами одной и той же заявки, как Вы делали уже неоднократно на этом форуме. Ибо ничего кроме неразберихи это не решает. Пока собес не получил решение, он не может ответить НИ НА ОДНУ из заявок: хоть две, хоть двадцать две Вы их направите. Кроме того что у них множатся заявки и они вынуждены по нескольку раз печатать, регистрировать, потом удалять одни и те же заявки - при том, что это время они могли потратить на обработку фактических обращений вместо "дублей". 
Если у вашего "метода" появится много последователей, я буду вынуждена ограничивать количество поданных заявок от одного пользователя средствами портала.

**Comment by AndreyPopovNew** [comment]
@zolotovatatyana  я обращаю ваше внимание, что я рекомендую подавать не одну и ту же заявку, а заказывать отдельную УСЛУГУ по **информации** о назначении субсидии!

и что плохого в моем методе? месяц или больше смотреть на тот как статус заявки не меняется?

я подал заявку о получении **информации** - через пару дней мне ответили "не назначена"
через неделю еще раз подал заявку о получении **информации** - через пару дней мне ответили "не назначена"
еще через неделю еще раз подал заявку о получении **информации** - прислали ответ "назначена" и в заявке о назначении поменялся статус.

раз в неделю это много?

**Comment by zolotovatatyana** [comment]
Каким образом Вы считаете обработка **еще трех** заявок на  **информацию** _(взять в работу, распечатать данные, отнести в отдел субсидий, сотруднику отдела субсидий поискать в базе, написать ответ, отнести в компьютерный отдел, специалисту разобрать результаты, найти вашу заявку в списке, обработать "не назначена")_  ускорит обработку этими же двумя сотрудниками Вашей первичной заявки на оформление субсидии?

**Comment by lizayampol** [comment]
допустим это так, но почему деньги на субсидии уже пришли (я это вижу на сайте complatezh и на сайтах горгаза, водоканала и облэнерго), а ответа нет?
.если деньги есть - то и решение принято. Тогда где письмо?

**Comment by zolotovatatyana** [comment]
Взаимодействие с реестрами и комунхозом происходит в одной системе (под МС-Дос писаном динозавре), а взаимодействие с заявителями - в другой (iGov). Сведения переносятся в айгов вручную сотрудниками соцпомощи, и не всегда так оперативно как хотелось бы, из-за нехватки специалистов.

**Comment by AndreyPopovNew** [comment]
@zolotovatatyana сужу по личной статистике Центральный (Кировский) УСПНЗ, чт отаки ускоряет.

как вы написали тут в соседнем посте, тогда у работника таки "доходят руки" открыть папку и пролистать ее, чтобы найти или убедиться что решения нет.
