### ISSUE TITLE
Запрос о размере субсидии на ЖКУ  №0-763566045

### ISSUE THREAD

**Issue by ValerijL** [e-government-ua/iForum#701]
Здравствуйте!
Изначально в связи с изменением состава семьи подал новую заявку на получение субсидии (историю можно посмотреть в закрытой заявке "№0-645306860, #682" на этом портале). В результате 2.11.16 получил положительный ответ и файлик,но на неотопительный период. Здесь посоветовали подать запрос чуть позже (через неделю наприм.) о размере субсидии через igov.org.ua. Но поскольку уже было начало 11 месяца и отопительный сезон в разгаре, я не стал ждать и подал заявку №0-763566045 03.11.16 в Индустриальный район г.Днепр. Пришло письмо на почту, всё ОК и ждите ответ в течении 5 рабочих дней. На сегодняшний день статус заявки "Заявка подана - Перевірка даних" и тишина. И деньги, к стати, на лицевые счета ЖКУ заходили последний раз 1.10.16 за сентябрь месяц. А дальше тишина, хотя субсидия назначена.
В связи с этим:
1. Когда может быть ответ по заявке?
2. Может повторно подать?
3. Может у них (в смысле у государства) уже деньги закончились?
Спасибо!
P.S. На сайте igov.org.ua задавал вопрос через "Маю питання щодо мого звернення". В ответ тоже тишина. И ещё. Обьясните, пож, если в курсе "автоматический перерасчет субсидии" насколько автоматический? Чего у них всё так долго?

**Comment by zolotovatatyana** [comment]
Добрый день!
Автоматический перерасчет субсидии происходит по сути так же как и при первой подаче, за исключением необходимости заявителю заполнять заново документы (Заяву и декларацию) и доставлять их в органы соцзащиты.
А по сути процесс остается тем же: отправка запросов во все органы, реестры и коммунальные предприятия за сведениями о ваших доходах и расходах. Поэтому, проходит он так же порядка месяца, а иногда и больше.

Повторная подача смысла не имеет, т.к. все равно заявки отрабатываются в порядке поступления, и ничего кроме накопления списка задач у сотрудников собеса вы не выиграете.

Деньги у государства не закончились :) Просто бюрократия и несогласованость доступов в реестры превращают начисление в целый квест, а недостаток рабочих рук замедляет отправку ответов гражданам.
