### ISSUE TITLE
Авторизация через Сертификат электронно-цифровой подписи

### ISSUE THREAD

**Issue by georg444** [e-government-ua/iForum#702]
На портале https://igov.org.ua получил через "Приват 24" Сертификат электронно-цифровой подписи (ЭЦП), по которому захожу на портал и подписываю документы.
Но по этому ЭЦП почему-то не могу зайти на портал http://portal.pfu.gov.ua, каждый раз получаю ответ "Сертификат ЭЦП не найден".
Объясните мне, пожалуйста, в чем дело? Почему так происходит?
![1](https://cloud.githubusercontent.com/assets/24429828/20968728/8433b67c-bc8e-11e6-9960-fd1cfaea972b.jpg)
![2](https://cloud.githubusercontent.com/assets/24429828/20968735/89eb2e4c-bc8e-11e6-8335-42eba820cbff.jpg)
![3](https://cloud.githubusercontent.com/assets/24429828/20968743/91d1c2ec-bc8e-11e6-8967-dbe2b75ffb9f.jpg)
![4](https://cloud.githubusercontent.com/assets/24429828/20968749/95063a06-bc8e-11e6-9eef-323cfc9306c3.jpg)
Благодарю за ответ.
Если есть возможность, прошу ответ выслать на E-mail: georg.sicorski@gmail.com

**Comment by AndreyPopovNew** [comment]
1. portal.pfu.gov.ua  никакого отношения в iGov не имеет.
2. и там четко написано сертификаты каких АЦСК принмаются!!! 
АЦСК Министерства юстиции и АЦСК фискальной службы.
АЦСК Приватбанк там не числится, как и еще с десяток других АЦСК

**Comment by georg444** [comment]
AndreyPopovNew
Огромное спасибо.
