### ISSUE TITLE
504 Gateway error при попытке авторизации на https://e.land.gov.ua/register/back/register_full

### ISSUE THREAD

**Issue by SergeySch** [e-government-ua/iForum#704]
при попытке авторизации на https://e.land.gov.ua/register/back/register_full с использованием BankID ПриватБанка в итоге открывается страница ( https://bank24.privatbank.ua/LoginP24/loginNext ) с ошибкой 504 Gateway error. Техподдержка ПриватБанка сообщила - 
"Спасибо за ожидание! уточнила информацию для уточнения данного вопроса Вам необходимо обращаться в поддержку сервиса на сайте https://igov.org.ua"

**Comment by GrekD** [comment]
@SergeySch 
на выходных ПБ проводил плановые работы по точкам входа (в данном случае Банк ИД). Уже все работает, хотя немного забавно что техподдержка ПБ отправляет к нам )
