### ISSUE TITLE
Когда заработает ФОП регистрация? 

### ISSUE THREAD

**Issue by iValentin** [e-government-ua/iForum#705]
Добрый день!
Не работает ни в одном регионе :( 
![image](https://cloud.githubusercontent.com/assets/18313364/21253354/a1227712-c366-11e6-9eb1-85117a5db091.png)

**Comment by iValentin** [comment]
Но раньше работала!

**Comment by zolotovatatyana** [comment]
Доброго дня! Реєстрація ФОП та Юр.осіб на території поза межами Дніпропетровської області тимчасово призупинена у зв'язку зі [змінами](http://zakon2.rada.gov.ua/laws/show/1666-19/page2#n339)  до  [Закону України "Про державну реєстрацію юридичних осіб, ФОП та громадських формувань"](http://zakon5.rada.gov.ua/laws/show/755-15/page#n67) згідно до яких унеможливлена екстерриторіальність послуги. Реєстратори не мають доступ до реєстру іншого регіону. Приносимо вибачення за незручності. Волонтери iGov ведуть активну роботу щодо залучення до обробки звернень державних реєстраторів з інших регіонів.

**Comment by agerman-ua** [comment]
Добрый день, @iValentin .
1. Действительно не работает в Киеве и практически во всех других областях. Нет исполнителей.
В ближайшее время будет доступна в Тернопольской области. Ведутся переговоры в Хмельницкой, Волынской и Херсонской областях. По другим пока нет конкретики.
2. Раньше услуга была законодательно закреплена как экстерриториальная для всех видов подачи обращений, т.е. даже лично прийдя к регистратору в славном городе-герое Одессе можно было провести регистрационные действия в нашей прекрасной столице - Киеве. Теперь реестр законодательно и физически "закрыт" для проведения изменений регистратором из другой области. Если Вы будете ссылаться на норму нового закона в котором указано что в электронном виде услуга экстерриториальна, то я Вас немного разочарую (как ранее и сам себя), поскольку речь идет о том что нам разрешено подавать в электронном виде заявку не находясь в области по которой мы хотим получить регистрационную услугу. Но регистратор ДОЛЖЕН там находиться. Увы. Так что раньше не услуга работала а регистраторы из других областей.
Надеюсь полностью ответил.
Если что-то ещё непонятно - сразу спрашивайте.
С уважением, Август.

**Comment by iValentin** [comment]
Та чтобы они, эти демократы, руку сломали ... Ту, которой голосовали, собаки. 
А вам спасибо, жаль только, что неопределенность сплошная теперь по этому вопросу, как везде в этой сраной стране.

**Comment by agerman-ua** [comment]
:) Поверьте мы "лупаем ту скелю". 
День за днём ребята придумывают как изменить что-то не имея никакой возможности прямо и просто повлиять.
Если появится хоть один адекватный регистратор на регион мы можем запускать там эти услуги.
А страна у нас хорошая. :) Прорвёмся,
