### ISSUE TITLE
Проверка запроса  0-335364590

### ISSUE THREAD

**Issue by froosty** [e-government-ua/iForum#706]
Добрый день. Подавал заявку на регистрацию ФОП вместе с заявлением на регистрацию плательщиком единого налога. А сейчас оказалось, что меня нет в реестре плательщиков единого налога. Проверьте, пожалуйста, мою заявку и проясните ситуацию.

**Comment by agerman-ua** [comment]
Добрый день, @froosty 
Мы, к сожалению, не можем прокомментировать что происходит на стороне налоговой.
В момент проведения регистрации есть возможность добавить заявление на выбор системы налогообложения. Т.е. регистратор добавляет в реестр Ваше заявление, и налоговая его видит вместе с фактом Вашей регистрации.
Очень рекомендую обратиться в налоговую для прояснения всех вопросов связанных с ними.
Ранее было достаточно полное обсуждение сходного вопроса. **[Здесь](https://github.com/e-government-ua/iForum/issues/550) можно почитать.**
С уважением, Август.

**Comment by froosty** [comment]
Добрый день, Август. Проверили в налоговой, у них при получении документов указали тип документа "НДС", хотя заявление по единому налогу (оригинал у меня). Могу ли я узнать регистратора, который проводил регистрацию, чтобы выяснить что передавалось и на чьей стороне ошибка (регистратора, или налоговой). Так же, если это возможно, могу ли я получить какое-то подтверждение о том, какие документы были прикреплены к моей заявке.

**Comment by froosty** [comment]
Ещё один вопрос. Можете ли Вы проверить (послать запрос) у гос. регистратора, какие документы хранятся в моём деле? В "Витягу" такие данные про регистратора: "Державна реєстрація фізичної особи-підприємця; 06.07.2016 22730000000047935; Коваленко Ольга Василівна; Виконавчий комітет Новомосковської міської ради Дніпропетровської області".

**Comment by agerman-ua** [comment]
Добрый день,
Заявление Ваше есть в обращении. Значит должно быть и в реестре. Оперативно уточнить что именно находится в реестре нет возможности. Скорее всего завтра постараемся уточнить. 
Но это не важно. Если Вы читали ссылку на https://github.com/e-government-ua/iForum/issues/550 там видно что налоговая периодически и местами игнорирует данные заявления из реестра. Данный вопрос правильно решать на месте имея про запас заявление. Регистрацию в реестре мы можем контролировать а вот подтверждения выбранной системы налогообложения - нет.
С уважением, Август.

**Comment by froosty** [comment]
Добрый вечер. Я понимаю ,что правильно решать вопрос на месте ( [#550](https://github.com/e-government-ua/iForum/issues/550) читал ) Но я нахожусь в Киеве, а ехать нужно в Красноармейск. Т.е. путь не близкий. И я бы хотел ехать максимально подготовленным. А то я приеду, мне скажут что-то вроде "мы ничего не получали" и я проехав через пол страны, я вернусь домой, и всё равно буду к Вам приставать =) Может быть есть возможность просмотреть подробные данные по моей заявке (т.к. в личном кабинете, к сожалению, подробную информацию просмотреть нельзя), посмотреть, какие документы хотя бы ушли к регистратору. Очень жду Вашего ответа.
С уважением, Константин.

**Comment by Propeller-SV** [comment]
@froosty добрый вечер. Был в похожей ситуации (тема #550 моя, как видите), поэтому напишу пару фраз.
Насколько я знаю, если вы зарегистрированы в налоговой как плательщик налога на общих основаниях, то перейти на упрощенную систему вы теперь сможете лишь со второго квартала 2017 (с 01.04.2017), никак не раньше. Все необходимые бумаги можно отправить обычной почтой заказным письмом с описью вложения, ехать в налоговую никакой необходимости нет. Как нет необходимости разбираться в том, где и по чьей вине произошел сбой. Только зря потратите время и нервы. Задним числом налоговая менять ничего не будет. Лучше найти живой контакт в вашей налоговой и следовать их инструкциям.
А пока придется платить налог по общей системе или временно прекратить предпринимательскую деятельность.
Удачи!

**Comment by agerman-ua** [comment]
Добрый день, Константин.
Регистратор получил Ваше заявление по упрощёнке. Скан в формате пдф. Тут проблем не было. В реестре другого нет. Ехать живьем в такую налоговую даль действительно не обязательно. Можно отправлять заказным новое заявление. Только соблюсти его оформление (заказным и с описью вложения).
Искренне жаль что так у Вас сложилось. 
Когда подключится налоговая к порталу такого уже не будет.
С уважением, Август.

**Comment by froosty** [comment]
@agerman-ua Здравствуйте, Август. Спасибо большое за помощь. У меня к Вам ещё одна просьба. У меня у товарища была подобная проблема и ему с вашего сайта отправили документ "Опис документів, що надаються фізичною особою державному реєстратору для проведення реєстраційної дії "державна реєстрація фізичної особи-підприємця". Возможно ли мне получить такой документ на почту?

С уважением, Константин

**Comment by agerman-ua** [comment]
Добрый вечер, Константин.
Документ доступен по уникальному коду оказания админуслуги.
В письме о успешном завершении регистрации должен быть.
По ссылке https://usr.minjust.gov.ua/ua/freesearch
Выбираем опцию "Результат надання адміністративних послуг" - вводим код.
С уважением, Август.

**Comment by froosty** [comment]
Добрый вечер, Август. Дело в том, что там его нет. Там показывает "Документи: відомості відсутні" У моего коллеги тоже так было, он обратился к вам и ему с адреса, с которого приходят от вас письма выслали этот документ вложением. Поэтому и обратился с этой просьбой к Вам.
С уважением, Константин.

**Comment by agerman-ua** [comment]
Добрый день, Константин.
Да. Сейчас сложилась очень ... "глупая" ситуация (. Когда уже нет возможности у регистратора что-либо делать по им же обработанным делам если они теперь в другой области.
Я уточню момент как получить искомое.
С уважением, Август.

**Comment by froosty** [comment]
@agerman-ua Здравствуйте, Август. Спасибо, очень жду от Вас информации.
С уважением, Константин.

**Comment by froosty** [comment]
@agerman-ua Здравствуйте, Август.
Хотел уточнить, не стало ли что-то известно по моему вопросу.

И ещё одну вещь хотел уточнить. После регистрации приходит сообщение "Ваше звернення №... на тему "Державна реєстрація створення фізичної особи – підприємця", опрацьовано і по ньому винесено позитивне рішення про реєстрацію змін.", ну и, соответственно, статус в разделе "мой журнал" изменился. Я хотел бы узнать, по какому критерию это происходит? Я имею ввиду, что это в автоматическом режиме через какое-то апи дёргается, или регистратор должен вам прислать какое-то подтверждение, или регистратор через свой интерфейс должен вручную изменить статус заявки. Или ещё как-то. Ну если конечно это возможно узнать. Жду Вашего ответа.

С уважением, Константин.

**Comment by agerman-ua** [comment]
Добрый день, Константин.
Регистратор или администратор в своем кабинете в Вашей заявке выбирает соответствующий статус. Если требуется, пишет комментарий. Его он либо знает (регистратор) либо получил информацию от регистратора (адмиинстратор). Нажимает обработать и статус Вашей заявки меняется а Вы получаете соответствующее письмо. Следующим шагом развития должен стать апи связанный с реестром, чтобы не делать дополнительных очевидных движений. Но это пока планы, которые не зависят ещё от нас.
С уважением, Август.
