### ISSUE TITLE
Заявка  № 0-507776071 для получения субсидии на ЖКУ

### ISSUE THREAD

**Issue by Gesslow** [e-government-ua/iForum#707]
Здравствуйте! Пришло SMS, что начислена субсидия! А вот детали не могу увидеть(((, по номеру заявки в "Моём журнале" ничего не светится( -> https://igov.org.ua/journal. Подскажите пожалуйста, как можно просмотреть детали. Спасибо!

**Comment by zolotovatatyana** [comment]
Здравствуйте! Проверьте пожалуйста, пришло ли на электронную почту (адрес, который вы указывали при оформлении заявки) письмо, с вложением о размере субсидии.

И я поздравляю вас с решением, и благодарю за терпение несмотря на  долгое ожидание.

**Comment by Gesslow** [comment]
Приветствую! К сожалению, на почту ничего пока не пришло(( Может есть ещё способ увидеть результаты??? Если подскажите буду очень благодарен)) Спасибо огромное за содействие:) Мне действительно было приятно с Вами поддерживать общение)!

**Comment by zolotovatatyana** [comment]
Отправила копию расчетки на емейл, который был указан в заявке.

**Comment by Gesslow** [comment]
Татьяна, расчетку получил, спасибо огромное за помощь! Успехов и всего Вам доброго!!! Удачи!
