### ISSUE TITLE
Заявки 0-807094210 та 0-807151185 (вагітність і народження, соцзахист)

### ISSUE THREAD

**Issue by alex-79** [e-government-ua/iForum#708]
Доброго дня!
Ще 16 листопада було подано заявки на призначення допомоги в зв’язку з вагітністю та пологами  0-807094210, а також на призначення соціальної допомоги при народженні дитини 0-807151185. До сьогодні мною не отримано ніякої відповіді стосовно цих заявок. Хочеться дізнатися поточний стан виконання заявок. Чи є сенс чекати, чи iGov у Кривому Розі не працює і необхідно звертатися безпосередньо до відділу соцзахисту? 
Дякую.

**Comment by zolotovatatyana** [comment]
Доброго дня
iGov у Кривому Розі працює.
Я спробую уточнити деталі щодо ваших заявок.

**Comment by alex-79** [comment]
Сьогодні нарешті зателефонували. Дякую за допомогу

**Comment by zolotovatatyana** [comment]
Дякую що скористались нашим сервісом, та щасти Вам у Новому Році!
