### ISSUE TITLE
Нет ответа по заявке на субсидию

### ISSUE THREAD

**Issue by EvgeniyKachur** [e-government-ua/iForum#71]
Подавал заявку 18.10.2015, пришел ответ, что заявка будет рассмотрена в течении 20 дней. Номер заявки 9361493 ?????????????????

**Comment by dmitrijzabrudskij** [comment]
20 рабочих дней

**Comment by EvgeniyKachur** [comment]
Ясно, извините, невнимательно прочитал сообщение ).

**Comment by IgorChuvpilo** [comment]
Здравствуйте! Подал заявку 9.10.2015. Пришёл ответ о принятии. №7593477.
13.10.2015 заявка принята в роботу.
Потом поменялась дата принятия в работу на 6.11.2015.
Хотелось бы знать почему? Ответа не было, хотя сегодня 20 рабочих дней от 15 октября.
