### ISSUE TITLE
Нельзя войти через BankID проблема с ssl сертификатами

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iForum#710]
> Dennis R: 
> Ребята из igov.org.ua, почините сайт, нельзя войти через BankID проблема с ssl сертификатами

https://www.facebook.com/igov.org.ua/photos/a.1601562290132648.1073741827.1589199384702272/1623034644652079/?type=3&comment_id=1807084916247050&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by zolotovatatyana** [comment]
проблема не подтвердилась
