### ISSUE TITLE
які строки розгляду поданих документів для електронної реєстрації ТОВ ?

### ISSUE THREAD

**Issue by Tsylitsynskyy** [e-government-ua/iForum#711]
0-893920492 заявка подана 26.12.2016 о 15.58.Наразі час 28.12.2016 12.29. Заявка значиться в обробці. Ніяких документів щодо розгляду не має. Постановою Кабінету Міністрів України від 25.12.2015 №1133 «Про надання послуг у сфері державної реєстрації юридичних осіб, фізичних осіб — підприємців та громадських формувань у скорочені строки». Розгляд документів, поданих для державної реєстрації та проведення інших реєстраційних дій, здійснюється у такі строки: 1) щодо юридичних осіб та фізичних осіб — підприємців — протягом 24 годин після надходження документів, поданих для державної реєстрації та проведення інших реєстраційних дій, крім вихідних та святкових днів. закон не діє ?

**Comment by agerman-ua** [comment]
@Tsylitsynskyy 
Добрий день,
Ви правильно використовуєте посилання, але треба дещо уточнити щодо строків. Завжди про це намагаюсь писати, але звісно не всі могли це прочитати. Строки витримуються реєстраторами. Це факт. Але уявіть собі чергу до реєстратора з заявами на руках. З якого моменту починається відлік зазначеного в законі терміну? Правильно, з моменту коли реєстратор взяв в обробку Ваше звернення. А коли Ви чекаєте в черзі - час не враховується. Подавши будь-яке звернення на нашому порталі Ви можете займатися далі своїми справами і не сидіти в черзі. Ви отримуєте гарантії що Ваше звернення не буде загублено, або якимось чином залишиться без розгляду.
Таких звернень, по яким є зазначені строки багато, тому реєстратори беруть тільки те що можуть опрацювати в зазначені законом терміни.
Вибачте, якщо наведена інформація Вас засмутить, або не відповідає Вашим очікуванням.

До речі, у Вашому зверненні є недолік (не з Вашої вини), прошу переподати звернння бо в ньому відсутній файл заяви з накладеним ЕЦП. Прошу після переподання прислати сюди новий номер, щоб я хоч міг перевірити повноту Вашого звернення. Ще раз вибачаюсь за незручності.

З повагою, Август.

**Comment by agerman-ua** [comment]
@Tsylitsynskyy 
Трохи пізніше Ви отримаєте лист-відмову та прохання переподати звернення. Це стандартна процедура, бо кожне звернення повинно бути опрацьовано позитивно або з мотивованою відмовою. Тому, якщо Ви вже вдало переподасте звернення - не звертайте на цей лист уваги.
З повагою, Август.

**Comment by Tsylitsynskyy** [comment]
Ви отримуєте гарантії що Ваше звернення не буде загублено, або якимось
чином залишиться без розгляду.--     нажаль губились.не раз.

Закон ж  є закон.

До речі, у Вашому зверненні є недолік (не з Вашої вини), прошу переподати
звернння бо в ньому відсутній файл заяви з накладеним ЕЦП.  -   а де ж
гарантії обіцяні?(

28 грудня 2016 р. о 12:59 agerman-ua <notifications@github.com> написав:

**Comment by agerman-ua** [comment]
@Tsylitsynskyy 
Вибачте. Ми не загубили Ваше звернення, а за результатом його попереднього (без держслужбовця) опрацювання, не чекаючи поки повна черга дійде до нього, - виявили неможливість отримання по ньому позитивного рішення з причин які вказали. 
Ви про це отримали листа. 
Я саме це мав на увазі коли писав про гарантії розгляду.
З повагою, Август.

**Comment by Tsylitsynskyy** [comment]
Ви про це отримали листа.
Я саме це мав на увазі коли писав про гарантії розгляду.
З повагою, Август.  -   наразі заявка значиться у обробці.   0-893920492

29 грудня 2016 р. о 09:21 agerman-ua <notifications@github.com> написав:

**Comment by agerman-ua** [comment]
@Tsylitsynskyy 
Вибачте - зараз дуже великий був стрес щодо закриття ФОП. Там не всі звернення з першого разу виходили. Тому відразу перевіряв всі номери на коректність. Паралельно по декілька. І Вам відписав за іншим зверненням. Так що щиро вибачаюсь. З Вашим зверненням все добре. Все інше, раніше написане, залишається в силі.

**Comment by Tsylitsynskyy** [comment]
заявка №0-893920492  до цього часу в обробці.......

**Comment by agerman-ua** [comment]
@Tsylitsynskyy 
На жаль, у з'вязку з навантаженням або без цієї причини постійні проблеми у реєстраторів безпосередньо з їх програмою. Періодично не працює реєстр по всій Україні. А це, звісно відразу відображається на опрацюванні всіх звернень пов'язаних з реєстраційними діями на порталі.
З повагою, Август.

**Comment by Tsylitsynskyy** [comment]
це не портал послуг це жаль

**Comment by agerman-ua** [comment]
@Tsylitsynskyy 
Ми намагаємось ситуацію змінити в більш прийнятну. 
Але ми, знову ж таки на жаль, багато від чогось та когось залежні. 
Всій команді порталу дуже прикро бачити подібні коментарі.
З повагою, Август.

**Comment by agerman-ua** [comment]
@Tsylitsynskyy 
Реєстратор знайшов у Вас невідповідність між заявою та рішенням про створення та зробила запит не через портал прямо на Вашу поштову скриньку. Перевірте її. Вона не може з Вами зв'язатися бо телефон який Ви вказали не обслуговується. Я перевірив цю частину новин - це відповідає дійсності, телефон не обслуговується. Можливо і поштова скринька не існує?
Питання стосується кількості засновників та статутного капіталу - це суттєво.
З повагою, Август.
