### ISSUE TITLE
Проблема с закрытием ФОП

### ISSUE THREAD

**Issue by VeraSu** [e-government-ua/iForum#712]
Я закрываю сегодня 3 ФОП
Везде одна и та же проблема: ЕЦП не видна. Я использую ЕЦП приватБанка
Ваше звернення №0-900602553 на тему "Державна реєстрація припинення підприємницької діяльності фізичної особи – підприємця за її рішенням", опрацьовано і по ньому винесено рішення про відмову в державній реєстрації припинення підприємницької діяльності.

Коментар держслужбовця (Доброго дня. По технічним причинам з нашого боку не сформовано заяву з ЕЦП. Треба сформувати заявку повторно. Також просимо звернути увагу на те, що у зв'язку з великою кількістю поданих звернень, реєстратори можуть не встигнути прийняти в роботу Ваше звернення до кінця 2016 року та провести реєстраційні дії. Якщо Ви згодні на можливе опрацювання звернення в січні 2017 року, будь ласка, подайте Ваше звернення повторно.)

И так уже  3  раза!!!

**Comment by VeraSu** [comment]
Что делать???

**Comment by Konstantin2r** [comment]
У меня точно такой же отказ, направил повторно и скрестил пальцы.
Кто занает как обойти это баг, подскажите, буду очень благодарен, так как живу в другой области и физически появиться у регистратора не могу.
Спасибо заранее.

**Comment by Konstantin2r** [comment]
Имею еще один отказ по той же причине.
хелп
SOS

**Comment by agerman-ua** [comment]
Всем участникам данной темы и не только.
Спокойно переподавайте кто ещё не успел, проблема с пропажей заявлений-файлов ушла.

**Comment by Konstantin2r** [comment]
Спасибо, а можно проверить заявочку?
0-902697094
Спасибо заранее.

**Comment by agerman-ua** [comment]
@Konstantin2r 0-902697094 норм.

**Comment by Konstantin2r** [comment]
Фух. А то валерианка заканчивается. Спасибо Вам большое.

**Comment by Pernatuy** [comment]
Моя заявка прийнята ще 24 грудня 0-891337128. Досі рішення не прийнято. Прошу перевірити, чи все з нею гаразд. І як довго ще чекати?

**Comment by agerman-ua** [comment]
@Pernatuy 
Добрый день. 
З заявкою №0-891337128 все гаразд. 
Чекаємо опрацювання держреєстратором.
З повагою, Август.

**Comment by artkuxar** [comment]
подскажите. подавал заявку на закрытие ФОП супруги. № заявки 0-899535147
Вот пришел ответ:
Ви подали заявку на послугу Державна реєстрація припинення підприємницької діяльності ФОП за її рішенням. Cтатус: Надання послуги
Что значит "надання послуги"? Т.е. все в процессе или уже можно ехать в налоговую?

**Comment by agerman-ua** [comment]
@artkuxar 
Добрый день, Артём.
Нет, это было только подтверждение регистрации обращения на портале.
Ехать в налоговую только после получения письма в конкретным решением. Положительное или отрицательное. Если отрицательное - смотрим причину.
С уважением, Август.

**Comment by ISablin** [comment]
Подскажите пожалуйста. Подавал заявку на закрытие ФОП 4 января 17 года. Заявка 0-907233959 
Cтатус: Надання послуги. С этой заявкой всё нормально? Я уже сегодня повторную подал 0-912806952 (но это я уже сделал зря я так понял? Или это не создаст проблем?). Спасибо за ответ.

**Comment by agerman-ua** [comment]
@ISablin 
Вторую лучше конечно закрыть. Её ненужная обработка займёт время у регистратора. В результате всё равно ФОП будет закрыт после первой. Мы всячески пытаемся повысить эффективную нагрузку на регистраторов. Спасибо что написали.
С уважением, Август.

**Comment by Zoya-med** [comment]
Подавала заявку на закрытие 27.12.16, номер 0-897252404 , и тихо, может что-то не так? Можно проверить?

**Comment by agerman-ua** [comment]
@Zoya-med Вам закрыли ФОП, просто не успели завершить операцию на портале.

**Comment by Zoya-med** [comment]
Я уже вижу, что фоп закрыли (в реестре). Но мне ведь нужно подтверждение по почте, чтобы я шла с ним в налоговую. И при этом уложиться в 10 дней, а закрыли 05.01. Когда ждать это подтверждение? 
заранее благодарна за ответ.

**Comment by agerman-ua** [comment]
@Zoya-med 
Уточним завтра с утра.

**Comment by Zoya-med** [comment]
Вчера пришло подтверждение
 "Ваше звернення №0-897252404 на тему "Державна реєстрація припинення підприємницької діяльності фізичної особи – підприємця за її рішенням", опрацьовано і по ньому винесено позитивне рішення про державну реєстрацію припинення підприємницької діяльності.
Унікальний номер "Код" : 257873394559.
У будь-який час Ви можете отримати результат наданих адміністративних послуг використавши "Код" під час пошуку на офіційній сторінці Міністерства юстиції України, обравши для пошуку опцію "Результат надання адміністративних послуг."
Это уже все? Теперь можно идти в налоговую? Никаких документов не присылают?

**Comment by agerman-ua** [comment]
Добрый день, @Zoya-med 
Конечно идите в налоговую.
Если есть время и возможности регистраторы могут присылать и скан файла-описи. Но гарантировать это нельзя (как в Вашем случае). Налоговая видит все изменения в реестре. Если будут вопросы - отправляйте туда (в реестр). 
С уважением, Август.

**Comment by Zoya-med** [comment]
Спасибо

**Comment by Dimon35** [comment]
Добрий день,

Подав заявку 0-923135668 на закриття ФОП, я з Житомирської обл і так розумію, що реєстратор не зможе її обробити?
Можна її анулювати?

**Comment by agerman-ua** [comment]
@Dimon35 
Так, не опрацюють. Ви ж обирали іншу область а не свою. 
Але все одно дякую за попередження, зараз закриємо і Вам надійде лист. 
І черга до реєстраторів на одне звернення буде меншою.
З повагою, Август.

**Comment by Dimon35** [comment]
Дякую, вибачаюсь!

**Comment by ISablin** [comment]
Добрый день! Я проверил в реестре что меня сняли с учёта в дфс, и прочих установах одновременно с закрытием фоп. Я получил скан "Опис". Что с ним делать? Нужно ли идти в налоговую? Как дальше действовать? Я закрыл фоп по месту регистрации в Днепре а живу в Киеве.

**Comment by agerman-ua** [comment]
Добрый день, @ISablin 
Есть ньюансы зависящие, например, от системы налогообложения ФОП и даты его регистрации. В налоговую однозначно необходимо подать отчет за последний год работы предпринимателя. Но ехать не обязательно, можно отправить все необходимые документы и по почте с уведомлением и с вложением описи содержимого. Что именно Вам туда вкладывать - проконсультируйтесь, пожалуйста, со специалистом, не хотелось бы Вам дать несоответствующую Вашей ситуации инструкции.
Достаточно типичным является следующий сценарий. Закрыл в реестре - в налоговой получил бегунок - посетил все кабинеты. Но Вас он, к сожалению, не устроит.
С уважением, Август.

**Comment by ISablin** [comment]
Спасибо Вам, за развёрнутый ответ.
