### ISSUE TITLE
А если у меня телефон  не Андроид, то что мне делать?

### ISSUE THREAD

**Issue by Mika545** [e-government-ua/iForum#713]
Есть ли где-то вообще грамотная инструкция по заполнению? 
Я пока ничего понять не могу((

https://igov.org.ua/service/87/general  я про это

**Comment by agerman-ua** [comment]
@Mika545 Вам только номер телефона нужно указать и почту. А потом наложить эцп. Вот тут нужно убедиться что плагин подтягивается. Не должно быть проблем с Хромом.
Краткая инструкция тут на соседней с услугой закладке.
https://igov.org.ua/service/87/instruction

**Comment by Mika545** [comment]
@agerman-ua я тут пока разбиралась и выяснила, что у меня нет электронной подписи. А без нее ничего не происходит, так? 
И вся проблема в том, что нахожусь я сейчас не в Украине. Раньше была карточка Приват Банка, но она была закрыта . То есть в Приват 24 войти не могу. Что делать?.... помогите , пожалуйста!

**Comment by agerman-ua** [comment]
@Mika545 
Да без ЭЦП не получится получить данную услугу.
Авторизоваться можно и через ЭЦП. А не через приват24.
С уважением, Август.

**Comment by Mika545** [comment]
@agerman-ua а какие есть способы получения ЭЦП? 
если ты не в Украине

**Comment by agerman-ua** [comment]
@Mika545 
**[Довідник, як отримати ЕЦП, за цим посиланням.](https://goo.gl/1OioXt)**

**Comment by Mika545** [comment]
@agerman-ua **Де і як в Україні** можна отримати електронно-цифровий підпис
В Украине !
А я не в Украине .
И еще, пожалуйста, ответьте ЭЦП- должна быть для юридических лиц? 
Так как я пытаюсь войти в Приват 24 , там якобы можно сформировать подпись, но они мне говорят, что если мне нужна цифровая подпись, обычный кабинет Приват 24 не подойдет, нужно открывать у них счет. Это правда?

**Comment by zolotovatatyana** [comment]
можно в Приват24 для физлиц сгенерировать ЭЦП физлица.

Заходите Приват24 - Все услуги - Бизнес - Электронная цифровая подпись - Скачать сертификат

![image](https://cloud.githubusercontent.com/assets/17428210/21573462/3de6447a-ceed-11e6-9df1-4972691dc934.png)

**Comment by agerman-ua** [comment]
@Mika545 
Нет. ЭЦП при закрытии ФОП может быть и Ваша личная.
По поводу получения ЭЦП в приват24 предыдущий пост содержит полностью исчерпывающий и понятный ответ?
С уважением, Август.
