### ISSUE TITLE
Каков процесс закрытия ФОП

### ISSUE THREAD

**Issue by 1st** [e-government-ua/iForum#714]
Добрый день. Есть неактивный ФОП, хочу его закрыть. Живу заграницей, в ближайшее время не планирую езать в Украину.

Интересует как происходит процесс **полного** закрытия ФОП. Предположим что я сформировал заявку на закрытие через сайт iGov, получил письмо о том что заявка принята. Какие будут следующие шаги?

Я предполагаю что мне нужно сделать доверенность на закрытие ФОП третьему лицу (бухгалтеру, например). Но вначале хочу понять каков весь процесс, и насколько он "быстрый".

Спасибо.

**Comment by agerman-ua** [comment]
Добрый день, Антон. ( @1st )
Вам необходимо иметь действительную ЭЦП. 
Если её нет - получить можно по ссылке доступной на странице услуги.
Условно можно разделить процесс на две части. Официальное прекращение деятельности ФОП и снятие с налогового учёта. Мы, с помощью портала, можем помочь получить только первую услугу.
Получение письма о принятии заявки - подтверждает факт подачи и уникально идентифицирует Вашу заявку на портале. Это значит что Ваше обращение попало в общую по соответствующей области (сейчас Днепропетровская и Тернопольская) очередь таких заявок.
Абсолютно точно сроки назвать затрудняюсь - есть факторы которые непредсказуемы (например сам реестр сейчас работает с перебоями).
Но вполне можно рассчитывать на закрытие в течении пары недель января. Это с учётом праздников и прочих выходных дней.
Это приведёт к тому что новых обязательств возникать не будет.
Останется решить вопросы связанные с прошлыми периодами (отчеты, налоги и прочее). Это вторая часть. Тут тоже можно обойтись без личного визита - отправить заявление заказным с уведомлением и описью вложения. Прочие детали бухгалтер Вам подскажет.
С уважением, Август.

**Comment by 1st** [comment]
@agerman-ua Кстати, подал заявку в 9 утра сегодня, в 11 часов она была уже рассмотрена и я получил письмо с подтверждением. Интересно, если в течение 10  дней не принести документы в налоговую - что в таком случае может быть? Ведь в присланном документе ничего не говорится о сроках. Спасибо.

**Comment by agerman-ua** [comment]
Добрый день. @1st 
Проверьте, на всякий случай, Ваш статус в реестре минюста.
https://usr.minjust.gov.ua/ua/freesearch
Вопрос про последствия конечно больше к налоговой.
Поскольку речь идет о предоставлении налоговой отчетности за последний период действия до закрытия санкции не должны отличаться от обычных в таких случаях за несвоевременно предоставленные отчеты. Но Вам ведь никто не мешает отправить их по почте заказным письмом с уведомлением и описью вложения. Без визита к ним. А потом письменно запросить о задолженности.
С уважением, Август.
