### ISSUE TITLE
Довідка про місце реєстрації та склад сім’ї (форма 3) - отсутствует район

### ISSUE THREAD

**Issue by Ksellos** [e-government-ua/iForum#716]
В параметрах заявки на услугу Довідка про місце реєстрації та склад сім’ї (форма 3), отсутствует Новокодацкий (Ленинский) район г. Днепра.

**Comment by annastolbova** [comment]
Послуга діє тільки для Соборного, Чечелівського і Шевченківського районів. 
райони додаються поступово тільки після узгодження з ними.
