### ISSUE TITLE
Авторизация 16-летнего с паспортом IDcard,проблемы оплатить доставку справки Укрпоштой

### ISSUE THREAD

**Issue by drnata** [e-government-ua/iForum#717]
Задача: Получить Довідку про склад сім"ї для подачи в военкомат. 

Попытки авторизации на сайте через IDcard требуют загрузки какого-то приложения, QR-код телефон сканирует несколько минут и не определяет никак. Приложение, которое там указано скачать и установить - не качается, вбитое вручную в PlayMarket  не находится.

Вопрос: Каким образом мой сын может заказать справку на свое имя? Судя по форме , которую надо заполнить, я не могу заказать справку на его имя. Это решаемо?

**Comment by drnata** [comment]
И, кстати, в разделе "Для чого вап потрібна довідка" нет пункта про военкомат.

**Comment by drnata** [comment]
Попытки заказать справку  ужена свое имя привели к проблемы оплаты.  Неоднократные попытки оплатить услуги Укрпошти по доставке справки через Приват24, LiqPay или хотя бы получить реквизиты оплаты ни к чему не привели. Все время пишет - ошибка, платеж отклонен. Обращение в банку и проверка не выявили нарушений. Оператор банка, сказал, что проблема у принимающей стороны, т.к. в виде ошибки указано: Не найден public_key. И как получить услугу?

**Comment by zolotovatatyana** [comment]
@Akylish88

**Comment by Akylish88** [comment]
Добрый день подскажите пожалуйста номер вашей заявки.
И я очень прошу вас прикрепить скриншот ошибки.

**Comment by drnata** [comment]
Здравствуйте. Заявка 0-908342203
<a target="_blank" href="http://radikal.ru/big/14n29lt78pbe2"><img src="http://s020.radikal.ru/i721/1701/11/4449b0e92a91t.jpg" /></a>

<a target="_blank" href="http://radikal.ru/big/uhgvdhnpjee6w"><img src="http://s013.radikal.ru/i325/1701/68/e84a92faffcdt.jpg" /></a>

**Comment by Akylish88** [comment]
Переподайте пожалуйства заявку.
Это редкий сбой.

Напишите пожалуйста, какую ошибку выдало в первый раз.

**Comment by drnata** [comment]
Сомневаюсь,попыток было несколько, но кажется первой шибкой было : Не найден public_key.
Попробую еще раз.

**Comment by drnata** [comment]
С промежуточным странным сообщением (см. на скринах) и , цитирую - "Неизвестная ошибка", самовольной деавторизацией,но операция завершена успешна :))) У меня ощущение, что стоит мне сделать попытку заказать услугу , все срочно ломается.

<a target="_blank" href="http://radikal.ru/big/3bp82ocwgasim"><img src="http://s019.radikal.ru/i611/1701/c4/09b04a6f8f72t.jpg" /></a>

<a target="_blank" href="http://radikal.ru/big/oy2ucqica0jfh"><img src="http://s020.radikal.ru/i704/1701/f8/47e31fa12b5dt.jpg" /></a>

**Comment by Akylish88** [comment]
Давайте в телефонном режиме.
Дайте мне свой телефон.
Или наберите меня 0993527640.

**Comment by drnata** [comment]
В общем, чуда не случилось. Справку  заказала 22 дня назад, опалата прошла, радостно написали, что выслали. Ничего не пришло. Походы на почту бесконечные с просьбой посмотреть письмо - заколебали. Сообщение на самом сайте, что справка не пришла, и что делать - в ответ глухое молчание. Ок. Очередная попытка что-то сделать с iGov - неудачная.

**Comment by Akylish88** [comment]
Пришлите пожалуйста скрин письма с ответом. Регистратор говорит, что вам был отказ. Мне нужно больше информации что б вам помочь.

**Comment by drnata** [comment]
Мне уже помощь не нужна, пошла и взяла справку. Вот скриншот по заявкам 
<a target="_blank" href="http://radikal.ru/fp/thiy5b225w17e"><img src="http://s019.radikal.ru/i627/1701/99/672bd0c06550t.jpg" ></a>
Вот ответы на текущую заявку 
<a target="_blank" href="http://radikal.ru/fp/fqfjb48k5th0c"><img src="http://s019.radikal.ru/i604/1701/b3/04cf8b3f16adt.jpg" ></a>
<a target="_blank" href="http://radikal.ru/big/zpx3cnfw5xd2i"><img src="http://i045.radikal.ru/1701/00/cd1e33652fa1t.jpg" /></a>
<a target="_blank" href="http://radikal.ru/fp/wq7b5nshsy9f2"><img src="http://s020.radikal.ru/i700/1701/45/3d0684623321t.jpg" ></a>
А вот счет от liqpay 
<a target="_blank" href="http://radikal.ru/fp/wg99z8864beel"><img src="http://s020.radikal.ru/i714/1701/92/a18bb5b13ef1t.jpg" ></a>

**Comment by drnata** [comment]
Теперь будет просто приятно, если вернут деньги на карту. Но даже не надеюсь. Хорошо, хоть сумма не велика :(

**Comment by Akylish88** [comment]
Напишите номер карты.

**Comment by Akylish88** [comment]
Актуален ли еще вопрос возврата средств?

**Comment by drnata** [comment]
да, простите, забыла отправить номер.
4149 4978 2612 8490

**Comment by Akylish88** [comment]
Подтвердите возврат средств.

**Comment by drnata** [comment]
Получила. Спасибо за участие в проблеме.
