### ISSUE TITLE
Не возможно авторизоваться через BankID

### ISSUE THREAD

**Issue by dutchakdev** [e-government-ua/iForum#718]
Не доступен BankID, только у меня?
https://igov.org.ua/journal

<img width="321" alt="image 2017-01-06 at 16 03 43" src="https://cloud.githubusercontent.com/assets/1294321/21720057/b6db9dee-d429-11e6-8fe0-3c92d404ecce.png">

**Comment by annastolbova** [comment]
спробували зайти, все працює в звичайному режимі,
будь ласка, спробуйте очистити кеш та кукіз в браузері та спробуйте зайти ще раз.
Якщо буде можливість, то напишіть нам про результати.
Якщо буде помилка, то зробіть скрін помилки, будь ласка, та надішліть сюди.
