### ISSUE TITLE
Зняття з обліку в податковій, роз'ясніть будь ласка!

### ISSUE THREAD

**Issue by Ihor1987** [e-government-ua/iForum#719]
У мене така ситуація: 5 січня через IGOV замовив послугу "Державна реєстрація припинення підприємницької діяльності фізичної особи – підприємця за її рішенням", 6 січня на електронну пошту прийшло повідомлення про винесення позитивного рішення. В Єдиному державному реєстрі юридичних осіб, фізичних осіб-підприємців та громадських формувань зафіксовано стан "припинено".
Тепер протягом 10 днів я повинен звернутись в податкову.
Питання наступні:
1) Як виглядає цей ліквідаційний звіт? Де можна знайти зразок його? Буду вдячний, якщо скинете посилання на зразок цього звіту і напишете як його заповнювати (діяльність ФОП не веду з вересня 2010 року).
2) Чи повинен я паралельно з ліквідаційним звітом писати якусь заяву та подавати інші якісь звіти?
3) У мене немає фізичної можливості найближчим часом потрапити до податкової інспекції. Чи можу я всі ці звіти та заяви надіслати через інтернет? 
Заздалегідь дякую за допомогу!

**Comment by agerman-ua** [comment]
@Ihor1987 
Доброго дня.
1. Це звичайний останній звіт за останній рік діяльності. У Вашому випадку пустий за 2016. Є питання щодо декількох днів 2017 року, про це буде далі.
2. Начебто ні, можливо в податковій можуть попросити написати заяву на проведення перевірки, але це не обов'язково. Просто на протязі 3-х років може бути проведена перевірка податковою та нараховані штрафи та податки за період діяльності ФОП. Тобто до закриття.
3. Після закриття в реєстрі начебто неможливо (поки не було змоги перевірити напевно) подати в електронній формі але можна завжди скористатися поштою на замовлення та описом вкладення листа.
Зараз готовимо більш детальну інструкцію про дії в податковій.
З повагою, Август.

**Comment by vladchv** [comment]
В мене зняття з обліку 04.01.17 р. Звіт за 2016 рік здав в електроному вигляді 03.01.17- єдиний податок , I група.  Тепер залишається питання щодо 4-х днів 2017 року - протягом 10-ти днів, чи в наступному році, чи інший варіант ?

**Comment by agerman-ua** [comment]
@vladchv 
Треба уточняти. Думаю Ваш випадок зараз буде дуже масовим.

**Comment by Ihor1987** [comment]
@agerman-ua Дуже дякую за інформаццю

**Comment by Ihor1987** [comment]
@vladchv Підкажіть будь ласка де можна здати звіт в електронному вигляді? Дякую!

**Comment by agerman-ua** [comment]
@Ihor1987 
Ниже варианты.
http://prokey.org.ua/kak-besplatno-otpravlyat-otchetnost-v-elektronnom-vide
http://www.05366.com.ua/news/708980

**Comment by vladchv** [comment]
@Ihor1987 
Я фориую звіт у OPZ, а відправляю через Sonata, - так приймає моя податкова.  Скористуйтесь порадою від @agerman-ua  через електронний кабінет - http://www.05366.com.ua/news/708980

**Comment by Ihor1987** [comment]
Дуже Вам дякую за допомогу!

**Comment by vladchv** [comment]
Доброго дня, чи є  вже інформація  щодо дій  та звітів ФОПа - платника єдиного податку , які припинили реєстрацію в перші дні 2017 року ?

**Comment by agerman-ua** [comment]
Так є. Ще не універсальна інструкція. Сьогодні ще раз перегляну та видам тут. Може хтось вже пройшов цей шлях і можливо запропонує якийсь додатковий лайфхак.

**Comment by vladchv** [comment]
На форумі " Бухгалтер 911" поставив питання : "Доброго дня, ФОП на спрощенній системі Ігрупа, дата припинення діяльності 04.01.17 Підкажіть будь-ласка, чи потрібно сплатити за січень 2017 єдиний податок та як правильно заповнити ліквідаційну декларацію?
Відповідь : " За январь - ЕН и, если не пенсионер/инвалид, - ЕСВ.
Заполняете "звітну" декларацию - как обычно: КВЕДы, январскую оплату... В бумажной форме разницы нет какую форму файла для заполнения Вы выберите. От руки напишите "ліквідаційна". У меня сомнения только с выбором периода, который нужно проставлять в декларации.
Думаю, что это должна быть "годовая" (для 1 и 2 групп) - за 2017-й год "

**Comment by agerman-ua** [comment]
"Думаю, что это должна быть "годовая" (для 1 и 2 групп) - за 2017-й год "
@vladchv 
Нет. Могут быть проблемы. Годовой ликвидационный должен быть за 2016 год и отдельный отчет с 01 января 2017 по дату закрытия в реестре.

**Comment by vladchv** [comment]
На " Вістник "ДФС пишуть, що Нормами Податкового кодексу не передбачено ліквідаційної звітності для фізичних осіб — підприємців.http://www.visnuk.com.ua/ua/pubs/id/9247

**Comment by agerman-ua** [comment]
Цитата
"Отже, фізичні особи, щодо яких до  Єдиного державного реєстру внесено запис про припинення підприємницької діяльності фізичної особи — підприємця, подають податкові декларації у  строки, визначені п.  49.18 ст.  49 Податкового кодексу, залежно від  обраної ними системи оподаткування в  період підприємницької діяльності."
Значит подаём в установленные сроки уже не электронный отчет только с 01 января по день закрытия. Т.е. по 04 января.
Ликвидационным он станет после написания на нём этого слова. Тут, мне кажется, не принципиально. Возможно просто привычное определение вместо "последний отчет".
С уважением, Август.
