### ISSUE TITLE
Как получить выписку о регистрации с указанием ИНН?

### ISSUE THREAD

**Issue by victor-n-yegorov** [e-government-ua/iForum#721]
Нужна выписка о регистрации ФОП, в которой указан мой ИНН.
Я сформировал выписку на сайте с указанием ИНН, но в ней его нет.
Заранее благодарю за помощь

**Comment by agerman-ua** [comment]
@victor-n-yegorov 
Добрый вечер.
А где регистрировались? Если на портале iGov то пожалуйста укажите номер обращения.
С уважением, Август.

**Comment by victor-n-yegorov** [comment]
Здравствуйте
Да, я регистрировался на iGov.

Информация по запросу выписки:
Номер запиту: 1001961651
Дата запиту: 09.01.2017

**Comment by agerman-ua** [comment]
@victor-n-yegorov 
Простите, но мне необходим номер обращения по регистрации Вас именно на портале iGov.

**Comment by victor-n-yegorov** [comment]
Я сразу не понял, какой номер нужен.
Номер обращения по регистрации: № 0-777093771

**Comment by agerman-ua** [comment]
@victor-n-yegorov 
Добрый день, простите что пришлось немного подождать.
Хотел убедиться что всё норм. 
Теперь точно можете по уникальному коду (из почты в ответе на обращение) получить выписку в любое время с портала минюста по бесплатному запросу.
С уважением, Август.

**Comment by victor-n-yegorov** [comment]
Спасибо за помощь
