### ISSUE TITLE
Добавление видов деятельности ФОП

### ISSUE THREAD

**Issue by alexbgua** [e-government-ua/iForum#722]
заявка 0-912233777 висит
подскажите, а сколько времени ждать - думал за день добавится
спасибо

**Comment by agerman-ua** [comment]
@alexbgua Нет, за день точно не получается сейчас. ( У нас регистраторы обрабатывают сейчас все услуги по ФОП и юрлицам. В хронологическом порядке. Сейчас очень много заявок по закрытию ФОП. Это минимум до начала следующей недели очередь. Если не будете ждать - прошу дать знать, закроем заявку чтобы регистраторы не тратили время на полную проверку перед обработкой в реестре
С уважением, Август.

**Comment by alexbgua** [comment]
Понял, спасибо, пока подожду.

**Comment by agerman-ua** [comment]
Спасибо.

**Comment by alexbgua** [comment]
0-912233777 закройте плиз заявку - вопрос решен на месте у регистратора.
Спасибо.

**Comment by agerman-ua** [comment]
Принято, закрыто. Спасибо за информацию.
