### ISSUE TITLE
Регистрация ФОП. Звернення № 0-912663142

### ISSUE THREAD

**Issue by VictoriaK13** [e-government-ua/iForum#723]
Добрый день!
Обращение оформляла 10.01.2017. Днепропетровская область, г.Першотравенск.
Подскажите, пожалуйста, как долго ожидать факта регистрации?
И будет ли обработано в налоговой заявление на Единый налог, если оно прикреплено к заявке?

**Comment by agerman-ua** [comment]
Добрый день, @VictoriaK13 
В связи с загрузкой массовыми закрытиями ФОП, и тем что регистраторы обрабатывают всё что поступает для регистрации в хронологическом порядке можно ожидать обработки на следующей неделе. И, да, прикреплённое заявление для налоговой будет отсканировано регистратором и добавлено в реестр. Именно там налоговая его и увидит. Вместе с Вашей регистрацией.
Но, если Вы указали в заявлении дату регистрации плательщиком единого налога например завтра а регистрация произойдёт послезавтра, то налоговая может формально Вам отказать (регистратор просто передает заявление). Поэтому пока лучше после регистрации убедиться что Вас поставили на налоговый учёт. С соответствующим статусом. Это очень зависит от конкретной налоговой.
С уважением, Август.

**Comment by VictoriaK13** [comment]
Насколько я понимаю, там есть 10-тидневный промежуток времени для подачи заявления на Единый налог. Т.е. если обработка регистратором произойдёт на следующей неделе, то и подача заявления на Единый налог будет считаться от этой же даты, верно? 
Дату перехода на Единый налог в заявлении не указывала.

**Comment by agerman-ua** [comment]
@VictoriaK13 
Вы абсолютно правильно всё поняли и сделали.
Очень приятно. Спасибо.
С уважением, Август.

**Comment by VictoriaK13** [comment]
Добрый день!
Заявка всё ещё не обработана, хотя была 'открыта и начата эскалация'. Что это значит? Может, в чём-то проблема и от меня ещё нужны документы?

**Comment by agerman-ua** [comment]
@VictoriaK13 
Нет. Нужно чтобы администратор забрал из очереди.
Возможно вопросы у администратора и возникнут - Вам или позвонят или будет запрос в почту (зависит от конкретного человека и его стиля работы).
С уважением, Август.

**Comment by VictoriaK13** [comment]
Подскажите тогда, пожалуйста, как долго этот "забор из очереди" может занять?

**Comment by agerman-ua** [comment]
В Вашем случае уже сегодня-завтра. Просто заявки отрабатывают в хронологическом порядке.

**Comment by VictoriaK13** [comment]
А сама обработка много времени занимает?

**Comment by agerman-ua** [comment]
Нет. Обычно с передачей регистратору и обратно - сутки. Это с получением информационного письма и закрытием обращения.
Могут, конечно, появиться вопросы у чиновника, но это скорее исключения.

**Comment by VictoriaK13** [comment]
Возможно ли, если в ближайшие пару дней заявка не обработается, отменить её и сделать это всё вручную по месту жительства? Или необходимо ожидать окончания обработки онлайн? Или возможно параллельно подать ещё и в бумажном видепо месту жительства и результат будет по тому способу, который обработается быстрее?

**Comment by agerman-ua** [comment]
@VictoriaK13 
Да. Если в понедельник-вторник не обработают - можно будет отменить. Напишете просто об этом.
Параллельно - не очень хорошо, просто если уже пойдёте к регистратору - лучше отменить заявку. Очередь на портале станет меньше - регистратор потратит время (проверки Вашего обращения и на отказ по ней) уже с большей пользой на того кому нужнее. В любом случае мы не конкурируем по скорости с личным визитом к регистратору. Он однозначно быстрее и более предсказуемый по срокам.
С уважением, Август.

**Comment by VictoriaK13** [comment]
Поняла. Спасибо.
А возможно как-то узнать, под каким номером в очереди стоит моё обращение?

**Comment by agerman-ua** [comment]
@VictoriaK13 
Номеров в очереди нет. Есть дата и время подачи заявки и её уникальный номер.

**Comment by VictoriaK13** [comment]
Можно, пожалуйста, отменить Звернення № 0-912663142 ?

**Comment by agerman-ua** [comment]
@VictoriaK13 Отменили.
