### ISSUE TITLE
справка о отсутствии судимости

### ISSUE THREAD

**Issue by alexbgua** [e-government-ua/iForum#724]
подскажите, пожалуйста, сколько времени занимает сделать справку об отсутствии судимости?

**Comment by agerman-ua** [comment]
До месяца обычно. А какой у Вас номер заявки?

**Comment by alexbgua** [comment]
ребенок подала, просто она оказалась годна месяц всего. А как отменить запрос там нет такой функции. 
Спасибо

**Comment by alexbgua** [comment]
Если можно отмените 0-916806472, плиз

**Comment by agerman-ua** [comment]
Принято. На подтверждение отмены будет письмо.
С уважением, Август.

**Comment by elenapopova1525** [comment]
подскажите как сейчас можно онлайн заказать справку о несудимости. Летом заказывала а сейчас не могу ее найти

**Comment by alexbgua** [comment]
https://igov.org.ua/service/1/general
пользуйтесь поиском
Надання довідки про притягнення до кримінальної відповідальності, відсутність (наявність) судимості або обмежень, передбачених кримінально-процесуальним законодавством України

**Comment by elenapopova1525** [comment]
спасибо.
