### ISSUE TITLE
Ошибка в фамилии

### ISSUE THREAD

**Issue by kovaan** [e-government-ua/iForum#725]
Оформила заявку "Державна реєстрація припинення підприємницької діяльності фізичної особи – підприємця за її рішенням" 0-914988353 12.01.2017. Сегодня 16.01 заметила, что при входе на iGov через ПРИВАТ 24 фамилия моя написана неправильно. Надо ли мне подавать заявку заново?

**Comment by agerman-ua** [comment]
Добрый день, @kovaan 
Да. Конечно, необходимо подать новую, после закрытия первой. Сейчас закроем - сможете подать новую. После того как изменят в банкайди, конечно. И, кстати, после этого проверьте ЭЦП, нужно и там правильную фамилию.
С уважением, Август.

**Comment by kovaan** [comment]
В банке уже исправили. А насчет ЭПЦ, то сказали, что туда информация сама подтягивается.

**Comment by kovaan** [comment]
Вы написали "сейчас закроем".  Вы мне скажите, что можна новую подавать, или мне прийдет уведомление?

**Comment by agerman-ua** [comment]
Да. Письмо с отказом.

**Comment by kovaan** [comment]
Спасибо. Подала новую заявку.  Номер  0-918286024. Скажите, в этом месяце успею сняться с учета?

**Comment by agerman-ua** [comment]
Очень реально в этом месяце. 
Просто сейчас из-за новогодних праздников сложилась ситуация когда выходных в которые продолжали поступать заявки было много, а рабочих дней, когда обрабатывали, было мало.

**Comment by kovaan** [comment]
Спасибо огромное за помощь.
