### ISSUE TITLE
Порядок закрытия ФОП Днепр

### ISSUE THREAD

**Issue by accaunt1988** [e-government-ua/iForum#727]
после подачи заявления на сайте, получил положительный ответ. Приехал в налоговую, кроме громадных очередей увидел такую заяву:
До уваги платникiв податкiв - фiзичних осiб пiдприемцiв, якi находяться в стадii припинення!!!
1. Звернутися ЄДР (комсомольска 58) із заявою що до припинення підприемницької діяльності
2. Надати заяву до ПФУ (чичерина 100) що до отримання акту звірки - для ФОП, які зареєструвалися до 1.10.2013
3. Зьявитися до ДПІ у Красногвардійському районі для завершення процедури припинення після 09.02.2017

В связи с этим у меня есть вопросы:
- нужно ли отвозить заявление на комсомольскую если я подавал через сайт igov ? если надо, то какой формат этой заявы? 
- в ПФУ мы только заяву отвозим на акт сверки? саму сверку мы не забираем у них?

**Comment by agerman-ua** [comment]
Добрый день. @accaunt1988 
Если Вы получили положительный ответ по услуге закрытия ФОП, поданную через iGov, всегда можно проверить, в самом реестре, состояние Вашего ФОП. Если там "припинено" то п.1 выполнен в полном объеме.
По второму вопросу - нужно уточнять при подаче заявления, если они вносят в реестр то нет, но думаю что нужно забирать саму сверку. В общем самый правильный вариант - уточнить при подаче заявления. И, если можно, напишите сюда что ответят. Спасибо.
С уважением, Август.
P.S. Спасибо за перечень пунктов.

**Comment by accaunt1988** [comment]
В реестре отметка что "припинено" уже стоит. уточнил в налоговой, сказали что сразу приходить после 09.02.17 - назначат проверку для окончательного закрытия чп.
Отчетные документы за 2016г сдаются в обычном порядке.

**Comment by agerman-ua** [comment]
@accaunt1988 
Спасибо.
