### ISSUE TITLE
Оформление заявки на получение загранпаспорта

### ISSUE THREAD

**Issue by AlexVorob** [e-government-ua/iForum#728]
Добрый день, столкнулся с такой проблемой. Мне необходимо оформить загранпаспорт, в отделении ДМС сказали, что заявки на оформление подаются только через портал IGov. Для того что бы подать заявку с портала IGov необходимо пройти верификацию данных, для этого нужен либо ЕЦП, либо через банк. Я не работаю, банковских карт не имею, ЕЦП соответственно тоже нет. 
Подскажите как мне подать заявку ?

**Comment by julyprodan** [comment]
Добрый день! Процедура записи в электронную очередь через портал iGov предполагат верификацию по средствам ЕЦП, ID-карты или Bank ID банка, из представленного на сайте. Упрощеной процедуру не существует, поэтому помочь Вам не смогу.

С другой стороны, сотрудники подразделения не имеют права Вам отказывать в оформлении паспорта без очереди iGov.

**Comment by julyprodan** [comment]
В каком подразделении Вам отказали в приёме?

**Comment by annastolbova** [comment]
немає відповіді
