### ISSUE TITLE
Фильтр доступных услуг по областям?

### ISSUE THREAD

**Issue by 2957023985-2835798** [e-government-ua/iForum#729]
Нужен фильтр доступных услуг по областям. Иначе тычешься в услуги, а система говорит, что услуга не активна. Морской бой какой-то.

**Comment by zolotovatatyana** [comment]
Здравствуйте. Такой фильтр давно реализован.

![image](https://cloud.githubusercontent.com/assets/17428210/22238520/8e4c1ae4-e21a-11e6-9b0e-3c3a48023725.png)

**Comment by 2957023985-2835798** [comment]
спасибо
