### ISSUE TITLE
Мій журнал, помилка

### ISSUE THREAD

**Issue by Artyom-ARS** [e-government-ua/iForum#73]
На вкладці "Мій журнал" замість дати показує "NaN.NaN.0NaN NaN:NaN"

**Comment by zhmurko** [comment]
подтверждаю проблему: в браузере Firefox 42 воспроизводится на Win10 и MacOsX 10.10

**Comment by zhmurko** [comment]
@Artyom-ARS попробуйте в другом браузере зайти - в Google Chrome дата заявки отображается нормально
