### ISSUE TITLE
Электронно-цифровая подпись (ЕЦП) от А-банка

### ISSUE THREAD

**Issue by korrch** [e-government-ua/iForum#730]
Подскажите пожалуйста, подойдет ли ЕЦП от А-банка?
В банке выдают, но они не знают подойдут ли ключи по формату. не хочется зря платить деньги.

**Comment by agerman-ua** [comment]
Должны подойти. А какая стоимость?
Неужели нет карточки Приватбанка? У них бесплатно.

**Comment by korrch** [comment]
да стоимость 74 гр за год. мелочи жизни.
приватбанка карты нету

**Comment by agerman-ua** [comment]
Тогда подождите до завтра. Уточню наверняка.

**Comment by korrch** [comment]
ок. тогда жду.

**Comment by agerman-ua** [comment]
Добрый день.
Заверили что не должно быть проблем с ЕЦП от А-Банка.

**Comment by korrch** [comment]
спасибо
