### ISSUE TITLE
проблема при закриті ФОП через портал

### ISSUE THREAD

**Issue by dobrotvirskoy** [e-government-ua/iForum#731]
подав заявку на закриття ФОП номер заявки 0-926151666
отримав відмову оскільки ФОП зареєстрований в іншій області
хоча закон про державну реєстрацію фізичних і юридичних осіб 
дозволяє здійснювати дії незалежно від місця
так звана екстериторіальність
зокрема ст 7 п3
ст4 п2
підкажіть що робити

**Comment by agerman-ua** [comment]
@dobrotvirskoy 
На жаль будь-які посилання безсилі, оскільки реєстратор, наприклад Дніпропетровської області не в змозі виконати в ЕДР будь-які дії за межами Дніпропетровської області. Це обмеження самого реєстру. Повноцінну екстериторіальність відмінили влітку минулого року.
На сьогодні підключено Дніпропетровську, Тернопільску, Львівську та Донецьку області. ФОП та громадянам які бажають виконати реєстраційні дії в межах зазначених областей ми можемо допомогти, в інших - треба звертатися безпосередньо до будь-якого реєстратора тієї області.
З повагою, Август.

**Comment by dobrotvirskoy** [comment]
Власне я і є ФОП який зареєстрований у Львівській області

**Comment by dobrotvirskoy** [comment]
Львівська обл недоступна?

**Comment by agerman-ua** [comment]
Вибачте. Послуга саме "закриття ФОП" у Львівській області не підключена. Це тимчасово. Планується у лютому-березні. Не вистачає вільного часу у реєстраторів. Намагаємось розширити кількість підключених реєстраторів - зараз тільки реєстрація ФОП та юрсоіб.

**Comment by EdwardRymar** [comment]
Доброго дня. Відравив заявку на припинення діяльності через igov 28.12.16. Отримав на пошту відповідь з номером. Зараз вже 24.01. Звернувся до реєстратора особисто та, нажаль, отримав відмову. Кажуть що 10.01.2017 особою Шкута Н.М. накладено обмеження на мій запис у реєстрі. Що робити далі?

**Comment by agerman-ua** [comment]
@EdwardRymar 
Доброго дня.
Дуже жаль що так сталося. Ми завжди намагаємось виключити такі ситуації. Звісно це не залежить від порталу. Завтра з ранку буду намагатися закрити питання саме цим реєстратором.
З повагою, Август.

**Comment by onevenkoss** [comment]
в наших змі повідомляли що людина відкривалася в Маріуполі, а закрилася тут через Дніпро. То як це не працює екстериторіальність, то напевно так хотілось. А якщо такий чужинець як я, вже подав тут заяву і піду понесу папір особисто до свого центру по місцю реєстрації, це ніяк не вплине на результат?

**Comment by agerman-ua** [comment]
@onevenkoss 
От не знаю що сказати. Неможливо таке зробити звичайним чином. Тільки реєстратор з самої області може виконувати дії в ньому по ній.
)) Ви не чужинець, прсто якщо подали не по своєму регіону, просто напишіть про це, ми виключимо Ваше звернення з черги, хай хоч трохи поменшає. А якщо по своєму - то перед візитом до реєстратора теж дайте знати - ми знов таки виключимо з черги Ваше звернення і щиро подякуємо. ))) А результат не покращиться точно. Закрити двічі не вийде. )))

**Comment by onevenkoss** [comment]
agerman-ua, =Заявка подана - Надання послуги= , у мене наче статус змінився, от не пам'ятаю, надання послуги це шо означає хтось взявся за розгляд?

**Comment by agerman-ua** [comment]
Ні. Не обов'язково. Який номер звернення?

**Comment by onevenkoss** [comment]
@agerman-ua, 0-925956601 відміняйте

**Comment by onevenkoss** [comment]
от і добре, не хотілось шоб якась особа шкут н.м шось наклала на моє звернення ахаха

**Comment by EdwardRymar** [comment]
@agerman-ua , Доброго вечора. Отримав листа на пошту з позтивним рішенням про припинення... Дуже дякую!

**Comment by dobrotvirskoy** [comment]
Львівська обл недоступна?

**Comment by agerman-ua** [comment]
@dobrotvirskoy 
На закриття ФОП так. (
Вони не готові опрацьовувати цю послугу зараз. 
Попередньо планується запуск у лютому-березні.
З повагою, Август.
