### ISSUE TITLE
Как узнать в каком статусе находится ЧП?

### ISSUE THREAD

**Issue by 1st** [e-government-ua/iForum#732]
Добрый день.

Для подачи годового отчета нужно знать на какой системе налогообложения я нахожусь. Год назад уехал из Украины и работаю заграницей. По телефону в налоговой говорят что это конфидециальная информация.

На сайте https://usr.minjust.gov.ua/paidextract можно выбрать какие пункты внести в выписку. Но я не нашел там пункт, говорящийо том, на какой системе налогообладения я находусь сейчас (и был весь 2016 год).

Если кто знает как можно получить эту информацию без посещения налоговой - прошу помочь. Спасибо.

**Comment by agerman-ua** [comment]
@1st 
Добрый вечер.
Можно попробовать через кабинет налоговой.
https://cabinet.sfs.gov.ua/cabinet/faces/public/reestr.jspx;CABINET=SAHR_4GntFzfnGwzHb6mDR1BxBdwEEoOVWfOS6Mm5_PCd6LEQkgk!106075105
Разберётесь?

**Comment by 1st** [comment]
@agerman-ua сейчас буду пробовать. Спасибо за супер быстрый ответ!

**Comment by 1st** [comment]
@agerman-ua Кстати спасибо. Вы мне помогли - я нашел бесплатную выписку где сказано с какого по какое число я был на едином налоге. Очень рад.

Хорошо бы улучшить портал igov для быстрого поиска не только по фразе, но и описанию или по тегам, а так же по русским названиям и сокращениям, и поиску по части слова. И все бы в live режиме, с фильтрацией на фронтенде...

**Comment by agerman-ua** [comment]
@1st 
))) Отлично. Рад что смог помочь.
По поводу улучшений - полностью солидарен. Ещё много что нужно сделать. )
