### ISSUE TITLE
Закрытие ФОП в Донецкой области

### ISSUE THREAD

**Issue by Nat99999** [e-government-ua/iForum#735]
Подскажите, пожалуйста, действительно ли уже работает закрытие ФОП для Донецкой области?
А то на странице статистики https://igov.org.ua/service/87/statistics как-то странно выглядит: Середня оцінка = 0,  Таймінг = 0. Это нормально?
Создала заявку вчера (24 января) в обед, это когда примерно до нее очередь дойдет? Заявка 0-928511701

**Comment by agerman-ua** [comment]
@Nat99999 
Очень приятно это говорить. Да. Действительно работает. Сегодня были перебои в работе реестра. И обработано только несколько заявок из очереди. Завтра все подключенные регистраторы будут получать новые ключи для работы с ЕДР и, следовательно, послезавтра можно надеяться на результат.
С уважением, Август.

**Comment by Nat99999** [comment]
@agerman-ua 
> Очень приятно это говорить. 

Вы даже не представляете, насколько приятно это слышать :) особенно жителям Донецка и прочих городов за линией фронта. Огромное Вам спасибо!

**Comment by af7** [comment]
1. Для донецких ФЛП можно обращаться в любую налоговую в любом городе?
2. Если я не смогу обратиться в налоговую течение 10 дней - 
а) какие последствия? 
б) ФЛП все равно будет считаться закрытым?
в) ЕСВ уже можно будет не платить?

**Comment by Nat99999** [comment]
@af7 
Дончанам нужно обращаться в одну из Мариупольских налоговых http://dn.sfs.gov.ua/okremi-storinki/struktura/73802.html
А вот лично или почтой - решайте сами.
Кстати, вот статья о закрытии ФОП для переселенцев https://dou.ua/forums/topic/17192/

**Comment by agerman-ua** [comment]
@af7 
1. Там есть отдельный порядок, можете воспользоваться советом @Nat99999 
2/а - сразу никаких, потом штрафы за не сданный вовремя отчет последний и может ещё какие-то нарушения найдут и накрутят пеню. Это касается только периода деятельности ФЛП.
2/б - Да ФЛП закрыт с момента закрытия в реестре
2/в - Только за время когда был зарегистрирован ФЛП. После закрытия не платите.

**Comment by af7** [comment]
@Nat99999 , заявку заявку на iGov еще не делал, так как вряд ли быстро попаду в налоговую в Мариуполе и пытаюсь понять что будет если.

@agerman-ua , так ведь на донецких требования по сдаче отчетов и штрафы вроде не распространяются. Или я ошибаюсь?

То есть я пытаюсь понять имеет ли смысл сразу закрыть через iGov сейчас, а в налоговую в Мариуполе прийти когда-нибудь потом или лучше пока вообще не закрываться.

**Comment by agerman-ua** [comment]
@af7 Если Вы не работаете как ФЛП и не планируете этим заниматься ближайшие месяцы то закрыть - правильный вариант. Открыть несложно. 
Это же ежемесячный расход в 700 с копейками. 
Но окончательное решение принимать Вам как и ответственность за все его последствия.
С уважением, Август.

**Comment by af7** [comment]
Закрыть надо однозначно. Главный вопрос:
1. После закрытия на iGov люди с донецкой пропиской по прежнему свободны от своевременных отчетов и штрафов? И соответственно это можно сделать позже?
2. Отчеты в налоговую можно подавать в эл. виде и без iGov. Тогда можно ли сделать эту вторую часть "ліквідаційні звіти та виконати інші дії для завершення закриття Вашого ФОП" удаленно (не через iGov, но удаленно)?

**Comment by agerman-ua** [comment]
@af7 
1."Закрытие на iGov" это идентично фразе просто закрыть в реестре. Не более и не менее.
Есть требования к процессу закрытия. Своевременно сдать отчет туда входит. 
2. После закрытия ФЛП сдача в электронном виде, насколько мне известно, невозможна. Только по почте заказным с уведомлением и описью вложения или лично.
С уважением, Август.

**Comment by Nat99999** [comment]
@af7 
1. С одной стороны, меня удивляет, почему здесь в Донецке все так уверены, что можно не сдавать отчеты (по-моему, хоть пустые, но сдавать надо). А с другой стороны, когда другу на днях "посчастливилось" дозвониться в налоговую, и он получил ответ "Вы должны оплатить ВСЕ за ВСЕ периоды", меня это тоже удивляет - почему Украина обязывает нас платить ЕСВ и налоги, но не платит пенсию нашим родителям?..
2. Лично я свои нулевые отчеты за 2016 г. попросила подругу отправить с Украины (заказным с уведомлением и описью вложения). Если получится закрыться через igov, то так же отправлю и ликвидационные отчеты за 1 квартал 2017 г., а счет попробую закрыть через онлайн-банкинг. Ну а если когда-то налоговая решит провести аудит и позвонит мне, только тогда (возможно) поеду в Мариуполь со всеми документами. Ну а Вы в Вашей ситуации решайте сами.

**Comment by af7** [comment]
@agerman-ua , спасибо за объяснения!
@Nat99999 , 
1. Есть закон "Про тимчасові заходи на період проведення антитерористичної операції", который освобождает предпринимателей АТО от штрафов за несдачу отчетов и неоплату налогов и ЕСВ. Т.е. фактически это отсрочка от всех обязательств на неопределенный, но в момент закрытия ФОП платить ЕСВ все равно придется только без штрафов.
Разумеется нет никакой логики, в том что Украина требует ЕСВ, но отказывается платить пенсии. Но так или иначе, а по факту происходит такая несправедливость.
2. А можно подробнее, как именно делается эта опись вложения? Может, какой-то примерный образец. Т.е. что конкретно нужно вкладывать кроме самого отчета.
А еще тут пишут еще про какую-то "заяву на зняття з обліку вашого фоп".
https://www.facebook.com/innalozovska/posts/1319281601448454
3. А сколько вообще времени должны вообще храниться старые документы?

**Comment by agerman-ua** [comment]
@af7 
1. Надеюсь что это работает. 
2. Уведомление отправителю о том что получатель получил. По поводу описи вложения - на почте расскажут всё. "Заява на зняття з обліку" если Вас закрыли и есть этот статус в реестре "Припинено" думаю излишний. Возможно это касается тех кто регистрировался ещё до появления данного реестра. Некоторых в нём даже нет.
3. Какие именно? Если отчеты по деятельности ФЛП - то минимум 3 года, ну лучше перестраховаться. Это срок после которого нет исковой давности к ФЛП. Этот срок не касается, если не ошибаюсь, только ЕСВ.
С уважением, Август.

**Comment by Nat99999** [comment]
Уррра, наконец-то пришел ответ от iGov (на емейл):
> Ваше звернення на тему "Державна реєстрація припинення підприємницької діяльності фізичної особи – підприємця за її рішенням", опрацьовано і по ньому винесено позитивне рішення про державну реєстрацію припинення підприємницької діяльності.
> У будь-який час Ви можете отримати результат наданих адміністративних послуг використавши "Код" під час пошуку на офіційній сторінці Міністерства юстиції України, обравши для пошуку опцію "Результат надання адміністративних послуг. 
> Вам обов'язково треба звернутися на протязі 10 діб до Вашої податкової інспекції згідно реєстрації. Там треба подати ліквідаційні звіти та виконати інші дії для завершення закриття Вашого ФОП.
Отправляла заявку 24.01.17 в обед, ответ пришел 30.01.17 в 10:00
Громаднейшее спасибо всем - и порталу, и регистраторам!
@agerman-ua  А как мне оставить отзыв? здесь  https://igov.org.ua/service/87/feedback

**Comment by agerman-ua** [comment]
@Nat99999 
Поздравляю. Всегда очень приятно видеть живой результат. )))
Если всё нормально - достаточно поставить из полученного письма выбранную Вами оценку и Вас перенаправит на страницу отзывов.

**Comment by Nat99999** [comment]
@agerman-ua  Ага, из письма ткнув, получилось оставить отзыв. Спасибо!

**Comment by af7** [comment]
@Nat99999 , поздравляю.
Я вот только все же вернусь своему вопросу. 
Как уже обсуждали, есть закон "Про тимчасові заходи на період проведення антитерористичної операції", который освобождает предпринимателей АТО от штрафов за несдачу отчетов и неоплату налогов и ЕСВ.
То есть фактически расширяет 10 дней на любой удобный срок.
Так эти освобождения от сроков отчетности в случае закрытия на донецких распространяются тоже или нет?

**Comment by agerman-ua** [comment]
@af7 
Вот материал, пока самый полный, который встречал, по данной теме.
http://fgorenie.org/novini/237-yak-pereselencyu-zakriti-fop-nstrukcya.html

**Comment by af7** [comment]
С ума можно сойти! Здесь уже что-то совсем новенькое...

> 2. Заява про зняття з обліку у державну фіскальну службу 
> звернутись до районної державної податкової інспекції з вимогою списати заборгованість зі сплати ЄСВ та штрафні санкції;

**Comment by agerman-ua** [comment]
@af7 
> С ума можно сойти!

Не нужно. Разбираемся с проблемами по мере их появления.

**Comment by Nat99999** [comment]
@af7 
Пожалуйста, не выносите мозг админам iGov! Они свою часть процесса (закрытие у регистратора) Вам сделают. А дальше сами звоните/едете в налоговую и выясняете из первых рук.
Для любителей покопаться глубже есть Гугль, есть [донецкая Кроха](http://kroha.dn.ua/topic-Likvidatsiya-FLP-Kak-zakryit-svoe-donetskoe-SPD-na-Ukraine-?f=318&t=193302), есть [обсуждение на Лиге](http://forum.liga.net/Messages.asp?did=175199&page=1), есть [Дебет-Кредит](https://news.dtkt.ua/), ну и весь интернет в Вашем распоряжении.
А здесь малоизвестный очень специализированный форум, где многие Ваши вопросы только отвлекают спецов от их основных задач, которые они кстати делают бесплатно.

**Comment by af7** [comment]
К админам никаких претензий. Только благодарности!
Согласен, что мои вопросы выходят за границы услуги iGov - придется искать ответы в других местах.

**Comment by agerman-ua** [comment]
@af7 
Спасибо за понимание. 
Но если что-то нароете полезного, делитесь тут. Всё таки это может помочь другим. ) Это как "попутное" волонтёрство. )))
С уважением, Август.

**Comment by Vikadon** [comment]
Добрый день,
после выбора Донецкая область - при вводе ключа, запрашивается пароль. ввожу пароль и пишет что "Не вдалося знайти відповідний сертифікат", что это значит? Ключ и сертификаты получали в один день 3.02 через Мастер кей. Сертификаты записаны на диск, но уже и в компьютер перенесли и установили и все равно такая надпись.

**Comment by agerman-ua** [comment]
@Vikadon 
Добрый день.
Вы авторизуетесь через ЭЦП?! Выбираете файл и вводите пароль, после чего и получаете указанную надпись?

**Comment by Vikadon** [comment]
да, через ецп

**Comment by agerman-ua** [comment]
@Vikadon 
Возможно Вы выбираете не файл хранилище ЭЦП. Может у Вас архив и криптоплагин просто "не видит" его? Поэкспериментируйте, пожалуйста, и напишите обязательно о результатах.

**Comment by Nat99999** [comment]
Извините, если не в тему. Из своего свежего опыта закрытия р/счета написала такую инструкцию, может кому поможет:

**Как закрыть счет в Приватбанке удаленно и бесплатно (через Приват24):**
- Заходим в Приват24 для бизнеса https://client-bank.privatbank.ua/p24/ 
- Меню – Счета – Закрытие счета – формируем заявку на закрытие счетов
- На следующий день счета в статусе «закрыт». Но нам еще нужно получить справку о закрытии счетов.
- Меню – Документы – Справки – Заказать – формируем заявку на справку о закрытии счета
- Через 5 мин. приходит емейл со ссылкой на справку, лежащую на сайте Папка24 (https://papka24.com.ua/ – сервис по электронному документообороту)
- Если Вы еще не зарегистрированы в Папка24, регистрируемся.
- Если у Вас еще нет ЭЦП (электронной подписи от Приват24 для бизнеса), то получаем ее в Приват24 для бизнеса.
- Затем входим на https://papka24.com.ua/ с логином-паролем, выбираем файл сертификата ЭЦП, вводим к нему пароль, и открываем Справку о закрытии счета. 
- Когда Справка у Вас уже открыта, вверху справа нажимаем на значок Скачать, и сохраняем файл себе на комп (в формате PDF).
- Все, PDF-файл справки можно распечатать, отсылать на емейл, предъявлять в налоговую и т.п..

По ходу в Приват24 встретила такую фразу:
*Заверять копии электронных документов мокрой печатью банка не нужно. Все справки, заверенные электронно-цифровой печатью банка, приравниваются к оригиналам документов на бумажном носителе с мокрой печатью и могут быть предоставлены для проверки в контролирующие органы в электронном или распечатанном виде с заверением со стороны предприятия (письмо Государственной фискальной службы Украины от 12.05.2016).

**Comment by julikin** [comment]
Добрый день,
после выбора Донецкая область - при вводе ключа, запрашивается пароль. ввожу пароль и пишет что "Не вдалося знайти відповідний сертифікат", что это значит? авторизуюсь через ЭЦП АЦСК Украина

**Comment by agerman-ua** [comment]
Добрый день, простите за задержку отвечу если ещё актуально. Попробуйте воспользоваться Банкайди. 
Очень похоже на то что ключ именно АЦСК Украина не проходит. Но это странно. Такую проблему давно уже не встречали.
Для чистоты эксперимента есть у Вас платежная карта Привата? Чтобы сгенерить себе бесплатно другой ЭЦП. И использовать его.
