### ISSUE TITLE
Неправильна адреса реєстрації

### ISSUE THREAD

**Issue by mzelinska** [e-government-ua/iForum#736]
Доброго дня!
Хочу подати заявку на заміну водійських прав у звязку зі зміною прізвища. Логінюсь в систему з допомогою Bank ID. В мене відображається неправильна адреса прописки, хоча я звернулась ще минулого тижня в банк, оновила і в них вже правильна інформація відображається ... Супорт в банку сказав звертатись до розробників ресурсу з цим питанням. На скільки критично, щоб інформація в цьому полі була вказана так, як в паспорті зараз є? І якщо критично, то чи можете Ви оновити це поле?
![image](https://cloud.githubusercontent.com/assets/25364926/22329727/501edc18-e3cb-11e6-8175-6c4c1495b292.png)

**Comment by agerman-ua** [comment]
Там тягнеться саме банківська інформація. Змінити з нашого боку немає можливості.
