### ISSUE TITLE
припинення підприємницької діяльності ФОП

### ISSUE THREAD

**Issue by RostJunior** [e-government-ua/iForum#737]
Подав заявку на закриття ФОП 13.01.2017 16:18, завтра буде 14 днів, можна дізнатися на якій стадії заявка і скільки чекати на відповідь, а то їхати ще через всю Україну в податкову і хотілось по скоріше з цим покінчити.  (0-916503181)

**Comment by Nat99999** [comment]
@RostJunior 
В сегодняшних отзывах уже говорят о 26 днях :( - здесь https://igov.org.ua/service/87/feedback
Дніпропетровська сьогодні 15:51 - После подачи заявки и ее обработки прошло 26 дней.

**Comment by RostJunior** [comment]
тогда будем ждать. Только еще вопрос, если в январе подана заявка, то ЕСВ платить только за январь, или за февраль тоже (в случае получения ответа про закрытия в феврале), а то уже 26.01.

**Comment by Nat99999** [comment]
@RostJunior 
По-моему, налоговиков не интересует дата подачи заявки, а только дата закрытия у регистратора.

**Comment by agerman-ua** [comment]
@RostJunior , добрый вечер
@Nat99999 абсолютно прав/права учитывается именно дата закрытия в реестре.
Сегодня будет массовая рассылка, регистраторы задыхаются и не успевают из-за живых очередей и нестабильной работы самого реестра. Т.е. в оставшееся время работают с заявками с портала.
Это касается Днепропетровской области.
По другим областям получше.
С уважением, Август.

**Comment by RostJunior** [comment]
Погано, що не відображається яка там черга заявок, і які перспективи, а то на сайті писали 1-3 дні, потім 13-15 днів. Погано, що не має змоги поїхати самому закрити, а коли була нагода понадіявся, що швидко на сайті igov закриють до кінця місяця, і так вже 18-й день....
