### ISSUE TITLE
BankID - достаточно быть клиентом банка как физлицо?

### ISSUE THREAD

**Issue by af7** [e-government-ua/iForum#738]
BankID - достаточно быть клиентом любого из указанных банков как физлицо или обязательно нужно быть клиентом банка как ФЛП? (речь идет об услуге закрытия ФЛП)
И нужно ли для BankID что-то делать в банке, кроме получения обыкновенного доступа к счету через интернет?

**Comment by zolotovatatyana** [comment]
Не нужно быть AKG? достаточно как физлицо.
