### ISSUE TITLE
де знайти у який термін повинна бути розглянута заявка?

### ISSUE THREAD

**Issue by Artyom-ARS** [e-government-ua/iForum#74]
Де можна знайти у якій термін повинна бути розглянута заявка?
Було б гарно якщо це можно було б побачити не тільки при поданні але і у інформації про послугу.

**Comment by jhonlab** [comment]
Поддерживаю вопрос!

**Comment by GrekD** [comment]
@Artyom-ARS 
@jhonlab 
доброго дня!
Заявка повинна бути розглянута у термін встановлений законодавством - Ви можете глянути ці терміни в інтернеті, по більшості послуг ми повідомляємо також про цей термін у листі
