### ISSUE TITLE
Оформление справки 6-ЗЕМ - не делайте это через сайт iGov

### ISSUE THREAD

**Issue by angi1987** [e-government-ua/iForum#740]
Заявка  0-913139080 от 11.01.17
Через две недели после подачи документов через сайт, не было ни какого ответа.
Пришлось поехать в Держкомзем (там где подгатавливают эту справку) и ЦНАП (там где выдают эту справку на руки)и там и там сказали, что оформить **"Довідку з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6-ЗЕМ)"** через сайт невозможно.  А на сайте такая услуга есть.

**Comment by Akylish88** [comment]
Добрый день, Анна Владимировна? Правобережный ЦНАП?

Кто именно и когда вам такое сказал?
Уточню и отпишусь вам.

**Comment by angi1987** [comment]
Добрый день. Это сказали 27.01.2017  главный юрист Держкомзема (Сичеславская Набережная, 29а) и начальник Правобережного ЦНАПа (к сожалению не знаю фамилий при необходимости могу уточнить).
Начальник Правобережного ЦНАПа подтвердил, что заявку № 0-913139080 они у себя не видят. Поиск по фамилии также ни к чему не привел. Начальник Правобережного ЦНАПа пообещал при встрече с администраторами сайта iGov разобраться в этой проблеме

**Comment by Akylish88** [comment]
Заявку нашли.
Руководство ЦНАПов сказало услугу оказывают и должны обрабатывать.

Я вам завтра послезавтра отпишусь про окончательный результат.

**Comment by angi1987** [comment]
Спасибо. Жду ответа
