### ISSUE TITLE
Регистрация ФОП. Звернення № 0-925262258

### ISSUE THREAD

**Issue by MsMargo** [e-government-ua/iForum#741]
Добрый день!
Обращение оформляла 20.01.2017. Днепропетровская область, г.Камянское.
Подскажите, пожалуйста, как долго ожидать факта регистрации?
И будет ли обработано в налоговой заявление на Единый налог (было прикреплено к заявке)?

**Comment by agerman-ua** [comment]
Добрый день. @MsMargo 
Приблизительно до середины следующей недели должны обработать.
Да. Должно быть принято заявление налоговой из реестра, куда его прикрепит регистратор.
Но необходимо уточнять после регистрации обязательно.
