### ISSUE TITLE
Заявка на загранпаспорт. ч.2

### ISSUE THREAD

**Issue by Solaris81** [e-government-ua/iForum#742]
Добрый день. Требуется помощь знающих людей.
Проблема в том, что не могу создать заявку (замовити послугу) на загранпаспорт. Сначала все вроде нормально, ровно до того момента, когда необходимо выбрать подразделение миграционной службы. Какое бы отделение не выбирал - нет мест в электронной очереди. И так целую неделю пытаюсь, и никак...
Может, есть какое-то объективное объяснение этому факту???
Ах да, город Днепр.

**Comment by julyprodan** [comment]
Добрый день, электронная очередь имеет ограниченное число мест. На текущий момент все места на февраль, которые выделялись под очередь iGov -  уже разобраны.
По подразделениям Шевченковского, Новокодацкого районов и областной ДМС ежедневно добавляется один день. 

Спасибо за понимание.

**Comment by Solaris81** [comment]
Спасибо за Вашу помощь. С утра получилось попасть в очередь.
Еще маленький вопрос: при заполнении формы нигде не спрашивалось про срок изготовления паспорта. Если я правильно понимаю, то срок изготовления я выбираю, когда хочу распечатать квитанцию для оплаты. И в ДМС я иду с оплаченной квитанцией (810 грн при изготовлении за 7 дней) и заявлением на ускоренное оформление. Верно?

**Comment by julyprodan** [comment]
Верно. Вам необходимо оплатить за срочный паспорт и прийти с квитанцией в отделение ДМС
