### ISSUE TITLE
Справка о несудимости

### ISSUE THREAD

**Issue by elenapopova1525** [e-government-ua/iForum#743]
Здравствуйте . Не могу заказать справку о несудимости. Ссылка кот. вы мне давали ранее не дает возможности сейчас заказать.

**Comment by agerman-ua** [comment]
@elenapopova1525 
Добрый вечер,
В данный момент услуга временно закрыта, мы ожидаем раскрытия сразу на всю Украину. Сейчас происходит перераспределение процессов внутри МВД. Выдачу справок передают в другой орган.
С уважением, Август.

**Comment by elenapopova1525** [comment]
спасибо
