### ISSUE TITLE
Державна реєстрація створення фізичної особи – підприємця (Звернення № 0-925262258)

### ISSUE THREAD

**Issue by MsMargo** [e-government-ua/iForum#744]
Добрый день! Подавала заявку на регистрацию ФЛ-П 20 января, она до сих пор в статусе "в обработке". Также писала здесь сообщения и на на igov, но все они без ответа. Хочу уточнить, стоит ли мне ждать завершения регистрации ФЛ-П или я должна обратиться к гос.регистратору? Если же стоит ждать, сориентируйте, пожалуйста, по срокам.

**Comment by agerman-ua** [comment]
@MsMargo 
Сейчас большая общая очередь. 
Обрабатывают в хронологическом порядке. 
Примерно, учитывая темпы обработки и количество заявок, можно обработку Вашей заявки ожидать на следующей неделе. Может и скорее получится, но это не гарантировано.
С уважением, Август.

**Comment by MsMargo** [comment]
Спасибо. Могу ли я расчитывать на то, что она будет 100% обработана? Дата регистрации ФЛ-П будет как дата подачи заявки или дата окончания обработки?

**Comment by agerman-ua** [comment]
@MsMargo 
Дата регистрации будет равна или накануне от даты закрытия заявки на портале.
Обычно совпадает.

**Comment by MsMargo** [comment]
@agerman-ua 
Тогда заявление на переход на Единый налог должно быть с этой датой и от этой даты будут отсчитываться 10 дней для перехода на него?

**Comment by agerman-ua** [comment]
Поскольку это не переход а выбор то дата будет с момента регистрации. И да 10 дней именно от даты регистрации.

**Comment by toxaus** [comment]
@MsMargo в підсумку - за який термін вдалося зареєструватись?

**Comment by MsMargo** [comment]
@toxaus подала заявку 20 января, зарегистрировано 4 февраля, оповещение пришло только 6

**Comment by agerman-ua** [comment]
@MsMargo 
просто 04 работал регистратор в реестре (суббота) а на основании данных от него в понедельник обработали уже заявку на портале. Такое может быть. Тут в принципе сначала реестр а потом только извещение через портал.
