### ISSUE TITLE
Реєстрація нового місця проживання. Пара комментариев в целом по услуге.

### ISSUE THREAD

**Issue by zabulus** [e-government-ua/iForum#745]
1. По UI заявки. Есть поля, в которых нужно указывать достаточно длинные данные. Например, кем выдан паспорт. Есть предложение поля сделать multiline, т.к. не удобно перепроверять введенные данные.
2. По бланкам заявок, пришедших в аттаче. Оказалось, что некоторые документы должны были распечатаны двусторонней печатью. Нам пошли на встречу, скрепили степлером. Это следовало бы указать, и может пдфники соответственно сгруппировать с указанием о двусторонней печати.
3. По списку документов. Общая вещь, которую хотелось бы устранить - это копии документов. Более того, в заявке я аттачил документы для основания заявки (вытяг, например). Дополнительно копии этих документов мне нужно было отксерить на месте. Аналогично с копиями паспортов, их тоже хорошо было бы приатачить к заявке (тут согласен, что опционально, не у всех есть электронная копия документов). И эти приатаченные копии уже использовались без ксерокопирования на месте. 
В идеале я вижу что прихожу только с оригиналами документов:
2 документа для внесения изменений (в нашем случае домовая книга пред. места жительства и паспорт)
и 2 документа обоснования: вытяг, договор купли-продажи и паспорт владельца.
4. Требование квитанции с мокрой печатью. Это вообще очень сильно уменьшает безотрывность от компьютера при подаче заявления. Заплатил через приват24, потом только прочитал о мокрой печати. Пришлось идти в отделение.
И о хорошем. В целом для нас все прошло более чем удачно, поэтому большое спасибо за этот сервис.

**Comment by smoktii-igov** [comment]
п. 1 - Реализовано 
п. 2 - В процессе реализации https://github.com/e-government-ua/i/issues/1501
п. 3 - определяется исполнителями услуги. В тексте писем есть упоминание о необходимости приходить с копиями и оригиналами документовю
п. 4 - есть внешние условия/ограничения
