### ISSUE TITLE
Проблема с закрытием ФОП

### ISSUE THREAD

**Issue by korrch** [e-government-ua/iForum#746]
25 января подал заявку. пришел ответ:
Ваша заявка 0-929424002 прийнята!

26 января пришло письмо:
У зв'язку з великою кількістю поданих звернень по припиненню діяльності ФОП та періодичною непрацездатністтю реєстру мін'юсту, реєстратори можуть не встигнути приняти в роботу Ваше звернення до кінця січня 2017 року та провести реєстраційні дії.

2 февраля пришло такое письмо:
Ваше звернення на тему "Державна реєстрація припинення підприємницької діяльності фізичної особи – підприємця за її рішенням", опрацьовано і по ньому винесено рішення про відмову в державній реєстрації припинення підприємницької діяльності.
Коментар держслужбовця (Причина: відсутні дані ключа електронного цифрового підписсу. Будь ласка, спробуйте подаьт заяву повторно)

подал заявку 3 февраля повторно. пришло письмо:
Ваша заявка 0-942573102 прийнята!

возник вопрос: А что с ключем было не то? на сайт загрузился без проблем.

**Comment by agerman-ua** [comment]
@korrch 
Добрый вечер,
А у Вас ЭЦП чей?

**Comment by korrch** [comment]
ТОВ "Центр сертификации ключей Украина" в офисе А-Банка

**Comment by agerman-ua** [comment]
@korrch 
Ага. Была определённая проблема с этими ключами. Не могли получить всю картину ситуации.
Но одна замечательная девушка ассистировала со своим ЭЦП и разработчик выловил и устранил нестыковки. )

**Comment by korrch** [comment]
То есть теперь проблем не будет?

**Comment by agerman-ua** [comment]
@korrch 
Даже если Вы спрашиваете про ЭЦП, никто не может, в принципе, исключить проблемы. 
Просто если возникнет сложность уверен что она будет устранена. )

**Comment by korrch** [comment]
понятно. спасибо

**Comment by korrch** [comment]
проблемы продолжаются. 
позвонила девушка и сказала что с мой ЭЦП не годится. я не могу понять что там не так. потому как я его открыть не могу... сегодня открыл счет в Банке Пивденный. зашел через BankID но к моему удивлению все равно нужен ЭЦП. а зачем тогда этот BankID ? 
на сайте банка описание работы с вашим сайтом такое:
Работает данная система очень просто: пользователь заходит на сайт iGov.org.ua, нажимает на кнопку «Войти через BankID», выбирает в списке свой банк и дает системе доступ к данным, которые она запрашивает. Это может быть фамилия, имя,  отчество, номер и серия паспорта или другие данные.

загрузил старый файл без конвертации. странно что загрузилось, раньше не получалось.
ЭЦП у меня от Центр сертификации ключей Украина, который есть вашем списке основных АЦСК. 
у меня есть 2 файла с разрешением .PCK и .ZS2 есть еще какие-то 2 сертификата. я загрузил .ZS2
что не так я не понимаю. объясните пожалуйста?

**Comment by agerman-ua** [comment]
Подайте новую заявку и сюда напишите её номер. Сразу проверим ЭЦП.

10.02.2017 1:19 пользователь "korrch" <notifications@github.com> написал:

**Comment by korrch** [comment]
подал. заявка 0-952890436

**Comment by agerman-ua** [comment]
@korrch 
Принял.
