### ISSUE TITLE
Електронний квиток.

### ISSUE THREAD

**Issue by HopOleg** [e-government-ua/iForum#747]
В (Кіровограді) Кропивницькому, де з електронними сервісами зовсім туго, презентували мобільну систему електронних квитків: [http://dostyp.com.ua/novini/yizditi-po-smartfonu-u-kropivnits-komu-priezientuvali-mobil-nu-sistiemu-ieliektronnikh-kvitkiv-foto](url)
Візьміть на озброєння, здається ідея має право на життя, особливо в "студентських" містах.

**Comment by annastolbova** [comment]
дякуємо за Вашу зацікавленність проектом, але на цей момент ми все ж таки більш сконцентровані на запуску адмінпослуг, до речі, розпочали співпрацю з Кропивницьким. маємо надію, що найближчим часом вже запустимо послуги.
