### ISSUE TITLE
Регистрация ФЛП - Отредактировать обращение  № 0-944711922

### ISSUE THREAD

**Issue by aspgraver** [e-government-ua/iForum#748]
Здравствуйте!

При подаче заявки на регистрацию ФЛ-П, в переходе на единый налог приложил первый лист заявления, после подачи обращения, приложил два остальных отсканированных листа (в примечании было написано что так можно). 

Сейчас думаю что, может нужно было приложить это все одним документом, в формате pdf ? А то после прочтения топиков здесь, складывается мнение что, это заявление, да и еще в таком виде как я закинул, может вовсе не рассматриваться.

В комментариях в обращении я прикрепил файл pdf с полным заявлением, если можно то, поставьте этот файл в обращение, а все остальные комментарии удалите.

**Comment by agerman-ua** [comment]
@aspgraver 
Добрый вечер,
Удалять не будем, не получится. Дополнительный файл будет, но не можем гарантировать что чиновник случайно не использует только первый лист. Есть небольшой риск. Чтобы устранить недоразумения можно пойти одним из двух путей. 
1. Спокойно дождаться регистрации, проверить в кабинете налогоплательщика свой статус, и если что-то не так, написать заяву на протяжении 10 дней после регистрации и закрыть этот вопрос.
2. Попросить закрыть указанное обращение, подать в новом заявление сразу одним файлом. Но всё равно бывают "осечки" на стороне налоговой. Проверять всегда нужно систему налогообложения. Ну и если что не так смотрим п.1.
С уважением, Август.

**Comment by aspgraver** [comment]
Что означает данный статус: Заявка вiдкрита i почата ескалація - Очікування в черзі ?

**Comment by agerman-ua** [comment]
@aspgraver 
Значит просто сработал механизм автоматического извещения всех участников по Вашей заявке самим порталом о том что "и чего ждём?!".
Но причину задержки мы знаем - большая очередь. Просто ждём обработки.

**Comment by aspgraver** [comment]
В общем сегодня проверил на сайте министерства юстиции, наконец-то меня зарегистрировали)

Теперь вопрос следующий, в электронном кабинете плательщика данных о том, что я на едином налоге - нет. 

Как лучше сейчас поступить, дождаться пока на igov закроют мое обращение (выполнено или что там за статусы бывают при закрытии) и проверить снова или же сразу подавать заявление на единый налог ?

**Comment by agerman-ua** [comment]
@aspgraver 
Если лучше - значит безопасней, то да, можно не дожидаться письма с портала. 
Наличие регистрации и факта там взятия на налоговый учёт - достаточное основание для подачи заявления на единый налог.
Там будет только констатация факта регистрации и уникальный код по которому можно увидеть выписку. Выписка иногда доступна только по истечении нескольких дней.
С уважением, Август.
