### ISSUE TITLE
Довідка про несудимість

### ISSUE THREAD

**Issue by johneleks** [e-government-ua/iForum#75]
Чи є можливість отримати довідку про несудимість?

**Comment by GrekD** [comment]
@johneleks 
да
https://igov.org.ua/service/1/general

**Comment by johneleks** [comment]
"Місто: 
Львів
 
На жаль, поки що у Вашому регіоні неможливе надання цієї послуги в електронному вигляді.Ви можете допомогти пришвидшити процес переведeння послуги в електронний вигляд:"

Але дякую
