### ISSUE TITLE
Юридична підстава для роботи i-gov

### ISSUE THREAD

**Issue by DevvisioN** [e-government-ua/iForum#750]
Привіт, народ!
У першу чергу хочу подякувати Вам за вашу працю, створити і підтримувати такий потужний сервіс - це вже досягнення. Але є проблема - після подачі заявки (прізвища я опущу - не хочу псувати людям життя через їх можливе незнання) майбутнього підприємця П. попросили підійти в ЦНАП. Після чого один із співробітників ЦНАП'у заявив, що нема жодної юридичної підстави для обробки інформації із сервісу(Igov). Питання - це правда? 
Якщо ні - будь-ласка, скиньте посилання на рішення/закон/підставу/чи-як-воно-там-називається
що дозволяє використовувати дані для надання послуг, а ще краще - в топ на офіційний портал, щоб було як доказати свою правоту у суперечці із ЦНАП'ом. Дякую.

**Comment by agerman-ua** [comment]
@DevvisioN 
Доброго дня. тут має значення співробітник якого саме ЦНАПу таке каже. 
Завжди є місцевий орган якому підпорядковується будь-який ЦНАП. 
Якщо цим керівним органом прийнято рішення про співпрацю з порталом то ЦНАП повинен виконувати таке рішення. 
Давайте не будемо спускатися на рівень тих людей котрі просто не бажають працювати.
З повагою, Август.

**Comment by DevvisioN** [comment]
Доброго дня, пане Серпень)
Ви маєте на увазі, що, у випадку, якщо місцевий орган влади (виконавчий?) прийняв рішення про співпрацю, то ЦНАП повинен працювати з i-gov? А чи має він (орган) законну підставу для прийняття такого рішення? Якщо так, то киньте, будь-ласка посилання на даний закон. А рішення місцевої влади я вже сам якось пошукаю.
З повагою,
Андрій.

**Comment by agerman-ua** [comment]
@DevvisioN 
Так, пан Ендрю), саме це я й мав на увазі.
http://zakon5.rada.gov.ua/laws/show/5203-17/paran83#n83
ст.9 п.4
"... в разі надання адміністративних послуг в електронній формі - через Єдиний державний портал адміністративних послуг, у тому числі через інтегровані з ним інформаційні системи державних органів та органів місцевого самоврядування."
Як і раніше, з повагою, Август. )

**Comment by DevvisioN** [comment]
Дуже сильно Вам вдячний! Будемо "виховувати" ЦНАП.
З повагою, вдячністю, надією та краплинкою гумору,
Ендрю)
