### ISSUE TITLE
змінити мій паперовий паспорт на людський ІД 

### ISSUE THREAD

**Issue by AntonOnapchenko** [e-government-ua/iForum#751]
Я просто хочу змінити мій паперовий паспорт на людський ІД але я не працюю з Українськими банками а через Фейсбук коли підтверджую свої дані нічого не відбувається допоможіть мені будь ласка !!!

**Comment by Koffeek** [comment]
@AntonOnapchenko Просто змінити не вийде. Паспорт нового зразка видається лише при зміні ПІБ, втраті, викраденні чи пошкодженні паспорта громадянина України. Або за бажанням замість вклеювання фотокарток у 25 чи 45 років. Авторизуватись на порталі також можна за допомогою електронно-цифрового підпису (https://docs.google.com/document/d/1Bai40Xw-XUcJfYR96CQD7-gSjsCtAlC3DMqbbcI-fxw/edit). Також Ви можете особисто звернутись до підрозділу ДМС за місцем реєстрації та подати відповідну заяву у живий черзі
