### ISSUE TITLE
Заявка на получение загран паспорта

### ISSUE THREAD

**Issue by TarasR** [e-government-ua/iForum#752]
После указания услуги "Паспорт громадянина для виїзду за кордон" переходим к заполнению полей при авторизации через карту "Ощадбанка" после ввода цифр с СМС сообщения получаю следующие картинки
![igov](https://cloud.githubusercontent.com/assets/25842267/23061717/9ef23924-f50b-11e6-8c26-9d05e9ca5059.png)
![igov 2](https://cloud.githubusercontent.com/assets/25842267/23061723/a376bf88-f50b-11e6-8fe9-9f401ad3831c.png)
![igov 3](https://cloud.githubusercontent.com/assets/25842267/23061725/a635d9ac-f50b-11e6-96ba-6864181d6d21.png)

помогите разобраться в чем причина!!!!

**Comment by annastolbova** [comment]
зараз авторизація через ощад вже працює коректно
