### ISSUE TITLE
Призначення субсидії - Звернення № 0-834709787

### ISSUE THREAD

**Issue by SergeyZCH** [e-government-ua/iForum#754]
Заявка висит с 25.11.16 до сих пор нет ответа. В чем может быть проблема?
Заранее благодарен за ответ

**Comment by annastolbova** [comment]
ми бачимо , що заявка в роботі, але Ви завжди можете зв'язатися зі своїм УПСЗН за контактами (нижче посилання) та дізнатися про нарахування , розгляд зараз триває зазвичай більше 60 днів.

http://www.adm.dp.gov.ua/OBLADM/obldp.nsf/index/921F8CA52B81B331C2257E9E0037DBDA/$File/%D0%B3%D0%B0%D1%80%D1%8F%D1%87%D0%B8%20%D0%BB%D0%B8%D0%BD%D0%B8%D0%B8%20%D1%81%D1%83%D0%B1%D1%81%D0%B8%D0%B4%D0%B8%D0%B8.pdf
