### ISSUE TITLE
Закрытие ФОП № 0-939495908 (вынесено позитивное решение - в реестре ФОП не закрыт)

### ISSUE THREAD

**Issue by KaterinaKL** [e-government-ua/iForum#755]
Добрый день, у меня возникла проблема с закрытием ФОП.
после подачи заявления на сайте (0-939495908), получила 03.02.2017 положительный ответ (Ваше звернення на тему "Державна реєстрація припинення підприємницької діяльності фізичної особи – підприємця за її рішенням", опрацьовано і по ньому винесено позитивне рішення ). 
Я отправила все необходимые документы в налоговую, и там мне ответили, что у них нет оснований для дальнейших процедур по закрытию ФОП, т.к. в реестре ФОП не находится в стадии прекращения деятельности.
Если мне пришел ответ, что заявка обработана и вынесено позитивное решение, почему в реестре не изменился статус ФОП?

**Comment by agerman-ua** [comment]
Добрый вечер. @KaterinaKL 
Действительно на первый взгляд странная ситуация. 
Однако это редкий, но классический, случай ошибки оператора.
На самом деле Вам было отказано, и даже была введена причина отказа. Но из-за того что при закрытии обращения служащим был выбран неправильный вариант результата, для Вас было сформировано письмо без использования этой информации.
Привожу текст с причиной отказа.
"Причина:Вибачте, фізична особа-підприємиць зареєстрована в іншій області, ми не можемо провести державну реєстрацію припинення за межами Донецької області; пропонуємо звернутись до будь-якого відділу реєстрації у Вашій області".
С уважением, Август.

**Comment by KaterinaKL** [comment]
Спасибо за ответ.
А планируется подключение услуги для Луганской области?

**Comment by agerman-ua** [comment]
Добрый вечер.
В ближайшее время - нет. (
Однако есть отдельная процедура для ВПЛ, которая позволяет при персональном визите к любому регистратору получить регистрационные услуги. Но это, к сожалению, только лично.
С уважением, Август.
