### ISSUE TITLE
Не отримала повідомлення про припинення дії ФОП

### ISSUE THREAD

**Issue by smetanajula** [e-government-ua/iForum#756]
Добрий день. 21.02.2017 на сайті іGov я подала заявку про припиненні дії ФОП, про що отримала підтвердження на електронну пошту (Ваше звернення 0-969605221 успішно зареєстровано).  22.02.2017 я перевірила стан на сайті Мін. Юсту (usr.minjust.gov.ua) де в запиті по моєму ФОП побачила інформацію що дія припинена. На мою електронну адресу не прийшло повідомлення про підтвердження припинення дії, не файла, ні посилання за яким можна його завантажити. Як мені отримати Повідомлення про припинення щоб надати його до податкової?

**Comment by agerman-ua** [comment]
Доброго дня. @smetanajula 
Таке може трапитись у випадку, коли реєстратор виконав реєстраційні дії але ще не передав Вашу справу назад до адміністратора. Після отримання адміністратором справи Ваше звернення буде опрацьовано на порталі. Повідомлення після цього має суто інформативний характер. Те що ви побачили в реєстрі і є кінцевий результат наданої послуги, Повідомлення роздруковувати Вам не потрібно, оскільки податкова дивиться саме в реєстр і їм не потрібні інші документи.
З повагою, Август.

**Comment by smetanajula** [comment]
Дякую за оперативну відповідь.

**Comment by smetanajula** [comment]
Дякую за оперативну відповідь!

2017-02-23 2:08 GMT-08:00 agerman-ua <notifications@github.com>:
