### ISSUE TITLE
Заявка по субсидии 7529127

### ISSUE THREAD

**Issue by Yonka2502** [e-government-ua/iForum#76]
Зравствуйте, заявка отправлена 9.10. Прошло 20 рабочих дней, ответа нет. Проверьте, пожалуйста, может есть информация какая-нибудь.

**Comment by Yonka2502** [comment]
Днепропетровск, Анд район. 15.10.15 взята в роботу. Где можно узнать результат?

**Comment by dmitrijzabrudskij** [comment]
попробуйте позвонить им напрямую: (056) 375-90-64, (056) 376-52-03

должна быть в работе

**Comment by Yonka2502** [comment]
По телефону(056) 375-90-64 отвечают только по детским выплатам, второй телефон - не берут трубку. Каждый день звоню десяток раз. Может еще другой номер телефона есть?

**Comment by dmitrijzabrudskij** [comment]
(067)8949392 нашел такой мобильный
