### ISSUE TITLE
0-964747551 Чи буде надано довідку в електронному вигляді?

### ISSUE THREAD

**Issue by dotsentkh** [e-government-ua/iForum#760]
Я створив запит на одержання довідки про доходи для заповнення декларації держ службовця. Але через тиждень прийщла відповідь, що через 5 днів довідку можна буде одержати з паспортом у відділенні ДФС. Заявці встановлено статус "Закрита". Тепер виникає питання чи буде надана довідка в електронному вигляді? Мені той папірець не потрібен, я хотів пошвидше замовити довідку та на її основі заповнити декларацію. Телефони ДФС вказані у відповіді не відповідають.

**Comment by annastolbova** [comment]
ця довідка надається тільки у паперовому вигляді,
якщо потрібна просто інформація про доходи, можна скористатися послугою https://igov.org.ua/service/1561/general  - це інформаційний запит
