### ISSUE TITLE
ДМС - Звернення № 0-970565588 —  "Скасувати заявку"

### ISSUE THREAD

**Issue by V-Tarasov** [e-government-ua/iForum#761]
Скасував заявку  0-970565588 через форму у email "Ви можете скасувати свою заявку, вказавши причину [field] [button] "Скасувати заявку"
Але у "Мій журнал > Звернення № 0-970565588" вона досі має статус "В обробці"

**Comment by annastolbova** [comment]
заявка закрита та була успішно скасовна
