### ISSUE TITLE
Звернення №0-976822924. Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця). 

### ISSUE THREAD

**Issue by AnastasiaYu** [e-government-ua/iForum#762]
Добрый день. На завтра(03.03) назначено время, но не пришли реквизиты и суммы оплаты административного сбора, а также никакой инструкции. Сообщите, пожалуйста, какие дальнейшие действия? Примут ли меня завтра?

**Comment by smoktii-igov** [comment]
Должны сегодня обработать. Если что реквизиты на сумму 13,60
Одержувач: УДКСУ у Індустріальному районі м. Дніпро, Банк ГУ ДКСУ у Дніпропетровській обл., МФО 805012, Код ЄДРПОУ 37989295, Р/р 33212879700006, код платежу 22012500
