### ISSUE TITLE
Реестрація ФОП - Звернення № 0-984090527

### ISSUE THREAD

**Issue by toxaus** [e-government-ua/iForum#763]
Якщо є можливість, уточніть, будь ласка, яка зараз ситуація з чергою? +- коли можна очікувати на реєстрацію?

При реєстрації вклав .pdf файл з фото заяви на ЄП, в якій вказав дату створення звернення (лише в пункті 5.1, дату взяття на облік звісно не проставляв). Тепер, через затримку в обробці звернення, підозрюю можуть виникнути проблеми з обробкою моєї заяви на ЄП. 
**1. Уточніть, "вірний" алгоритм вказування дати по цій заяві - залишати поле з датою (пункт 5.1) порожнім ? Чи вказувати там дату з запасом в кілька днів?
2. Чи варто, для підстраховки, зараз додати до звернення ще одну заяву із іншими датами?** 

Буду вдячним за допомогу та поради.

**Comment by agerman-ua** [comment]
Доброго дня, @toxaus 
Зараз реально очікувати опрацювання до середини наступного тижня. Тобто у вівторок - реально.
1. Залишайте порожнім
2. Ні, не варто.
Варто обов'язково перевірити реєстрацію по спрощеній системі одразу після реєстрації.
З повагою Август.

**Comment by toxaus** [comment]
Ок, дякую.  Якщо не варто перезавантажувати, то сподіваюсь пройде мій перший варіант із вказаною датою (пункт 5.1). 
Чекатимемо.

**Comment by toxaus** [comment]
Бідь ласка, прошу скасувати моє звернення - № 0-984090527 ! 
Реєстрація оффлайн

**Comment by agerman-ua** [comment]
Щиро дякую за попередження. Звернення скасовано.
