### ISSUE TITLE
Услуга "внесення змін до реестраційних данних СПД" в Киеве недоступна. 

### ISSUE THREAD

**Issue by emakarenko** [e-government-ua/iForum#764]
Я 2 месяца назад регистрировала изменения к своему СПД, все работало отлично. Почему сейчас не работает?

**Comment by agerman-ua** [comment]
Добрый день,
Регистраторы не могут выполнять действия за пределами своей области.
Сейчас подключено несколько областей. 
Киева и Киевской области, к сожалению, среди них нет.
Как только появятся регистраторы в указанных регионах, готовые обрабатывать заявки полученные через наш портал - мы очень оперативно откроем данную услугу.
С уважением, Август.

**Comment by emakarenko** [comment]
Но раньше я несколько раз пользовалась данной услугой.

Как долго нужно ждать появления регистраторов?


09.03.2017 17:14, agerman-ua пишет:

**Comment by agerman-ua** [comment]
Очень приятно убедиться что мы не напрасно "лупаем цю скелю". 
Сроки подключения по Киеву и Киевской области, к сожалению, не поддаются пока прогнозированию.
С уважением, Август.
