### ISSUE TITLE
заявка №0-985528323 на регистрацию юр. лица 

### ISSUE THREAD

**Issue by Enyki** [e-government-ua/iForum#765]
Добрий день, по заявке №0-985528323 с 2.03 нет регистрации. Почему? 
Спасибо.

**Comment by agerman-ua** [comment]
Добрый день.
Простите, пока не готов ответить. Завтра с утра будет более полная информация.

**Comment by Enyki** [comment]
Добрий день, что-то удалось узнать.

**Comment by agerman-ua** [comment]
Должны взять в работу и обработать сегодня-завтра. После того как будет в работе - могут появиться вопросы. Поглядывайте в почту.

**Comment by Enyki** [comment]
Добрий день, еще нет регистрации. Стоит ждать? или уже не будет? 
Спасибо.

**Comment by agerman-ua** [comment]
Добрый день. Конечно стоит. И будет обработано.
Простите за неудобства.
