### ISSUE TITLE
Помилка в повідмленні про результат операції

### ISSUE THREAD

**Issue by chmelvv** [e-government-ua/iForum#766]
Після введення емейлу в формі "Залиште свій емейл" і натисканні "Зберегти" видає дане повідомлення з відсутнім номером в фігурних дужках.

"Інформація по операції: 'Відсилка запиту на додання нової послуги'
Відправлено на сервер під номером: {}
Дякуємо! Ви будете проінформовані, коли ця послуга буде доступна через Інтернет."

 https://goo.gl/photos/t1YGdfbKDQonDmYdA

**Comment by annastolbova** [comment]
передали в роботу спеціалістам, дякуємо за повідомлення.
