### ISSUE TITLE
Регистрация ФОП по доверенности

### ISSUE THREAD

**Issue by KatanovaLesya** [e-government-ua/iForum#767]
Как можно зарегистрировать ФОП по доверенности в этом сервисе? Такие данные некуда внести. Если осуществляешь вход под своим именем, то можешь оставить заявку на регистрацию только от себя. Если я просто не нашла как, подскажите пожалуйста.

**Comment by agerman-ua** [comment]
Добрый день,
Вы не ошиблись, по доверенности, на портале iGov.org.ua нельзя заказать услуги связанные с единым государственным реестром.
У меня только вопрос в связи с этим. 
А что мешает любому человеку получить ЭЦП самостоятельно или с чьей-то помощью?
По ссылке перечень организаций АЦСК которые могут выдавать ключи.
http://czo.gov.ua/ca-registry
С уважением, Август.

**Comment by KatanovaLesya** [comment]
Добрый день!
Спасибо за ответ. Думаю, ничего не мешает получить ключи, но люди разные
бывают.

С уважением,
Катанова Леся


28 марта 2017 г., 11:49 пользователь agerman-ua <notifications@github.com>
написал:
