### ISSUE TITLE
Помилка встановлення криптоплагіна

### ISSUE THREAD

**Issue by trueromio** [e-government-ua/iForum#768]
Встановив плагін, в доатках показує що плагін встановлено, але все одно видає повідомлення з проханням встановити плагін. 
![screenshot_20170328_162432](https://cloud.githubusercontent.com/assets/1929092/24410488/77e74c2a-13d3-11e7-8957-e6a94a9980e1.png)
![screenshot_20170328_162622](https://cloud.githubusercontent.com/assets/1929092/24410487/77dc0e46-13d3-11e7-9595-18f18d3e8c24.png)
Як переконати сайт що плагін встановлено?

**Comment by agerman-ua** [comment]
Доброе утро.
Есть проблемы у криптоплагина с поддержкой последних Фаерфоксов.
Нужно или откатить назад браузер (а стоит ли?) или установить Хром и уже в него ставить.
С уважением, Август.
