### ISSUE TITLE
0-869665698 Заявка на оформление субсидии

### ISSUE THREAD

**Issue by OBezdietko** [e-government-ua/iForum#769]
Доброго времени суток, заявка на оформление субсидии была открыта 16.12.2016 . 8 февраля по телефону запросили дополнительные документы и в течении недели их предоставили. Уже закончилась зима, а информации по статусу обращения никакой нет. На вопросы в чате iGov никто не отвечает.

**Comment by annastolbova** [comment]
ми бачимо , що заявка в роботі, але Ви завжди можете зв'язатися зі своїм УПСЗН за контактами (нижче посилання) та дізнатися про нарахування , розгляд зараз триває зазвичай більше 30 -60 днів.

http://www.adm.dp.gov.ua/OBLADM/obldp.nsf/index/921F8CA52B81B331C2257E9E0037DBDA/$File/%D0%B3%D0%B0%D1%80%D1%8F%D1%87%D0%B8%20%D0%BB%D0%B8%D0%BD%D0%B8%D0%B8%20%D1%81%D1%83%D0%B1%D1%81%D0%B8%D0%B4%D0%B8%D0%B8.pdf

**Comment by OBezdietko** [comment]
Из двух телефонов "Управління праці та соціального захисту населення Шевченківської (Бабушкінської) районної ради у місті Дніпрі" по указанной ссылке один не отвечает, а на втором заблокированы входящие вызовы. На сообщения так же никто не отвечает. И как мне узнать что с заявкой? Тратить несколько часов на поездку туда и выяснять самостоятельно? В чем тогда помощь iGov?
