### ISSUE TITLE
Нет ответа на запрос субсидии 

### ISSUE THREAD

**Issue by IgorChuvpilo** [e-government-ua/iForum#77]
Здравствуйте! Подал заявку на субсидию г.Днепропетроск Бабушкинский р-н 9.10.2015. 
Пришёл ответ о принятии. №7593477.
Проверка статуса заявки получал ответ:
13.10.2015 заявка принята в роботу.
Проверка статуса заявки 9.11.2015 дала ответ:
6.11.2015 заявка принята в роботу.
Поменялась дата принятия в работу на 6.11.2015.
Хотелось бы знать почему? Ответа не было, хотя сегодня 20 рабочих дней от 15 октября.

**Comment by IgorChuvpilo** [comment]
Проверка статуса заявки 12.11.2015 дала ответ:
11.11.2015 заявка принята в роботу.
Почему дата принятия в работу отодвигается с каждым днём?

**Comment by dmitrijzabrudskij** [comment]
она в работе, ожидает решения по субсидии
причина такой истории обработки - в неправильной обработке самим районом. убеждаем, разъясняем каждый день как правильно делать - но не все это понимают даже с 5-го раза...

последняя инструкция была дана 11.11.2015 - вот поэтому и было изменение статуса. прошу дождаться ответа

**Comment by IgorChuvpilo** [comment]
Спасибо большое за ответ!
Всё ясно и понятно!!!
Буду ждать.
С уважением, Игорь.

12.11.2015 11:37, dmitrijzabrudskij <notifications@github.com>
>она в работе, ожидает решения по субсидии
> причина такой истории обработки - в неправильной обработке самим районом. убеждаем, разъясняем каждый день как правильно делать - но не все это понимают даже с 5-го раза...
> 
> последняя инструкция была дана 11.11.2015 - вот поэтому и было изменение статуса. прошу дождаться ответа
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/e-government-ua/iForum/issues/77#issuecomment-156048834


-- реклама -----------------------------------------------------------
Купуй дешевше на Aukro.ua! Розпродаж!
http://h.holder.com.ua/c?tz&z1585&b107358&s03908&r[rndID]&u
