### ISSUE TITLE
Створення юрособи - Заявка 0-1045648199

### ISSUE THREAD

**Issue by alash1** [e-government-ua/iForum#770]
добрый. с момента подачи заявки прошел 1 месяц. обратной связи нету. один раз ответили через аккаунт на фейсбуке. заранее спасибо за ответ.

**Comment by agerman-ua** [comment]
Добрый день,
С Вами обязательно должны были связаться или по телефону или через портал.
В понедельник, сразу с утра, уточним и текущий статус и причину такой задержки.
Вы же уверены что указали контактный номер телефона корректно?

**Comment by alash1** [comment]
спасибо за ответ. телефоны: 066-710 67 84, 096-397 31 70.  alash@ukr.net почта.

**Comment by agerman-ua** [comment]
Принято.

**Comment by alash1** [comment]
добрый. ничего не происходит. никто не звонил и не писал.

**Comment by agerman-ua** [comment]
Добрый. Уточнил. Подождите ещё немного. Сегодня точно обработают. 
Буду очень благодарен, если по факту обработки сразу напишете об этом, чтобы мне оперативно быть в курсе.
С уважением, Август.

**Comment by Husak93** [comment]
таже проблема, заявка обрабатывается с 28.03

**Comment by agerman-ua** [comment]
@Husak93 
Прошу сообщить номер Вашей заявки и услугу. Только в другом ишью, пожалуйста.
Чтобы не смешивать несколько случаев.
Благодарю за понимание.
С уважением, Август.

**Comment by alash1** [comment]
на 22.00 03/04/17 ничего не изменилось.

**Comment by alash1** [comment]
04.04 ничего.

**Comment by agerman-ua** [comment]
Вижу. ( Повторно связался. Обещали отработать сегодня.

**Comment by alash1** [comment]
отказано в регистрации.
там надо еще и статут приложить?
я думал, что при выборе модельного статута этого не нужно делать.
посоветуйте, пожалуйста, что мне лучше дальше делать.
заранее спасибо.

Ваше звернення №0-981580250 на тему "Державна реєстрація створення юридичної особи", опрацьовано і по ньому винесено рішення про відмову в реєстрації.

Коментар держслужбовця (Причина:Відповідно ст. 56. п.5 Господарського кодексу України, якщо суб'єкт господарювання створюється та діє на підставі модельного статуту в рішенні про його створення, яке підписується усіма засновниками, зазначаються відомості про його найменування, мету і предмет господарської діяльності, а також інформація про провадження діяльності на основі модельного статуту.)

**Comment by alash1** [comment]
или же переделать решение о создании юрлица и создать заявку заново?
или прикрепить к существующей заявке, если это возможно?

**Comment by agerman-ua** [comment]
@alash1 
Не понял. Из отказа видно что нет корректного решения о создании юрлица. А не что нужно прикрепить модельный устав.
1. Устав прикладывать не нужно если модельный.
2. Согласно замечания нужно подправить решение о создании.
3. Прикрепить к исходной заявке новое решение не получится. Если был отказ - заявка закрыта.
С уважением, Август.
P.S.Напомните это у Вас сроки до 10 числа?

**Comment by alash1** [comment]
![default](https://cloud.githubusercontent.com/assets/26826648/24654702/88c9e23a-1943-11e7-89ee-a0b730e68944.jpg)
вот решение о создании, которое я подавал. там есть пункт о деятельности на основе модельного устава.

**Comment by alash1** [comment]
спасибо за ответ. до 10 числа нужно подавать заявку 1пдв.

**Comment by alash1** [comment]
добавить в решение пункт о цели деятельности и подать новую заявку?
заранее спасибо.

**Comment by agerman-ua** [comment]
по документу
не "ідентифікаційний №" а "Реєстраційний номер облікової картки платника податків"
п.3 не "фонд" а "капітал"
добавить информацию про цели и предмет деятельности предприятия
Есть очень высокая вероятность с таким наименованием получить дубль и только из-за этого отказ.
Подать новую заявку - да.
Сюда прислать номер новой заявки

**Comment by alash1** [comment]
новая заявка звернення 0-1045648199

**Comment by alash1** [comment]
на 12.00 изменений в статусе нет.

**Comment by agerman-ua** [comment]
Напоминал с утра. Обещали сегодня.

**Comment by alash1** [comment]
дякую. извините за беспокойство.

**Comment by alash1** [comment]
Ничего.

**Comment by agerman-ua** [comment]
((( Будут сегодня Вам звонить. Прошу держать телефон в поле зрения или слышимости.
В решении я же писал что нужно заменить в тексте "фонд" на "капитал"!?
Попросил чтобы напрямую связались. 
Время бежит. Искренне не хочу играть в "испорченный телефон".

**Comment by alash1** [comment]
спасибо. все исправил. буду ждать.

**Comment by alash1** [comment]
Звонили. Сказали внести корректировки в заявку. Как лучше- попытаться внести изменения в сущеСтвующую заявку или создать новую? Заранее спасибо.

**Comment by agerman-ua** [comment]
Тоже говорил. Думаю стоит попробовать зарегистрировать. Возможно регистратор откажет из-за явно не оригинального названия. Тогда и будем говорить о новой заявке.

**Comment by alash1** [comment]
добрый вечер. не могу на сайте найти возможность редактирования уже поданной заявки. если Вы не возражаете, создам еще одну заявку с учетом всех замечаний и другим названием предприятия. с ув. Алаш.

**Comment by alash1** [comment]
добрый. не смог отредактировать уже поданную заявку № 0-1045648199, поэтому создал новую  0-1049920007.
изменил название предприятия. вроде совпадений не нашел.
заявку составлял с учетом замечаний и рекомендаций.
большое Вам спасибо за помощь и консультации.
заранее спасибо.
с ув. Алаш.

**Comment by agerman-ua** [comment]
Новая заявка пригодится только если откажут по первой по причине не уникального наименования. Посмотрим как будут сегодня развиваться события.

**Comment by alash1** [comment]
добрый.
заявку можно закрыть.подал документы в правобережный цнап г. днепр.
сказали ответ будет в четверг.
спасибо Вам за помощь и консультации.
не знаю Вашей роли в проекте, но возможно это кому нибудь поможет.
было бы намного проще, если бы было какое нибудь стандартное решение основателя или образец протокола загальных сборов. основные претензии регистраторов по ним.
если не возражаете, прикреплю те, которые я подавал.
еще раз спасибо за помощь и консультации.
с ув. Алаш.

**Comment by agerman-ua** [comment]
Доброй ночи, Алаш.
Спасибо за позитив и желание улучшить услугу для других.
Подумаем как именно применить Ваши советы.
Искренне желаю Вам удачи.
С уважением, Август.

**Comment by alash1** [comment]
добрый. зарегистрировали. завтра заберу выписку.
еще раз спасибо.

**Comment by agerman-ua** [comment]
Добрый день.
Спасибо за обратную связь.
Искренне желаю успехов.
Август.
