### ISSUE TITLE
Державна реєстрація створення ФОП (№ 0-1018463009) нет ответа по заявке с 28.03.17

### ISSUE THREAD

**Issue by Husak93** [e-government-ua/iForum#771]
Звернення № 0-1018463009
Услуга: Державна реєстрація створення фізичної особи – підприємця

**Comment by agerman-ua** [comment]
Принял.

**Comment by agerman-ua** [comment]
Поздравляю. Вас уже зарегистрировали. Просто будет подтверждающее письмо об этом.
Если Вы планировали упрощенную систему налогообложения - прошу обязательно проверить регистрацию в налоговой. Или непосредственно или через кабинет налогоплательщика на сайте налоговой. Бывают проблемы. Регистратор не отвечает за эту часть. А мы не можем повлиять на налоговую.
С уважением, Август.

**Comment by Husak93** [comment]
дату регистрации можете сказать?

**Comment by agerman-ua** [comment]
Да. Конечно. Сегодня. 2017.04.03
В письме будет ссылка на бесплатный запрос на портале минюста
Собственно вот она
https://usr.minjust.gov.ua/ua/freesearch
Вводите свой инн, подтверждаете что не робот и получаете информацию по себе из реестра.

**Comment by Husak93** [comment]
спасибо!
