### ISSUE TITLE
Регистрация ФЛП (0-1018463009) нет выписки!

### ISSUE THREAD

**Issue by Husak93** [e-government-ua/iForum#772]
При открытии на мин.юс. Результат надання адміністративних послуг нет выписки, хотя у накомых у всех была.

**Comment by agerman-ua** [comment]
Без номера заявки ответить Вам проблематично.
Не сразу появляется. Иногда несколько дней проходит.

**Comment by Husak93** [comment]
0-1018463009

**Comment by agerman-ua** [comment]
Добрый день.
Можно проверять.

**Comment by Husak93** [comment]
есть, спасибо

**Comment by agerman-ua** [comment]
Отлично. Удачи.  )
