### ISSUE TITLE
Ошибка загран для ребенка

### ISSUE THREAD

**Issue by TRAViS-UA** [e-government-ua/iForum#773]
Залогинен на сайте. Используется сертификат от приватбанка. ПРи попытке зайти в раздел загранпаспорт для ребенка, выдает такое.
![image](https://cloud.githubusercontent.com/assets/10690376/24832441/2da5ee98-1cb9-11e7-8d9a-130531e8397d.png)

**Comment by annastolbova** [comment]
дякуємо за повідомлення, ситуація вже виправлена
