### ISSUE TITLE
Призначення субсидії № 0-869665698 - заявка закрита але на пошту прийшов пустий лист з результатом

### ISSUE THREAD

**Issue by OBezdietko** [e-government-ua/iForum#774]
Після закриття звернення 0-869665698 на електропошту дружини прийшов лист без прікріпленого документа з результатом опрацювання. 
Звернення до спеціалістів iGov через Гугл формс з приводу цїєї проблеми, як зазначено  в листі, не дало ніякого результату. Нема ніякого фідбеку, я навіть не розумію чи потрапило те звернення до когось з підтримки.
Тому прошу тут про допомогу та роз'яснення яким чином мені дізнатися результат опрацювання даного звернення.

**Comment by OBezdietko** [comment]
Який результат обробки запиту?

**Comment by annastolbova** [comment]
результат повторно відправлений на пошту Ozhenko.a@gmail.com
