### ISSUE TITLE
Почему нет графы "Вибір сектора перетину" при оформлении пропуска?

### ISSUE THREAD

**Issue by katrica** [e-government-ua/iForum#775]
Почему нет графы "Вибір сектора перетину" при оформлении пропуска?

**Comment by smoktii-igov** [comment]
Если речь об услуге "Оформлення/переоформлення електронної перепустки до зони АТО для перетину лінії зіткнення", то оформлением и реализацией этой услуги занимается СБУ на сайте https://urp.ssu.gov.ua/

**Comment by smoktii-igov** [comment]
Оформлення перепустки дозволяє перетинати лінію зіткнення через любий сектор
