### ISSUE TITLE
Выписка регистрации ФЛП пришла без ИНН

### ISSUE THREAD

**Issue by Xen4n** [e-government-ua/iForum#776]
Выполнил запрос на получение выписки и скачал её по ссылке https://usr.minjust.gov.ua/ua/extractsearch . В выписке не указан мой ИНН.

**Comment by agerman-ua** [comment]
Добрый день.
Укажите, какой у Вас номер заявки на портале iGov.org.ua ?
Имею в виду номер заявки на регистрацию ФЛП.
С уважением, Август.

**Comment by Xen4n** [comment]
Номер заявки: 0-1005012288

**Comment by agerman-ua** [comment]
Добрый день,
Вам был отправлен на почту "уникальный код" и инструкции по его использованию.
По данному коду доступна ссылка на архив "Свідоцтво про державну реєстрацію СПД / Виписка".
Там есть Ваш ИНН.

**Comment by Xen4n** [comment]
Спасибо за ответ.
