### ISSUE TITLE
Обмен паспорта гражданина украины всвязи с непридатностью.

### ISSUE THREAD

**Issue by IgorLemon** [e-government-ua/iForum#777]
Не возможно занять очередь, ни в отделении, ни в онлайн очереди - она просто не работает!
При чем, нет очереди во всех отделениях разом, беспредел.
Стоял 2 часа в оболонском - кончились билеты, это вообще как понимать.. совдепия какая-то

**Comment by annastolbova** [comment]
по Київській, Львівській, Харківській, Хмельницькій та Одеській областях - черга повністю електронна і щоденно додається 1 день (+15 днів), якщо вільної дати та часу немає, то можна спробувати подати заявку після 00:00, коли оновлюється інформація на наступну дату.
