### ISSUE TITLE
Ошибка при подписании заявки ЕЦП

### ISSUE THREAD

**Issue by bublicus** [e-government-ua/iForum#778]
При созждании заявки "Внесення змін до реєстраційних даних фізичної особи-підприємця" (https://igov.org.ua/service/1497/general) и попытке подписи ее с помощи ЕЦП появляется ошибка "Unable%20to%20sign%20a%20file.%20bankid.privatbank.ua%20return%20an%20empty%20response"

**Comment by annastolbova** [comment]
Будь ласка, спробуйте ще очистити кеш та кукіз в браузері та спробуйте зайти ще раз і подати звернення.
Якщо буде помилка, то зробіть скрін помилки, будь ласка, та надішліть в наступному коментарі.
