### ISSUE TITLE
Загрузка файлов документов при заполнении формы "Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця)"

### ISSUE THREAD

**Issue by mariykam** [e-government-ua/iForum#78]
В при заполнении формы "Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця)" - https://igov.org.ua/service/29/general, необходимо загрузить скан копии одиного или более документов. Форма же позволяет загрузить только один файл. Конечно можно объединить скан копии в doc, pdf или даже в одно изображение, но неясно, подойдет ли формат конечному получателю обращения и это требует дополнительного времени. В связи предлагаю:
1. Добавить возможность загрузить более одного файла
2. Указать в явном виде какие типы файлов можно загружать

UPD
3. Сделать загрузку файла обязательной (ДМС не принимает заявку без документов)
4. Добавить в форму вопрос о наличии детей до 14-ти лет зарегистрированных по месту текущей регистрации, т.к. дети до 14-ти не могут быть зарегистрированы отдельно от родителей.
5. В ДМС также жаловались,что пасспотрные данные, а именно кем выдан документ, записаны не совсем верно - только на одном языке (в моем случае на русском) и наименование органа указано не полностью.

**Comment by Koffeek** [comment]
@mariykam 
Спасибо за отзыв. Отчитываюсь о проделанной работе.
1,2. Добавлена приписка о загрузке в pdf или zip-архиве (получатели примут)
3. Реализуется, т.к. файлы загружаются в зависимости от типа. К концу месяца будет точно.
4. В принципе дети с 10 лет могут быть зарегистрированы отдельно от родителей. Добавим уточнение к вопросу о желании регистрировать ребёнка.
5. По паспортным данным специально сделана сноска, что Вам необходимо проверить насколько корректно и на украинском языке они заполнены, если это не так, то обратиться в службу поддержки своего банка.

Извините, что так долго не отвечали, будем оперативнее. Если ещё будут вопросы - пишите. Спасибо.

**Comment by mariykam** [comment]
Добрый день!
Спасибо за информацию!

4. Нам в ДМС сказали, что именно с 14-ти можно регистрировать ребенка отдельно, он даже может принимать решение, где.
Но дело не совсем в желании зарегистрировать ребенка по новому адресу... Если родитель хочет снять себя с регистрации по старому месту и второй родель там не прописан, то он ОБЯЗАН независимо от своего желания выписать и ребенка оттуда и зарегистрировать вместе с собой по новому адресу или с другим родителем по адресу другого родителя, если родитель зарегистриванны по разным адресам. Ребенок не может быть прописан отдельно от родителей. И тогда нужно еще предоставить в ДМС св-во о рождении. Имхо, важно хотя-бы получить инфу о наличии ребенка по старому адресу и предоставить сотруднику ДМС, чтобы он мог в письме потребовать необходимый пакет документов, если юзер отметит, что будет выписываться с ребенком, или сообщить, что зарегистрироваться без ребенка нельзя, если юзер отметит, что не хочет выписывать ребенка. 

Удачи!

**Comment by Koffeek** [comment]
@mariykam
Если идти строго по закону, то ребёнок с 10 лет может быть зарегистрирован не с родителями, а с 14 самостоятельно подает заявку на регистрацию. Но ДМС обычно не заморачивается и говорит, что отдельная регистрация возможна только с 14. Добавим поле с предупреждением и отдельно в письме укажем про свидетельство о рождении. Спасибо, что помогаете стать лучше.
