### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by serj-miner** [e-government-ua/iForum#780]
1. Заповняю форму "Державна реєстрація фізичної особи – підприємця".
2. Натискаю кнопочку "Замовити послугу з ЕЦП".
3. Видає Invalid Token.

**Comment by annastolbova** [comment]
Будь ласка, спробуйте ще очистити кеш та кукіз в браузері та спробуйте зайти ще раз на послугу (бажано через ЕЦП, яким Ви потім будете підписувати заявку).
Якщо буде помилка, то зробіть скрін помилки, будь ласка, та надішліть на цю адресу.

**Comment by agerman-ua** [comment]
Можливо минув значний час після Вашої останньої авторизації. Вийдіть та знову пройдіть авторизацію.
