### ISSUE TITLE
Не працює система повідомлень

### ISSUE THREAD

**Issue by SFoxLviv** [e-government-ua/iForum#781]
Доброго дня,
Ще 04.04.2017 створив заявку на отримання копії диплому і з того часу висить **В обробці** 
Про це писав Вам у формі https://docs.google.com/forms/d/1d2ZttyUR9DBqSInCXsx_llvg8xp8ecjTgHVJnTtb2HM/viewform?edit_requested=true але відповіді ніякої не отримав (((
Подзвонив в університет і дізнався, що вони мою заявку побачили і документи підготували, тільки не могли зі мною звязатись, бо система повідомлень не працює.
Прошу прийняти це до уваги та виправити як найшвидше, бо виглядає так, що Ваш сервіс вже паро місяців у підвішеному стані і люди не можуть ним скористатись у повній мірі.

**Comment by Akylish88** [comment]
Доброго дня, дякую за звернення.
Спілкувався з працівниками архіву ЛНУ, вони повідомили що вже з вами зв'язувались.

Для покаращення сервісу ми завтра проведемо для працівників ЛНУ навчання, щоб уникнути проблем у майбутньому.

**Comment by SFoxLviv** [comment]
Дякую за оперативну відповідь.
