### ISSUE TITLE
Державна реєстрація змін до відомостей про фізичну особу – підприємця

### ISSUE THREAD

**Issue by TereschenkoA** [e-government-ua/iForum#784]
Добрый день! По заявке 0-1098569082 пришел e-mail с некорректными данными:
во-первых, номер Унікальний номер "Код" : 1766365575539_. на сайте МинЮста не находится
С нижним подчеркиванием: На жаль, за Вашим запитом нічого не знайдено. Спробуйте змінити критерій пошуку.
Без нижнего подчеркивания: Ошибка: За вказаним кодом доступу відомості відсутні

во-вторых, проблема приложением к письму. В приложении запрос другого человека, Тараборкин Дмитро Михайлович.

Как мне получить информацию о моей заявке? Мне нужно подавать ее повторно?

**Comment by agerman-ua** [comment]
Добрый день.  @TereschenkoA 
Нет, подавать повторно не нужно. Разбираемся.
С уважением, Август

**Comment by agerman-ua** [comment]
Ага. Теперь ясно.
Администратор опечаталась и одна цифра задублировалась.
176636557539 - правильный номер "Результату надання адміністративних послуг".
С уважением, Август.
