### ISSUE TITLE
Авторизация через IDкарту недоступна

### ISSUE THREAD

**Issue by NataliaLiash** [e-government-ua/iForum#787]
Сыну 17 лет, есть ID карточка. Войти по ней невозможно, потому что ни один из трех смартфонов в семье не имеет NFC модуля. В банке он не имеет карты полноценной. Вопрос: каким образом он может записаться на снятие с места регистрации? Могу ли это сделать я через свой аккаунт, если ему это сделать невозможно?

**Comment by NataliaLiash** [comment]
Уже убедилась, что не могу подать заявление за сына. Как быть дальше?

**Comment by zolotovatatyana** [comment]
Так, ви можете зареєструвати дитину через спеціальну послугу для дітей, використовуючи свій аккаунт
