### ISSUE TITLE
Витяг з ЄДР юр. осіб та фоп - не указан инн.

### ISSUE THREAD

**Issue by meakashi** [e-government-ua/iForum#788]
Добрый день.
Зарегистрировался как ФОП через igov - № 0-1368189848. Заявка успешно обработана.
Сделал вытяг из реестра №1003014387, а он не подходит, чтоб сделать ключи для сдачи отчетности. Как получить выписку о регистрации?

**Comment by zolotovatatyana** [comment]
Доброго дня! після успішної реєстрації Ви отримали листа з кодом надання послуги. Зробіть виписку о реєстрації використовуючи для запиту цей унікальний код адмінпослуги

**Comment by meakashi** [comment]
Как получить выписку, а не вытяг. В вытяге нет инн.

**Comment by meakashi** [comment]
Спасибо. Понял.
