### ISSUE TITLE
Ответ по заявке  5037754

### ISSUE THREAD

**Issue by Kostya91** [e-government-ua/iForum#79]
Заявка на субсидию номер 5037754, 
2015-09-28 13:55:22.727	Взяти в роботу 
таков статус на  11.11.2015. 
Вопросы: 
-чего не взяли в работу, я так понимаю что следующий статус "в работе" или что-то вроде этого?
-когда возьмут в работу? 
- когда ответ по заявке?  сроки прошли

**Comment by dmitrijzabrudskij** [comment]
какой район выбирали при подаче?

**Comment by Kostya91** [comment]
Ленинский район

**Comment by Kostya91** [comment]
Дмитрий, получилось что-то узнать ?

**Comment by dmitrijzabrudskij** [comment]
да, в работе на финальном этапе. ждут решения. после чего отправят Вам ответ
