### ISSUE TITLE
заявка №0-1749209317

### ISSUE THREAD

**Issue by Hanna09** [e-government-ua/iForum#790]
Добрый день! Подскажите, пожалуйста, что со статусом заявки? с 28.02 весит в очереди, 05.03 обновилась до нового статуса - "ожидание в очереди"((( По таймингу в Днепропетровской области около 7 дней на обработку, а прошло уже 2 недели

**Comment by zolotovatatyana** [comment]
Дякуємо за Ваше повідомлення. ​З відповідальними держслужбовцями буде проведено роботу з метою прискорення обробки Вашої заявки та унеможливлення затягування строків в майбутньому.

**Comment by Hanna09** [comment]
Вдячна за Ваш час і вашу відповідь, але воз і нині там! 
3 тижні на обробку - це багато дуже.

**Comment by Hanna09** [comment]
Така сама ситуація зі зверненням № 0-1788198920.
Вже страшно подавати інші звернення!
