### ISSUE TITLE
Звернення № 0-1893308709 - Регистрация ФОП

### ISSUE THREAD

**Issue by Hanna09** [e-government-ua/iForum#791]
Добрый день!
Спасибо Вам огромное за помощь с прошлыми обращениями!
Но ситуация повторяется, к сожалению!
Заявка с 02.04 весит в очереди, 07.04 обновилась до нового статуса - "ожидание в очереди"((( По таймингу в Днепропетровской области около 7 дней на обработку, а прошло уже почти 4 недели. На обращение в поле комментарий гос. служащим никакого ответа. Переподать заявку я не могу так как как висит текущая! Месяц на открытие ФОП - это очень долго....

**Comment by agerman-ua** [comment]
@Hanna09 добрый день.
Да, к сожалению именно такая очередь на текущий момент и сформировалась. Но как раз сейчас берут в работу начало апреля. Если сегодня не успеют отработать то уже в среду. Но не позднее. На всякий случай напоминаю про упрощенку. Проверяйте после регистрации, пожалуйста статус в налоговой. Мы не можем сейчас это делать автоматически за Вас.
В ближайшее время должна ситуация качественно измениться в лучшую сторону. 
С уважением, Август

**Comment by agerman-ua** [comment]
@Hanna09 заявка уже была в работе, уточнил - должны успеть обработать сегодня.

**Comment by Hanna09** [comment]
Огромное вам спасибо за Ваш труд!)))
