### ISSUE TITLE
Звернення 0-2140927019 держ. реєстрація ФОП

### ISSUE THREAD

**Issue by Inna513** [e-government-ua/iForum#792]
Доброго дня !
Подала заявку ще 22.08, до цього часу вона в статусі «Очікування в черзі».
Як можна прискорити процес реєстрації?
Допоможіть, будь ласка!

**Comment by agerman-ua** [comment]
Доброго дня. 
Спробуємо. З ранку.

**Comment by agerman-ua** [comment]
В роботі. Макимум до понеділка включно опрацюють.
Буде непогано якщо сюди відпишитесь про "да" чи "ні". Дякую.

**Comment by Inna513** [comment]
Да.
Дякую!

7 сентября 2018, 14:11:18, от "agerman-ua" <notifications@github.com>:

В роботі. Макимум до понеділка включно опрацюють.
Буде непогано якщо сюди відпишитесь про "да" чи "ні". Дякую.

**Comment by agerman-ua** [comment]
Зверніть увагу, будь-ласка, на систему оподаткування. Щоб співпадало з очікуваним. Бо на податкову не маємо впливу.

**Comment by agerman-ua** [comment]
І Вам щира подяка від всіх нас за те що скористалися послугою на порталі. Гарного дня!
