### ISSUE TITLE
Звернення № 0-2231591346

### ISSUE THREAD

**Issue by gbi46** [e-government-ua/iForum#793]
Здравствуйте. Правильно понимаю, что в Павлограде Днепропетровской области еще не рассматриваются заявки, созданные через портал?

**Comment by zolotovatatyana** [comment]
Ваше звернення оброблене, приносимо вибачення за можливі незручності, викликані затримкою опрацювання з боку держслужбовців. З відповідальними буде проведено роботу з метою унеможливлення затягування строків в майбутньому.
