### ISSUE TITLE
0-2196874047

### ISSUE THREAD

**Issue by funkeuphoria** [e-government-ua/iForum#794]
18сентября подала заявку. До сих пор нет ответа. 24го заявка изменила статус на "рассмотрение" и все. Как узнать, кто рассматривает заявку, куда её направили и к кому обращаться с вопросами о сроках рассмотрения.

**Comment by zolotovatatyana** [comment]
Ваше звернення оброблене. Деталі направлено електронною поштою 5 жовтня.

**Comment by funkeuphoria** [comment]
Не знаю, имеете ли вы доступ к ответу, на который ссылаетесь, но в этом ответе говорится о том, что мой запрос перенаправлен к распорядителю информации и ответ будет дан в ближайшее время.  На данный момент его ещё нет. Как можно менять статус моего запроса на "закрыт"?

**Comment by zolotovatatyana** [comment]
Відповідь органом, який отримав Ваше звернення (Херсонська ОДА), надана в повному обсязі в межах його компетенції. Запит передано до Херсонської МВК, після розгляду вони зможуть надати свою відповідь на контакти що Ви залишили при реєстрації звернення.

**Comment by funkeuphoria** [comment]
То есть iGov работает только с городской администрацией? И на этом этапе
любой ответ администрации даёт повод закрыть вопрос, хотя на самом деле,
его просто перенаправити в исполнительный комитет?
 Даже не смотря на то,что я по сути ответ не получила, а получила
информацию только о текущем статусе запроса?
Когда будет дан ответ из исполкома, на сайте iGov  для меня ничего не
изменится? И этот ответ я там просмотреть не смогу?
Спасибо.

**Comment by zolotovatatyana** [comment]
![image](https://user-images.githubusercontent.com/17428210/46607253-fd05e900-cb08-11e8-911c-92f46eab77ee.png)
при реєстрації Вашого звернення Ви обираєте орган, до якого звертаєтесь із запитом. 
На порталі звернення до ОДА закрито, і відповідь від МВК в межах потчного запиту надана бути не може. 
Ви можете або очікувати на відповідь каналами, які обере МВК із переданого з ОДА запиту, або подати новий запит на сайті, вказавши правильного суб'єкта.
