### ISSUE TITLE
Субсидии: за какое время нужна декларация?

### ISSUE THREAD

**Issue by katebutenko** [e-government-ua/iForum#8]
Задают вопрос, за какое время подавать декларацию. Человек работал в войсках Украины полгода в 2014м году, с тех пор безработный. Что и как отмечать в заявке на субсидию?

**Comment by dmitrijzabrudskij** [comment]
там по умолчанию стоит нужный период (2014 год)

**Comment by katebutenko** [comment]
а если человек полгода работал, а потом перестал, что тогда нужно писать в каком поле? Там дальше вопросы "Назва організації, де Ви працюєте:" и т.д., все в настоящем времени.

**Comment by dmitrijzabrudskij** [comment]
ну если в настоящем времени, то писать про текущую ситуацию - то есть безработный

**Comment by katebutenko** [comment]
Заполнявший передает спасибо :) закрываю таску.
