### ISSUE TITLE
Заявка 11020575

### ISSUE THREAD

**Issue by tertish** [e-government-ua/iForum#80]
Появился статус заявки на субсидию
"Необхідно уточнити дані
Заява та декларація направлені до районного управління СЗН Павлоградської РДА. Рекомендуємо звернутися до управління м.Павлоград."

То есть это отказ? Обращаться в СЗН обязательно нужно, к кому, и по какому вопросу?

**Comment by dmitrijzabrudskij** [comment]
попробуйте позвонить им: (05632) 6-25-69, (05632) 6-28-57

приход в районное отделение соцзащиты нужен только в одном случае - если Вы декларацию заполняли за последние 3 месяца (тогда нужны справки о доходах всех работающих прописанных с Вами)

если будут что-то другое требовать - опишите ситуацию сюда и дайте номер заявки

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
