### ISSUE TITLE
не могу авторизироваться

### ISSUE THREAD

**Issue by nikitakam** [e-government-ua/iForum#81]
здравствуйте, при авторизации через систему bankid, приватбанк, ввожу номер телефона, пароль, идет переадрессация на igov и там выдает следующее:"ПОМИЛКА{"code":200,"err":{"error":{"state":"err","code":"CLD001","desc":"Ошибка получения данных клиента "}}}"

**Comment by GrekD** [comment]
@nikitakam проблема еще актуальна?
