### ISSUE TITLE
Отзыв об оформлении загран.паспорта

### ISSUE THREAD

**Issue by olenaa** [e-government-ua/iForum#82]
Здравствуйте, я воспользовалась услугой эл. записи в миграционную службу для оформления загран. паспорта. Реальная процедура немного отличалась от того, как она описана на сайте. Я бы хотела оставить отзыв для других пользователей, возможно, он будет так же полезен людям, которые тестируют услугу. Где я могу его написать?

**Comment by dmitrijzabrudskij** [comment]
добрый день
пишите сюда, пожалуйста
все, что будет возможно на данный момент, учту

**Comment by olenaa** [comment]
Ок. 
1) Если речь идет о переоформлении загран. паспорта (у меня истек срок действия), то с собой обязательно нужно брать старый паспорт и сдавать его.
2) Если нужно оставить себе старый паспорт (у меня действующая виза), то нужно взять с собой оригинал старого загран. паспорта, сделать его копию и дополнительно оплатить 60 грн.
3) Если оплачивать услуги наличными - нужно взять с собой дополнительные деньги на оплату комиссий (у меня было 3 платежки в среднем по 8 грн). 
4) Берут не 2, а одну ксерокопию ИНН   
6) Ксерокопии платные
5) Там нужно заполнять заявления - дают бланки, но с собой надо брать ручку :)
Еще - в самой службе никак не информируют о возможности регистрироваться через интренет, или о том, что "статус" паспорта можно отследить он-лайн. Нет ни объявлений, ни печатных материалов.

**Comment by dmitrijzabrudskij** [comment]
спасибо за информацию. отвечаю по тем пунктам, которые знаю:
1. добавлю эту инфу в имейл. таки недосмотрели
2. тоже самое
3. специально не указываем эту информацию чтобы не делать рекламу того терминала, который у них стоит (поэтому есть общее "наличные")
4. зависит от района. в некоторых 2 нужны. чтобы не бугать потом по округе в поиска ксерокса пишем сразу 2 с запасом:)
5. поэтому пишем 2
6. это, конечно, кошмар:( в каком районе такой абсурд происходит?

это уже присылается в имейле после регистрации. добавлю еще в имейл после посещения миграционной службы

**Comment by olenaa** [comment]
Спасибо за обратную связь :) я была в отделении на Ильича 3. В очереди было около 20 человек и только одна я по эл. регистрации. Соответственно - очередь на ксерокс, очередь в терминал и т.д. На месте людей никто не информирует, что можно отслеживать статус он-лайн, и если человек не регистрировался на сайте - он и не узнает о такой возможности. На вопрос "когда забирать паспорт" - отвечают, "приходите ровно через 30 дней во второй половине дня". Звонить некуда, да и "некогда отвечать на звонки", то есть только личный визит = опять очередь.

**Comment by dmitrijzabrudskij** [comment]
имейл уже поправил
насчет всего основного - тоже работаем, не всегда быстро, но все-таки получается менять отношение специалистов миграционной службы к процессу и гражданину.

**Comment by olenaa** [comment]
Спасибо большое :) Да, я понимаю, что менять систему нелегко, это просто супер, что теперь не надо стоять в очереди, чтобы сдать документы! Может, со временем можно будет записаться и на получение готового паспорта?

**Comment by eugen7** [comment]
"Воспользовался" услугой получения загранпаспорта через igov.org.ua...Впечатлений масса и все негативные. Есть, так сказать, "большое спасибо" как к работникам миграционной службы, так и к igov.org.ua. Если позволите (не удалите) напишу подробнее и не только вам.

**Comment by dmitrijzabrudskij** [comment]
@olenaa да, хочу так сделать со временем. пока не получается синхронизироваться 

@eugen7 конечно рассказывайте

**Comment by eugen7** [comment]
Молчание с вашей стороны расцениваю как знак согласия. Поэтому пишу подробнее как "козаки загранпаспорт получали". 
Началось всё хорошо. Даже подозрительно хорошо и просто. Зашёл на igov.орг.(далее буду писать - "игов" потому, что тут автоматически что-то переправляется некоректно)., через приват24   авторизировался, записался на ближайшее свободное время на ул. красная 2 Днепропетровск, получил очень вежливое письмо с инструкциями, подписанное двумя авторами: "игов" и "державной миграционной службой". причём заканчивалось письмо "с уважением". Как я дальше поясню, это слово ("с уважением") окажется ключевым в дальнейшей работе миграционной службы.

**Comment by eugen7** [comment]
Отпросился с работы, прибыл заранее (на пол часа) в указанное место (мало ли, ну чтоб вдруг не пропустить долгожданную встречу). Как вы понимаете назначенное время - вещь относительная (настолько относительная, что Энштейн об этом даже не подозревал). В помещении на ул. Красной обнаружил с два десятка утомлённых, заросших и отчаявшихся людей. Посмотрев им в глаза и спросив кто крайний, сразу вспомнил фильм "Хатико" как верный пёс ждал на вокзале своего хозяина. Никаких ассоциаций или параллелей проводить не стану, просто глаза, выражение их глаз...очень похожее... 
С этого момента я вернулся к реальности.
Визуальной либо какой-нибудь другой информации по поводу того, в какую дверь, за кем, в какой последовательности нет. Никто ничего не знает. Случайно узнаю, что в очереди есть люди, которые записались как я через игов. Бывалые в этих стенах люди из очереди посоветовали держаться ближе к белой закрытой пластиковой двери без опознавательных знаков: отдута время от времени могут появляться как приведения какие-то женщины, причём время их появления предугадать (как рассказывали люди с опытом) практически не возможно. Можно прождать два часа безрезультатно, а можно наблюдать их появление очень часто. Они открывают двери называют фамилии только что подошедших каких-то людей (не назначавших как мы время), но имеющих нужный телефон на который они звонят с улицы (в стеклянную дверь всё видно да и частично слышно). Перед тем как их запускают в "святая святых" в те самые белые двери, к ним на улицу выходит с папочкой мужичок с соседнего кабинета, потом тот мужичок возвращается со своей папочкой. Люди проходят. За те два часа моего ожидания мужичок выбегал на улицу минимум раз пять.  Ну такая у него работа, всё время на ногах... 
Спустя два часа от назначенного, пришло и моё время - пришла женщина (без косы), но собственную смерть я так именно и представлял: наглая, хамоватая, смотрит на тебя с пренебрежением и выражением лица, что всё теперь в её руках и ни куда ты от неё не денешься.
Я пытаюсь зайти. Люди набрасываются на неё (словно пытаются меня защитить от её холодного дыхания), задавая свои вопросы на которые им некому дать ответы, возмущаясь что они большее не выдержат и покончат жизнь самоубийством, так и не поняв зачем всё таки нужен "игов", электронные записи и процедуры, если ничего не изменилось.
Наконец, прохожу в их пыточную, присаживаюсь, даю копии документов. Женщина подходит ко мне, смотрит мои документы, и задаёт мне потрясающий вопрос - "и что?", "что вы хотите?". Я начинаю объяснять, что пришёл получить платную услугу оформления загранпаспорта. Она -"Где квитанции?". Я объясняю,что ещё не оплатил, могу дать наличные деньги (как было указано в письме) или сейчас сам могу оплатить и принести квитанции. В это время заходит вторая служительница преисподнии. Далее они начинают при мне обсуждать мой отчаянный поступок (прибытие к ним без квитанций), тыкают на меня пальцами, фыркают "что им чтоли нужно за меня идти оплачивать", дают мне советы почитать закон "про державну службу" и т.д. На мои апелляции к полученному письму, в коем чёрным по белому всё написано (причём как я выше указывал с уважением подписанное двумя авторами), обе служительницы дружно мне ответили, что не имеют никакого отношения к письму, к "игов" - сайту облгосадминистрации, миграционная служба здесь не причём, все эти электронные записи "имели они в виду" (это если быть кратким), и что мне придётся заново записаться через "игов" и прийти уже с квитанциями. Кстати, одна из барышень сказала что на днях имела встречу с "разработчиками игов", популярно им объяснила что она думает о всём этом, на что они - разработчики "сильно обиделись". 
      Из разговора с обидчицами, я пришёл к выводу что они совершенно не владеют информацией из моего бланка запроса на "игов" : по какому вопросу я к ним записался, на какое время и т.д. Реквизиты для оплаты "держмита" в письме заметно отличаются от реквизитов, которые они мне дали на бланке (хорошо, что я не оплатил его заранее по данным из письма, потому что они бы заставили меня оплачивать снова второй раз). По остальным банковским реквизитам у меня также есть вопросы, немного разберусь и думаю что вопросы появятся не только у меня, но и компетентных органов...Знания порождают скорбь, а хамство - проблемы. 
В общем, вырвался я из их плена на свободу, иду по улице обплёванный (но зато живой!) и думаю, что ничего из этого ("игов") не получится. Всё как раньше работало, так и работает. Всё мутно, проблемно, и главное анонимно. Установить личности обеих красавиц мне так и удалось (в миграционной службе на ул.Красной это большой вопрос кто тебя обслуживает), и в письме которое я получил об этом ни слова. А ведь из-за этой анонимности потом отсюда и качество обслуживания, и фразы "у нас у всех столько работы", премии не понятно кому и не понятно за что, очереди брошенные на произвол судьбы, необоснованные "отшивы" клиентов за которые никто не отвечает и т.д.  И мы это всё содержим, платим.. за услуги миграционной службы.
Покидая стены этой организации мне одна из вышеупомянутых особ (ну которая общалась с "разработчиками игов"), кинула вслед фразу что "разделяет со мной горе" от того, что не получается так как написано и как должно быть. 
Но как по мне, горе совсем не в этом, а в том что обоим работницам миграционной службы на внешний вид чуть более 20-25 лет, и рассуждая таким образом в своём возрасте, о своей работе, о своём функциональном предназначении, имея уже сформированное и закалённое своё понимание системы работы с клиентами, поступая "по-старинке" в свои детские 25... идея "игов" не плохая, но вряд ли у неё получиться вылечить эту болезнь. 

Р.S. Сегодня утром мне пришло сообщение от "игов", что я (несмотря на всё вышеизложенное) оказывается не явился своевременно для сдачи документов для оформления загранпаспорта и мне предложено снова зарегистрироваться на портале "игов". И знаете кто подписался? Два автора. И главное, с уважением, державна миграцийна служба и команда портала "игов".
       Буду ли я снова подавать заявку? Наверное, нет. Главное, чтоб "игов" в статусе заявок себе для отчётности и статистики поставил плюсик, гордо и уверенно обозначил на странице проверки статусов заявок - "Заявка виконана"!

**Comment by eugen7** [comment]
подскажите, а как удалить свои цифровые документы в разделе "мои документы" на https://igov.org.ua/ ?

**Comment by dmitrijzabrudskij** [comment]
сообщите, пожалуйста, Ваше фио и дату визита на красную? если фамилию сотрудницы выяснить не удалось, то имя ее Вы запомнили?

**Comment by eugen7** [comment]
Имена не помню. Был вчера 16.11.15. назначенное время 15.30. Моя фамилия Варнаков Евгений Александрович. Сотрудницы были две. Номер моей заявки 15986629. Вы админ и можете  проверить?

**Comment by dmitrijzabrudskij** [comment]
я разработчик этой услуги. что Вы хотите проверить?

**Comment by eugen7** [comment]
Я имел ввиду, Вы можете проверить кто меня обслуживал? если верить одному из упомянутых выше персонажей, то вы её должны знать или хотя бы обидеться. Брюнетка, среднего роста, "деловая колбаса".

**Comment by dmitrijzabrudskij** [comment]
ну я догадываюсь кто это -  и правда звонила-высказывала свое мнение. посмотрим что выйдет из этой ситуации. спасибо Вам за сигнал. я отпишусь по результату

**Comment by eugen7** [comment]
Если установка исполнителей не возможна или займёт много времени, то не тратьте время. Вы не сможете на них повлиять. Эффективным может быть только один метод - проводить внезапные проверки, ловить на горячем, привлекать к ответственности.
Результат обращения клиента всё равно останется таким, каким он всех устраивает кроме самого клиента: для миграционной службы - клиент не приходил, для портала - заявка выполнена, клиент - без паспорта, и для того чтобы не унижаться и получить паспорт  он обращается к "нужным" людям за дополнительную плату, и заходит как белый человек в те самые белые двери. Кстати забыл упомянуть, что на моих глазах для таких клиентов другие сотрудницы этой самой миг.службы лично и мигом проводили платежи через стоящий в коридоре зелёный терминал.

**Comment by artexmedia** [comment]
Сегодня оформлял, процесс прошел отлично, кроме того что обычные квитанции они не принимают, необходимы мокрые печати, так что кто будет оформлять через приват24, надо ехать в банк потом!

**Comment by dmitrijzabrudskij** [comment]
@artexmedia а в каком подразделении это было?

**Comment by artexmedia** [comment]
@dmitrijzabrudskij на пр. Ильича, 3

**Comment by dmitrijzabrudskij** [comment]
спасибо за информацию

**Comment by artexmedia** [comment]
@dmitrijzabrudskij да это вам спасибо

**Comment by alex-xander-dp-ua** [comment]
Дублирую то, про что общался через ФБ с Дмитрием Дубилетом 28.08.2015

Как мне стало известно из гугла, существует вот такой документ:
=========
ЗАЯВА
Прошу Вас надати мені дозвіл на написання прізвища та імені ( чи прізвища, або імені) в моєму 
закордонному паспорті латинськими літерами, а саме:
відповідно до їх написання у документах, виданих державними органами іноземної країни 
Копію вказанного документа додаю.
Дата Підпис
==========
При обслуживании 25.08.2015 на улице Поля мне изначально отказали на включение в анкету нужный мне вид латинской транслитерации.
Но девушка-клерк сразу же предложила прийти на следующий день с подтверждающими эту необходимость документами - их оригиналами и ксероксами. И сказала, что этот вопрос можно будет решить в течение этой недели, то есть до 28.08.2015, после чего документы уже уйдут в Киев окончательно.
26.08.2015 я пришел с оригиналами и ксероксами сертификатов в области IT, выданных мне американским сертификационным центром, и оригиналом и ксероксом моего EIN - налоговым номером, выданным мне американской налоговой службой - то есть иностранным государственным органом.
Теперь со мной беседовала уже не девушка-клерк, а их начальница отдела по фамилии Ярош (сама лично она мне никак не представлялась, но я её имя узнал ещё вчера , через телефон горячей линии), сначала мне было безаппеляционно заявлено, что все эти мои документы были заполненны мной так как мне захотелось и теперь на их основании хочу от неё чего-то добиться - то есть разговор изначально стал неконструктивным, потом после дальнейшего разговора мне было предложено НОТАРИАЛЬНО всё это перевести и нотарильно заверить до 27.08.2015 (то есть меньше чем за сутки!) - так как она не знает английского языка, а только русский и польский язык. 
На основании каких именно документов я должен сделать именно нотариально - мне пояснено не было, ни текст ни номер.

В частном разговоре со своими друзьями я узнал , что за нужное латинское написание имени и фамилии в загранпаспорте ещё несколько лет назад с них брали взятку в размере 1500$
Я не знаю  - шла речь конкретно про эту начальницу Ярош или про ещё какого-то другого начальника в нашей областной миграционной системе - но налицо большое потенциальное коррупционное поле. 
Которое нужно было бы ликвидировать. 
А так же организовать прозрачное рассмотрение документов на нужное латинское написание имени и фамилии.

Что из всего этого можно было бы организовать и упростить?

**Comment by dmitryvovnenko** [comment]
Добрый день! Сегодня впервые столкнулся с реалиями оформления загранпаспорта. Точнее моя жена столкнулась. 30 января зарегистрировали заявку на получение загранпаспорта на igov.org.ua. Время выбрали 4 февраля на 10:45. Жена приготовила весь пакет документов: ксерокопии, оригиналы, старый загранпаспорт, проплатила в отделении банка необходимые платежи и получила на руки квитанции с мокрыми печатями. Сегодня приехала в отделение ГМС на Октябрьской, 12 (г. Кривой Рог). Там ее никто не ждал. Потребовали бумаги, которые подтверждают, что она записана на данное время. Распечатку электронного письма мы сделать не догадались. Ей рассказали, что они не малейшего отношения к сайту igov.org.ua не имеют, и что там происходит не имеют ни малейшего представления. Кроме того рассказали, что вообще не имеют доступа к базе данных сайта igov.org.ua, т.е. они наши заявки якобы вообще не видят. И рассказали басню о том, что ближайшая дата, на которую могут записать для фотографирования это 17 марта, т.е. через 1.5 месяца! Шок!!!
Заявка 0-96108034. До сих пор висит такой статус "2016-01-30 18:42:12.624	Заявка подана - обробка дмс"
Какие возможные варианты решения данного вопроса? Стоит ли подавать заявку и приходить к ним второй раз с распечатанным письмом? Куда есть смысл пожаловаться?
Заранее спасибо за все возможные ответы.

**Comment by dmitrijzabrudskij** [comment]
@dmitryvovnenko разбираемся с Вашим случаем. по результату отпишусь

**Comment by dmitryvovnenko** [comment]
Пока что оформили вторую заявку на 8 февраля в 14:45. Письмо с указанным временем уже распечатали и положили в общую стопку документов. Но хочется жить цивилизованно, а не так, как при совке: если ты выдаешь бумажки, то только тогда можешь чувствовать себя человеком. Да и на ускорении процессов кое-кому видимо очень хочется зарабатывать.

**Comment by dmitrijzabrudskij** [comment]
@dmitryvovnenko вправили мозги Кривому Рогу - с нетерпением ждут Вас 8-го числа. если будут какие-то замечания - пишите обязательно сюда

**Comment by AndriiUKR** [comment]
Добрый день!
Сегодня тоже были в этом отделении - Кривой Рог, ул. Октябрьская. История следующая.Приходили по заявке 0-93950243. Записывались на 15-00 на оформление биом.загран.паспорта для ребенка . Пришли в 14-30. Ксерокопии сделали.  По счету не платили. В итоге оказалось, что реквизиты у нас не те. Дали другие и ПОСЛАЛИ в банк. Оплатили быстро и в 14-45 были уже в кабинете у начальника. Он культурно отправил нас фотографироваться в 1й или 3й кабинет. И тут НАЧАЛОСЬ! Там оказывается очередь по номеркам!, а не по времени! У нас, естественно, номерка нет. Мы стали наугад за последними в оба кабинета. Первая подошла очередь в 3й. Зашли. Женщина грубая и нетактичная. Такое ощущение, что ты преступник. Пробыли у нее минут 20. Сказала, что у нее вышла из строя аппаратура и ИДИТЕ ДЕЛАЙТЕ В ДРУГОМ МЕСТЕ!!! Может перегрузите аппаратуру? Мы подождем. НЕТ! ИДИТЕ! У меня люди по месяцу ждут, а вы хотите так все быстро оформить! В 1м кабинете мы свою очередь пропустили. Вернулись в 3й. А там ДАЛЬШЕ ИДЕТ ПРИЕМ! ВСЕ НОРМАЛЬНО РАБОТАЕТ!!! НО ВСЕ-РАВНО ИДИТЕ ДЕЛАЙТЕ В ДРУГОМ МЕСТЕ!!! НА ВАШЕГО РЕБЕНКА АППАРАТУРА НЕ РЕАГИРУЕТ!!! Вот такой БРЕД!!!Пошли опять к начальнику. Опять все культурно и благородно! Большая подпись на документах и отправил конкретно в 1й кабинет без очереди. Там от женщины опять хамство в наш адрес. Фамилию уже нашу знала на тот момент. В кабинете с ребенком быть не разрешила, но на подпись позвала. Ушли в 16-30. Потрачено куча нервов, но документы приняли. Будем ждать выдачи.
Получится когда-нибудь скоординировать две очереди(ведь обе же по предварительной записи)?

**Comment by dmitrijzabrudskij** [comment]
@AndriiUKR спасибо за информацию. на начальника уже подействовало, до остальных тоже, надеюсь, дойдет

а насчет реквизитов - действительно такое есть - каждый год счета меняются на новые. предупреждение день в день - потому Вы и попали в эту ситуацию (имейл отправлялся намного раньше при регистрации заявки еще со старыми счетами)

**Comment by dmitryvovnenko** [comment]
AndriiUKR, а какие же реквизиты действительны на данный момент? Если заявка подавалась 30 января, то это уже новые реквизиты?

**Comment by dmitrijzabrudskij** [comment]
вот счет для оплаты услуг:
Р/р 37114034079427  ЄДРПОУ 37806243  МФО 805012 в ГУДКСУ у Дніпропетровській облас

поменялся с 04.02

**Comment by dmitryvovnenko** [comment]
Как же все сложно. А если уже оплатили 3 февраля, то что делать то?

**Comment by AndriiUKR** [comment]
Как я понял 3.02.2016 действовали еще старые реквизиты, а именно сегодня уже другие. Т.е. если бы мы оплатили сегодня по старым то было бы в трубу, а у Вас все ок.

**Comment by dmitrijzabrudskij** [comment]
да, все правильно поняли - с 04.02 новый счет. до этого дня учлась бы оплата на старый.

**Comment by dmitryvovnenko** [comment]
Документы сдали, все быстро сделали, для тех, кто регистрирует заявку на сайте, всё делают быстрее, кстати с 8 февраля офрмлять документы на загранпаспорт можно по районным паспортным столам.

**Comment by AndriiUKR** [comment]
Продолжение нашей истории. Вчера 1 марта 2016 позвонили и сказали, что полиграф.комбинат фото забраковал. Персонал свое "ФЕ" к нам все-таки ПРОЯВИЛ!!! Приходите делать новое фото в 1-й кабинет. И это спустя 3,5 недели!!! Твари! Больше нечего сказать. 
Теперь не знаю, занимать ли опять электронную очередь или так пойти? Думаю запишусь, на всякий случай в электронную.

**Comment by MariaDudnichenko** [comment]
Добрый день! При регистрации эл. очереди на получение загранпаспорта в Днепропетровской обл, город Никополь невозможно выбрать дату и время. Все поля заполнены , дат нет. Пишу везде и всюду , срочно нужно просто. Прошу пожалуйста исправить.

**Comment by Lilia1507** [comment]
Добрый день! Зарегистрировалась на сайте igov, в Кривой рог, теперь переживаю меня вызовут по моему времени или все равно занимать очередь? И я уже оплатила по тем реквизитам что мне выслали на почту,  судя по комментариям я так понимаю что могут оказаться не те реквизиты?

**Comment by MariaDudnichenko** [comment]
У меня получилось так что по почте после эл. регистрации мне пришли 2 реквизита на 170 и 390 грн но по приходу в дмс в Никополе оказалось что нужен ещё 1 платёж на 85 грн ( типа экспресс справка о несудимости). И в реквизитах на 390 грн оказался неправильный код услуги, пришлось возвращаться в банк , и там все исправили.

**Comment by AndriiUKR** [comment]
Вот и закончилась наша история получения загран.паспорта для ребенка.
Итого с 4 февраля по 1 апреля оформляли документ. Два месяца нервотрепки.
Так с людьми не должны работать.

**Comment by MariaDudnichenko** [comment]
Добрый день ! а как я могу себе создать эл очередь, если я клиент банка кредит днепр?

**Comment by nixeramus** [comment]
Подскажите по заявке 0-148790190 - висит в статусе Заявка подана - обробка дмс

**Comment by paveldhq** [comment]
Добрый день. Есть проблемка - заявка долго висит в состоянии *Заявка подана - обробка дмс*

12.05.2016 подал 4 заявки:
- на себя - 0-233749713 (замена)
- на детей 0-233836343, 0-233815565, 0-233797302 (выдача)

Не пришло ни одно письма с инструкциями. Подскажите, это глюк сервиса или раздолбайство сотрудников ДМС?

Спасибо.

**Comment by dmitryvovnenko** [comment]
Письма с  сервиса должны были обязательно прийти со всеми инструкциями и списком документов, которые необходимо подготовить. По поводу статуса "Заявка подана - обробка дмс": похоже они тупо игнорируют, но если вы в Кривом Роге подавали заявку на улицу Октябрьскую, то можно смело ломиться в назначенное время к начальнику. Он отправляет в кабинет на первом этаже, там вам отсортируют все документы, аккуратно сложат в необходимом порядке и опять возвращаетесь к начальнику. На этом этапе документы на ваших детям он забирает, а вам придется отстоять живую очередь к кабинету, где вас фотографируют. Единственный момент насчет фотографий детей - делайте фотографии без очков, если кто-то из них носит. У меня старшую дочку в фотостудии сфотографировали в очках, то хорошо что удачный снимок и очки не перекрывали зрачки, поэтому сказали что прокатит. На какое число подавали заявку то?
