### ISSUE TITLE
Пособие при рождении ребенка - не меняется статус

### ISSUE THREAD

**Issue by alex0405** [e-government-ua/iForum#86]
Добрый день.
Заявка 15401600. Жовтневый район. Подана 10/11/2015г.
Статус: "2015-11-10 14:09:43.638	Заявка подана"
В ответах здесь было, что через 3 дня статус должен измениться на "У роботі".
Как уточнить, есть ли движение по заявке?

**Comment by GrekD** [comment]
@alex0405 
добрый день! Подскажите, пожалуйста, вопрос еще актуален?

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
