### ISSUE TITLE
Заявка 5233934

### ISSUE THREAD

**Issue by Nikolay2016** [e-government-ua/iForum#87]
Добрый день. В письме в котором указывалось что моя заявка обработана, было написано, что размер субсидии указан в приложенном файле. На самом деле был приложен файл "ук ел.заява.pdf" со статьей "Інтернет допоможе оформити субсидію" из газеты "Урядовий кур'ер". Размера субсидии там не указано. Подскажите мои дальнейшие действия? Где мне ознакомится с размером субсидии?  Спасибо.

**Comment by dmitrijzabrudskij** [comment]
добрый день. подскажите район, номер заявки и Вашу почту, которую указывали при подаче?

**Comment by Nikolay2016** [comment]
Добрый день. Район - Бабушкинский,  Заявка - 5233934, email -
nikolay.com@gmail.com
Спасибо.

*-------------------------------------------------------------------------*
*С уважением,*
*Николай*

17 ноября 2015 г., 17:56 пользователь dmitrijzabrudskij <
notifications@github.com> написал:

**Comment by dmitrijzabrudskij** [comment]
спасибо за сигнал. буду разбираться с районом
