### ISSUE TITLE
субсидии

### ISSUE THREAD

**Issue by OksanaGorant** [e-government-ua/iForum#9]
при заполнении информации максимальное количество взрослых проживающих выбирается 1+3. У меня больше. Как это можно указать? Так же не указывается проживание несовершеннолетних детей. Это нужно указывать? И обслуживающий район выбирает не по проживанию.

**Comment by dmitrijzabrudskij** [comment]
1+5
вписывать
поясните?

**Comment by OksanaGorant** [comment]
Куда вписывать?
Виберіть район, в якому ви обслуговуєтесь: - я могу выбрать только 2 района.

**Comment by dmitrijzabrudskij** [comment]
в форму вписывать
значит, другие районы еще не участвуют в пилоте

**Comment by OksanaGorant** [comment]
спасибо

**Comment by katebutenko** [comment]
@dmitrijzabrudskij  мне тоже жаловались, что в форме нет отдельного поля для детей, может просто добавить?

**Comment by dmitrijzabrudskij** [comment]
так а зачем детей выносить отдельнок куда-то? указывайте по ним все данные кроме паспорта и инн - и они тоже попадут в заявку

**Comment by katebutenko** [comment]
@dmitrijzabrudskij http://screencast.com/t/g4thwyYs Там поля только для повнолітніх ) про 1+3 у меня тоже вопрос.

Если сможешь, выйди в слак, объясню, почему у пользователей возникают проблемы.

**Comment by dmitrijzabrudskij** [comment]
у меня в слаке мусора много - пиши в скайп если что

насчет совершеннолетних - таки наша ошибка. любых сожителей можно вписать. просто дети без паспорта и инн будут. и поправлю в бою сегодня

**Comment by katebutenko** [comment]
@dmitrijzabrudskij  ясно, спасибо. Я не знаю твой скайп, добавь меня - foramigos

**Comment by Doxtyp** [comment]
@dmitrijzabrudskij Добрый день!
Как можно узнать состояние заявки на субсидию, оформленную на сайте 02сен2015?
После оформления пришло на почту сообщение: "Ваше звернення щодо отримання субсидії на оплату житлово-комунальних послуг зареєстроване. Ви отримаєте відповідь протягом 20 робочих днів.". С тех пор тишина. Заявку не видно в кабинете. Номера заявки нет. Как быть?

**Comment by dmitrijzabrudskij** [comment]
так а что есть? фио, район?

**Comment by Doxtyp** [comment]
Балакина Полина Наумовна
Жовтневый р-н

**Comment by Doxtyp** [comment]
Балакина Полина Наумовна Жовтневый район проспект Героев, 11/323​

**Comment by dmitrijzabrudskij** [comment]
от нее заявки не было. пусть попробует переподать и напишите мне чтобы я проверил упала ли она

**Comment by Doxtyp** [comment]
dmitrijzabrudskij Здравствуйте!
Еще раз оформил заявку на субсидию №7201725. Проверьте, пожалуйста

**Comment by dmitrijzabrudskij** [comment]
да, эта заявка есть

**Comment by Doxtyp** [comment]
Спасибо! А существует возможность сохранить для себя копию самой заявки?
Она же сохраняется на сервере? Просто,  если соц.службы укажут на
неточности или неполноту каких-либо пунктов, гораздо удобнее будет
устранить эти замечания имея под рукой копию заявки (IMHO)

**Comment by dmitrijzabrudskij** [comment]
редактирование заявок в работе. скоро будет

**Comment by Doxtyp** [comment]
Спасибо за информацию!
Буду ждать

2015-10-09 10:30 GMT+03:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by nika65** [comment]
Создать заявку через выбор банка . Отсутствуют другие банки, в которых у моих родственников счёта и которые могут подтвердить все данные. 
Например добавьте Банк Кредит Днепр
Зарание спасибо за ответ.

**Comment by LamronNu** [comment]
@nika65 
ответила Вам здесь: https://github.com/e-government-ua/iForum/issues/16#issuecomment-147983708

продублирую:
Сейчас в списке только те банки, которые предоставляют такую функцию, т.е. дают возможность "заходить через БанкИД". К сожалению, не все банки "идут на контакт", поэтому не все есть в списке.

Т.е. "добавлять банки" мы не можем, это зависит только от самих банков..

**Comment by Glavspez** [comment]
Добрый день. Заявка на субсидию № 3379800 подана 10.09.2015 г., взята в работу 18.09.2015 г. Прошло уже больше 20 рабочих дней, ответа нет. Куда нужно обращаться?

**Comment by dmitrijzabrudskij** [comment]
добрый день. в какой район какого города?

**Comment by Glavspez** [comment]
Днепропетровск, Ленинский район

**Comment by yarik1983** [comment]
Такая же проблема. 21.09.2015 заявка на субсидию взята в работу и с тех пор ответа нет. Днепропетровск, Ленинский район.

**Comment by dmitrijzabrudskij** [comment]
3379800в работе еще. yarik1983, какой номер у вашей заявки? (или фио от кого подавалась)

**Comment by yarik1983** [comment]
номер заявки  4202273

**Comment by dmitrijzabrudskij** [comment]
тоже в работе

**Comment by skryagaga** [comment]
в поле телефон постоянно выдает ошибку

**Comment by skryagaga** [comment]
ПОМИЛКАSYSTEM_ERR For input string: "067 566 7367"

**Comment by skryagaga** [comment]
кто-то с таким сталкивался? заполнено по форме

**Comment by skryagaga** [comment]
все решилось

**Comment by Doxtyp** [comment]
dmitrijzabrudskij Здравствуйте!
заявка на субсидию №7201725 (Днепропетровск, Жовтневый р-н) "взята в работу" 12,10,2015 и больше никакой информации. Вы можете уточнить статус на текущий момент?

**Comment by dmitrijzabrudskij** [comment]
добрый день
позвоните им, пожалуйста - телефон 056 377-08-37

пс: скоро будем слать телефон каждого района в имейле после подачи заявки
