### ISSUE TITLE
Как редактировать заявку на субсидию?

### ISSUE THREAD

**Issue by gek1401** [e-government-ua/iForum#90]
Добрый день! Я подал заявку на субсидию 9 ноября № 14920718 г.Вольногорск, которая была успешно принята. На следующий день мне звонили из отдела по субсидиям, а так же пришло письмо о том, что необходимо уточнить данные. Не нашёв как делать изменения в заявке, я сделал новую 12 ноября № 16091856. После этого из отдела пришло письмо о том, что надо не создавать новую, а дозаполнить старую. Подскажите как делать редактирование если это возможно или не мучиться собирать документы и идти в отдел по субсидиям.

**Comment by dmitrijzabrudskij** [comment]
добрый день
Вы все правильно сделали - нужно было новую заявку заполнить:) разговаривал сегодня с Вольногорском и объяснил им этот момент. так что все в порядке - новую заявку они возьмут в работу

относительно уточнений - это будет, но через 2-3 недели примерно. пока отлаживаем процесс

**Comment by gek1401** [comment]
Добрый день! 
Спасибо за участие. 
У меня ещё есть несколько вопросов по заполнению: 
1. Если на две предыдущие заявки пришли с замечаниями, то необходимо создать новую с учётом замечаний. 
2. Я проживаю в частном доме поэтому при заполнении указал только те позиции за которые идёт оплата, а в остальные позиции указал "не користуюсь". При разговоре с работником отдела субсидий оказалось что надо заполнять все позиции только в поле с лицевым счётом указывать "нули" (их количество должно совпадать как в лицевых счетах). 
3. Так же от работника отдела прозвучало о том, что необходимо для пенсионером указывать номер пенсионного удостоверения, где его указывать. 
4. Доход от процентов по депозитам указывать или нет, если да то куда или к какой форме. 

17 ноября 2015, 17:48:12, от "dmitrijzabrudskij" < notifications@github.com >: 

добрый день 
Вы все правильно сделали - нужно было новую заявку заполнить:) разговаривал сегодня с Вольногорском и объяснил им этот момент. так что все в порядке - новую заявку они возьмут в работу относительно уточнений - это будет, но через 2-3 недели примерно. пока отлаживаем процесс —

**Comment by dmitrijzabrudskij** [comment]
1. да
2. не нужно. выбирайте "не пользуюсь"
3. не нужно
4. не учитывается в доход, поэтому указывать не нужно

с Вольногорском проведут беседу
