### ISSUE TITLE
Письмо про обработанную заявку пришло без вложения

### ISSUE THREAD

**Issue by lestativa** [e-government-ua/iForum#91]
Добрый день!
Моя заявка на оформление субсидии зарегистрирована 8.11.2005 г. под №14794145. 
11.11.2015 пришел ответ на почту, что моя заявка обработана и "Розмір субсидії вказаний у файлі, який прикріплено до цього листа". Но письмо пришло без вложения. Как быть?
Спасибо!

**Comment by dmitrijzabrudskij** [comment]
добрый день
дайте пожалуйста Вашу почту и название района, куда отправлялась заявка

**Comment by lestativa** [comment]
lestativa@gmail.com
Жовтневый район

**Comment by lestativa** [comment]
Стесняюсь спросить, а дальше-то что?

**Comment by dmitrijzabrudskij** [comment]
точно жовтневый? я не нахожу у них такой заявки

**Comment by dmitrijzabrudskij** [comment]
таки жовтневый. но Кривой Рог
переотправил решение - смотрите почту

**Comment by lestativa** [comment]
Большое спасибо и за решение проблемы, и взагали за Вашу важную и полезную работу! Хай щастить!
