### ISSUE TITLE
kor27

### ISSUE THREAD

**Issue by kor27** [e-government-ua/iForum#92]
Добрый день. В письме в котором указывалось что моя заявка обработана, было написано, что размер субсидии указан в приложенном файле. На самом деле был приложен файл "ук ел.заява.pdf" со статьей "Інтернет допоможе оформити субсидію" из газеты "Урядовий кур'ер". Размера субсидии там не указано. Подскажите мои дальнейшие действия? Где мне ознакомится с размером субсидии? Спасибо.номер заявки 5165501.моя эл. kor.kor210775@yandex.ua

**Comment by kor27** [comment]
Добрый день. В письме в котором указывалось что моя заявка обработана, было написано, что размер субсидии указан в приложенном файле. На самом деле был приложен файл "ук ел.заява.pdf" со статьей "Інтернет допоможе оформити субсидію" из газеты "Урядовий кур'ер". Размера субсидии там не указано. Подскажите мои дальнейшие действия? Где мне ознакомится с размером субсидии? Спасибо.номер заявки 5165501.моя эл. kor.kor210775@yandex.ua

**Comment by dmitrijzabrudskij** [comment]
добрый день
не только у Вас - системное явление для этого района. боремся
