### ISSUE TITLE
Справка о несудимости: заявка обработана успешно, НЕТ ВЛОЖЕНИЯ

### ISSUE THREAD

**Issue by opTEAMist** [e-government-ua/iForum#93]
Приветствую всех разработчиков и пользователей iGov !

Воспользовался сервисом для заказа справки о несудимости для всех членов семьи (3 чел.). Это мой первый опыт с iGov, который в целом могу охарактеризовать как позитивный.

Отчеты об успешной обработке заявок пришли строго в установленный законом срок. В теле каждого письма стандартный текст: "Електронна копія довідки підписана ЕЦП знаходиться в додатку до цього листа", однако ни вложений, ни ссылок на внешний ресурс ни одно из трех полученных писем не содержит. 

Номера заявок 11350837 ; 11454627 ; 11459519 .

Вижу, что многие пользователи в ответ на заявки в другие органы также получали ответы без вложений. Так всё-таки баг или фича?

Владислав

**Comment by kurbpa** [comment]
@opTEAMist 
Добрый день.
К огромному сожалению пока идет реформа по перводу МВД в полицию у коллег из МВД нетактуального ЭЦП для заверения этой справки. Поэтому  временно не отправляют.

**Comment by opTEAMist** [comment]
Благодарю за разъяснение.

Для нашей ситуации вполне хватило бы эл. документа с ЭЦП, поэтому, конечно, немного жаль. Впрочем, признаЮ, что одна поездка в милицию (забрать готовую бумажную справку) вместо как минимум двух, как это было раньше - это, по местным меркам, уже большой шаг вперед. 

Спасибо, и успехов в дальнейшем развитии сервиса!
