### ISSUE TITLE
О субсидиях!

### ISSUE THREAD

**Issue by Ira1954** [e-government-ua/iForum#94]
Заявка на субсидию номер 6551497! Зарегистрирована 05.10.2015! Днепропетровск Бабушкинский район! 16.11.2015 пришел ответ с прикрепленным файлом в котором отсканированный текст газеты Урядовый курьер вместо субсидии! Как это понимать? Спасибо

**Comment by dmitrijzabrudskij** [comment]
массовая ситуация в этом районе, к сожалению:(
разбираемся

**Comment by Ira1954** [comment]
А как должно быть? Обработать в течении 20-ти дней в директивные сроки-нарушено!!! И в любом случае указать конкретные причины в ответе! Наверное эта ситуация скрывается от главы областной администрации, который  многократно в прессе отмечал этот сервис! Если Вас не затруднит, проинформируйте пожалуйста ,к чему привели разбирательства в районе!

**Comment by dmitrijzabrudskij** [comment]
должно быть сканированное решение. тем более оно у них есть в распечатанном виде.
конечно расскажу чем закончилось - ничего ни от кого не скрывается. я больше Вас заинтересован в правильной работе районов по субсидиям - тогда не нужно будет тратить время на разбор подобных ситуаций и заниматься другими  важными услугами, которых хватает

**Comment by Ira1954** [comment]
Большое спасибо! Сегодня пришел документ по субсидии! Хороший сервис!!!!
