### ISSUE TITLE
Заявка на субсидию не меняется статус

### ISSUE THREAD

**Issue by SBORODENKO** [e-government-ua/iForum#95]
Добрый день. Заявка №9954833 прошло 20 рабочих дней, а статус так и остался в состоянии "Заявка подана". Как узнать что с заявкой?

**Comment by dmitrijzabrudskij** [comment]
добрый день. нужно позвонить в район и узнать в каком состоянии. какой это район?
и, как показала практика, в 20 дней (даже рабочих) далеко не всегда укладываются...

**Comment by SBORODENKO** [comment]
Черкасская обл. г Смела

**Comment by SBORODENKO** [comment]
Подскажите пожалуйста по какому телефону можно получить информацию?

**Comment by dmitrijzabrudskij** [comment]
(04733) 4 23 34
или 
(04733) 2 00 60

есть вот такие телефоны
