### ISSUE TITLE
Реєстрація місця проживання дитини до чотирнадцяти років

### ISSUE THREAD

**Issue by sergopal** [e-government-ua/iForum#96]
При заполнении формы "Реєстрація місця проживання дитини до чотирнадцяти років" в опции "Район м. Дніпропетровськ, до якого належить нове місце проживання дитини"  отображен только Бабушкинский район. В остальных районах услуга не работает? Если не работает, то когда запустят все районы, интересует Кировский. Если лаг, то прошу исправить.

**Comment by Koffeek** [comment]
@sergopal 
На данный момент услуга проходит обкатку на Бабушкинском районе. С 1 декабря планируем подключить Кировский, Жовтневый, АНД, Индустриальный и, возможно, остальные районы. Спасибо за отзыв. Извините, за то, что долго не отвечали
