### ISSUE TITLE
Необхідно уточнити дані. Пожалуйста, ответьте!

### ISSUE THREAD

**Issue by nadiarum** [e-government-ua/iForum#98]
Здравствуйте. Подала заявку на субсидию 16408869.
Пришло письмо с текстом "необхідно уточнити дані".
Что это означает? Кто должен уточнять данные? Я? А какие именно данные и каким образом?

**Comment by GrekD** [comment]
@nadiarum
извините за эту недоработку - попала к Вам в тестовом режиме.
Актуален ли еще вопрос?

**Comment by nadiarum** [comment]
Я дозвонилась с тридцать шестого раза до отдела субсидий, где мне сообщили, что субсидия назначена, а подтвердить в электронном виде они не смогли и не могут, потому что сотрудник, который умеет, сейчас в отпуске. Поэтому они мне послали бумажное письмо, которое я еще не читала. Вот.

Отправлено с iPhone

**Comment by GrekD** [comment]
@nadiarum укажите, пожалуйста, город или район на который подавали заявку

**Comment by annastolbova** [comment]
Після останнього коментаря минуло більше 60 днів.
Якщо будуть ще питання по цій темі , прохання відкрити це issue через команду reopen.
Гарного дня.
